### PR TITLE
[squeezebox] Fix notification sometimes playing last playlist item first

### LINKED ISSUE #16367: [squeezebox] Power on for notification sometimes plays parts of current playlist item first
Over the years of using the squeezebox binding, I had some strange experiences when someone rang my doorbell or I wanted to make an announcement in the house. Instead of the announcement or the ringtone, I heard the last played sound of a player.
Since I have a complex rule which syncs players etc., I always blamed that for this annoying bug. But when I had the idea of clearing the playlist before doing announcements, I had a closer look at the implementation of the notification in the player thing.

As it turns out, the culprit is:

https://github.com/openhab/openhab-addons/blob/235abce53136b6a4a1b6b8d60890b917963456e4/bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java#L80-L83

So if the player is switched off, there is somehow still the current playlist item within that player. If you now power on the player, it first plays that and then eventually switches to the notification.

Steps to reproduce:

- play some internet radio stream on a squeezboxplayer
- there is one entry in the playlist
- now stop the squeezebox player via "power off" button in the LMS webUI
- Play a notification sound via rule, i.e. `playSound("your-player-thing", "doorbell.mp3", new PercentType(30))`
- The internetradio stream will be played briefly before the notification! (It sometimes even gets stuck there until the notification timeout occurs and then the notification is fully swallowed)

I have prepared a PR to fix this, as the "send power on" is not necessary for the notification. When we send the command to play our playlist item which contains the notification, it is turned on appropriately, so no need to send that power command first. So if we skip sending it, all works as expected.

=> No more disco in the house in case someone rings the doorbell ;)

### PR DESCRIPTION
**Pull request by t2000**
Fixes #16367

### CODE REVIEW

**Comment by mhilbush** [comment]
Thanks for this change.

I'm curious what you're using as a player. I know that some players (such as piCorePlayer) don't need to be powered on. But I wasn't sure about the original SqueezeBox devices, such as the SqueezeBox Receiver.

Do you think the call to `isPoweredOn` is not needed in `restorePlayerState`? And, if not needed there, should that method and associated attribute be removed completely from `SqueezeBoxPlayerState.java`?

**Comment by t2000** [comment]
I am indeed using software players with piCoreplayer and `squeezeboxlite` binaries.

Unfortunately I do not have a hardware squeezebox device to test :(

I would probably not remove it from `SqueezeBoxPlayerState.java` as it IS a state of the player. In the webUI of the Logitech media Server you can click the "on/off" button wich says "Power:XYZ". So I would keep it in the state, as it reflects the real player's state.

However, I would certainly remove it from the start of a notification as this leads to the undesired behavior of playing something that's still in the playlist from the last powered off moment.

**Comment by mhilbush** [comment]
> Unfortunately I do not have a hardware squeezebox device to test :(

Neither do I. But i'm fine with the change. We'll just need to see if anyone who uses those devices has a problem.

But what about the call to `isPoweredOn` in `restorePlayerState`? Should that also be removed? If we're not sending the power on command, why would we want to send a power off command?

**Comment by t2000** [comment]
> But what about the call to `isPoweredOn` in `restorePlayerState`? Should that also be removed? If we're not sending the power on command, why would we want to send a power off command?

Well, the "playlist play NUMBER` turns the player ON, i.e. the power state changes with that to ON automatically. Stopping it alone does **not** power it OFF. So I would suggest to keep it in there, especially in cases where real devices have to be powered off. What do you think?

**Comment by mhilbush** [comment]
> So I would suggest to keep it in there, especially in cases where real devices have to be powered off. What do you think?

Yes, I think that makes sense.

**Review by mhilbush — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
I can give it a test with Radio/Receiver tonight.

**Review by jlaur — APPROVED** [review]
Thanks for the fix! It works perfectly with Squeezebox Receiver and Radio when they are initially off. After playing the notification, they are automatically turned off again.

**Pull request merged**
