### PR TITLE
[mail] Add support for e-mail headers

### PR DESCRIPTION
**Pull request by andrewfg**
**Background**
Previously e-mails sent by this binding could not be grouped into a "threaded view" in the user's email client, because the binding could not provide an e-mail "Reference" header (which is the key for message threading).

**Solution**
This PR allows one to (optionally) add e-mail headers such as, but not limited to, the "Reference" header.

**Example Rule**
```
rule "Send Mail with a Reference Header"
when
    ...
then
    val mailer = getActions("mail","mail:smtp:xyz")
    mailer.addHeader("Reference", "<unique-thread-identifier>")
    mailer.sendMail("joe@abc.com", "message-subject", "message-text")
end
```
Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Review by martinvw — APPROVED** [review]

**Comment by J-N-K** [comment]
@openhab/add-ons-maintainers I would like to revert this change and replace it with the thread-safe implementation in https://github.com/smarthomej/addons/pull/199/files. Functionally this is equivalent (besides being thread-safe), but it is a breaking change regarding the usage. WDYT?

**Comment by jlaur** [comment]
@J-N-K - I agree. We cannot preserve the current API/usage since it stores state across calls as you mentioned [here](https://github.com/openhab/openhab-addons/pull/11307#issuecomment-939428676). It shouldn't be a big deal since there is a new solution - of course needs to be mentioned in distro notes.

@openhab/add-ons-maintainers - other opinions?

**Comment by andrewfg** [comment]
@J-N-K would your proposed change still support my original use-case (below)? (If so, then I would have no objections..)

```
rule "Send Mail with a Reference Header"
when
    ...
then
    val mailer = getActions("mail","mail:smtp:xyz")
    mailer.addHeader("Reference", "<unique-thread-identifier>")
    mailer.sendMail("joe@abc.com", "message-subject", "message-text")
end
```

**Comment by J-N-K** [comment]
You would have to create a `Map<String,String>` and then use `mail.sendMail("joe@abc.com", "message-subject", "message-text", headers)` but I think that also works for you.

**Comment by andrewfg** [comment]
^
LGTM :)

**Pull request merged**
