### PR TITLE
[shelly] set min value to 1s for updateInterval in config.xml

### PR DESCRIPTION
**Pull request by rose78ch**
https://github.com/openhab/openhab-addons/issues/11892

### CODE REVIEW

**Comment by lolodomo** [comment]
@markus7017 for review. 

I guess polling each second could lead to a lot of network traffic and potential problems (for example if the poll takes more than 1 second).

**Comment by lolodomo** [comment]
By the way, your change does not compile and your PR is not correctly signed.

**Comment by rose78ch** [comment]
> By the way, your change does not compile and your PR is not correctly signed.

How can I do that?

**Comment by rose78ch** [comment]
> @markus7017 for review.
> 
> I guess polling each second could lead to a lot of network traffic and potential problems (for example if the poll takes more than 1 second).

In the mystrom binding the minimum interval is also 1s and I don't have some problems.

**Comment by lolodomo** [comment]
> > @markus7017 for review.
> > I guess polling each second could lead to a lot of network traffic and potential problems (for example if the poll takes more than 1 second).
> 
> In the mystrom binding the minimum interval is also 1s and I don't have some problems with network traffic.

I was just telling that if 10s was chosen, there could be a reason. I have myself no idea if it is reasonable or not, I do not even know/analyze what is done during the poll.
Ideally, we need the comment from the author/maintainer of this binding. That is the reason why I ping him.

**Comment by lolodomo** [comment]
Note that patching the code in GitHub WEB without checking that the code is even compiling (and so of course without any test) is not the minimal quality for PRs expected by the openHAB project.
As you can see, your changes lead to the project no more compiling.

**Pull request closed without merging**
