### PR TITLE
[shelly] update readme for shellyplugs

### PR DESCRIPTION
**Pull request by TimmiORG**
[shelly] Readme update for the Plug-S

Updated the readme file to include the channels available for the Shelly Plug S device.

### CODE REVIEW

**Comment by lolodomo** [comment]
@@markus7017 : is this change OK for you ?

**Comment by wborn** [comment]
Friendly review ping @markus7017

**Comment by jlaur** [comment]
@markus7017 - I saw activity from you today, so will attempt another gentle review ping. :)

**Comment by markus7017** [comment]
Incorporated in a different PR

**Pull request closed without merging**
