### PR TITLE
[powermax] Console command completion

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

Depends on openhab/openhab-core#3111

### CODE REVIEW

**Comment by lolodomo** [comment]
Partial in the context means that it is not yet possible to complete the thing UID required as parameter.
A change must be implemented first in the core framework.

**Comment by lolodomo** [comment]
In fact, everything is there in core framework to retrieve all things. I am going to add completion on the thing UID.

**Comment by lolodomo** [comment]
Full parameters completion is now implemented. PR is ready for review.

**Review by jlaur — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
