### PR TITLE
[lgwebos] Use system properties when available

### LINKED ISSUE #7398: [lgwebos] Thing properties
Some system properties exist and they could be used by the binding rather than defining new specific properties.
Few properties may be useless or even confusing for the final user.
Here are the list of current properties:

- deviceId: OK - we have serialNumber (Thing.PROPERTY_SERIAL_NUMBER) as system property but I am not sure the current deviceId property is really a serial number.
- deviceOS : is it useful ? Its value is "webOS".
- deviceOSVersion / deviceOSReleaseVersion : it is not clear for the final user why several versions are provided. In my case, the first one is "4.1.0" and the second "4.7.1". The second is the nearest to what the TV is showing in menu: 04.71.25. I suggest to keep only the value of the current property deviceOSReleaseVersion and to name it firmwareVersion (system property Thing.PROPERTY_FIRMWARE_VERSION). In case 4.1.0 is a hardware version, we could use hardwareVersion (system property Thing.PROPERTY_HARDWARE_VERSION)
- lastConnected: OK
- modelName: we should use modelId (system property Thing.PROPERTY_MODEL_ID)
- manufacturer: we should use vendor (system property Thing.PROPERTY_VENDOR)

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #7398

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@sprehn : I put "WIP" because I am waiting for your feedback. I am open to keep certain properties I removed in case you think it could be of any help for the user or the maintener.

**Comment by sprehn** [comment]
These are the properties in my case with the latest version.


Name | Value
-- | --
deviceId | 6da62662-1369-a82d-95c7-353c235ed503
deviceOS | webOS
deviceOSReleaseVersion | 2.2.1
deviceOSVersion | 4.1.0
lastConnected | 2020-04-17T18:04:58.133Z
manufacturer | LG Electronics
modelName | LG Smart TV **null**


Notice the null in modelName. this was introduced here:
```
.withProperty(Thing.PROPERTY_MODEL_ID,
                         device.getDetails().getModelDetails().getModelName() + " "
                                 + device.getDetails().getModelDetails().getModelNumber())
```

It should be checked if ModelNumber is set.

These properties are for debugging reasons, so that we can ask users for details in case they report a bug. And to be honest, I have no clue what the difference is between OSVersion and OSReleaseVersion. but I would keep deviceOS, deviceOSReleaseVersion, deviceOSVersion.

I totally fine to use OH Thing Default keys for:
PROPERTY_MODEL_NAME -> Thing.PROPERTY_MODEL_ID
PROPERTY_MANUFACTURER -> Thing.PROPERTY_VENDOR

**Comment by lolodomo** [comment]
Ok, changed.

**Comment by cpmeister** [comment]
Manually checked sign-off

**Pull request merged**
