### PR TITLE
[hue] Fix on startup NPE

### PR DESCRIPTION
**Pull request by DerOetzi**
Fixed NPE reported by @andrewfg 

https://community.openhab.org/t/hue-binding-v2-5-6-snapshot-nullpointerexception-errors-on-startup/100027/5 and #7518

@lolodomo please have look

### CODE REVIEW

**Comment by DerOetzi** [comment]
> LGTM

Sorry can you please review again. Because I have found some unnecessary parameters while investigating on the NPE

**Comment by andrewfg** [comment]
Many thanks. The snapshot distribution is erroring (on openhabian) right now, but I will test it as soon as I do get the new snapshot installed.

**Comment by andrewfg** [comment]
I just updated to openHabian snapshot `openHAB 2.5.6~S139-1 (Build #139)` and I am still seeing a ton of NullPointerEcxeptions on start-up. => Question: _did your "fixes" actually make it into Build 139?_

```
2020-06-07 17:17:58.960 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.hue.internal.handler.HueLightHandler@cf168': null
java.lang.NullPointerException: null
	at org.openhab.binding.hue.internal.handler.HueLightHandler.onLightAdded(HueLightHandler.java:545) ~[?:?]
	at org.openhab.binding.hue.internal.handler.HueBridgeHandler.registerLightStatusListener(HueBridgeHandler.java:815) ~[?:?]
	at org.openhab.binding.hue.internal.handler.HueLightHandler.getHueClient(HueLightHandler.java:433) ~[?:?]
	at org.openhab.binding.hue.internal.handler.HueLightHandler.initializeThing(HueLightHandler.java:147) ~[?:?]
	at org.openhab.binding.hue.internal.handler.HueLightHandler.initialize(HueLightHandler.java:127) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

**Comment by andrewfg** [comment]
Ok. I installed `Build #140` today, and everything is good again :)

**Pull request merged**
