### PR TITLE
[miio] add poweroff properties to zhimi powerstrip

### PR DESCRIPTION
**Pull request by marcelrv**
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by cpmeister** [comment]
you forgot to add `channelType`

**Comment by marcelrv** [comment]
These don't have channel type, unless the channeltype adds info e.g a more elaborate description no sense to add

**Comment by cpmeister** [comment]
But it looks like that is what you did with all other properties...

**Comment by marcelrv** [comment]
In the beginning I used to make channeltypes for each channel.

As I introduced the local files, anyway I can't control if the user uses existing channeltypes or just create new ones, hence nowadays I only make them if there is any additional value to it, stuff that is not in the database, e.g. the description, the <state> details etc)

The other reason is to skip it is that it created sometimes issues when the type of channel changed, (e.g. mode is sometimes a string, sometimes a number) this lead to unexpected issues, which were hard to diagnose.

There is some discussion if the channelTypes are mandatory yes or no, if the outcome of the discussion is that it will be mandatory, I'll change the basichandler to automatically pick a channeltype based on the type field in the database rather than add one for each individually.

**Review by cpmeister — APPROVED** [review]

**Pull request merged**
