### PR TITLE
[jssscripting] Fix JS Quantity to Java QuantityType conversion

### PR DESCRIPTION
**Pull request by florian-h05**
Regression from https://github.com/openhab/openhab-js/pull/312.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jlaur That should fix it. I’ve created it from GitHub web and are not able to test it, so would be great if you could compile and deploy it and test it.

**Comment by jlaur** [comment]
@florian-h05 - thank you! I have now tested the fix, and it works perfectly.

**Comment by florian-h05** [comment]
Fine, then let's merge this.
This should also be backported to 4.1.x

**Comment by jlaur** [comment]
> Fine, then let's merge this.
> This should also be backported to 4.1.x

Yes. Do you want to test this also while waiting for the 4.1.x branch to be created? I only did one basic test by successfully running a rule that was previously broken - and requiring one of the EDS thing actions having `QuantityType` in the method signature.

**Review by jlaur — APPROVED** [review]
LGTM

**Comment by florian-h05** [comment]
> Do you want to test this also while waiting for the 4.1.x branch to be created?

I don’t think that’s necessary.

However I wonder if we should provide a backward compatibility layer so that the conversion still works for older versions of the library. Though I would expect every user that has openhab-js installed manually to upgrade it to the latest version, and as the library had no breaking changes for nearly a year now, nothing should hold back from upgrading to the latest version. You only get plenty of fixes and some new features. 
WDYT?

**Comment by jlaur** [comment]
> However I wonder if we should provide a backward compatibility layer so that the conversion still works for older versions of the library. Though I would expect every user that has openhab-js installed manually to upgrade it to the latest version, and as the library had no breaking changes for nearly a year now, nothing should hold back from upgrading to the latest version. You only get plenty of fixes and some new features.
> WDYT?

I'm not sure it's relevant in 4.1 to older versions of openhab-js than the version bundled with 4.1. I don't know if it it's relevant or even possible to support newer versions of openhab-js in 4.0 (in case of manual upgrade of openhab-js without upgrading to 4.1)?

**Comment by florian-h05** [comment]
> I'm not sure it's relevant in 4.1 to older versions of openhab-js than the version bundled with 4.1.

Not really, there is no reason to not upgrade to the latest openhab-js when moving to openHAB 4.1.

> I don't know if it it's relevant or even possible to support newer versions of openhab-js in 4.0

That’s a good question. openhab-js still works on 4.0, but the automatic type conversion for Quantity will not work for the latest version. 
IMO there is also no reason to not upgrade from 4.0 to 4.1, but it would be possible to modify the type conversion to support old and new versions of openHAB-JS. This fix then could be backported to 4.0.x to make newer openhab-js versions compatible with openHAB 4.0.x, but whether there will be a new 4.0.x release is another question.

Personally, I’d vote no keep this PR as is, and require users to upgrade their manually installed openhab-js to the latest version when moving to openHAB 4.1. For 4.0 users that upgrade to the latest version of the library, I would say, that only the latest openHAB release provides full compatibility with the latest version of the library and they should please upgrade openHAB.

**Pull request merged**
