### PR TITLE
[insteon] Changed singletons to OSGI services

### PR DESCRIPTION
**Pull request by cpmeister**
Also includes other code cleanup and simplification.

### CODE REVIEW

**Comment by robnielsen** [comment]
@cpmeister thanks for making the changes. I'll build and make sure it doesn't break anything this weekend.

**Comment by cpmeister** [comment]
@robnielsen I managed to delete the RequestQueueManager entirely and use a scheduler instead. I attempted to do the same for Poller but that class used scheduling quirks that I don't think would be easy to replicate with a simple scheduler so I left it as is.

The scheduler replacement for RequestQueueManager should be functionally identical but I would greatly appreciate you testing it out to confirm I didn't screw up.

**Comment by robnielsen** [comment]
@cpmeister, I don't understand why RequestQueueManager needs to be replaced. It works and has successfully worked for years (since Oct 11, 2015). I'm all for improving code where beneficial, but I don't see any benefit here. Especially with how fragile the Insteon protocol is. @kaikreuzer what do you think?

The original OH1 code for RequestQueueManager is at https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.insteonplm/src/main/java/org/openhab/binding/insteonplm/internal/device/RequestQueueManager.java

**Comment by robnielsen** [comment]
@cpmeister, these changes didn't work. Did you try to run the code at all? 

```
2020-03-20 06:25:35.826 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] : Constructor with 0 arguments not found. Component will fail.
2020-03-20 06:25:35.843 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] :  Error during instantiation of the implementation object: Constructor not found.
2020-03-20 06:25:36.038 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] :  Error during instantiation of the implementation object: Constructor not found.
2020-03-20 06:25:36.099 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] :  Error during instantiation of the implementation object: Constructor not found.
2020-03-20 06:25:36.141 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] :  Error during instantiation of the implementation object: Constructor not found.
2020-03-20 06:25:36.168 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] :  Error during instantiation of the implementation object: Constructor not found.
2020-03-20 06:25:36.207 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.device.DeviceTypeLoader(284)] :  Error during instantiation of the implementation object: Constructor not found.
2020-03-20 06:25:36.248 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.driver.Poller(286)] : Constructor with 0 arguments not found. Component will fail.
2020-03-20 06:25:36.264 [ERROR] [org.openhab.binding.insteon         ] - bundle org.openhab.binding.insteon:2.5.4.202003201121 (262)[org.openhab.binding.insteon.internal.driver.Poller(286)] :  Error during instantiation of the implementation object: Constructor not found.
```

**Comment by cpmeister** [comment]
Sorry about that, I'm still new to OSGI so didn't know that it required public constructors for its components.
Also don't worry too much removing RequestQueueManager, I can just revert that change if it doesn't work, but I'm pretty confident that it can safely be removed. The reason I want to remove it is because it is trying to implement a behavior that is already available in the standard libraries, and removing that class would be 200 fewer lines of code that needs to maintained.

I understand the perspective of "if it ain't broke don't fix it" but my goal isn't to fix something, but to make the maintenance load lighter.

**Comment by robnielsen** [comment]
Once you revert the changes to RequestQueueManager, and have something to try let me know. BTW, the RequestQueueManager code is rock solid so I'd doubt if it would need any maintenance since it hasn't been touched in 4.5 years.

**Comment by cpmeister** [comment]
Please humor me and test it with RequestQueueManager removed.

**Comment by cpmeister** [comment]
I might revisit this at some point but this isn't that important of a fix right now.

**Pull request closed without merging**
