### PR TITLE
 [openwebnet] 3.3.0 aux beta6 (#11515)

### PR DESCRIPTION
**Pull request by fabgio**
[openwebebnet] fixes after first community testing (#11515). Reference PR #12468

### CODE REVIEW

**Comment by fabgio** [comment]
I created a new brench (beta6) so I made a new PR to review all of the stuff!

**Comment by fabgio** [comment]
Just a Maven question: How can I update artifact's name to include beta[n] postfix?
I have been seeking for a while!
Thanks

**Comment by jlaur** [comment]
@fabgio - is this PR intended to replace #12468, since it includes changes not yet merged from that PR?

**Comment by fabgio** [comment]
Yes exactly

**Comment by jlaur** [comment]
> @jlaur Yes exactly!

Would it be possible for you to add the new commits to the previous branch for that PR and close this PR? There's already an open review, so there's no reason to create a new PR.

**Comment by fabgio** [comment]
Ops I realize i made a mistake! I have to apologize I am new to PRs. For the sake of clarity could I delete this one and resume the old one with new commit and delete this one?

**Comment by jlaur** [comment]
> Ops I realize i made a mistake! I have to apologize I am new to PRs. For the sake of clarity could I delete this one and resume the old one with new commit and delete this one?

That would be preferable for continuity, yes.

**Pull request closed without merging**
