### PR TITLE
[openwebnet] fixing support for central unit

### PR DESCRIPTION
**Pull request by aconte80**
Objective:

Enhance OpenWebNet binding to support thermoregulation with 4/99 zone central unit, e.g. BTicino 3550 model.

Changelog

- fix read setTemp (MANUAL mode) at startup
- fix read mode (OFF/PROTECTION/WEEKLY/SCENARIO/MANUAL) at startup
- fix https://github.com/openhab/openhab-addons/issues/12401
- fix https://github.com/openhab/openhab-addons/issues/12417

It requires Own4j version 0.8.1

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@mvalla ; can you please review?

**Review by mvalla — APPROVED** [review]
LGTM!

**Comment by lolodomo** [comment]
Thank you

**Pull request merged**
