### PR TITLE
[upnpcontrol] Small correction to UpnpControl Binding README.md

### PR DESCRIPTION
**Pull request by jf114**
In the Thing Configuration section starting at Line 40, the code example had parameters transposed versus the preceding description and the true operation of the binding.  The correction puts the parameters included in the original example in the thing that they belong with in Lines 80 and 81.  The optional notification parameters of the renderer were not included originally and I have left it like that.

### CODE REVIEW

**Comment by mherwege** [comment]
@jf114 Thank you for noticing and for the pull request to correct.
It seems not quite right yet. `searchfromroot` should be `searchFromRoot`. I would also add all the other parameters that were missed. `responseTimeout` on both renderer and server, `notificationVolumeAdjustment` and `maxNotificationDuration`. `responseTimeout` is an advanced option, and also missing from the section above describing the configuration options.
Can you add these as well?

**Comment by jf114** [comment]
@mherwege I hope that this second commit has done it (my first contribution here, so please be gentle...)

**Review by mherwege — APPROVED** [review]

**Comment by mherwege** [comment]
This looks fine from a content perspective. Thank you for this first contribution.

**Review by kaikreuzer — APPROVED** [review]
Merging as small patch exception without DCO.

**Pull request merged**
