### PR TITLE
[freeboxos] Enhance state display pattern for uptime

### PR DESCRIPTION
**Pull request by clinique**
Resolves issue #17205

### CODE REVIEW

**Comment by lolodomo** [comment]
Tested, works well.
Maybe we should use "days" rather than "day", WDYT ?

**Comment by maniac103** [comment]
Why not 'd' instead of 'day', assuming state patterns are not translated?

**Comment by lolodomo** [comment]
They are translatable.

But d is a good idea for a shorter value, that is for example "08d 22h 33m 14s".

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
