### PR TITLE
[souliss] Souliss Binding initial contribution

### PR DESCRIPTION
**Pull request by lucacalcaterra**
Souliss Binding
Souliss is a networking framework for Arduino and compatibles boards, and is designed to let you easily build a smart home that is distributed over multiple boards via Ethernet, WiFi, wireless point-to-point and RS485 bus.

Souliss is an open-source and community driven project.
Project: https://github.com/souliss
Wiki: https://github.com/souliss/souliss/wiki

This binding is ready for review.

Also-by: Tonino Fazio fazioa@gmail.com (github: fazioa)
Signed-off-by: Luca Calcaterra calcaterra.luca@gmail.com (github:lucacalcaterra)

Co-Authored-By: Tonino Fazio fazioa@gmail.com (github: fazioa)

### CODE REVIEW

**Comment by lucacalcaterra** [comment]
for maintainers. This is a refactored and optimized  (or so, i hope!) version of binding 1.x of Souliss. We would like to integrate new version in current version of Openhab (3.x). Feel to ask others infos. Thanks ! Luca

**Comment by Hilbrand** [comment]
Thanks for migration this binding. At first sight it looks like your code contains some unrelated merge commits. This makes reviewing harder. Can you remove those commits.

**Comment by lucacalcaterra** [comment]
Damn, I made a mess! I tried to keep the branch clean but couldn't. Now I'm at a standstill. I'll try to recreate the branch

**Comment by Hilbrand** [comment]
You can do a `git rebase -i HEAD~<number>` where number is the number of commits you want to rework. You than get a list with all commits and you can delete the commits that are not yours and save. After that you can do a pull --rebase to update your branch.

**Pull request closed without merging**
