### PR TITLE
Bump Netty version to 4.1.92.Final

### PR DESCRIPTION
**Pull request by Skinah**
update to latest netty to ensure latest improvements and security patches are applied. This also needs this core PR to be merged:

https://github.com/openhab/openhab-core/pull/3577

https://netty.io/news/2023/04/25/4-1-92-Final.html

Signed-off-by: Matthew Skinner <matt@pcmus.com>

### CODE REVIEW

**Review by wborn — APPROVED** [review]

**Review by wborn — CHANGES_REQUESTED** [review]
Please resolve the itest runbundles to fix the build.

**Comment by Skinah** [comment]
Not sure this is something I can fix. It appears to be looking at cache....


[INFO] Testing /home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons/itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun:
[ERROR] Tests not run because project has errors
[ERROR] Error   : io.netty.buffer;version=[4.1.72,4.1.73) Not found in [bnd-cache [/home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/6.4.0/bnd-cache r/w=false], org.openhab.core.bom.runtime-index [/home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/6.4.0/org.openhab.core.bom.runtime-index r/w=false], org.openhab.core.bom.test-index [/home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/6.4.0/org.openhab.core.bom.test-index r/w=false], org.openhab.core.bom.openhab-core-index [/home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/6.4.0/org.openhab.core.bom.openhab-core-index r/w=false], self [/home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/6.4.0/self r/w=false], openHAB Add-ons :: Integration Tests :: MQTT Homie Tests [io.netty.codec-mqtt,io.netty.handler,org.openhab.binding.mqtt,com.fasterxml.jackson.core.jackson-annotations,com.fasterxml.jackson.core.jackson-databind,org.openhab.binding.mqtt.generic,io.dropwizard.metrics.jvm,com.librato.metrics:librato-java,com.zaxxer.HikariCP,com.fasterxml.jackson.core.jackson-core,io.netty.codec-socks,org.apache.commons.codec,io.netty.handler-proxy,org.lastnpe.eea:eea-all,log4j,io.netty.buffer,slf4j.log4j12,org.openhab.binding.mqtt.homie.tests,io.netty.common,slf4j.api,com.h2database.mvstore,io.dropwizard.metrics.core,io.netty.transport,io.netty.codec,io.moquette:moquette-broker,io.netty.transport-native-unix-common,io.netty.resolver,org.openhab.binding.mqtt.homie,com.librato.metrics:metrics-librato,io.netty.transport-native-epoll,io.netty.codec-http r/w=false]]

**Comment by holgerfriedrich** [comment]
@Skinah The versions are hard coded for thee itests in bndrun files. Netty versions are specified in ```itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun```, ```itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun```, ```itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun```.

Did you try to adapt those files?

**Comment by J-N-K** [comment]
Use `-DwithResolver` on the maven command line, never edit `.bndrun` files by hand.

**Comment by holgerfriedrich** [comment]
Thanks, @J-N-K . A bit tricky to get it running..... https://github.com/Skinah/openhab-addons/pull/4

**Review by wborn — APPROVED** [review]
Thanks all!

**Pull request merged**
