### PR TITLE
[homekit] add support for number and dimmer item types to window covering

### PR DESCRIPTION
**Pull request by yfre**
add support for dimmer and number item types for current and target position of a window covering accessory as requested in #9972 

Signed-off-by: Eugen Freiter <freiter@gmx.de>

### CODE REVIEW

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by grzegorz914** [comment]
OH3.1 Build 2184 dosent work:

config items as:
```
Group             gBlind   "Blinds"       		         {homekit = "WindowCovering"}
Number          blind_current_position    (gBlind)       {homekit = "CurrentPosition"}
Dimmer           blind_target_position     (gBlind)       {homekit = "TargetPosition"}
String             blind_position            (gBlind)       {homekit = "PositionState"}
```

get warning
```
2021-02-05 17:52:43.435 [WARN ] [AbstractHomekitPositionAccessoryImpl] - Unsupported item type for characteristic TARGET_POSITION at accessory java.util.concurrent.CompletableFuture@141a48a[Completed normally]. Expected Rollershutter, Dimmer or Number item, got class org.openhab.core.items.GroupItem
2021-02-05 17:52:43.604 [WARN ] [AbstractHomekitPositionAccessoryImpl] - Unsupported item type for characteristic TARGET_POSITION at accessory java.util.concurrent.CompletableFuture@1c13c62[Completed normally]. Expected Rollershutter, Dimmer or Number item, got class org.openhab.core.items.GroupItem
2021-02-05 17:53:02.215 [WARN ] [.accessories.HomekitAccessoryFactory] - Accessory of type WindowCovering must have following characteristics [TARGET_POSITION, CURRENT_POSITION, POSITION_STATE]. Found only [Item:PLC_ParterKotlowniaRoleta1PozycjaZ (Type=DimmerItem, State=0, Label=Kotłownia roleta 1 pozycja zadana, Category=rollershutter, Tags=[Setpoint, Level], Groups=[KotlowniaRoleta1])  HomeKit type:WINDOW_COVERING HomeKit characteristic:TARGET_POSITION]
2021-02-05 17:53:02.217 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PLC_ParterKotlowniaRoleta1PozycjaZ: Missing mandatory characteristics
```

**Comment by yfre** [comment]
> Group             gBlind   "Blinds"       		         {homekit = "WindowCovering"}
> Number          blind_current_position    (gBlind)       {homekit = "CurrentPosition"}
> Dimmer           blind_target_position     (gBlind)       {homekit = "TargetPosition"}
> String             blind_position            (gBlind)       {homekit = "PositionState"}

hm.. strange. just tried the same config and looks good

```
2021-02-05 19:04:42.359 [TRACE] [mekit.internal.HomekitChangeListener] - Item gBlind is a HomeKit accessory of types [WINDOW_COVERING=EMPTY]
2021-02-05 19:04:42.359 [TRACE] [.accessories.HomekitAccessoryFactory] - Constructing gBlind of accessory type WindowCovering
2021-02-05 19:04:42.359 [TRACE] [.accessories.HomekitAccessoryFactory] - Mandatory characteristics for item gBlind characteristics [Item:blind_current_position (Type=NumberItem, State=1.0, Label=null, Category=null, Groups=[gBlind])  HomeKit type:DUMMY HomeKit characteristic:CURRENT_POSITION, Item:blind_position (Type=StringItem, State=NULL, Label=null, Category=null, Groups=[gBlind])  HomeKit type:DUMMY HomeKit characteristic:POSITION_STATE, Item:blind_target_position (Type=DimmerItem, State=NULL, Label=null, Category=null, Groups=[gBlind])  HomeKit type:DUMMY HomeKit characteristic:TARGET_POSITION]
2021-02-05 19:04:42.360 [TRACE] [.accessories.HomekitAccessoryFactory] - Optional characteristics for item gBlind characteristics {}
2021-02-05 19:04:42.360 [TRACE] [thub.hapjava.server.impl.HomekitRoot] - Added accessory java.util.concurrent.CompletableFuture@1bda5638[Completed normally]
2021-02-05 19:04:42.360 [TRACE] [pl.http.impl.NettyHomekitHttpService] - Resetting connections
2021-02-05 19:04:42.361 [TRACE] [mekit.internal.HomekitChangeListener] -  add items blind_target_position
```

**Comment by grzegorz914** [comment]
Please try to add this from GUI

**Comment by grzegorz914** [comment]
Here log after add characteristics to items one by one:

```
2021-02-05 19:39:44.857 [WARN ] [.accessories.HomekitAccessoryFactory] - Accessory of type WindowCovering must have following characteristics [TARGET_POSITION, CURRENT_POSITION, POSITION_STATE]. Found only [Item:PLC_ParterKotlowniaRoleta1Stany (Type=StringItem, State=STOPPED , Label=Kotłownia roleta 1 stany, Category=rollershutter, Tags=[Status], Groups=[KotlowniaRoleta1])  HomeKit type:WINDOW_COVERING HomeKit characteristic:POSITION_STATE]
2021-02-05 19:39:44.861 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PLC_ParterKotlowniaRoleta1Stany: Missing mandatory characteristics
2021-02-05 19:40:32.591 [WARN ] [.accessories.HomekitAccessoryFactory] - Accessory of type WindowCovering must have following characteristics [TARGET_POSITION, CURRENT_POSITION, POSITION_STATE]. Found only [Item:PLC_ParterKotlowniaRoleta1Pozycja (Type=NumberItem, State=0 %, Label=Kotłownia roleta 1 pozycja, Category=rollershutter, Tags=[Level, Point], Groups=[KotlowniaRoleta1])  HomeKit type:WINDOW_COVERING HomeKit characteristic:CURRENT_POSITION]
2021-02-05 19:40:32.594 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PLC_ParterKotlowniaRoleta1Pozycja: Missing mandatory characteristics
2021-02-05 19:41:01.202 [WARN ] [.accessories.HomekitAccessoryFactory] - Accessory of type WindowCovering must have following characteristics [TARGET_POSITION, CURRENT_POSITION, POSITION_STATE]. Found only [Item:PLC_ParterKotlowniaRoleta1PozycjaZ (Type=DimmerItem, State=0, Label=Kotłownia roleta 1 pozycja zadana, Category=rollershutter, Tags=[Setpoint, Level], Groups=[KotlowniaRoleta1])  HomeKit type:WINDOW_COVERING HomeKit characteristic:TARGET_POSITION]
2021-02-05 19:41:01.205 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PLC_ParterKotlowniaRoleta1PozycjaZ: Missing mandatory characteristics
```

**Comment by grzegorz914** [comment]
OK,

partially fixed, my group was set with Members Base Type, removed it and workin but get strange warning DECREASING:
```
2021-02-05 19:52:27.134 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DECREASING  for PositionState characteristic of the item PLC_ParterKotlowniaRoleta1Stany. Expected one of following [DECREASING, INCREASING, STOPPED]. Returning STOPPED.
2021-02-05 19:52:27.140 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DECREASING  for PositionState characteristic of the item PLC_ParterKotlowniaRoleta1Stany. Expected one of following [DECREASING, INCREASING, STOPPED]. Returning STOPPED.
2021-02-05 19:52:27.142 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DECREASING  for PositionState characteristic of the item PLC_ParterKotlowniaRoleta1Stany. Expected one of following [DECREASING, INCREASING, STOPPED]. Returning STOPPED.
```

**Comment by grzegorz914** [comment]
OK,

all fixed in making was space am end of state.

**Pull request merged**
