### PR TITLE
[boschindego] Add localization support for textual states

### LINKED ISSUE #12941: [boschindego] Localization support for textualstate
The channel **textualstate** should support i18n translations. Since state is also available as a numeric value through channel **statecode**, this should not introduce problems for rules/automations.

### PR DESCRIPTION
**Pull request by jlaur**
Add localization support for textual states:
- **Non-redundancy:** State options for **statecode** uses the same texts as **textualstate**.
- **Normalization:** Only unique texts are provided, so duplicate states reference the same text.

Fixes #12941

### CODE REVIEW

**Comment by jlaur** [comment]
I have no idea how to test correct display of state options:

```
	<channel-type id="statecode" advanced="true">
		<item-type>Number</item-type>
		<label>State Code</label>
		<description>API code of the Indego state</description>
		<state readOnly="true">
			<options>
				<option value="0">@text/indego.state.reading-status</option>
(...)
			</options>
		</state>
	</channel-type>
```

I cannot see them anywhere in MainUI or in a sitemap. I believe they were used by PaperUI in the past, but I haven't seen option texts anywhere since then.

**Comment by jlaur** [comment]
I have verified the texts through API Explorer now, looks correct:

```
{
    "parameters": [],
    "parameterGroups": [],
    "description": "API code of the Indego state",
    "label": "State Code",
    "itemType": "Number",
    "kind": "STATE",
    "stateDescription": {
      "readOnly": true,
      "options": [
        {
          "value": "0",
          "label": "Reading status"
        },
        {
          "value": "257",
          "label": "Charging"
        },
```
etc.

So ready for review.

**Comment by jlaur** [comment]
@lolodomo - can I lure you into this small PR? Then will provide Danish translations through Crowdin.

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
