### PR TITLE
[bluetooth.ruuvitag] Correctly parse NA temperature & acceleration

### PR DESCRIPTION
**Pull request by ssalonen**
Fixed by bumping support library fi.tkgwf.ruuvi:ruuvitag-common
https://github.com/Scrin/ruuvitag-common-java/releases/tag/v1.0.2

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

### CODE REVIEW

**Comment by lolodomo** [comment]
Dependency resolution failed during the builds.

**Comment by ssalonen** [comment]
The project does not yet upload releases to Central repository https://github.com/Scrin/ruuvitag-common-java/issues/3

Was the previous release manually uploaded to openhab repositories by a maintainer?

**Comment by ssalonen** [comment]
@lolodomo manual upload to artifactory is needed. This was done last time by @kaikreuzer as mentioned above

**Review by kaikreuzer — APPROVED** [review]
@ssalonen I've uploaded the new version to Artifactory - thanks for the fix.

**Pull request merged**
