### PR TITLE
[shelly] New Shelly Manager (more detailed information, status, integrated firmware upgrade)

### PR DESCRIPTION
**Pull request by markus7017**
This PR brings the Shelly Manager,  check doc/ShellyManager.md
- provides detailed information on your Shellys
- helps to diagnose WiFi issues or device instabilities
- includes some common actions and 
- simplifies firmware updates.

### CODE REVIEW

**Comment by markus7017** [comment]
fyi: We are ready to start review. This Manager has already been hardened, no issues open at the moment

**Comment by markus7017** [comment]
@fwolter How do we want to proceed here? I check the option to remove the Actions and Firmware handling from the Manager to reduce the PR size. This would include base code  and Overview page, but no device actions. This would reduced the PR size apx. by 500-700 lines of code. Would be an option, but I think doesn't move the needle. Nevertheless, I would be open to do that reducing the backlog.

I'm expecting samples of a new device generation next week, which requires integration of a new API (in addition to the existing ones). This will bring additional code so I like to find a way to get as much as possible merged before starting on this enhancement. 

What could be the best compromise with regards to the backlog on your side?

**Comment by fwolter** [comment]
Do you want to remove the Actions and Firmware handling from the code entirely or only from this PR? If the latter, it makes no difference from my POV.

If your are blocked by anything, you can base a PR on another PR and add the "awaiting other PR" label.

**Comment by markus7017** [comment]
@fwolter ok, was just a thought to make it easier for you. What time could I expect for someone to start the review here?

**Comment by fwolter** [comment]
Could be a few days or weeks.

**Comment by markus7017** [comment]
@openhab/add-ons-maintainers Can someone support here and start review of the PR. Otherwise, this will get bigger and bigger while extending functionality and I don't want to create more (multiple PRs in parallel are not easy to handle within the same project)

**Review by kaikreuzer — APPROVED** [review]
Lgtm, thanks.
You are doing massive developments on that binding, wow.
One wish that you might want to keep in mind for future refactorings: Try to avoid creating threads yourself, but rather use either existing or dedicated thread pools.

**Pull request merged**
