### PR TITLE
[lgwebos] Improving TV shutdown detection

### PR DESCRIPTION
**Pull request by sprehn**
This is a small improvement to leverage upnp goodbye broadcast to detect that the TV was turned off by the remote control.  In some cases it takes up to a minute after the TV went black until the os fully shuts down in the background and closes the websocket connection. This change improves the speed of shutdown detection for those users who's network setup allows upnp discovery.

### CODE REVIEW

**Comment by lolodomo** [comment]
Why not simply implement DiscoveryListener on your thing handler and do something in thingRemoved? 
Your change would create a hard dependency on JUPnP.

**Comment by sprehn** [comment]
Hi, 

there is already a dependency to JUpnp for thing discovery in UpnpDiscoveryParticipant and in LGWebOSUpnpDiscoverySearch.

The binding detects wether the TV is online or offline via the status of the websocket connection.

However, these TV don't fully shut down immediatly, when they are turned off via remote. The screen goes dark, but in the background the system shuts down, which takes some time.

The API does signal that the system is going down through any other known mechanism. 
But via UPNP it does send the good-bye broad cast.

A while later it will close the websocket connection. That is when the Thing handler detects it in any case and updates the power channel to off.

**Comment by lolodomo** [comment]
What I tries to say is that your classes LGWebOSUpnpDiscoveryParticipant and LGWebOSUpnpDiscoverySearch already handle a very frequent refresh of the thing discovery (through UPnP search). What you could do is just be notified in your thing handler of any change by the discovery stuff. If you catch the thing removal from the discovery stuff, you can do what you want on this thing.

**Comment by lolodomo** [comment]
Addtionally, I have a question. Why the LG binding needs to force an UPnP scan every 10s ?
Why not letting JUPnP discovers UPnP devices like in any other bindings using JUPnP ?

**Comment by sprehn** [comment]
The explanation is in the JavaDoc of LGWebOSUpnpDiscoverySearch: 
"WebOS TV does not automatically show up by the normal background scans, as it does not respond to openHABs generic search request. A special ssdp search request for lge-com:service:webos-second-screen:1 is required. This component sends this ssdp search request."
The actual capture of the response happens the normal way via LGWebOSUpnpDiscoveryParticipant.

I am trying to understand your comments on how to receiving notifications on thing handler, but don't understand it yet. Could you direct me to an example in one of the other binding, maybe?

Please note, in an older connectsdk based version of the binding everything relied on upnp discovery, but it turned out it did not working for all users. Therefore, this version only relies on pure ability to connect to the TV over network.  Upnp discovery is only an optional feature.

**Comment by lolodomo** [comment]
You have to llok for DiscoveryListener. This listener is implemented by few thing handlers like for exemple in the IPP binding:
https://github.com/openhab/openhab-addons/blob/127f05d7cbb865ae2f7a939c761707f0479d5143/bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/handler/IppPrinterHandler.java#L49
or in the SamsungTV binding:
https://github.com/openhab/openhab-addons/blob/127f05d7cbb865ae2f7a939c761707f0479d5143/bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java#L67

Your thing handler will then be notified of all discovery changes through the methods thingDiscovered and thingRemoved.

**Comment by lolodomo** [comment]
> The explanation is in the JavaDoc of LGWebOSUpnpDiscoverySearch:
> "WebOS TV does not automatically show up by the normal background scans, as it does not respond to openHABs generic search request. A special ssdp search request for lge-com:service:webos-second-screen:1 is required. This component sends this ssdp search request."
> The actual capture of the response happens the normal way via LGWebOSUpnpDiscoveryParticipant.

Ok, thank you for the explanation.
It would have better to add a method in the core framework for that.

**Comment by sprehn** [comment]
> It would have better to add a method in the core framework for that.
Would happily rework the binding if there is a more elegant solution offered in the core, like adding the ssdp search request so some list etc.

**Comment by sprehn** [comment]
I tried DiscoveryListener and it definitely gets called when this thing is found, however, thingRemoved does not get called when the TV shuts down. 
Unfortunately the method using the detector class also stopped working. I will close this PR until my investigation finishes.

**Comment by sprehn** [comment]
Finished my experiments for today:
I turned off the tv via remote control. When TV shuts down, it turns of the onkyo receiver via ARC.
DiscoveryLIstener thingRemoved gets immediately called for UID of Onkyo receiver at  2020-02-25 00:02:40.657
Shutdown detector implementation detects it as well only two seconds later.
24seconds later we see ShutdownDetector and DiscoveryListener being triggered, alongside with the disconnect from the websocket.

```
2020-02-25 00:02:40.657 [DEBUG] [ebos.internal.handler.LGWebOSHandler] - thingRemoved: onkyo:TX-NR626:9fb0264c-8326-4cb9-e02f-4c0983b98a33
2020-02-25 00:02:42.494 [DEBUG] [iscovery.LGWebOSUpnpShutdownDetector] - Detected device shutdown: 192.168.2.119
2020-02-25 00:03:06.445 [DEBUG] [very.LGWebOSUpnpDiscoveryParticipant] - Found LG WebOS TV: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:6da62662-1369-a82d-95c7-353c235ed503, Descriptor: http://192.168.2.119:1794/, Root: true
2020-02-25 00:03:06.446 [DEBUG] [iscovery.LGWebOSUpnpShutdownDetector] - Detected device shutdown: 192.168.2.119
2020-02-25 00:03:06.446 [DEBUG] [ebos.internal.handler.LGWebOSHandler] - thingRemoved: lgwebos:WebOSTV:6da62662-1369-a82d-95c7-353c235ed503
2020-02-25 00:03:06.489 [DEBUG] [bos.internal.handler.LGWebOSTVSocket] - WebSocket Closed - Code: 1001, Reason: server shutting down
```


Another interesting observation is, that the custom search ssdp request may not be required anymore. Will continue the investigation in a few days.

**Pull request closed without merging**
