### PR TITLE
[deconz] improve lastSeen channel, add reachable status, fixes

### LINKED ISSUE #8181: [deconz] thing status for onofflight type is not reported
With the latest version of deconz addon the thing status for lights is not reported.

### PR DESCRIPTION
**Pull request by J-N-K**
- add missing debug messages and remove unnecessary debugging
- allow disabling of lastseen polling (see #7992)
- add reachable status to light things (fixes #8181)

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Either none of my devices or my deconz firmware is not supporting `lastSeen`. IMO the channel should be added dynamically only if supported.

**Comment by stefanuytterhoeven** [comment]
About : polling LastSeen status deconz.
is it in seconds, minutes,??? Is it possible to add this to the parameter description?

**Comment by J-N-K** [comment]
The unit should be displayed in the UI and is mentioned in the documentation. It is minutes.

**Comment by stefanuytterhoeven** [comment]
I see this in the paperUI:
"Interval to poll the deCONZ Gateway for this sensor's "lastSeen" channel. Polling is disabled when set to 0."
But, you are right. I found it in the docs too now. Would be nice if it was also mentioned in the parameter description.
Anyway, thanks for you VERY QUICK response!  :)

**Pull request merged**
