### PR TITLE
[net][WIP] Network Protocol Binding initial contribution

### PR DESCRIPTION
**Pull request by paulianttila**
Adding this WIP binding here for transparency to avoid any duplicate work.

Net binding provides features to receive data via network protocols like UDP, TCP and HTTP.

### CODE REVIEW

**Comment by davidgraeff** [comment]
#4342

**Comment by paulianttila** [comment]
@davidgraeff, This binding provides UDP, TCP and HTTP server functionality, not HTTP client like you linked binding. This binding also provide data parser thing which can be used to parse e.g. binary data to channels. Data parser thing can be used via UDP, TCP or HTTP bridges or as a standalone thing where data can be injected by the rules action.

**Comment by J-N-K** [comment]
@paulianttila what's the status here?

**Comment by Hilbrand** [comment]
Closing due to long time no activity. If you still want this binding added feel free to reopen or discuss the best way to proceed.

**Pull request closed without merging**
