### PR TITLE
Typos a/an

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by fwolter** [comment]
Thank you for this PR! Catching also things like "a {@link AsynchronousSocketChannel}" looks like a bit more sophisticated script. I guess you didn't do that by hand...?

**Comment by dilyanpalauzov** [comment]
I found the places with `git grep` and then changed the files by hand.

**Review by fwolter — APPROVED** [review]
Thanks, good work!

**Comment by fwolter** [comment]
There's a formatting error due to a line, which became one character longer. Can you run `mvn spotless:apply`?

**Review by wborn — APPROVED** [review]

**Pull request merged**
