### PR TITLE
[avmfritz] Fix wrong system channel types

### LINKED ISSUE #15155: Fritz!DECT200/210 Wall Plugs shown unknown after OH 4.0.0M3 update
All DECT Devices where working well in OH 3.4.4. After Upgrade to OH 4.0.0M3 some of the DECT 200 / DECT 210 Wallplugs are shown "Unknown" instead of Online. See [https://community.openhab.org/t/avm-dect-200-wallplugs-not-working-in-oh4-0-0-m3/147512/28](https://community.openhab.org/t/avm-dect-200-wallplugs-not-working-in-oh4-0-0-m3/147512/28) for details
 AVM Fritz!Box Binding

Screenshots shows one "Online" and the other wallplug "Unknown":
image

In summary 4 of 7 are unknown.
I tried removing and adding again the Devices, Removing and adding again the Fritzbox and new installation of binding.
It always results in 4 unknown and 3 online Fritz DECT 200 Things.

I made the update twice on 2 different systems. Always the same.

If you need further informations, you can contact me anytime.

## Expected Behavior

All DECT200/210 Devices should be online, as in OH 3.4.4 version
## Steps to Reproduce (for Bugs)

1. Update from OH 3.4.4 to 4.0.0M3
2. Check DECT200/210 in MainUI

## Context
Update to OH 4.0.0 leads to non functional AVM Fritz!DECT 200 and 210 Devices

## Your Environment

* Version used:Openhab 4.0.0M3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): see below
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
```
openhabian@oh40test:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Linux oh40test 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Raspbian-1deb11u1rpt1)
OpenJDK Client VM (build 17.0.6+10-Raspbian-1deb11u1rpt1, mixed mode, emulated-client)
```

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #15155

### CODE REVIEW

**Comment by jlaur** [comment]
For reference, regression of #14587.

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by helmar74** [comment]
Hi, is there any possibility to test it upfront or do I have to wait until OH 4.0.0 Milestone 5?

**Comment by J-N-K** [comment]
Use the snapshot

**Pull request merged**
