### PR TITLE
[influxdb] Treat a stored 1 AND 1.0 as true

### LINKED ISSUE #9455: [influxdb] historic states of switch items are always OFF with influxdb v1
With an influxdb v1 database, OH3 always read historical historical state of switch items as `OFF`. Yet, values are well stored in the database (can be seen with grafana). 
These community posts are related to this problem:
  - https://community.openhab.org/t/oh3-restoreonstartup-not-working/110592
  - https://community.openhab.org/t/oh3-graph-of-switch-item/109811.
  - https://community.openhab.org/t/oh3-rule-check-in-a-rule-if-item-was-on-in-past-30-minutes/110567

### PR DESCRIPTION
**Pull request by t2000**
Fixes #9455

Signed-off-by: Stefan Triller <github@stefantriller.de>

### CODE REVIEW

**Comment by t2000** [comment]
close and re-open to trigger rebuild

**Review by lujop — CHANGES_REQUESTED** [review]
It seems good to me. But can you add that case in `InfluxDBStateConvertUtilsTest`

**Comment by t2000** [comment]
Of course, sure. I have added the test case. Thanks for the review.

**Review by lujop — APPROVED** [review]

**Review by wborn — APPROVED** [review]
Thank you!

**Pull request merged**
