### PR TITLE
[androidtv] Improve documentation with hint and potential troubleshooting

### PR DESCRIPTION
**Pull request by Boldfor**

### CODE REVIEW

**Comment by morph166955** [comment]
I'm ok with the change, but please fix the PR failure.

**Comment by Boldfor** [comment]
> I'm ok with the change, but please fix the PR failure.

Thanks for the reply, and apologies for causing extra work with the failed check.

Do you know how I can fix this error?

**Review by lsiepel — APPROVED** [review]
Thanks for improving the docs!

As it is a small documentation fix i applied the small patch exception, but you might want to look into your sign-off. We have a real name policy.
For reference: https://www.openhab.org/docs/developer/contributing.html#sign-your-work

**Comment by Boldfor** [comment]
@lsiepel thabks fircthe explanation and for making an exception.

**Pull request merged**
