### PR TITLE
[velux] back port of #8520 & #8673 bug fixes from OH3 to OH2.5.x

### PR DESCRIPTION
**Pull request by andrewfg**
This is a back port of the bug fixes in PR #8520 and PR #8673 from OH v3.0.0 back to the v2.5.x bug fix branch

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by andrewfg** [comment]
Back ported to #8702

**Review by fwolter — APPROVED** [review]

**Comment by kaikreuzer** [comment]
@fwolter Please also set the 2.5.10 milestone for such PRs - thanks!

**Comment by kaikreuzer** [comment]
@andrewfg The PR title is what will appear in the 2.5.10 release notes. "back port of..." is not suitable for that.
Could you please come up with a snappy title that best describes the fix?

**Comment by andrewfg** [comment]
@kaikreuzer / @fwolter - this PR was included in the v2.5.10 release alright -- **EXCEPT** that on `openhab.org` the revised `ReadMe.md` page has the v1 flag on it (see screenshot) _=> must I do something special to force the v2 flag to show?_

image

**Pull request merged**
