### PR TITLE
[infrastructure] enable external null-annotations

### PR DESCRIPTION
**Pull request by J-N-K**
This enables lastNPE.org's external annotations to the JDK. 

There is stilla lot of annotations missing, but the wrong null-warnings on `Map.get()` and the errors on `Optional.ofNullable()` should no longer occur and we can stop working around perfectly valid code just because our null annotations don't allow it. 

We can decide later to add additional annotations (either by adding a new artifact e.g. to the code-analysis or by providing PR to lastnpe and improve the artifact we have now).

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by fwolter** [comment]
I'd love to see this integrated rather sooner than later, but I don't feel confident to merge into `2.5.x` as this might be a new feature?

**Comment by wborn** [comment]
Thanks for looking into this. We also have https://github.com/openhab/openhab-core/issues/888 for this (with bounty). 
If builds succeed and it doesn't cause issues in IDEs I don't see any reason to wait with merging this. :smile:
Those annotations are only used at compile time and not runtime so it should only impact developers.

**Comment by J-N-K** [comment]
After reading the issue mentioned by @wborn: I have no idea if this works in Eclipse. I don't use Eclipse. BTW, the `Map.get` implementation in lastNPE is wrong. So maybe we should move to our own set of EEA. What do you think is a good place for that?

**Comment by martinvw** [comment]
What is wrong about map.get is there an issue about it?

**Comment by J-N-K** [comment]
Map.get can return null. Without EEA a null-check after Map.get is identified as „dead code“ and produces a warning. This is obviously wrong and can only be worked around by adding @Nullable to the value-part of the map declaration (which is also wrong in most cases).

Unfortunately the definition of Map.get in lastNPE EEA also indicates that Map.get return a non-null value.

**Comment by wborn** [comment]
I think it makes sense to have a new project for this e.g. openhab-eea see my https://github.com/openhab/openhab-core/issues/888#issuecomment-612386177.

> Unfortunately the definition of Map.get in lastNPE EEA also indicates that Map.get return a non-null value.

Did you also try building your own version? The last release is 4y old and that method definition did get updated meanwhile (https://github.com/lastnpe/eclipse-null-eea-augments/pull/26).

**Comment by kaikreuzer** [comment]
> Did you also try building your own version?

No need to build your own - I am committer on the project, so simply create a PR and we can look into building a new official release. If you fancy to review any of the open PRs, also feel free to do so, if they are helpful 😎 .

**Comment by J-N-K** [comment]
Perfect!

**Comment by kaikreuzer** [comment]
lastnpe is a bit in a deadlock, though. There isn't a concept of supporting different jvm/library versions and the current code is targeting Java 8. For us it would probably very helpful to get https://github.com/lastnpe/eclipse-null-eea-augments/pull/85 merged, which brings JDK 11 support. I don't really have time to look into that project and get obstacles solved there - I have a million things with higher prio right now for OH3... To move forward with this, you'd therefore have to prepare well-thought-through PRs that are easy to understand and merge for me without diving into the bloody details :-/

**Comment by vorburger** [comment]
@J-N-K if you are motivated to drive http://www.lastNPE.org further than the current set of committers have time for (including myself; I initiated that project, but have since sailed on to very different lands..), we would be happy to promote you to commiter and new maintainer! :smiling_imp: https://github.com/lastnpe/eclipse-null-eea-augments#contribute suggests 3 PRs, but we can make that 2... :smile_cat:

**Comment by kaikreuzer** [comment]
@vorburger Being a maintainer does not help much as long as we don't have any other maintainer that does a peer review of any PR. And here at openHAB we are very much against self-merged PRs from maintainers 😎 .

**Comment by J-N-K** [comment]
@vorburger @kaikreuzer I reviewed the large (and IMO most important PR) https://github.com/lastnpe/eclipse-null-eea-augments/pull/85. After that is merged I would really like to see a new release so we have a good base to start with here.

**Comment by vorburger** [comment]
https://github.com/lastnpe/eclipse-null-eea-augments/issues/91

**Pull request closed without merging**
