### PR TITLE
Added support for publishing ChannelDescriptionChangedEvents

### PR DESCRIPTION
**Pull request by lolodomo**
For the bindings homeconnect, lgwebos, netatmo, remoteopenhab, rotel,
somfytahoma, sonos and sonyprojector

Depends on openhab/openhab-core#1505

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by octa22 — APPROVED** [review]
[somfytahoma] LGTM

**Comment by lolodomo** [comment]
Depening PR in core repo is now merged. So we are ready to merge this one.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Comment by lolodomo** [comment]
@kaikreuzer : if you can merge this one before the build of the coming night, this will simplify my life tomorrow morning ;)

**Comment by kaikreuzer** [comment]
Alright, let's merge and make your life a bit more enjoyable tomorrow morning 😉 .

**Pull request merged**
