### PR TITLE
[mercedesme] bugfix websocket exception after sending command

### LINKED ISSUE #16932: [mercedesme] Socket error if command state is *unrecognized*
If command is send to vehicle via `handleCommand` and the proto state isn't available yet an `IllegalArgumentException` is thrown. 
This is currently not catched and causes a Websocket error which is reflected in the thing status.

Thing is recovering so no blocker, but Exception handling needs to be introduced.

### PR DESCRIPTION
**Pull request by weymann**
fixes #16932

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Comment by lolodomo** [comment]
@lsiepel : please stop merging while the milestone build is in progress.
@kaikreuzer : probably something to check before releasing.

**Comment by lsiepel** [comment]
> @lsiepel : please stop merging while the milestone build is in progress. Kai will tell us when the build is finished and so when we can merge again. @kaikreuzer : probably something to check if this PR is part of the milestone or not.

Where can I see this?

**Comment by lolodomo** [comment]
> Where can I see this?

We have a thread to coordinate the releases on the community forum. The last time, someone asked to add you, maybe it was not done :(

**Comment by lsiepel** [comment]
> > Where can I see this?
> 
> We have a thread to coordinate the releases on the community forum. The last time, someone asked to add you, maybe it was not done :( I ask again, this will be very important during the coming week.

Can you send me the link?

**Comment by lolodomo** [comment]
I just sent you an invite.

**Comment by kaikreuzer** [comment]
> @kaikreuzer : probably something to check if this PR is part of the milestone or not.

Checked, it is not part of the milestone build. I'll make sure that it is also excluded from the release notes.

**Pull request merged**
