### PR TITLE
[openweathermap] Added new supported languages

### LINKED ISSUE #9695: [OpenWeatherMap] OpenWeatherMap Binding language DA missing
According to the OpenWeatherMap, the language can be set do Danish (da), but the binding cant handle that

https://openweathermap.org/current#multi

### PR DESCRIPTION
**Pull request by cweitkamp**
- Added new supported languages

Closes #9695

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Review by Hilbrand — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Of course, you checked that they are available for the API ?

**Comment by cweitkamp** [comment]
No, I did not. I copied them from https://openweathermap.org/current#multi. And I have to trust it what they are publishing.

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Ok, that is what I mean. Perfect.

**Pull request merged**
