### PR TITLE
Fix BaseThingHandler.initialize() deprecations

### PR DESCRIPTION
**Pull request by wborn**
Related to https://github.com/openhab/openhab-core/pull/1665

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

Btw, do you have any suggestion what we shall do wrt Travis? Our build now always exceeds the timeout, so I guess we should reduce it in some way, e.g. by disabling the tests on the full build, wdyt?

**Comment by wborn** [comment]
The last time we hit the timeout (60 minutes?) I asked Travis CI if they could increase it for this project which they did. But even if they would increase it, builds still takes a lot of time (similar to Jenkins) so it does  not result in fast feedback.

The issue with disabling tests is that Jenkins also doesn't run them so they would then only run in the single add-on Travis builds.

We could also see how well a parallel build works although the output is less easy to debug and because of the increased load, timing sensitive tests are more likely to fail. I use the parallel builds myself all the time nowadays.

Another way around the timeout could be to split up the build using a matrix and build stages so Travis would build a subset of the projects in different build jobs which are all smaller than the timeout.

**Comment by kaikreuzer** [comment]
> The issue with disabling tests is that Jenkins also doesn't run them

Maybe we should enable them on Jenkins then? Or did we run into memory issues there? I actually do not remember the details anymore, but in theory, having a single PR build only would be neat.

**Comment by wborn** [comment]
We've already fixed many deprecations but according to the [Deprecated API](https://next.openhab.org/javadoc/latest/deprecated-list.html) list there are still a few more to go.

**Comment by wborn** [comment]
Building with tests was probably removed from Jenkins because builds took too long. They take even more time now (3+ hours) so that will only increase with tests enabled. If Jenkins does the partial or full build depending on the PR content it would be fast most of the time and there would be no need for Travis.

Throwing in more hardware will probably not help much to keep build times low with a full build unless it would be a parallel build. Those can make good use of extra cores. :-)

**Comment by kaikreuzer** [comment]
I switched to parallel build a few days ago and it brought down our build time to <50 minutes: https://ci.openhab.org/view/Pull%20Request%20Builds/job/PR-openHAB-Addons/buildTimeTrend
We could possibly think about activating tests on it as well...

>  If Jenkins does the partial or full build depending on the PR content 

If you'd want to give that a try on Jenkins, feel free! Just set up a separate build plan for testing it and we can see how well that works.

**Pull request merged**
