### PR TITLE
[lifx] Set tagged flag accordingly for unicast and broadcast messages

### PR DESCRIPTION
**Pull request by paulianttila**
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

### CODE REVIEW

**Comment by paulianttila** [comment]
Fix #13682

**Comment by lolodomo** [comment]
@wborn : as the maintainer of this binding, you are welcome for review that fix.

**Comment by wborn** [comment]
I will have a look soon. :slightly_smiling_face:

**Comment by wborn** [comment]
Hi @paulianttila, do I understand correctly that the light does initially go ONLINE but due to the short power interruption stops responding to `GetServiceRequest` ? Is it also reproducible by manually toggling power on a light or would that cause the light to restart properly?

**Comment by paulianttila** [comment]
@wborn in fact, light doesn't go to ONLINE state after lifx binding start in normal ciscumstances either (not power break situation). I haven't recognise that so far as it haven't cause any issue for me. The reason is that lifx lights (which I have) doesn't 'never' response to unicast GetServiceRequests. 

Binding send unicast GetServiceRequests also during start in LifxLightCommunicationHandler, but there is no response for that either, so maybe that should be changed as well.

Here are the test result with two different bulb versions which I have; LIFX A19 and LIFX Color 1000. 

Full log with unmodified lifx binding [lifx-org.log](https://github.com/openhab/openhab-addons/files/10146064/lifx-org.log)

Full log with modified lifx binding which sent both GetServiceRequests and GetEchoRequest in LifxLightOnlineStateUpdater (also trace logs 'Channel is ready for reading' and 'No datagram is available' was removed in the test version). [lifx-mod.log](https://github.com/openhab/openhab-addons/files/10146072/lifx-mod.log)

Lifx [documents](https://lan.developer.lifx.com/docs/querying-the-device-for-data#discovery) says that GetService is typically used for broadcast, so maybe intentation was not even use the message for unicast.

**Comment by wborn** [comment]
Thanks for the info @paulianttila. I tried to reproduce the issue in a VM so openHAB is in its own subnet to be sure broadcasts don't work. I was unable to reproduce your issue a couple of days ago like this and all seemed fine just like when I implemented the unicast.

So I thought let's try to reproduce it with a Color 1000 which I also have. However when I tried today all the previously configured lights were offline after starting openHAB in the VM. It seems that when you first add the lights by IP they are online... but if you then restart the LIFX bundle the lights remain offline. :slightly_frowning_face:

I'll have a look at the code why this is. Are they online for you too after first adding them?

**Comment by paulianttila** [comment]
> Are they online for you too after first adding them?

No, thing stays offline state also when add it. But if you bind any channels from the thing, then state immediately changes to online state.

**Comment by wborn** [comment]
>  Did you use files or UI for your tests?

So far I've tested by adding things using the UI.

**Comment by paulianttila** [comment]
@wborn I think I found the root cause. Reason why bulb doesn't response to unicast GetServiceRequest is the fact that `tagged` flag is not correctly set.

Lifx [document](https://lan.developer.lifx.com/docs/packet-contents) states following

> The tagged field is a boolean flag that indicates whether the Frame Address target field is being used to address an individual device or all devices. When you broadcast a message to the network (i.e. broadcasting a [GetService (2)](https://lan.developer.lifx.com/docs/querying-the-device-for-data#getservic--e-packet-2) for discovery) you should set this field to 1 and for all other messages you should set this to 0.

Binding use value 1 also for unicast requests. I changed sendPacket methods to set the tagged flag accordingly and now my bulbs response to  unicast GetServiceRequests.

**Comment by wborn** [comment]
The fix works fine for me too! :+1:

I think it is better to also remove the calls to `setTagged` from the Packets because the value will always be overwritten with these changes. I've created https://github.com/paulianttila/openhab-addons/pull/3 for that.

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
