### PR TITLE
[tesla] extend docu on 'softwareupdateversion', this can hold map updates too

### PR DESCRIPTION
**Pull request by hakan42**
Slight docu update, yesterday I got an software update notification and saw in the logs that this was caused by a map update.

### CODE REVIEW

**Comment by lsiepel** [comment]
In that case `softwareupdateavailable` should also have the map addition.

**Comment by hakan42** [comment]
How would you do that? Rename the channel as well or just amend the description in the channels.xml file?

Suggestions welcome 😁

**Comment by lsiepel** [comment]
> How would you do that? Rename the channel as well or just amend the description in the channels.xml file?
> 
> Suggestions welcome 😁

Just adapt the documentation, luckily the channel label/description is 'generic' software so both car and map update will fit.

**Comment by hakan42** [comment]
Done, could you please give this another view?

**Review by lsiepel — APPROVED** [review]
LGTM

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@kgoderis as code maintainer or @kaikreuzer : does it look good to you ?

**Pull request merged**
