### PR TITLE
[remoteopenhab] Listen to the new ChannelDescriptionChangedEvent even…

### PR DESCRIPTION
**Pull request by lolodomo**
…ts to update dynamic state/command options

Also handle dynamic command options

Depends on openhab/openhab-core#1505

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
I was able to test the handling of the new event in the remote openHAB binding. I have now something working.
The problem is that now we have a general problem with state options no more updated in UI. So I let the PR in "work in progress" until this is fixed. I hope this is only because UIs were not yet recompiled.

**Comment by lolodomo** [comment]
IMHO, this PR is now ready for review. I was not able to see the changes in UIs due to the bug I just discovered in core  framework (openhab/openhab-core#2409) but I was able to see the coming event received and correctly handled by the binding.

Regarding the command description provider I added, this was not tested because we have not a lot of bindings using this feature and no one I am using myself. But it should be correctly handled too.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Comment by lolodomo** [comment]
With the bug in the core framework now fixed, I was able to do even more tests, meaning checking directly impact in UI, and I can confirm that it works perfectly.

**Pull request merged**
