### PR TITLE
[max] Remove org.apache.commons

### PR DESCRIPTION
**Pull request by lsiepel**
- Remove dependency on apache.commons

While some unittests have been provided, not everything is tested, so minor refactoring from code perspective.

Test jar 4.1.0 : https://1drv.ms/u/s!AnMcxmvEeupwjq5YgHLYUNfUqbM3ZQ?e=2oAfZ0

### CODE REVIEW

**Comment by lsiepel** [comment]
@marcelrv are you able to review?

**Comment by lsiepel** [comment]
@marcelrv Gentle ping

**Comment by marcelrv** [comment]
@lsiepel sorry I totally missed your earlier inclusion.

I don't see on short notice possibilities to do functional test as I'm redoing my heating and currently don't have the Max operational.

Looking at the code I don't see obvious flaws, so if the tests are passed as well I recommend indeed to merge it

**Comment by marcelrv** [comment]
LGTM

**Comment by lsiepel** [comment]
@jlaur can we get this merged before the next milestone?

**Comment by jlaur** [comment]
> can we get this merged before the next milestone?

I don't think I have reviewed this one, unfortunately I don't have time today. Maybe some other @openhab/add-ons-maintainers can help.

**Comment by kaikreuzer** [comment]
@lsiepel As we meanwhile have a `StringUtils` class in core, should this new method maybe added there?

**Comment by lsiepel** [comment]
@jlaur can we get this merged?

**Review by marcelrv — APPROVED** [review]

**Review by jlaur — APPROVED** [review]
> @jlaur can we get this merged?

Yes, let's get it merged. I finally did a review assisted by ChatGPT to reduce cognitive overload for me when comparing the byte copy implementations. 😄

**Comment by jlaur** [comment]
@lsiepel - this is not my area of expertise, but I'm wondering if this line should be removed as well?
https://github.com/openhab/openhab-addons/blob/226806d55c8530d8c8a1329a5162b7d1f682e448/itests/org.openhab.binding.max.tests/itest.bndrun#L65

**Comment by lsiepel** [comment]
> @lsiepel - this is not my area of expertise, but I'm wondering if this line should be removed as well?
> 
> https://github.com/openhab/openhab-addons/blob/226806d55c8530d8c8a1329a5162b7d1f682e448/itests/org.openhab.binding.max.tests/itest.bndrun#L65

Yeah, was looking into that as you mentioned in the other post. I think this can safely be removed. I’ll come up with a PR

**Pull request merged**
