### PR TITLE
Remove unnecessary semicolons

### PR DESCRIPTION
**Pull request by wborn**
This helps with stopping the proliferation of unnecessary semicolons.

### CODE REVIEW

**Review by theater — APPROVED** [review]
OK

**Review by holgerfriedrich — APPROVED** [review]
LGTM

**Review by robnielsen — APPROVED** [review]

**Comment by robnielsen** [comment]
lgtm

**Review by mherwege — APPROVED** [review]
LGTM

**Review by lsiepel — APPROVED** [review]
LGTM

**Review by jlaur — APPROVED** [review]
Thanks!

**Review by stefan-hoehn — COMMENTED** [review]
Nanoleaf looks good to me

**Review by J-N-K — COMMENTED** [review]
Thanks!

**Pull request merged**
