### PR TITLE
[miio] added functions for Vacuums P2009/2036/2157

### PR DESCRIPTION
**Pull request by mabosch74**
fixed typo for starting sequence
added support for "find me" & "test sound" function
added clear names for faults

### CODE REVIEW

**Review by marcelrv — APPROVED** [review]
Thanks for your contribution.
The minor readme update (mapping comment) will come automatically when I do my next run with readme maker.

**Comment by marcelrv** [comment]
@mabosch74 see only now... can you sign off your commit, than it will pass the DCO check

**Comment by mabosch74** [comment]
> @mabosch74 see only now... can you sign off your commit, than it will pass the DCO check

sorry, but where can i make the sign off?

**Comment by marcelrv** [comment]
It is done when you create your commit.
You add a line `Signed-off-by: your name<email>` at the end of the commit text. Eclipse can do it automatically
See in the below section the DCO check (which now indicates the red cross) (click details) link to see more info

**Comment by mabosch74** [comment]
> It is done when you create your commit.
> You add a line `Signed-off-by: your name<email>` at the end of the commit text. Eclipse can do it automatically
> See in the below section the DCO check (which now indicates the red cross) (click details) link to see more info

sorry, I don't get it to work over web, no glue to do this without local installed git.

**Comment by marcelrv** [comment]
I'll let @cpmeister decide if that is a blocking issue... dunno how strict the project is wrt to the signoff

**Comment by cpmeister** [comment]
Yes, a sign off is required for any non-trivial commit.

**Comment by fwolter** [comment]
@mabosch74 do you need any help adding the sign-off line?

**Comment by fwolter** [comment]
@mabosch74 You can also post the sign-off line in the comments here.

**Comment by marcelrv** [comment]
@mabosch74 would be great to have this 
You can also post the sign-off line in the comments here. to avoid the juggling with git

**Comment by marcelrv** [comment]
@mabosch74 would you mind confirming this (adding a line signed of here in the comments) , or alternatively let me know if you want me to incorporate it in one of my PR's

**Comment by mabosch74** [comment]
> @mabosch74 would you mind confirming this (adding a line signed of here in the comments) , or alternatively let me know if you want me to incorporate it in one of my PR's

Hey Marcel, if you can post my changes, this would be great.

**Comment by wborn** [comment]
Hi @mabosch74, have a look at https://www.openhab.org/docs/developer/contributing.html#sign-your-work

If you agree with the "Developer Certificate of Origin", just add a comment here with your real name and e-mail like:

`Signed-off-by: Joe Smith <joe.smith@email.com>`

Then we'll add it to your commit and we can merge this pull request.

**Review by mabosch74 — COMMENTED** [review]
Signed-off-by: Marcel Bossert-Schwab <mbossertschwab@gmx.de>

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
