### PR TITLE
[jsscripting] ES6+ Support

### PR DESCRIPTION
**Pull request by jpg0**
Parent PR to track all the changes required to get ES6+ support into OH. This will remain WIP until it's dependencies are merged. This supercedes https://github.com/openhab/openhab-addons/pull/6399.

Remaining pieces currently implemented that need to go somewhere:
  - Lifecycle / OSGiScriptExtensionProvider - osgi + lifecycle for script libs (https://github.com/openhab/openhab-core/pull/1635)
  - BindingItemProviderDelegate + package / ProvidersScriptExtensionProvider - allows creation of item provider. This provider allows items to be bound based on their metadata. (TBD)
  - RuleFactory + ModuleHandlerStuff - allows wiring up of *unmanaged* rules. Currently always registered which causes some lifecycle problems. (will open PR)
  - FixedProvider / SuspendableFixedProvider - allows suspendable providers to allow correct insertion order (TBD)
  - LifecycleAwareDelegate / - General stuff that is aware of consumer lifecycles (TBD)
  - ~~Sitemap package - all sitemap API assistance stuff (moved to https://github.com/jpg0/ohj-support)~~
  - ClassExtender - Graal specific (TBD)
  - additional context from script manager (will open a PR)
     - dependency tracking
     - engine identifier (blocks https://github.com/openhab/openhab-core/pull/1196)

### CODE REVIEW

**Comment by jpg0** [comment]
A question here for the maintainers - I am expecting that I should be targeting OH 3.x here. Should I be working against master? If so why is it so far behind 2.5.x?

**Comment by Hilbrand** [comment]
Yes if you're targeting openHAB 3 you should work against master. It's not behind 2.5.x. It's just different. On the master only code compatible with 3.0 is present. All current development is done on 2.5.x and automigrated to 3.0 at the moment. Once 2.5.9 is released the 2.5.x branch will be migrated to 2.0 and merged back into the master and the master will become the default again.

**Comment by jpg0** [comment]
Thanks @Hilbrand. That makes perfect sense to me, however the message on master of "This branch is 81 commits ahead, 1009 commits behind 2.5.x." made me afraid that the automerging isn't happening and I'm in danger of colliding with changes on 2.5.x that are yet to land in master.

I'll assume that this isn't the case and target master.

**Comment by kaikreuzer** [comment]
@jpg0 All fine here - all you need to do to also make the build happy is to add your new project to the [reactor pom.xml](https://github.com/openhab/openhab-addons/blob/master/bundles/pom.xml) as well.

**Comment by simonihmig** [comment]
Kai Kreuzer <notifications@github.com> schrieb am Do., 10. Sep. 2020, 15:25:

**Comment by jpg0** [comment]
@kaikreuzer did you mean to close this?

**Comment by kaikreuzer** [comment]
Nope, see (4) in https://github.com/openhab/openhab-addons/issues/8512 😄 .

**Comment by jpg0** [comment]
Reopened as https://github.com/openhab/openhab-addons/pull/8516

**Pull request closed without merging**
