### PR TITLE
[tado] Add channel for PresenceState and support setting HOME/AWAY. Fixes #8826

### LINKED ISSUE #8826: [tado] Add Home/Away setting to be writable
Currently the tado Binding only supports **reading** the Home/Away status.

As of April 2020, the App now supports setting the Home/Away status manually, and it seems the Api now also supports setting the mode. 

Source: https://shkspr.mobi/blog/2019/02/tado-api-guide-updated-for-2019/#comment-149590

PUT request to:
https://my.tado.com/api/v2/homes/{homeId}/presenceLock

With a body like:
```json
{
"homePresence": "AWAY"
}
```

or `"HOME"` correspondingly.

Also used here:
https://github.com/equinoxefr/domoticz_scripts/blob/master/tado.py#L32

Unfortunately I'm not experienced with openhab addons, so it would be cool if someone could create a PR for this.
Maybe @wborn or @Hilbrand

### PR DESCRIPTION
**Pull request by Pro**
Backport of #8868 to 2.5.x

### CODE REVIEW

**Comment by Pro** [comment]
I'm not sure why CI fails as I did a rebase of the commit onto current upstream/2.5.x

**Comment by cpmeister** [comment]
looks like you need to run spotless

**Comment by Pro** [comment]
Tried it, but it didn't find any issues: `mvn spotless:apply -pl :org.openhab.binding.tado`

Anyways I rebased onto current 2.5.x, maybe that fixes the build failure

**Comment by fwolter** [comment]
If I see correctly this is an enhancement. The `2.5.x` branch receives only bug fixes.

**Comment by fwolter** [comment]
Feel free to re-open if you think closing is wrongful.

**Pull request closed without merging**
