### PR TITLE
[freebox] Support for more audio streams through the HTTP audio servlet

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #15113

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by clinique** [comment]
@lolodomo : I guess this will have to be reported in Freebox is binding also

**Comment by lolodomo** [comment]
I will test this PR to confirm that the 5s timeout is appropriate.

**Comment by lolodomo** [comment]
> I will test this PR to confirm that the 5s timeout is appropriate.

The player starts quickly and 5s is fine.

I disabled the support of OGG as it apparently does not work (tested with VoiceRSS producing an OGG file).

It is now tested and ready for a review&merge.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
