### PR TITLE
[knx] Allow all port names for serial interfaces

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Starting with openHAB 3.3, the framework enforces using serial
ports which are detected by the system by default. This feature
is now disabled for the KNX addon to allow using symlinks to
ports as well.
Refers-to: openhab/openhab-core#3014

Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Review by J-N-K — APPROVED** [review]

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by wborn** [comment]
The KNX binding doesn't use the OHC serial transport yet (https://github.com/openhab/openhab-addons/issues/7573). So you probably need to set `gnu.io.rxtx.SerialPorts` for it to work. Which is otherwise unneccessary when the OHC serial transport is used, because it automatically does that for you. :slightly_smiling_face:

**Comment by holgerfriedrich** [comment]
@wborn this is the behaviour as in OH 3.2, right?
And yes it is still gnu IO, porting is not done yet. I cannot test, as I do not have a serial device at hand. Calimero lib has some changes in the unreleased main line in this area.

**Comment by wborn** [comment]
Yes it's still the same as with OH 3.2. I just mentioned it for whenever users cannot get their udev rule based ports working with the KNX Binding.

**Pull request merged**
