### PR TITLE
[jdbc] Upgrade MySQL Connector/J to 8.0.31

### PR DESCRIPTION
**Pull request by jlaur**
See:
- https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-31.html
- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.0.31

Previous upgrade: #13242

### CODE REVIEW

**Comment by lsiepel** [comment]
Isn't this something dependabot should notice and auto bump?

**Comment by jlaur** [comment]
> Isn't this something dependabot should notice and auto bump?

I believe only for critical security updates, since we don't have it enabled otherwise:
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

No configuration file:
https://github.com/openhab/openhab-addons/tree/main/.github

**Comment by lolodomo** [comment]
Is it absolutely required for OH3.4?

**Comment by jlaur** [comment]
> Is it absolutely required for OH3.4? 

Absolutely not. 😊

**Comment by jlaur** [comment]
@lolodomo - but for OH 4.0 it should be fine. 😄

**Review by lolodomo — APPROVED** [review]

**Comment by mhilbush** [comment]
When running 4.0 build 3245, I get a failure when installing the mysql JDBC persistence service.
```
2022-12-21 12:04:40.082 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-persistence-jdbc-mysql': Error:
	Error downloading mvn:com.mysql/mysql-connector-j/8.0.31
```
I see the artifact was moved to `mysql-connector-j` in the maven repo, so I don't understand why it's not loading.

Seeing this exception in the console
```
org.apache.karaf.features.internal.util.MultiException: Error:                                                                                                      Error downloading mvn:com.mysql/mysql-connector-j/8.0.31
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.io.IOException: Error downloading mvn:com.mysql/mysql-connector-j/8.0.31
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		... 3 more
	Caused by: java.io.IOException: Error resolving artifact com.mysql:mysql-connector-j:jar:8.0.31: [Could not find artifact com.mysql:mysql-connector-j:jar:8.0.31 in openhab (https://openhab.jfrog.io/openhab/libs-snapshot/)]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
		at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
		... 6 more
		Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.mysql:mysql-connector-j:jar:8.0.31 in openhab (https://openhab.jfrog.io/openhab/libs-snapshot/)
			at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
			at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
			at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
			at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
			at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
			at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
			... 11 more
	Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact com.mysql:mysql-connector-j:jar:8.0.31
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
		at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
		... 11 more
```

Does the artifact need to be on jfrog?

**Comment by jlaur** [comment]
> Does the artifact need to be on jfrog?

Yes it does, sorry. @kaikreuzer, can you upload it?

**Comment by kaikreuzer** [comment]
Done! @mhilbush Please try again.

**Comment by mhilbush** [comment]
Resolved. Thanks Kai.

**Pull request merged**
