### PR TITLE
Normalize thread names (2)

### PR DESCRIPTION
**Pull request by andrewfg**
See also #17804 

Signed-off-by: AndrewFG <software@whitebear.ch>

### CODE REVIEW

**Comment by andrewfg** [comment]
@lsiepel I marked this as draft to reflect the state of #17804 .. however I think it is essentially ready for review .. but I will wait until you tell me to release it..

**Review by lsiepel — APPROVED** [review]
Checked all 43 files, LGTM.

**Comment by andrewfg** [comment]
> Checked all 43 files

Just so you know: the 'extends Thread' search did as you say reveal 57 such cases; however a few of them did already implement the agreed normalised thread naming convention.

**Comment by andrewfg** [comment]
@lsiepel I don't know why one of the three CI java builds failed here. It could be an instability in one of the tests (wemo binding)

**Review by kabili207 — APPROVED** [review]
LGTM

**Pull request merged**
