### PR TITLE
[boschshc] Upgrade to REST API version 3.2

### LINKED ISSUE #15053: [boschshc] Upgrade to REST API version 3.2
Today Bosch announced that in July the Smart Home Controllers will receive an update which does not support REST API version `2.x` anymore (https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/80).

This means that we have to update the openHAB binding because we currently use API version `2.1`.

### PR DESCRIPTION
**Pull request by david-pace**
closes #15053

### CODE REVIEW

**Comment by david-pace** [comment]
@GerdZanker I updated to the latest API version that is documented in the Postman collection (`3.2`). It seems like everything still works. I tested all channels of the hardware that I have available. If possible it would be great if you could check with your hardware as well.

**Comment by jlaur** [comment]
@david-pace - I have added the label "additional testing preferred" according to your https://github.com/openhab/openhab-addons/pull/15067#issuecomment-1583312464. You can remove this label when the PR is ready to be merged. Thanks!

**Comment by GerdZanker** [comment]
> @GerdZanker I updated to the latest API version that is documented in the Postman collection (`3.2`). It seems like everything still works. I tested all channels of the hardware that I have available. If possible it would be great if you could check with your hardware as well.

Hello @david-pace, I have the same test results. 
It seems like everything still works. I tested the discovery of bridge and devices and the channels of few devices.
My SHC hardware reports the following supported ``"apiVersions":["2.9","3.5"]``. Therefore I think the binding is now prepared for the next SHC software update where the support for 2.x is dropped.
Thank you for your fast reaction on the announcement.

**Review by GerdZanker — APPROVED** [review]

**Review by jlaur — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
