### PR TITLE
[linky] Binding stopped working

### LINKED ISSUE #16585: [linky] Binding stopped working since February
Error identified in the community [here](https://community.openhab.org/t/linky-communication-error/132889/36?u=glhopital).
The binding won't connect due to an internal server error.

### PR DESCRIPTION
**Pull request by clinique**
The entry point for the authentication and further data requests changed.
Bumped jsoup dependency
Resolves #16585

### CODE REVIEW

**Comment by clinique** [comment]
@lolodomo : this is ready for your review.

**Comment by lolodomo** [comment]
I compile and test that today.

**Comment by jlaur** [comment]
@clinique, @lolodomo - it seems like this should probably be cherry-picked to 4.1.x? In that case, do you think it would make sense to extract the library upgrade to another PR to reduce risk for next hotfix?

**Comment by lolodomo** [comment]
The bundle does not start due to the change of version of org.jsoup:
```
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.linky [293]
  Unresolved requirement: Import-Package: org.jsoup; version="[1.15.0,2.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.7.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.7.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.7.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.7.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.7.4]
```
Is it possible to avoid this change of version ?

**Comment by clinique** [comment]
> The bundle does not start due to the change of version of org.jsoup:
> ```
> org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.linky [293]
>   Unresolved requirement: Import-Package: org.jsoup; version="[1.15.0,2.0.0)"
> 
>         at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.7.4]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.7.4]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.7.4]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.7.4]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.7.4]
> ```
> Is it possible to avoid this change of version ?

Some other bindings are using the same version (Verisure IIRW) - it should work and works in the dev environment. On top of that previous version is signaled with a security issue, reason why I thought it would be a good move

**Comment by lolodomo** [comment]
I just put the built jar in my addons folder. I am running a recent snapshot, number 4004.

**Comment by jlaur** [comment]
> I just put the built jar in my addons folder. I am running a recent snapshot, number 4004.

Does it work if you install the [SMGW binding](https://www.openhab.org/addons/bindings/smgw/), for example (to fulfill the dependency)?

**Comment by clinique** [comment]
@lolodomo : you're ready to go, I reverted json dependency to the original version.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
Thank you a lot Gael, I will test it with next snapshot tomorrow.

**Comment by lolodomo** [comment]
And I will cherry pick it in 4.1.x

**Comment by lolodomo** [comment]
I confirm it works. Bravo Gael.

**Comment by clinique** [comment]
> I confirm it works. Bravo Gael.

Merci Laurent !

**Pull request merged**
