### PR TITLE
[netatmo] Fix doorbell channels flapping

### PR DESCRIPTION
**Pull request by clinique**
Adressing issue #13002

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
LGTM.

Would be nice for @lolodomo to confirm.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@clinique : are tests finished and positive ?

**Comment by clinique** [comment]
> @clinique : are tests finished and positive ?

Please wait @HaKUnsash feedback. I'll ping you

**Comment by HaKuNaCH** [comment]
> > @clinique : are tests finished and positive ?
> 
> Please wait @HaKuNaCH feedback. I'll ping you

positive feedback given here, thx for investigating:
https://github.com/openhab/openhab-addons/issues/13002

**Comment by clinique** [comment]
> @clinique : are tests finished and positive ?

You can proceed

**Pull request merged**
