### PR TITLE
[knx] Enable support for cemi in SerialBridge config

### PR DESCRIPTION
**Pull request by petero-dk**
From this commit (https://github.com/calimero-project/calimero-core/commit/b322db4f8bb7949e3d35299750049813d99cb25c ) in the calimero project, cemi support has been enabled. 

This PR makes the switch available in the BridgeThing configuration.

I am unsure how the Calimero is imported into this project, and how it is possible to reference a later release than Calimero 2.4 since that is the last official release and that is earlier than the CEMI fix.

### CODE REVIEW

**Comment by petero-dk** [comment]
Notice that the Travis CI build actually FAILED since the constructor is undefined because it does not reference the correct Calimero build.

This is as expected

```
[ERROR] /home/travis/build/openhab/openhab2-addons/bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java:[58,2112] The constructor KNXNetworkLinkFT12(FT12Connection, TPSettings, boolean) is undefined
```

**Comment by J-N-K** [comment]
We use snapshots or forked versions only if there is an absolute need for that (e.g. security issues, bugfixes for existing functionality, dead project at the other end). I don't see that this is the case here.

Even if we would agree that we could use our own version, there is anotehr problem:  current Calimero requires Java11 at runtime. OpenHAB2 is has Java8 as minimum requirement. Therefore we can't upgrade. Java 11 will probably be minimum requirement for OH3.

**Comment by petero-dk** [comment]
Ahh, I was confused for a second. To sum up just so I completely understand:

The changes I refer to are in the next version of Calimero but still the official one. Which now uses Java11 which means we cannot use the latest version but are stuck on the last version to support Java8 until OH3 (probably).

I have not made any changes to Calimero, just the addon.

**Comment by petero-dk** [comment]
Any serial device for KNX that uses cEMI does not work directly with the KNX binding most notably that means the KBerry (one could argue this would be a bugfix)

**Comment by J-N-K** [comment]
> I have not made any changes to Calimero, just the addon.

True. But we need to upgrade calimero bundles to get it working. I see no way we could do that.

**Comment by J-N-K** [comment]
I believe that no one will come up with a solution for the Java11 requirement on newer calimero releases. We simply can't solve that with OH2. I would like to close this PR. @openhab/2-x-add-ons-maintainers, WDYT?

**Comment by petero-dk** [comment]
Actually I might have a solution. 

A google engineer informed me that the D8 and the R8 dexer and shrinker for Android build has, as part of the build pipeline, a tool that can "recompile" Java11 to Java8 (and other configurations also) which means it is possible to take the Calimero build for Java11 and desugar it to a Java8 build (I think they use magic).

This jar would be without the encryption part which is Java 11 specific, but everything else would be there. 

Currently I am working on a build system that would do this automatically.

Now: When that works would there be a path for that to be used with the above PR and join OH2?

**Comment by petero-dk** [comment]
I have now managed to implement the changes required in the addon, and via a separate project it is possible to crosscompile (any package) to java8: https://github.com/petero-dk/javacrosscompiler

However Calimero does not seem to like working with my kberry device so for now I have paused development. Even with a few custom changes it just wont work (https://github.com/petero-dk/calimero-core). So I cannot 100% guarantee it works.

**Comment by petero-dk** [comment]
Actually I was so focused on the errors that I have completely forgotten to test whether I could send commands to the KNX network from Openhab with this backcompiled Calimero. And that WORKS. Just to recap. Taking the latest Calimero 2.5-SNAPSHOT, running it through the magic machine of rebuilding for Java 8 does actually work. However Calimero has issues working with BAOS devices/kberry devices.

**Comment by petero-dk** [comment]
I have just gotten an outreach from the calimero project, he fixed my issue with the Baos device (https://github.com/calimero-project/calimero-core/issues/89). 

I now have the neccessary components to create a Calimero build (for Java 8) from the latest branch of Calimero to support cEMI and additionally BAOS devices such as the kBerry. However obviously this is not the official Calimero jars, but it will be the official Calimero . That means openHAB will be able to run most serial devices without KNXD and significantly minimizing the difficulty in getting openHAB and KNX to work. ( I also have this running on my openHAB on openHABian )

@J-N-K I have now solved getting a Java 8 build of Calimero ;-) What is the interest in getting this official? I have made sure to make the toolchain for the crosscompilation versioned and on a github project. I can easily make a CI pipeline that continously builds Calimero builds from the official project. (Link above) 

Note: The crosscompiler will work for ANY Java 9 or later library that needs to run on Java 8. Just note that specific Java 9 or later functionality that depends on JRE new platform functionality will not work, such as Calimero supports encrypted IP connections which depends on new crypto functionality in Java 11. Those functions cannot be backported and as such they will not work.

**Comment by meckiemac** [comment]
hi, since we upgraded to calimero 2.5 in OH 3.2 can we also integrate cemi? means integrate this patch too?

**Pull request closed without merging**
