### PR TITLE
[milight] Update README.md

### PR DESCRIPTION
**Pull request by Trysupe**
**Beautify README**

* Fix Indentation 
* Change comment character from '#' to '//'
* Remove wrong formatting attempts ('rsqb' & 'lsqb')
* Minor changes

### CODE REVIEW

**Review by fwolter — APPROVED** [review]

**Comment by fwolter** [comment]
Can you please sign-off your commits? You can click on Details at the DCO check below.

**Comment by Trysupe** [comment]
Can the sign-off be done be done online too? I just edited the README in the online editor and did not clone it locally.

**Comment by fwolter** [comment]
IDK. Can you post your sign-off message here? I will adopt it in the commit message, then.

**Comment by Trysupe** [comment]
`Felix Schneider <fs@felix-schneider.org>`

Is this what you're asking for?

**Comment by fwolter** [comment]
It is `Signed-off-by: Felix Schneider <fs@felix-schneider.org>`. I'll add it. Thanks!

**Comment by Trysupe** [comment]
When will this visible in the docs?

**Comment by fwolter** [comment]
With the next OH3 milestone release under next.openhab.org and with the openHAB 3 release (end of the year) under openhab.org. IDK when the due date of 3.0.0.M4 is.

**Pull request merged**
