### PR TITLE
[mqtt.homeassistant] fix compilation problems

### PR DESCRIPTION
**Pull request by ccutrer**
Due to #15427 and #14839 being developed independently, but merged to main successively

### CODE REVIEW

**Comment by ccutrer** [comment]
cc @jlaur @lolodomo

**Review by lolodomo — APPROVED** [review]
LGTM

**Review by jlaur — APPROVED** [review]

**Comment by jlaur** [comment]
@ccutrer - thanks for the quick fix!

**Comment by lolodomo** [comment]
@ccutrer : no need to check/update your other MQTT homeassistant PRs ?

**Comment by ccutrer** [comment]
> @ccutrer : no need to check/update your other MQTT homeassistant PRs ?

#14241 needed rebased and fixed. The others were already written in such a way that they'd be fine once #15427 was merged.

**Pull request merged**
