### PR TITLE
[mqtt.homeassistant] Fix color lights that don't specify color_mode: true

### LINKED ISSUE #17184: [mqtt.homeassistant] Color channel not created for Hue lights via zigbee2mqtt
## Expected Behavior
My lights should have a color channel.

## Current Behavior
They only have a brightness channel.

## Steps to Reproduce (for Bugs)
Example configuration JSON:
```json
{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/Basement Laundry Room East Can/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","brightness":true,"brightness_scale":254,"command_topic":"zigbee2mqtt/Basement Laundry Room East Can/set","device":{"configuration_url":"http://opennuc:8084/#/device/0x001788010d47085f/info","identifiers":["zigbee2mqtt_0x001788010d47085f"],"manufacturer":"Philips","model":"Hue white and color ambiance 5/6\" retrofit recessed downlight (9290031346)","name":"Basement Laundry Room East Can","sw_version":"1.116.3","via_device":"zigbee2mqtt_bridge_0xe0798dfffe882ce4"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","candle","fireplace","colorloop","finish_effect","stop_effect","stop_hue_effect"],"max_mireds":500,"min_mireds":153,"name":null,"object_id":"basement_laundry_room_east_can","origin":{"name":"Zigbee2MQTT","sw":"1.38.0","url":"https://www.zigbee2mqtt.io"},"schema":"json","state_topic":"zigbee2mqtt/Basement Laundry Room East Can","supported_color_modes":["xy","color_temp"],"unique_id":"0x001788010d47085f_light_zigbee2mqtt"}
```
Note that there is a `supported_color_modes` attribute, but _not_ a `color_mode` attribute. The code seems to assume that a color bulb will have a `color_mode` attribute.

## Context
I don't see `color_mode` in the docs at https://www.home-assistant.io/integrations/light.mqtt/#json-schema for the discovery payload, so either Home Assistant changed how it works, or openHAB has always been wrong. More digging is needed.
This also _used_ to work with these bulbs, so I suspect a zigbee2mqtt update changed their discovery payload.

## Your Environment
* Version used: openHAB 4.3.0-SNAPSHOT
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 22.04 jammy
* zigbee2mqtt version: 1.38.0

### PR DESCRIPTION
**Pull request by ccutrer**
See https://github.com/home-assistant/core/pull/111676

Fixes #17184

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks LGTM. Ping @antroids

**Comment by antroids** [comment]
The `color_mode` and `brightness` flags were deprecated in HA and their values should be assumed as `true`.
It means that these modes will be active when they are in `supportedColorModes`.
I think you could also remove the org.openhab.binding.mqtt.homeassistant.internal.component.Light.ChannelConfiguration#colorMode within this PR.

**Comment by ccutrer** [comment]
A few clarifications:

`color_mode` is completely deprecated, and soon-to-be-removed. `brightness` is not deprecated - it just defaults to `true` now, and should only be set to `false` for the unusual case of a bulb that supports color, but _not_ brightness.

**Comment by ccutrer** [comment]
Ugh... brightness is assumed true, _unless_ color_mode is only OnOff. I'll handle that as [a separate issue](#17245).

**Comment by lsiepel** [comment]
The DCO failed can you look into it?

**Comment by ccutrer** [comment]
Dang it, I forgot to signoff my quick commit this morning. Fixed.

**Pull request merged**
