### PR TITLE
[mycroft] Adjust thread name for web socket client

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by dalgwen — APPROVED** [review]
👍

**Comment by lolodomo** [comment]
A counter is maybe not the best option because a new thread pool will be created each time the thing handler is initialized.

**Comment by lolodomo** [comment]
@dalgwen : please have a new look.

**Review by dalgwen — APPROVED** [review]
OK for me.
But the whole websocket id construction really seems to be some kind of black magic.
I see that you made some merge request on other bindings for the same purpose.
Shouldn't it be a common method somewhere ?
Like in HexUtils or in UIDUtils ?
It is so easy to not using the thread name properly.

**Comment by lolodomo** [comment]
> I see that you made some merge request on other bindings for the same purpose.
> Shouldn't it be a common method somewhere ?
> Like in HexUtils or in UIDUtils ?
> It is so easy to not using the thread name properly.

Could make sense to add a method in the same class as the one that provides createHttpClient and createWebSocketClient.

**Comment by lolodomo** [comment]
Awaiting PR openhab/openhab-core#3359 to be merged to then update this PR

**Comment by lolodomo** [comment]
My initial analysis was wrong, there is no risk of IAE with the current code.

**Review by wborn — APPROVED** [review]

**Pull request merged**
