### PR TITLE
[jsscripting] Standardize on `js` for SCRIPT

### PR DESCRIPTION
**Pull request by rkoshak**
This has the add-on docs consistent with the main docs.
Signed-off-by: Richard Koshak <rlkoshak@gmail.com>

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
Thanks! Can you please open a PR to openhab-js to update the docs there as well? I am normally copying the README from openhab-js to the addon‘s README.

**Comment by florian-h05** [comment]
Another thing: The SCRIPT profile PR has been merged a few days ago, do you know how to use it?

**Comment by florian-h05** [comment]
If the same PR is provided to openhab-js, this shouldn’t cause a conflict. 
If it does, I can easily resolve it when I update the library version the next time.

Ultimately, I want an automated process to pick up the docs from the openhab-js repo, @Confectrician is already looking into that.

**Comment by rkoshak** [comment]
Yes, I'll open a PR over there too.

**Comment by jlaur** [comment]
> If the same PR is provided to openhab-js, this shouldn’t cause a conflict.
> If it does, I can easily resolve it when I update the library version the next time.

OK, let's merge it then, although it seems like unneeded duplication and risk as it would land here anyway. 🙂

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
