### PR TITLE
[amazonechocontrol] Support QuantityType Color Temperature command

### LINKED ISSUE #17917: Are we sure that all bindings accept properly a value in Kelvin and a value in mirek as command?
@andrewfg : I have a doubt, are we sure that all bindings accept properly a value in Kelvin and a value in mirek as command?

_Originally posted by @lolodomo in https://github.com/openhab/openhab-core/issues/3891#issuecomment-2546145215_

### PR DESCRIPTION
**Pull request by andrewfg**
Resolves #17917 

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by andrewfg** [comment]
## TODO

We need to fix also the [MQTT channels](https://community.openhab.org/t/openhab-4-3-zigbee2mqtt-color-temperature-in-mired-not-working/160911/3) before merging this PR!!

**Comment by lsiepel** [comment]
Changed to draft to prevent unwanted merge. Please revert when mqtt channels are fixed.

**Comment by andrewfg** [comment]
@ccutrer do you think anything needs to be done in the MQTT bindings in order for them to accept QuantityType inputs. AFAICT they do already accept such inputs and a) if the Channel has a ‘unit’ field then UoM conversions are applied, or b) if the Channel has no ‘unit’ field then it takes the raw decimal value of the given QuantityType (without conversion).

**Comment by ccutrer** [comment]
To answer here: the handleCommand and downstream calls are all set up to handle K or mirek in MQTT, but due to another issue core was only sending decimal commands. PRs are open (https://github.com/openhab/openhab-core/pull/4507 and #17929) to fix that.

**Comment by andrewfg** [comment]
@lolodomo the case of MQTT is covered by @ccutrer 's two PRs, so this one is ready to go. We should probably cherry pick it back into OH 4.3..

**Comment by andrewfg** [comment]
> have a PR by binding

No problem. I will split it.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
> No problem. I will split it.

Wait, I am not 100% sure it is necessary and I don't want to make you loose your time!
@jlaur @lsiepel : is it ok for you to backport this PR in 4.3.x even if it impacts several bindings ?

**Comment by andrewfg** [comment]
It will only take about 30 minutes to do the split

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
Can you please adjust the content of your first message ?

**Comment by jlaur** [comment]
> is it ok for you to backport this PR in 4.3.x even if it impacts several bindings ?

If I get the context right, what is left here in this PR is a fix for a regression introduced by #17754 - and likewise for all the others (i.e. #17942 fixes #17777 etc.). So I think all the PR's should be backported to 4.3.x.

Given a clean commit history (one commit per binding) we could have merged just one PR without squash-merging the commits. We did that here: https://github.com/openhab/openhab-addons/pull/17725#issuecomment-2533068994

But I like this split approach as well, since there is a clean 1:1 relation for each PR to a PR that introduced the issue - and also all bindings will be mentioned in the release notes. 👍

**Comment by lolodomo** [comment]
To be backported in branch 4.3.x.

**Comment by lolodomo** [comment]
I will do the different backporting, I am just searching again the proper git commands... to not make a mistake?

**Comment by jlaur** [comment]
> I will do the different backporting, I am just searching again the proper git commands... to not make a mistake!

For reference: https://github.com/openhab/openhab-addons/pull/15329#issuecomment-1658595092

**Comment by lolodomo** [comment]
The 5 PRs are now backported to branch 4.3.x.

**Pull request merged**
