### PR TITLE
pom reference update from http to https

### PR DESCRIPTION
**Pull request by marcelrv**
This fixes issue in eclipse where pom appears to have an error. Replacing the http with https fixes the issue.

note:  only the 2nd url changed, this is in line with the examples on the maven site https://maven.apache.org/pom.html#the-basics

image

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Review by pacive — APPROVED** [review]

**Review by druciak — APPROVED** [review]

**Review by ecdye — APPROVED** [review]
LGTM

**Review by bern77 — APPROVED** [review]
LGTM

**Review by bobadair — APPROVED** [review]
LGTM

**Review by fruggy83 — APPROVED** [review]
LGTM

**Review by robnielsen — APPROVED** [review]

**Review by t-8ch — APPROVED** [review]

**Review by kaikreuzer — APPROVED** [review]
Thank you!

**Comment by J-N-K** [comment]
Just noticed that some bundles contain a reference to `http://maven.apache.org/xsd/maven-4_0_0.xsd` (e.g. dmx, onewire, influxdb, tr064 and probably all others that are unchanged with this PR). IMO this is wrong, too.

**Comment by marcelrv** [comment]
> Just noticed that some bundles contain a reference to `http://maven.apache.org/xsd/maven-4_0_0.xsd` (e.g. dmx, onewire, influxdb, tr064 and probably all others that are unchanged with this PR). IMO this is wrong, too.

I guess so. Let me submit a PR for those as well. Did not catch these in  my search/replace indeed.

**Pull request merged**
