### PR TITLE
[jsscripting] Upgrade openhab-js to 5.1.2

### PR DESCRIPTION
**Pull request by florian-h05**
Second attempt to fix a problem, where persisting TimeSeries failed when injection caching was enabled.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jlaur This is the second attempt to fix openhab/openhab-js#346.

**Comment by lsiepel** [comment]
Would it be usefull to create something like an itest for this ?

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by florian-h05** [comment]
> Would it be usefull to create something like an itest for this ?

Probably yes, but preferably this should be available for the openhab-js repo itself, where the library is developed, and not only for the add-on.
However I have no idea how to create itests for JS Scripting, as it is quite complex with the JavaScript library ran by GraalJS and the add-on, which allows dynamic access from JS to the Java classes of openHAB Core.

**Pull request merged**
