### PR TITLE
[freeathomesystem] Initial contribution

### PR DESCRIPTION
**Pull request by andrasU**
This is the reworked initial contribution of the free@home binding, which is based on the official local API from ABB/Busch-Jäger

ABB/Busch-Jäger free@home binding for OpenHAB

This is a new binding for controlling free@home devices from ABB / Busch-Jaeger. I would like to provide this binding to the OpenHAB community to be able to bind the free@home devices through the official API.
This Binding makes possible to control the [free@home] devices through the free@home SysAP bridge.

The SysAP bridge is the only one device, which shall be added manually to the system.
The things can be detected on the openHAB dashboard
This binding is creating the thing's channels automatically based the free@home drives features.
The following devices are supported

ABB / Busch-Jaeger System Access Point 2.0
free@home Switch Actuator Sensor 1/1, 2/1, 2/2 (wired and wireless)
free@home Dimming Actuator Sensor 1/1, 2/1 (wired and wireless)
free@home Blind Actuator Sensor 1/1, 2/1 (wired and wireless)
free@home Movement Detector Actuator
free@home Radiator Thermostat types
free@home Switch Actuator 4-channel
free@home Switch Actuator 4-channel
free@home Dimming Actuator 4- and 6-channel
IP-touch panel (function: door opener, door ring sensor)
Hue devices (untested)

[Link to binary](https://github.com/andrasU/openhab-free-home-binding)

### CODE REVIEW

**Comment by jlaur** [comment]
@andrasU - you could close this PR and reopen #13703 to preserve history/comments.

**Comment by andrasU** [comment]
> @andrasU - you could close this PR and reopen #13703 to preserve history/comments.

@jlaur - I tried but the button at bottom of the PR page #13703 was not active to me. Maybe the rights were not sufficient. If you have a better idea which could work also for me please tell and I will try it.

Thank you

**Comment by jlaur** [comment]
> I tried but the button at bottom of the PR page #13703 was not active to me. Maybe the rights were not sufficient. If you have a better idea which could work also for me please tell and I will try it.

This one will need to be closed first, as the same branch can't have two open PR's. If you will not be able to do it after closing this one, please let me know, and I'll see if I can do it.

> Other thing: the build is not successful however not in may changes. What could I do?

Since only one of the builds failed, it might not be related to your code. You could check the build logs if you want to be sure you didn't introduce any unstable tests, but otherwise I wouldn't worry too much about that for now.

**Comment by andrasU** [comment]
@jlaur FYI

Closed to reopen the old PR

**Pull request closed without merging**
