### PR TITLE
[openhabcloud] Update README.md

### PR DESCRIPTION
**Pull request by DeviantGnome**
Add a note to let a user know that the server may need to be restarted before their cloud service will see it as "online". Without this, it's not apparent as to what the user may need to do next.

### CODE REVIEW

**Comment by digitaldan** [comment]
I'm not aware of needing to restart OH for the binding to work, that would seem to be a bug to me, is there a discussion somewhere that suggests this is required?

**Comment by DeviantGnome** [comment]
Hey Dan. I couldn't find anything directly related to a restart fixing this issue definitively. I had configured openHAB Cloud Connector, set up the account at myopenhab.org, and it didn't update from offline to online. I tried changing the state of devices to get it to "talk" to myopenhab, but that didn't seem to do the trick. So many times a simple restart is the quickest and easiest thing, and that seemed to be the case here.

Also, I know I missed the signature on my commit (this is my first open-source contribution), and I'm working to get it fixed. I knew I had to have it, but I was committing from GitHub (which I've never done before, always from CLI), and was expecting an option to add the signature. My mistake!

**Comment by digitaldan** [comment]
>I had configured openHAB Cloud Connector, set up the account at myopenhab.org, and it didn't update from offline to online. 

Hmm, so in this case the binding was configured first, so it tries to connect to the cloud service, but of course there is not an account to connect too, so it fails. Once you create an account, you need to restart OH (or rather somehow force the binding to restart) in order for it to try again.

If this was indeed the order of events, then i would say we need to address this in the binding by having it try to auto reconnect after a login failure if it does not already do this.  There also might need to be an update to the readme to reflect the delay that might be there in connecting after creating an account.

**Comment by DeviantGnome** [comment]
Right. Seems you can't create the cloud account unless you have the UUID and secret, which you don't get until you configure the connector. So, it'll always fail.

I'll take a look at the code and see if I can find a retry in there. If there isn't, I'll see about implementing one. If there is, I'll update the readme accordingly.

And of course, I'll get the signature thing sorted out. ;)

As far as this PR goes, if you would rather close it and I can submit a new one when I have it figured out, that's perfectly fine.

**Comment by digitaldan** [comment]
Actually, i'm confused, you mention:
>and it didn't update from offline to online. 

Where do you see this?  The cloud service is not a "thing", but rather a service, so there is not a Thing status (ie ONLINE/OFFLINE) associated with it.  How are you determining if it's online or not ?

**Comment by digitaldan** [comment]
nm, I think i understand, it still shows as offline on the openHAB cloud web portal.

**Comment by MHerbst** [comment]
> If this was indeed the order of events, then i would say we need to address this in the binding by having it try to auto reconnect after a login failure if it does not already do this.

I have seen a similar behavior in my installation after the last update. I suspect that this can happen especially on slower systems like a Raspberry 3. Especially if JSR223 scripting is also used. I also have sometimes problems with other bindings (probably timing issues). To avoid any problems I always start openHAB anew after the first start after the update completed.

**Comment by Hilbrand** [comment]
@DeviantGnome I'm closing this pr for now. Maybe you can create an issue describing the problem so we can track what is the problem and you can post more information about what you found or use that as the basis for a new pr if you find anything. Thanks.

**Pull request closed without merging**
