### PR TITLE
[avmfritz] Update README.md (fritzavm binding docs)

### PR DESCRIPTION
**Pull request by Rossko57**
Add skeletal "Troubleshooting' section, with minimal debug log instruction.

Signed-off-by Ross Kennedy <rossko@culzean.clara.co.uk>

### CODE REVIEW

**Comment by Hilbrand** [comment]
I don't know if we want this kind of generic information in the documentation here. This information can be applied to each binding. It should be enough to have it in the generic logging documentation page. That documentation might be some improvement with how to find the right name to use for a binding, like here one needs to know to use `org.openhab.binding.avmfritz`. (Although it would be really great if we have an api to just set debug level on any addon via a rest call).

**Comment by Rossko57** [comment]
It is not intended for generic information.
There's a very specific-to-this-binding pointer to _useful_ information to gather.
Not all bindings are alike here.  Some are multi-package, in others it would be pointless.

There **is** generic looking "check the Things" advice, added because it is not self evident that Thing status can include plain language clues like "communication failure".  Maybe that's nonsense and should come out.
There is probably _better_ specific-to-this-binding-advice, like looking at something in Fritz.  I have no idea.

I don't use this binding, I won't be offended whether the suggestion is adopted, altered, or dropped in the bin,

It's just to throw a lifeline to a user of this binding who has fallen at the first steps.

**Comment by J-N-K** [comment]
Can‘t we show the bundle-names in the header of the documentation file?

**Comment by kaikreuzer** [comment]
As already discussed in https://github.com/openhab/openhab-addons/issues/8175: There is really nothing specific about this binding in this PR. I can only repeat what I said in https://github.com/openhab/openhab-addons/issues/8175#issuecomment-663047005 already.

**Pull request closed without merging**
