### PR TITLE
[mqtt.homeassistant] Support color temp on JSON schema lights

### PR DESCRIPTION
**Pull request by ccutrer**
also adds a color_mode channel if color temp is possible, so you can know how the bulb is behaving

### CODE REVIEW

**Review by antroids — CHANGES_REQUESTED** [review]
Thank you for the PR!

**Comment by lolodomo** [comment]
@ccutrer : did you see @antroids 's comments?

**Comment by ccutrer** [comment]
Force pushed to rebase so tests would pass with changes to HSBType's handling of conversions. New changes were added as a separate commit.

**Review by antroids — APPROVED** [review]

**Comment by antroids** [comment]
LGTM, thank you!

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
