### PR TITLE
[icalendar] added last_update-channel

### LINKED ISSUE #9301: [icalendar] calendar last update would be nice
It would be nice if the calendar shows the date of the last successful download of a calendar it's date. This allows to escalate problems with rules to the user (e.g. the user wants to know if last successful download is longer than 4 days ago).

I think implementing it by adding a DateTime-typed channel just showing the file date is exactly the interesting data.

I'll implement this but i'm open to suggestions a while before starting the work.

### PR DESCRIPTION
**Pull request by daMihe**
last_update describes the last successful update of the calendar. Fixes #9301.

### CODE REVIEW

**Review by fwolter — APPROVED** [review]
As OH3 RC is already feature freezed, your PR will be merged as soon as OH3 is released. Your changes will go into OH3.1, then.

**Comment by cweitkamp** [comment]
@daMihe Thanks for adding this channel. Did you maybe miss something? I always see this message in my logs:

```
2020-12-28 10:29:40.212 [WARN ] [ar.internal.handler.ICalendarHandler] - Framework sent command to unknown channel with id 'last_update'
```

**Comment by daMihe** [comment]
hmm. there seems something to be missing. I assume adding a channel in xml is not enough, as i have not migration logic built in and you are getting this error. I'll check this theese days. You can work this around by readding the thing (this is what i did, as for development you want to start with a clean state...).

**Comment by cweitkamp** [comment]
I should give you more details. I already recreated my Thing and in general the Channel is working fine. But during OH restarts I see the message above in my logs. I guess you have to add an additional case in the `handleCommand` method of the handler:

https://github.com/openhab/openhab-addons/blob/f9b763210d67f286186eeded6c69e1001ed28d2b/bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java#L104-L120

**Comment by daMihe** [comment]
Okay. A separate PR will follow, i'll add you as reviewer.

**Pull request merged**
