### PR TITLE
[boschshc] Boost unit test coverage

### PR DESCRIPTION
**Pull request by david-pace**
Boosts the unit test coverage for the `boschshc` binding in `src/main/java`
to 94%.

Main code changes:
* made some methods package-protected in order to be testable
* fix typo in exception message (in class `BridgeHandler`)

Test code changes:
* add lots of additional tests
* refactor redundant tests to parameterized tests
* add utility class providing arguments for common parameterized tests
* fix a problem caused by wrong order of `super.beforeEach()` calls
* remove unnecessary `lenient()` configurations

### CODE REVIEW

**Comment by david-pace** [comment]
Rebased on main - can be reviewed now 😎

**Comment by lsiepel** [comment]
> Rebased on main - can be reviewed now 😎

Do you use some kind of test coverage analysis? @holgerfriedrich uses jacoco for knx, also used in bmw binding, that seems a  solid tool.

**Review by lsiepel — APPROVED** [review]
LGTM. Thanks for adding tests !

**Comment by david-pace** [comment]
Hi @lsiepel, I use [EclEmma](https://www.eclemma.org/) which uses [JaCoCo](https://www.jacoco.org/jacoco/) under the hood. I have also used the JaCoCo Maven Plug-In in several projects in order to make the coverage visible in SonarQube, for example. It works very well :+1: The only thing I remember is that the Maven configuration can be complicated if results should be aggregated.

**Pull request merged**
