### PR TITLE
Re: [Nuki] Initial Support for Nuki Opener

### PR DESCRIPTION
**Pull request by d3473r**
Hi all,

this is the https://github.com/openhab/openhab-addons/pull/7497 PR from @alx-k reapplied to the current [2.5.x](https://github.com/openhab/openhab-addons/tree/2.5.x) branch which fixes https://github.com/openhab/openhab-addons/issues/6041.
Please add the `migrate to OH3` label so i can download the migrated sources and create a PR against `main` as the [generated sources](https://github.com/openhab/openhab-addons/pull/7497#issuecomment-711349862) from the original PR (probably) have [expired](https://ci.openhab.org/job/openHAB-Addons-Migration/110/artifact/bundles/).

Regards,
D3473R

### CODE REVIEW

**Comment by fwolter** [comment]
If I understand correctly you only want to have a migrated version of the old (this) PR and this isn't supposed to get merged.

**Comment by D3473R** [comment]
> If I understand correctly you only want to have a migrated version of the old (this) PR and this isn't supposed to get merged.

Yes, I just want to have the migrated code, then I will open a new PR. 
The Build hase failed though, maybe I've broken something with the merge, I did not have the time to fix it yet.

**Comment by fwolter** [comment]
The code doesn't compile as it has formatting issues. You can run `mvn spotless:apply` to fix it. But that doesn't help getting it migrated. I can't see what causes the migration to fail. Maybe @kaikreuzer sees it at a glance.

**Comment by D3473R** [comment]
After a few cups of tea I managed to do the merge again and this time successful (hopefully) 😁 
Can you please add the `migrate to OH3` label again? @fwolter

**Comment by fwolter** [comment]
Looks like the migration doesn't work. I can't see the problem... Do you mind making the migration manually? It shouldn't be a big deal.

**Comment by d3473r** [comment]
I'll try the migration manually and then open a new PR on the v3 branch :+1:

**Pull request closed without merging**
