### PR TITLE
[mercedesme] Fix trip channel type id

### LINKED ISSUE #17265: [mercedesme] Cannot find channel type: mercedesme:consumption-conv-resetchannel
From https://github.com/weymann/MercedesMe-OH-Drops/issues/2 submitted by @DrScr3w 

Hello, after restarting OH I noticed that the following two messages appear in the log.

```javascript
2024-07-13 06:23:23.588 [WARN ] [ore.internal.thing.ThingTypeResource] - Cannot find channel type: mercedesme:consumption-conv-resetchannel
2024-07-13 06:24:12.581 [WARN ] [core.thing.internal.ThingManagerImpl] - Channel types or config descriptions for thing 'mercedesme:hybrid:089b61ca41:WXXXXX' are missing in the respective registry for more than 120s. In case it does not happen immediately after an upgrade, it should be fixed in the binding.
```

**Environment**
openHAB: 4.2
Promox: VM Debian
```yaml
347 │ Active │  80 │ 4.2.0.202406291337    │ openHAB Add-ons :: Bundles :: MercedesMe Binding

### PR DESCRIPTION
**Pull request by weymann**
Fixes #17265

### CODE REVIEW

**Comment by lolodomo** [comment]
Please also provide upgrade instructions for an automatic update of existing things.

**Comment by weymann** [comment]
> Please also provide upgrade instructions for an automatic update of existing things.

Is there a way to test the instructions?
I tried `bundle:update` in openHAB console and the errors are disappearing. But shouldn't the channels be added automatically after updating?

**Comment by lsiepel** [comment]
> > Please also provide upgrade instructions for an automatic update of existing things.
> 
> Is there a way to test the instructions? I tried `bundle:update` in openHAB console and the errors are disappearing. But shouldn't the channels be added automatically after updating?

The instructions are wrong, they should be update not add. See https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

to test you would configure a thing with the previous bj ding version. Uninstall the binding, drop the jar in the adobe folder and it should be updated with no errors in the log.

**Comment by weymann** [comment]
> to test you would configure a thing with the previous bj ding version. Uninstall the binding, drop the jar in the adobe folder and it should be updated with no errors in the log.

Fine, this is what I'm testing since days.

**Setup**
- Install released binding from Add-on Store
- Create Things - errors in log, Channels are not visible in `Thing - Channels` Tab

**Update**
I tested in all possible combinations
- `update-channel` in instructions.xml
- `add-channel` in instructions.xml
- dropping bundle into `addons `folder after removal of released binding
- `bundle:update` via openHAB console to update released binding - see picture below

**Result**
All combinations above are showing the same result. 
- The Things created with released binding are **_not_** updated - same channels as before
- New Things created are fine - no errors, no missing channels 

image

**Comment by lsiepel** [comment]
1. Install released binding from Add-on Store
2. Create Things - errors in log, Channels are not visible in Thing - Channels Tab
3. Dropping bundle into addons folder after removal of released binding
4. bundle:update via openHAB console to update released binding 

As the thingtypeversion needs to be updated each time, you can not do this on your an instance you already used. You need a fresh openHAB instance to start with.

**Comment by weymann** [comment]
> As the thingtypeversion needs to be updated each time, you can not do this on your an instance you already used. You need a fresh openHAB instance to start with.

Ok, all I want to know if I can test test the `instructions.xml` or not. From your last comment it looks like I'm not able to test it. So I trust on your latest remark and provided already the `update-channel` instructions.

**Comment by lsiepel** [comment]
> > As the thingtypeversion needs to be updated each time, you can not do this on your an instance you already used. You need a fresh openHAB instance to start with.
> 
> Ok, all I want to know if I can test test the `instructions.xml` or not. From your last comment it looks like I'm not able to test it. So I trust on your latest remark and provided already the `update-channel` instructions.

It is testable, but because it was already tried you need a new openHAB instance to retry

**Comment by weymann** [comment]
> It is testable, but because it was already tried you need a new openHAB instance to retry

Please enlighten me. 
I've everything available. A raspi free available which I can install/update/upgrade at any time.
What are the steps to test this PR in order to check the `instructions.xml` correctly?

**Comment by jlaur** [comment]
> It is testable, but because it was already tried you need a new openHAB instance to retry

That is not needed. When you go back to the previous version (any version before this PR) and create a Thing, that Thing will be created with the previous thingTypeVersion. After that, install the new version again, and the upgrade will be triggered. You can check the `thingTypeVersion` property before and after, and if it's incremented by 1, the upgrade succeeded. If the channels are not fixed then, the instructions are probably faulty. When the instructions are executed, there should also be something logged in case of errors.

**Comment by lsiepel** [comment]
> > It is testable, but because it was already tried you need a new openHAB instance to retry
> 
> That is not needed. When you go back to the previous version (any version before this PR) and create a Thing, that Thing will be created with the previous `thingTypeVersion`. After that, install the new version again, and the upgrade will be triggered. You can check the `thingTypeVersion` property before and after, and if it's incremented by 1, the upgrade succeeded. If the channels are not fixed then, the instructions are probably faulty. When the instructions are executed, there should also be something logged in case of errors.

Good addition to check the thingtypeversion. I always use a new instance, have had too many issues because previous upgrades, same thing uids etc. But it is not essential.

**Comment by weymann** [comment]
Thanks for the hint to check `thingTypeVersion` in previous created `things`. 
With this I realized no update was performed on the previous things and my stupid error was simply `instructions.xml` was placed in the wrong folder :(

Now old things are updated with correct `thingTypeVersion` and channels are updated correctly.

Many thanks for helping!

**Review by lsiepel — APPROVED** [review]
LGTM

**Pull request merged**
