### PR TITLE
[keba] Improve connection establishment and stability

### PR DESCRIPTION
**Pull request by MikeTheTux**
Pull reequest for https://github.com/openhab/openhab-addons/issues/6347#issuecomment-778797191

My first ever. Please be patient.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks!
Two questions upfront:
1. You mentioned that (parts of) the code is from @Raketenschnitzel - if this is the case, you should mention him in the sign-off and we must have his approval for contributing the code.
2. Git shows all classes completely changes in this PR instead of just highlighting the lines with code changes. Any idea why this is? This makes reviewing pretty difficult...

**Comment by MikeTheTux** [comment]
You are right! But sorry, I do not know how to reach out to @Raketenschnitzel in order to ask for his approval.
He might reply to this conversation, as he is mentioned ...

I recognized the bad diff already. It's m first time using this development toolchain. Maybe some bad settings in the editor ...
I will give that a look in the evening.

**Comment by MikeTheTux** [comment]
re 1) still open
re 2) resolved
new problem:
3.) DCO conflict, that I cannot resolve

**Comment by MikeTheTux** [comment]
In order to resolve the technical problems with this PR, I created the following new one #10179

**Pull request closed without merging**
