### PR TITLE
[surepetcare] Fix possible timeout bug

### PR DESCRIPTION
**Pull request by lsiepel**
- Resolves https://github.com/openhab/openhab-addons/issues/11527
- Minor java17 improvements

Test jar is here: 4.1.0: https://1drv.ms/u/s!AnMcxmvEeupwjrMwEoS1zTCIf2zmxQ?e=9dOG5d

### CODE REVIEW

**Review by renescherer — APPROVED** [review]
Thanks very much for the improvement.

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by wborn** [comment]
I think other add-ons have similar issues after briefly looking at the search results of [request.send()](https://github.com/search?q=repo%3Aopenhab%2Fopenhab-addons+request.send%28%29%3B&type=code).

**Comment by lsiepel** [comment]
> I think other add-ons have similar issues after briefly looking at the search results of [request.send()](https://github.com/search?q=repo%3Aopenhab%2Fopenhab-addons+request.send%28%29%3B&type=code).

I’ll look at those too, next week. Thanks.

**Pull request merged**
