### PR TITLE
[vwweconnect] [WIP] Initial contribution

### PR DESCRIPTION
**Pull request by jannegpriv**
My goal is to add support for the VW We Connect portal to openHAB.

New PR to openHAB 3.0, old PR #8314 can be closed.

Link to community thread with URL to latest built jar-file for openHAB 2.0:
https://community.openhab.org/t/new-binding-volkswagen-we-connect/92057

Signed-off-by: Jan Gustafsson <jannegpriv@gmail.com>

### CODE REVIEW

**Comment by fwolter** [comment]
What's the state of this PR? Do you like it to be reviewed?

**Comment by fwolter** [comment]
As the backlog of open PRs is quite big currently, I will postpone the review, also because it is WIP.

**Comment by jannegpriv** [comment]
That is OK, maybe better choice to go for @markus7017 CarNet binding, one binding to rule them all (Audi/VW).

**Comment by hmerk** [comment]
@jannegpriv Since apache.commons is deprecated and removed, your Binding does not start any longer under openHAB 3.1 M3.
Could you possibly provide a fix for that ?

**Comment by jannegpriv** [comment]
Web API has been deprecated, let's go for the CARNET binding.

**Pull request closed without merging**
