### PR TITLE
[http] Fix brightness

### PR DESCRIPTION
**Pull request by constambeys**

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
Please sign-off properly your PR.

**Comment by constambeys** [comment]
> Please sign-off properly your PR.

Is it ok now?

**Comment by lolodomo** [comment]
> Is it ok now?

No !

But as this is a very small change and as the change is obviously needed, I am going to merge your PR.

**Comment by constambeys** [comment]
Perfect, thanks 👍

**Pull request merged**
