### PR TITLE
[knx] Change the conversion of the DPT251.600 to use RGB and White.

### PR DESCRIPTION
**Pull request by genesis81**
With the new feature, the HSBType is converted into RGBW, and we convert the status signal from the KNX back into an HSB value.

Due to the conversion, some accuracy is lost, but the result is approximately correct.

Need #https://github.com/openhab/openhab-core/pull/3849 to work.

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
Rebuilds can be triggered by adding and removing the label "rebuild".
Btw: We have to wait until the nightly build of core creates another snapshot.

**Comment by J-N-K** [comment]
I have triggered a core build. It should be available in about an hour.

**Comment by genesis81** [comment]
> Rebuilds can be triggered by adding and removing the label "rebuild". Btw: We have to wait until the nightly build of core creates another snapshot.

Thanks for the information, but my mistake was that i pull the acutal branch and push. I didn't see that i lost my changes. Normaly i work with .NET and Visual Studio. NetBeans is not my prefered IDE.

**Comment by genesis81** [comment]
> Rebuilds can be triggered by adding and removing the label "rebuild". 

I can't apply new labels to the Pull Request. No rights.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
Let's wait still few days for a potential feedback from @kaikreuzer or @holgerfriedrich

**Comment by holgerfriedrich** [comment]
Pls do not merge yet.

**Comment by holgerfriedrich** [comment]
This PR would actually change the behavior of the binding. As of now you can use HSBType for RGB and a PercentType for the W channel.

I think it is useful to bring in the conversion from RGBW which merges RGB and W into HSBType - but users should be able to select both the old and the proposed handling. I am thinking of using a custom DPT like 251.60600.

I already have a draft for this, give me some time to check.

**Comment by lolodomo** [comment]
> Pls do not merge yet.

I added the tag "won't fix", even if not really appropriate, to avoid a merge.
Should we simply close this PR @holgerfriedrich  ?

**Comment by genesis81** [comment]
Done with https://github.com/openhab/openhab-addons/pull/16078

**Pull request closed without merging**
