### PR TITLE
[astro] Adressing issue #5732

### LINKED ISSUE #5732: [astro] Update Astro binding to use local country data for calculating seasons
## Your Environment

* Version used: OpenHAB 2.4 stable
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): openHABian v1.4.1-468

Apparently season start and end dates are not consistently applied between countries. Some countries commence their seasons on the equinox or solstice (which may be the current Astro binding behaviour) however this differs between countries. In Australia the following is true:
Spring starts 1st September
Summer starts 1st December
Autumn starts 1st March
Winter starts 1st June 

Potential solutions include using location data to set the correct season behaviour or (if this is too complex due to the huge variance in how seasons are recorded) alternatively allow the user to set it themselves in the binding. I'm sure there are other options also.

Associated links:
https://github.com/eclipse/smarthome/issues/4767#issuecomment-501120686
https://community.openhab.org/t/oh2-astro-binding-feature-request-seasons-in-australia/37367/4

### PR DESCRIPTION
**Pull request by clinique**
Closes #5732

Signed-off-by: Gaël L'hopital <gael@lhopital.org>

### CODE REVIEW

**Comment by clinique** [comment]
@cpmeister , @gerrieg : integration tests seems to fail due to normal failures :-/ I don't know how to proceed

**Comment by lolodomo** [comment]
This will enter in conflict with my own changes in the discovery service in PR #7850.

**Comment by cpmeister** [comment]
There are already conflicts.

**Comment by clinique** [comment]
> This will enter in conflict with my own changes in the discovery service in PR #7850.

Reverting the modification on AstroDiscoveryService so we will not conflict.

**Comment by clinique** [comment]
@lolodomo : Once your [PR](https://github.com/openhab/openhab-addons/pull/7850) is merged I will proceed with my changes in AstroDiscoveryService

**Comment by clinique** [comment]
@cpmeister : travis fails on integration tests for other bindings. Can you still review ?

**Comment by J-N-K** [comment]
Travis fails unrelated, build and tests for astro succeed

**Comment by J-N-K** [comment]
Can you edit the sign-off in the first post to include your real-name and use that one in further commits? Thanks.

**Comment by clinique** [comment]
@J-N-K : sorry, I do not get your comment, all my commits are signed as usually using my personal mail adress.

**Comment by cpmeister** [comment]
He is asking for a sign-off that uses a real name, not a github username.

**Comment by J-N-K** [comment]
Like:  `Jan N. Klug <jan.n.klug@rub.de>` instead of `J-N-K <jan.n.klug@rub.de>`

**Pull request merged**
