### PR TITLE
[airq] Add Hydrogen Sulfide (H₂S)

### PR DESCRIPTION
**Pull request by fwolter**
This PR depends on #16694.

### CODE REVIEW

**Comment by lsiepel** [comment]
Please rebase now the other pr is merged.

**Review by lsiepel — CHANGES_REQUESTED** [review]
As a channel is added to an existing thing, upgrade instruction is needed. I should have seen this at the rebase request.
Details here: https://www.openhab.org/docs/developer/bindings/thing-xml.html#updating-thing-types

**Comment by fwolter** [comment]
Thanks for the link! I know there was something. I searched for "Thing migration", but couldn't find anything. Now, I know why.

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by fwolter** [comment]
Thanks!

**Pull request merged**
