### PR TITLE
[sensebox] Fixed potential NPE introduced in PR 8171

### PR DESCRIPTION
**Pull request by cweitkamp**
- Fixed potential NPE introduced in PR #8171

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Is this only "potentially" or an actual problem in the 2.5.7 build that just finished today?

**Comment by cweitkamp** [comment]
To be honest I am not sure. I did not see it yet - the boxes I am tracking seem to expose those data or an empty String. This is an additional safe-guard because `org.apache.commons.lang.StringUtils` methods always checked for `null` first.

**Comment by heiler** [comment]
With version 2.5.7 I see 

```
2020-07-25 12:08:39.743 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.openhab.binding.sensebox.internal.SenseBoxAPIConnection.reallyFetchDataFromServer(SenseBoxAPIConnection.java:141) ~[?:?]
	at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.lambda$0(SenseBoxHandler.java:106) ~[?:?]
	at org.eclipse.smarthome.core.cache.ExpiringCache.refreshValue(ExpiringCache.java:101) ~[?:?]
	at org.eclipse.smarthome.core.cache.ExpiringCache.getValue(ExpiringCache.java:72) ~[?:?]
	at org.eclipse.smarthome.core.cache.ExpiringCacheMap.get(ExpiringCacheMap.java:198) ~[?:?]
	at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.fetchData(SenseBoxHandler.java:163) ~[?:?]
	at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.handleCommand(SenseBoxHandler.java:119) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

2020-07-25 12:08:39.792 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.openhab.binding.sensebox.internal.SenseBoxAPIConnection.reallyFetchDataFromServer(SenseBoxAPIConnection.java:141) ~[?:?]
	at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.lambda$0(SenseBoxHandler.java:106) ~[?:?]
	at org.eclipse.smarthome.core.cache.ExpiringCache.refreshValue(ExpiringCache.java:101) ~[?:?]
	at org.eclipse.smarthome.core.cache.ExpiringCache.getValue(ExpiringCache.java:72) ~[?:?]
	at org.eclipse.smarthome.core.cache.ExpiringCacheMap.get(ExpiringCacheMap.java:198) ~[?:?]
	at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.fetchData(SenseBoxHandler.java:163) ~[?:?]
	at org.openhab.binding.sensebox.internal.handler.SenseBoxHandler.handleCommand(SenseBoxHandler.java:119) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Is this bug covered by this fix?

Kind regards

**Comment by cweitkamp** [comment]
Yes, that is exactly the case covered by this fix.

**Pull request merged**
