### PR TITLE
[gpstracker][WIP] Life360 application support

### PR DESCRIPTION
**Pull request by gbicskei**
This PR adds Life360 support to the binding using available REST API.

### CODE REVIEW

**Comment by gbicskei** [comment]
@kaikreuzer @wborn 
Hi,
I have an OH related technical question. Life360 allows the clients to register a callback URI for circle events which will be called by Life360 in cases like someone enters/leaves a place. The problem is the authorization: BASIC authentication is not available, the client should provide an access token at the time or callback registration which will be used by myopenhab.org to authorize the callback call. This is the same scenario as the Google Assistant integration just the Life360 doesn't provide a UI to link the accounts. The question: is there a way to generate an access token e.g. at binding startup that is acceptable by myopenhab.org.
Thanks

**Comment by kaikreuzer** [comment]
@gbicskei Unfortunately not. myopenHAB does not have any easy way to authenticate through OAuth2/tokens at myopenHAB - Basic Auth is the only option.

**Comment by gbicskei** [comment]
@openhab/2-x-add-ons-maintainers 
Hi,
The pull request [build ](https://travis-ci.org/gbicskei/openhab2-addons/builds/578702000?utm_medium=notification&utm_source=email) fails with timeout. Could you please check.
Thanks

**Comment by kaikreuzer** [comment]
PR build is running: https://ci.openhab.org/job/PR-openHAB2-Addons/14992/console

**Comment by gbicskei** [comment]
@openhab/2-x-add-ons-maintainers 
The build is still not OK. It fails on build of a binding not connected to this PR...

**Comment by kaikreuzer** [comment]
Ignore the Jenkins PR build for now - as long as the Travis build succeeds and a local build is ok for you, that should be just fine!

**Comment by Hilbrand** [comment]
What is the status of this enhancement?

Is the life360 using OAuth2 authentication? and if so can the user register with their own callback url? This is something used among others by the Spotify binding, where the user registers a callback to their own local openHAB instances, which is a servlet that is part of the binding. Is that something that could work here? Or does it use a completely different authentication method?

**Comment by Hilbrand** [comment]
Closing due to long time no feedback. If you still want this change added you can reopen this pull request. If you need help feel free to ask.

**Pull request closed without merging**
