### PR TITLE
[miele] Fix supercool/superfreeze for fridges/fridge-freezers

### LINKED ISSUE #11320: [miele] Channels supercool/superfreeze for fridge/fridge-freezer are not working
Channels **supercool** and **superfreeze** for fridges and fridge-freezers are not working.

Both channels are declared as read-only strings, but should have been writable switches, and are in fact handled as switches in handleCommand:

```
case SUPERCOOL: {
    if (command.equals(OnOffType.ON)) {
        result = bridgeHandler.invokeOperation(applianceIdentifier, modelID, "startSuperCooling");
    } else if (command.equals(OnOffType.OFF)) {
        result = bridgeHandler.invokeOperation(applianceIdentifier, modelID, "stopSuperCooling");
    }
```

Furthermore, the channels are not updated according to current operation of the fridge/fridge-freezer.

## Expected Behavior
- The two channels should be of type Switch.
- The two channels should be writable.
- Setting to ON should start super cooling/freezing.
- Setting OFF should stop super cooling/freezing.
- When operation is selected from appliance directly, through Miele app or in some other way, the settings should be reflected in these channels.

## Current Behavior
The channel declarations do not correspond to the command handling. It might be possible to set linked items to values "ON" or "OFF" as string through a rule, not sure if it will work, especially since defined as read-only channels.

For sure the channels are never updated from the outside, but will only serve as triggers.

## Possible Solution
Change channels to be of Switch type. This will by principle be a breaking change, but in this case it's already broken, so should not be a problem.

## Steps to Reproduce
Link an item to one of the channels of include it in a sitemap. Observe that string is empty and nothing can be done with it.

## See also
This issue was extracted from #11317 as distinct bug.

### PR DESCRIPTION
**Pull request by jlaur**
Fix channels **supercool** and **superfreeze** for fridges/fridge-freezers.

Both channels were declared as read-only strings, but should have been writable switches, and are in fact handled as switches in handleCommand:

```
case SUPERCOOL: {
    if (command.equals(OnOffType.ON)) {
        result = bridgeHandler.invokeOperation(applianceIdentifier, modelID, "startSuperCooling");
    } else if (command.equals(OnOffType.OFF)) {
        result = bridgeHandler.invokeOperation(applianceIdentifier, modelID, "stopSuperCooling");
    }
```

Furthermore, the channels were not updated according to current operation of the fridge/fridge-freezer. This fix enables two-way synchronization of the supercool/superfreeze state by using the **state** property.

See more details in linked issue.

## Testing
Tested with fridge.

Initial sitemap:
image

Enable:
image

Verify state in Miele app:
image

Disable:
image

Verify state in sitemap:
image

## Pull request note
This fix was provided as part of some planned channel quality improvements. See #11317 for intentions/possible next steps.

Fixes #11320 

Signed-off-by: Jacob Laursen <jacob-github@vindvejr.dk>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@kgoderis : as author or maintainor, of this binding, can you please have a look?

**Comment by jlaur** [comment]
> @kgoderis : as author or maintainor, of this binding, can you please have a look?

That would be really desirable, but FYI he seems inactive since November last year: #8902

**Comment by lolodomo** [comment]
@jlaur : ok. Do you want to become an official maintainor if this binding?

**Comment by jlaur** [comment]
> @jlaur : ok. Do you want to become an official maintainor if this binding?

If we are sure that @kgoderis would like to resign as maintainer of his binding - sure, I can step in. Miele has abandoned the XGW 3000 gateway for which the binding was created, so there won't be any improvements/changes in the gateway. I will continue fixing the issues I'm finding and enhancing probably until the binding supports all features of the gateway. After that probably only keeping up with openHAB/Java will be required, i.e. maintenance.

**Comment by lolodomo** [comment]
We can have several maintainers defined for a binding. 
If you know well its code and are ok to maintain it and look at PRs by others for this binding, I suggest that you push a PR adding you as maintainer in the file CODEOWNERS, without suppreaaing kgoderis.

**Pull request merged**
