### PR TITLE
[homekit] Fix documentation and "CLOSED" state

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by cpmeister** [comment]
Are you only changing the formatting of the readme? I suspect you are changing the line endings used in the file as well.

**Comment by ecdye** [comment]
That and fixing a verb that currently says CLOSE when it should be CLOSED

**Comment by J-N-K** [comment]
@yfre Is this code-change correct?

**Comment by yfre** [comment]
@ecdye thank you for improving the README and fixing the bug in the code. 
@J-N-K the changes look ok for me.

**Pull request merged**
