### PR TITLE
[groovyscripting] Update Groovy to 4.0.24

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
Updates Groovy from 4.0.23 to 4.0.24.

### CODE REVIEW

**Review by wborn — CHANGES_REQUESTED** [review]
You'll need to resolve the itest runbundles:

https://github.com/openhab/openhab-addons?tab=readme-ov-file#integration-tests

and fix the signoff.

**Comment by dilyanpalauzov** [comment]
Exactliy the same changes, as presented here, were done for the upgrades 4.0.11 → 4.0.22 and 4.0.22 → 4.0.23.

**Comment by wborn** [comment]
I looked closer 🕵️ and now see that this change apparently makes the bundle depend on Jackson 2.18 while openHAB only provides Jackson 2.17:

`requirement [org.openhab.automation.groovyscripting/4.3.0.202412120841] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.fasterxml.jackson.core)(version>=2.18.0)(!(version>=3.0.0)))"]]
`

See: https://github.com/apache/groovy/commits/GROOVY_4_0_X/

**Comment by dilyanpalauzov** [comment]
I do not know how to fix this in reasonable time.

**Comment by wborn** [comment]
Perhaps we can fix it by changing the dependency version in the pom.xml file. Maybe I find some time to test that after the OH 4.3 release.

**Pull request closed without merging**
