### PR TITLE
[jsscriptingnashorn] Set service id

### PR DESCRIPTION
**Pull request by florian-h05**
Sometimes, the REST API returns the Nashorn add-on info for the GraalJS addon. I am suspecting some issue with addon id here, therefore let's see if this helps.

### CODE REVIEW

**Comment by wborn** [comment]
> Sometimes, the REST API returns the Nashorn add-on info for the GraalJS addon

Which API call(s) have this issue?

**Comment by florian-h05** [comment]
When both JS Scripting add-ons are installed, `/rest/addons/automation-jsscripting` returns:

```json
{
    "uid": "automation-jsscripting",
    "id": "jsscripting",
    "label": "JavaScript Scripting (Nashorn)",
    "version": "4.0.0.SNAPSHOT",
    "compatible": true,
    "contentType": "application/vnd.openhab.feature;type\u003dkaraf",
    "link": "https://www.openhab.org/addons/automation/jsscripting/",
    "author": "openHAB",
    "verifiedAuthor": true,
    "installed": true,
    "type": "automation",
    "description": "This adds a JS (Nashorn) script engine.",
    "configDescriptionURI": "",
    "keywords": "",
    "countries": [
        ""
    ],
    "connection": "",
    "properties": {},
    "loggerPackages": [
        "org.openhab.automation.jsscripting"
    ]
}
```

And `/rest/addons/automation-jsscriptingnashorn` returns:

```json
{
    "uid": "automation-jsscriptingnashorn",
    "id": "jsscriptingnashorn",
    "label": "JavaScript Scripting (Nashorn)",
    "version": "4.0.0.SNAPSHOT",
    "compatible": true,
    "contentType": "application/vnd.openhab.feature;type\u003dkaraf",
    "link": "https://www.openhab.org/addons/automation/jsscriptingnashorn/",
    "author": "openHAB",
    "verifiedAuthor": true,
    "installed": true,
    "type": "automation",
    "configDescriptionURI": "",
    "keywords": "",
    "countries": [],
    "connection": "",
    "properties": {},
    "loggerPackages": [
        "org.openhab.automation.jsscriptingnashorn"
    ]
}
```

**Comment by J-N-K** [comment]
The addon.xml of Nashorn scripting is wrong.

**Comment by J-N-K** [comment]
Since this is not the cause of your issues (see attached PR), I'm closing here.

**Pull request closed without merging**
