### PR TITLE
[homeconnect] Undo PR 10754

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by bruestel — APPROVED** [review]

**Comment by fwolter** [comment]
There's a conflicting file, now.

**Comment by fwolter** [comment]
Shall #10754 be removed from the milestone, i.e. the changelog?

**Comment by lolodomo** [comment]
> 
> 
> There's a conflicting file, now.

I just fixed it.

PS: thank you for your different merges.

**Comment by lolodomo** [comment]
> 
> 
> Shall #10754 be removed from the milestone, i.e. the changelog?

I believe it was included in 3.1M5 but not included in the milestone changelog.
But if your question is relative to the final 3.1 release, yes it owuld be better to exclude PR 10754 and 10792 from the final changelog.

**Review by fwolter — APPROVED** [review]

**Pull request merged**
