### PR TITLE
[hue] Fix exception text in bridge status description

### PR DESCRIPTION
**Pull request by jlaur**
Related to #15460

Usages:
https://github.com/openhab/openhab-addons/blob/fef05c33220bc368fd9d0166dc403410f21aa880/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java#L470-L471

https://github.com/openhab/openhab-addons/blob/fef05c33220bc368fd9d0166dc403410f21aa880/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java#L494-L495

https://github.com/openhab/openhab-addons/blob/fef05c33220bc368fd9d0166dc403410f21aa880/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java#L687-L688

Documentation: https://www.openhab.org/javadoc/latest/org/openhab/core/thing/i18n/thingstatusinfoi18nlocalizationservice

### CODE REVIEW

**Review by andrewfg — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
@openhab/add-ons-maintainers - this small fix would be nice to have cherry-picked into `4.0.x` in order to get better issue reports.

**Comment by jlaur** [comment]
@openhab/add-ons-maintainers - one line review, please? I can cherry-pick myself, if you let me. 😉

**Comment by wborn** [comment]
Permission granted 😄

**Review by wborn — APPROVED** [review]

**Pull request merged**
