### PR TITLE
[neohub] Destroy the web socket client when disposing thing handler

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by andrewfg — APPROVED** [review]
LGTM thank you.

**Comment by jlaur** [comment]
@lolodomo - to me it's not obvious what is being fixed here without any description. I would probably assume it's a memory leak, but I hope you can provide a bit more insight. I can see that Jetty `WebSocketClient` implements [Destroyable](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/component/Destroyable.html). This raises two questions for me:
- After being destroyed it can no longer be started. I didn't check if this is needed, but since you mention "when disposing thing handler" in PR title, I assume not.
- Since it's a LifeCycle component, are we sure it wouldn't be automatically destroyed later? How much have you tested/verified that we indeed have a memory leak?

I hope you can help me by explaining this, then I would also be able to go through the other PR's.

**Comment by lolodomo** [comment]
> to me it's not obvious what is being fixed here without any description or linked issue. I would probably assume it's a memory leak, but I hope you can provide a bit more insight. I can see that Jetty `WebSocketClient` implements [Destroyable](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/component/Destroyable.html).

I realized I asked the question but had no answer. 
https://github.com/openhab/openhab-addons/issues/8027#issuecomment-653867133

**Comment by lolodomo** [comment]
I am closing this PR as I am not able to prove that this call to destroy is needed.

**Pull request closed without merging**
