### PR TITLE
[bluetooth.bluez] Prevent excessive warnings when bluez is not present.

### LINKED ISSUE #10136: [bluetooth.bluez]  Discovery cause always errors
Environment which doesn't have DBus like OS X, Bluetooth discovery spit every time following exception

```
12:19:04.434 [qtp464949400-60] ERROR o.o.c.c.d.i.DiscoveryServiceRegistryImpl:380 - Cannot trigger scan for thing types '[bluetooth:bluez]' on 'BlueZDiscoveryService'!
java.util.concurrent.CompletionException: org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address: MachineId file can not be found
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.openhab.binding.bluetooth.util.RetryFuture$CallableTask.run(RetryFuture.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address: MachineId file can not be found
	at org.freedesktop.dbus.connections.impl.DBusConnection.lambda$determineMachineIdFile$5(DBusConnection.java:320)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.freedesktop.dbus.connections.impl.DBusConnection.determineMachineIdFile(DBusConnection.java:320)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getDbusMachineId(DBusConnection.java:303)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:149)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:169)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:219)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184)
	at com.github.hypfvieh.bluetooth.DeviceManager.createInstance(DeviceManager.java:74)
	at org.openhab.binding.bluetooth.bluez.internal.DeviceManagerFactory.lambda$0(DeviceManagerFactory.java:82)
	at org.openhab.binding.bluetooth.util.RetryFuture$CallableTask.run(RetryFuture.java:67)
	... 6 common frames omitted

```

At the moment, user can install only bluetooth binding, which then install all bluetooth related bundles (also BlueZ).

Short term solution could be to change logging level of BlueZ binding or just log error ones during start.

Possible long term solution could be that bluetooth binding will be separated to multiple bindings. Then user can select only features which are needed (e.g. BlueGiga + Airthings).

### PR DESCRIPTION
**Pull request by cpmeister**
Fixes #10136.

Signed-off-by: Connor Petty <mistercpp2000+gitsignoff@gmail.com>

### CODE REVIEW

**Review by kaikreuzer — CHANGES_REQUESTED** [review]
Sorry, not as good as https://github.com/openhab/openhab-addons/pull/10153 yet.
When starting the bluez bundle, I still have a warning in the log:
```
21:32:53.827 [pipe-start 152] DEBUG o.o.b.b.b.i.DeviceManagerFactory:78 - initializing DeviceManagerFactory
21:32:53.827 [OH-bluetooth-1] WARN  o.o.b.b.b.i.DeviceManagerFactory:112 - Failed to initialize DeviceManager: org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address: MachineId file can not be found
```

**Comment by cpmeister** [comment]
I made sure that only a single warning would be printed in the log since it is still necessary to log something in the case someone is _supposed_ to have bluez on their machine but it still doesn't work for whatever reason. I don't want to take away debugging ability for legitimate use cases.

**Comment by cpmeister** [comment]
Would you like me to exclude that log from machines that don't have bluez present on their system?

**Comment by kaikreuzer** [comment]
Yes, clearly for a system where there is no BlueZ or DBus, no warning or error must be logged.

**Comment by kaikreuzer** [comment]
@cpmeister Any update here?

**Comment by kaikreuzer** [comment]
As https://github.com/openhab/openhab-addons/pull/10153 has been merged, I close this PR - please feel free to re-open it if you find a better solution!

**Pull request closed without merging**
