### PR TITLE
[homekit] allow NumberItems for BatteryLowStatus

### PR DESCRIPTION
**Pull request by ccutrer**
use a lowThreshold metadata config to infer if it's low

### CODE REVIEW

**Review by lolodomo — CHANGES_REQUESTED** [review]
Just one minor comment about javadoc

**Comment by lolodomo** [comment]
@yfre : please have a look.

**Review by lolodomo — APPROVED** [review]
LGTM

**Review by yfre — APPROVED** [review]
LGTM

**Comment by yfre** [comment]
@ccutrer thank you! it saves some rules for me (and for sure for others as well)

**Pull request merged**
