### PR TITLE
[homepilot] HomePilot Binding initial contribution

### PR DESCRIPTION
**Pull request by stundzig**
Hi,

I've updated my binding for Rademacher HomePilot to the latest 2.5.0-SNAPSHOT. I've also done some code cleanups.

Could you please check my implementations? I would like to contribute them to the main openhab.

Thanks.

Regards
Steffen...

### CODE REVIEW

**Comment by Hilbrand** [comment]
Hi @stundzig Do you still want to continue having the HomePilot merged or do you need any help?

**Comment by stundzig** [comment]
> Hi @stundzig Do you still want to continue having the HomePilot merged or do you need any help?

Hi, i would like to continue the requested pull request. But i need a little bit more time.

**Comment by cpmeister** [comment]
@stundzig Any progress on this?

**Comment by Hilbrand** [comment]
Closing due to long time no activity. If you still want this binding merged do reopen it and push changes to this pull request as there are still valuable comments that should be addressed and otherwise are difficult to track.

**Pull request closed without merging**
