### PR TITLE
[boschindego] Add missing specialized text for unreachable device

### PR DESCRIPTION
**Pull request by jlaur**
Small fix for #13040 as specialized text for unreachable device was missing, so it would should "Gateway timeout" where it should show "Device is unreachable".

### CODE REVIEW

**Comment by lolodomo** [comment]
To be clean, shouldn't you mention `IndegoUnreachableException` in each method that can throw this exception and also in the javadoc of these methods ?

**Comment by jlaur** [comment]
> To be clean, shouldn't you mention `IndegoUnreachableException` in each method that can throw this exception and also in the javadoc of these methods ?

I have documented it on relevant paths now.

**Comment by jlaur** [comment]
@BillGOH - latest version here, also including the SpotMow status code: https://drive.google.com/file/d/1caMAEgdSEAMYGJ0xgoYGp8al9gDsm5GW/view?usp=sharing

**Comment by lolodomo** [comment]
What about getState, getCalendar, getWeather, ...

**Comment by jlaur** [comment]
> What about getState, getCalendar, getWeather, ...

I only mentioned it on relevant paths, where it's expected to happen, i.e. `getOperatingData()`. In any case it's sufficient to catch `IndegoException` from which `IndegoUnreachableException` is derived, but when mentioned it should be considered whether `IndegoUnreachableException` should be handled differently.

It's already a bit too much IMHO, but on the other hand it doesn't hurt to expose it in Javadoc for considering more fine-grained exception handling. In standard Java libraries you will often see only the superclass documented, for example [IOException](https://docs.oracle.com/javase/7/docs/api/java/io/IOException.html). I'm not sure about the distinction here, but in specific scenarios the direct subclass is also documented. Perhaps when there is only one or a few possible types thrown? For example, it's documented that the constructor of `FileInputStream` can throw `FileNotFoundException`, but in this case I think no other IOExceptions are possible.

**Comment by jlaur** [comment]
> I only mentioned it on relevant paths, where it's expected to happen, i.e. `getOperatingData()`. In any case it's sufficient to catch `IndegoException` from which `IndegoUnreachableException` is derived, but when mentioned it should be considered whether `IndegoUnreachableException` should be handled differently.

Just to add some more context: `getOperatingData()` is the only method which will directly contact the device, so only this method is subject to gateway timeout when doing so. Other methods will be handled directly by Bosch services, for example `getState()` will respond nicely even when the device has been turned off for several days. `getWeather()` has nothing specific to do with the device, except that's in context of the device's location. If other methods will unexpectedly cause gateway timeout, it should not be handled as device not being reachable.

**Comment by lolodomo** [comment]
Ok, my fault, I did not notice the unreachable exception was derived from the other. So no risk to miss this exception.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
