### PR TITLE
[mqtt.homie] build a per-thing thing type

### LINKED ISSUE #9728: [mqtt.homie] Missing Channel Groups
As I understood the documentation, the UI should group the channels by the corresponding nodes for Homie thing. But instead there is only a list of channels, and no groups shown.
The grouping feature I'm missing can be seen in a [screenshot of OpenWeatherMap binding](https://community-openhab-org.s3.dualstack.eu-central-1.amazonaws.com/original/3X/7/6/7674870c1bdeed0be3cdf6df3b2d1fdafb54be24.png). Please note the channels grouped in "Wetterstation" and "Aktuelles Wetter"

## Expected Behavior
Autodetect a thing having multiple nodes with multiple channels each.
When created, in the UI the thing should group all channels by their nodes.
3 nodes with 2 channels each, should result in 3 channel groups named by their nodes and having 2 channels appropriately to the node properties.

## Current Behavior
All channels are listed in one list, there is no grouping in the UI.

## Possible Solution
Group the channels by their nodes as described in the [documentation](https://www.openhab.org/addons/bindings/mqtt.homie/).

## Steps to Reproduce (for Bugs)
1. Auto-discover a MQTT Homie Thing, having multiple homie nodes with multiple homie properties each.
2. Create the thing from inbox when it was auto-discovered.
3. Show the thing details in the UI
4. Find a list of all channels, but without grouping.

## Context
I have a device with multiple sensors, each sensor can have/publish multiple values. Simple example: 3 temperature sensors, each with properties "temperature" and "enabled". First one measures temperature. Second one defines whether the sensor is enabled or disabled, this property is settable.
When auto-discovering and creating the thing in openHAB, I get a list of all channels. But as there is no grouping, the list contains 3 entries "temperature"  and 3 entries "enabled".
It's OK to search a list of 6 entries, but the full blown device has 16 nodes with 3-5 properties each, while nodes of the same type have properties of same name. A list of 60-80 ungrouped items would be easier to manage if that grouping feature would work.

## Your Environment
* openHAB version: 2.5.10 (Paper UI), 2.5.11 (Paper UI), 3.0.0 (Main UI)
* Firefox 84, Chrome 87
* Java Zulu 8 (current) for openHAB 2.5.x, Java AdoptOpenJDK 11.0.9.101 for openHAB 3.0.0
* Windows 10 (current)
* Device implements Homie 3.0.1
* MQTT server: Mosquitto, on external system (not provided by openHAB)

Thx guys!

### PR DESCRIPTION
**Pull request by ccutrer**
Otherwise channel groups don't show up correctly in MainUI (in actual groups with a heading).

Note that this is completely backwards compatible - even though Things change their ThingTypeUID after they're created, their UID does _not_ change, so no channel UIDs change either.

A happy consequence of building ChannelDefinitions for the ThingType is that custom ChannelTypes are no longer necessary - the only variable parts are labels and state/command descriptions, which are overridden by the ThingType's ChannelDefinition and the DynamicStateDescriptionProvider respectively. This can greatly increase responsiveness of MainUI if you have many Homie things with many channels. My /rest/channel-types response went from 2.6MB to 175KB. Since the full list of thing types is never queried, there's no corresponding increase anywhere else.

Fixes #9728, #11704

### CODE REVIEW

**Comment by lolodomo** [comment]
Build failed in tests.

**Comment by ccutrer** [comment]
ping @lolodomo. I know this is a large PR, but I've got additional commits waiting for this to merge, including a similar change for Home Assistant, and then on top of those two using AbstractStorageBasedTypeProvider so that both Homie and Home Assistant things don't have the two minute delay before going online after an openHAB restart.

**Comment by ccutrer** [comment]
Ping @jlaur @lolodomo

**Review by lsiepel — APPROVED** [review]
LGTM. As i'm no Homie expert i can't fully asses the backwards compatibility. Before i merge this, can you confirm it is well tested and does not need a breaking change alert in the openhab-distro ?

**Comment by ccutrer** [comment]
Yes, I can confirm that this is fully backwards compatible. I've been running this for over a year in my production, environment at this point, at two others for nearly 6 months.

**Pull request merged**
