### PR TITLE
[mqtt.homeassistant] Remove newStyleChannels temporary back-compat

### PR DESCRIPTION
**Pull request by ccutrer**
This includes removing deprecated channel IDs controlled by the same flag.

### CODE REVIEW

**Comment by lsiepel** [comment]
So you want to merge it this quick? It would make it harder to create patch releases, due to conflicts. Maybe wait for the first patch release to arrive?

**Comment by ccutrer** [comment]
I'm fine with waiting a bit. If I do any more enhancements, I'll just base them on top of this commit, and not send a PR until this merges.

**Comment by lsiepel** [comment]
As a follow up to the 4.3.0 upgrade notice, you might want to consider a similar 5.0.0 warning. For those who forgot, or skipped a version.

**Comment by ccutrer** [comment]
I was already planning on it. Thanks for the reminder.

**Pull request merged**
