### PR TITLE
[digitalstrom] Fix initialization of temperature control devices

### LINKED ISSUE #10649: [digitalstrom] Scheduled runnable ended with an exception
I'm running openHAB 3.0.1 release build. I just wanted to test the dss-IP device from digitalstrom with the coresponing binding in openhab.
I entered the network adresse, username and password and I get this error in the log file once I start the binding.

```
2021-05-05 12:30:52.605 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'digitalstrom:dssBridge:f56bd9c9e0' changed from UNINITIALIZED (DISABLED) to INITIALIZING

2021-05-05 12:30:52.624 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'digitalstrom:dssBridge:f56bd9c9e0' changed from INITIALIZING to ONLINE (CONFIGURATION_PENDING): Checking configuration...

2021-05-05 12:30:53.438 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.checkZones(TemperatureControlManager.java:171) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:151) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:130) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.handler.BridgeHandler$Initializer.run(BridgeHandler.java:165) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]

	at java.lang.Thread.run(Unknown Source) [?:?]
```

### PR DESCRIPTION
**Pull request by ardanedh**
This fixes an _UnsupportedOperationException_ thrown when adding an element to a fixed-size list.
This code section has not worked for years ...

Fixes #10649

### CODE REVIEW

**Review by jlaur — COMMENTED** [review]
Thanks for the fix!

One question: Should `SUPPORTED_EVENTS` remain static? It seems strange to me that the second constructor adds two new events that will be available for all instances. Also, it seems there is no mutual exclusion for this operation, so there could be concurrency issues. I don't know the binding, so have to ask.

**Comment by ardanedh** [comment]
Thats a good point. To be honest, I cannot estimate the impact on the binding. The codebase is huge ...
After my first commit and a nights rest, I reconsidered the change made and added a more sensible approach using a java.util.Set. The code actually adds values to this supported event configuration and this might also lead to problems in the long run, similar to your mentioned concurrency issues.

**Comment by jlaur** [comment]
> Thats a good point. To be honest, I cannot estimate the impact on the binding. The codebase is huge ... After my first commit and a nights rest, I reconsidered the change made and added a more sensible approach using a java.util.Set. The code actually adds values to this supported event configuration and this might also lead to problems in the long run, similar to your mentioned concurrency issues.

Okay, so let's keep the scope to fix the specific exception without changing the somewhat strange logic. Perhaps you could consider wrapping the creation of the set in `Collections.synchronizedSet` so that write access would be synchronized (i.e. two objects are created through second constructor at the same time). It's not the most performant way, but it looks sufficient for this scenario (otherwise check out https://www.baeldung.com/java-concurrent-hashset-concurrenthashmap).

**Comment by ardanedh** [comment]
The suspicious `static` declaration of the `SUPPORTED_EVENTS` happened not so long ago. I think reverting the field back to an instance variable is the best option. I don't think thread safety would have been an issue with the HashSet, but better safe than sorry.
The change now includes more lines than I wanted in the first place, but I think this version should be safe to use. Again, I cannot test the changes, but there is an active user in the linked community [thread](https://community.openhab.org/t/digitalstrom-binding-online-configuration-pending/54295/91) who might be willing to report whether the change has any effect.

**Comment by jlaur** [comment]
> The suspicious `static` declaration of the `SUPPORTED_EVENTS` happened not so long ago.

Thanks, I see now that it's a regression of #14402 which looks like an attempt to fix a SAT warning because of a naming convention violation, but actually ended up introduced this bug.

> I think reverting the field back to an instance variable is the best option.

I agree.

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by jlaur** [comment]
> The change now includes more lines than I wanted in the first place, but I think this version should be safe to use. Again, I cannot test the changes, but there is an active user in the linked community [thread](https://community.openhab.org/t/digitalstrom-binding-online-configuration-pending/54295/91) who might be willing to report whether the change has any effect.

If you are able to provide a JAR for the user and get confirmation that it works as expected now, that would be awesome. 🙂

**Comment by ardanedh** [comment]
> Thanks, I see now that it's a regression of #14402 which looks like an attempt to fix a SAT warning because of a naming convention violation, but actually ended up introduced this bug.
Declaring the variable static was not actually a problem, I suppose. The nasty bug was creating a fixed size list by passing a String argument and later _adding_ values to the fixed size list (and not to an actual ArrayList).

**Comment by ardanedh** [comment]
> If you are able to provide a JAR for the user and get confirmation that it works as expected now, that would be awesome. 🙂

I will try to do that. Not sure if the user can apply the fix "by hand", though.

**Comment by jlaur** [comment]
> Declaring the variable static was not actually a problem, I suppose. The nasty bug was creating a fixed size list by passing a String argument and later adding values to the fixed size list (and not to an actual ArrayList).

You are right again, the bug was already present. It only made things a little worse by starting to share supported events between instances and introducing a concurrency issue. But all this didn't matter since it would already have thrown.

**Comment by Clocker** [comment]
> > If you are able to provide a JAR for the user and get confirmation that it works as expected now, that would be awesome. 🙂
> 
> I will try to do that. Not sure if the user can apply the fix "by hand", though.

Hello, 
if you provide me a jar file and you can tell me where to copy it to and how to set up user right, groups etc. I will test it on my actual opehabian system.

**Comment by ardanedh** [comment]
> Hello, if you provide me a jar file and you can tell me where to copy it to and how to set up user right, groups etc. I will test it on my actual opehabian system.

I don't know how to easily provide you the JAR - unless you send me a private email (email is visible in the commit (r.sch...) and let me know which openHAB version you are using. I'll compile and send you the patched plugin.
For installing a snapshot version of a binding see the [FAQ](https://community.openhab.org/t/frequently-asked-questions-faqs/17727#addons-1) in the openHAB community.

**Comment by Clocker** [comment]
Some in the actual openhabian update the new version seems to be integrated. At least now I get lots of items.

**Comment by ardanedh** [comment]
> Somehow in the actual openhabian update the new version seems to be integrated. At least now I get lots of items.

That's correct. As far as I know, snapshot versions of the distro or docker are regularly updated.
Could we say that the fix solved your problem with your digitalSTROM installation using temperature control things (don't even know what these actually are)?

**Pull request merged**
