### PR TITLE
[androidTV] fix version parsing for newer Philips TV models

### PR DESCRIPTION
**Pull request by marcelrv**
closing #17370

This fixes the issue for me. But needs to be tested for older TVs which provides the int as a version.

(note, the alternative would be to completely remove the version parsing, as the getVersion & setVersions don't seem to be called anywhere)

### CODE REVIEW

**Comment by marcelrv** [comment]
> You could add a unit test to simulate an older tv version string.
I recommended the testing indeed as I don't know the format for older TVs. Hence was hoping @morph166955 would be able to test it against an older TV.

@morph166955 Here is the jar if that makes testing more easy.
https://www.verpaalen.com/openhab/org.openhab.binding.androidtv-4.3.0-SNAPSHOT.jar

**Comment by morph166955** [comment]
I don't have a Philips TV personally to test this against.  We pulled Philips in a while ago because it runs the ATV protocols under the hood.  Philips is much like the Nvidia Shield for this binding where it provides additional hooks beyond what ATV provides.  ATV is a very broad userbase because it's not tied to a single vendor.  This shouldn't do anything to cause issues with the ATV stack.  You may want to put a post on the forum and see if other PTV users can regression test this on older models to make sure it doesn't have issues.

**Comment by marcelrv** [comment]
So, I added a test for both the version as a string as well version as an int.
With this I'm fairly confident the parsing will happen without any error.
This `version` variable is nowhere used, so the main question was if any exception was triggered if the version would still be provided as int.

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
