### PR TITLE
[shelly] Cancel the init job when the thing handler is disposed

### LINKED ISSUE #14032: [shelly] Log "spam" after upgrade to openHAB 3.4 from 3.3
## Expected Behavior
No warning messages.

## Current Behavior
After upgrading openHAB & addon packages from version 3.3 onto 3.4 my log files are "spamed" with thoses messages:

```
...
2022-12-21 19:51:50.188 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ShellyRelayHandler tried updating the thing status although the handler was already disposed.

2022-12-21 19:51:50.191 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ShellyRelayHandler tried updating the thing status although the handler was already disposed.
...
```
No comparable messages in previous version 3.3, not even before of that in 3.2.

## Steps to Reproduce (for Bugs)
1. Stop openhab instance and restart it without Shelly binding, none of those warning in log.
2. Stop openhab instance again, restart with Shelly binding, the messages are again flooding log files.

## Context
It is impossible to live read log files, on CLI or on WebIF PaperUI due to message flooding and depended things, more IO to SD-Card, size of log files, more log file switches, outrunning history etc.

## Your Environment
openHABian (64-bit) 1.7.x, Raspberry Pi 4 with EnOcean Pi.
```
binding = astro,avmfritz,enocean,hpprinter,network,ntp,openweathermap,shelly,vdr,yamahareceiver
misc = homekit
persistence = mapdb
transformation = scale
ui = basic,habpanel
```

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #14032

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by lsiepel** [comment]
I think there is still something to fix on the closed issue and is pr this considered for a patch to 3.4.x?

**Comment by lolodomo** [comment]
> I think there is still something to fix on the closed issue 

What exactly? 
The issue was about log spamming and I hope this was solved. 

> and is this pr considered for a patch to 3.4.x?

I don't know. 
@jlaur

**Comment by jlaur** [comment]
> > and is this pr considered for a patch to 3.4.x?
> 
> I don't know.

It's very low risk, and we know for sure that there are issues with the binding. Best case is that it's now fixed, and in worst case this fix will not cause any harm. Cherry-picked.

**Comment by lolodomo** [comment]
Thank you @jlaur

**Comment by lsiepel** [comment]
> 

Not 100% sure, just like you said [here](https://github.com/openhab/openhab-addons/issues/14032#issuecomment-1408516261)

**Pull request merged**
