### PR TITLE
[boschshc] Support for Smart Water Alarm

### LINKED ISSUE #16593: [boschshc] Add support for water detector
Since I'm afraid of water and moisture in the basement, I use Bosch water detectors. They work pretty well. However, I couldn't connect them to my openHAB because they are missing from the boschshc binding.
I use openHAB version 4.1.2 (Build) and Bosch Smart Home Controller II. 
I would be very happy about an extension of the boschshc binding to use the water detector.

### PR DESCRIPTION
**Pull request by david-pace**
Adds support for Bosch Smart Water Alarm devices.

* add new thing type and new channel types
* add new services for water detector
* refactor CameraNotificationState and PrivacyModeState to a common enum EnabledDisabledState that can be re-used in the water detector tilt service states
* implement handler for new device
* register new device in handler factory and discovery
* add unit tests
* add documentation

closes #16593

### CODE REVIEW

**Review by jlaur — APPROVED** [review]
Flawless, many thanks! Will let @GerdZanker have a look before merging.

**Comment by david-pace** [comment]
Thanks for the review @jlaur ❤️

We should also wait for the confirmation by @name-lake in #16593 whether the `sensor-moved` channel works. Everything else was already tested with the real hardware :+1:

**Review by GerdZanker — APPROVED** [review]
Nice!

**Comment by david-pace** [comment]
Hi @mherwege, I have a question about the trigger channel. In the [documentation](https://www.openhab.org/docs/developer/bindings/thing-xml.html#system-trigger-channel-types) I found that the most suitable system trigger channel type would probably be `system.trigger`, correct?

I now defined the channel in `thing-types.xml` like this:

```
<channel id="sensor-moved" typeId="system.trigger"/>
```

But I could not find which types of commands I am supposed to send to this channel. Should I send `OnOffType.ON` commands to trigger, or are there specialized trigger commands for these types of channels?

**Comment by mherwege** [comment]
I used it extensively in the Elro Connects binding for a similar use. I defined specific channel types for it. The handler has a method triggerChannel to trigger it. Have a look here: https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.elroconnects.

**Comment by jlaur** [comment]
@david-pace - you can also have a look at #16704 showing an end-to-end implementation of a trigger channel.

**Comment by david-pace** [comment]
Hi @jlaur and @mherwege, the code is now open for a final review 👍 It was tested with the real hardware by a helpful user in #16593 already ❤️

**Review by jlaur — APPROVED** [review]
Still LGTM :)

**Pull request merged**
