### PR TITLE
[sonos] Support for more audio streams through the HTTP audio servlet

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #15113

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@dalgwen : it is a first audio sink update to use `AudioSinkSync`. I kept an asynchronous handling for `URLAudioStream`. Any audio stream except `URLAudioStream` is now handled using the new method `audioHTTPServer.serve`.

**Comment by dalgwen** [comment]
Hello,
I can't test and maybe I miss something, but I don't understand why it extends AudioSinkSync ?
In the processSynchronously() you use the httpAudioServlet, which is inherently async.
You should use the AudioSinkSync class and its method only if processSynchronously() returns when the sound is fully played.

**Comment by lolodomo** [comment]
This one was of course fully tested by me.

>I don't understand why it extends AudioSinkSync ?
> In the processSynchronously() you use the httpAudioServlet, which is inherently async.
> You should use the AudioSinkSync class and its method only if processSynchronously() returns when the sound is fully played.

What is synchronous is the handling by `handler.playNotificationSoundURI`.

**Comment by dalgwen** [comment]
> What is synchronous is the handling by `handler.playNotificationSoundURI`.

OK, I get it now, thanks. LGTM

**Comment by lolodomo** [comment]
@openhab/add-ons-maintainers : I believe this PR is ready for a merge.

**Review by kaikreuzer — APPROVED** [review]

**Pull request merged**
