### PR TITLE
[nikohomecontrol] Add more device types, use Niko API token authentication, code improvements.

### PR DESCRIPTION
**Pull request by mherwege**
Niko released a published API for their Home Control II system. The binding has been changed based on this API. This resulted in:
- Adoption of token based authentication, as defined in the API documentation.
- Addition of some extra device types, that can be mapped to already existing activity types.
- Addition of instant power measurement readings.
- Fixes based on API documentation.
- Other fixes and code improvements.

### CODE REVIEW

**Comment by bccrew** [comment]
After a 32hours stable run, 1 error happened.

2019-12-24 07:10:33.377 [DEBUG] [l.nhc2.NikoHomeControlCommunication2] - Connection error: CONNECTED
com.hivemq.client.mqtt.exceptions.ConnectionClosedException: java.io.IOException: Connection reset by peer
Caused by: java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_232]
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_232]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_232]
at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_232]
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377) ~[?:1.8.0_232]
at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247) ~[bundleFile:4.1.42.Final]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147) ~[bundleFile:4.1.42.Final]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[bundleFile:4.1.42.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [bundleFile:4.1.42.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [bundleFile:4.1.42.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [bundleFile:4.1.42.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [bundleFile:4.1.42.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [bundleFile:4.1.42.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [bundleFile:4.1.42.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.42.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.42.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by mherwege** [comment]
@bccrew This should be resolved in the latest version. I added a restart of the connection of the MQTT connection stops for any reason.

**Comment by bccrew** [comment]
Ok, let's see if it stays stable for longer periods now.

**Comment by mherwege** [comment]
Closing, new PR will push into 2.5.x branch.

**Pull request closed without merging**
