### PR TITLE
[keba] Fix unit in example for power channel

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #12529 

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by jlaur** [comment]
@lolodomo - please do not create branches directly in this repository, but instead in your own fork.

**Comment by lolodomo** [comment]
> @lolodomo - please do not create branches directly in this repository, but instead in your own fork.

The change was done directly in Github. I thought the branch will be created in my Github fork. 
Should I forgive that PR? 
It is only one character removed on README.

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by jlaur** [comment]
> The change was done directly in Github. I thought the branch will be created in my Github fork.

Ah, that's good to know, it's probably one of the explanations why this sometimes happens.

> Should I forgive that PR?

I forgive it. 😃 No, I've merged it instead and deleted the branch.

**Pull request merged**
