### PR TITLE
[harmonyhub] Update README.md

### PR DESCRIPTION
**Pull request by olemr**
Propose adding a note on the fact that there is no way to detect buttons pressed on the remote.
I spent a few hours before realizing this fact.

### CODE REVIEW

**Comment by fwolter** [comment]
@digitaldan Can you take a look?

**Comment by Skinah** [comment]
What @olemr is saying is correct, just I would have worded it differently. Not referring to the ‘hub’, but instead that the X channel won’t create events when a button is pushed.

**Comment by fwolter** [comment]
@digitaldan 👀

**Comment by digitaldan** [comment]
I think it would be better to adopt our more standard documentation approach and list a table of channels, supported item types and if they are Read/Write , or Write only.  This was an early oh2 binding and probably proceeded  our documentation standards.

**Review by wborn — APPROVED** [review]
Thanks. If anyone has further improvements, please create PRs for them. :slightly_smiling_face:

**Pull request merged**
