### PR TITLE
Rework ThingActions

### PR DESCRIPTION
**Pull request by wborn**
* Remove duplication by making use of default Java generated exceptions
* Make ThingActions labels/descriptions more consistent

See #8732

### CODE REVIEW

**Review by cpmeister — APPROVED** [review]
LGTM

**Review by mhilbush — APPROVED** [review]
LGTM

**Review by bobadair — APPROVED** [review]
LGTM for alarmdecoder and lutron bindings.

**Comment by bern77** [comment]
LGTM

**Review by bern77 — APPROVED** [review]
LGTM

**Review by Skinah — APPROVED** [review]
LGTM

**Pull request merged**
