### PR TITLE
Fix/suppress PMD CompareObjectsWithEquals findings

### PR DESCRIPTION
**Pull request by wborn**
Newer PMD versions discover more CompareObjectsWithEquals findings.

Related to https://github.com/openhab/static-code-analysis/pull/423

### CODE REVIEW

**Review by bern77 — APPROVED** [review]
LGTM

**Comment by robnielsen** [comment]
LGTM

**Review by robnielsen — APPROVED** [review]

**Review by RSStephens — APPROVED** [review]

**Review by fwolter — APPROVED** [review]
That took longer to review than expected. I could barely understand some weird code around some comparisons. I wouldn't have excepted so many `==` string comparisons either. Let's hope that fixing the broken, but working code don't lead to fixed code but broken functionality. Maybe we should give the binding code owners a bit time to also review the changes.

**Review by clinique — APPROVED** [review]
LGTM

**Review by fruggy83 — APPROVED** [review]
LGTM

**Comment by wborn** [comment]
>  I could barely understand some weird code around some comparisons.

Yes the dscalarm binding code comparisons were very weird. :thinking:

**Review by druciak — APPROVED** [review]
Satel changes LGTM

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
