### PR TITLE
[miio] add suppoprt Mijia Omni Robot Vacuum-Mop dreame.vacuum.p2114o

### LINKED ISSUE #16120: [miio] new device database MiJia Omni Robot-Vacuum (B101CN)
MiJia Omni Robot-Vacuum (B101CN) with id `dreame.vacuum.p2114o` was scanned and a database file generated.
[test-dreame.vacuum.p2114o-20230830-020759.txt](https://github.com/openhab/openhab-addons/files/13773385/test-dreame.vacuum.p2114o-20230830-020759.txt)

The following properties were tested successfully (using the Xiaomi app in parallel):
- actions (Actions), except `vacuum-start-room-sweep`, `vacuum-extend-start-clean`, `map-map-req`, `map-update-map` and `time-delete-timer`, because these commands require params
- status (Robot Cleaner - Status)
- fault (Robot Cleaner - Device Fault)
- mode (Robot Cleaner - Mode)
- battery_level (Battery - Battery Level)
- charging_state (Battery - Charging State)
- brush_left_time (Main Cleaning Brush - Brush Left Time)
- brush_life_level (Main Cleaning Brush - Brush Life Level)
- brush_left_time1 (Side Cleaning Brush - Brush Left Time)
- brush_life_level1 (Side Cleaning Brush - Brush Life Level)
- filter_life_level (Filter - Filter Life Level)
- filter_left_time (Filter - Filter Left Time)
- work_mode (Vacuum Extend - Work Mode)
- cleaning_time (Vacuum Extend - Cleaning Time)
- cleaning_area (Vacuum Extend - Cleaning Area)
- cleaning_mode (Vacuum Extend - Cleaning Mode)
- mop_mode (Vacuum Extend - Mop Mode)
- waterbox_status (Vacuum Extend - Waterbox Status)
- task_status (Vacuum Extend - Task Status)
- break_point_restart (Vacuum Extend - Break Point Restart)
- carpet_press (Vacuum Extend - Carpet Press)
- serial_number (Vacuum Extend - Serial Number)
- clean_rags_tip (Vacuum Extend - Clean Rags Tip)
- keep_sweeper_time (Vacuum Extend - Keep Sweeper Time)
- faults (Vacuum Extend - Faults)
- relocation_status (Vacuum Extend - Relocation Status)
- enable (Do Not Disturb - Enable)
- start_time (Do Not Disturb - Start Time)
- end_time (Do Not Disturb - End Time)
- mult_map_info (Map - Mult Map Info)
- volume (Audio - Volume)
- voice_packet_id (Audio - Voice Packet Id)
- set_voice (Audio - Set Voice)
- voice_change_state (Audio - Voice Change State)
- time_zone (Time - Time Zone)
- timer_clean (Time - Timer Clean)
- first_clean_time (Clean Logs - First Clean Time)
- total_clean_time (Clean Logs - Total Clean Time)
- total_clean_times (Clean Logs - Total Clean Times)
- total_clean_area (Clean Logs - Total Clean Area)
- mop_life_level (Mop - Mop Life Level)
- mop_left_time (Mop - Mop Left Time)

The following properties couldn't be tested (I have no idea how to do it):
- clean_extend_data (Vacuum Extend - Clean Extend Data)
- remote_state (Vacuum Extend - Remote State)
- nation_matched (Vacuum Extend - Nation Matched)
- laser_switch (Vacuum Extend - Laser Switch)

According to miot-spec there are more properties, like `room-ids`, `dry-left-time` and others related to base station.
And also additional actions, like "Start Dust Arrest" or "Stop Dry" also related to base station.

### PR DESCRIPTION
**Pull request by marcelrv**
Adding support for the following model:
* Mijia Omni Robot Vacuum-Mop (modelId: dreame.vacuum.p2114o)

closes #16120

### CODE REVIEW

**Comment by lsiepel** [comment]
Depends on https://github.com/openhab/openhab-addons/pull/16381 regarding readme generation. Please generate with that config file or wait for that PR to be merged.

**Comment by marcelrv** [comment]
I'm waiting for the later to avoid merge conflicts

**Comment by lsiepel** [comment]
> I'm waiting for the later to avoid merge conflicts

That one is merged, so it can be regenerated.

**Comment by marcelrv** [comment]
@lsiepel Thx. I've rebased and updated the readme.

**Pull request merged**
