### PR TITLE
[rotel] Add support for RC-1590 with firmware >= 1.40

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@cpmeister : a review & merge of this small enhancement before the release of 2.5.6 would be really appreciated ;)

**Comment by cpmeister** [comment]
Is this change backwards compatible for users with the older firmware?

**Comment by lolodomo** [comment]
Absolutely, there is a configuration setting (protocol) to choose between the two different protocol versions.

**Comment by lolodomo** [comment]
Thank you for the express merge.

**Pull request merged**
