### PR TITLE
Revert "[itests mqtt.homeassistant] Fixed itests for mqtt.homeassistant"

### PR DESCRIPTION
**Pull request by J-N-K**
Reverts openhab/openhab-addons#7140

Upgrading bnd was unintended and obviously causes problems on Jenkins

### CODE REVIEW

**Comment by cpmeister** [comment]
Can I get a sign.off on this>

**Comment by J-N-K** [comment]
This was created with GitHubs „revert commit“ button.

Signed-Off-By: Jan N. Klug <jan.n.klug@rub.de>

**Comment by J-N-K** [comment]
Looking at Jenkins it seems to be fixed.

**Comment by cpmeister** [comment]
Fixed with or without this PR?

**Comment by J-N-K** [comment]
With this PR.

**Comment by cpmeister** [comment]
Manually approved sign.off

**Comment by kaikreuzer** [comment]
Thanks - I have also launched https://ci.openhab.org/view/Integration%20Builds%20(2.5.x)/job/openHAB2.5.x-Addons/ to see whether it really fixes the build.

**Comment by mehoekstra** [comment]
Please let me know what you find.  This made all of the iTests work for me locally and in Travis as the pull request logs show.  Looking back in the Travis logs, itests for HomeAssistant hadn't been working for many months.  I thought I was doing you all a favor.

**Comment by mehoekstra** [comment]
??? Looking at these logs, all of the Travis tests pass in my pull request, now they all fail again.  That's the desired behavior?

**Comment by J-N-K** [comment]
The build script unfortunately builds itests based only on the bundle name. So an itests bundle Which is disabled by commenting the module in the pom is still build. 

I agree that having the tests working is what should be desired (as they worked before). Reverting the whole PR was the fastest way. I‘ll try to have a look at this in the next days.

**Comment by mehoekstra** [comment]
OK.  I see from my email that this did break somebody else's build, I will take a look also.  The only additional test that I commented out was hueemulation since the execution was failing for JDK11.

**Pull request merged**
