### PR TITLE
[ventaair] Add Air quality and service time channels

### LINKED ISSUE #11791: [ventaair] Feature request:  Add Air quality and service time channels
I got an email with the following request:

I have a Venta model AH902 and it is working fine with current binding, but maybe there is a possibility to add "air quality pm2.5" measurement ("Dust" field in response) and "service time" in minutes ("ServiceT" field in response). I also noticed that the water level number can be 4 (Max)

I am sending you debug information:
```
{
    "Header":
    {
        "DeviceType": 12,
        "MacAdress": "f8:f0:f0:f0:f0:f0",
        "Hash": "-42",
        "Error": 0,
        "DeviceName": ""
    },
    "Action":
    {
        "Power": true,
        "FanSpeed": 2,
        "TargetHum": 55,
        "Timer": 0,
        "Boost": false,
        "SleepMode": false,
        "ChildLock": false,
        "Automatic": false,
        "SysLanguage": 0,
        "CleanLanguage": 0,
        "TempUnit": 0,
        "DisplayLeft": 0,
        "DisplayRight": 0,
        "Reset": 0,
        "ConINet": 3,
        "DelUser": false
    },
    "Info":
    {
        "SWDisplay": "V0.103",
        "SWPower": "V1.001",
        "SWTouch": "V1.3.0",
        "SWWIFI": "V19.4.8",
        "CleanMode": false,
        "RelState": [true, true, false, false],
        "TimerT": 0,
        "OperationT": 4494,
        "DiscIonT": 4494,
        "CleaningT": 4494,
        "FilterT": 2245,
        "ServiceT": 4,
        "UVCOnT": 0,
        "UVCOffT": 469,
        "CleaningR": 0,
        "Warnings": 8
    },
    "Measure":
    {
        "Temperature": 20.3,
        "Humidity": 47.8,
        "Dust": 2,
        "WaterLevel": 4,
        "FanRpm": 800
    }
}
```

### PR DESCRIPTION
**Pull request by t2000**
- also add value 4 for water level

Closes #11791

Signed-off-by: Stefan Triller <github@stefantriller.de>

### CODE REVIEW

**Review by lolodomo — CHANGES_REQUESTED** [review]
Please run the maven command to update the default i18n properties file.

`mvn i18n:generate-default-translations`

**Comment by lolodomo** [comment]
@t2000 : as author or maintainer of this binding, any comment ?

**Comment by t2000** [comment]
```
[ERROR] No plugin found for prefix 'i18n' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/stefan/.m2/repository), central (https://repo1.maven.org/maven2), openhab-release (https://openhab.jfrog.io/openhab/libs-release)] -> [Help 1]
```
And I am the author of this PR ;)

**Comment by lolodomo** [comment]
> And I am the author of this PR ;)

Of course but are you the author of this binding ?

**Comment by lolodomo** [comment]
> happens in the `openhab-addons` directory directly as well as in the directory of the binding.

Probably because your local repo / branch is outdated.
I tried myself this morning for several bindings and it works well.

**Comment by t2000** [comment]
> Of course but are you the author of this binding ?
Yes I am too :)

>Probably because your local repo / branch is outdated.
>I tried myself this morning for several bindings and it works well.

I just rebased and still the same error :(

I forced pushed it, but on that branch your command doesnt work unfortunately :(

**Comment by t2000** [comment]
```
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/i18n-maven-plugin-3.2.0-SNAPSHOT.jar
[WARNING] Failed to retrieve plugin descriptor for org.openhab.core.tools:i18n-maven-plugin:3.2.0-SNAPSHOT: Plugin org.openhab.core.tools:i18n-maven-plugin:3.2.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.openhab.core.tools:i18n-maven-plugin:jar:3.2.0-SNAPSHOT in central (https://repo1.maven.org/maven2)
```

That is the issue, I tried it with `mvn -U clean i18n:generate-default-translations` to force it to redownload the dependencies which ist did for some, but still:

```
stefan@xps13 ~/openhab-2021/git/openhab-addons/bundles/org.openhab.binding.ventaair [feature/ventaairQualityServiceTime]$ mvn -U clean i18n:generate-default-translations
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/openhab/openhab-super-pom/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/openhab/openhab-super-pom/maven-metadata.xml (459 B at 1.2 kB/s)
Downloading from central: https://repo1.maven.org/maven2/org/eclipse/m2e/lifecycle-mapping/1.0.0/lifecycle-mapping-1.0.0.pom
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/eclipse/m2e/lifecycle-mapping/1.0.0/lifecycle-mapping-1.0.0.pom
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
Downloading from central: https://repo1.maven.org/maven2/org/eclipse/m2e/lifecycle-mapping/1.0.0/lifecycle-mapping-1.0.0.jar
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/eclipse/m2e/lifecycle-mapping/1.0.0/lifecycle-mapping-1.0.0.jar
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Could not find artifact org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in central (https://repo1.maven.org/maven2)
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/maven-metadata.xml
Downloading from central: https://repo1.maven.org/maven2/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/maven-metadata.xml
Downloading from central: https://repo1.maven.org/maven2/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/i18n-maven-plugin-3.2.0-SNAPSHOT.pom
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/i18n-maven-plugin-3.2.0-SNAPSHOT.pom
[WARNING] The POM for org.openhab.core.tools:i18n-maven-plugin:jar:3.2.0-SNAPSHOT is missing, no dependency information available
Downloading from central: https://repo1.maven.org/maven2/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/i18n-maven-plugin-3.2.0-SNAPSHOT.jar
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/openhab/core/tools/i18n-maven-plugin/3.2.0-SNAPSHOT/i18n-maven-plugin-3.2.0-SNAPSHOT.jar
[WARNING] Failed to retrieve plugin descriptor for org.openhab.core.tools:i18n-maven-plugin:3.2.0-SNAPSHOT: Plugin org.openhab.core.tools:i18n-maven-plugin:3.2.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.openhab.core.tools:i18n-maven-plugin:jar:3.2.0-SNAPSHOT in central (https://repo1.maven.org/maven2)
Downloading from central: https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 372 kB/s)
Downloaded from central: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 123 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.327 s
[INFO] Finished at: 2021-12-19T13:34:08+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'i18n' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/stefan/.m2/repository), central (https://repo1.maven.org/maven2), openhab-release (https://openhab.jfrog.io/openhab/libs-release)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

Any idea?

**Comment by t2000** [comment]
Ca somebody either a) fix the translation maven dependency or b) merge this request because its fully unrelated... Thank you.

**Comment by lolodomo** [comment]
I pushed the updated translations as a PR to your repo.
You just have to merge my PR and then push again to update your PR.

**Comment by lolodomo** [comment]
> > Of course but are you the author of this binding ?
> 
> Yes I am too :)

Why were you not listed as author/maintainer in the CODEOWNER file in this case ?

**Comment by lolodomo** [comment]
> > > Of course but are you the author of this binding ?
> > 
> > 
> > Yes I am too :)
> 
> Why were you not listed as author/maintainer in the CODEOWNER file in this case ?

Very funny.
I finally understood.
Ok, I probably wrongly read !

**Comment by t2000** [comment]
@lolodomo Thanks for updating the translations. But I still don't know why the maven dependency wasn't correctly resolved on my laptop...

I have integrated your changes and force pushed my branch, hence updated this PR. Thanks for your help.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
> But I still don't know why the maven dependency wasn't correctly resolved on my laptop...

I just compiled again my core repo and then the command was running well again.

**Pull request merged**
