### PR TITLE
Apply Spotless after release

### PR DESCRIPTION
**Pull request by lsiepel**
Applied spotless to fix the build after deployment script did something 'extra'.

### CODE REVIEW

**Comment by jlaur** [comment]
@lsiepel - this seems fishy? "openhab-addons: Prepare next version" is still running, maybe let's wait and see it looks after that?

**Comment by kaikreuzer** [comment]
I agree that we should wait a bit. openhab-core would already be ready to be updated.

**Comment by lsiepel** [comment]
No need to rush, this PR is here ready to be merged whenever the task is completed. :-)

**Comment by jlaur** [comment]
Okay, checking Git history, I found #16097. So it seems the maven plugin makes these undesired changes besides bumping version number, and we then manually revert them right after. And we live with that, because we don't know how to avoid it. Correct? 🙂

**Comment by kaikreuzer** [comment]
Yep, that's correct.

**Comment by lsiepel** [comment]
> Okay, checking Git history, I found #16097. So it seems the maven plugin makes these undesired changes besides bumping version number, and we then manually revert them right after. And we live with that, because we don't know how to avoid it. Correct? 🙂

Yes, see https://github.com/openhab/openhab-core/issues/3952#issuecomment-1868054818

I remember this XML multiple lines issue also occurred elsewhere. Can’t find the link. I think it had to do with inconsistent behaviour of spotless on all operating systems.

**Pull request merged**
