### PR TITLE
[mercedesme] Refactor code and fix test

### PR DESCRIPTION
**Pull request by lsiepel**
A follow up to https://github.com/openhab/openhab-addons/pull/15628 
Refactored the `handleCommand` method and adjusted the tests. This needs some testing as i do not own a mercedes to test. 

The Thing properties hold the capabilities of the car/account. I assumed that if a car has a capability, it is listed with a `true` value. Unfortunately the tests where inconclusive so please double check @weymann

### CODE REVIEW

**Comment by tl-photography** [comment]
> A follow up to #15628 Refactored the `handleCommand` method and adjusted the tests. This needs some testing as i do not own a mercedes to test.
> 
> The Thing properties hold the capabilities of the car/account. I assumed that if a car has a capability, it is listed with a `true` value. Unfortunately the tests where inconclusive so please double check @weymann

buy the man a Mercedes!

(sorry i had to)

**Comment by weymann** [comment]
> buy the man a Mercedes!

for me too - the foundation should be able to afford this :)

Good start to bring more clarity in VehicleHandler. Pushed https://github.com/lsiepel/openhab-addons/commit/66df1a15493cf91308d09a72ed926614184c89e8 for

- switch/case handling for complete `handleCommand`
- fix failing unit test from https://github.com/openhab/openhab-addons/actions/runs/9616331795/job/26525598415?pr=16897 (hopefully)

**Comment by lsiepel** [comment]
Thanks. @weymann. Are you able to do some basic tests with the car? Unit tests seem fine now

**Review by weymann — APPROVED** [review]
LGTM

- Unit tests running stable
- tested all commands which are supported on my vehicle

**Review by jlaur — APPROVED** [review]
Thanks, let's merge this and hope it will resolve the test issue, also seen [here](https://ci.openhab.org/job/openHAB-Addons/lastCompletedBuild/org.openhab.addons.bundles$org.openhab.binding.mercedesme/testReport/org.openhab.binding.mercedesme/StatusTests/testNoTokenStored/).

**Comment by weymann** [comment]
> Thanks, let's merge this and hope it will resolve the test issue, also seen [here](https://ci.openhab.org/job/openHAB-Addons/lastCompletedBuild/org.openhab.addons.bundles$org.openhab.binding.mercedesme/testReport/org.openhab.binding.mercedesme/StatusTests/testNoTokenStored/).

yes, PR will fix this

**Pull request merged**
