### PR TITLE
[googletts] Fix authentication after communication error

### LINKED ISSUE #15746: [googletts] Missing service configuration
## Expected Behavior

Some CommunicationException should not reset the oAuthService variable.

## Current Behavior

After some WARN like

`2023-10-13 06:15:16.652 [WARN ] [ce.googletts.internal.GoogleCloudAPI] - Error initializing Google Cloud TTS service: An unexpected IOException occurred: java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed
`

or 

`2023-10-05 09:08:16.316 [WARN ] [ce.googletts.internal.GoogleCloudAPI] - Error initializing Google Cloud TTS service: An unexpected IOException occurred: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Buffering capacity 2097152 exceeded`

the oAuthService variable is reset to null and Google TTS returns the Missing service configuration until openHAB is restarted.

## Possible Solution
```
public byte[] synthesizeSpeech(String text, GoogleTTSVoice voice, String codec) {
        String format = getFormatForCodec(codec);
        try {
            return synthesizeSpeechByGoogle(text, voice, format);
        } catch (AuthenticationException e  ̶|̶ ̶C̶o̶m̶m̶u̶n̶i̶c̶a̶t̶i̶o̶n̶E̶x̶c̶e̶p̶t̶i̶o̶n̶ ̶e̶) {
            logger.warn("Error initializing Google Cloud TTS service: {}", e.getMessage());
            if (oAuthService != null) {
                oAuthFactory.ungetOAuthService(GoogleTTSService.SERVICE_PID);
                oAuthService = null;
            }
            voices.clear();
        } catch (CommunicationException e) {
            logger.warn("Error initializing Google Cloud TTS service: {}", e.getMessage());
            voices.clear();
        }
        return null;
    }
```

Probably like this, but I'm not sure.

## Your Environment
Version used: openHAB 4.0.3 
Environment name and version: OpenJDK Runtime Environment Zulu17
Operating System: Ubuntu 20.04.3

### PR DESCRIPTION
**Pull request by jlaur**
Fixes #15746

JARs for testing:
- [org.openhab.voice.googletts-4.0.4-SNAPSHOT.jar](https://drive.google.com/file/d/1s_g1XnpMKN81Fr5CiY4Lkn356RHJmxP6/view?usp=sharing)
- [org.openhab.voice.googletts-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1E-GSiHmtNlV3q_I_YK4wT4nGJ1NPCBCe/view?usp=sharing)

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@Artur-Fedjukevits : can you test this fix before I merge it ?
@jlaur you could link the jar for testing ?

**Comment by jlaur** [comment]
> @jlaur you could link the jar for testing ?

Good idea, done. When tested, I would suggest to also cherry-pick this into `4.0.x`.

**Comment by lolodomo** [comment]
> > @jlaur you could link the jar for testing ?
> 
> Good idea, done.

Ah, this was already done in the issue.

**Comment by Artur-Fedjukevits** [comment]
> @Artur-Fedjukevits : can you test this fix before I merge it ? @jlaur you could link the jar for testing ?

Sorry for the delay. Tonight I will check it.

**Comment by jlaur** [comment]
> When tested, I would suggest to also cherry-pick this into 4.0.x.

@lolodomo - thanks for the review. Do you agree to backport the fix?

**Comment by lolodomo** [comment]
Ok

**Pull request merged**
