### PR TITLE
[miio] improve zhimi fan channels

### PR DESCRIPTION
**Pull request by marcelrv**
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by fwolter** [comment]
There is one conflicting file, now.

Is this backward compatible as you changed the Item Type.

**Comment by marcelrv** [comment]
no, indeed there are changing channels, possibly not backwards compatible. (however, I'm still quite unclear to which extend a number to number:QtyType change is actually breaking the compatibility)

In the OH3.1 upgrade notifications/comments there is already a remark about changing channels in the upgrade from OH3.0 to OH3.1 due to the introduction of the quantity types (in many devices, not just these, e.g. all devices with temperature channel have been updated etc)

**Review by fwolter — APPROVED** [review]
LGTM

You could add an ALERT to https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/update.lst

**Comment by marcelrv** [comment]
You mean this :-)
https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/update.lst#L42

**Comment by fwolter** [comment]
Oh, yes. Interesting sort order in this file.

**Pull request merged**
