### PR TITLE
[multiple] Reduce SAT warnings

### PR DESCRIPTION
**Pull request by lsiepel**
This PR fixes some (not all) sat warnings related to:
- NoEmptyLineSeparatorCheck
- ModifierOrderCheck
- TypeNameCheck
- ConstantNameCheck (mainly loggers)

### CODE REVIEW

**Comment by Wolfgang1966** [comment]
LGTM for TACMI. Thank you :-)

**Review by wborn — APPROVED** [review]
Thanks for the cleanup!

**Review by theater — COMMENTED** [review]
LGTM paradox alarm

**Review by clinique — COMMENTED** [review]
LGTM

**Pull request merged**
