### PR TITLE
[exec] Fix whitelist not read

### PR DESCRIPTION
**Pull request by J-N-K**
Reported on the forum.

### CODE REVIEW

**Comment by jlaur** [comment]
I assume it's a regression from #14004.

**Review by jlaur — APPROVED** [review]
LGTM, thanks.

**Comment by J-N-K** [comment]
Exactly, that’s why I wanted to have these core changes merged early, so that we can find and fix what went wrong.

**Comment by jlaur** [comment]
> Exactly, that’s why I wanted to have these core changes merged early, so that we can find and fix what went wrong.

Yes, just wanted to add this for context as I needed to check the change from that PR myself in order to understand the issue. 🙂

**Pull request merged**
