### PR TITLE
[jdbc] Fix IllegalArgumentException on service activation

### LINKED ISSUE #14053: [jdbc] Service fails in activation when having persisted items with invalid name
Reported in the forum:
https://community.openhab.org/t/openhab-3-4-release-discussion/142257/115

## Expected Behavior
The persistence service should work, but skip and warn about invalid item names.

## Current Behavior
Exception is thrown during `@Activate`:

```
2022-12-23 11:40:40.096 [ERROR] [jdbc.internal.JdbcPersistenceService] - bundle org.openhab.persistence.jdbc:3.4.0 (304)[org.openhab.persistence.jdbc.internal.JdbcPersistenceService(382)] : The activate method has thrown an exception
java.lang.IllegalArgumentException: 12 is not a valid item name
```

## Possible Solution
Skip invalid items.

## Steps to Reproduce
For configurations not using real names, manipulate an item in the items manage table by appending e.g. a "%" to its name:
image

Then start the service.

### PR DESCRIPTION
**Pull request by jlaur**
Reported in the forum:
https://community.openhab.org/t/openhab-3-4-release-discussion/142257/115

Fixes #14053
Regression of #13544

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
To be cherry-picked in 3.4.x.

**Comment by jlaur** [comment]
@lolodomo - will you, or should I?

**Comment by lolodomo** [comment]
> @lolodomo - will you, or should I?

Please do it, I saw your instructions in the other PR but that is not fully clear to me.

**Comment by jlaur** [comment]
> Please do it, I saw your instructions in the other PR but that is not fully clear to me.

Done. You can PM me if you would like more info.

**Pull request merged**
