### PR TITLE
Remove/ignore Eclipse project files

### LINKED ISSUE #8451: Remove all .project and .classpath files after migration of add-ons to OH3
All bindings have the eclipse `.project` and `.classpath` files checked in. This can be helpful when importing a project. However that was more relevant in the past than today. Because we now can simply import projects as maven projects. With the current eclipse setup script there are no project imported anymore, meaning it won't help there either.
Also these files are only needed for eclipse while we now support other ide's too. It might be a little bit inconvenient for existing users if we change this. But when moving to openHAB 3 the eclipse should use Java 11 (although it might be possible to just add Java 11, I would recommend to install eclipse using Java 11).
Therefor this issue proposes to remove all `.project` and `.classpath` files from all the add-ons. 

Things to do after migration:
1. Remove all `.project` and `.classpath` files.
2. Add `.project` and `.classpath` to `.gitignore`
3. Update the skeleton to no generate these files anymore (this is not blocking because generating does no harm)
4. Update the eclipse documentation to use maven import.
5. Communicate this change.

### PR DESCRIPTION
**Pull request by wborn**
Fixes #8451

### CODE REVIEW

**Review by druciak — APPROVED** [review]
LGTM

**Review by Cossey — APPROVED** [review]
(Y)

**Review by kaikreuzer — APPROVED** [review]
I guess we do not have to wait for the PR build here.

**Comment by wborn** [comment]
No but I was testing if I could get the PR build fixed. :-)

**Comment by kaikreuzer** [comment]
Sorry for having interrupted those tests 😇 .

**Pull request merged**
