### PR TITLE
[modbus] Number scaling example with JINJA transform

### PR DESCRIPTION
**Pull request by ssalonen**
Signed-off-by: Sami Salonen <ssalonen@gmail.com>

### CODE REVIEW

**Comment by ssalonen** [comment]
ping @rossko57 for comments

**Comment by Rossko57** [comment]
Looks good. I don't know much about JINJA, but looks less cumbersome than javasript for simple scales.   I wonder which is more efficient, where we may run it on dozens of registers every second.

Unrelated; new OH3 channel profile capabilities _should_ mean we can now take a numeric channel and feed into a UoM type Item i.e, adding the units of our choice.

**Comment by ssalonen** [comment]
UoM would be very welcome... Do you if profile support nowadays transforming commands?

Good point about performance, it's a valid point. I presume javascript has very good performance.

Another benefit of javascript is that by learning that you have more freedom.

**Comment by Rossko57** [comment]
"Do you if profile support nowadays transforming commands?"

Yes, it will not be backported to OH2, but OH3 transform profile can now be used with any Item type, is no longer restricted to Strings.
As part of this change, it can be used to link to QuantityType Items as well.

https://github.com/openhab/openhab-core/pull/1603

For an example, it could take a `2271` update from modbus binding `number` channel, transform to `"22.71 °C"`, and pipe to a `Number:Temperature` type Item.
Obviously has some uses
- but -
It is a one-way transform, quite what will happen if you write a command to such an Item I do not yet know.


" I presume javascript has very good performance."
This I do not know.  I have seen others knowing more than me say - NO, it's poor.  I think there's an overhead to loading up the js each time, or something like.  This may be different in OH3 and/or Java 11

**Comment by ssalonen** [comment]
Hmm ok, so it is one-way still.

Need to try out at some point if UoM would work with transformations, I think it probably does.

With UoM I am not sure anymore if the Jinja is so much more convenient, so perhaps it is better to guide users to more general-purpose JS.

**Comment by ssalonen** [comment]
Hmmm, reading the code it actually looks bidirectional at least in OH 

https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemOffsetProfile.java

‘’’
    @Override
    public void onStateUpdateFromItem(State state) {
    }

    @Override
    public void onCommandFromItem(Command command) {
        callback.handleCommand((Command) applyOffset(command, false));
    }

    @Override
    public void onCommandFromHandler(Command command) {
        callback.sendCommand((Command) applyOffset(command, true));
    }

    @Override
    public void onStateUpdateFromHandler(State state) {
        callback.sendUpdate((State) applyOffset(state, true));
    }
‘’’

**Pull request closed without merging**
