### PR TITLE
[venstarthermostat] Update README.md

### PR DESCRIPTION
**Pull request by digitaldan**
Small typo in README

Signed-off-by: Dan Cunningham dan@digitaldan.com

### CODE REVIEW

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by cpmeister** [comment]
Can you add a sign-off?

**Comment by digitaldan** [comment]
Will do, i tried for the first time using the github web editor to make the change, did not think about the lack of a sign off.

**Comment by digitaldan** [comment]
Actually i'm going to close this, i did not realize this created a branch on our main repo, i assumed it created one in my personal repo.  That will be the first and last time I use the github web editor.

**Comment by digitaldan** [comment]
See #8500 , apologies for the confusion.

**Pull request closed without merging**
