### PR TITLE
[shelly] Fix missing /shelly/manager

### PR DESCRIPTION
**Pull request by wborn**
Using Whiteboard annotations seems to fix this issue.

### CODE REVIEW

**Comment by J-N-K** [comment]
I wonder why I didn't come across this when working on the karaf upgrade PR...

**Review by J-N-K — APPROVED** [review]
LGTM

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by wborn** [comment]
Just add unit tests for it and it will never happen again. :wink:

**Pull request merged**
