### PR TITLE
[tesla] Fix update timestamp and null exception for offline state

### PR DESCRIPTION
**Pull request by billfor**
# Description

- Fix the update channel.
- Fix a NULL exception caused by attempted poll when vehicle is offline.

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
I am not sure @kgoderis is still really active here. Maybe @kaikreuzer you would like to validate ?

**Comment by kgoderis** [comment]
I am still alive and I follow at a distance. :-) you guys don’t really need me to improve certain things Sent from my iPhoneOn 16 Oct 2023, at 22:22, lolodomo ***@***.***> wrote:﻿
I am not sure @kgoderis is still really active here. Maybe @kaikreuzer you would like to validate ?

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
