### PR TITLE
[deconz] add categories and tags to lights (where applicable)

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by jensflorian** [comment]
`		<state pattern="%d K" min="15" max="100000" step="100"/>`

Note this will look in OH3 as follows:
Bildschirmfoto 2020-12-06 um 15 57 38

I think a proper range for color temperature would be usually from 1000-10000 K.

**Comment by J-N-K** [comment]
That’s a different issue. In general the State descriptions should reflect the device properties. The default range (which is equal to the range of the zigbee specification) is used if the device properties are not reported.

**Comment by J-N-K** [comment]
Jenkins fails unrelated

**Comment by lolodomo** [comment]
Just for my better understanding: added tags are semantics tags for openHAB? 
Because if true the tag should be "Light"  and not "Lighting" I believe.

**Comment by J-N-K** [comment]
http://next.openhab.org/docs/developer/bindings/thing-xml.html#default-tags clearly defines `Lighting` and also states that only tags in the list should be used.

**Comment by lolodomo** [comment]
Are you sure these tags are not outdated? 
What's the purpose exactly?  Is it to automatically add the right semantics tags from our model to the item when linking the channel to it? Would it mean that the core framework is converting "Lighting" Into "Light" during this operation? 
Or us this tag independent of our semantics model? What is its usage in this case?

**Comment by J-N-K** [comment]
If the tags really changed, that should be reflected in the developer documentation. Also HUE uses the same tags. Tags show up in the same way in the UI, so I doubt there is something rewritten.

**Comment by lolodomo** [comment]
Maybe these tags were designed for vocal assistants ? Not for Google home anymore as it is now using metadata like `ga="Light"`. Maybe for Amazon Alexa or Apple Homekit ?
I was just asking myself if we should start adding tags from our openHAB semantics. I think I read one time @ghys saying we should do. @ghys: can you help me understand the purpose of these tags on the channel and whether we should also consider tags from our semantics classes ?

**Comment by ghys** [comment]
I have no idea what http://next.openhab.org/docs/developer/bindings/thing-xml.html#default-tags is (the table), it's the first time I see this table. I have made https://github.com/openhab/openhab-webui/pull/577 recently so that when you use the "add items from thing" feature the default tags that are defined on the channel or channel type are added to the item. If they are semantic tags then yes they will contribute to the model.
@marcelrv has already added some semantic tags to the miio binding, see https://github.com/openhab/openhab-webui/issues/576 (first screenshot).

**Comment by lolodomo** [comment]
Ok, this is what I understood. So the idea now would be to add semantics classes as tags in binding channel types.
And the developer guide has to be updated.

**Review by cpmeister — APPROVED** [review]
LGTM

**Pull request merged**
