### PR TITLE
Inital contribution of MAX! binding

### PR DESCRIPTION
**Pull request by marcelrv**
Here is the refactored MAX! binding

Signed-off-by: Marcel Verpaalen marcel@verpaalen.com

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi @marcelrv! It seems I have completely missed to ask you for a small README documentation, which I could refer to from https://github.com/openhab/openhab2/blob/master/docs/sources/addons.md.
I had created a short guide on how to do it: https://github.com/eclipse/smarthome/blob/master/docs/sources/development/extensions/bindings/docs.md
It would be great if you could create a PR with such an README - thanks!

**Comment by marcelrv** [comment]
speaking of it....
I'm close to completion of it...

https://github.com/marcelrv/openhab2/blob/patch-1/addons/binding/org.openhab.binding.max/README.md

2015-05-25 22:11 GMT+02:00 Kai Kreuzer <notifications@github.com>:

**Comment by kaikreuzer** [comment]
Will it be complieted within the next 10 minutes? Then I would be able to add it to the alpha 2 release :-)

**Comment by marcelrv** [comment]
If I would have seen your email :-)
#255 created

**Pull request merged**
