### PR TITLE
[Telegram] Can't send message with underscore character

### PR DESCRIPTION
**Pull request by clinique**
Escapes the "_" in the message. Solves issue #11691

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@clinique : was it tested ?

**Comment by clinique** [comment]
> @clinique : was it tested ?

Yes. I replicated the example presented in the issue.

**Comment by mtzro2003** [comment]
Hi guys!

Implementing this breaks the formatting of the messages using `markdown` as the underscore means italic...
Of course, I could switch to using `HTML` in `parseMode`, but then `markdown` is not fully functional, so maybe it could be entirely removed from thing configuration.
Up until now, I escaped underscore (and other markdown characters) when sending telegrams with items names with a simple 
```
result.replace("_", "\\_").replace("*", "\\*").replace("[", "\\[").replace("`", "\\`")
```

**Comment by lolodomo** [comment]
A new issue would have been better. Without, there is a good risk to "loose" your message.
Pinging @clinique.

**Comment by RubenKona** [comment]
New implementation on 3.4 break original messages with "_". Before (3.3 and earlier, Windows 10) works perfectly with messages with underscores. Now always add extra characters, so, for example, URLs or user names and passwords on messages doesn't works anymore.

**Pull request merged**
