### PR TITLE
[avmfritz] Minor improvements and SAT findings

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed dependency on `org.apache.commons`
- Moved model classes into dto package
- Added nullness annotations
- Slim down config class
- Minor improvements

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
Please leave a comment on everything you have in your mind. As I said: My plan is to refactor the binding step by step.

**Comment by cpmeister** [comment]
Well, one thing that stuck out that I honestly could go either way one is the use of `@NonNullByDefault({})` in your configuration class. I'd prefer if it wasn't used but I completely understand why it was used. 🤷‍♂️ 

But I can see a bit of optimization that could still be done in the `onDeviceUpdated` method in the base handler class to reduce redundant method calls.

**Comment by J-N-K** [comment]
The `@NonNullByDefault({})` annotation is not an injected OSGi service. Therefore it cannot be used there (even if I still think that it should be allowed wherever the code makes sure the field is non-null before access).

**Comment by cpmeister** [comment]
Should we allow Configuration classes to be omitted from the null checker? They are basically DTO classes anyway.

**Pull request merged**
