### PR TITLE
remove @J-N-K from CODEOWNERS

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Review by martinvw — APPROVED** [review]

**Comment by Skinah** [comment]
Thank you for all that you have done and sorry to see you leave, wishing you all the best in the future.

**Comment by J-N-K** [comment]
Since four of you reacted with the „confused“ emoji, let me
explain why this PR was raised. 

You might have noticed in the discussions in some recent PRs and issues that there are differences within the maintainers group. Since this differences are not solved the way it should be (e.g. vote of the maintainers or decisions of the AC) but by sole decisions of one maintainer (or some unofficial sub-group of maintainers) with an „everything is discussed“ attitude, I decided to step down and leave the project. This was not an easy decision (as you might guess after several years and more than 360 PR on this project) and I hope that someone else steps up and takes over. OpenHAB is a good piece of software, but project management needs to be improved.

**Comment by kaikreuzer** [comment]
> project management needs to be improved

FTR, we have a clear and documented process for it (https://www.openhab.org/docs/developer/governance.html) and I do not recall a single PR where a veto of one maintainer was ever ignored.
If this happens, I think it should first be discussed in the maintainer group and if there is dissent, it can be escalated to the AC. Nothing like this seem to have happened here, which is a pity.

I nonetheless respect your decision and your contributions for the project.
Please let us know if you also resign as a maintainer of @openhab/add-ons-maintainers.

**Comment by J-N-K** [comment]
@kaikreuzer True, there is a process. But a process that is not followed is worth nothing.

Just look at your last PR in core. That was a clear veto from my side and has been ignored.

**Comment by kaikreuzer** [comment]
> That was a clear veto from my side and has been ignored.

You should mention that you are not a member of @openhab/core-maintainers, so maybe there is some misunderstanding.
The [governance documentation](https://www.openhab.org/docs/developer/governance.html#maintainers) clearly states:
_"This means that the maintainer role is always related to a certain repository/component only and not to the entire project as such."_

**Comment by J-N-K** [comment]
Funny, that’s exactly the problem.

It‘s true that it‘s a core PR, but it affects ONLY addons, since the channels are only used in addons. If you look at the discussions in the corresponding deconz issue, I already clearly stated my opinion there. And all participants agreed that we can have both channels, even if I think that the one preferred by you is the wrong one. Now you make a change in core (where I have no vote) which overturns the agreement reached in addons and declare that all rules have been followed.

**Comment by J-N-K** [comment]
Since the discussion seems to have come to an end: yes, please remove me from @openhab/add-ons-maintainers.

I would have preferred to tell you that personally, but unfortunately that wasn't possible. So here's my last word on this issue: Maybe you whole-heartedly do respect other's contributions to the project. But that is (beside you stating that) not reflected in your behaviour towards the community. You should think about why other maintainers told me in private communication that "they understand how I feel" or that they "sometimes wonder what their place in the project is". You could also ask yourself if all the contributors (and maintainers) the project lost over the past few years were all wrong when they complained about exactly the same things as I did. It's not always the other who are wrong.

**Review by clinique — APPROVED** [review]

**Comment by kaikreuzer** [comment]
> And all participants agreed that we can have both channels

Yes, and the very clear outcome was that "every binding implements the color temperature channel in the above described openHAB style. Some of them provide an additional channel for colorTemperatureAbs", see https://github.com/openhab/openhab-addons/issues/8260#issuecomment-762321923. 

> Now you make a change in core (where I have no vote) which overturns the agreement reached in addons 

Note that it was me who actually even suggested adding the ct-abs as a system channel type in the first place (https://github.com/openhab/openhab-addons/pull/9939#discussion_r563328208) - and this channel was marked as advanced already there, so https://github.com/openhab/openhab-core/pull/2183 was merely a fix upon https://github.com/openhab/openhab-core/pull/2157. Nothing was overturned and everything was done as discussed in addons and in a fully backward compatible way.

[Threatening](https://github.com/openhab/openhab-addons/issues/8260#issuecomment-762364553) to stop maintaining a binding if it has to follow the rules, is imho not an acceptable behavior for a maintainer - and this unfortunately hasn't been [the only time](https://github.com/openhab/openhab-addons/issues/9480#issuecomment-750122107).

**Comment by J-N-K** [comment]
Don‘t twist reality. In the second link I said, I‘ll not develop new bindings if I need to provide textual configuration. That’s very different from not maintaining a binding.

And yes, I still think that breaking correct implementations just for the sake keeping a broken definition that has been set in the somewhere in the past and never used in actual code is wrong.

**Pull request merged**
