### PR TITLE
[aWATTar] Fix countdown and remaining channels

### PR DESCRIPTION
**Pull request by tl-photography**
This PR fixes the countdown and remaining channels stuck in "undef".

The channels would not get updated when the conditions are not met and the default is UNDEF.

### CODE REVIEW

**Comment by lsiepel** [comment]
Do you know when this problem was introduced? I see some risk to backport to 4.2, wdyt?

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM. Would be nice if @Wolfgang1966 can confirm.

**Comment by tl-photography** [comment]
I'm currently on 4.1.3 and this is already broken.
I haven't seen an issue for this yet, so I guess it's not that important...?

**Comment by tl-photography** [comment]
No worries, it's a small fix for a not that important issue

**Review by Wolfgang1966 — APPROVED** [review]

**Comment by Wolfgang1966** [comment]
LGTM. Thanks for addressing this issue :-)

**Pull request merged**
