### PR TITLE
[shelly] Fix generation 1 device support

### LINKED ISSUE #16990: [shelly] Support for Gen1 devices dropped in 4.2.0.M4?
I have several devices (Gen 1) of type "Shelly 1" or "Shelly 1PM". They suddenly stopped working after upgrade from 4.2.0.M2 to 4.2.0M4.

This is the error which is shown in the UI

```
COMMUNICATION_ERROR
An unexpected API response. Please verify the logfile to get more detailed information.
```

On the other hand I have a new "Shelly 1 Mini Gen3" device which works fine with 4.2.0.M4. Both types of devices work very well with 4.2.0.M2

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #16990

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by kaikreuzer** [comment]
@markus7017 In case you are around tonight, it would be great if you could have a quick look (and also at the linked community discussison).

**Comment by J-N-K** [comment]
As I said in the community forum: IMO someone using gen 2 devices should confirm that this still works.

**Comment by markus7017** [comment]
I thin the problem occurs when device is defined in .things. If discovered and added by mDIS the recovery handler adds the deviceGeneration flag. This is missing when define in .things. Let me check

**Comment by lolodomo** [comment]
It will be also missing if thing is declared manually in UI.

**Comment by markus7017** [comment]
I think 

gen2 = ShellyDeviceProfile.isGeneration2(thingType) ||  "2".equals(gen);
should do the job without changes to the xml
@J-N-K could you please give this a try

I don't have a .things setup

**Comment by J-N-K** [comment]
I can't test anything. I don't have shellies. If you believe there is a better way, feel free to create another PR and close this one.

**Comment by lolodomo** [comment]
We can't discuss ages, the RC2 is planed this morning.
As the binding is currently broken for Gen 1 devices, and as I don't understand how the fix could badly impact users with Gen 2 devices, I would be in favour to merge immediately.
Then users could try with RC2.

**Comment by lolodomo** [comment]
As I may understand, this property is only to provide information to the user about the device generation. And we have a function to identify generation 2  based mainly on used thing type.
Why using this property at the place we are fixing in that PR (that is when initializing the thing handler) and not just calling the method ?
If I am right, it could be improved later, but  after 4.2 is released.
But maybe I am loosing something @markus7017 ?

**Comment by markus7017** [comment]
This property usually is set in mdns discovery and works for Gen 1 and Gen 2+3. The binding has to use 2 different APIs. The problem occurs when a thing is defined in a .things file and the peoperty is not set. This loc determines the property based on the mdns service name. 

What happens: Thing is defined in .things without the property, which means gen is empty. Now the code says !"1".equals() which is fine if gen is not blank, but otherwise leads into wrong outcome, so the binding tries to initialize a Gen 1 device with the Gen 2 API.

Let me try to setup a .things config to verify the mentioned loc.

**Comment by maniac103** [comment]
> This property usually is set in mdns discovery and works for Gen 1 and Gen 2+3. The binding has to use 2 different APIs. 

I think that part is well understood. What @lolodomo intended to ask, I think is
- Why is the property used for determining the API to use, instead of relying solely on the thing type?
- Assuming relying on the thing type is not sufficient for whatever reason, why is it a property and not a configuration parameter so that users can override it in .things files?

**Comment by markus7017** [comment]
Problem fixed, I created PR #17009

**Comment by lolodomo** [comment]
Thank you @maniac103 for clarifying my thoughts. Your summary is perfect.
I am afraid there was a possible mismatch between concepts (configuration parameter and property).

**Pull request closed without merging**
