### PR TITLE
[homeconnect] Add missing channel update handler configuration

### PR DESCRIPTION
**Pull request by lolodomo**
Related to dryer, washer and washer/dryer appliances

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@bruestel : please have a look, I have the feeling that some channel update handler were not setup and it could lead to channels not being initialized when the channel "selected_program_state" was not linked.

**Review by bruestel — APPROVED** [review]
"please have a look, I have the feeling that some channel update handler were not setup and it could lead to channels not being initialized when the channel "selected_program_state" was not linked."

Yes you are right. The original aim was to prevent too many API requests from being triggered. But, since we have caching at the API request level, it shouldn't be a problem. Furthermore, we are throttling the API requests.

After the rebuild, I just forgot about these handlers.

**Comment by lolodomo** [comment]
@bruestel : I factorized duplicated code after your approval. So please review again to cover the last little change.

**Review by bruestel — APPROVED** [review]
:+1:

**Review by fwolter — APPROVED** [review]

**Pull request merged**
