### PR TITLE
[freeboxos] Change default HTTPS port

### LINKED ISSUE #17075: [freeboxos] Strange default value for parameter httpsPort
For the bridge thing, the default HTTPS port is set to 15682.
When I use the default domain, that is "mafreebox.freebox.fr", the expected port is 443 but 15682 is used by default if HTTPS is enabled and as a result the request fais.
Why did you set the default to 15682 @clinique ?
The workaround is to force the port to 443 in the thing configuration.

### PR DESCRIPTION
**Pull request by lolodomo**
Set default to 443 as it is the default HTTPS port to use to connect to mafreebox.freebox.fr.

Fix #17075

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Please wait @clinique approval before merging.
Maybe there is a mystery I am not understanding. Do you need port 15682 to access mafreebox.freebox.fr ? For the Freebox Revolution, I have to use port 443.

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by clinique** [comment]
Yes, I'll dig this - this port number does not come out of the blue

**Comment by lsiepel** [comment]
> Yes, I'll dig this - this port number does not come out of the blue

Sorry, you approve the PR (the port wil change from 15682 to 443) or not?

**Comment by lolodomo** [comment]
> Sorry, you approve the PR (the port wil change from 15682 to 443) or not?

He wants first to understand fwhy he sets it to 15682.
So, we are waiting for his feedback.
Until that, the workaround is to not rely on default but set the parameter to 443.

**Comment by lolodomo** [comment]
> I'm unable to test / analyze it until the end of the month.

No hurry as there is a workaround.

**Comment by clinique** [comment]
@lolodomo : you can proceed with this one, I did not find any obvious reason for using 15682 (I'm using 27068 on my side).

**Review by clinique — APPROVED** [review]
LGTM

**Pull request merged**
