### PR TITLE
[hdl][WIP] HDL Binding initial contribution

### PR DESCRIPTION
**Pull request by stigli**
[HDL][WIP] Initial contribution for HDL Automation.

This is a new binding for the smart house system HDL Automation.
There is no issues in the static code analysis.
Squashed every commit and added sign off on commit

Readme file has been updated and will be updated when there is question in the forum thread:
https://community.openhab.org/t/new-binding-hdl-automation/67204

Jar file can be found her:
https://github.com/stigli/openhab2-addons/tree/master/addons/binding/org.openhab.binding.hdl/releases

### CODE REVIEW

**Comment by davidgraeff** [comment]
If you want a review by maintainers, you need to remove the WIP from the title :)

**Comment by stigli** [comment]
Okey, thought that was when it should be added to the offical repo.

**Comment by stigli** [comment]
OK  will look over. Thank you.

**Comment by davidgraeff** [comment]
That's sweet :D You just talked to our bot :) The bot will tell you when your PR compiled successfully on our continuous integration service or when it failed, and will even attach the log file.

**Comment by stigli** [comment]
hehe have to be nice to the bots you know. Before they take over the world.

**Comment by J-N-K** [comment]
What's the status here?

**Comment by stigli** [comment]
> What's the status here?

Hi. working on gettting it building with bnd. Something strange and it does not want to start after converting.

**Comment by Hilbrand** [comment]
Closing due to long time no activity. If you still need help with migrating or still want to continue with this binding feel free to ask or reopen this pr.

**Pull request closed without merging**
