### PR TITLE
[tado.doc] Updated tado binding documentation for tado X

### PR DESCRIPTION
**Pull request by JPlenert**
Updated the documentation of the tado binding, as the current binding is not compatible to the new tado X devices.
Inserted a swagger link to updated API for the new devices.

### CODE REVIEW

**Comment by andrewfg** [comment]
@JPlenert looking at the API it seems we should be able to adapt the existing binding to support X devices as well. WDYT?

**Comment by JPlenert** [comment]
> @JPlenert looking at the API it seems we should be able to adapt the existing binding to support X devices as well. WDYT?

I think that should be possible! If openhab had been written in C#, it would have been finished long ago - But I'm not a Java guy :-)

**Review by andrewfg — APPROVED** [review]
LGTM

**Comment by JPlenert** [comment]
@andrewfg More then welcome! But the comment I made in the documentation stays true - this binding doesn't work with the tado X products and Matter Binding is not existing and tested with Tado X.

**Comment by andrewfg** [comment]
Yes. The comment is fine. I already approved this PR.

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

> Signed-off-by: JPlenert <joerg@plenert.net>

As this is a small documentation improvement, i applied the small patch exception, but you might want to look into the signoff's as we have a real name policy.
For reference: https://www.openhab.org/docs/developer/contributing.html#sign-your-work

**Pull request merged**
