### PR TITLE
[netatmo] Fix the thresholds for the WifiStatus channel

### LINKED ISSUE #10540: [netatmo] WifiStatus channel never set to "excellent"
For the Wifi status channel, we are relying on the system channel type `signal-strength`.
This channel type expects a value between 0 and 4.
Unfortunately, the binding is only producing a value between 0 and 3. The channel value will then be "good" in best case but never "excellent".
This is due to this property set on the thing type:
```
<property name="signalLevels">86,71,56</property>
```
This list should rather contain 4 values.

In my own case, the netatrmo app is showing an "excellent" wifi level but OH is saying just "good". So I know I should add a 4th value lower than 56.

@clinique : any suggestion for the last value to add ?

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #10540

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by clinique — APPROVED** [review]

**Comment by lolodomo** [comment]
I am going to check how good are the new thresholds by moving the station at different places in my house and compare with what is showing the Netatmo app.

**Comment by lolodomo** [comment]
This is clearly not obvious to experiment !
But I believe that the first value leading to a switch from 4 bars to 3 bars is 55 and the first value leading to a switch from 3 bars to 2 bars is 70.
That would mean we should use 69 and 54 as thresholds.
I will have now difficulty to experiment lower quality Wifi, I should move the station outside the house for that !!

**Comment by lolodomo** [comment]
Small house, small garden. Even in the garden, the wifi connection is between average and good.
So I stop the experimentations. The new values are probably not so bad, certainly better than the previous ones.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
