### PR TITLE
[lcn] Add shutter positioning/angle, operating hours counters, tunable white, regulator mode, beeping

### PR DESCRIPTION
**Pull request by fwolter**
Also, fix possible race condition during connecting, when the PC coupler is not connected to the LCN data wire.
Replace discontinued LCN-PKE by LCN-VISU.

Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

### CODE REVIEW

**Review by jlaur — CHANGES_REQUESTED** [review]
Thanks for these improvements. It looks good, and I particularly like the ratio of test classes changed vs. total number of classes changed. :-) Only a small request to remove the updated German translation and instead provide the changes in Crowdin after having the PR merged. For reference: https://www.openhab.org/docs/developer/utils/i18n.html#managing-translations

**Comment by fwolter** [comment]
Sure, fixed!

**Review by jlaur — APPROVED** [review]
Thank you!

**Comment by fwolter** [comment]
Thanks!

**Pull request merged**
