### PR TITLE
[lgwebos] Handle volume update whatever the audio output

### LINKED ISSUE #7207: [lgwebos] Volume issue since update
Since update, I'm not longer able to use delta volume from LG WebOs Tv. Previously tv set to "LG Sound Sync" openhab WebOS binding would watch for volume changes, I then in turn would use this in a rule to control my Denon Receiver located in a different portion of the house. 

On "Internal Speaker" Openhab/WebOs binding see's the volume change, on any other setting it does not.

I believe this issue is related to this change. Can I get this reverted or instructions on where to locate this file to change.

https://github.com/openhab/openhab-addons/commit/e1b14edd146c9bfe93e5200ba0368929f55bb3ba

Openhabian / Pi 3
LG OLED 55' 2017
WebOS binding
on latest updates.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #7207

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by cpmeister** [comment]
What about delta values?

**Comment by lolodomo** [comment]
I have no idea how to produce delta value. My TV seems to produce only absolute values.

**Comment by cpmeister** [comment]
@sprehn Can you give your input for this PR?

**Comment by sprehn** [comment]
I think this is the right approach - LGTM

**Pull request merged**
