### PR TITLE
Upgrade SAT to 0.14

### PR DESCRIPTION
**Pull request by holgerfriedrich**
New static code analysis tools package has been released, lifting the versions of

    PMD from 6.39.0 to 6.53,
    SpotBugs from 4.7.0 to 4.7.3,
    Checkstyle from 8.45.1 to 10.6.0;
    and to adapt to schema changes in OH 4.0.

Looking at the check results, there is one substantial difference between 0.13 and 0.14, see the comparison below:
image

- pmd UnusedPrivateMethod is reduced by ~100 
- (EmptyControlStatement replaces several Empty* rules, this is intended)

Refs: openhab/openhab-core#3599

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
@J-N-K new SAT requires a : in ```addons.xml```, section ```config-description-ref` uri``` - can I just change io.xxx to io:xxx or is this wrong?

**Comment by J-N-K** [comment]
I only checked HomeKit, it seems that `io.homekit` is wrong. The `config.xml` declares `io:homekit` and that is also what is referenced by `HomekitImpl`.

**Comment by holgerfriedrich** [comment]
Thanks, @J-N-K. I checked the others. Seems fine.

So, this PR in now ready for review.

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
