### PR TITLE
Resolve itests after jUPnP upgrade

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Review by hmerk — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
For reference: https://github.com/jupnp/jupnp/tree/2.6.1

**Comment by kaikreuzer** [comment]
I've now removed all jUPnP unrelated changes the resolver did - let's hope this solves it.

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
