### PR TITLE
[VolvoOnCall] Backports of fixes for #8554 and #8518 to 2.5.x branch

### PR DESCRIPTION
**Pull request by mbronk**
- Fixes issues #8554 and #8518 in **2.5.x branch** as well as backports request cache functionality (already fixed by @clinique on main)
  - Note #8554 is a critical fix for the binding - without which it is completely defunct (on all 2.5.x versions).  The fix needs to be accompanied by cache addition, as the binding creates way too much traffic otherwise

--
The intent of the PR was to minimize changes and to *avoid* changing code structure wherever possible, so that any negative system-wide effects can be, hopefully, contained. Individual changes are in separate commits, for possibly cherry-picking.
_Since this is a backport, all the changes herein are already in mainline branch (conceptually), so if there's ever a need to merge back, conflict resolution strategy should be to take all the changes from 'main'. Given the 3.x binding (on 'main') has undergone a substantial refactoring, this means this PR is *NOT* mergeable as-is to the main branch._

### CODE REVIEW

**Review by clinique — APPROVED** [review]

**Comment by mbronk** [comment]
@kaikreuzer - would you mind taking a look at the [Jenkins build result #21727](https://ci.openhab.org/job/PR-openHAB2-Addons/21727/console)? It fails to collect git changes with a: `refusing to merge unrelated histories`...

I _think_ it has to do with the recent history rewrite and **openhab2-addons** -> **openhab-addons** transition though run out of ideas :( 
As far as I can see, the PR is properly branched off the '_new_' 2.5.x branch (openhab-addons) and Github is happy to merge it... while Jenkins fails. Could it be due to stale workspace contents on the build agent?
Please advise what can I do to get this merged...

FYI - there's a squashed version of the same available here (#8661) - just in case there would be a need of a manual cherry-pick etc.

Thanks!

**Comment by kaikreuzer** [comment]
@mbronk This looks all a bit messy here.
There should be a PR on main, which can then be backported to 2.5.x, if really a critical fix. Ideally, this can happen by cherry-picking the commits from main to 2.5.x. For this, it is important to have dedicated PRs for different issues - a PR shouldn't include all kinds of different things...

> I see the job triggered for this PR is 'PR-openHAB2-Addons' and not 'PR-openHAB-Addons'. Could it be the reason?

This is what one expects, isn't it? The PR is for openHAB2, so the according build plan is triggered. I have now cleaned its workspace to see if the build issues are solved by that.

**Comment by mbronk** [comment]
> This looks all a bit messy here.
> There should be a PR on main, which can then be backported to 2.5.x, if really a critical fix. Ideally, this can happen by cherry-picking the commits from main to 2.5.x. 

@kaikreuzer : Well... this PR is actually an attempt to clean up the situation a bit - maybe a failed one, but an attempt nonetheless :) Feel free to propose a different resolution strategy and/or split/change this PR as you see fit.
**Current state:** There is a PR on main (by @clinique) - #8595, which does quite a lot of refactoring **as well as fixes** both issues. That one is already in, and IMHO **not** cherry-pickable to 2.5.x (at least not as-is).
I am also of the opinion that sustaining branches should not receive non-essential refactorings a5nd other changes - which is why I am not even proposing trying to merge entire PR #8595 and try to make it OH2.5-compatible again. 
I could make 2 PRs for the same... though decided to do atomic commits and a single PR (as they are very related and either all or none should go in)



> For this, it is important to have dedicated PRs for different issues - a PR shouldn't include all kinds of different things...

Couldn't agree more... Though as stated above, we *are* in this situation already on 'main'. This is an attempt to straighten this out, actually.



> I see the job triggered for this PR is 'PR-openHAB2-Addons' and not 'PR-openHAB-Addons'. Could it be the reason?
> > This is what one expects, isn't it? The PR is for openHAB2, so the according build plan is triggered. I have now cleaned its workspace to see if the build issues are solved by that.

I don't know your Jenkins setup, so might be mistaken, but I am assuming that this branch should build with OH2.x config (JDK8 etc.). At the same time, this being a PR against openhab-addons repo (and not the frozen 'openhab2-addons')... I wonder if it shouldn't it have the new git checkout settings(?)

**Comment by mbronk** [comment]
FYI - The force-push is just to trigger a new Jenkins build after the agent's workspace has been cleaned. No code changes

**Comment by kaikreuzer** [comment]
Ok, thanks @mbronk for your detailed explanation! I agree, under the given circumstances, your PR is the right thing to do.

> I am assuming that this branch should build with OH2.x config (JDK8 etc.). At the same time, this being a PR against openhab-addons repo (and not the frozen 'openhab2-addons')... I wonder if it shouldn't have the new git checkout settings(?)

The `openhab2-addons` repo is just for keeping the old history available. The code of the head is identical to the `2.5.x` branch in the `openhab-addons` repo. So BOTH versions (2.5 and 3.0) are in the `openhab-addons` repo (as it has been since the beginning of the year already). And yes, Jenkins builds the 2.5.x branch with Java8 and the main branch with Java11, so all fine.

**Comment by mbronk** [comment]
@kaikreuzer  - I see the Jenkins build has now passed... Thanks for your help!
Was it cleaning the agent workspace that helped, or did you have to reconfig the job? 

BTW. could you please add additional reviewers to this PR (and tag with 2.5.10, maybe) so it can be merged in the future?

**Comment by kaikreuzer** [comment]
> Jenkins build has now passed

Perfect 👍 

> Was it cleaning the agent workspace that helped

Yes - I had that in the past as well, it sometimes gets messed up by having different PRs with different histories...

> BTW. could you please add additional reviewers to this PR

No need for additional reviewers. @clinique already approved and I had a quick look over it as well, so we are good to merge!

**Review by kaikreuzer — APPROVED** [review]

**Comment by mbronk** [comment]
> No need for additional reviewers. @clinique already approved and I had a quick look over it as well, so we are good to merge!

Perfect. Thanks tons for your help!

**Comment by kaikreuzer** [comment]
Thank you for your work!

**Pull request merged**
