### PR TITLE
[freeboxos] Fix enabling/disabling of Mac OS file sharing

### LINKED ISSUE #17200: [freeboxos] Mac OS file sharing enabling/disabling is failing
Log says:  Api request failed: Impossible de mettre à jour la configuration Afp

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #17200

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lsiepel** [comment]
Replace an enum with a string? I would opt to change the configuration parameter to have options in the xml, so the value can be chosen from the UI.

For file based config, I propose to add a check in the initialize method. This check would check if the enum.valueOf(config.parameter.topUpper()) throws an illegal argument exception and set the thing state to configuration_error accordingly.

string is also possible, but with a limited list I would really prefer enum.

**Comment by lolodomo** [comment]
This is only an API field that is returned by the API but unused by the binding.
I could also remove it but @clinique option was to have a full DTO which makes sense.

**Comment by lolodomo** [comment]
Look at lines 61-63 to understand.
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/AfpManager.java#L62

It is not OH thing configuration but Freebox OS config API.

**Comment by lsiepel** [comment]
Based on the text in the linked issue I thought it was the openHAB config. Nevertheless still prefer proper enum conversion, no magic strings in the code, but it ie much less important and certainly not blocking. 

LGTM

**Comment by lolodomo** [comment]
API filed is a string.

**Comment by clinique** [comment]
Still I don't understand the purpose of removing the enum.

**Comment by lolodomo** [comment]
> Still I don't understand the purpose of removing the enum.

The get API returns value "airport" in lowercase for the field server_type.
When using the set API, you have to use "airport" also. If the field is set with "AIRPORT", the API simply fails.
Due to the conversion to an enum, string "airport" is first converted to enum value AIRPORT when handling the get API. When reused and serialized in the PUT request, the server_type field was set with "AIRPORT" and the API failed.

@clinique : is it clearer now ?

**Review by clinique — APPROVED** [review]

**Pull request merged**
