### PR TITLE
[RFXCOM] Adding support for T11 Blind1 Type

### PR DESCRIPTION
**Pull request by MPH80**
The T11 Blind type - ASP - works within the binding and the code is supported, but the configuration option was missing within the blinds1 xml file - this corrects that missing entry and adds them as supported into the readme.

I've been running this version locally for about 2 months now using blinds by Louvolite which are reported as ASP type in RFXMgr

### CODE REVIEW

**Comment by MPH80** [comment]
Alright - screwed this up - closing the pull request. Will try again another day!

**Comment by martinvw** [comment]
@MPH80 the changes look fine and we wil squash it in a single commit. What is the problem why you think it’s cannot be salvaged?

**Comment by MPH80** [comment]
> @MPH80 the changes look fine and we wil squash it in a single commit. What is the problem why you think it’s cannot be salvaged?

I had failed to sign the commits so it was alerting me with errors here. I didn't want to waste anyone's time until I had done it properly! I'm an old-timey java dev, so I'm more used to SVN - need to learn git properly. Let me re-figure this out on my end so I do it correctly and then I'll resubmit.

**Comment by martinvw** [comment]
Given its two lines if you can just confirm that you agree to the [DCO](https://www.openhab.org/docs/developer/contributing.html#sign-your-work) I could add on your behalf. If you like we can also spend some time on getting the commits fixed, I have the time and will to help you :-)

**Comment by MPH80** [comment]
Thank you so much for the offer. Unfortunately I spotted it just after I'd deleted the branch I was working on to try and correct my mistakes. I've opened a new PR with the sign off in and hopefully that is all clean!

**Pull request closed without merging**
