### PR TITLE
exclude bundles that are not yet included in the build from the aggregated feature

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Review by wborn — APPROVED** [review]

**Comment by andrewfg** [comment]
Hi @kaikreuzer I am working on a PR #8520 that should fix the problem with building the velux binding, so could you please re-enable that binding in the build reactor so that you can run Travis CI tests on this PR?

**Comment by kaikreuzer** [comment]
@andrewfg Simply enable it within your PR #8520.

**Comment by andrewfg** [comment]
> Simply enable it within your PR #8520.

@kaikreuzer thanks for the suggestion, but I tried that and I still get the Travis error below..

```
[ERROR] [ERROR] Could not find the selected project in the reactor: :org.openhab.binding.velux @ 
[ERROR] Could not find the selected project in the reactor: :org.openhab.binding.velux -> [Help 1]
```

**Comment by kaikreuzer** [comment]
Well, Travis seems to have a point there, since your bundle is not listed in https://github.com/andrewfg/openhab-addons/blob/velux-oh3-main/bundles/pom.xml and hence it is not part of the reactor. 😎

**Comment by andrewfg** [comment]
Yes @kaikreuzer I know that.. ;

The problem is that the binding used to call core methods that were `deprecated` in 2.5.x and which were totally removed from 3.0.0, so although it would build OK in 2.5.x it fails in 3.0.0.

I suppose that somebody removed it from the reactor in order for the rest of the bindings to build. ??

Now, in my PR I have rewritten the "bad" methods so they don't call deprecated core methods any more. And now it does build OK in 3.0.0 with MVN locally. => So all we need to do now, is reintegrate it again into the reactor.

**Comment by kaikreuzer** [comment]
> So all we need to do now, is reintegrate it again into the reactor.

Yes, that's why I asked you to include it in the reactor on your branch. The link above points to your branch and it shows that you have not done so.

**Pull request merged**
