### PR TITLE
[goecharger] Adjusting to changes in the API by GO-E

### PR DESCRIPTION
**Pull request by chilobo**
New temperature fields, amx ...
Suggestions by Samuel Brucksch in july are added.
New attempt to get this merged.

### CODE REVIEW

**Comment by chilobo** [comment]
I tried to get these small changes merged in july already. Suggestions by Samuel Brucksch are already included.
I copied the jar into my existing openhab installation, binding is working. 
Somes users in 
[https://community.openhab.org/t/go-e-charger-wallbox-binding/93338/90](url)
asked me to merge the changes into openhab-addons.
Hopefully I can manage to get it approved, last time I did not manage to do the sign-off ?

**Comment by lolodomo** [comment]
Code was reviewed in #12382 and then the PR was closed! So my comments are in the other PR.

**Comment by chilobo** [comment]
Signed-off-by: Christian Koch <chi.koch@gmail.com>

**Comment by lsiepel** [comment]
Please sign the commit: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by ranzen84** [comment]
Please have a look at https://github.com/openhab/openhab-addons/pull/12400
I think the temps are only available if you have hardware revision 3 of the go-eCharger.
If the temps are changed within this PR, you can not use temp with a charger with older hardware revision

**Comment by jlaur** [comment]
@chilobo - please have a look at #12400 which has just been merged, to see if anything is missing from your perspective.

**Comment by chilobo** [comment]
https://github.com/openhab/openhab-addons/commit/ba03fef082502c38fd89717c17ddd10777cf1189
has support for API 2.0 and is already merged.

**Pull request closed without merging**
