### PR TITLE
[tr064] Use Util.getAndUnmarshalXML method to retrieve phonebook

### LINKED ISSUE #10436: openhab TR064-Binding Timeout while downloading phonebook
Tested with actual TR064 Binding and openhab3.1.0 M3:

If phonebook exceeds an unknown size, the download takes longer than 2000ms which seems to be a hard coded timeout for downloading the phonebook.

All phonebooks with a few entries got downloaded fine and working. But bigger phonebooks don't

small one:

`2021-04-02 18:19:38.311 [DEBUG] [nternal.phonebook.Tr064PhonebookImpl] - Downloaded phonebook Test: {0XXXXXXXXX=NAME, **50=ISDN/DECT Rundruf, **43=Wecker 3, **42=Wecker 2, YYYYYYYYY=NAME, **41=Wecker 1, **1=DECT Wohnung, **2=Fax Büro, **623=DEVICE, **600=Anrufbeantworter, **622=DEVICE, **621=DEVICE, **605=Anrufbeantworter, **9=Alle (Rundruf)}
`

Bigger one:
```
2021-04-02 18:19:40.341 [WARN ] [nternal.phonebook.Tr064PhonebookImpl] - Failed to get phonebook with URL https://192.xxx.xxx.x:49443/phonebook.lua?sid=yyyyyyyyyyyyyyyyyyyyyyyyy:
2021-04-02 18:19:40.341 [WARN ] [nternal.phonebook.Tr064PhonebookImpl] - Failed to get phonebook with URL https://192.xxx.xxx.x:49443/phonebook.lua?sid=yyyyyyyyyyyyyyyyyyyyyyyyyyy:
java.util.concurrent.TimeoutException: Total timeout 2000 ms elapsed
        at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

So please increase timeout or otherwise (my suggestion) make it configureable within Bridge with parameter phonebookTimeout

Thanks for great work of all developers.

### PR DESCRIPTION
**Pull request by cweitkamp**
- Use `Util.getAndUnmarshalXML(...)` method to retrieve phonebook (the method supports timeout 5s and caching)

Fixes #10436

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
I am running this version in my prod environment for two days now without seeing the error described in #10436 anymore.

@JensHoRi would it be okay for you to replace your PR (#10441) by this one?

**Comment by JensHoRi** [comment]
Hello Christoph, 

Of course, if it helps :) 

I‘m not so familiar with Java, just proud to make my very first change 😂

I think yours is much better than just raise the timeout ;)



Mobil gesendet

**Comment by cweitkamp** [comment]
Alright. I closed your PR. Please do not refuse to create more PRs.

**Review by wborn — APPROVED** [review]
Thank you!

**Pull request merged**
