### PR TITLE
[Tankerkoenig] Fixes #8876

### LINKED ISSUE #8876: [tankerkoenig] Thing repeatedly goes offline
## Expected Behavior
It is expected that the binding stays online all (most) of the time.

My Bridge configuration:
```
Bridge tankerkoenig:webservice:Tankpreise "Tankpreise" [ apikey="<api key>", refresh=10, modeOpeningTime=true ]
```

The broken down monitoring part (it is a bit more complex, with delay triggers and notifications sent, but this code shows the relevant parts):
```
rule "Tankerkoenig Binding online (debug)"
when
    Thing "tankerkoenig:webservice:Tankpreise" changed from OFFLINE to ONLINE
then
    logInfo("Tankerkoenig Binding", "The binding is online")
end

rule "Tankerkoenig Binding offline (debug)"
when
    Thing "tankerkoenig:webservice:Tankpreise" changed from ONLINE to OFFLINE
then
    logInfo("Tankerkoenig Binding", "The binding is offline")
end
```

## Current Behavior
I have monitoring in place for most of the Bindings, to see if they go offline, and if there is a problem. This Binding goes offline very often, comes online for a fraction of a second, and then goes offline again. However this does not happen all the time. This is yesterday:
```
2020-10-26 02:42:45.029 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 02:42:45.100 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 02:52:45.317 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 02:52:45.390 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 03:02:45.597 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 03:02:45.666 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 03:12:45.874 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 03:12:45.935 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 03:22:46.192 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 03:22:46.279 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 03:32:46.781 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 03:32:46.846 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 03:42:47.309 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 03:42:47.384 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 03:52:47.888 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 03:52:47.945 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 04:02:48.237 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 04:02:48.286 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 04:12:48.755 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 04:12:48.818 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 04:22:49.334 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 04:22:49.385 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 04:32:49.655 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 04:32:49.721 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 04:42:50.175 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 04:42:50.247 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 04:52:50.567 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 04:52:50.638 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 05:00:51.135 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 05:02:50.852 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 05:12:51.320 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 05:12:51.407 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 05:22:51.668 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 05:22:51.777 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 05:32:52.059 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 05:32:52.107 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 05:42:52.629 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 05:42:52.768 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 05:52:53.325 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 05:52:53.397 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 06:02:53.669 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 22:03:38.124 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 22:13:38.579 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 22:13:38.660 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 22:23:39.161 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 22:23:39.225 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 22:33:39.677 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 22:33:39.753 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 22:43:40.203 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 22:43:40.281 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 22:53:40.765 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 22:53:40.849 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 23:03:41.273 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 23:03:41.376 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 23:13:41.874 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 23:13:41.934 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 23:23:42.459 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 23:23:42.531 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 23:33:42.891 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 23:33:42.938 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 23:43:43.418 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 23:43:43.498 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
2020-10-26 23:53:44.027 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is online
2020-10-26 23:53:44.086 [INFO ] [me.model.script.Tankerkoenig Binding] - The binding is offline
```

I would expect this Binding to stay online, except when there is a network or server-side problem.

## Steps to Reproduce (for Bugs)
Install and configure the binding, use the above Rules code for monitoring the binding.

## Context
Currently I can not reliable monitor this Binding, and most importantly I don't know if it is fetching accurate prices.

## Your Environment
openHAB 2.5.9 (about to be updated to .10), the problem is not new in this version but exists since I started using the Binding.
The openHAB system runs on a Pi 4 with an up-to-date Raspbian system.

### PR DESCRIPTION
**Pull request by JueBag**
Fixes #8876 
Fixes the problem caused by stations reporting "null" instead of "false"
Fixed faulty parsing of opening times in case of daily times ("täglich").

Signed-off-by: Jürgen Baginski <opus42@gmx.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Build failed with spotless errors.

**Comment by JueBag** [comment]
Sorry for that one!

Actually this was my first try using VSCode, which worked for running the changed code in the IDE (able to use breakpoints!!). What didn't work last nigth was directly publishing the changes to Git, however that was working now.
AND two times publishing something  and passing the DCO check immidiatly! That is a progress for me!

**Comment by JueBag** [comment]
Is there anything that I should do? The build failed just BEFORE tankerkoenig.

**Comment by J-N-K** [comment]
That‘s why I retriggered the build. I do not understand why the new tado lib is a problem so often, since it is clearly available in the repo.

**Comment by kaikreuzer** [comment]
Yeah, the tado lib issue is annoying, I couldn't yet figure out the reason for it either...

**Review by cpmeister — APPROVED** [review]

**Comment by kaikreuzer** [comment]
@JueBag Please note that the issue title is what is used for the release notes later on - could you change it to something that roughly explains what situation is fixed?

**Comment by kaikreuzer** [comment]
Cherry-picked to 2.5.x.

**Pull request merged**
