### PR TITLE
[venstarthermostat] Use doubles over Int or float types when processing temperatures, fix Checkstyle Warnings

### PR DESCRIPTION
**Pull request by digitaldan**
Converting everything to a int made it difficult for Celsius users and dealing with half step values.   The code had been using double, float and int types for temperatures, this standardizes on just using doubles.   Tested with both F and C configured thermostats. 

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
Please hold off until PR #10736 is merged so that author does not have to deal with merge conflicts (i'll deal with them instead)

**Review by jferfolia — APPROVED** [review]
Simple variable type harmonization.

**Comment by digitaldan** [comment]
I also  fixed all the checkstyle errors, of which there were a lot.  So while the PR now looks to have a lot changes unrelated to the C/F issue, they are mostly cosmetic (as mentioned in https://github.com/openhab/openhab-addons/pull/10736#issuecomment-855272563)

**Review by fwolter — APPROVED** [review]
Thanks!

**Pull request merged**
