### PR TITLE
[clearone] Add new binding for ClearOne XAP multi-channel audio matrix

### PR DESCRIPTION
**Pull request by ConfusedTA**
Here is my proposed contribution of a binding to allow control of the ClearOne XAP range of devices, which are a multi-way audio matrix (8x8 or 12x12)

I have only implemented a small subset of the features of the XAP devices - mapping of a single input to an output, volume control and mute, and selection of a pre-defined Macro or Preset (which are defined using the G-Ware software).

I have been using this at home for a few months with 2x XAP800 units and 9 output zones (7 mono, 2 stereo), and 4 selectable inputs - as well as a "static" input from my openHAB box which is always mapped to all outputs (for whole-home notifications).

I hope that I've included enough information in the ReadMe, and I understand that without the hardware it is difficult to test!

Signed-off-by: Garry Mitchell <garrymitchell@my105e.com>

### CODE REVIEW

**Comment by ConfusedTA** [comment]
This is my first PR, and it looks like something has got messed up - I did have a gap of a few months in keeping my branch up to date, so I merged changes just prior to submitting this PR... Plus some of my WIP check-ins didn't have a sign-off...

Would it be better for me to cancel this PR, create a new branch, commit my code in 1 signed-off commit, and resubmit the PR?

**Comment by fwolter** [comment]
It's better to use rebase instead of merge in pull requests. Fixing missing sign-off messages is easier, then.

You can stick to this PR and reset your the commits before your first one: `git reset --soft 4adc214`. Then, you can commit your unstaged files for your new binding again and discard all other other changes.

To rebase your changes upon the main branch, do the following:

If not already done, add the upstream openHAB addon repo as a remote to your local repo and fetch it:
```
git remote add upstream https://github.com/openhab/openhab-addons.git
git fetch upstream
```
The remotes (`git remote --verbose`) should look like this, now:
```
origin  https://github.com/[your name]/openhab-addons.git (fetch)
origin  https://github.com/[your name]/openhab-addons.git (push)
upstream        https://github.com/openhab/openhab-addons.git (fetch)
upstream        https://github.com/openhab/openhab-addons.git (push)
```
Then, you can rebase your PR's branch onto `main`:
```
git rebase upstream/main
```
Finally force-push the rebased branch to this PR's branch:
```
git push origin [your branch name of this PR] --force-with-lease
```
**DON'T** use merge! This can clutter the Git history and make the PR unusable.

**Comment by ConfusedTA** [comment]
@fwolter thank you for the feedback.
As you can probably tell, I'm a bit of a newbie when it comes to git, PRs etc, and I think I've done something to mess up my local repository as the commands you kindly suggested aren't completing successfully - I'm half tempted to just throw it all away and start from scratch, as I think that'll be the quicker and easier way - I'll add my binding as a single commit, which is based upon an already up to date base, and whatever the skeleton script does should get applied properly...

**Comment by fwolter** [comment]
It might be indeed easier to open a new PR.

**Comment by ConfusedTA** [comment]
Closing PR as I've messed it up, and will create a new one.

**Pull request closed without merging**
