### PR TITLE
Clean up pom.xml to comply with styleguides.

### PR DESCRIPTION
**Pull request by Hilbrand**

### CODE REVIEW

**Comment by theater** [comment]
OK

**Comment by Hilbrand** [comment]
@wborn No. While adding the ohc.version change (I cherrypicked Kai's commit) I noticed differences in the poms and fixed those by running spotless (left out all the other changes) and manual editing.

**Comment by J-N-K** [comment]
Could you re-base and resolve conflicts? Thanks.

**Comment by Hilbrand** [comment]
Closing pr. Needs to be redone completely as it won't merge or rebase properly with 2.5.x branch. Maybe some other day.

**Pull request closed without merging**
