### PR TITLE
[deconz] support for IncreaseDecreaseType commands

### LINKED ISSUE #8861: [deconz] Feature request for supporting INCREASE and DECREASE commands on dimmable items
I'm making a feature request for supporting to send INCREASE and DECREASE commands to dimmable items.

I have been using Openab 2.4.0 until now, and i am moving my way over to version 3.x. I am glad to see that the Deconz binding now supports lights/outlets. Until now i have been using the Deconz binding for switches and sensors, and the HUE binding for controlling my outlets and lights (HUE binding connected to my Deconz hub). 

I can now control both my lights and outlets through Deconz binding. Everyting works as it should (ON,OFF, and specific dimming values like 10,50,100,etc), but i notice that the INCREASE and DECREASE commands do not work.
It would be nice to have this implemented in the Deconz binding if possible.
I'm currently using the HUE binding for my dimmable items, but it would be nice to get rid of the HUE binding, both because i will need one binding less, and the Deconz seems to have more detalis about the things (i.e if the device is online or offline).

I have tried to run the INCREASE and DECREASE on the following setup, with no success:
Openhab 2.4.0 (ligthts and outlets are not supported by Deconz)
Openhab 2.5.9
Openhab 3.0.0.M1
Openhab 3.0.0-snapshot (Build 1982)

### PR DESCRIPTION
**Pull request by J-N-K**
Closes #8861 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by cpmeister** [comment]
looks like you need to run spotless

**Comment by J-N-K** [comment]
done

**Comment by cpmeister** [comment]
Tado binding keeps failing in jenkins...

**Pull request merged**
