### PR TITLE
[boschindego] Add support for random mowing status code

### PR DESCRIPTION
**Pull request by sid3windr**
# Title

[boschindego] Add 'Mowing randomly' state code 524

# Description

When choosing "Mow without Dock" on the Indego, status switches to 524. This is indicated in the mobile app as "Mowing randomly".

### CODE REVIEW

**Review by jlaur — APPROVED** [review]
LGTM, thanks!

**Comment by jlaur** [comment]
@sid3windr - minor, but when decompiling the app I see this string:
```xml
<string name="mower_state_random_mowing">Random mowing</string>
```

Do you see "Mowing randomly" or "Random mowing" as well in the app?

**Comment by sid3windr** [comment]
I'll need to put it in random mode to check, will get back to you. I know it says something different in the app compared to the screen on the device - I may have mixed both up...

**Comment by sid3windr** [comment]
@jlaur Apologies for the very late reply, it's indeed "Random mowing" in the app.

**Comment by jlaur** [comment]
> Apologies for the very late reply, it's indeed "Random mowing" in the app.

No worries. However, I'm sorry, I've lost the context - what does it say on the display?

**Pull request merged**
