### PR TITLE
[innogysmarthome] Reconnect fixes (#8182)

### PR DESCRIPTION
**Pull request by Novanic**
This pull-request fixes a few reconnect problems regarding the WebSocket, see issue #8182 for more information

- When an error occurred while starting the websocket, no reconnect attempt was started which caused that the binding loses the connection (till the next restart of the server or binding), see issue #8182 for more information
- When an error occurs, it is now waited at least for 30 seconds for the next reconnect attempt to avoid too many requests (on re-occurring errors).
- Fix for a side-effect of "Fix possible resource leak #8080" (the websocket were closed unnormally by default which could trigger false and about one reconnect attempt per second).
- NullPointerException fixed
- An Exception could cancel the scheduler, so no reconnect attempt was executed.
- An Exception could get the binding in a mode which executed unnecessary reconnects at a fixed rate.
- First automated tests added for the binding.

### CODE REVIEW

**Review by Hilbrand — APPROVED** [review]
LGTM. I'll keep it open for a few more days so you can test if it's running ok this time 😉

**Comment by Novanic** [comment]
Ok. :-)

Here is a built version with the changes for testing: https://www.dropbox.com/s/5vv5qpnznelq10d/org.openhab.binding.innogysmarthome-2.5.9-SNAPSHOT.jar?dl=0

**Comment by Hilbrand** [comment]
Looks like you  need to fix the conflicts cause by your other pr: #8375

**Comment by Novanic** [comment]
I hate Git... Just forgot to add Signed-off-by to the commit message.............. I think I have to create a new branch and a new pull-request........

**Comment by Hilbrand** [comment]
Looks like everything is ok? No need to create a new pr. When having to fix previous commits you can always use `git rebase -i HEAD~<number of commits to fix>`. and than push force the changes back.

**Comment by Novanic** [comment]
Yes, I had luck that there was only the last commit message without sign-off. I had problems in the past with rebase and merge (rebases and merge commits weren't recognized correctly, all commits of other people were added to the pull-request). I think the problem is that I'm working with a fork and creating pull-requests from a branch of the fork... I should give up the fork for the next pull-requests.

**Comment by Novanic** [comment]
I think the pull-request could now get merged. At least 3 people tested the version for a few days and there were some reconnect attempts which were all successfully. The greatest risk is that I did something wrong on fixing the branch today... ;-)

**Pull request merged**
