### PR TITLE
[jsscripting] Refactor log formatting & Respect toString polyfills

### PR DESCRIPTION
**Pull request by florian-h05**
## Description

Fixes a problem, where toString polyfills of objects were ignored:

- Accept `toString` polyfills on objects and do not `JSON.stringify` them (some classes in the openhab-js library will introduce toString polyfills for string serialization).
- Refactor the log message formatting to ease understanding & readibility.

## Testing

Perform various log statements to check my changes:

```javascript
var item = {
  a: 'x',
  b: 'y'
}

console.log(item);

var arr = ['hello', 'world', 5, item];

console.log(arr);

console.log(undefined, 7, null);

console.log(function () {
  console.log("Hello world")
})

console.log(new RegExp(/ab+c/, 'i'))

console.log('Hello', 'Florian', 5, arr, item)
```

### CODE REVIEW

**Comment by florian-h05** [comment]
@digitaldan I need your review here, because it's a JS change.

**Comment by florian-h05** [comment]
@digitaldan I added try catch to both functions to handle potential errors. For Java objects the behaviour is:
- if toString does not return `[object Java]`, then use toString
- If toString does return `[object Java]`, use JSON.stringify. This works on Java objects (I tested it).

**Review by digitaldan — APPROVED** [review]
LGTM !

**Comment by florian-h05** [comment]
@jlaur Can you merge?

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
