### PR TITLE
[nibeuplink] Remove binding

### PR DESCRIPTION
**Pull request by alexf2015**
This binding is obsolete since the API is discontinued by NIBE. It is replaced by a new binding, see my other pull request #17451

### CODE REVIEW

**Comment by lsiepel** [comment]
Could you share some insights in what kind of strategy NIBE is using to make this obsolete? Is there a specific date, firmware, or hardware version that renders this binding obsolete? Does it affect all users, as in this binding will not work for _any_ user from now on?

**Review by lsiepel — APPROVED** [review]
LGTM.

**Comment by alexf2015** [comment]
> Does it affect all users, as in this binding will not work for _any_ user sinds september 2024 ?

The central API is retired and thus all users are affected and need to migrate to myuplink.

**Comment by jlaur** [comment]
@alexf2015 - can you also create a PR towards the openhab-docs repo for removing the logo?

**Pull request merged**
