### PR TITLE
[dscalarm] Bridge/things management refactored

### PR DESCRIPTION
**Pull request by lolodomo**
Relative to #7704 and #3990

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@RSStephens : please try these changes and confirm that the binding is still working well.

**Comment by RSStephens** [comment]
@lolodomo, I am running it now on my system.  Everything seems to be functioning as it should.  I would like to give it about 24 hours before merging.  I'll get back tomorrow.  Thanks.

**Comment by lolodomo** [comment]
@RSStephens : as a bonus, I made few additional changes to avoid logging the password configuration setting. Please take a look.
I see a configuration setting named "user code" on the panel thing type. It is not marked as "password". I hope this is not a kind of pin code ?

**Comment by RSStephens** [comment]
@lolodomo :  Thank you for your diligence on working on this.  Yes, the logging of the 'password' configuration setting needs to be removed.  As for the 'user code', it is a numeric user code required by the DSC Alarm to perform certain commands, such as arming and disarming of the system.  I noticed it being logged in _DSCAlarmBaseBridgeHandler.java_ at lines 700 and 787.  The error logs need to remain but the parameters 'userCode' and 'dscAlarmData[0]' can be removed from the respective lines.

Also, I have tested the binding and it appears that it is functioning properly.  I think the PR can be merged whenever you are ready.  Thank you.

**Comment by lolodomo** [comment]
Ok, I have masked the user code too.

If you are ok with these changes, please do a review and approve them. As you are the official maintener of this binding, this could certainly help in the global review/merge process of this PR.

**Pull request merged**
