### PR TITLE
[lgwebos] Create WEB socket client using OH core method

### PR DESCRIPTION
**Pull request by lolodomo**
Follow-up PR #14331

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This PR depends on openhab/openhab-core#3356.

**Comment by lolodomo** [comment]
Core PR is now merged, let's rebuild...

**Review by jlaur — APPROVED** [review]
Thanks for taking care of this!

**Comment by lolodomo** [comment]
Build is now ok. 
If required, someone has to trigger the other build ( CI / Build).

**Pull request merged**
