### PR TITLE
Move to JUPnP v3.0.1

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@wborn : I found that hue emulation binding is still compiling with a very old version of JUPnP. Is there a reason ?
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.io.hueemulation/pom.xml#L52

**Comment by lolodomo** [comment]
Must be merged with openhab/openhab-core#4165

**Comment by lolodomo** [comment]
@wborn : as itests/bndrun have `org.jupnp;version='[3.0.0,3.0.1)'`, I guess it is not necessary to update them ?

**Comment by wborn** [comment]
> I found that hue emulation binding is still compiling with a very old version of JUPnP (2.5.2). Is there a reason ?

I think it was just missed during the other updates.

> as itests/bndrun files have org.jupnp;version='[3.0.0,3.0.1)', I guess it is not necessary to update them ?

They need to be resolved as well because the range does not include 3.0.1 so it won't be able to resolve a bundle that matches the range.

**Comment by lolodomo** [comment]
> > I found that hue emulation binding is still compiling with a very old version of JUPnP (2.5.2). Is there a reason ?
> 
> I think it was just missed during the other updates.
> 
> > as itests/bndrun files have org.jupnp;version='[3.0.0,3.0.1)', I guess it is not necessary to update them ?
> 
> They need to be resolved as well because the range does not include 3.0.1 so it won't be able to resolve a bundle that matches the range.

Done

**Review by wborn — APPROVED** [review]
Thanks! :slightly_smiling_face:

**Comment by lolodomo** [comment]
Build succeeded. Can the PR be merged before midnight so that nightly builds will not fall tomorrow?
@wborn @jlaur

**Comment by jlaur** [comment]
@lolodomo - thanks for your extensive analysis and fix for this problem! And also thanks to @wborn for assistance. It was a joy to follow jupnp/jupnp#227. 🙂

**Pull request merged**
