### PR TITLE
[souliss] fix config Float values incompatible with oh 3.3

### PR DESCRIPTION
**Pull request by lucacalcaterra**
Signed-off-by: Luca Calcaterra <calcaterra.luca@gmail.com>

### CODE REVIEW

**Comment by jlaur** [comment]
Could this be related to (i.e. fixed by) openhab/openhab-core#3010 or is it a different problem?

**Comment by wborn** [comment]
There's also https://github.com/openhab/openhab-core/pull/3024 which may help.

**Comment by lucacalcaterra** [comment]
> Could this be related to (i.e. fixed by) [openhab/openhab-core#3010](https://github.com/openhab/openhab-core/pull/3010) or is it a different problem?

Yes , same issue. Could be ok this fix ?

**Comment by lucacalcaterra** [comment]
> > Could this be related to (i.e. fixed by) [openhab/openhab-core#3010](https://github.com/openhab/openhab-core/pull/3010) or is it a different problem?
> 
> Yes , same issue. Could be ok this fix ?

@wborn  @jlaur  Could be pass this fix ?

**Comment by jlaur** [comment]
> @wborn @jlaur Could be pass this fix ?

Not sure what you mean? But if core fix will fix this issue, there is nothing to fix in the binding. Would it be possible for you to verify with a snapshot version?

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab-core/pull/3024 should solve that without changes to the binding.

**Comment by jlaur** [comment]
@lucacalcaterra - openhab/openhab-core#3024 was recently merged, so this should be fixed now. Perhaps you could verify with latest snapshot - otherwise it will be included in next milestone.

**Comment by lucacalcaterra** [comment]
@jlaur i should be find time to work on it... too much  busy  now... :-(  thanks !

**Pull request closed without merging**
