### PR TITLE
[rfxcom] Read multiple bytes at a time over serial connection

### PR DESCRIPTION
**Pull request by Jamstah**
There's no reason not to read multiple bytes at a time (that I could find) so
for best practice, set the read limit to be the maximum size of an rfxcom
message. Tested fine on my system.

Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>

### CODE REVIEW

**Review by martinvw — APPROVED** [review]

**Comment by paulianttila** [comment]
Are you sure that message receiving will not slow down? As messages from rfxcom most probably will never be max length, would binding always wait data as long the receive timeout (100ms) occurs?

**Comment by Jamstah** [comment]
> Are you sure that message receiving will not slow down? As messages from rfxcom most probably will never be max length, would binding always wait data as long the receive timeout (100ms) occurs?

It will wait for the minimum of this value, or the value requested in the read call. The value requested in the read call will always be lower, so there will be no delays.

**Comment by lolodomo** [comment]
I also have in mind a blocking read until this number of bytes is read or timeout is reached.

**Comment by Jamstah** [comment]
> I also have in mind a blocking read until this number of bytes is read or timeout is reached.

All reads are done in a separate thread, so there is no blocking of the main process.

**Comment by lolodomo** [comment]
Of course but it could delay the handling of messages. Not so much considering the timeout setup. 
Your change probably combines an advantage and a disadvantage.

**Comment by Jamstah** [comment]
> Of course but it could delay the handling of messages. Not so much considering the timeout setup.
> Your change probably combines an advantage and a disadvantage.

It cannot delay message handling.

We continuously poll for the first byte to get the package length (ie, waiting for a message), then we read that length exactly. The read call will return when we have the full message to process. It will not wait for the full receive threshold.

**Comment by Jamstah** [comment]
Found time to explain more fully :)

Here's the read loop: https://github.com/openhab/openhab-addons/blob/fb01d2c5d0003c9a72fd9368127bb8bdddb2cbd6/bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java#L63

That loop reads 1 byte: `int bytesRead = connector.read(buf, 0, 1);`. If it gets a byte, it processes the associated message. If it doesn't get a byte, it tries again until it does (waiting for new messages).

Once we have a byte, that's the length of the next message, so we go on to processMessage: https://github.com/openhab/openhab-addons/blob/fb01d2c5d0003c9a72fd9368127bb8bdddb2cbd6/bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java#L84

That works out how much of the message we don't have, and tries to read it all at once: `int bytesRead = connector.read(buf, bufferIndex, bytesRemaining);`. Once it has the whole message, it processes it.

The receive threshold is documented here: https://docs.oracle.com/cd/E17802_01/products/products/javacomm/reference/api/javax/comm/CommPort.html#getInputStream()

A read call will until _either_ the threshold is reached, or the number of bytes requested is reached, or it times out. With this PR, in our main loop, it will block until there is 1 byte or it times out. In our processMessage, it will block until we get the data we wanted or it times out. Before this PR, it would always block until we got 1 byte because of the threshold, which just meant having to read _everything_ 1 byte at a time.

**Comment by lolodomo** [comment]
Ok, I agree with you now.

**Comment by paulianttila** [comment]
In fact, Oracle documentation is little bit scary as someone could understand spec differently.

image

where n = Read Buffer Size, which could be understood as a real buffer size (buffer.length) rather than len parameter given in read. In our case both threshold and buffer size would be 256 bytes and read would block as long timeout occurs.

luckily nrjavaserial implementation is done "properly"

https://github.com/openhab/nrjavaserial/blob/9a407b820606ff15504244c17adec2d57ba60897/src/main/java/gnu/io/RXTXPort.java#L1334-L1423

```
read(byte b[], int, int)
Documentation is at http://java.sun.com/products/jdk/1.2/docs/api/java/io/InputStream.html#read(byte[], int, int)
*/
	/**
	*  @param b[]
	*  @param off
	*  @param len
	*  @return int  number of bytes read
	*    IOException
*
*timeout threshold       Behavior
*------------------------------------------------------------------------
*0       0       blocks until 1 byte is available
*>0      0       blocks until timeout occurs, returns 0 on timeout
*>0      >0      blocks until timeout or reads threshold bytes,
                 returns 0 on timeout
*0       >0      blocks until either threshold # of bytes or len bytes,
                 whichever was lower.
	*/
		public synchronized int read( byte b[], int off, int len )
			throws IOException
		{
			if (debug_read)
				z.reportln( "RXTXPort:SerialInputStream:read(" + b.length + " " + off + " " + len + ") called" /*+ new String(b) */ );
			int result;
			/*
			 * Some sanity checks
			 */
			if ( fd == 0 )
			{
				if (debug_read)
					z.reportln( "RXTXPort:SerialInputStream:read() fd == 0");
				z.reportln("+++++++ IOException()\n");
				throw new IOException();
			}


			if( b==null )
			{
				z.reportln("+++++++ NullPointerException()\n");
				if (debug_read)
					z.reportln( "RXTXPort:SerialInputStream:read() b == 0");
				throw new NullPointerException();
			}


			if( (off < 0) || (len < 0) || (off+len > b.length))
			{
				z.reportln("+++++++ IndexOutOfBoundsException()\n");
				if (debug_read)
					z.reportln( "RXTXPort:SerialInputStream:read() off < 0 ..");
				throw new IndexOutOfBoundsException();
			}


			/*
			 * Return immediately if len==0
			 */
			if( len==0 )
			{
				if (debug_read)
					z.reportln( "RXTXPort:SerialInputStream:read() off < 0 ..");
				return 0;
			}
			/*
			 * See how many bytes we should read
			 */
			int Minimum = len;


			if( threshold==0 )
			{
			/*
			 * If threshold is disabled, read should return as soon
			 * as data are available (up to the amount of available
			 * bytes in order to avoid blocking)
			 * Read may return earlier depending of the receive time
			 * out.
			 */
				int a = nativeavailable();
				if( a == 0 )
					Minimum = 1;
				else
					Minimum = Math.min( Minimum, a );
			}
			else
			{
			/*
			 * Threshold is enabled. Read should return when
			 * 'threshold' bytes have been received (or when the
			 * receive timeout expired)
			 */
				Minimum = Math.min(Minimum, threshold);
			}
...
```

**Pull request merged**
