### PR TITLE
[homeconnect] Build state options with a unique item for unsupported programs

### LINKED ISSUE #10701: [homeconnect] Spin speed / washing temperature for unsupported washing program
When your washing program is unsupported by the API, the spin speed and the washing program temperature are displaying a raw value like that:
image
It would be better if the displayed value could be like for a supported washing program, that is:
image

Technically, the reason is that there is no state options built for an unsupported washing program leading to the display of the raw value. The solution would be to build the option with the current value and the good label.

### PR DESCRIPTION
**Pull request by lolodomo**
Apply to spin speed, temperature and drying taget channels

Fix #10701

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by bruestel — APPROVED** [review]

**Comment by lolodomo** [comment]
The bukd is failing but with no link with my changes. I found that
```
[INFO] openHAB Add-ons :: Integration Tests :: mielecloud Binding Tests FAILURE [02:51 min]
```

**Comment by bruestel** [comment]
> The bukd is failing but with no relation to my PR. I found that
> 
> ```
> [INFO] openHAB Add-ons :: Integration Tests :: mielecloud Binding Tests FAILURE [02:51 min]
> ```

can you try to rebase your branch with the main branch.

**Comment by bruestel** [comment]
> I think we can just ignore the failure in this case. What is important is that the build of the binding succeeded.

if you rebase the code a new build starts. Maybe the `mielecloud` bug was fixed in the meantime.

**Comment by lolodomo** [comment]
Let see what will happen after merging my branch with the last changes...

**Pull request merged**
