### PR TITLE
[miio] Improve Airpurifiers

### PR DESCRIPTION
**Pull request by marcelrv**
as per https://community.openhab.org/t/binding-request-philips-air-purifier/66304/50

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by ppolewicz** [comment]
@marcelrv can you please tell me how to install this on my environment somehow, so that I can test to make sure it works as intended?

**Comment by marcelrv** [comment]
The short: Take the JSON file for your device and drop it in the conf/misc/miio folder ( the miio part you need to create yourself) , restart the binding.

The more elaborate version in the binding readme...

**Comment by J-N-K** [comment]
When was the original version merged?

**Comment by marcelrv** [comment]
> When was the original version merged?

the miot versions <6months ago, the other one 1or2 years ago i think.. it has been there for some time?

**Comment by J-N-K** [comment]
I guess it should be noted in the release notes then, looks like a breaking change. Can you prepare a PR in openhab-distro for that?

**Comment by marcelrv** [comment]
You mean cuz the channels changed?
I can make a pe for distro, but what do I put in that pr for the distro?

**Comment by marcelrv** [comment]
@J-N-K I did not directly see a place where I should make a remark for release notes in the distro itself.

I did for now make a placeholder page for the release notes 3.1 and added some comments around changing channel definitions. As in this 3.1 release there are over 100 channels changed (not just this PR), I did not name them individually, instead refer to the readme.

https://github.com/openhab/openhab-distro/wiki/openHAB-3.1-Release-Notes

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab-distro/blob/a46f10257474c2fa7f790331e124036bee3bf1c0/distributions/openhab/src/main/resources/bin/update.lst#L39

Something like this for 3.1.0 was what I had in mind

**Comment by marcelrv** [comment]
ok, got it... Did not know the existence of that file.

**Comment by ppolewicz** [comment]
I am on openhabian, openhab2 2.5.11-1, I have downloaded all 3 json files to /etc/openhab2/conf/misc/miio (though I had to create `conf/misc/miio` myself), restarted the daemon, but the UI looks the same as before.
Tried to follow https://github.com/openhab/openhab-addons/blob/62d8c455706034e55fc089782a867ff80aa85f07/bundles/org.openhab.binding.miio/README.md#advanced-adding-local-database-files-to-support-new-devices - the path is NOT printed in the logs, so I've put the files in `/opt/openhab/conf/misc/miio/`, restated, but the UI looks the same as before.

I need help :|

**Review by J-N-K — APPROVED** [review]

**Comment by ppolewicz** [comment]
Turns out the correct path was `/etc/openhab2/misc/miio` and the way to find it out is to log into the openhab console, `log:set debug org.openhab.binding.miio`, `restart org.openhab.binding.miio`, `log:display org.openhab.binding.miio` and scroll up to find the path.

This is how it looks now, and I'm afraid it's _worse_ than it [was before](https://community.openhab.org/t/binding-request-philips-air-purifier/66304/46?u=ppolewicz):
image

Perhaps I should be using openhab3 for it to work well?

**Comment by marcelrv** [comment]
yes, indeed only working with OH3, as that version supports the dynamic options in miio.

**Pull request merged**
