### PR TITLE
[miele] Rename channel `powerConsumption` to `energyConsumption` and set display unit to litres for `waterConsumption`

### PR DESCRIPTION
**Pull request by jlaur**
This removes channel `powerConsumption` and adds channel `energyConsumption` to rectify an old mistake.

This is a bit overdue and should probably have been done in #13930, in hindsight. This is a breaking change requiring users to relink items to the new channels. I doubt there are many users though. I will create a note for that in openhab-distro.

I tried first to do a backwards compatible deprecation (see first commit), but I think this drags too much technical debt along than can be justified, so would prefer to just take the bull by the horns now.

Additionally sets state description pattern unit to **litre** for water consumption as default unit m³ makes no sense for dishwashers and washing machines.

The upgrade will only happen after two minutes. I'm not sure if this is a known and accepted issue, or should be reported as a bug in core:
```
2023-10-17 22:24:22.980 [WARN ] [core.thing.internal.ThingManagerImpl] - Channel types or config descriptions for thing 'miele:dishwasher:Miele_XGW3000:000000000000_0' are missing in the respective registry for more than 120s. In case it does not happen immediately after an upgrade, it should be fixed in the binding.
2023-10-17 22:24:22.981 [INFO ] [core.thing.internal.ThingManagerImpl] - Updating 'miele:dishwasher:Miele_XGW3000:000000000000_0' from version 0 to 1
```

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
Please also mention the change about `waterConsumption` channel in your description and commit message.

**Comment by lolodomo** [comment]
> The upgrade will only happen after two minutes. I'm not sure if this is a known and accepted issue, or should be reported as a bug in core:
> 
> ```
> 2023-10-17 22:24:22.980 [WARN ] [core.thing.internal.ThingManagerImpl] - Channel types or config descriptions for thing 'miele:dishwasher:Miele_XGW3000:000000000000_0' are missing in the respective registry for more than 120s. In case it does not happen immediately after an upgrade, it should be fixed in the binding.
> 2023-10-17 22:24:22.981 [INFO ] [core.thing.internal.ThingManagerImpl] - Updating 'miele:dishwasher:Miele_XGW3000:00000
> ```

Don't know if this is normal.
This binding was not identified in #14954

**Comment by jlaur** [comment]
> > Maybe @J-N-K could tell us if this delay is expected when upgrading thing type.
> 
> Initially a channel is missing because the update hasn't removed it yet. But there might also be side-effects of doing it in opposite order, i.e. updating thing type first. In any case it would be nice with some input here. The only real impact is the two minutes additional delay and a logged warning.

I guess it's expected when carefully reading the warning: "In case it does not happen immediately after an upgrade, it should be fixed in the binding."

**Comment by jlaur** [comment]
> Please also mention the change about `waterConsumption` channel in your description and commit message.

It's already in the PR description and I have now also added it to the PR title. If you want me to change the commit message, I will need to rebase in the evening. In that case maybe it would be even better to do as a separate PR, but it would require two thing type updates, so initially slipped it in here for simplicity.

**Comment by lolodomo** [comment]
> I guess it's expected when carefully reading the warning: "In case it does not happen immediately after an upgrade, it should be fixed in the binding."

Yes, I vaguely remember now that @J-N-K explained this is normal during thing upgrade.

**Comment by lolodomo** [comment]
> It's already in the PR description and I have now also added it to the PR title which will be used for the squash commit. If you want me to change the commit message, I will need to rebase in the evening. In that case maybe it would be even better to do as a separate PR, but it would require two thing type updates, so initially slipped it in here for simplicity.

I am going to adjust the commit message when merging...

**Comment by jlaur** [comment]
> I am going to adjust the commit message when merging...

👍 You can probably just delete the two commit messages and keep only the PR title as message and the sign-off.

**Comment by lolodomo** [comment]
I was thinking about the channel type for `waterConsumption` that you changed. But in fact, it is not very important to mention it because it will be handled by the upgrade process for users using UI and this is change is transparent for users using file.

**Comment by J-N-K** [comment]
Thing upgrades will happen when the thing can be initialized, i.e. all pre-requisites are fulfilled. One of these pre-requisites is that all thing- and channel-types are available in the respective registries.

If you change the channel-type (and remove the old type, like you did here) then the old channel-type is missing on next startup. The result is the warning. After the 120s delay, we try to initialize the thing in any case, the thing will be updated and from then on the channel has the new channel-type and the warning will not appear again.

IMO enforcing the channel-type naming convention on already existing channel-types is unnecessary/wrong. It leads to more confusion than necessary and thing-updates that are not really needed.

**Comment by jlaur** [comment]
> IMO enforcing the channel-type naming convention on already existing channel-types is unnecessary/wrong. It leads to more confusion than necessary and thing-updates that are not really needed.

In this specific case changing channel type names has no end user impact though:
- `powerConsumption`: Channel was deleted, so new channel might as well use new channel type with correct name also.
- `waterConsumption`: Channel type was updated with new state pattern, so since this update way required anyway, I think the renaming shouldn't cause any additional problems, and it was just done for consistency.

**Pull request merged**
