### PR TITLE
[miio] Initial i18n properties file for Xiaomi miio binding

### PR DESCRIPTION
**Pull request by marcelrv**
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by lolodomo** [comment]
@marcelrv : ideally you should use @text rather than a hardcoded English text when calling updateStatus in your thing handler.

**Comment by marcelrv** [comment]
@lolodomo I see this indeed as a very first step in making the binding i18n compatible.
e.g. the 1250+ dynamically created channels defined infor the things also need a solution. (I did not yet see easy solution for those...)

**Comment by lolodomo** [comment]
It looks like all channel types are not there in the properties file. An example: MijiaVacuumV2_fan-level

**Comment by marcelrv** [comment]
> It looks like all channel types are not there in the properties file. An example: MijiaVacuumV2_fan-level

Yes, because they are about to be removed https://github.com/openhab/openhab-addons/pull/11568

**Review by lolodomo — APPROVED** [review]
LGTM, hoping there are no forgotten channel types.

**Pull request merged**
