### PR TITLE
[miio] add DreameBot L10s Ultra

### LINKED ISSUE #15217: [Miio] Dreame L10S Ultra - Add support
As suggested by @marcelrv this issue to request to add official support to Dreame L10S Ultra.

All the channed found via unsupported channel method seems to work properly although some mapping need to be adjusted (e.g. many channel can be mapped as switch but having custom values for ON and OFF)

Probably my fault but was not able to configura a Map channel....

Please find attacched :

- test-dreame.vacuum.r2228o-20230619-232217.txt
- info_DreameL10sUltra.json renamed .txt

[test-dreame.vacuum.r2228o-20230619-232217.txt](https://github.com/openhab/openhab-addons/files/11996024/test-dreame.vacuum.r2228o-20230619-232217.txt)
[info_DreameL10sUltra.json.txt](https://github.com/openhab/openhab-addons/files/11996033/info_DreameL10sUltra.json.txt)

### PR DESCRIPTION
**Pull request by marcelrv**
Adding support for the following models:
* DreameBot L10s Ultra (modelId: dreame.vacuum.r2228o)

close #15217

### CODE REVIEW

**Comment by lolodomo** [comment]
I just merged another of your PRs and it introduced a conflict in this one.

**Comment by marcelrv** [comment]
@lolodomo I fixed the merge conflict now. So it should be good to go again.
I also fixed the merge conflict that came to https://github.com/openhab/openhab-addons/pull/14210

**Review by fwolter — APPROVED** [review]
Do you write these JSON files by hand or are they generated?

**Comment by marcelrv** [comment]
@fwolter in the early days all created by hand.
Nowadays Xiaomi mosly uses miot based devices and they are automatically created by the user if there is an unsupported device, or by me using the MiotJsonFileCreator and than tweaked a little by hand (e.g. replacing some of the left over Chinese characters, adding categories & tags etc)

the tool is here:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/MiotJsonFileCreator.java

**Pull request merged**
