### PR TITLE
[Freebox] Update binding in regard of OH3

### PR DESCRIPTION
**Pull request by clinique**
Integrate UoM
Major evolution of the binding, breaking changes
Onboards Delta capabilities
Enhanced Player capabilities.
Dynamic creation of channels for the server based on actual capabilities

Signed-off-by: clinique <gael@lhopital.org>

### CODE REVIEW

**Comment by clinique** [comment]
Supersedes PR #7095

**Comment by lolodomo** [comment]
IMHO the title should be updated. This is largely more than an adaptation to OH3. 
This is even more like a new binding :)

**Comment by lolodomo** [comment]
And why not proposing a new binding? When we are sure of its stability and no feature is lost compared to the old binding, we can remove the old binding from the distribution few months later.

**Comment by clinique** [comment]
> 
> 
> And why not proposing a new binding? When we are sure of its stability and no feature is lost compared to the old binding, we can remove the old binding from the distribution few months later.

That an idea, how could we call it ?

**Comment by lolodomo** [comment]
Freebox NG
Freebox Delta
Freebox 2
I don't know what could be the perfect name, maybe a name showing the compatibility with several boxes.

**Comment by clinique** [comment]
> 
> 
> Freebox NG
> Freebox Delta
> Freebox 2
> I don't know what could be the perfect name, maybe a name showing the compatibility with several boxes.

Maybe Freebox3 to be consistent with OH versioning ?

**Comment by clinique** [comment]
@lolodomo : I've been eavily working on it past days. I'll follow your advice and will push a separate binding called freeboxos as I'm going to extend capabilities toward repeaters, players... It's tough because there is no official documentation but I found some entry points..

**Pull request closed without merging**
