### PR TITLE
[http] Fix parsing of Color RGB values

### PR DESCRIPTION
**Pull request by Ryz3D**
When parsing RGB values from a http channel state request (in the form "0,1,2") there is an error like this one:

> Failed processing result for URL http://esp32dev2/get/color: For input string: "114,69,40"

Even though the input string "114,69,40" is supposed to be valid.
Which stems from RefreshingUrlCache.java:processResult after calling ColorItemConverter:toState. In the toState function the input is matched against the regex TRIPLE_MATCHER ("(\d+),(\d+),(\d+)") and then the r, g and b channels are set by matcher.group. The problem is that matcher.group returns which match was found, thus matcher.group(0) refers to the first three-digit pattern matching TRIPLE_MATCHER. Then matcher.group(1) has nothing to return as there is only one three-digit group.
Instead I have moved to only using matcher.group(0) and splitting it by the commas. Afterwards the state is parsed as expected.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks for the investigation and the fix. But can't the `TRIPLE_MATCHER` then be removed completely? It looks to me as if you could directly parse, split and process the `string` variable. Wdyt?

**Comment by J-N-K** [comment]
The matcher ensures the format is valid. Wouldn‘t it be possible to just use group 1-3 instead of 0-2 (which is obviously wrong).

**Comment by Ryz3D** [comment]
Hi,

@J-N-K is right, matcher.group just returns the entire match with parameter 0, so groups 1-3 are actually the correct regex groups. I have reverted the code and changed to matcher.group(1) through matcher.group(3), which appears to work just as well. Thank you!

**Review by kaikreuzer — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
