### PR TITLE
[modbus] Update apache commons pool2 to latest version

### PR DESCRIPTION
**Pull request by ssalonen**
Resolves many bugs present in the old version. Despite the large bump in version, seems to run just fine based on quick testing.

Marking as WIP -- more extended testing ongoing in community forum.

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

### CODE REVIEW

**Comment by ssalonen** [comment]
Appreciate review / check on the dependency management -- I might not be familiar with all the places that need touching when a dependency is updated.

**Comment by ssalonen** [comment]
Travis:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project org.openhab.io.transport.modbus: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/openhab/openhab-addons/bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusPoolConfig.java:[75,2726] Name clash: The method setEvictionPolicy(EvictionPolicy<ModbusSlaveConnection>) of type ModbusPoolConfig has the same erasure as setEvictionPolicy(EvictionPolicy) of type BaseObjectPoolConfig but does not override it
[ERROR] /home/travis/build/openhab/openhab-addons/bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusConnectionPool.java:[50,1780] The method setConfig(GenericKeyedObjectPoolConfig) is ambiguous for the type ModbusConnectionPool
[ERROR] /home/travis/build/openhab/openhab-addons/bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusConnectionPool.java:[80,3329] Cannot reduce the visibility of the inherited method from BaseGenericObjectPool<ModbusSlaveConnection>
```

So some small adjustments are needed... It's also probably good idea to resolve all (transitive) dependencies in itest bnd.

**Comment by cweitkamp** [comment]
> Appreciate review / check on the dependency management

At first glance you touched all mandatory places.

May I ask you to add `itests/org.openhab.binding.modbus.tests/` to the list of [CODEOWNERS](https://github.com/openhab/openhab-addons/blob/2.5.x/CODEOWNERS)?

**Comment by ssalonen** [comment]
Hacky workarounds that were necessary for https://issues.apache.org/jira/browse/POOL-338 have been removed. `itests` dependencies resolved successfully.

Now just waiting for green light from Travis and Jenkins

**Comment by Hilbrand** [comment]
No green light yet. You need to run `mvn spotless:apply`.

**Comment by Hilbrand** [comment]
If testing is finished can you remove the work-in-progress to trigger us to merge this pr.

**Review by Hilbrand — APPROVED** [review]
LGTM

**Comment by ssalonen** [comment]
For the record, testing with users happening here : https://community.openhab.org/t/modbus-stops-without-any-errors/104050?page=3. The whole thread is about some recent regression which makes the polling of modbus data hang... Due to hanging when borrowing connection from connection pool (implemented with Apache pool2)

Reports tell that the main issue discussed there remains even with newer Apache pool but at least it did not make things worse. To be exact, tests were done with vanilla 2.8.0 binding but with updated Apache pool. So not all the changes in this PR have been tested yet with users.

I have also created patched version on top of this branch (
https://github.com/ssalonen/openhab2-addons/tree/modbus-fix-hang ), currently being tested by the users. 

Let's hold off merging this so we get the big issue solved first, there's no immediate value to roll out only the Apache pool update.

**Comment by ssalonen** [comment]
This is ready to be merged -- positive tests in community forums. As discussed above, will also issue another PR based on `modbus-fix-hang` branch.

**Pull request merged**
