### PR TITLE
[solarwatt] Add smart heater device support

### PR DESCRIPTION
**Pull request by thumm**
The [EGO Smart Heater](https://www.ego-seibert.de/produkte/pseudo-sub1/smart-heater) screw-in heater stores excess photovoltaic energy fully automatically as hot water. These changes add support for this device to the solarwatt binding.

The test version of the binding can be found [here](https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.solarwatt/4.0.0-SNAPSHOT/).

### CODE REVIEW

**Comment by jlaur** [comment]
@sven-carstens - it seems you are not in the contributors group, so you were not automatically added as reviewer. Would you like to review this PR?

**Review by jlaur — CHANGES_REQUESTED** [review]
Thanks for the contribution! After fixing the minor description issue, can you also regenerate the I18N properties file? See https://www.openhab.org/docs/developer/utils/i18n.html#generating-i18n-properties-file

**Comment by sven-carstens** [comment]
Looks fine by me. And great to know of at least one other user besides me.

**Review by jlaur — APPROVED** [review]
LGTM

**Pull request merged**
