### PR TITLE
[tesla] Add channel for raw JSON response from the upstream API

### PR DESCRIPTION
**Pull request by hakan42**
Inspired by https://github.com/openhab/openhab-addons/pull/15580 and discussions I had earlier about creating channels for little-used properties, this enhancement creates an advanced channel to expose the RAW JSON response of the upstream API for the "vehicleData" calls.

That way, an user will be able to access any data points in the API via the [JSONPATH ](https://www.openhab.org/addons/transformations/jsonpath/) transformation.

### CODE REVIEW

**Comment by hakan42** [comment]
@lsiepel , may I again draw your attention to another pull request ?

**Comment by lsiepel** [comment]
> @lsiepel , may I again draw your attention to another pull request ?

While it may fit in some usecases, my personal opinion remains the same, i don't like raw channels. I prefer to model the API to the openHAB domain to keep it inline with the openHAB architecture. But the other PR also got merged, so it seems fine from maintainers perspective.

**Comment by lolodomo** [comment]
No the other PR was not yet merged. 
And U tend to agree with you @lsiepel 
This should be discussed with IH leaders before creating new PR if this kind.

**Comment by lolodomo** [comment]
@openhab/add-ons-maintainers : WDYT about such proposal ?

**Comment by kaikreuzer** [comment]
I also agree with @lsiepel here. Unless there is really a strong reason for it, we should avoid raw channels.
@hakan42 What information do you see in the JSON that is not reflected in the existing channels? Imho, the Tesla API does not change that often and we should rather make sure to provide "semantic" channels for any new additions.

**Comment by hakan42** [comment]
I would argue that the current owners API is reverse engineered but not really something defined by Tesla. And therefore prone to change. The other part is, it feels like ... missing a proper english word for "Fleißarbeit" here , maybe grind? :) 

I might be inclined to define "semantic" channels for all of the old json results, but for this the internals of the mapping of json trees to channels would need a bit of rework.

In the end, it would depend on how long the owners' API does live on, perhaps wait until February or so to see where Tesla goes with the fleet API and whether they let the current one alive? WDYT @kaikreuzer  ?

**Comment by kaikreuzer** [comment]
If tesla removes or heavily changes the owner's API, the binding anyhow would require a rework - and having the raw channel wouldn't help here, if the API does not exist anymore. But in the past years, not much has happened and we only added a few new channels over time.
I don't see anything missing in the current set of channels and hence I do not see the need for any change right now.

**Comment by hakan42** [comment]
O.k., let me withdraw this pull request then, and create fresh ones for specific channels when I identify a proper need for them.

Thank you all for your insights and comments :)

**Comment by lolodomo** [comment]
I close it

**Pull request closed without merging**
