### PR TITLE
[harmonyhub] Updated README to get buttonPress values with the new REST API implementation

### PR DESCRIPTION
**Pull request by 2wyck3d**
openHAB 3.X put the REST API behind authorization and the old URL no longer works in the browser due to an authentication error. These new instructions allow for a trivial way to find the commands.

### CODE REVIEW

**Review by digitaldan — APPROVED** [review]
lgtm, thanks!

**Comment by kaikreuzer** [comment]
@2wyck3d Could you please add a sign-off (see [here](https://www.openhab.org/docs/developer/contributing.html#sign-your-work))? It's good enough if you add it as a comment to the PR.

**Comment by 2wyck3d** [comment]
Signed-off-by: Jerry Gallo <2wyck3d@gmail.com>

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
