### PR TITLE
[somfytahoma] Faster feedback for commands initiated by the binding

### PR DESCRIPTION
**Pull request by lolodomo**
Also fix references to OH2

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@octa22 : this is my proposal to have a faster feedback for the commands started by the binding. The refresh of events is run every 2 seconds while commands are still running and then return to the interval defined for the thing (default is 30 seconds).
Note that there is no risk to have concurrent events updates (for the same device) as the next refresh is scheduled only when the current is finished.

**Review by octa22 — APPROVED** [review]
Nice. LGTM

**Comment by lolodomo** [comment]
@openhab/add-ons-maintainers : please review & merge.

**Review by fwolter — APPROVED** [review]
LGTM

**Pull request merged**
