### PR TITLE
[unifiedremote] Initial contribution

### PR DESCRIPTION
**Pull request by GiviMAD**
## Unified Remote Binding.
This binding allow send some command to the unified remote server through its web client interface.
It create some channels to control the mouse, some navigation keys, some media keys, and not much more.

_Good day.  This is my first contribution to this amazing product. Some days ago I started search for a way to control my computer with openHAB and I decided to try to write this binding that seems to finally be working._
_Please let me know if there are any suggestions to improve the binding as I'm still getting in touch with this technology. I will also open a thread in the Add-ons forum pointing to this pr, in case someone wants to try it or have an idea for a better implementation. Thanks in advance for your time._

### CODE REVIEW

**Comment by Hilbrand** [comment]
Thank you for adding this binding. I have a first question. Does it only support sending commands to the remote or can you also read the status. For example if it's  playing, what the volume is, etc? That does have an impact on the channel design in the binding. That's why I ask.

**Comment by GiviMAD** [comment]
Hi Hilbrand. Thanks for your reply. No, it doesn't support read the status. The channels I mapped are unidirectional to the server as it doesn't provide any state information in the responses.

**Comment by Hilbrand** [comment]
If you only can send commands you should model the channel with command options. You could simply reduce this to 1 channel with all the options (maybe with the exception of the mouse position as it accepts a dynamic value). See this documentation  on how such a channel would look like in xml: https://www.openhab.org/docs/developer/bindings/thing-xml.html#command-description

**Comment by kaikreuzer** [comment]
Not sure why Github has closed this PR (it wasn't me in person...), but please see https://github.com/openhab/openhab-addons/issues/8512 on how to proceed now.

FTR, the automatic code migration has created [this code](https://ci.openhab.org/view/Pull%20Request%20Builds/job/openHAB-Addons-Migration/6/artifact/bundles/org.openhab.binding.unifiedremote/*zip*/org.openhab.binding.unifiedremote.zip), which should give you an easy start for a new PR against `main`. Thanks!

**Comment by GiviMAD** [comment]
Ok, I will do. I also will reduce the number of channels of the binding as suggested by Hilbrand. Thanks for your help guys.

**Pull request closed without merging**
