### PR TITLE
[keba] Add support for additional x-series wallboxes

### PR DESCRIPTION
**Pull request by MikeTheTux**
Fixed https://github.com/openhab/openhab-addons/issues/16472.

The following wallboxes from the x-series are now supported as well:
- x-series 4G, w/o LM: identified via `S` in the product designation string
- x-series WLAN, w/o LM: identfied via `U` in the product designation string

Fixed type mapping for identifier 'A':
- was x-series but actually is c-series

Test Build: [org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip](https://www.dropbox.com/scl/fi/4f10fw3d2dcgmzxfzbm7h/org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip?rlkey=rcxs7gm5uypy6oz6aao1ybas8&dl=0)

### CODE REVIEW

**Comment by MikeTheTux** [comment]
I added `S` and `U` to the list of supported device types, but did not delete `A`, `C`, `D` and `G` from the list, although they are not listed in [kecontactp30_bden_web.pdf](https://www.keba.com/download/x/ea958eb797/kecontactp30_bden_web.pdf).
Does anyone know, what the identifier of the BMW wallbox is?

309297702-70e79885-6de8-4b09-bbbb-5d3068835931

**Comment by MikeTheTux** [comment]
@Andre1Becker found it in a [different manual](https://www.keba.com/file/downloads/e-mobility/KeContact_KCP20_30_ih_de.pdf) page 8 :

309446937-cd521cfa-42a2-43f2-aa52-e9d147ceda38

`A`, `C`, `D` is now clarified as well.

`A` is a c-series, but implemented as x-series right now:

```
        E('0'),
        B('1'),
        C('2'),
        A('3'),
        X('A', 'B', 'C', 'D', 'E', 'G', 'H', 'S', 'U');
```

`G` is still unclear. BMW wallbox?
What about the Company Car wallbox or PV-Edition?

image

**Comment by MikeTheTux** [comment]
I filed a support request at Keba, also asking for further info about the upcoming P40/P40pro.

**Comment by Andre1Becker** [comment]
> `G` is still unclear. BMW wallbox? What about the Company Car wallbox or PV-Edition?

I've got this '[Dienstwagen-Edition](https://www.mobilityhouse.com/de_de/keba-dienstwagen-edition-126-389-wallbox.html)' (Company Car Edition) so that should be covered. At least that specific version :-)

**Comment by Andre1Becker** [comment]
> I filed a support request at Keba, also asking for further info about the upcoming P40/P40pro.

I just noticed the P40 too.
That seems to be the best Idea to get all the I fos needed.

Have a sunny weekend!

**Comment by lolodomo** [comment]
Is it ready for a merge ?

**Comment by MikeTheTux** [comment]
> Is it ready for a merge ?

Please merge.

Until now, I did not receive any feedback on my support request at Keba. If there is an outcome that requires some changes in the binding, we can raise a new PR.

In the meanwhile I was able to find out the P40 product naming schema:
* [p40pro_technicaldata_cable_dben.pdf](https://www.keba.com/download/x/787dcc6bc9/p40pro_technicaldata_cable_dben.pdf)
* image

Still it is not clear, if the same UDP protocol is supported by the P40/P40pro / or not.

**Review by lolodomo — APPROVED** [review]

**Pull request merged**
