### PR TITLE
[lifx] Fix QuantityType command

### PR DESCRIPTION
**Pull request by andrewfg**
Split from #17919

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
Don't think we need to backport this one. Do you agree @andrewfg ?

**Comment by andrewfg** [comment]
@lolodomo indeed no need to backport; it just fixes a compiler warning.

**Comment by jlaur** [comment]
@lolodomo - consider removing the "enhancement" label, since there is probably no reason to mention this tiny technical refactoring in the release notes? Users will wonder what is "fixed".

**Comment by lolodomo** [comment]
I agree. Done.

**Pull request merged**
