### PR TITLE
[chatgpt] Set proper default values for channel configuration

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Withhout this patch, creating a new channel in the UI without changing the default values for model, temperature, or maxtokens, the values are not stored to the json db.

Added a trace logging for the requests sent to chatgpt. Without this ends up with an invalid query starting with 
``` {"temperature":0.0,"model":"","max_tokens":0,"```...

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thanks!
I thought that the config is always automatically set from the XML entries - seems I was wrong for channel configs...

**Review by kaikreuzer — APPROVED** [review]
Thanks!
I thought that the config is always automatically set from the XML entries - seems I was wrong for channel configs...

**Comment by holgerfriedrich** [comment]
@kaikreuzer @jlaur IMHO this should be cherry-picked to 4.0.x branch.

**Comment by holgerfriedrich** [comment]
@kaikreuzer @jlaur It seems we have missed to cherry-pick this for 4.0.3....

**Comment by kaikreuzer** [comment]
@holgerfriedrich Indeed. I have cherry-picked it now, so that it will be at least in 4.0.4.

**Pull request merged**
