### PR TITLE
[linky] Removed from the distribution until it is fixed

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by fwolter** [comment]
Can you add a reference what is broken?

**Comment by lolodomo** [comment]
The authentication code is broken. 
Look at issue #10360 for more details,

**Review by clinique — APPROVED** [review]

**Comment by fwolter** [comment]
Are you sure @clinique and you won't be able to fix it until December, when OH 3.2 is released?

**Comment by lolodomo** [comment]
I seriously doubt it will be fixed soon as noone is working on it and/or has the beginning of a solution.
In case a solution is found, we could then remove the comments I added in this PR.

**Comment by fwolter** [comment]
Ok, I think we should take down the binding documentation, too, then.

**Comment by fwolter** [comment]
Can you run spotless?

**Review by fwolter — APPROVED** [review]

**Comment by kaikreuzer** [comment]
This PR broke our build, see https://ci.openhab.org/job/sandbox-openhab3-release/363/execution/node/354/log/.
I guess the feature.xml needs to be removed/renamed as well, so that it isn't picked up by the feature aggregation.

**Pull request merged**
