### PR TITLE
[sleepiq] Add new channels

### PR DESCRIPTION
**Pull request by mhilbush**
Add 4 new channels for detailed sleep time breakdown.

Signed-off-by: Mark Hilbush [mark@hilbush.com](mailto:mark@hilbush.com)

### CODE REVIEW

**Review by jlaur — CHANGES_REQUESTED** [review]
Thank you, LGTM! Only thing missing is regeneration of the I18N properties file. 🙂

**Comment by mhilbush** [comment]
Right. 🙄

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by jlaur** [comment]
@J-N-K - FYI, new UoM channels added here (to be included in #14389).

**Comment by J-N-K** [comment]
Thing upgrade instructions are missing

**Comment by mhilbush** [comment]
@J-N-K @jlaur I don't mind being a guinea pig to use the new thing update feature, but as there's no documentation, I could use some advice.

So the obvious part is that I need to create the update directory in OH-INF, then create an instructions xml file.

Is there a naming convention for the instructions file? I see the test uses `singleInstructions.xml` and `multiInstructions.xml`. Are those standard names, or can I pick whatever I want? Or, is there a naming convention you would prefer?

Then I guess I create some `add-channel` tags for the new channels. 
- But what is the purpose of the `<label>` tag? Is that duplicating the `<label>` tag in the `thing-types.xml`? 
- Why do I need to provide the `<type>` tag? The type of that channel id is already in the thing types. Or, if there are multiple thing typoes defines, you need that to know which one(s) to which the change should be applied?

Note I can't easily test it because my things are defined in a `.things` file, and I don't currently have a separate test environment.

**Comment by J-N-K** [comment]
- you can pick any name you want
- `label` (`description`) sets the label (description). If you don't use it, the label (description) used should be the one from the channel-type
- the update instructions don't know what's defined in the thing-type, just put the correct channel-type UID (i.e. including binding-id) in there
- don't forget to add `thingTypeVersion` property to the thing-type (otherwise also newly created things will be updated)

**Comment by mhilbush** [comment]
Thanks.

I'll submit something shortly. If you would please look it over that would be great.

**Comment by lolodomo** [comment]
> * don't forget to add `thingTypeVersion` property to the thing-type (otherwise also newly created things will be updated)

Do you mean with a higher value (l2 for example) than the target value (1) in the upgrade file?

**Comment by mhilbush** [comment]
> Do you mean with a higher value (l2 for example) than the target value (1) in the upgrade file?

Yeah, I just was wondering whether it should be that instead of what I wrote.

**Comment by mhilbush** [comment]
BTW, I don't see the `thingTypeVersion` in the thing description xsd. Is there a new version of the xsd that includes that new property?

**Comment by mhilbush** [comment]
This is what I have for the instructions. So I just need to sort out how to handle the `thingTypeVersion` property.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<update:update-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:update="https://openhab.org/schemas/update-description/v1.0.0"
    xsi:schemaLocation="https://openhab.org/schemas/update-description/v1.0.0 https://openhab.org/schemas/update-description-1.0.0.xsd">

    <thing-type uid="sleepiq:dualBed">

        <instruction-set targetVersion="1">
            <add-channel id="todaySleepInBedSeconds">
                <type>sleepiq:todaySleepInBedSecondsType</type>
            </add-channel>
            <add-channel id="todaySleepOutBedSeconds">
                <type>sleepiq:todaySleepOutBedSecondsType</type>
            </add-channel>
            <add-channel id="todaySleepRestfulSeconds">
                <type>sleepiq:todaySleepRestfulSecondsType</type>
            </add-channel>
            <add-channel id="todaySleepRestlessSeconds">
                <type>sleepiq:todaySleepRestlessSecondsType</type>
            </add-channel>
        </instruction-set>

    </thing-type>

</update:update-descriptions>
```

**Comment by mhilbush** [comment]
Duh! I see now. I need a property **tag**...
```
<property name="thingTypeVersion">1</property>
```

**Pull request merged**
