### PR TITLE
Link to Java 21 documentation

### PR DESCRIPTION
**Pull request by jlaur**
This prevents issues because older documentation may not apply to Java 21.

Previous update: #15406

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks LGTM

**Comment by wborn** [comment]
Thanks! We a have a few more repos with these JavaDoc links (see #15406 links). Do you have plans to create PRs for those as well @jlaur?

**Comment by jlaur** [comment]
> We a have a few more repos with these JavaDoc links (see #15406 links). Do you have plans to create PRs for those as well

Thanks for catching that! Hopefully all should be covered now.

**Comment by wborn** [comment]
Nice! 👍

**Pull request merged**
