### PR TITLE
[solarmax] Improve binding with respect to channel Current Power Generated

### PR DESCRIPTION
**Pull request by peter-schaeffer**
# Title

Improve Solarmax binding  with respect to channel Current Power Generated

# Description

Channel Current Power Generated requires updates for:
units: from WATT_HOURS to WATT
digital representation: from Integer to Decimal

### CODE REVIEW

**Comment by jlaur** [comment]
@jamietownsend - would you like to review?

**Review by lsiepel — CHANGES_REQUESTED** [review]
Why did you upload the PDF? guess it shouldnt be included in this PR?

**Comment by peter-schaeffer** [comment]
> Why did you upload the PDF? guess it shouldnt be included in this PR?

I considered the pdf relevant anyway and not directly connected to the code chages. Thus I considered to create a separate pull request. I am sorry if this violated any rules.

**Comment by jlaur** [comment]
> It is not common that we add this kind of documentation to the binding code in github.

I agree that it's better kept outside of this repo, and it would also add almost 1/2 MB to the repo size. I just checked, and we don't have any .pdf or .doc files in the repo.

**Review by jamietownsend — APPROVED** [review]
Code changes are good.

Thanks for finding this document. I agree that it's very valuable and wish I'd had it, but will let others decide if such docs should belong in the repository.

**Comment by peter-schaeffer** [comment]
> > It is not common that we add this kind of documentation to the binding code in github.
> 
> I agree that it's better kept outside of this repo, and it would also add almost 1/2 MB to the repo size. I just checked, and we don't have any .pdf or .doc files in the repo.

O, understood! 
Can you please let me know the right procedure to revert the adding of the pdf? As it was added in a pull request different to this one, I guess I take the pdf out in a new PR and this one will get the approval as suggested by @jamietownsend . 
Correct?

**Comment by lsiepel** [comment]
> > > It is not common that we add this kind of documentation to the binding code in github.
> > 
> > 
> > I agree that it's better kept outside of this repo, and it would also add almost 1/2 MB to the repo size. I just checked, and we don't have any .pdf or .doc files in the repo.
> 
> Ok, understood! Can you please let me know the right procedure to revert the adding of the pdf? As it was added in a pull request different to this one, I guess I take the pdf out in a new PR and this one will get the approval as suggested by @jamietownsend . Correct?

Files don't cross join PR's. It is added to this PR, maybe accidental. If you have your IDE set to the branch this PR is created from. (peter-schaeffer:main) you can delete the file and commit the change to this branch. this PR will be auto updated from that commit.

**Comment by peter-schaeffer** [comment]
> > > > It is not common that we add this kind of documentation to the binding code in github.
> > > 
> > > 
> > > I agree that it's better kept outside of this repo, and it would also add almost 1/2 MB to the repo size. I just checked, and we don't have any .pdf or .doc files in the repo.
> > 
> > 
> > Ok, understood! Can you please let me know the right procedure to revert the adding of the pdf? As it was added in a pull request different to this one, I guess I take the pdf out in a new PR and this one will get the approval as suggested by @jamietownsend . Correct?
> 
> Files don't cross join PR's. It is added to this PR, maybe accidental. If you have your IDE set to the branch this PR is created from. (peter-schaeffer:main) you can delete the file and commit the change to this branch. this PR will be auto updated from that commit.

PDF document was removed successfully.

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Comment by lsiepel** [comment]
> > PDF document was removed successfully.
> 
> Unfortunately it was not. Too late now to avoid impact on repository size, but it should still be considered if the file should be left or removed.

These binary files can be overlooked easily, but i should have taken more care. I'll fix it.

**Comment by peter-schaeffer** [comment]
@lsiepel: I did check the repository with respect to the pdf and do not really understand how it made its way into the merged version. I'm am sorry for the hazzle and appreciate your effort to get rid of it.

**Pull request merged**
