### PR TITLE
[airthings] Add support for Airthings Wave Mini

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by paulianttila** [comment]
@kaikreuzer Wave+ doesn't work anymore with bluegiga adapter, but I also tested with main branch without these changes and Wave+ doesn't work there either, so I guess your changes aren't the root cause.

I have been ones again struggled 6 hours with the Eclipse IDE and debugging :( Especially, when change the brach, debugging just don't work. I don't know what kind of black magic it need, but crying seems to help sometimes.

**Comment by kaikreuzer** [comment]
@paulianttila I own a Wave+ and a Wave mini and both work with this PR - I have it running on my prod system (and yes, I am also using the Bluegiga-adapter).

The only issue I noticed is that the discovery is a bit flaky and often the device appears as a bluetooth beacon instead of an airthings device in the inbox. But this is no problem with the airthings bundle, but with the generic bluetooth discovery service.

**Comment by kaikreuzer** [comment]
If you prefer to test on a distro and not in the IDE, you can try out this jar:
[org.openhab.binding.bluetooth.airthings-3.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/6291936/org.openhab.binding.bluetooth.airthings-3.1.0-SNAPSHOT.zip)

**Comment by paulianttila** [comment]
> I own a Wave+ and a Wave mini and both work with this PR - I have it running on my prod system (and yes, I am also using the Bluegiga-adapter).

Thats great. 

As I was not able to get it work in IDE, I actually build it my self, but tested with 3.1.0.M3. There was breaking change introduced couple of days ago (#8970), so that's was the reason why it didn't work. I downloaded latest nightly build and it seems to work fine. 👍

**Review by paulianttila — APPROVED** [review]
LGTM

**Review by fwolter — APPROVED** [review]
LGTM

**Pull request merged**
