### PR TITLE
Add and fix Eclipse .project, .classpath files

### PR DESCRIPTION
**Pull request by wborn**
These changes were necessary to fix errors when opening these projects in Eclipse.

### CODE REVIEW

**Review by Hilbrand — APPROVED** [review]
LGTM.

Wdyt about removing these files with OH 3? Their generated with importing a maven project anyway.

**Comment by wborn** [comment]
I'd love to see them removed because it always results in modified files after updating projects. 

There was https://github.com/openhab/openhab-addons/issues/5670 for this, @kaikreuzer in https://github.com/openhab/openhab-addons/issues/5670#issuecomment-498029185: 

> I can only be convinced that they should be removed if I am shown an (automatic) Eclipse IDE setup that doesn't work worse than before the change...

Since add-on projects are no longer automatically imported during the IDE setup (https://github.com/openhab/openhab-distro/pull/1061) that may convince @kaikreuzer that the files can be removed. :wink:

Removing them causes everyone having to reimport their Eclipse projects. So when all 2.5.x add-ons are migrated to the master branch, it might be a good time to also remove these Eclipse project files.

**Comment by J-N-K** [comment]
They are also useless when other IDEs are used.

**Comment by Hilbrand** [comment]
People probably need to reinstall eclipse with Java 11 anyway. So another reason. I'm going to make an issue and put it on the project page.

**Comment by Hilbrand** [comment]
Issue created #8451

**Comment by kaikreuzer** [comment]
> Since add-on projects are no longer automatically imported during the IDE setup (openhab/openhab-distro#1061) that may convince @kaikreuzer that the files can be removed.

Well, as all of you seem to be clear on it, I hardly stand a chance to argue against it as it seems.
Import as Maven project seems to work ok by now, so that seems indeed a standard way to use then.
Only downside is that we have different approaches for core+distro and add-ons then, because for the proper IDE setup, I hope we keep core+distro the way they are - unless someone manages to change the Oomph setup to smoothly import those projects as Maven projects.

**Comment by Hilbrand** [comment]
I would not change core+distro either at the moment. Both already use a different strategy as they import all project during setup. Developing core already seems more advanced. Sometimes people setup eclipse for binding development and also check core and end up with a lot of errors.  So there is room for improvement. I also updated the issue to add a not to update the documentation to use maven import for addon development.

**Pull request merged**
