### PR TITLE
[hue] Support new home security products

### LINKED ISSUE #15562: [hue] support new home security devices
Philips / Signify just launched a range of home security devices (cameras, contacts, etc.) so these need to be supported (via API v2).

### PR DESCRIPTION
**Pull request by andrewfg**
Philips / Signify has added a range of home security products to its offering. Specifically security cameras, security contact devices, and tamper switch devices. And this PR adds support for those products.

Resolves #15562

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by andrewfg** [comment]
@jlaur since your #15552 has been merged, this one is also ready for review

**Review by jlaur — APPROVED** [review]
Thanks for the addition of the new security products, LGTM.

Can you refresh my memory, what is the test status? Did you get any community feedback? IIRC you don't currently have any of the security products? In any case, if you are confident with the PR in its current state, let's merge it and await user feedback. 🙂

**Comment by andrewfg** [comment]
> what is the test status? 

It works for me.

> Did you get any community feedback? 

Nope.

> you don't currently have any of the security products? 

Wrong. I purchased a security contact device for testing. It is not actually used daily in my system. But it does work for testing purposes. 

By contrast I did not purchase a security camera device, but it simply uses a DTO based on the regular motion sensor (which I do have), so I guess it is probably Ok.

> if you are confident with the PR in its current state, let's merge it and await user feedback

Agreed.

**Comment by andrewfg** [comment]
Many thanks @jlaur

**Pull request merged**
