### PR TITLE
[googletts] Fix authorization from returning null refresh token

### PR DESCRIPTION
**Pull request by mhilbush**
Signed-off-by: Mark Hilbush <mark@hilbush.com>

Related to #12711 

This binding suffers from the same issue as the nest binding in that any authorization after the first one causes the Google API to return no refresh token. The net effect is that the binding will work until it needs to refresh the access token (usually after approximately 1 hour).

### CODE REVIEW

**Comment by mhilbush** [comment]
Good catch. I had no idea all that was in the config description.

**Comment by wborn** [comment]
>  I have not changed the de and fr translation files?

I think it is better to do it via Crowdin otherwise they will be overwritten the next time a string is changed. After the PR is merged Crowdin will automatically mark the changed strings in all other languages as untranslated.

**Comment by mhilbush** [comment]
Ok, I think I got it this time. 🤞

**Review by wborn — APPROVED** [review]
Thank you!

**Pull request merged**
