### PR TITLE
[nibeheatpump] Support 16-bit addressing

### PR DESCRIPTION
**Pull request by paulianttila**
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

### CODE REVIEW

**Comment by paulianttila** [comment]
fixes #13684

**Comment by paulianttila** [comment]
@elupus I would appreciate if you could double check the changes?

**Review by elupus — APPROVED** [review]
Looks good!

**Review by jlaur — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
