### PR TITLE
[BMW ConnectedDrive] initial contribution

### PR DESCRIPTION
**Pull request by ntruchsess**
This pull-request is based on https://github.com/openhab/openhab-addons/pull/8576
It fixes most of the outstanding review-comments and adds new functionality:

- it allows modification of the 'Charge Profile' both via handling commands send to the corresponding channels plus an Action (to atomically change and submit from within rules).

### CODE REVIEW

**Comment by fwolter** [comment]
Are you in contact with @weymann about this?

**Comment by ntruchsess** [comment]
> Are you in contact with @weymann about this?
generally speaking: yes, I'm in contact. He did port my additional functionality to his 2.5.x version. He seems to be rather busy, but yesterday he did recommend my OH3-version for use: https://community.openhab.org/t/bmw-connecteddrive-bmw-i3/103876/6
There is some uncertainty about how to progress with the channels that kind of implement a list or 'sliding-window' interface resulting in one channel depending on what the user chooses in the other. In the review comments there was a recommendation to provide actions to handle this, he was not sure what the design of such action should be. (you did refer to this here: https://github.com/openhab/openhab-addons/pull/8576#discussion_r549890626 ). I guess this is one of the reasons his PR doesn't progress since a few weeks.
I started with an action-class to allow modifying the chargeprofile-related attributes and trigger sending all changes at once. It is both technically required (you can only send the whole charging-profile at once) and it ensures the change is atomic - so if a user is modifying those values in parallel it cannot happen that a mixture of user-changes and rule-changes is sent to the car. The user get's to see his changes being overridden by the rules outcome and may decide to modify again. That was pretty straightforward but doesn't help with the design of the other depending channels (that sliding-window of service-messages)
From what I understand @weymann did design it this way primary to overcome the limitations of the UI (which doesn't allow to display table-like data easily). What is the recommended way to pass such table-like data to the UI then, if not this way?

**Comment by fwolter** [comment]
Thanks for following up on this! If I understand correctly, you forked #8576 to make some progress on the review findings. The best approach would be to commit your changes to that PR. This way the discussion is bundled in one PR. If we would continue here, the discussion and findings would split, which makes things difficult to track. You could ask @weymann if he grants write permission for the PR's branch, then, you could work together on #8576. WDYT?

**Comment by ntruchsess** [comment]
sure, makes more sense. In addition to this I started to explore OH3-widgets and now see my approach for editable times and weekdays does suit the old style sitemaps well, but does not fit into the new widget-philosophy. I'll do some redesign here and resubmit as soon I have a working solution.

**Comment by fwolter** [comment]
Great! Looking forward to see your changes in #8576!

**Pull request closed without merging**
