### PR TITLE
[surepetcare] fixes #11234 Check for null before updating pet location channels

### LINKED ISSUE #11234: [surepetcare] Sure Petcare Binding failed to load bridge
Hello, 

I'm a newcomer to Openhab, i've almost moved all of my devices to this wonderful new ecosystem, except for my two cat feeders. I've created the following thing: 

```
Bridge surepetcare:bridge:bridge_surepetcare "[SurePetcare] SurePetcare API" @ "LivingRoom" [ username="...", password="...", refreshIntervalTopology=36000, refreshIntervalStatus=300 ] {
        Thing pet                 236309 "[SurePetcare] Flint"         @ "LivingRoom"
	Thing pet                 236308 "[SurePetcare] Quinty"        @ "LivingRoom"
	Thing feederDevice 390621 "[SurePetcare] Flint feeder"  @ "LivingRoom"
	Thing feederDevice 391260 "[SurePetcare] Quinty feeder" @ "LivingRoom"
}
```

It looks like the bridge fails to load judging by the status "Status: UNINITIALIZED" and the HANDLER_INITIALIZING_ERROR message. When i dump the logs i see the following error message: 

```
[ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'surepetcare:bridge:bridge_surepetcare': null
java.lang.NullPointerException: null
        at org.openhab.binding.surepetcare.internal.handler.SurePetcarePetHandler.updateThing(SurePetcarePetHandler.java:178) ~[?:?]
        at org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler.updateThings(SurePetcareBridgeHandler.java:176) ~[?:?]
        at org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler.initialize(SurePetcareBridgeHandler.java:84) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

It appears that the binding is not quite able to parse the response of the API. When i remove the "Thing pet" entries from the bridge, it starts up just fine. It looks like the [SurePetcarePetHandler](https://github.com/renescherer/openhab-addons/blob/master/bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcarePetHandler.java#L178) is not expecting `pet.status.activity` to be null.

Im running my openhab 3.1.0 on raspberry pi 4 (8GB). 

I created a pull request that should fix this issue: https://github.com/openhab/openhab-addons/pull/11235

### PR DESCRIPTION
**Pull request by maarten-blokker**
Fixes a nullpointer exception when updating pet location status. See #11234 for more details.

### CODE REVIEW

**Comment by martinvw** [comment]
@HerzScheisse and/or @renescherer could you maybe review these changes, thanks a lot!

**Comment by martinvw** [comment]
@maarten-blokker it would be great if you could include a `Signed-off-by` (to certify that you wrote it or otherwise have the right to pass it on as an open-source), see https://www.openhab.org/docs/developer/contributing.html#sign-your-work

If running a local git client you can use `git commit --amend --signoff`

**Comment by renescherer** [comment]
I'm happy with the fix. 

Thanks @maarten-blokker for the contribution.

**Comment by martinvw** [comment]
Great, thanks @renescherer. @maarten-blokker please ping me or other maintainers when the commit is signed off.

**Comment by maarten-blokker** [comment]
> I'm happy with the fix.
> 
> Thanks @maarten-blokker for the contribution.

Happy to contribute! 😄 

> Great, thanks @renescherer. @maarten-blokker please ping me or other maintainers when the commit is signed off.

Not sure how to proceed, any action needed from my side?

**Comment by maarten-blokker** [comment]
@martinvw Not familiar with the process, ran the command and pushed it, it still looks like the github action is not happy!

**Comment by martinvw** [comment]
I see that I forgot to mention that you should force push, but I can fix that ☺️

**Pull request merged**
