### PR TITLE
[intesis] Add RSSI channel to intesisHome and fixed some NPEs

### PR DESCRIPTION
**Pull request by hmerk**
Signed-off-by: Hans-Jörg Merk <github@hmerk.de>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by hmerk** [comment]
Thanks @lolodomo

**Comment by jlaur** [comment]
@hmerk, can you change the PR title as you added a signal strength channel, not an RSSI channel (which would be the raw values like -70 dBm)? This is a little confusing (cc @lolodomo):

```java
updateState(CHANNEL_TYPE_RSSI, signalStrength);
```

**Comment by hmerk** [comment]
@jlaur Done 😉

**Pull request merged**
