### PR TITLE
Use Collection.isEmpty

### PR DESCRIPTION
**Pull request by wborn**
Fixes 47 SAT UseCollectionIsEmpty findings.

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM for remote openhab binding

**Review by octa22 — APPROVED** [review]
LGTM [jablotron]

**Review by andrewfg — APPROVED** [review]
[hdpowerview] LGTM
[icalendar] LGTM
[neohub] LGTM

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
