### PR TITLE
Use renamed Units class

### PR DESCRIPTION
**Pull request by wborn**
Depends on https://github.com/openhab/openhab-core/pull/1896

### CODE REVIEW

**Review by clinique — APPROVED** [review]
LGTM

**Review by Skinah — APPROVED** [review]

**Review by mherwege — APPROVED** [review]
LGTM

**Review by marcelrv — APPROVED** [review]
LGTM for miio  binding

**Review by crnjan — APPROVED** [review]

**Review by pacive — APPROVED** [review]

**Review by Cossey — APPROVED** [review]
Approving changes to hp printer binding.

**Pull request merged**
