### PR TITLE
[volvooncall] Add missing channels and update documentation (#6880)

### PR DESCRIPTION
**Pull request by soleetions**
Added to the VolvoOnCall binding:

- Tyre pressure
- Plugin Hybrid (PHEV) / Twin engine data
- Preclimatization next to Remote heater
- Average speed
- Brake fluid level

Also updated the readme file

### CODE REVIEW

**Comment by clinique** [comment]
I think you must rebase your PR, there's a lot of alien files.

**Comment by soleetions** [comment]
> I think you must rebase your PR, there's a lot of alien files.

Hmm.. I'm a noob with git and pull requests. 
What's the best way to do this?

I pulled the latest changes from from upstream to my fork to be in sync with the latest code, but this seems to go wrong?

**Comment by clinique** [comment]
Yes, mastering github is a bit tricky when you begin but it comes quick. I think your fork has been done a while ago, so you need to : 
- switch to addons 2.5.x branch
- pull last update
- switch back to your branch
- rebase it
- solve the conflicts it is has some

**Comment by soleetions** [comment]
So instead of creating a fork, clone the upstream repo and create a new branch in that one?
Because pulling on the 2.5.x branch from my fork doesn't fetch the upstream changes.

**Comment by clinique** [comment]
Yes, you can create a brand new clean fork and make another branch on it. You'll probably save your time

**Comment by soleetions** [comment]
Closing this PR, will create a new one

**Pull request closed without merging**
