### PR TITLE
[tesla] Adapt binding to changed API from Tesla backend

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes https://github.com/openhab/openhab-addons/issues/14894

The Tesla API has removed most endpoints that the binding was using for querying vehicle data.
The only one left is an aggregated call to fetch all data at once.

This PR does the necessary changes.
In my tests, all seems to work well. If enough people report that it works for them as well, this would be a candidate to backport to 3.4.x.

### CODE REVIEW

**Review by jlaur — CHANGES_REQUESTED** [review]
Thanks for taking care of this!

There are some compiler and SAT warnings introduced, you could have a look at https://ci.openhab.org/job/PR-openHAB-Addons/15443/Static_20Code_20Analysis_20Report/summary_report.html#org.openhab.binding.tesla.internal.protocol.VehicleData.java for example.

For the particular DTO class, you can fix most of them by using the `@SerializedName` annotation and camelCasing the variables. The missing `@NonNullByDefault` can be ignored for now, or you could move all the classes to a `dto` directory to have them excluded from the check.

Most of the compiler warnings are because of changed code lines that already lacked proper null handling, so you can choose to ignore them for now.

**Comment by kaikreuzer** [comment]
@jlaur I intentionally created the new DTO in the same way as the others as I didn't want to introduce a mix of variable naming styles in the same package.
I'd rather suggest to do a clean-up refactoring as an independent PR that then covers all of the DTOs. But in order to have a chance to backport this PR here, I prefer to keep the changes as small as possible.

**Comment by jlaur** [comment]
> I'd rather suggest to do a clean-up refactoring as an independent PR that then covers all of the DTOs. But in order to have a chance to backport this PR here, I prefer to keep the changes as small as possible.

That's sounds sensible.

**Review by jlaur — APPROVED** [review]

**Comment by hlemmens** [comment]
Probably stupid from my side, but when I install the 4.0.0 SNAPSHOT .jar file, I get a "ERROR:HANDLER" and "HANDLER_MISSING_ERROR" on the Tesla bridge. Should I and how should I install a new handler?

**Comment by theater** [comment]
Not sure if you need any feedback Kai, but I tested today and the fix works just fine on 4.0.0.
Cheers,
K.

**Comment by kaikreuzer** [comment]
@theater Thanks, feedback is always welcome!

**Comment by hlemmens** [comment]
@kaikreuzer. Many thanks for the fix and the hint. I managed to install the 3.4.4 Snapshot.jar and it works. The old issue [Tesla] Binding going offline #14435 is popping up again. In the 3.4.2 version it was fixed with the commit https://github.com/thijslemmens/openhab-addons/commit/24b74c53a01c022269cc4b9e34422e4d6e35271e. Can this fix be integrated as well? Is it already done in the 4.0.0 SNAPSHOT version?

**Comment by kaikreuzer** [comment]
> In the 3.4.2 version it was fixed 

Any fix that was in 3.4.2 should also have been done in 4.0.0, since we always only backport fixes, but never only fix things on older releases.

**Comment by hlemmens** [comment]
I’m afraid the issue with the access token renewal was not fixed in 3.4.2. . The commit I mentioned in previous comment has not been accepted and integrated as far as I know.

**Comment by jlaur** [comment]
@hlemmens - I don't see any pull requests from you, did you mean to create one?

**Comment by kaikreuzer** [comment]
If you are referring to [this](https://github.com/openhab/openhab-addons/issues/14435#issuecomment-1506995921) "solution", I would say that it anyhow isn't something to merge, since recreating the http client all the time does not look like a proper way to fix it.

**Comment by hlemmens** [comment]
[This](https://github.com/openhab/openhab-addons/issues/14435#issuecomment-1506995921) solution Is to my knowledge the only one that seems to work. Since I installed the fix for the changed Tesla API, every 8 hours I lose the connection with the car:
2023-05-05 07:28:40.348 [DEBUG] [sla.internal.handler.TeslaSSOHandler] - Exchanging SSO refresh token for API access token
2023-05-05 07:28:40.380 [DEBUG] [sla.internal.handler.TeslaSSOHandler] - An exception occurred while invoking a HTTP request: 'java.io.EOFException: HttpConnectionOverHTTP@d326f5::DecryptedEndPoint@1aa7a86{l=/_my internal ip_:39516,r=auth.tesla.com/23.55.96.81:443,OPEN,fill=-,flush=-,to=28816900/0}'


Happy to see a better solution than the existing one.

**Pull request merged**
