### PR TITLE
[teleinfo] Refactor channel config files for Linky standard mode

### PR DESCRIPTION
**Pull request by olivierkeke**
Signed-off-by: Olivier Marceau <hollysaiqs@marceau.ovh>

This PR removes some channel-type xml definitions duplicated in several config files.

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Did you run the i18n tool? Normally it should generate no changes on the properties file.

**Comment by olivierkeke** [comment]
> Did you run the i18n tool? Normally it should generate no changes in the properties file.

It still generates one duplicate but this one comes from an old part of the binding on which I'm less familiar. I'm investigating on it.

**Comment by lolodomo** [comment]
Last question: don't you prefer to remove the file common-cbemm-evo-icc-channel-types.xml which contains only this channel?

**Review by lolodomo — APPROVED** [review]
Thank you

**Pull request merged**
