### PR TITLE
[freeboxos] Fix macAddress property when discovering a server

### LINKED ISSUE #17071: [freeboxos] Revolution added from inbox has an invalid MAC address
I added the api bridge from inbox and the bridge is ONLINE.
Then I scan for things in Main UI and found my Revolution Server and added it.
But this thing remains unitialized: HANDLER_CONFIGURATION_PENDING
{macAddress=La valeur {addressSection={addressSegmentIndex=0.0, extended=false, divisions=[{value=20.0, upperValue=20.0}, {value=11.0, upperValue=11.0}, {value=108.0, upperValue=108.0}, {value=102.0, upperValue=102.0}, {value=43.0, upperValue=43.0}, {value=101.0, upperValue=101.0}]}} ne correspond pas au modèle ([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2}).} 

The MAC address field has this wrong value: {addressSection={addressSegmentIndex=0.0, extended=false, divisions=[{value=20.0, upperValue=20.0}, {value=11.0, upperValue=11.0}, {value=108.0, upperValue=108.0}, {value=102.0, upperValue=102.0}, {value=43.0, upperValue=43.0}, {value=101.0, upperValue=101.0}]}}

Note that I changed few values to not publish the real MAC address.

Looks like the discovery code is not able to retrieve a proper MAC address ?

@clinique for help

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #17071

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by clinique — APPROVED** [review]

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by lolodomo** [comment]
Please backport to 4.1.x.

**Comment by jlaur** [comment]
> Please backport to 4.1.x.

You are free to do that, however I assume you mean 4.2.x. 😉

**Comment by lolodomo** [comment]
Yes 4.2.x

**Pull request merged**
