### PR TITLE
[sleepiq] Fix the failing tests on Windows

### LINKED ISSUE #7981: [sleepiq] Tests failing
Build on Windows 10:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.sleepiq.api.model.BedSideStatusTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.185 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.BedSideStatusTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.BedSideStatusTest)  Time elapsed: 0.015 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "isInBed": false,
  "alertDetailedMessage": "No Alert",
  "sleepNumber": 55,
  "alertId": 0,
  "lastLink": "3 d 05:04:38",
] "pressure": 573
}> but was:<{[
  "isInBed": false,
  "alertDetailedMessage": "No Alert",
  "sleepNumber": 55,
  "alertId": 0,
  "lastLink": "3 d 05:04:38",
  "pressure": 573]
}>
        at org.openhab.binding.sleepiq.api.model.BedSideStatusTest.testSerializeAllFields(BedSideStatusTest.java:54)

[INFO] Running org.openhab.binding.sleepiq.api.model.BedsResponseTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.BedsResponseTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.BedsResponseTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "beds": [
    {
      "name": "Bed1"
    },
    {
      "name": "Bed2"
    }
] ]
}> but was:<{[
  "beds": [
    {
      "name": "Bed1"
    },
    {
      "name": "Bed2"
    }
  ]]
}>
        at org.openhab.binding.sleepiq.api.model.BedsResponseTest.testSerializeAllFields(BedsResponseTest.java:49)

[INFO] Running org.openhab.binding.sleepiq.api.model.BedStatusTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.BedStatusTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.BedStatusTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "status": 1,
  "bedId": "-9999999999999999999",
  "leftSide": {
    "isInBed": true
  },
  "rightSide": {
    "isInBed": false
] }
}> but was:<{[
  "status": 1,
  "bedId": "-9999999999999999999",
  "leftSide": {
    "isInBed": true
  },
  "rightSide": {
    "isInBed": false
  }]
}>
        at org.openhab.binding.sleepiq.api.model.BedStatusTest.testSerializeAllFields(BedStatusTest.java:51)

[INFO] Running org.openhab.binding.sleepiq.api.model.BedTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.BedTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.BedTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "registrationDate": "2017-02-17T02:14:10Z",
  "sleeperRightId": "-1111111111111111111",
  "base": "MODULAR",
  "returnRequestStatus": 0,
  "size": "QUEEN",
  "name": "Bed",
  "serial": "",
  "isKidsBed": false,
  "dualSleep": true,
  "bedId": "-9999999999999999999",
  "status": 1,
  "sleeperLeftId": "-2222222222222222222",
  "version": "",
  "accountId": "-8888888888888888888",
  "timezone": "US/Pacific",
  "model": "P5",
  "purchaseDate": "2017-02-02T00:00:01Z",
  "macAddress": "AABBCCDDEEFF",
  "sku": "QP5",
  "zipcode": "90210",
] "reference": "55555555555-5"
}> but was:<{[
  "registrationDate": "2017-02-17T02:14:10Z",
  "sleeperRightId": "-1111111111111111111",
  "base": "MODULAR",
  "returnRequestStatus": 0,
  "size": "QUEEN",
  "name": "Bed",
  "serial": "",
  "isKidsBed": false,
  "dualSleep": true,
  "bedId": "-9999999999999999999",
  "status": 1,
  "sleeperLeftId": "-2222222222222222222",
  "version": "",
  "accountId": "-8888888888888888888",
  "timezone": "US/Pacific",
  "model": "P5",
  "purchaseDate": "2017-02-02T00:00:01Z",
  "macAddress": "AABBCCDDEEFF",
  "sku": "QP5",
  "zipcode": "90210",
  "reference": "55555555555-5"]
}>
        at org.openhab.binding.sleepiq.api.model.BedTest.testSerializeAllFields(BedTest.java:80)

[INFO] Running org.openhab.binding.sleepiq.api.model.FamilyStatusTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.FamilyStatusTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.FamilyStatusTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "beds": [
    {
      "status": 1
    }
] ]
}> but was:<{[
  "beds": [
    {
      "status": 1
    }
  ]]
}>
        at org.openhab.binding.sleepiq.api.model.FamilyStatusTest.testSerializeAllFields(FamilyStatusTest.java:48)

[INFO] Running org.openhab.binding.sleepiq.api.model.PauseModeTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.PauseModeTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.PauseModeTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "accountId": "-8888888888888888888",
  "bedId": "-9999999999999999999",
] "pauseMode": "off"
}> but was:<{[
  "accountId": "-8888888888888888888",
  "bedId": "-9999999999999999999",
  "pauseMode": "off"]
}>
        at org.openhab.binding.sleepiq.api.model.PauseModeTest.testSerializeAllFields(PauseModeTest.java:46)

[INFO] Running org.openhab.binding.sleepiq.api.model.SleepersResponseTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.SleepersResponseTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.SleepersResponseTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "sleepers": [
    {
      "firstName": "Alice"
    },
    {
      "firstName": "Bob"
    }
] ]
}> but was:<{[
  "sleepers": [
    {
      "firstName": "Alice"
    },
    {
      "firstName": "Bob"
    }
  ]]
}>
        at org.openhab.binding.sleepiq.api.model.SleepersResponseTest.testSerializeAllFields(SleepersResponseTest.java:49)

[INFO] Running org.openhab.binding.sleepiq.api.model.SleeperTest
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.openhab.binding.sleepiq.api.model.SleeperTest
[ERROR] testSerializeAllFields(org.openhab.binding.sleepiq.api.model.SleeperTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
  "firstName": "Alice",
  "active": true,
  "emailValidated": true,
  "isChild": false,
  "bedId": "-9999999999999999999",
  "birthYear": "1970",
  "zipCode": "90210",
  "timezone": "US/Pacific",
  "isMale": false,
  "weight": 110,
  "duration": "",
  "sleeperId": "-1111111111111111111",
  "height": 64,
  "licenseVersion": 6,
  "username": "alice@domain.com",
  "birthMonth": 6,
  "sleepGoal": 450,
  "isAccountOwner": true,
  "accountId": "-5555555555555555555",
  "email": "alice@domain.com",
  "avatar": "",
  "lastLogin": "2017-02-17 20:19:36 CST",
] "side": 1
}> but was:<{[
  "firstName": "Alice",
  "active": true,
  "emailValidated": true,
  "isChild": false,
  "bedId": "-9999999999999999999",
  "birthYear": "1970",
  "zipCode": "90210",
  "timezone": "US/Pacific",
  "isMale": false,
  "weight": 110,
  "duration": "",
  "sleeperId": "-1111111111111111111",
  "height": 64,
  "licenseVersion": 6,
  "username": "alice@domain.com",
  "birthMonth": 6,
  "sleepGoal": 450,
  "isAccountOwner": true,
  "accountId": "-5555555555555555555",
  "email": "alice@domain.com",
  "avatar": "",
  "lastLogin": "2017-02-17 20:19:36 CST",
  "side": 1]
}>
        at org.openhab.binding.sleepiq.api.model.SleeperTest.testSerializeAllFields(SleeperTest.java:66)

[ERROR] testSerializeLastLoginNull(org.openhab.binding.sleepiq.api.model.SleeperTest)  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure:
expected:<{[
] "lastLogin": "null"
}> but was:<{[
  "lastLogin": "null"]
}>
        at org.openhab.binding.sleepiq.api.model.SleeperTest.testSerializeLastLoginNull(SleeperTest.java:73)

[INFO] Running org.openhab.binding.sleepiq.api.model.TimeSinceTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.openhab.binding.sleepiq.api.model.TimeSinceTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   BedSideStatusTest.testSerializeAllFields:54 expected:<{[
  "isInBed": false,
  "alertDetailedMessage": "No Alert",
  "sleepNumber": 55,
  "alertId": 0,
  "lastLink": "3 d 05:04:38",
] "pressure": 573
}> but was:<{[
  "isInBed": false,
  "alertDetailedMessage": "No Alert",
  "sleepNumber": 55,
  "alertId": 0,
  "lastLink": "3 d 05:04:38",
  "pressure": 573]
}>
[ERROR]   BedStatusTest.testSerializeAllFields:51 expected:<{[
  "status": 1,
  "bedId": "-9999999999999999999",
  "leftSide": {
    "isInBed": true
  },
  "rightSide": {
    "isInBed": false
] }
}> but was:<{[
  "status": 1,
  "bedId": "-9999999999999999999",
  "leftSide": {
    "isInBed": true
  },
  "rightSide": {
    "isInBed": false
  }]
}>
[ERROR]   BedTest.testSerializeAllFields:80 expected:<{[
  "registrationDate": "2017-02-17T02:14:10Z",
  "sleeperRightId": "-1111111111111111111",
  "base": "MODULAR",
  "returnRequestStatus": 0,
  "size": "QUEEN",
  "name": "Bed",
  "serial": "",
  "isKidsBed": false,
  "dualSleep": true,
  "bedId": "-9999999999999999999",
  "status": 1,
  "sleeperLeftId": "-2222222222222222222",
  "version": "",
  "accountId": "-8888888888888888888",
  "timezone": "US/Pacific",
  "model": "P5",
  "purchaseDate": "2017-02-02T00:00:01Z",
  "macAddress": "AABBCCDDEEFF",
  "sku": "QP5",
  "zipcode": "90210",
] "reference": "55555555555-5"
}> but was:<{[
  "registrationDate": "2017-02-17T02:14:10Z",
  "sleeperRightId": "-1111111111111111111",
  "base": "MODULAR",
  "returnRequestStatus": 0,
  "size": "QUEEN",
  "name": "Bed",
  "serial": "",
  "isKidsBed": false,
  "dualSleep": true,
  "bedId": "-9999999999999999999",
  "status": 1,
  "sleeperLeftId": "-2222222222222222222",
  "version": "",
  "accountId": "-8888888888888888888",
  "timezone": "US/Pacific",
  "model": "P5",
  "purchaseDate": "2017-02-02T00:00:01Z",
  "macAddress": "AABBCCDDEEFF",
  "sku": "QP5",
  "zipcode": "90210",
  "reference": "55555555555-5"]
}>
[ERROR]   BedsResponseTest.testSerializeAllFields:49 expected:<{[
  "beds": [
    {
      "name": "Bed1"
    },
    {
      "name": "Bed2"
    }
] ]
}> but was:<{[
  "beds": [
    {
      "name": "Bed1"
    },
    {
      "name": "Bed2"
    }
  ]]
}>
[ERROR]   FamilyStatusTest.testSerializeAllFields:48 expected:<{[
  "beds": [
    {
      "status": 1
    }
] ]
}> but was:<{[
  "beds": [
    {
      "status": 1
    }
  ]]
}>
[ERROR]   PauseModeTest.testSerializeAllFields:46 expected:<{[
  "accountId": "-8888888888888888888",
  "bedId": "-9999999999999999999",
] "pauseMode": "off"
}> but was:<{[
  "accountId": "-8888888888888888888",
  "bedId": "-9999999999999999999",
  "pauseMode": "off"]
}>
[ERROR]   SleeperTest.testSerializeAllFields:66 expected:<{[
  "firstName": "Alice",
  "active": true,
  "emailValidated": true,
  "isChild": false,
  "bedId": "-9999999999999999999",
  "birthYear": "1970",
  "zipCode": "90210",
  "timezone": "US/Pacific",
  "isMale": false,
  "weight": 110,
  "duration": "",
  "sleeperId": "-1111111111111111111",
  "height": 64,
  "licenseVersion": 6,
  "username": "alice@domain.com",
  "birthMonth": 6,
  "sleepGoal": 450,
  "isAccountOwner": true,
  "accountId": "-5555555555555555555",
  "email": "alice@domain.com",
  "avatar": "",
  "lastLogin": "2017-02-17 20:19:36 CST",
] "side": 1
}> but was:<{[
  "firstName": "Alice",
  "active": true,
  "emailValidated": true,
  "isChild": false,
  "bedId": "-9999999999999999999",
  "birthYear": "1970",
  "zipCode": "90210",
  "timezone": "US/Pacific",
  "isMale": false,
  "weight": 110,
  "duration": "",
  "sleeperId": "-1111111111111111111",
  "height": 64,
  "licenseVersion": 6,
  "username": "alice@domain.com",
  "birthMonth": 6,
  "sleepGoal": 450,
  "isAccountOwner": true,
  "accountId": "-5555555555555555555",
  "email": "alice@domain.com",
  "avatar": "",
  "lastLogin": "2017-02-17 20:19:36 CST",
  "side": 1]
}>
[ERROR]   SleeperTest.testSerializeLastLoginNull:73 expected:<{[
] "lastLogin": "null"
}> but was:<{[
  "lastLogin": "null"]
}>
[ERROR]   SleepersResponseTest.testSerializeAllFields:49 expected:<{[
  "sleepers": [
    {
      "firstName": "Alice"
    },
    {
      "firstName": "Bob"
    }
] ]
}> but was:<{[
  "sleepers": [
    {
      "firstName": "Alice"
    },
    {
      "firstName": "Bob"
    }
  ]]
}>
[INFO]
[ERROR] Tests run: 21, Failures: 9, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.872 s
[INFO] Finished at: 2020-06-22T18:20:02+02:00
[INFO] Final Memory: 38M/662M
[INFO] ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #7981

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Please read my comment in the issue, I am not sure that it is the best way to fix the problem with endline encoding.

**Comment by wborn** [comment]
I just copy pasted the files from the orignal repo. On my machines Git is configured to not automatically convert line endings to my OS default. I think your Git is configured to automatically convert line endings? That's why you probably run into such issues.

Gson apparently always serializes JSON with `\n` line endings. What might be better is to use `Files.readAllLines` instead of `Files.readAllBytes` and then join the lines with `\n` . That way other line endings would also be supported, see:

```java
    /**
     * Read all lines from a file. This method ensures that the file is
     * closed when all bytes have been read or an I/O error, or other runtime
     * exception, is thrown. Bytes from the file are decoded into characters
     * using the specified charset.
     *
     * <p> This method recognizes the following as line terminators:
     * <ul>
     *   <li> <code>&#92;u000D</code> followed by <code>&#92;u000A</code>,
     *     CARRIAGE RETURN followed by LINE FEED </li>
     *   <li> <code>&#92;u000A</code>, LINE FEED </li>
     *   <li> <code>&#92;u000D</code>, CARRIAGE RETURN </li>
     * </ul>
     * <p> Additional Unicode line terminators may be recognized in future
     * releases.
     *
     * <p> Note that this method is intended for simple cases where it is
     * convenient to read all lines in a single operation. It is not intended
     * for reading in large files.
     *
     * @param   path
     *          the path to the file
     * @param   cs
     *          the charset to use for decoding
     *
     * @return  the lines from the file as a {@code List}; whether the {@code
     *          List} is modifiable or not is implementation dependent and
     *          therefore not specified
     *
     * @throws  IOException
     *          if an I/O error occurs reading from the file or a malformed or
     *          unmappable byte sequence is read
     * @throws  SecurityException
     *          In the case of the default provider, and a security manager is
     *          installed, the {@link SecurityManager#checkRead(String) checkRead}
     *          method is invoked to check read access to the file.
     *
     * @see #newBufferedReader
     */
    public static List<String> readAllLines(Path path, Charset cs) throws IOException {
```

**Comment by lolodomo** [comment]
Ok, reading how Git is working, that is now clearer for me and I understand that all .json files are converted from LF to CRLF on Windows. It explains why I have CRLF on these files while in Git database they have only LF.
So the files themself are not the problem, the problem is clearly that the current tests are not compatible with Windows platform but only work on Linux. Your proposal consisting in changing the reading of the file in the tests looks the best. I will go in this direction.

Note that I see that our .gitattributes file contains:
```
 java text=auto
.xml text=auto
``
Maybe we should add `.json text=auto` ? Of course, it will not solvce the current problem.

**Comment by lolodomo** [comment]
Done. Ready for a review & merge.

**Comment by wborn** [comment]
> Maybe we should add .json text=auto ?

That makes sense since .xml is already there. It will make checkouts between users of the same OS more consistent. It might initially cause some test failures. Linux is tested using Travis/Jenkins so it will be easy to see if tests still work. You've already checked conversion to Windows line endings yourself. :wink:

**Comment by lolodomo** [comment]
The change of .gitattributes is out of the scope of thius PR. I have not tested it yet. In my case, with default Git settings, as nothing is set for .json files in .gitattributes, I understand that Git setting core.autocrlf is used which is set to true, meaning files will be converted to CRLF on Windows (core.eol is unset). Changing the file .gitattributes should have no impact in practice. It would just avoid involving different Git settings for .xml and .json files.

**Comment by wborn** [comment]
Yes that's how it works. Another benefit would be that it's also easier to search (and replace) text spanning multiple lines in many files when they consistently use the OS default line endings.

**Pull request merged**
