### PR TITLE
Fixes configuring dynamodb and influxdb using the UI

### PR DESCRIPTION
**Pull request by wborn**
* Update config.xml file paths
* Add missing annotations to DynamoDBPersistenceService
* Remove required configuration policy from DynamoDBPersistenceService causing the component to be not instantiated

See: https://github.com/openhab/openhab-addons/pull/5275#issuecomment-626187471

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> Remove required configuration policy from DynamoDBPersistenceService causing the component to be not instantiated

Just a question here: Did you test that it starts up without exceptions when no configuration is present?
Many OH1 persistence services expected a configuration and threw exception if none was there.

**Comment by wborn** [comment]
It didn't throw exceptions but it did log warnings about that the configuration was incomplete.

**Comment by kaikreuzer** [comment]
Then we should revert this again. It should be totally fine to install an add-on without using it.

**Comment by kaikreuzer** [comment]
And if the service isn't started in that case, even better.

**Comment by wborn** [comment]
I would agree if there also was a way to configure it using the UI. But it seems to require instantiation or it will not show up. So you would only be able to configure it using files.

**Comment by kaikreuzer** [comment]
Ok, but then we have to remove the warnings that it shows - it should just be silent, of no configuration is provided.

**Pull request merged**
