### PR TITLE
[netatmo] Correction of flapping ROOMS and PERSONS

### LINKED ISSUE #12764: [Netatmo] Problem during update of 'room' thing
## Current Behavior
At every refresh the room thing goes offline and then online again. Channels are updated correctly.

`2022-05-19 10:27:58.038 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxx:xxxxxx:xxxxxx' changed from ONLINE to OFFLINE: Thing is not reachable

2022-05-19 10:27:58.269 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxx:xxxxxx:xxxxxx' changed from OFFLINE: Thing is not reachable to ONLINE`

Every other thing of the binding updates correctly without problems

## Your Environment
Version used: Openhab 3.3 M5
Default Netatmo binding for 3.3 M5 distribuition (3.3.0.M5)

### PR DESCRIPTION
**Pull request by clinique**
Fixes #12764 

Signed-off-by: clinique <gael@lhopital.org>

### CODE REVIEW

**Comment by lolodomo** [comment]
As you are now setting the thing status to ONLINE while not before, did your verify that there is no regression on other thing types?

**Comment by clinique** [comment]
`isIgnoredForThingUpdate``is only set to `true` for Rooms and Persons across the codebase. But wait before proceeding, RickyTR seems to still have problems. I did not clearly understand what but does not seem solved.

**Comment by lolodomo** [comment]
@clinique : any progress ?

**Comment by clinique** [comment]
> @clinique : any progress ?

Nope

**Comment by jlaur** [comment]
Please create a new PR targeting the **main** branch.

**Pull request closed without merging**
