### PR TITLE
Update license headers to 2021

### PR DESCRIPTION
**Pull request by wborn**
Signed-off-by: Wouter Born <github@maindrain.net>

### CODE REVIEW

**Comment by J-N-K** [comment]
Unfortunately the diff  is too large to be viewed. But I would have expected that the number of lines added and removed is the same. But there are around 900 line less after the diff.

**Comment by wborn** [comment]
The were some add-on feature.xml files where I removed the header. I usually review these huge changes by scrolling through them with `git show <sha>` :slightly_smiling_face:

**Comment by wborn** [comment]
I see it also updates the headers on some external code so I'll fix that.

**Review by Hilbrand — APPROVED** [review]

**Comment by fwolter** [comment]
The skeleton contains a license header in the feature.xml. Should it be removed there, too?

**Comment by wborn** [comment]
I think it would be better, as most feature.xml files already don't have it and the header is usually bigger than the actual content. Those files are also aggregated into a file that does have the header.

**Pull request merged**
