### PR TITLE
[mybmw] 16642 fix image not loading anymore

### PR DESCRIPTION
**Pull request by martingrassl**
unfortunately it looks like BMW reverted the changes for the missing images, so I had to revert the changes done for this bug. Sorry for the confusion...

### CODE REVIEW

**Comment by jlaur** [comment]
See #16643.

**Comment by martingrassl** [comment]
> @martingrassl - no need to revert #16643 entirely, only this single line?

@jlaur no I want to revert everything. If you look at the commit https://github.com/openhab/openhab-addons/pull/16682/commits/0bb698d166a1af845344de409740251b887bc40f you can see that I changed all files which were merged previously - but if you look at the whole diff it looks like if only one line of code changed. Maybe I did something wrong, but I copied file by file of the old version to my local and then committed to GH. So maybe we could give a try, merge this PR and then I can check if everything is fine or if I have to create another PR!?

**Comment by jlaur** [comment]
> > @martingrassl - no need to revert #16643 entirely, only this single line?
> 
> @jlaur no I want to revert everything.

Can you please try to rebase towards main?

**Comment by jlaur** [comment]
> > @jlaur no I want to revert everything.
> 
> This PR includes 6 commits. Can you please try to rebase towards main?

Alternatively, you can:
- Delete your local branch.
- Do a fresh checkout from main.
- Create a new branch with the same name as the deleted one.
- Revert commit 995ea2dd3513cbb6810badee0f0285a77fcc02cb.
- Force push.

**Comment by martingrassl** [comment]
> > > @jlaur no I want to revert everything.
> > 
> > 
> > This PR includes 6 commits. Can you please try to rebase towards main?
> 
> Alternatively, you can:
> 
>     * Delete your local branch.
> 
>     * Do a fresh checkout from main.
> 
>     * Create a new branch with the same name as the deleted one.
> 
>     * Revert commit [995ea2d](https://github.com/openhab/openhab-addons/commit/995ea2dd3513cbb6810badee0f0285a77fcc02cb).
> 
>     * Force push.

Good ideas, thanks. I'll try tomorrow

**Comment by martingrassl** [comment]
@jlaur  this PR looks better now: https://github.com/openhab/openhab-addons/pull/16687. I'm closing this one

**Pull request closed without merging**
