### PR TITLE
[knx] Add JaCoCo test-coverage

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Test coverage analysis is based on JaCoCo tool.
This tool is also used in the mybmw binding.

Test-coverage report is part of the site documentation
in the target after test and can be viewed in a web browser.
IDE integration is possible via coverage extensions.

(Note: implementation changed from separate profile to always active, see comments below)

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
This is just an optional profile which can be used to generate a coverage report of the unit tests.
Does not affect the standard build.

**Comment by holgerfriedrich** [comment]
@wborn Just asking, do you know if we have other tooling for code coverage in use?

**Comment by wborn** [comment]
Currently there isn't any tooling for test coverage in openHAB. Usually I check the test coverage using IDE plug-ins.

There are also plug-ins in Jenkins to visualize it. SonarQube also has nice views and metrics for monitoring this.
IIRC the jacoco overhead is very small so it could be enabled by default for everything.

**Comment by holgerfriedrich** [comment]
@wborn thank you. I was looking for something I could use for my local builds. JaCoCo seems fine for this use case. After your comment, I changed the approach and activate the coverage report by default.

For everyone interested, here are screenshots from the html report and the IDE integration (VS Code with "Coverage Gutters" extension)
image
image

**Review by lsiepel — APPROVED** [review]
LGTM

**Pull request merged**
