### PR TITLE
[rrd4j] Corrected the default configurations

### PR DESCRIPTION
**Pull request by JueBag**
According the comments DEFAULT_NUMERIC, DEFAULT_QUANTIFIABLE config should have 5 archives, the 4th was missing. Additionally the ConsolFunction changed in the DEFAULT_QUANTIFIABLE.
The DEFAULT_OTHER config had false computed archives.

Signed-off-by: Jürgen Baginski opus42@gmx.de

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thank you!
Not sure why I had messed this up so much...

**Comment by JueBag** [comment]
That was fast! Thanks.
I'll problably have more questions on the changes of rrd4j after doing some more tests. Will post them on the forum.

Maybe at some point of time I'll be able to post a PR which passes the "signed-off" test.

**Comment by kaikreuzer** [comment]
I was a little bit too quick here with merging, this has broken our build...
@JueBag Could you please apply spotless to your change and create a new PR with that?

**Comment by JueBag** [comment]
I'm sorry for this problem.
Running "spotless" requires a more complete IDE setup (your guessed correctly, my PR was made  with the online editor).
Actually I'm observing problems to install (better get) the needed JDK.   Working on it....

**Pull request merged**
