### PR TITLE
[keba] Correct item type for state item in readme.md

### PR DESCRIPTION
**Pull request by maihacke**
# Minor change in documentation for state item

Fix documentation to correct item type for state item
Should fix https://github.com/openhab/openhab-addons/issues/13679

# Description
Fix documentation to correct item type for state item

### CODE REVIEW

**Comment by lolodomo** [comment]
The channel definition still mention Number and not String. 
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.keba/src/main/resources/OH-INF/thing/kecontact.xml#L75

**Comment by lolodomo** [comment]
And the binding is building a DecimalType for this channel:
https://github.com/openhab/openhab-addons/blob/da59cdd255a66275dd7ae11dd294fedca4942d30/bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java#L315

So Number looks good and String is wrong.

**Comment by lolodomo** [comment]
In fact, you need to make the inversed fix. 
Read the issue.

**Comment by maihacke** [comment]
Damn was totally confused this morning. Now it's (hopefully) the intended change. Sorry.

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
