### PR TITLE
[jsscripting] Fix node_modules handling

### PR DESCRIPTION
**Pull request by J-N-K**
Depends on https://github.com/openhab/openhab-core/pull/3372

### CODE REVIEW

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

I have tested this, works fine.

**Comment by florian-h05** [comment]
@wborn Can you please review this PR and the core PR? JS Scripting is currently broken and this will fix it :smiley:

**Comment by florian-h05** [comment]
@jlaur Can this get merged?
I have locally build this together with the core change and it works fine.

The CI build is failing because the core changes were merged today and I guess they aren‘t available in the core artifacts yet. If this gets merged today, JS Scripting should be fixed tomorrow (and we don‘t have to wait an additional day). In case the SNAPSHOT build of the addon fails, this is no great loss since JS Scripting is already broken.

Another option to speed this up is to get someone trigger the core build in Jenkins, I guess @kaikreuzer could help here.

**Comment by wborn** [comment]
I triggered a build. It will also allow for testing some Jenkins upgrades. :smile:

**Review by wborn — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
