### PR TITLE
[miio] update for vacuum.e2

### PR DESCRIPTION
**Pull request by marcelrv**
small update now critical commands are confirmed working.

closing #9005
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by cpmeister** [comment]
All of the line endings have changed in the readme file. You will need to fix the ReadmeHelper first.

**Comment by marcelrv** [comment]
yes, thought this would be easy...
but even running it with the new readme maker, the line endings are somehow seem wrong. 
In the hex editor I checked that it indeed just a  0x0A 
Dunno which piece is adding the CR part

**Comment by cpmeister** [comment]
If you are usingAre they coming from the base doc?

**Comment by marcelrv** [comment]
Nope it is from the automatic part.
The only thing I can think of is that maybe Windows automatically converts to Unix but Unix not converting if it was wrongly created on unix

**Comment by marcelrv** [comment]
Suggest to merge it as to me it seems to have the right line ending... At least I can confirm it has only 0A ending and git does not see a difference, so I'm assuming this is what is in this pr

**Review by cpmeister — APPROVED** [review]

**Pull request merged**
