### PR TITLE
[nibeheatpump] nibegw: Support ESP8266 and other features

### PR DESCRIPTION
**Pull request by gaaf**
This PR contains some patches I personally use on my nibegw device.

Take/cherry-pick whatever you deem useful. If you need me to respin the PR, let me know what to leave out.

### CODE REVIEW

**Comment by jlaur** [comment]
@paulianttila - if you will find some time, perhaps you could have a look at this PR?

**Comment by lsiepel** [comment]
Gentle ping @paulianttila 
@gaaf do you know if this was tested/used by some other community members?

**Comment by jlaur** [comment]
@paulianttila - any chance you could have a look at this PR?

**Comment by gaaf** [comment]
I have since switched to esphome. As there hasn't been any response from the maintainer, I have no interest in pursuing the integration of these patches anymore. You're ofcourse still free to use them.

**Pull request closed without merging**
