### PR TITLE
[shelly] Bug fixes

### PR DESCRIPTION
**Pull request by markus7017**
This PR includes some minor fixes

### CODE REVIEW

**Comment by cpmeister** [comment]
Are you adding anything else to this or can I merge this?

**Comment by markus7017** [comment]
no, a mini-PR to fix some mintor bugs from 2.5.4; enhancements will be another one (later)

**Comment by cpmeister** [comment]
If this isn't ready please mark the PR as a "work in progress".

**Comment by markus7017** [comment]
@cpmeister this one is done, sorry for confusion, I meant “yes, this is a mini PR for bug fixes, everything else will be a new one”🤪🦠

**Pull request merged**
