### PR TITLE
[linky] Thing goes OFFLINE once again

### LINKED ISSUE #17773: [linky] Binding again unavailable
image

@clinique @lo92fr for information

### PR DESCRIPTION
**Pull request by clinique**
Correction of the url.
Resolves #17773

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lsiepel** [comment]
Does it need a backport?

**Comment by clinique** [comment]
> Does it need a backport?

Yes, please.

**Comment by lolodomo** [comment]
Was the previous PR already backported ?

**Comment by lsiepel** [comment]
> Was the previous PR already backported ?

Guess you refer to https://github.com/openhab/openhab-addons/pull/17538 i hesitatie to backport that one as it is not just the mandatory bug fix, but also has some other changes.

**Comment by lolodomo** [comment]
Backporting this new one if the other was not backported is I believe fully useless as the binding will still not work.
To be confirmed by @clinique

**Comment by clinique** [comment]
I do confirm. This binding is broken until then. But maybe we're only 3 using it :-)

**Comment by lsiepel** [comment]
Both PR's are now backported.

**Pull request merged**
