### PR TITLE
[insteon] handle cases when channelLinked is not called after initialization

### PR DESCRIPTION
**Pull request by robnielsen**
This addresses changes in behavior from OH2 to OH3 as described at https://github.com/openhab/openhab-core/issues/1707.

### CODE REVIEW

**Comment by robnielsen** [comment]
@wborn when you have a chance, can you check this out. I basically implemented what you suggested in https://github.com/openhab/openhab-core/issues/1707.

**Review by wborn — APPROVED** [review]
Thanks and sorry for the inconvenience!

**Comment by lolodomo** [comment]
Would it be possible to create an issue to list and follow all bindings that should be checked due to the change in the core framework?

**Comment by robnielsen** [comment]
@lolodomo, can you add a comment about this to https://github.com/openhab/openhab-core/issues/1707?

**Comment by lolodomo** [comment]
Done. 
You're right, it was not the good place here.

**Pull request merged**
