### PR TITLE
[elkm1] ELKM1 alarm panel binding continued development

### PR DESCRIPTION
**Pull request by matchews**
Signed-off-by: Matt Myers mmyers75@icloud.com

ELKM1 Alarm panel binding continued development

Picking up code development from David Bennet

### CODE REVIEW

**Comment by fwolter** [comment]
What is the relationship to PR #7150?

**Comment by matchews** [comment]
> What is the relationship to PR #7150?

Sorry, that was a first attempt before the code was mostly cleaned up.  I just closed it.

**Comment by Hilbrand** [comment]
You accidentally included your other binding in this pr haywardomnilogic. Just remove that part and push again.

**Comment by matchews** [comment]
As you can see I'm learning git as I go here.  I'm not sure I have the correct setup on my end.  I cloned the add-ons repo, forked it once, created a hayward binding branch, add the files, commit and pushed them.  I then created a branch for the ELKM1 binding, added the files (forgot to remove the hayward files), commit and pushed them.  Now I'm struggling with removing the hayward files while keeping the elk files in the elk branch.  Is there a better way to set this up for multiple binding development?  Any advice is appreciated.  Thx!

**Comment by Hilbrand** [comment]
When creating a new branch make sure the branch you start of is checked out (or pass the right arguments to git command). So in this case you should have started first with `git checkout 2.5.x` and than run the git create.

It now seems to you removed to much. There are several ways to fix this. One is to run:
`git rebase -i HEAD~7` this will open an editor with a list of commits. You can replace the word `pick` with `d` (for `delete`) on all the commits that should not be here. Which are the last 2 and the 3 before your first elkm1 commit. Save the file and exit and then it should fix it.

To put you changes back to GitHub you need to force push them. Use `git push --force-with-lease`.

**Comment by matchews** [comment]
Thanks for the help Hilbrand!  Let me know if anything else needs cleaned up.

**Comment by fwolter** [comment]
Before reviewing this, we should finish your other PR #8338, as some feedback applies to this PR, too.

**Comment by kaikreuzer** [comment]
Closing this PR as it is not in a mergeable state. Please follow [the instructions to port this PR to the main branch](https://github.com/openhab/openhab-addons/issues/8512) for openHAB 3.

**Pull request closed without merging**
