### PR TITLE
[amazonechocontrol] Improve documentation

### PR DESCRIPTION
**Pull request by lsiepel**
- Re-aranged to prevent duplicate headers, 
- Fixed some markdown warnings
- Same information was listed on several places (de-duplicate)

### CODE REVIEW

**Review by clinique — COMMENTED** [review]
LGTM. Thanks.

**Review by theater — APPROVED** [review]

**Comment by lsiepel** [comment]
Sorry, commit to wrong branch, corrected now. :-/

**Comment by lsiepel** [comment]
@openhab/add-ons-maintainers Please merge before 4.3.0 GA

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
