### PR TITLE
[rfxcom] Support for Lucciair DC Speed

### PR DESCRIPTION
**Pull request by martinvw**
Add support for speed for the regular Lucciair DC Fan

See also: https://community.openhab.org/t/rfxcom-add-on-support-for-lucciair-dc-speed-1-to-6/131625

### CODE REVIEW

**Comment by lolodomo** [comment]
Looks like this PR contains changes from another PR I just merged.

**Comment by martinvw** [comment]
> Looks like this PR contains changes from another PR I just merged.

@lolodomo I rebased, it should be fine now, thanks for the quick review of my PR

**Comment by martinvw** [comment]
Fair point I still need to come up with a good solution for the the backwards compatibility any suggestions? Thanks!

**Comment by lolodomo** [comment]
> Fair point I still need to come up with a good solution for the the backwards compatibility any suggestions? Thanks!

I see no good solution. But a solution is to inform users through the release notes.

**Comment by martinvw** [comment]
See https://github.com/openhab/openhab-distro/pull/1373

**Comment by martinvw** [comment]
@lolodomo ready!

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
