### PR TITLE
[openhabcloud] Update README for new notification features

### PR DESCRIPTION
**Pull request by florian-h05**
Refs #16938.

This adds the NotificationAction docs to the openHAB Cloud Connector add-on, my plan is to link the action docs to this new docs. Documentation close to code is always a good thing.

### CODE REVIEW

**Comment by florian-h05** [comment]
@digitaldan @lsiepel Documentation for #16934 is ready to be merged.

**Comment by florian-h05** [comment]
Please wait with merging, just let me add a few examples.

**Comment by florian-h05** [comment]
So now this is finally ready for merging.

**Review by lsiepel — APPROVED** [review]
LGTM, thanks

**Comment by digitaldan** [comment]
@florian-h05 thanks so much for doing this !

**Pull request merged**
