### PR TITLE
[satel] Fixes for INT-RS module

### PR DESCRIPTION
**Pull request by druciak**
This PR fixes communication problems when using INT-RS bridge.
Issue is described here: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests/56135/234
After several disconnections one of the binding threads hangs and communistion is stopped. The main change is to rely on receive timeout that can be setup for serial port instead of thread based watchdog.

Signed-off-by: Krzysztof Goworek <krzysztof.goworek@gmail.com>

### CODE REVIEW

**Comment by cpmeister** [comment]
has this change been made to the main branch yet?

**Comment by druciak** [comment]
Not yet. Should I start with PR to main?

**Comment by cpmeister** [comment]
Yes, please start with a PR against main. You can keep this PR in the meantime.

**Comment by druciak** [comment]
Done:
https://github.com/openhab/openhab-addons/pull/9072

**Review by cpmeister — APPROVED** [review]

**Pull request merged**
