### PR TITLE
[wiz] Correct units for RSSI

### PR DESCRIPTION
**Pull request by ccutrer**
Number:Power of dBm, instead of Number:Dimensionless of dB.

See discussion in #17826

### CODE REVIEW

**Comment by jlaur** [comment]
Thanks! Can you please also provide update instructions for fixing the channel? Otherwise LGTM.

**Comment by lolodomo** [comment]
This is the case where only item type is changed. It cannot be handle through upgrade instructions. But I remember @lsiepel made rests few weeks ago and if I correctly remember it was not necessary. @lsiepel  ?

**Comment by jlaur** [comment]
> This is the case where only item type is changed. It cannot be handle through upgrade instructions. But I remember @lsiepel made rests few weeks ago and if I correctly remember it was not necessary. @lsiepel ?

I think an update instruction is needed and will work, see #17845. Please correct me if I'm wrong, @andrewfg.

**Comment by andrewfg** [comment]
Do you need upgrade instructions. The original binding was only released a few days ago, so the only users so far will be snapshot users.

**Comment by jlaur** [comment]
> Do you need upgrade instructions? The original binding was only released a few days ago, so the only users so far will be snapshot users.

Sorry for being unclear, I meant to ask you for confirmation that it will work.

It is needed, because otherwise snapshot and milestone 5 users will need to recreate their Things.

**Comment by andrewfg** [comment]
^
Insofar as #17845 did work, then this would work here too. (But TBH although it changes the channel type on already created things, I don't know it the upgrade process does actually change the parameters on already created items that are linked to those channels. I think it should do that, but I honestly don't know if it really does so. But in any case that is a discussion for OH and not here..

**Comment by andrewfg** [comment]
Probably you need something like the following (not checked)..

#### /update/instructions.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<update:update-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:update="https://openhab.org/schemas/update-description/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/update-description/v1.0.0 https://openhab.org/schemas/update-description-1.0.0.xsd">

	<thing-type uid="wiz:color-bulb">
		<instruction-set targetVersion="1">
			<update-channel id="rssi">
				<type>wiz:rssi</type>
			</update-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="wiz:tunable-bulb">
		<instruction-set targetVersion="1">
			<update-channel id="rssi">
				<type>wiz:rssi</type>
			</update-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="wiz:dimmable-bulb">
		<instruction-set targetVersion="1">
			<update-channel id="rssi">
				<type>wiz:rssi</type>
			</update-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="wiz:plug">
		<instruction-set targetVersion="1">
			<update-channel id="rssi">
				<type>wiz:rssi</type>
			</update-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="wiz:fan">
		<instruction-set targetVersion="1">
			<update-channel id="rssi">
				<type>wiz:rssi</type>
			</update-channel>
		</instruction-set>
	</thing-type>

	<thing-type uid="wiz:fan-with-dimmable-bulb">
		<instruction-set targetVersion="1">
			<update-channel id="rssi">
				<type>wiz:rssi</type>
			</update-channel>
		</instruction-set>
	</thing-type>

</update:update-descriptions>
```

#### and for each thing-type.xml

```
  <thing-type uid="color-bulb">
    ...
    <properties>
      <property name="thingTypeVersion">1</property>
    </properties>
    ...

  <thing-type uid="tunable-bulb">
    ...
    <properties>
      <property name="thingTypeVersion">1</property>
    </properties>
    ...

  <thing-type uid="dimmable-bulb">
    ...
    <properties>
      <property name="thingTypeVersion">1</property>
    </properties>
    ...

  <thing-type uid="plug">
    ...
    <properties>
      <property name="thingTypeVersion">1</property>
    </properties>
    ...

  <thing-type uid="fan">
    ...
    <properties>
      <property name="thingTypeVersion">1</property>
    </properties>
    ...

  <thing-type uid="fan-with-dimmable-bulb">
    <properties>
      <property name="thingTypeVersion">1</property>
    </properties>

```

**Comment by lsiepel** [comment]
Bit late to the discussion, but yes upgrade instructions are needed, a simple update statement is enough exactly as what @andrewfg suggests. 
For reference: https://github.com/openhab/openhab-addons/pull/17737#discussion_r1855284453

**Review by jlaur — APPROVED** [review]
LGTM

**Pull request merged**
