### PR TITLE
[energidataservice] Add support for reduced electricity tax

### LINKED ISSUE #15635: [energidataservice] Add channel for reduced electricity tax
When using electricity for heating in Denmark, you can apply for paying reduced electricity taxes after the first 4000 kWh consumed per year.

This reduced rate is available in the Energi Data Service [DatahubPricelist](https://www.energidataservice.dk/tso-electricity/DatahubPricelist) dataset and could be exposed as a channel in the binding:
- GLN Number: 5790000432752
- Note: Reduceret elafgift
- ChargeType: D03

image

See https://community.openhab.org/t/energi-data-service-binding-4-0-0-0-4-1-0-0/144370/16

### PR DESCRIPTION
**Pull request by jlaur**
Resolves #15635

Builds available for testing:
- [org.openhab.binding.energidataservice-4.0.4-SNAPSHOT.jar](https://drive.google.com/file/d/115El7h4wvmxrGkpqGwoB-cbWoAi7X4YB/view?usp=sharing)
- [org.openhab.binding.energidataservice-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/18jgAHnhZzd7YMI2Qmbp31Ww4yEb-KMUC/view?usp=sharing)

### CODE REVIEW

**Comment by jlaur** [comment]
Marking as draft as I have some doubts/ideas. Probably it would be better to expose only one channel for electricity tax and make it configurable whether to use reduced rate or not. It must be possible to change this configuration from rules, so it can be automated when the meter hits 4000 kWh, and when the date hits January 1st.

**Comment by jlaur** [comment]
On hold and awaiting review of #15651.

**Comment by jlaur** [comment]
@lolodomo - if you still have time, maybe this one could be reviewed and considered for M2? I consider it low-risk due to extensive test coverage - and I'm also running it in my production system.

**Comment by lolodomo** [comment]
I reviewed everything except the tests. No comment until now.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
