### PR TITLE
[tesla] removed glassfish dependencies

### PR DESCRIPTION
**Pull request by kaikreuzer**
Related to https://github.com/openhab/openhab-core/pull/1443

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by wborn** [comment]
I tested this on the add-ons port with https://github.com/openhab/openhab-core/pull/1443: 
* the Tesla binding builds fine with these changes
* the LaMetricTime feature verification fails:

`[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-lametrictime; type=karaf.feature; version=3.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-lametrictime)(type=karaf.feature)(version>=3.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-lametrictime/3.0.0.SNAPSHOT: missing requirement [openhab-binding-lametrictime/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.lametrictime; type=osgi.bundle; version="[3.0.0.202005021727,3.0.0.202005021727]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.lametrictime/3.0.0.202005021727: missing requirement [org.openhab.binding.lametrictime/3.0.0.202005021727] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.glassfish.jersey.client.authentication)(version>=2.22.0)(!(version>=3.0.0)))"]]`

**Comment by kaikreuzer** [comment]
There was a bundle dependency in the feature.xml. I removed it and hope that this solves it.

**Comment by kaikreuzer** [comment]
rebasing...

**Comment by wborn** [comment]
Feature validation fails because the lametrictime-api dependency seems to [depend](https://github.com/syphr42/liblametrictime-java/blob/6eae77a7ce8758503191b312e894b5f1acfeda90/pom.xml#L128-L139) on this artifact. Perhaps it can be embedded?

**Comment by kaikreuzer** [comment]
Outch, good catch.
That makes the fix more complicated.
As the lib does not seem to be actively maintained anymore, I think it might make sense to directly include the sources (which will need to be slightly adapted as well) into our add-on.

**Comment by kaikreuzer** [comment]
I have changed this PR to only adapt the Tesla binding.
Will create a new one for LaMetric Time.

**Pull request merged**
