### PR TITLE
[WIP] [somfytahoma] switched to the oauth2 login method

### PR DESCRIPTION
**Pull request by octa22**
This PR brings OAUTH2 to the Somfy Tahoma Binding, since Somfy is slowly switching to this new auth. method.
Still needs a lot of testing, so work in progress...

Seems to be working with Tahoma, but other portals are a question.

Signed-off-by: Ondrej Pecta <opecta@gmail.com>

### CODE REVIEW

**Comment by hartmark** [comment]
What does it mean that they are slowly switching to this auth? Will the old stop working?

The connection to my Tahoma is quite instable and I need to disable the bridge and enable it again after a while.

My hope is that this oauth2 method is working the same way if I have enabled the dev-mode and just connect with 
gateway-pin:8443 url as specified at:
https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode
https://somfy-developer.github.io/Somfy-TaHoma-Developer-Mode/#/Gateway/get_setup_gateways

**Comment by hartmark** [comment]
I wrote this small bash-script to interact with the local-dev endpoint.

```
#!/usr/bin/bash
echo 'Usage: '
echo "./tahoma-test.sh 'email' 'password' 'pid'"                             

curl -k -X POST \
  -c cookies.txt \
  --data-urlencode "userId=$1" \
  --data-urlencode "userPassword=$2" \
  -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
  https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/login  
echo ""

curl -X GET \
  --cookie cookies.txt \
  -H "Content-Type: application/json" \
  "https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/$3/local/tokens/generate"  
echo ""
read -r -p "Paste token gotten from command above: " token

curl -X POST \
  --cookie cookies.txt \
  -H "Content-Type: application/json" \
  "https://ha101-1.overkiz.com/enduser-mobile-web/enduserAPI/config/$3/local/tokens" \
  -d "{\"label\": \"Toto token\", \"token\": \"$token\", \"scope\": \"devmode\" }"

curl -k -X 'GET' \
  "https://gateway-$3.local:8443/enduser-mobile-web/1/enduserAPI/setup/gateways" \
  -H 'accept: application/json' \
  -H "Authorization: Bearer $token" | python -m json.tool

```

It would have been awesome it this binding supported it so I just need to go online to get a valid token.

**Comment by octa22** [comment]
Somfy still uses both auth methods, but started using the OAUTH2 as a primary one and the former one as a fallback. I guess once they tune it and users migrate to new versions of the app there will be no other login method than OAUTH. Have you tried this WIP version? Is it working for you? I will check the local dev mode and try to support it as well, I had no idea it has been allowed to enable it by this official version...

**Comment by hartmark** [comment]
I haven't tried this WIP version.

I'm quite the noob at this openhab development, is there any easy way for me to try out these changes?

**Comment by octa22** [comment]
you can disable the bundled SomfyTahoma version and try this one:
https://www.dropbox.com/s/94halw8f21l8opv/org.openhab.binding.somfytahoma-3.3.0-SNAPSHOT.jar?dl=1
copy the file to the addons directory of OH...
I hope it gets better...

**Comment by hartmark** [comment]
Thanks for the jar-file, it works perfectly. I was a bit confused that it didn't show up in the openhab gui that the binding was activated. However after some googling I realized the jars in the addons folder loads automagically.
```

openhab> bundle:list | grep -i somfy                                                                                                                                                                                                      
275 │ Active │  80 │ 3.3.0.202205040529    │ openHAB Add-ons :: Bundles :: SomfyTahoma Binding
openhab> feature:list | grep -i somfy                                                                                                                                                                                                     
openhab-binding-somfymylink                       │ 3.2.0            │          │ Uninstalled │ openhab-addons-3.2.0     │ Somfy MyLink Binding
openhab-binding-somfytahoma                       │ 3.2.0            │          │ Uninstalled │ openhab-addons-3.2.0     │ Somfy Tahoma Binding
openhab-binding-urtsi                             │ 3.2.0            │          │ Uninstalled │ openhab-addons-3.2.0     │ Somfy URTSI II Binding
```
I also had to run this command as INFO was the default log-level
`log:set DEBUG org.openhab.binding.somfytahoma`

```
openhab> log:tail org.openhab.binding.somfytahoma                                                                                                                                                                          
01:33:38.086 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Refreshing Tahoma states...
01:33:43.457 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Doing cleanup
01:33:43.467 [DEBUG] [overy.SomfyTahomaItemDiscoveryService] - Stopping SomfyTahoma background discovery
01:33:47.984 [DEBUG] [ma.internal.SomfyTahomaHandlerFactory] - Creating handler for bridge
01:33:47.988 [DEBUG] [overy.SomfyTahomaItemDiscoveryService] - Creating discovery service
01:33:47.992 [DEBUG] [overy.SomfyTahomaItemDiscoveryService] - Starting SomfyTahoma background discovery
01:33:48.750 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - OAuth2 Access Token: <redacted....>
01:33:48.917 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Events id: 96922a0f-98e4-e192-4d47-d4fada922c5a
01:33:48.920 [DEBUG] [ma.internal.SomfyTahomaHandlerFactory] - Creating handler for gateway
01:33:48.921 [DEBUG] [ma.internal.SomfyTahomaHandlerFactory] - Creating handler for awning
01:33:48.920 [DEBUG] [ma.internal.SomfyTahomaHandlerFactory] - Creating handler for exteriorscreen
01:33:48.919 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Initialize done...

```

Then after that the log goes on and lists my awnigs and exteriourscreens. I tried some basic testing raising and lowering them and it seems to work nicely.

The oauth2-token, will it expire after a while or is it working indefinitely?

**Comment by hartmark** [comment]
I just saw you have pushed new commits for the local mode api, if you want me to try it out you can send me another jar for that version too

**Comment by octa22** [comment]
I am glad it works. 
You are right I have added  the control over the LAN support, but it is not working so far because there is a bug in the Somfy firmware (the registeration as an local event subscriber does not work). Once they release a new FW for the Tahoma, we can move on.

**Comment by hartmark** [comment]
Cool, is there a tracker or something to subscribe for when the fw is out? Have you been in contact with them?

**Comment by octa22** [comment]
I am waiting for a fix for this issue - https://github.com/Somfy-Developer/Somfy-TaHoma-Developer-Mode/issues/4

**Comment by hartmark** [comment]
Thanks for the details, let's see when they fix this.

**Comment by hartmark** [comment]
Seems the linked issue has been fixed so I'd happy try out the version for local mode

**Comment by hartmark** [comment]
16:27:33.671 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Starting mDNS discovery...
16:27:38.684 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Cannot switch to developer mode - gateway not found on LAN

I'm running my openhab in a container so I guess mDNS is not possible. I have ipv6 access on my docker container so if I can specify an dns-name manually to use for the developer-mode it would work for me.

**Comment by hartmark** [comment]
I was able to get mDNS up and running in the docker-container.

It seems to fail to connect anyway.

Perhaps it tries to connect to the .local hostname and it seems to not be registred.

```
root@c18509864aed:/openhab# avahi-browse  _kizbox._tcp --resolve -t
+ (null) IPv6 gateway-1238-4254-7413                        _kizbox._tcp         local
+ (null) IPv4 gateway-1238-4254-7413                        _kizbox._tcp         local
+ (null) IPv6 gateway-1238-4254-7413                        _kizbox._tcp         local
+ (null) IPv4 gateway-1238-4254-7413                        _kizbox._tcp         local
= (null) IPv4 gateway-1238-4254-7413                        _kizbox._tcp         local
   hostname = [gateway-1238-4254-7413.local]
   address = [192.168.1.244]
   port = [443]
   txt = ["fw_version=2022.1.4-26" "gateway_pin=1238-4254-7413" "api_version=1"]
= (null) IPv6 gateway-1238-4254-7413                        _kizbox._tcp         local
   hostname = [gateway-1238-4254-7413.local]
   address = [192.168.1.244]
   port = [443]
   txt = ["fw_version=2022.1.4-26" "gateway_pin=1238-4254-7413" "api_version=1"]
= (null) IPv6 gateway-1238-4254-7413                        _kizbox._tcp         local
   hostname = [gateway-1238-4254-7413.local]
   address = [192.168.1.244]
   port = [443]
   txt = ["fw_version=2022.1.4-26" "gateway_pin=1238-4254-7413" "api_version=1"]
= (null) IPv4 gateway-1238-4254-7413                        _kizbox._tcp         local
   hostname = [gateway-1238-4254-7413.local]
   address = [192.168.1.244]
   port = [443]
   txt = ["fw_version=2022.1.4-26" "gateway_pin=1238-4254-7413" "api_version=1"]

```

```
root@c18509864aed:/openhab# ping gateway-1238-4254-7413.local -c 1
ping: gateway-1238-4254-7413.local: Name or service not known
root@c18509864aed:/openhab# ping gateway-1238-4254-7413 -c 1
PING gateway-1238-4254-7413 (192.168.1.244) 56(84) bytes of data.
64 bytes from gateway-1238-4254-7413.lan (192.168.1.244): icmp_seq=1 ttl=63 time=0.542 ms

--- gateway-1238-4254-7413 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.542/0.542/0.542/0.000 ms
root@c18509864aed:/openhab# ping gateway-1238-4254-7413.lan -c 1
PING gateway-1238-4254-7413.lan (192.168.1.244) 56(84) bytes of data.
64 bytes from gateway-1238-4254-7413.lan (192.168.1.244): icmp_seq=1 ttl=63 time=0.521 ms

--- gateway-1238-4254-7413.lan ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.521/0.521/0.521/0.000 ms

```

As you can see the .local hostname is not reachable and .lan is my dns-suffix set by the dhcp-server

**Comment by octa22** [comment]
I always connect to the advertised IP address, can you paste the the debug
log? the IP address should be logged there.
BTW the local connection works fine for me, unfortunately some devices are
not suported yet :-(
Ondrej

so 14. 5. 2022 v 21:37 odesílatel Markus Hartung ***@***.***>
napsal:

**Comment by hartmark** [comment]
I checked the logs and there's nothing more than I posted above.

I may have been too hasty to announce I got mDNS working in my docker container. The avahi-browse command uses dbus that is attached to the host by binding /var/run/dbus/system_bus_socket to the container. And it seems JmDNS library you're using doesn't support dbus.

 So that's the reason it's not working.

I'll try again tonight to get proper mDNS working in docker.

If you add an option to select the hostname manually I don't need to get mDNS working in docker.

**Comment by octa22** [comment]
Hello @hartmark,
please check the new version - https://www.dropbox.com/s/94halw8f21l8opv/org.openhab.binding.somfytahoma-3.3.0-SNAPSHOT.jar?dl=1
you can find the ip and gateway pin in the advanced bridge configuration. I hope this helps.

**Comment by hartmark** [comment]
Awesome!
Adding pin and "ip" worked perfectly. I entered the hostname of my gateway because I haven't set it to static ip and it worked so perhaps you should rename the property to "hostname/ip" or add a small description.

I found a promising docker image that I can perhaps add to the same network as my openhab container so hopefully I can get it working with just mDNS. I'll keep you posted about that.

**Comment by hartmark** [comment]
I got mDNS working so I can verify that it's working even without specifying the pin and ip manually.

For futher reference this is the way to get mDNS working in docker:
https://hub.docker.com/r/epandi/avahi

Shortly explained, just add another container that bridge the LAN with the docker-LAN and broadcast the mDNS traffic between.

I get however some errors occationally in the log:

```
01:40:49.279 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Refreshing Tahoma states...                                                                                                                                                
01:40:49.281 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Sending PUT to url: https://www.tahomalink.com/enduser-mobile-web/enduserAPI/setup/devices/states/refresh with data:                                                       
01:40:49.284 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Cannot call url: https://www.tahomalink.com/enduser-mobile-web/enduserAPI/setup/devices/states/refresh with params: !                                                      
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: HttpClient@62f86e{STOPPED} is stopped                                                                                                           
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]                                                                                                                         
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]                                                                                                                               
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:730) ~[?:?]                                                                                                                                                         
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.sendMethodToTahomaWithCookie(SomfyTahomaBridgeHandler.java:747) ~[?:?]                                                                               
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.sendMethodToTahomaWithCookie(SomfyTahomaBridgeHandler.java:736) ~[?:?]                                                                               
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.sendPutToTahomaWithCookie(SomfyTahomaBridgeHandler.java:726) ~[?:?]                                                                                  
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.invokeCallToURL(SomfyTahomaBridgeHandler.java:1062) ~[?:?]                                                                                           
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.forceGatewaySync(SomfyTahomaBridgeHandler.java:990) ~[?:?]                                                                                           
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.refreshTahomaStates(SomfyTahomaBridgeHandler.java:690) ~[?:?]                                                                                        
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.lambda$2(SomfyTahomaBridgeHandler.java:197) ~[?:?]                                                                                                   
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]                                                                                                                                                  
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]                
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]                                      
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]                                                                                                                                          
        at java.lang.Thread.run(Thread.java:829) [?:?]                                                               
Caused by: java.util.concurrent.RejectedExecutionException: HttpClient@62f86e{STOPPED} is stopped                                                                                                                                         
        at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:294) ~[?:?]       
        at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:262) ~[?:?]                                                                                                                                                 
        at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:600) ~[?:?]                                                                                                                                                           
        at org.eclipse.jetty.client.HttpRequest.sendAsync(HttpRequest.java:778) ~[?:?]     
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:765) ~[?:?]                   
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:726) ~[?:?]                                                                                                                                                         
        ... 13 more                                                                                                  

```

**Comment by lolodomo** [comment]
I just have a quick look and apparently you are not using the OAuth2 client from the OH core framework  Is there a reason? 

What kind of grant flow has to be implemented? 

I also found a client id and client secret hardcore. Looks strange.

**Comment by octa22** [comment]
I have decided to close this PR since Tahoma introduced meanwhile the local mode control, the OAUTH2 support seemed to be more stable than the old auth schema. I will create a new PR containing the local mode support only with the recommended auth schema.
Regarding to your questions - I have no idea there is an OAUTH2 support provided by the OH core framework, sorry. If you can point me to some binding with the right implementation, I will definitely use it in the future.
And yes - hardcoded clientid and secret have been reverse engineered from the web client, there is no offical OAUTH2 support.

**Comment by octa22** [comment]
the local mode support PR is here: https://github.com/openhab/openhab-addons/pull/13411

**Comment by lolodomo** [comment]
> I have no idea there is an OAUTH2 support provided by the OH core framework, sorry. If you can point me to some binding with the right implementation, I will definitely use it in the future.

For your information: https://github.com/openhab/openhab-core/tree/main/bundles/org.openhab.core.auth.oauth2client/src/main/java/org/openhab/core/auth/oauth2client/internal

Searching for oAuthFactory, I found the following bindings using it:

- mielecloud
- myq
- ecowatt
- groupepsa
- livisismarthome
- hydrawise
- nest
- innogysmarthome
- spotify
- ecobee
- mercedesme
- bticinosmarther
- automover
- homeconnect
- googletts
- googlestt

**Pull request closed without merging**
