### PR TITLE
Remove redundant modifiers from interfaces

### PR DESCRIPTION
**Pull request by wborn**
This removes redundant modifiers from the interfaces similar to https://github.com/openhab/openhab-core/pull/3560.

### CODE REVIEW

**Review by mherwege — APPROVED** [review]
LGTM for nikohomecontrol and upnpcontrol

**Review by jlaur — APPROVED** [review]
Thanks for the cleanup! 👍

**Review by holgerfriedrich — APPROVED** [review]
LGTM for knx

**Review by marcelrv — APPROVED** [review]

**Review by mhilbush — APPROVED** [review]
Thanks!

**Pull request merged**
