### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed version from references to openHAB repos and teams
- Added hint about Spotless formatting tool

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
Seems commons-collections is still being used in some places:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project org.openhab.binding.mqtt.homeassistant: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/openhab/openhab-addons/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java:[25,722] The import org.apache.commons.collections cannot be resolved
[ERROR] /home/travis/build/openhab/openhab-addons/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java:[129,6033] CollectionUtils cannot be resolved
```

**Comment by cweitkamp** [comment]
I can have a look tomorrow, if you like.

**Comment by cweitkamp** [comment]
@wborn Does marytts depend on commens-collections too?

```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.2.7:verify (karaf-feature-verification) on project org.openhab.voice.marytts: Feature resolution failed for [openhab-voice-marytts/3.0.0.SNAPSHOT]
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-voice-marytts; type=karaf.feature; version=3.0.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-voice-marytts)(type=karaf.feature)(version>=3.0.0.SNAPSHOT))" [caused by: Unable to resolve openhab-voice-marytts/3.0.0.SNAPSHOT: missing requirement [openhab-voice-marytts/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.voice.marytts; type=osgi.bundle; version="[3.0.0.201912221328,3.0.0.201912221328]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.voice.marytts/3.0.0.201912221328: missing requirement [org.openhab.voice.marytts/3.0.0.201912221328] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.commons.collections.map)(version>=3.2.0)(!(version>=4.0.0)))"]]
```

**Comment by wborn** [comment]
It certainly looks so because it is in the [dependency management section](https://github.com/marytts/marytts/blob/31c10d5bd47f08b24034c81635507a9b5a404a3a/pom.xml#L197-L201) of the POM. Did you embed it for other add-ons having this dependency? I personally don't use MaryTTS. I only test if it still works when I submit PRs e.g. to improve build times (https://github.com/openhab/openhab-addons/pull/6482).

**Comment by cweitkamp** [comment]
Yes, I did. See Java Sound Support:

https://github.com/openhab/openhab-addons/blob/bc212aec7a7c52e1bd9c2e6c638bfe63e870d3a8/bundles/org.openhab.io.javasound/pom.xml#L16-L21

https://github.com/openhab/openhab-addons/blob/bc212aec7a7c52e1bd9c2e6c638bfe63e870d3a8/bundles/org.openhab.io.javasound/src/main/feature/feature.xml#L7

I will add it for marytts too and will update to version 3.2.2 to superseed and fulfill #6483.

**Pull request merged**
