### PR TITLE
[denonmarantz] Fix blocking initialization

### LINKED ISSUE #16806: [denonmarantz] Auto-configuration is blocking `initialize`
The binding provides auto-configuration that will try to detect protocol, port and number of zones.

The way this is implemented is by calling a method from initialize:

https://github.com/openhab/openhab-addons/blob/bae5b0c9395cd378c989dd813063ff8be3bbb54e/bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java#L306-L317

This method will then perform up to three blocking calls with a timeout of three seconds each:

https://github.com/openhab/openhab-addons/blob/bae5b0c9395cd378c989dd813063ff8be3bbb54e/bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java#L205-L304

This can potentially block `initialize` for up to nine seconds on first initialization, and at least six seconds for unresponding hosts.

## Expected Behavior

The framework expects `initialize()` to be non-blocking and to return quickly. See https://www.openhab.org/docs/developer/bindings/#startup

## Current Behavior

When creating a Thing with an IP address that doesn't exist on the network (similar to a powered off receiver):

```
2024-05-26 21:22:17.112 [DEBUG] [internal.handler.DenonMarantzHandler] - Trying to auto-detect the connection.
2024-05-26 21:22:20.116 [DEBUG] [internal.handler.DenonMarantzHandler] - Error when trying to access AVR using HTTP on port 80.
java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.jetty.client.HttpDestination$RequestTimeouts.onExpired(HttpDestination.java:631) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.client.HttpDestination$RequestTimeouts.onExpired(HttpDestination.java:614) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeouts.onTimeoutExpired(CyclicTimeouts.java:110) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeouts.access$100(CyclicTimeouts.java:50) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeouts$Timeouts.onTimeoutExpired(CyclicTimeouts.java:196) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:298) ~[bundleFile:9.4.54.v20240208]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2024-05-26 21:22:22.114 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'denonmarantz:avr:53596abe49' takes more than 5000ms.
2024-05-26 21:22:23.119 [DEBUG] [internal.handler.DenonMarantzHandler] - Additionally tried to connect to port 8080, this also failed. Reverting to Telnet mode.
java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.jetty.client.HttpDestination$RequestTimeouts.onExpired(HttpDestination.java:631) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.client.HttpDestination$RequestTimeouts.onExpired(HttpDestination.java:614) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeouts.onTimeoutExpired(CyclicTimeouts.java:110) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeouts.access$100(CyclicTimeouts.java:50) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeouts$Timeouts.onTimeoutExpired(CyclicTimeouts.java:196) ~[bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:298) ~[bundleFile:9.4.54.v20240208]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2024-05-26 21:22:23.124 [DEBUG] [internal.handler.DenonMarantzHandler] - Configuring zone channels
2024-05-26 21:22:23.124 [DEBUG] [internal.handler.DenonMarantzHandler] - No zone channels have been added
2024-05-26 21:22:23.124 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone3#volume
2024-05-26 21:22:23.124 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone4#volume
2024-05-26 21:22:23.124 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone4#input
2024-05-26 21:22:23.124 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone4#volumeDB
2024-05-26 21:22:23.125 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone4#mute
2024-05-26 21:22:23.125 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone3#mute
2024-05-26 21:22:23.125 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone3#input
2024-05-26 21:22:23.125 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone3#volumeDB
2024-05-26 21:22:23.125 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone4#power
2024-05-26 21:22:23.126 [TRACE] [internal.handler.DenonMarantzHandler] - Removed channel zone3#power
2024-05-26 21:22:23.140 [DEBUG] [elnet.DenonMarantzTelnetClientThread] - Denon listener created
```

## Possible Solution

The auto-configuration phase could be scheduled to be executed in a separate thread.

## Steps to Reproduce

See above.

## Your Environment
* Version used: 4.2 snapshot 4096

### PR DESCRIPTION
**Pull request by jlaur**
Resolves #16806

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks, very clean.

I would consider this for backporting, agree?

**Comment by jlaur** [comment]
> I would consider this for backporting, agree?

Probably not, since it's not zero-risk, and I don't think it's critical - it's been like this for years. So I'd like to run it on my production system for some time to confirm there are no side-effects. I successfully tested two scenarios briefly:
1. Adding a Thing with non-existing IP address to reproduce timeouts/failing auto-configuration.
2. Initializing a working Thing for my receiver (i.e. skipping auto-configuration).

**Comment by jlaur** [comment]
@lsiepel - and now I realized I need to check what happens in case of `dispose` before the auto-configuration completes.

**Comment by lsiepel** [comment]
> @lsiepel - and now I realized I need to check what happens in case of `dispose` before the auto-configuration completes.

I guess you want to catch the interruption exception and quit/return immediate and not stat the second telnet connection

**Comment by jlaur** [comment]
> > @lsiepel - and now I realized I need to check what happens in case of `dispose` before the auto-configuration completes.
> 
> I guess you want to catch the interruption exception and quit/return immediate and not start the second telnet connection

`InterruptedException` is only thrown when the thread is interrupted. 😉 The issus is it was wild-running without a handle, and as a result "Handler DenonMarantzHandler tried updating the thing status although the handler was already disposed." and it kept trying to connect after it should have been disposed. I will need to check exactly why, because something else might also be going on.

I now did a change so the initialization job is scheduled and can be interrupted. It seems this also resolved the issue with endless reconnects. I will do a few more tests and checks tomorrow, so keeping as draft for now.

**Comment by jlaur** [comment]
> I now did a change so the initialization job is scheduled and can be interrupted. It seems this also resolved the issue with endless reconnects. I will do a few more tests and checks tomorrow, so keeping as draft for now.

I had another look to figure out what was going on when creating a Thing with invalid IP address and quickly deleting the Thing again. It was more or less as expected: The initialization thread was not interrupted by `dispose`. Thus the initialization thread would call `createConnection` **after** `dispose` had called `connector.dispose()`. So indeed it is resolved with the change I made yesterday.

**Pull request merged**
