### PR TITLE
[openhab-cloud] Fixes Jetty upgrade issue

### LINKED ISSUE #10470: [openhab-cloud] Corrupted REST response after update to nightly
After updating to the nightlies build,  integrations using the openhab-cloud  have became unstable, this includes our mobile app, OH3 UI and our Alexa integrations.  Its seems like the response to at least GET requests is returning either a duplicate response, or mid way through the response get repeated causing invalid JSON.  its feels almost like there is some type of struct or buffer that is not being flushed/cleared, or the index of where we are in that buffer is off or gets reset.    I am still looking at this, but the only significant  change to that i can see is https://github.com/openhab/openhab-core/pull/2264  , @wborn could there be anything with that upgrade you could see might cause this?  Of course this could be my system, so i would appreciate  if someone else could load `/rest/items` or the  load OH3 app using  our cloud service and confirm.  I'll continue to look at it as well.

### PR DESCRIPTION
**Pull request by digitaldan**
This removes the ResponseListener class and replaces it with lambda functions for the various Jetty response listeners. This seems to fix our duplicate onContent issue in #10470 , although i'm not at all clear why.
Fixes #10470

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by wborn** [comment]
Thanks for looking into this! I don't have a good explanation, but I it looks like there is no synchronization on the creation of the `CloudClient` in [CloudService.modified](https://github.com/openhab/openhab-addons/blob/223a7459465b0ebc994a1846a549304311ec6c0e/bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java#L231-L249). If that's the case then in theory if the `modified` method is called in quick succession, you might end up with 2 clients both handling requests.

**Comment by digitaldan** [comment]
Yeah,  i was able to confirm this is happening in a single instance of that ResponseListener inner class, and logging shows only one instance of the client is being created.  The pattern that led me down this path was that while we create one instance, we register it as a callback 4 times, i thought maybe Jetty had a bug where somehow it errantly called the onContent in 2 different listeners.  I did spend a little time going through the Jetty source code, but nothing stood out to me.

You do bring up an excellent point about an unrelated issue.   I can see in our cloud logs that occasionally we have 2 cloud client instances  from the same OH trying to connect, as one succeeds, the other one disconnects and then reconnects, which bumps the other one... this continually goes back and forth.   I have never been able to recreate it, but maybe  your observation  about not synchronizing could explain it.

**Comment by wborn** [comment]
After writing a unit test I could easily reproduce the issue. It is likely caused by https://github.com/eclipse/jetty.project/commit/d39f19cc230cabd59d1fd11d4d9f666b08c34b51.

The original `ResponseListener` would get registered twice as a `DemandedContentListener`. If you set a break point you can see it iterate over all `DemandedContentListener`s in `org.eclipse.jetty.client.ResponseNotifier.notifyContent(Response, ObjLongConsumer<Object>, ByteBuffer, Callback, List<DemandedContentListener>)`.

The reason seems to be that a `DemandedContentListener` (org.eclipse.jetty.client.api.Response.ContentListener) is created when calling `.onResponseContent(..)`. But it also registers a `DemandedContentListener`  listener when `.send(listener)` is called because the `ResponseListener` also implements `ContentListener` which extends `DemandedContentListener`.

**Review by wborn — APPROVED** [review]
Thanks for the fix!

**Comment by kaikreuzer** [comment]
Million thanks, @digitaldan! 🎉

**Pull request merged**
