### PR TITLE
[upnpcontrol] Remove org.apache.common

### PR DESCRIPTION
**Pull request by lsiepel**
- Remove dependency on org.apache.commons

Untested, minor refactoring only from code perspective

### CODE REVIEW

**Comment by mherwege** [comment]
Shouldn’t this be turned into a XmlUtils class in core now? See the original PR of this binding, and also a comment in the issue [here](https://github.com/openhab/openhab-addons/pull/7941#discussion_r453940350). The Sonos binding has the same requirement.

**Comment by mherwege** [comment]
And maybe have a look at [this](https://github.com/openhab/openhab-addons/issues/7722#issuecomment-679997251). I do think string escaping/unescaping is a general requirement when working with integrations, and a more general solution than doing it separately for every binding could make sense.

**Comment by lsiepel** [comment]
Agree, but after more than two and a half years these utility classes have not been added yet. So I decided to add these PR’s to atleast get this going. I hope it get’s merged and the discussion gets boosted at the topic you mentioned. 
From here it should not be hard to consolidate these utility classes to core. Hope you can confirm the implementation looks fit.

**Comment by mherwege** [comment]
Yes, LGTM

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
