### PR TITLE
[homeconnect] Home Connect Binding initial contribution

### PR DESCRIPTION
**Pull request by bruestel**
**Home Connect Binding**

The binding integrates the Home Connect system into openHAB. It uses the Home Connect API to connect to household devices (mainly Bosch and Siemens).

- Home Connect homepage: [https://www.home-connect.com](https://www.home-connect.com)
- Home Connect developer site: [https://developer.home-connect.com](https://developer.home-connect.com)

A snapshot of the binding can be downloaded from the community page [Home Connect addon: Looking for beta testers](https://community.openhab.org/t/home-connect-addon-looking-for-beta-testers/49702),

### CODE REVIEW

**Comment by Hilbrand** [comment]
Thank you for your contribution! I was going to review. But saw you're using a number of libraries for functionality also provided by openHAB core. Like HttpClient and OAuth2 support. Did you know about that? Or checked if you could use that? It would make the code simpler I would guess. Take a look at the Spotify Binding for the HttpClient and OAuth2 usage.

**Comment by Hilbrand** [comment]
On second view. I guess you already looked at the Spotify binding :smile: But still my comment about usage of HttpClient and OAuth2 holds.

**Comment by bruestel** [comment]
> On second view. I guess you already looked at the Spotify binding  But still my comment about usage of HttpClient and OAuth2 holds.

Yes I had a look at the Spotify binding :-D
Helped me to implement the DynamicStateProvider and integrate a servlet for oAuth stuff. 

I had a look at the OAuth2/HttpClient component but it didn't fit. I could have a second look but I would like to integrate the binding into the official repository first. The current authentication/token flow is tested by a bunch of beta users (see community link) and I don't want to touch it again. If I do it will postpone the release again.

**Comment by Hilbrand** [comment]
> I had a look at the OAuth2/HttpClient component but it didn't fit.

Do you remember what was causing it not to fit?

> I would like to integrate the binding into the official repository first. ... If I do it will postpone the release again

We also would like to have it migrated. But this would require the binding to be reviewed. And I'm not sure why I want to review code that is redundant and will be replaced later and I have to review again. What is the guarantee it will be rewritten to use the internal OAuth2 service? When integrating bindings other things become more relevant than only just merging code that works. We look at the big picture and try to get a system that works best for everyone. Part of this is to use as much as possible standardized services. This makes handling the code more easily and provide better maintainability. Also this takes into account, once the code is merged and you would move on and have no time to maintain it, someone else has to do it. And than having a standardized method will help. So please, do have a second look and let us know what you can do or if we can help making this happen.

**Comment by bruestel** [comment]
I will  have a second look. Got your point. I think it would be good to document it somewhere on the openHAB homepage. To give that hint to other developers before they start to implement oAuth stuff.

I started looking at the Spotify source code and two questions came up. Can someone please help me answering the questions:

1. `OAuthClientService#getAccessTokenResponseByAuthorizationCode(String authorizationCode, String redirectURI)` Why do I need to pass a `redirectURI` parameter? Shouldn't it be optional? In my case I need to get the current URI from the `HttpServletRequest` object and pass it to the method. I don't want the user to setup that URI in openHAB as he or she already defined it at the Home Connect developer page.

2.  Is `OAuthClientService#getAccessTokenResponse` synchronized? Don't think so but I would like to be certain. Would help me to get rid of a couple of lines of code. I'm using multiple of connection threads (due to Server-Sent Events) and if the oAuth token expires all threads start refreshing the the token at the same time. In my current implementation I used synchronize to prevent it. 
 
Thanks,
Jonas

**Comment by Hilbrand** [comment]
> Why do I need to pass a redirectURI parameter? Shouldn't it be optional?

It's an optional argument as defined by the OAuth2 specification. Dependent on what the authorization provider requires. With the Spotify Api it's a requirement. But if it's not required you can simply pass `null` as argument to the method.

> Is OAuthClientService#getAccessTokenResponse synchronized?

No it doesn't seem to be synchronized. Only the part where the key is stored and retrieved from storage. But that wouldn't prevent from making multiple calls. In the Spotify Binding I haven't synchronized it as it's not called by multiple threads in general at the same time. Although, it would make it a bit cleaner if it's synchronized.

**Comment by bruestel** [comment]
> It's an optional argument as defined by the OAuth2 specification.

Parameter is nonnull. Passing null doesn't work.

**Comment by Hilbrand** [comment]
> Parameter is nonnull. Passing null doesn't work.

Yes you're right. I was looking at the wrong method (`getAuthorizationUrl`) that actually does have the parameter Nullable. So I've created a pr to fix this: https://github.com/openhab/openhab-core/pull/1073

**Comment by Hilbrand** [comment]
Hi @bruestel The pr related to the null check has been merged in openhab-core. So you should be able to use it in your binding now.

**Comment by bruestel** [comment]
Hi @Hilbrand,
thank you. I would like to support openHAB 2.4 too, then I would still need to pass the parameter right?

**Comment by Hilbrand** [comment]
Yes for openHAB 2.4 support this would still be needed. However I quickly checked for other possible changes. and in the review I'll ask for changing the `HomeConnectDynamicStateDescriptionProvider` to use `BaseDynamicStateDescriptionProvider` (See this commit: https://github.com/openhab/openhab2-addons/pull/5954/files) But that change isn't compatible with 2.4 either.

For the Spotify binding I created a separate '2.3 version` branch and kept everything as is in there as the feature functionality was complete. (Also the custom OAuth2 implementation an earlier version contained and provided this version to the users until some time after 2.4 was released) and I continued the work on the pull request branch to use the openHAB OAuth2 service.

A comment regarding the code. I see some code duplication and code in classes I wouldn't expect. Do you appreciate any feedback that?

**Comment by bruestel** [comment]
Hi,

I've updated my pull request. 

**Summary**
- use `OAuthClientService` instead of own implementation
- added logger UI
- fixed checkstyle warnings
- improved README
- removed duplicated code
- cache API responses
- removed internal libraries and moved to maven dependency management
- added information about 3rd party licenses

**Comment by bruestel** [comment]
Will push again, if master builds again. :-(

**Comment by bruestel** [comment]
@FlorianSW If you need help setting up the simulator environment, please let me know. I'm glad to help.

**Comment by bruestel** [comment]
Created a new PR https://github.com/openhab/openhab-addons/pull/6794

**Pull request closed without merging**
