### PR TITLE
[jsscripting] Use `application/javascript` as MIME type

### PR DESCRIPTION
**Pull request by florian-h05**
With openHAB on the horizon and the NashornJS engine available as an addon with MIME type `application/javascript;version=ECMAScript-5.1`, GraalJS should take over the `application/javascript` MIME type.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jlaur I've added a unit test that calls the `GraalJSScriptEngineFactory`, but the test is failing before it even starts and I don't understand why. Can you please help me?

**Comment by J-N-K** [comment]
Please make sure that `application/javascript;version=ECMAScript-2021` still works. Otherwise user would have to re-create all UI based rules.

**Comment by florian-h05** [comment]
@J-N-K 

I was not sure if we want to keep that backward compatiblity (FYI: #14093 upgrades to ECMA2022), I had it in but removed it then. I'll just revert the removal. FYI, I have a UI PR that will add a menu to change the script type: https://github.com/openhab/openhab-webui/pull/1601.

**Comment by florian-h05** [comment]
@J-N-K Can you help me with the failing unit test? It's failing before it even starts ...

**Comment by J-N-K** [comment]
I guess it's the same as [here](https://stackoverflow.com/questions/74208293/maven-error-failed-to-run-the-ecj-compiler-unrecognized-option-patch-modul), but I have no idea why it failes in `automation.jsscripting` but not in `binding.dmx`.

**Comment by florian-h05** [comment]
The test is nearly the same as for [JS Scripting (Nashorn)](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.automation.jsscriptingnashorn/src/test/java/org/openhab/automation/jsscriptingnashorn/NashornScriptEngineFactoryTest.java) and there it works. As no one has an idea why it fails, I’ll remove it.

**Comment by J-N-K** [comment]
It‘s probably related to something on the classpath.

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
