### PR TITLE
[hpprinter] Update readme.md file to include example items configuration

### PR DESCRIPTION
**Pull request by stuart475898**

### CODE REVIEW

**Comment by Cossey** [comment]
Thanks @stuart475898 for updating the Readme on my binding. I see you're a first time contributor, welcome!

You need to sign off your commits before they can be merged (click the Checks tab above and it will tell you how to sign commits using git). When you sign your old commits you'll need to force push them back to the repo you opened the PR from.

Additionally, please also include a short description in the PR, even if its just a repeat of the commit history description to make it easy for the reviewers.

**Comment by J-N-K** [comment]
Another thing: please also add at least the thing configuration.

**Comment by kaikreuzer** [comment]
@stuart475898 Would you be so kind and address the comments above? Would be very much appreciated!

**Comment by Cossey** [comment]
Hey all: I planning on making some additional tweaks to the binding soon, now that the most recent PR was merged. When I do this I'll improve the documentation further based on Stuarts suggestion and close this if we don't hear back by then.

**Comment by Cossey** [comment]
I am closing PR since it has gone stale. The suggested changes have been implemented in PR #7637.

**Pull request closed without merging**
