### PR TITLE
do not apply spotless to footer.xml

### PR DESCRIPTION
**Pull request by kaikreuzer**
Not ideal, but it fixes the build.
I am not aware of an easy way to disable spotless on a given file/project.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by J-N-K** [comment]
Why was 

https://github.com/openhab/openhab2-addons/blob/2d957b7cdab75827c7995c380a16368428167003/pom.xml#L552

changed to 

https://github.com/openhab/openhab-addons/blob/1f7da6b6698365c6bf7c5a3ee124463e84a116bb/pom.xml#L551

I would guess that is the reason for the failing exclusion.

**Comment by kaikreuzer** [comment]
I assume that is a [question to yourself](https://github.com/openhab/openhab2-addons/commit/105e1b2b3b4bad1d59c2d0d97712429a2e4dbdca)...?

**Comment by kaikreuzer** [comment]
I have fixed that - thanks for the analysis!

**Comment by wborn** [comment]
It's probably because https://github.com/openhab/openhab2-addons/commit/ff3b37e77403aebeab1e50e397b9dc609634af16#diff-600376dffeb79835ede4a0b285078036 never got cherry picked.

**Review by wborn — APPROVED** [review]

**Comment by andrewfg** [comment]
@kaikreuzer I just want to point out that the current Spotless settings produce tons of NPE warnings on JUnit test suites with code as follows...

```
Aardvark aardvark = createAardvarkEating("termites");
assertNotNull(aardvark);
assertEquals("termites", aardvark.isEating());
```

Spotless gives an NPE warning on `aardvark.isEating()` in spite of the preceding `assertNotNull(aardvark)` which should suppress it. This was not the case with prior Spotless settings. 

PS I am allergic to the thought of having to rewrite my test suites with `if (aardvark != null) {}` throughout ;)

**Comment by wborn** [comment]
You can use `org.eclipse.jdt.annotation.Checks.assertNonNull(T...)` instead which will do the null check and return a `@NonNull` value. The class has many other useful checks that with using the null annotations.

**Comment by andrewfg** [comment]
As I said, @wborn, I am NOT asking you to tell me how to rewrite old code! I am reporting an ISSUE with the new Spotless settings, that IMHO should be changed to prevent such warnings newly appearing on older but perfectly valid code, that used to pass the tests perfectly!

**Comment by wborn** [comment]
This has nothing to do with Spotless. The code was probably flawed all along and it only now shows with command line Maven builds because the compiler was updated to a recent version that is also used in Eclipse, see https://github.com/openhab/openhab-addons/pull/8636. It used to report different errors/warnings in Eclipse and command line builds which got fixed by that PR.

**Comment by andrewfg** [comment]
Wouter, you are right that it has nothing to do with Spotless. Sorry, I apologise for my mistake.

You are also right that it is due to the compiler settings.

But you are wrong to say that this [code](https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test) was "flawed al along". It fully passed the tests (and IMHO correctly so) under previous build systems, and so it should IMHO pass under the current one.

**Comment by wborn** [comment]
I also said "probably" because there was no reference to actual code. :wink:

But looks like you run into a known limitation of the null analysis where it cannot infer that some method (`assertNotNull`) does a null check on a `@Nullable` variable (`NeoHubInfoResponse.createDeviceData`) and would thus throw an exception. That's where `Checks.requireNonNull` can help without impacting code too much.

**Comment by andrewfg** [comment]
Ok

**Comment by wborn** [comment]
Sometimes you have to help the analysis a bit to overcome these limitations. The flip side of the coin is that if it would be silent in these cases, you might end up with actual NPEs. If it were even possible to fully analyze these scenario's, it might take so much time to analyze, you would stop using the analysis because it becomes unworkable. :wink:

**Comment by andrewfg** [comment]
I hear what you say..

.. but this "problem" relates to JUnit test code that explicitly forces edge scenarios to Assert() that methods don't return unforeseen nulls; so it is irritating that the compiler would be more satisfied if the test code would not force edge tests (i.e. not exist).

=> To put it bluntly: I could just delete the "bad" JUnit tests to make the compiler happy, but that would mean that the runtime code would be riskier than it would otherwise be. Grrr!

**Pull request merged**
