### PR TITLE
[openwebnet] add default translations

### PR DESCRIPTION
**Pull request by mvalla**
As requested [in this other PR](https://github.com/openhab/openhab-addons/pull/12483#issuecomment-1075576483), this new PR adds default translations to the openwebnet binding.
Translations to other languages will be completed using crowdin.

### CODE REVIEW

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by mvalla** [comment]
hi @jlaur despite this PR has been merged some days ago, I cannot find the new strings to be translated to Italian in crowdin. It looks to me [the file there does not contain](https://crowdin.com/translate/openhab-addons/1192/en-it?filter=basic&value=3) the strings generated my this PR.
Is there any further step to trigger the request for translation by crowdin?

**Comment by lolodomo** [comment]
Strange, we have apparently only 90 strings in Crowdin.

**Comment by mvalla** [comment]
@lolodomo and @jlaur : how [the new strings to be translated](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties) can now be added to crowdin?

**Comment by mvalla** [comment]
@lolodomo or @jlaur any idea why the new string added with this PR do not show up on crowdin interface? 
Shall I open a new issue for this? 
I think would be good to have strings translated for the upcoming 3.3 release.

**Comment by lolodomo** [comment]
I don't know, maybe we should trigger an update of the default translations agsin?

**Comment by wborn** [comment]
I just uploaded them manually @mvalla. Hopefully the sync works better next time.

**Comment by mvalla** [comment]
thanks @wborn now all the new strings are on crowdin

**Pull request merged**
