### PR TITLE
Prevent new lines in bundles/pom.xml when creating binding skeleton

### LINKED ISSUE #13405: Script to create new binding skeleton: problem with file bom/pom.xml
The script to create a new binding skeleton is generating a lot of changes in the file bom/pom.xml. Only one line should be added (for the new binding) but in fact it generates a lot of more changes, certainly for formatting reason.

Tested with the Windows bat command file.

### PR DESCRIPTION
**Pull request by wborn**
Downgrades the Maven archetype plugin as workaround for:

* https://issues.apache.org/jira/browse/ARCHETYPE-584
* https://issues.apache.org/jira/browse/ARCHETYPE-587

Fixes #13405

### CODE REVIEW

**Comment by lolodomo** [comment]
That is very strange. Even without your changes, I can no more run the command with success, some files are not updated and some warnings are shown. The result is similar with your changes:
```
$ ./create_openhab_binding_skeleton.cmd test Laurent lolodomo
[INFO] Scanning for projects...
[INFO]
[INFO] ---< org.openhab.addons.bundles:org.openhab.addons.reactor.bundles >----
[INFO] Building openHAB Add-ons :: Bundles 3.4.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.2.1:generate (default-cli) > generate-sources @ org.openhab.addons.reactor.bundles >>>
[WARNING] The POM for org.eclipse.orbit.bundles:net.i2p.crypto.eddsa:jar:0.3.0.v20220506-1020 is missing, no dependency information available
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java) @ org.openhab.addons.reactor.bundles ---
[INFO]
[INFO] --- directory-maven-plugin:1.0:directory-of (directories) @ org.openhab.addons.reactor.bundles ---
[INFO] Directory of org.openhab.addons:org.openhab.addons.reactor set to: D:\dev\openhab3\git\openhab-addons
[INFO]
[INFO] --- spotless-maven-plugin:2.0.3:check (codestyle_check) @ org.openhab.addons.reactor.bundles ---
[INFO] Spotless check skipped
[INFO] Spotless check skipped
[INFO] Spotless check skipped
[INFO] Spotless check skipped
[INFO]
[INFO] <<< maven-archetype-plugin:3.2.1:generate (default-cli) < generate-sources @ org.openhab.addons.reactor.bundles <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.2.1:generate (default-cli) @ org.openhab.addons.reactor.bundles ---
[INFO] Generating project in Interactive mode
[WARNING] No archetype found in remote catalog. Defaulting to internal catalog
[INFO] Archetype repository not defined. Using the one from [org.openhab.core.tools.archetypes:org.openhab.core.tools.archetypes.binding:3.3.0-SNAPSHOT] found in catalog local
[INFO] Using property: vendorName = openHAB
[INFO] Using property: namespace = org.openhab
[INFO] Using property: author = Laurent
[INFO] Using property: githubUser = lolodomo
[INFO] Using property: bindingId = test
[INFO] Using property: bindingIdCamelCase = test
[INFO] Using property: startYear = 2010
[INFO] Using property: groupId = org.openhab.binding
[INFO] Using property: artifactId = org.openhab.binding.test
[INFO] Using property: version = 3.4.0-SNAPSHOT
[INFO] Using property: package = org.openhab.binding.test
Confirm properties configuration:
vendorName: openHAB
namespace: org.openhab
author: Laurent
githubUser: lolodomo
bindingId: test
bindingIdCamelCase: test
startYear: 2010
groupId: org.openhab.binding
artifactId: org.openhab.binding.test
version: 3.4.0-SNAPSHOT
package: org.openhab.binding.test
 Y: : Y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: org.openhab.core.tools.archetypes.binding:3.4.0-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: org.openhab.binding
[INFO] Parameter: artifactId, Value: org.openhab.binding.test
[INFO] Parameter: version, Value: 3.4.0-SNAPSHOT
[INFO] Parameter: package, Value: org.openhab.binding.test
[INFO] Parameter: packageInPathFormat, Value: org/openhab/binding/test
[INFO] Parameter: package, Value: org.openhab.binding.test
[INFO] Parameter: author, Value: Laurent
[INFO] Parameter: groupId, Value: org.openhab.binding
[INFO] Parameter: namespace, Value: org.openhab
[INFO] Parameter: startYear, Value: 2010
[INFO] Parameter: artifactId, Value: org.openhab.binding.test
[INFO] Parameter: bindingId, Value: test
[INFO] Parameter: vendorName, Value: openHAB
[INFO] Parameter: githubUser, Value: lolodomo
[INFO] Parameter: bindingIdCamelCase, Value: test
[INFO] Parameter: version, Value: 3.4.0-SNAPSHOT
[INFO] Parent element not overwritten in D:\dev\openhab3\git\openhab-addons\bundles\org.openhab.binding.test\pom.xml
[WARNING] Don't override file D:\dev\openhab3\git\openhab-addons\bundles\org.openhab.binding.test\pom.xml
[INFO] Executing META-INF/archetype-post-generate.groovy post-generation script
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/Laurent/.m2/repository/org/codehaus/groovy/groovy-all/2.4.16/groovy-all-2.4.16.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Add new bundle after: org.openhab.binding.tesla
Added github user to CODEOWNERS file
Added bundle to bom pom
Fix bundle parent pom.xml

*********************************************

 Start your new binding on a new git branch:

 git checkout -b test

*********************************************

[INFO] Project created from Archetype in dir: D:\dev\openhab3\git\openhab-addons\bundles\org.openhab.binding.test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:24 min
[INFO] Finished at: 2022-09-23T21:41:02+02:00
[INFO] ------------------------------------------------------------------------
        1 fichier(s) copié(s).

Laurent@VivoMini MINGW64 /d/dev/openhab3/git/openhab-addons/bundles (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   pom.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        org.openhab.binding.test/

no changes added to commit (use "git add" and/or "git commit -a")

```
I say it is strange because I am sure to used this script about one year ago to create the skeleton of the ecowatt binding.

**Comment by wborn** [comment]
Maybe try running the .sh script in the mingw shell and the .cmd script in a Windows shell?

**Comment by wborn** [comment]
Today I spent some time in Windows and it worked fine:

windows

**Comment by jlaur** [comment]
@lolodomo - any update on the issues you had?

**Comment by lolodomo** [comment]
I have no idea why it was not working for me. At this time, it was not working better even without this change. So maybe something specific to my dev environment. 
If @wborn is confident, let's merge the change.

**Comment by lolodomo** [comment]
Are you able to try by yourself on Windows @jlaur ?

**Comment by jlaur** [comment]
@lolodomo - I just tested the .cmd version in Windows from a command prompt, and unfortunately I'm seeing the same result as you, i.e. `pom.xml` is not updated (except reformatting of line 2-3).

**Comment by wborn** [comment]
Well let's wait for the issue to be fixed in the Maven plugin and keep adding review comments for this. :wink:

**Pull request closed without merging**
