### PR TITLE
[transform.exec] Fix service whitelisting

### PR DESCRIPTION
**Pull request by J-N-K**
Reported on the german openHAB forum.

### CODE REVIEW

**Comment by jlaur** [comment]
Déjà vu comment for others: Same fix as in #14522. It seems we have duplicated code in exec **binding** and exec **transform**. So also a regression of #14004.

**Review by jlaur — APPROVED** [review]
Thanks for the fix!

**Comment by J-N-K** [comment]
The code-duplication is unfortunately necessary because exec transformation and binding are independent.

**Comment by jlaur** [comment]
> The code-duplication is unfortunately necessary because exec transformation and binding are independent.

I understand, I just wanted to share this information as I was not previously aware. I guess the only current way to share that code would be to bundle them, but that would probably be quite counter-intuitive/undesirable. I didn't check how much code is duplicated.

**Pull request merged**
