### PR TITLE
[mybmw] API not working anymore because of Captcha request

### PR DESCRIPTION
**Pull request by martingrassl**

### CODE REVIEW

**Comment by martingrassl** [comment]
I didn't commit any relevant changes yet, so no need to review right now!

**Comment by lsiepel** [comment]
You created this empty PR, perfectly fine, just wondering if you want this in 4.3.0 then you got 2 more days :-)

**Comment by martingrassl** [comment]
Hi @lsiepel , does that mean that in 2 days we will get the final version already? Pew, I tried my best, but I'm running from one issue into the next one, it's not so simple... close to the end, hope I can make it tomorrow

**Comment by lsiepel** [comment]
> Hi @lsiepel , does that mean that in 2 days we will get the final version already? Pew, I tried my best, but I'm running from one issue into the next one, it's not so simple... close to the end, hope I can make it tomorrow

Sunday will be the last day we merge PR's, then there will be a code freeze for about a week.

**Comment by martingrassl** [comment]
@lsiepel , my git went crazy so I decided at this late time it is easier to create a new PR: https://github.com/openhab/openhab-addons/pull/17896/files. Thanks for your support, would be great if it could make it into 4.3.0

**Pull request closed without merging**
