### PR TITLE
Thing actions: add type in @ActionInput for generic class

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lsiepel** [comment]
Background or links are missing so i wonder why is it necesairy to add the full type namespace?

**Comment by jlaur** [comment]
I don't even see `type` mentioned in [the documentation](https://next.openhab.org/docs/developer/bindings/#actions-bound-to-a-thing), so I would also be interested in a reference to some information about this.

**Comment by jlaur** [comment]
Builds failed for unrelated reasons - see #17502.

**Comment by lolodomo** [comment]
You're right, full type namespace is not required. Here is the javadoc:

```
    /**
     * Specifies the acceptable data type for this {@link Input}. The value could be any string that makes sense for the
     * user, like a fully qualified name of a Java class, or a general description like "temperature", for example. The
     * value "*" means that all possible types are acceptable. The type is used to determine which {@link Output} can be
     * connected to this {@link Input} instance.
     */
    private String type;
```

I am finally even not sure that "type" is even required for simple class because the default is to retrieve the class canonical name:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/module/provider/AnnotationActionModuleTypeHelper.java#L123

What afraids me a little is what is done at this line:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/ConnectionValidator.java#L266
A class is searched from what is set in type parameter.
But I don't know exactly when this is run, but probably when using a thing action inside rules.

I will revert most of these changes.

**Comment by lolodomo** [comment]
Ok, PR is changed, I just kept addition of type parameter when expected in particular to get the dimension of a QuantityType at runtime.

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
