### PR TITLE
[hue] Update readme_v2.md

### PR DESCRIPTION
**Pull request by Gemertw**
Under demo.items the button-last-event channel was of the Number type. I have changed this to String. In the channels for devices section this was already corrected but is not 'live' yet?

### CODE REVIEW

**Comment by lolodomo** [comment]
@openhab/add-ons-maintainers : I have a doubt: can an item be linked to a trigger channel ?

**Comment by kaikreuzer** [comment]
No.

**Comment by lolodomo** [comment]
> No.

Thank you.

So the proper documentation fix will be to remove this item, not to fix its type.

**Comment by andrewfg** [comment]
> No

Umm. @kai I am not sure that your statement is correct. You can certainly link a a String item to a Trigger channel by means of a profile. I think this was what the creator of this PR is getting at. The button trigger channels produce a numeric value e.g. 1002 indicating the button id and the button press type, and this can be linked to a String type item via a profile.

**Comment by lolodomo** [comment]
But there is no profile used in the example.

**Comment by andrewfg** [comment]
> there is no profile used in the example.

Correct. So probably the correct answer for this PR is not to delete the example, but rather to modify it to also include a profile element in the item definition. Or?

**Comment by lolodomo** [comment]
Ok. 
I am myself not comfortable with profile. So a working example is welcome.

**Comment by andrewfg** [comment]
I am not currently at home, but from SSH into my system I can see that I do have String Items connected to such Trigger channels (by means of a profile) where the profile used is the default profile type (namely String) and since this is the default type, it does not need to be explicitly declared in the .items file entry. So -- in other words -- the changes to the example that are proposed here by the OP, do in fact work correctly. (Albeit perhaps not for the reasons that one might expect...)

```
String Dining_Room_Dimmer_Last_Event "Dining Room Dimmer Last Event" {channel="hue:device:g24:81d9a9d5-228c-45df-828e-0d224929b3d1:button-last-event"}
```

**Comment by Gemertw** [comment]
I am not using a profile either and have this working for several wall switches  in the same way as the example of @andrewfg.
Hence my request for this minor documentation change.
```String   WskmrKntrWallSwitch   "Dimmer switch state"  (PersistForRestore)    {channel="hue:device:huebridge2:WskmrWallSwitch:button-last-event"}```

**Review by andrewfg — APPROVED** [review]
As mentioned in the comments IMHO LGTM

**Comment by lolodomo** [comment]
https://www.openhab.org/docs/configuration/items.html#profiles

For `default` profile (type state):
> If you don't specify any Profile, this Profile will be used. For State Channels, this means that states and commands are just propagated from the Channel to the Item and vice versa without any changes. **For Trigger Channels, the Default Profile won't change anything on the Item.**

For `trigger-event-string` profile (type trigger):
> This Profile can be used to link a trigger channel to a String item. The item's state will be updated to the string representation of the triggering event (e.g. PRESSED).

Considering what you are noticing, the documentation is wrong ?

@openhab/core-maintainers : do you know where is the code in core framework that applies a profile per default to channel links ? We could check what is really implemented and then fix the documentation.

**Comment by andrewfg** [comment]
> Considering what you are noticing, the documentation is wrong ?

Yes I think so. For trigger channels it appears that it defaults to 'trigger-event-string' if no other profile is explicitly specified.

**Comment by andrewfg** [comment]
> do you know where is the code in core framework that applies a profile per default to channel links ?

@lolodomo the respective code line is [here](https://github.com/openhab/openhab-core/blob/ae85096e536ac83adf68524400f4fc523ec7acce/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java#L192) which confirms that the default profile for trigger channels is indeed `RIGGER_EVENT_STRING` and that therefore the doc is wrong.

@lolodomo if you agree with this, then I am happy to create a PR to fix the do. => Please let me know.

**Comment by lolodomo** [comment]
> > do you know where is the code in core framework that applies a profile per default to channel links ?
> 
> @lolodomo the respective code line is [HERE](https://github.com/openhab/openhab-core/blob/ae85096e536ac83adf68524400f4fc523ec7acce/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemProfileFactory.java#L192) which confirms that the default profile for trigger channels is indeed `TRIGGER_EVENT_STRING` and that therefore the doc is wrong.
> 
> @lolodomo if you agree with this, then I am happy to create a PR to fix the doc. => Please let me know.

Yes, please do it.

**Review by lolodomo — APPROVED** [review]

**Comment by andrewfg** [comment]
> Yes, please do it.

@lolodomo - done - see https://github.com/openhab/openhab-docs/pull/2141

**Pull request merged**
