### PR TITLE
[jsscripting] Extend mapping of openhab-js classes to native openHAB counterparts

### PR DESCRIPTION
**Pull request by florian-h05**
Addon part of https://github.com/openhab/openhab-js/issues/98.

### Description

This PR extends the target type mapping inside the JS Scripting addon to also translate the following openhab-js classes to their native openHAB Java counterparts when passing to Java methods:

- openhab-js `Item` -> `org.openhab.core.items.Item`
- openhab-js `Quantity` -> `org.openhab.core.library.types.QuantityType`

Regarding the updated bnd file: I hope I did the right (if I understood the docs correctly I did), but would be nice if one could have a look and verify that it is correct what I did.

### Testing

Use the following script to test:

```javascript
// Check JS-Item -> openHAB Item translation
actions.BusEvent.sendCommand(items.Temperature, "0 °C")

// Check JS-Quantity -> openHAB QuantityType translation
var QuantityType = Java.type('org.openhab.core.library.types.QuantityType')
QuantityType.valueOf('50 cm').add(Quantity('5 m'))
```

... or trust me given the simplicity of the code when comparing to the existing and well-working code.

### CODE REVIEW

**Comment by florian-h05** [comment]
@jlaur Can you please review this?

**Comment by jlaur** [comment]
@florian-h05 - I'm also not confident with bnd files, perhaps another @openhab/add-ons-maintainers could have a look?

**Comment by florian-h05** [comment]
@digitaldan Are you confident with bnd files?

**Comment by digitaldan** [comment]
> Are you confident with bnd files?

No, although the changes look pretty straight forward to me

**Review by wborn — APPROVED** [review]
LGTM!

**Pull request merged**
