### PR TITLE
[tado] Attempt to fix jenkins build errors.

### PR DESCRIPTION
**Pull request by cpmeister**
This merges the tado api-client subproject into the tado binding project. This should hopefully prevent jenkins from failing all the time on the tado binding.

Signed-off-by: Connor Petty <mistercpp2000+gitsignoff@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Funny, I was just trying to find a solution for the same issue as well. 
I reconfigured Jenkins to use our own openHAB Artifactory server as a mirror instead of going to JFrog directly.
https://ci.openhab.org/job/PR-openHAB-Addons/999 is just running with that approach.
Let's see how it turns out, but with 1000, you have clearly the better build number and I guess your approach anyhow makes sense.

**Comment by kaikreuzer** [comment]
Oops, my build failed as I missed to have snapshots available on the Artifactory url....

**Comment by kaikreuzer** [comment]
FTR: I reverted my changes on Jenkins as two other builds again failed with permission denied errors (which seem to have been passed through from jfrog).

**Comment by cpmeister** [comment]
Looks like it failed again. This time it couldn't resolve the swagger dependency.
Is jenkins preventing lookups in alternate repositories?
It seems like the specified repository is getting ignored.
```
  <pluginRepositories>
    <pluginRepository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </pluginRepository>
  </pluginRepositories>
```

**Comment by cpmeister** [comment]
I wonder if that was the issue all along...

**Comment by kaikreuzer** [comment]
> Is jenkins preventing lookups in alternate repositories?

That was only the case with my change that I put a mirror inbetween. As I reverted it, this should not be the case anymore - I'll retrigger the build and we will see.

**Comment by kaikreuzer** [comment]
Nonetheless, we usually do not want any additional repo references since they can be an issue for reproducible builds in the future. We already had the situation a couple of times that some 3rd party repo changed or disappeared, which makes it impossible to reproduce builds at a later time. We should thus rather try to move the required artifact to our bintray or have it made available on Maven Central.

**Review by kaikreuzer — APPROVED** [review]
Hooray, it succeeded - let's merge and see if it also helps the other PR builds 👍

**Comment by andrewfg** [comment]
@kaikreuzer / @cpmeister can you please explain what exactly you did with this Pull? I need to make a bug fix on this binding locally using the Eclipse IDE but it won't build any more. It does locally build using MVN, but I need to work interactively in the Eclipse IDE, and don't know what tweaks I need to make in the IDE so it will build. ??

**Comment by cpmeister** [comment]
@andrewfg The tado binding generates the code for the tado http api from the swagger specification file. Originally this api code was generated and put into another jar part of another pom file. This PR removed the need for a separate api jar by generating all of api code into the binding jar instead.

The reason I created this PR was solve jenkin's frequent failures in finding the pom file for the generated api jar. To avoid the issue of the pom file not getting found I removed the requirement of the pom file existing in the first place.

I don't know why it is failing in Eclipse now but I know that Eclipse had problems when I initially made the change as well. I'd try to help resolve the issue but for whatever reason I can't replicate the issues anymore. The binding seems to behave fine now for me in the IDE.

Have you tried adding the generated source directory to the projects build path? I think I had to do that initially after I removed the old pom file.

**Comment by andrewfg** [comment]
> Have you tried adding the generated source directory to the projects build path?

@cpmeister many thanks for the advice. Yes I solved it finally in Eclipse by manually creating a new Source Folder `src/main/api` and then adding the api java modules to it, as shown in the screenshot below. NOTE: obviously this manual step is not part of the pom structure, so it is not on GitHub; which means anyone wanting to compile the code in Eclipse in future will always have to do this same manual step themselves. (Which is why I have uploaded the screenshot here, for posterity..)

image

There was nevertheless still one lifecycle configuration error in Eclipse (below) that I could not resolve. However it did not prevent compiling the jar or debugging.

> Plugin execution not covered by lifecycle configuration: io.swagger:swagger-codegen-maven-plugin:2.3.1:generate (execution: default, phase: generate-sources)	pom.xml	/org.openhab.binding.tado	line 31	Maven Project Build Lifecycle Mapping Problem

**Comment by andrewfg** [comment]
**UPDATE RE: COMPILING TADO BINDING IN ECLIPSE**

The solution posted in my comment on 14 Jan has been superseded due to changes in the build system. Now to compile the Tado binding in Eclipse you have to manually create a new Source Folder `target/generated-sources/swagger/src/main/java` as shown in the screenshot below.

image

**Pull request merged**
