### PR TITLE
[jrubyscripting] Upgrade to JRuby 9.4.6.0

### PR DESCRIPTION
**Pull request by jimtng**

### CODE REVIEW

**Review by ccutrer — APPROVED** [review]

**Comment by lsiepel** [comment]
Release notes: https://github.com/jruby/jruby/releases/tag/9.4.6.0

**Comment by jimtng** [comment]
This got omitted from the M1 release note, perhaps because there were no labels. I've added `enhancement` label now

> For future upgrades it would be nice to have a small comment on the release (security, performance or functionality)

Could you please elaborate?

**Comment by lsiepel** [comment]
> This got omitted from the M1 release note, perhaps because there were no labels. I've added `enhancement` label now
> 
> > For future upgrades it would be nice to have a small comment on the release (security, performance or functionality)
> 
> Could you please elaborate?

A dependency update is transparant to the end-user and not something to mention in the release notes. Only if it brings functional improvements (new channels or significant performance improvements etc) or if it fxes notable bugs. If so, could you provide a description of the notable changes in the start post?

**Comment by jimtng** [comment]
An upgrade in the scripting engine/language version is always important to mention in the release note. There are numerous bug fixes, changes etc that may directly affect user's scripts.

The changes are all listed in the jruby's release notes. By mentioning the change in version, users can find out what's new from jruby's web site. A link can be included in the PR post although I didn't think it was necessary.

**Pull request merged**
