### PR TITLE
[spotify] Remove duplicate text and some spelling errors 

### PR DESCRIPTION
**Pull request by joepadmiraal**
…eadme

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Why is It marked as draft work on proves) ?

**Comment by joepadmiraal** [comment]
I moved it to draft to try to fix the DCO issue.
I've amended the commit message and moved the PR back to Open.
But I have no clue on how to re-trigger the DCO check.

**Comment by lolodomo** [comment]
As it is only minor changes in documentation, I will merge it even if DCO is wrong.

**Pull request merged**
