### PR TITLE
[lgwebos] Renew subscriptions for TV channel when source is changed

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
This PR fixed a problem that if your TV was not on TV tuner but for example on HDMI1 while the binding was started, then after switching to TV, the channels "channel name" and "channel number" were never updated.

**Comment by sprehn** [comment]
Wow, nobody has reportet this bug yet. I am able to reproduce it.
Ill see if I can come up with a simpler solution though. 
Wonder if it even still makes sense to subscribe only if a channel is linked. 
give me some time.

**Comment by sprehn** [comment]
when I subscribe to channels on HDMI I get  

Error: {"type":"error","id":14,"error":"500 Application error","payload":{"returnValue":false,"errorCode":"BROADCAST_ERROR_1003","errorText":"No information"}}

even if I now switch back to tv app and resubscribe, still same error.

have to reboot the tv on tvapp to make it work again.

Seems like subscribing to channel name and number is only supported when in TV app. 
problem is, what if the TV app changes name at some point.

Really seems like a bug in WebOS.

**Comment by lolodomo** [comment]
I did not see this error. I just enabled DEBUG level, is it enough to see it in logs ?

By the way, you're right, subscribing is useless when the application is not the TV app. I can easily update my PR, just one to change.
I think the id will never change, maybe the name.

**Comment by lolodomo** [comment]
The problem is that you have some apps which allow for example to open the image settings. With this app, I suppose that the channel subscription is still available.

**Comment by sprehn** [comment]
> I did not see this error. I just enabled DEBUG level, is it enough to see it in logs ?

yes, debug level is sufficient.

**Comment by sprehn** [comment]
similar issue discovered here in 2016: https://github.com/WeeJeWel/node-webos/issues/1

**Comment by sprehn** [comment]
have experimented on a fix as well here: https://github.com/sprehn/openhab-addons/tree/2.5.x-FixChannelSubscription with mentioned simplification to subscribe no matter if channel is linked or not.

however, I still get the mentioned error.

**Comment by sprehn** [comment]
Could you have a look at PR #7127
This includes my proposal to simplify BaseChannelHandler:refreshSubscription and also includes support for RefeshType on all readable channels.

**Comment by lolodomo** [comment]
I close this PR as it is covered in PR #7127

**Pull request closed without merging**
