### PR TITLE
[hue] Added support for publishing ChannelDescriptionChangedEvents

### PR DESCRIPTION
**Pull request by cweitkamp**
- Added service references to `DynamicStateDescriptionProvider` to support publishing `ChannelDescriptionChangedEvent`s

Depends on https://github.com/openhab/openhab-core/pull/1505 and https://github.com/openhab/openhab-core/pull/2410

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
@cweitkamp : you have to update this one to reflect your last changes in core.

**Comment by cweitkamp** [comment]
I know. Thanks for the reminder. Working on it.

**Comment by cweitkamp** [comment]
To finalize this task I introduced another method to publish a whole `StateDescriptionFragment` (see https://github.com/openhab/openhab-core/pull/2410).

**Comment by kaikreuzer** [comment]
Could you please apply spotless?

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
