### PR TITLE
[icalendar][WIP] add Filtered events item type

### PR DESCRIPTION
**Pull request by daMihe**
This PR adds a new thing type `filteredevents` to the iCalendar binding. It allows to get multiple events in a time frame and filtered by some event's text fields. It handles some use cases in issue #8022.

Technically the `calendar` item type was converted to a bridge and  `filteredevents` requires an `calendar` bridge. The conversion is done automatically by readding the item with same configuration and uid.

### CODE REVIEW

**Comment by daMihe** [comment]
As OpenHAB 3.0 is near and i don't think the PR is ready until then: should i already rebase and create a new PR?

**Comment by Hilbrand** [comment]
It's not possible to rebase yet as this binding is not yet on the master branch. Wait until we've migrated the 2.5.x bindings to the master branch and than rebase on master. You can than switch the pull request here to merge against master and push force the code back.

**Comment by daMihe** [comment]
> It's not possible to rebase yet as this binding is not yet on the master branch. Wait until we've migrated the 2.5.x bindings to the master branch and than rebase on master. You can than switch the pull request here to merge against master and push force the code back.

OK i'll wait.

**Comment by kaikreuzer** [comment]
Could you please re-create this PR against the `main` branch?
See https://github.com/openhab/openhab-addons/issues/8512. Thanks!

**Comment by daMihe** [comment]
I'll do in a few days.

**Pull request closed without merging**
