### PR TITLE
[jrubyscripting] clean up assignment of class objects

### PR DESCRIPTION
**Pull request by ccutrer**
pass the actual class objects through, and post-process in Ruby, to avoid the rescue nil -- and by extension, any issues with visibility into private objects from JRuby.

### CODE REVIEW

**Comment by ccutrer** [comment]
cc @jimtng @boc-tothefuture

**Comment by jimtng** [comment]
I've tested this change and it appears to be working.

**Review by boc-tothefuture — APPROVED** [review]
LGTM

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
