### PR TITLE
[insteon] remove optional from the description of network parameters

### PR DESCRIPTION
**Pull request by robnielsen**
Fixed documentation to match functionality.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I'd say this information is already covered by the "required" column. And the poll interval is not optional, it is just not required to specify it, but it is set in any case. I'd hence suggest to leave it as is.

**Comment by robnielsen** [comment]
@kaikreuzer. I made the change since it shows up like this in the UI:

image

Only port is required.

**Comment by kaikreuzer** [comment]
I'd then rather say that the "Optional..." must also be removed from the other parameter descriptions.
If it isn't clear to the user, which fields are optional, this should be addressed by the UI. We must not have all descriptions to be starting with "Optional" that does not make sense.

**Comment by robnielsen** [comment]
@kaikreuzer, I'm confused if you don't tell the user a parameter is optional in the UI, how will they know that it is?

**Comment by kaikreuzer** [comment]
Well, in openHAB 3 it tells you at least when leaving the fields:

Screenshot 2020-09-23 at 21 56 58

But I agree that it would be nicer to directly see, which parameters are required and which aren't.
@ghys Are there any standard mechanisms available in the framework to visualize required/optional fields?

**Comment by robnielsen** [comment]
I guess I still don't understand what the problem is with adding the word "Optional", it actually makes the description of the field more descriptive.

**Comment by ghys** [comment]
> Are there any standard mechanisms available in the framework to visualize required/optional fields?

https://github.com/openhab/openhab-webui/pull/349 will show the "Please fill out this field" message immediately without needing to focus on the field first, and will enforce parameters validation to be able to save.

**Review by kaikreuzer — CHANGES_REQUESTED** [review]
Great, thanks @ghys!

So I stick to my statement from above:

> I'd then rather say that the "Optional..." must also be removed from the other parameter descriptions.

**Comment by robnielsen** [comment]
OK, I'll make the change. I did notice this when I was trying to configure the Insteon binding with OH 3. Just to make it clear for end users, can we use stronger words for required fields? Maybe something like "This field must be filled".

**Comment by kaikreuzer** [comment]
> can we use stronger words for required fields? Maybe something like "This field must be filled".

"Please fill in this field" in bright red is not strong enough from your point of view?

**Comment by robnielsen** [comment]
> "Please fill in this field" in bright red is not strong enough from your point of view?

Not if you are color blind. From https://usabilla.com/blog/how-to-design-for-color-blindness/:

Don’t only rely on color to convey a message

**Comment by ghys** [comment]
It's the message the browser supplies when an input field is marked "required":
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required

It can be localized and everything, so I'm not willing to derive from that.

image

**Comment by robnielsen** [comment]
I've noticed many sites use a * to indicate required fields. This is from https://www.deque.com/blog/anatomy-of-accessible-forms-required-form-fields/: 

image

**Comment by robnielsen** [comment]
Or like I said above include Required in the text:
image

**Comment by robnielsen** [comment]
I created https://github.com/openhab/openhab-webui/issues/353 for the UI accessibility issues.

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
