### PR TITLE
[miio] Add support for device zhimi.humidifier.cb1 (Mi Air Humidifier)

### PR DESCRIPTION
**Pull request by Angerslave**
Mi Air Humidifier US version (zhimi.humidifier.cb1) is similar to other humidifiers with a couple of exceptions:
- No air quality index data
- trans_level is not supported
- Temperature property is different and returns °F

Thus separate file in the database to accommodate these differences. While most of PR is straightforward, transformation to °C directly is something I wonder if it should be done at binding level at all. I hope for advice of experienced OpenHAB developers in this topic.

Signed-off-by: Sergey Susikov <sergey.susikov@gmail.com>

### CODE REVIEW

**Comment by marcelrv** [comment]
LGTM. 
Thanks.
I think f to C or visaversa conversions can now be done in OH if I'm not mistaken.
If not, the place in the binding is "Conversions.java" you should in that case add another transformation/conversion and the conversion to your zhimi.humidifier.cb1.json file.

**Comment by skvalex** [comment]
@Angerslave Are you sure property "temperature" returns value in Fahrenheits? According to the [log file](https://community.openhab.org/t/xiaomi-mi-air-purifier-xiaomi-mi-io/34840/157) from the forum, the value is in Celsius, but it has another property "fahrenheit". I've also [posted](https://community.openhab.org/t/xiaomi-mi-air-purifier-xiaomi-mi-io/34840/158) a .jar there with the changes for this device, but no feedback received so far. Here's the diff:
[cb1.txt](https://github.com/openhab/openhab-addons/files/4176101/cb1.txt)

**Comment by Angerslave** [comment]
@marcelrv thank you for the review. As @skvalex mentioned, `temperature` does return Celsius data and there's a separate property that returns Fahrenheit. Hence removing the transformation. @skvalex, don't you mind if I include your changes in this PR?

**Comment by skvalex** [comment]
> @marcelrv thank you for the review. As @skvalex mentioned, `temperature` does return Celsius data and there's a separate property that returns Fahrenheit. Hence removing the transformation. @skvalex, don't you mind if I include your changes in this PR?

Of course, you can include it to your PR. I don't mind at all. Have you tested it with an actual device?

**Comment by Angerslave** [comment]
@skvalex I checked it with my cb1, `temperature` shows degrees C and `fahrenheit` shows respective F value. I'm not sure what modes enum changes as in Paper UI I can't see the effect.

@J-N-K kindly ask you to provide your feedback as a second reviewer. Thanks!

**Comment by J-N-K** [comment]
I think we should not add new channels for different units of the same value. Instead UoM should be used, so the user can select his favorite unit and the framework converts it accordingly.

**Comment by cpmeister** [comment]
What's the status of this?

**Comment by Angerslave** [comment]
> What's the status of this?

@cpmeister thanks for reminder, I removed Fahrenheit-related property and channel to prevent interface pollution as per @J-N-K comment.

**Pull request merged**
