### PR TITLE
[tesla] Adapt binding to changed API from Tesla backend

### PR DESCRIPTION
**Pull request by kaikreuzer**
This is https://github.com/openhab/openhab-addons/pull/14922 being backported to 3.4.x.

As it wasn't possible to cherry-pick or manually port the changes, I have sync'ed the complete binding code to the 3.4 branch (making sure that everything compiles).

It would probably be worthwhile if someone tests it, before it is being merged:

[org.openhab.binding.tesla-3.4.4-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/11380302/org.openhab.binding.tesla-3.4.4-SNAPSHOT.zip) (rename .zip to .jar)

### CODE REVIEW

**Comment by thekev** [comment]
Dropped the jar in my 3.4.3 installation and I have verified climate, odometer and state of charge are now updating. I don't use all the features though. I do have this warning message, which I do not find in logs going back about a week. I also updated from 3.4.1 to 3.4.3 just today, so don't have high confidence it is related to your changes.

```
[WARN ] [ore.internal.thing.ThingTypeResource] - Cannot find channel type: tesla:allowwakeup
```

**Comment by michi6383** [comment]
Very well done! Thank you! :)

**Comment by kaikreuzer** [comment]
@thekev No idea what this warning is about - there is indeed no such channel type. In case you have any old link to such a channel, please remove it and I'd hope the warning goes away.

FTR: I've just uploaded a newer version of the binding (as the zip above): It adds missing translations and brings discovery of new vehicles, even if they are asleep.

**Review by jlaur — APPROVED** [review]
Thanks for the fix and the backport!

**Comment by seliSoft** [comment]
@kaikreuzer Could you please take another look, it seems that details like BatteryLevel are not beeing updated (using 3.4.4.202305030715)
Thank you

**Pull request merged**
