### PR TITLE
[mqtt.homeassistant] add support for DeviceTrigger component

### PR DESCRIPTION
**Pull request by ccutrer**
A bit more work for this one, since this is the first trigger channel in the HASS binding

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@antroids : your review is welcome.

**Comment by lolodomo** [comment]
@ccutrer : isn't it covered by #14234 ?

**Comment by ccutrer** [comment]
Isn't what covered by #14234? This is #14234.

**Comment by lolodomo** [comment]
I wrote at the wrong place! I try again.

**Pull request merged**
