### PR TITLE
[tado] Add channel for PresenceState and support setting HOME/AWAY

### LINKED ISSUE #8826: [tado] Add Home/Away setting to be writable
Currently the tado Binding only supports **reading** the Home/Away status.

As of April 2020, the App now supports setting the Home/Away status manually, and it seems the Api now also supports setting the mode. 

Source: https://shkspr.mobi/blog/2019/02/tado-api-guide-updated-for-2019/#comment-149590

PUT request to:
https://my.tado.com/api/v2/homes/{homeId}/presenceLock

With a body like:
```json
{
"homePresence": "AWAY"
}
```

or `"HOME"` correspondingly.

Also used here:
https://github.com/equinoxefr/domoticz_scripts/blob/master/tado.py#L32

Unfortunately I'm not experienced with openhab addons, so it would be cool if someone could create a PR for this.
Maybe @wborn or @Hilbrand

### PR DESCRIPTION
**Pull request by Pro**
[tado] Add channel for PresenceState and support setting HOME/AWAY

This PR adds the support for reading the Tado Home Presence State (HOME/AWAY) and adds support for changing the HOME/AWAY state through OpenHAB.
Closes #8826 

Rebase of #8854 onto main branch.

@wborn I'm not the original author of this bundle. Therefore, I'm not sure how to get the additional api-client artifact to be built. Also I'm not a Maven expert... The pom.xml is in the `src/main/api` dir and I could only test the new bundle version when manually compiling the api. Can you push it to the openhab maven repo?

### CODE REVIEW

**Comment by wborn** [comment]
> Can you push it to the openhab maven repo?

I don't have these permissions but maybe @J-N-K build and uploaded the previous version in https://github.com/openhab/openhab-addons/pull/7006.

**Comment by Pro** [comment]
Maybe also @andrewfg could help, updating the api-client package?

**Comment by J-N-K** [comment]
Done

**Comment by andrewfg** [comment]
image

@wborn @J-N-K @Pro => I'm not sure if you need me to do anything more ?? => please let me know.

**Comment by Pro** [comment]
I'm not sure what caused Jenkins to fail. I cannot really find an error output somewhere.

**Comment by J-N-K** [comment]
The dependency-not-found result from the previous build was cached. This takes some time.

**Comment by Pro** [comment]
Seems the api-client maven is still not updated:

Build output:
> Failure to find org.openhab.binding.tado:api-client:jar:1.4.1

**Comment by andrewfg** [comment]
> Seems the api-client maven is still not updated:

Hmm. It is definitely in the [bintray](https://bintray.com/package/files/openhab/mvn/openhab-addons-deps?order=asc&sort=name&basePath=org%2Fopenhab%2Fbinding%2Ftado%2Fapi-client%2F1.4.1&tab=files) but maybe you need to check the naming in your pom dependency?

**Comment by Pro** [comment]
If I build it locally, it works (i.e., first `mvn install` in the api folder, then `mvn install` in the binding folder).
So I guess the naming should be correct.

**Comment by andrewfg** [comment]
Then it beats me; I guess @J-N-K needs to respond.

**Comment by J-N-K** [comment]
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.0.3:check (codestyle_check) on project org.openhab.binding.tado: The following files had format violations:
[ERROR] src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java
[ERROR] @@ -157,10 +157,9 @@
[ERROR] ········switch·(id)·{
[ERROR] ············case·TadoBindingConstants.CHANNEL_HOME_PRESENCE_MODE:
[ERROR] ················HomePresence·presence·=·new·HomePresence();
[ERROR] -················presence.setHomePresence(
[ERROR] -························command.toFullString().toUpperCase().equals("ON")·||
[ERROR] -································command.toFullString().toUpperCase().equals("HOME")·?
[ERROR] -································PresenceState.HOME·:·PresenceState.AWAY);
[ERROR] +················presence.setHomePresence(command.toFullString().toUpperCase().equals("ON")
[ERROR] +························||·command.toFullString().toUpperCase().equals("HOME")·?·PresenceState.HOME
[ERROR] +································:·PresenceState.AWAY);
[ERROR] ················try·{
[ERROR] ····················api.updatePresenceLock(homeId,·presence);
[ERROR] ················}·catch·(IOException·|·ApiException·e)·{
[ERROR] Run 'mvn spotless:apply' to fix these violations.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.tado
```

Please run `mvn spotless:apply -pl :org.openhab.binding.tado`

The new bundle is now correctly picked up.

**Comment by Pro** [comment]
I updated the PR with the spotless fixes, but now CI fails again:

> Failed to execute goal on project org.openhab.binding.tado: Could not resolve dependencies for project org.openhab.addons.bundles:org.openhab.binding.tado:jar:3.0.0-SNAPSHOT: Failure to find org.openhab.binding.tado:api-client:jar:1.4.1 in https://openhab.jfrog.io/openhab/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of openhab-release has elapsed or updates are forced -> [Help 1]

**Comment by J-N-K** [comment]
If this still does not work, I'll try to build locally and override Jenkins if that succeeds.

**Comment by J-N-K** [comment]
Build succeeds locally and library can be resolved. Must be some sort of caching issue.

**Pull request merged**
