### PR TITLE
[openweathermap] Prepare for shutdown of One Call API version 2.5

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Backport of commit by @florian-h05 from main branch to 4.1.x.

[openweathermap] Update README for shutdown of One Call API version 2.5 & Change default API version

Refs: #16665

@florian-h05 Seems I have to backport this to the 4.1.x branch to make it visible in the online docs for 4.1.
I picked this from main and removed the other changes.
I hope after merge this is picked up by the bot and rolled out to the website.

### CODE REVIEW

**Comment by J-N-K** [comment]
Why can't we just cherry-pick the other PR to 4.1.x?

**Comment by holgerfriedrich** [comment]
That would change the default as well. And  the translations would no longer be in sync, as properties file is changed.

That's why I only picked the change of the readme file.

**Comment by florian-h05** [comment]
@holgerfriedrich I don’t think that doc changes from the 4.1.x branch of openhab-addons are picked up by Jenkins to be migrated into the final-stable branch of openhab-docs.

When I wanted to change the JS Scripting docs after a release @Confectrician (docs maintainer) told me to to a PR directly to the final-stable branch of openhab-docs: https://github.com/openhab/openhab-docs/blob/final-stable/_addons_bindings/openweathermap/readme.md

So this PR here has to go to openhab-docs instead of openhab-addons. After the PR is merged, I will take care that the stable website is redeployed.

**Comment by holgerfriedrich** [comment]
@florian-h05 I saw several commits of a bot titled "Automated openhabian Docs fetch", so I thought this would still be active. Looking closer, is seems not to update any add-on docs.

**Comment by florian-h05** [comment]
👍 the last time that add-on docs were updated was in https://github.com/openhab/openhab-docs/commit/0604871478ff6677f6ee9342aaa4ba2ebd9c742d, add-on docs are migrated by Jenkins.

**Pull request closed without merging**
