### PR TITLE
[itests] Fix after changing Inbox interface

### PR DESCRIPTION
**Pull request by lolodomo**
Related to openhab/openhab-core#1848

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by cpmeister** [comment]
systeminfo.tests is failing in jenkins

**Comment by lolodomo** [comment]
> systeminfo.tests is failing in jenkins

First, I can confirm that full build is working on my machine.

Second, in the jenkins console output, strangely we don't find any trace of the run of this test, except the final failure in the summary. Strange !

I will not be able to help more, I have no particular knowledge in jenkins. I am just very confident on my PR.

**Review by kaikreuzer — APPROVED** [review]
Thanks - we will be able to confirm it when the main build now succeeds again 👍

**Pull request merged**
