### PR TITLE
[systeminfo] Support multiple processes

### PR DESCRIPTION
**Pull request by falkena**
Short summary: Refactored the binding to support multiple processes. Now the computer system is modeled as bridge and process was extracted to own thing. Additionally add annotations and fix some warnings.

Test-Jar is located under https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.systeminfo/2.5.0-SNAPSHOT/org.openhab.binding.systeminfo-2.5.0-SNAPSHOT.jar

Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com>

### CODE REVIEW

**Comment by J-N-K** [comment]
While I like the general idea (and it should have been designed that way from the beginning), I‘m not to happy that we will have so many breaking changes that require people to delete and re-add things with 2.5. This is a lot of work and makes a bad user-experience (especially since all configuration has to be done again and can‘t be copied).

Do you see any chance to keep the old way have the new one in parallel?

**Comment by cweitkamp** [comment]
We maybe can work out a different concept for the architecture. It should be possible for existing user to keep their configuration as they are for the next release. Thus I would suggest to keep the current thing type `computer`, add the attribute `listed="false"` to it and introduce a new thing type `system` which represents your new structure and owns the new features. The `listed` attribute is similar to a flag for deprecation. It means the entity will e.g. not be listed in the UIs and should not be used in discovery and so on. But existing setups will work like expected. We will remove the thing type for the release after the next one - which can be announced in the documentation - and users have time to switch it in their local environments. Wdyt?

**Comment by falkena** [comment]
Tested over longer time: It works for me.

**Comment by davidgraeff** [comment]
Because this is blocking the bnd migration how do we proceed here?

Until now we had a breaking change every release in one or the other addon.
I'm assuming that people are not expecting an update to work with a button click and they will read the breaking changes section.

**Comment by falkena** [comment]
@davidgraeff Please, migrate. I'll rebase and adapt the changes again.

**Comment by J-N-K** [comment]
@falkena Any progress here?

**Comment by falkena** [comment]
@J-N-K. Yes there is progress here. After long time fighting eclipse, bnd, conflicts on rebase due to not backward compatible changes and so on, i adapted the stuff to current openhab state. Additionally i "recovered" cpu load channel, removed in 51807c34e1165651ef267ba9b6110bc9834d2e4f using getSystemCpuLoadBetweenTicks(). I deploy the binding to my test system and run long time test.
Suggestion about backward compability is right. Nevertheless, i wouldn't rewrite the changes here. The reasons are simple: I haven't enough time at the moment and development/debugging are currently a kind of brainf... May be somebody will find time to review to get the stuff hopefully merged.

Kind regards,

Alexander

**Comment by Hilbrand** [comment]
Closing due to long time no activity. If you still want to have these changes added feel free to ask for help or reopen this pr.

**Pull request closed without merging**
