### PR TITLE
[lcn] Add ability to invert Rollershutter Up/Down

### LINKED ISSUE #8047: [lcn] Make up and down on RollerShutters interchangeable
I am using lcn OH2 binding #7509 and rollershutters that apparently have a non-canonical cabling: up and down are reversed.
On OH1 I was using:

`Rollershutter lcnJalousieWZWestLinks "Jalousie WZ West links" (gWZ,  gEGJalousien, gHausJalousie, gJalousienWest, gEGJalousienWest, gLcn) 
{lcn="[UP:myHome:RELAYS.0.54.11------], 
[DOWN:myHome:RELAYS.0.54.10------], [STOP:myHome:RELAYS.0.54.0-------]"}`

On OH2 binding this gets:

`Rollershutter lcnJalousieWZWestLinks "Jalousie WZ West links" (gWZ, gEGJalousien, gHausJalousie, gJalousienWest, gEGJalousienWest, gLcn) {channel="lcn:module:0242e6e48a96:0C050E1DBD:rollershutterrelay#1"}`

With OH2 I have to press the up button to get the shutters down as I can't intervene.

It would be great if the binding was allowing to interchange up and down buttons.
Obviously I would not like to change the cabling.

## Your Environment
* Version used: 2.5.6
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): raspberry pi + Debian

### PR DESCRIPTION
**Pull request by fwolter**
Closes #8047

### CODE REVIEW

**Comment by timbms** [comment]
Can you please add an example how the invertUpDown parameter is added?

**Comment by fwolter** [comment]
grafik

**Comment by timbms** [comment]
That was a quick return. How is this done in the configuration files? I am still old school.

**Comment by fwolter** [comment]
Actually it's the wrong place to ask these questions. You could open a thread in the community forum.

**Comment by timbms** [comment]
OK. You are right. Community forum would be the right place. 
Follow-up on invertUpDown: The icon displayed for open/close seems not inverted. Shall I open a new issue?

**Comment by fwolter** [comment]
Yes, please open an issue. I'll take a look into it, then.

**Pull request merged**
