### PR TITLE
[insteon] Added support to 2472D OutletLinc Dimmer for LED On/Off, LED Brightne…

### PR DESCRIPTION
**Pull request by tommycw1**
Recently bought one of these and these features were not supported by OH.

Interesting note, I suspected this would act just like a 2477D dimmer and it mostly does, but it does not respond to local on-level changes so I left that feature out. You can set the local on-level and reading the Status, you can see it takes the change, but pressing the hardware button still goes to full brightness - disregarding the OL setting.

This is for Feature Request: https://github.com/openhab/openhab-addons/issues/7469

### CODE REVIEW

**Comment by tommycw1** [comment]
@robnielsen 

Thanks for the help on figuring our how to get my repo caught up to the upstream.  When I did that it closed the original PR, so I submitted this new one.  Hope that is OK.

**Comment by robnielsen** [comment]
@tommycw1 looks good, but need to wait for https://github.com/openhab/openhab-addons/pull/7449 and then you'll need to update your PR to include the changes.

**Comment by tommycw1** [comment]
> you'll need to update your PR to include the changes.

Sounds good @robnielsen - I'm in no rush.

**Comment by robnielsen** [comment]
@tommycw1 #7449 has been merged. After you update your PR to include it, can you run `mvn spotless:apply` as well?

**Comment by robnielsen** [comment]
@tommycw1, have you considered using feature branches? Maybe that's why your PR's are getting closed.

**Pull request closed without merging**
