### PR TITLE
[systeminfo] Bump OSHI to 6.5.0

### PR DESCRIPTION
**Pull request by falkena**
Bump OSHI dependency version to 6.5.0

Release notes: https://github.com/oshi/oshi/blob/master/CHANGELOG.md
Especially https://github.com/oshi/oshi/pull/2538

Signed-off-by: Alexander Falkenstern [alexander.falkenstern@gmail.com](mailto:alexander.falkenstern@gmail.com)

### CODE REVIEW

**Review by mherwege — APPROVED** [review]
LGTM

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Comment by radek-turecki** [comment]
I absolutely support this initiative! The last version of System info is from 2016. I'm keeping my fingers crossed and rooting for this request to appear in the new version of OH!

**Comment by wborn** [comment]
This is the most recent upgrade. Maybe you can create one like this for the latest version (6.6.5) @radek-turecki? :wink:

**Comment by radek-turecki** [comment]
aha I understand, I checked in 4.3.0 and there is still a problem with reading temperature or fanspeed (Windows version of course), so I thought it was a problem that this add-on does not have a new version of OSHI.

Thank you very much for the clarification. You guys are doing a good job! Thanks!

**Pull request merged**
