### PR TITLE
Rework ThingActions

### PR DESCRIPTION
**Pull request by wborn**
* Remove proxy workarounds
* Move ThingActions and a few other classes into the internal package
* Use more consistent action labels/descriptions

Related to:

* openhab/openhab-core#1714
* openhab/openhab-core#1639

### CODE REVIEW

**Review by cpmeister — APPROVED** [review]
You realize that you could of just changed the `invokeMethodOf` implementation to just return the concrete action class instance instead of the interface right? That way you could still keep all the null/instance type checks refactored...

**Comment by bobadair** [comment]
LGTM for the alarmdecoder and lutron bindings. Good to see the root cause fixed and the work-arounds being unwound!

**Review by J-N-K — APPROVED** [review]

**Review by druciak — APPROVED** [review]
LGTM

**Comment by fwolter** [comment]
Thing and configuration labels are all upper case. Doesn't look it a bit strange when Action labels are all lower case?

**Comment by stefanroellin** [comment]
LGTM for mpd binding

**Comment by marcelrv** [comment]
LGTM wrt MAX!
I agree with @fwolter  _Thing and configuration labels are all upper case. Doesn't look it a bit strange when Action labels are all lower case?_

**Comment by wborn** [comment]
The labels should be lower case and written such that you can compose a sentence out of them (see https://github.com/openhab/openhab-core/issues/1639). 

That way you can use the "labels" to form a proper sentence that describes your rule, as show in the Paper UI NGRE rule editor:

example

Perhaps we should rename "label" to something else, add some JavaDocs or a SAT check to make this more clear.

**Review by mhilbush — APPROVED** [review]
LGTM

**Review by clinique — APPROVED** [review]

**Comment by wborn** [comment]
> You realize that you could have just changed the invokeMethodOf implementation to just return the concrete action class instance instead of the interface right? That way you could still keep all the null/instance type checks refactored...

I still wanted to look into what was possible to reduce all this duplicate code.

The compiler is also happy when converting:

```java
    public static void sendWakeOnLanPacket(@Nullable ThingActions actions) {
        if (actions instanceof NetworkActions) {
            ((NetworkActions) actions).sendWakeOnLanPacket();
        } else {
            throw new IllegalArgumentException("Actions is not an instance of NetworkActions");
        }
    }
```

to:

```java
    public static void sendWakeOnLanPacket(ThingActions actions) {
        ((NetworkActions) actions).sendWakeOnLanPacket();
    }
```

That way Java will throw a runtime exception when the provided value is null (NPE) or cannot be cast (CCE) without having to duplicate any code.

I also tried changing the signature to `sendWakeOnLanPacket(NetworkActions actions)` but that does not work because Xtext explicitly tries to call a static method with a `ThingActions` argument.

Another option could be to move this logic into a default method on the ThingActions interface so it can be reused in any `ThingActions` class, e.g.:

```java
    @SuppressWarnings("unchecked")
    default <T extends ThingActions> T as(Class<T> implClass) {
        if (implClass.isAssignableFrom(this.getClass())) {
            return (T) this;
        }
        throw new IllegalArgumentException(this + " is not an instance of " + implClass.getName());
    }
```

then you could use `actions.as(NetworkActions.class).sendWakeOnLanPacket()`, but it's just a complicated way of doing a regular cast.

**Pull request merged**
