### PR TITLE
[freeboxos] Fix systeminfo group for active-player thing type

### PR DESCRIPTION
**Pull request by lolodomo**
And remove this group from player thing type.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lsiepel** [comment]
For the Thing upgrade instructions i could not find how to handle these groups.  Should there be any upgrade instructions?

**Comment by lolodomo** [comment]
We could remove the 3 channels and add them again (only 2 of 3).

**Comment by lsiepel** [comment]
> We could remove the 3 channels and add them again (only 2 of 3).

I can't advice here as there4 does not seem to be no documentation and i have no experiences with this specfific use case.

**Comment by lolodomo** [comment]
Things upgrade tested successfully.

**Review by lsiepel — APPROVED** [review]

**Pull request merged**
