### PR TITLE
Run spotless for 2.5 branch on pom files

### PR DESCRIPTION
**Pull request by marcelrv**
I had some challenges getting Travis to run on the 2.5 branch as it complains about spotless errors.
This is running spotless on the 2.5, changing the POM files.

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Review by J-N-K — APPROVED** [review]
Thanks. I was preparing the same PR

**Comment by J-N-K** [comment]
@pfink Can we add `mvn spotless:apply` to the release-script? This happens every time the unleash-plugin changes the pom-versions after a release.

**Comment by pfink** [comment]
> @pfink Can we add `mvn spotless:apply` to the release-script? This happens every time the unleash-plugin changes the pom-versions after a release.

Probably it won't work like this. It has to be fixed within the unleash plugin: https://github.com/shillner/unleash-maven-plugin/issues/121

**Comment by J-N-K** [comment]
Build succeeded but deploying failed.

**Comment by J-N-K** [comment]
@openhab/add-ons-maintainers Can we merge here anyway?

**Comment by marcelrv** [comment]
The integration test are not running, causing the fail

**Review by t-8ch — APPROVED** [review]

**Review by wborn — APPROVED** [review]
Thanks!

**Pull request merged**
