### PR TITLE
[openhabcloud] Remove content encoding when proxing.

### PR DESCRIPTION
**Pull request by digitaldan**
We have recently added  gz and br encoding to the main UI.  Unfortunately the cloud binding does not pass this along as the default jetty client tries to decode this for you silently.  This removes jetty default encodings,  as streams should be untouched until they reach the web client.   See https://github.com/openhab/openhab-webui/pull/1521

Ping @ghys

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Let's wait a little in case @kaikreuzer would like to comment.

**Comment by digitaldan** [comment]
>Let's wait a little in case @kaikreuzer would like to comment.

Sure, just curious why ?

**Comment by lolodomo** [comment]
> > Let's wait a little in case @kaikreuzer would like to comment.
> 
> Sure, just curious why ?

Just because he is identified as the creator or maintainer of this binding.

**Comment by digitaldan** [comment]
Gotcha.

**Review by kaikreuzer — APPROVED** [review]
All fine, thanks.

**Pull request merged**
