### PR TITLE
[jdbc] Process operations asynchronously

### LINKED ISSUE #14927: [jdbc] `store` is not implemented in async way according to recommendation
See https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/persistenceservice#store(org.openhab.core.items.Item)

> Implementors should keep in mind that all registered [PersistenceService](https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/PersistenceService.html)s are called synchronously. Hence long running operations should be processed asynchronously. E.g. store adds things to a queue which is processed by some asynchronous workers (Quartz Job, Thread, etc.).

Identified in #14899

## Expected Behavior

`store` should call database asynchronously and return quickly.

## Current Behavior

Implementation is synchronous:

https://github.com/openhab/openhab-addons/blob/8a2e8b459566131d9defba85e3e6b2b611561edf/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java#L132-L170

https://github.com/openhab/openhab-addons/blob/8a2e8b459566131d9defba85e3e6b2b611561edf/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java#L215-L226

https://github.com/openhab/openhab-addons/blob/8a2e8b459566131d9defba85e3e6b2b611561edf/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java#L433-L445

## Possible Solution

Perhaps create a thread on demand and let it run running until it hasn't been used for a few minutes. For a busy system this would mean the thread would always be there and items would be persisted immediately as they are now, but delegated to and handled by the thread.

### LINKED ISSUE #15821: [jdbc-sqlite] Sometimes fails with SQLITE_BUSY with OH 4.0.3
## Expected Behavior
I have a rule that updates two items every 10 minutes.
I am expecting both item updates to be store in the SQLite database every time that they are changed. 
This was working in OH 3.4.0.

## Current Behavior
After upgrading to 4.0.3 I started getting occasional exceptions with SQLITE_BUSY and the item updates not being stored.
In the last 24 hours I had 8 times that it failed and the items are being updated every 10 minutes.
I set the level logs to debug on the sqlite binding and the log is attached that shows when this happens.
[SQlite-debug-log.txt](https://github.com/openhab/openhab-addons/files/13197839/SQlite-debug-log.txt)

I have only seen the error happen on one of the two items, never both.
I tried restarting both NAS and OH several times.
If I try and insert the values afterwards via the SQLite command line tool I can insert the values without any problems.

## Possible Solution
I am guessing this is a threading issue that the SQLite database can not handle two item updates (writes) at the same time. 
So some times the updates run so synchronously that the data write happens at the same time and then it fails.
Other times they er not aligned and everything works fine.
So a possible solution might be a global lock that prevents more then one thread from writing to the databased at a time. 

## Steps to Reproduce (for Bugs)
My jdbc.persist look like this:
[jdbc.persist.txt](https://github.com/openhab/openhab-addons/files/13197881/jdbc.persist.txt)
The rule look like this
```
rule "Update 10 minute value"
when
  Time cron "57 9/10 * ? * * *" 
then
...
    smartmeter_10_min_energy_usage.postUpdate( current_value - last_10_min_power_value )
    smartmeter_10_min_cost.postUpdate( (current_value - last_10_min_power_value) * (energi_data_service_total_price.state as Number ))
end
```

## Context
I am trying to store the power usage and cost every 10 minutes so that I can create a graph of this.

## Your Environment
* Version used: 4.0.3
* Environment name and version: Docker image openhab/openhab:4.0.3
* Operating System and version: Synology DS720+ NAS with DSM 7.2-64570 Update 1

### PR DESCRIPTION
**Pull request by jlaur**
Resolves #14927
Resolves #15821 (for good)

Tested by installing compiled bundle as well as [mysql-connector](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/8.0.33) into addons directory as `mysql-connector.jar`.

### CODE REVIEW

**Comment by jlaur** [comment]
I wanted to stress test this to see if there would be any changes in behavior and to verify the order of persisting states for the same item. For this purpose I wrote a small rule:
```javascript
rules.when()
    .item("Test").changed().toOn()
    .then(event =>
    {
        for (var i = 0; i= < 100; i++) {
            items.FastPersist.postUpdate(i);
        }
    })
    .build("Test persistence", "Quickly persist many item states");
```

`FastPersist` is a `Number` item with persistence `strategy = everyChange`.

It works the same way before and after the changes, but for me this was unexpected:
```
2023-10-24 22:38:19.737 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=38, Label=Test fast persistence, Category=) state=38 date=null
2023-10-24 22:38:19.758 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=45, Label=Test fast persistence, Category=) state=45 date=null
2023-10-24 22:38:19.776 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=51, Label=Test fast persistence, Category=) state=51 date=null
2023-10-24 22:38:19.796 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=99 date=null
2023-10-24 22:38:19.822 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=99 date=null
```

and so on... resulting in the following being persisted:

```csv
2023-10-24 22:38:19.906, 38
2023-10-24 22:38:19.919, 45
2023-10-24 22:38:19.937, 51
2023-10-24 22:38:19.956, 99
2023-10-24 22:38:19.983, 99
2023-10-24 22:38:19.994, 99
```
etc.

So I started digging to understand what happened. This is the persistence service method being called:

https://github.com/openhab/openhab-addons/blob/0886a24182eb910409b0e3c36471c53cb4bdcb4e/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java#L137-L141

This already gave a clue, because the new state is not provided, but is fetched on the fly. So probably the item was updated so fast by core, that all the subsequent persistence calls just kept fetching the end value of 100 and persisted this same value over and over again.

I then went to `PersistenceManager` to find the caller:

https://github.com/openhab/openhab-core/blob/f2c20af94458371adecd7adc4630312165fc9fed/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManager.java#L169

and adapted it for verification:
```java
                            if (persistenceService instanceof ModifiablePersistenceService modifiablePersistenceService) {
                                modifiablePersistenceService.store(item, ZonedDateTime.now(), state);
                            } else {
                                persistenceService.store(item, itemConfig.alias());
                            }
```

By using the [ModifiablePersistenceService](https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/modifiablepersistenceservice) method overload, I could provide timestamp and state explicitly by adding a new `State` parameter to `handleStateEvent`:

```java
    @Override
    public void stateChanged(Item item, State oldState, State newState) {
        handleStateEvent(item, true, newState);
    }

    @Override
    public void stateUpdated(Item item, State state) {
        handleStateEvent(item, false, state);
    }
```

this changed the results, but still not as expected since the order was not preserved:
```
2023-10-24 23:49:51.061 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=0 date=2023-10-24T23:49:50.989286200+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.075 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=2 date=2023-10-24T23:49:50.990285700+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.084 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=3 date=2023-10-24T23:49:50.990285700+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.093 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=4 date=2023-10-24T23:49:50.991284700+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.102 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=9 date=2023-10-24T23:49:51.023265500+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.119 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=6 date=2023-10-24T23:49:51.023265500+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.138 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=7 date=2023-10-24T23:49:51.024264200+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.149 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=8 date=2023-10-24T23:49:51.025263400+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.158 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=35 date=2023-10-24T23:49:51.025263400+02:00[Europe/Copenhagen]
2023-10-24 23:49:51.166 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=99, Label=Test fast persistence, Category=) state=5 date=2023-10-24T23:49:51.039254600+02:00[Europe/Copenhagen]
```

and so on.

I then added some additional logging to see not only when the scheduled tasks are executed, but also the order in which they are scheduled:
```java
    @Override
    public void store(Item item, ZonedDateTime date, State state) {
        logger.debug("JDBC::scheduling: item={} state={} date={}", item, state, date);
        scheduler.execute(() -> internalStore(item, date, state));
    }
```

and here it goes sideways with the order:
```
2023-10-25 21:43:32.595 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::scheduling: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=10 date=2023-10-25T21:43:32.595400100+02:00[Europe/Copenhagen]
2023-10-25 21:43:32.599 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::scheduling: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=11 date=2023-10-25T21:43:32.599397900+02:00[Europe/Copenhagen]
2023-10-25 21:43:32.601 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::scheduling: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=46 date=2023-10-25T21:43:32.601396+02:00[Europe/Copenhagen]
2023-10-25 21:43:32.601 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC::scheduling: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=20 date=2023-10-25T21:43:32.601396+02:00[Europe/Copenhagen]
```

but the order is (as expected) preserved when the scheduled tasks are finally executed:
```
2023-10-25 21:43:32.743 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=10 date=2023-10-25T21:43:32.595400100+02:00[Europe/Copenhagen]
2023-10-25 21:43:32.765 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=11 date=2023-10-25T21:43:32.599397900+02:00[Europe/Copenhagen]
2023-10-25 21:43:32.776 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=46 date=2023-10-25T21:43:32.601396+02:00[Europe/Copenhagen]
2023-10-25 21:43:32.786 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=FastPersist (Type=NumberItem, State=100, Label=Test fast persistence, Category=) state=20 date=2023-10-25T21:43:32.601396+02:00[Europe/Copenhagen]
```

In event log everything was in correct order:
```
2023-10-25 21:43:32.550 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 100 to 0
2023-10-25 21:43:32.553 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 0 to 1
2023-10-25 21:43:32.556 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 1 to 2
2023-10-25 21:43:32.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 2 to 3
2023-10-25 21:43:32.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 3 to 4
2023-10-25 21:43:32.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 4 to 5
2023-10-25 21:43:32.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 5 to 6
2023-10-25 21:43:32.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 6 to 7
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 7 to 8
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 8 to 9
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 9 to 10
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 10 to 11
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 11 to 12
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 12 to 13
2023-10-25 21:43:32.558 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 13 to 14
2023-10-25 21:43:32.565 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 14 to 15
2023-10-25 21:43:32.565 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 15 to 16
2023-10-25 21:43:32.566 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 16 to 17
2023-10-25 21:43:32.566 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 17 to 18
2023-10-25 21:43:32.566 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 18 to 19
2023-10-25 21:43:32.566 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 19 to 20
2023-10-25 21:43:32.567 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'FastPersist' changed from 20 to 21
```

So it think the async refactoring works as expected, even if the solution is a bit simplistic.

It will of course not work as described, because I modified `PersistenceManager` to get those results.

I'm not sure what to do with my findings yet, i.e. if this behavior is expected, even though in some ways it's not optimal.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@jlaur : is it ok for merging or do you have still a doubt ?

**Comment by jlaur** [comment]
> @jlaur : is it ok for merging or do you have still a doubt ?

Yes, I have been running it in production for some time now, and it was also tested by an SQLite user.

My findings from testing are not specific to JDBC.

**Pull request merged**
