### PR TITLE
Update license headers to 2022

### PR DESCRIPTION
**Pull request by Hilbrand**

### CODE REVIEW

**Review by clinique — APPROVED** [review]

**Review by hmerk — APPROVED** [review]

**Review by kaikreuzer — APPROVED** [review]
Time for it, thank you!

**Comment by lolodomo** [comment]
As we are merging PRs from last year, it is not impossible that some headers with 2021 were inserted after your PR was created.
Maybe it should be run again before each new milestone, at least the first milestones of 2022.

**Comment by wborn** [comment]
> Maybe it should be run again before each new milestone, at least the first milestones of 2022

Probably much sooner because the build fails due to a SAT error when the wrong headers are used. 😉

**Comment by lolodomo** [comment]
Ok, good point, at least we have a way to detect quickly such problem.

**Pull request merged**
