### PR TITLE
[darksky] Remove DarkSky binding due to EOL of their API

### PR DESCRIPTION
**Pull request by cweitkamp**
- Remove DarkSky binding due to EOL of their API

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
Can you please provide a link announcing this EOL?

**Comment by hmerk** [comment]
https://blog.darksky.net/
API will continue to work until March 31st 2023, therefore I see no reason for a rush now.

**Comment by jlaur** [comment]
@cweitkamp - if you can resolve the conflicts (or redo deletion if that would be easier), I think we can now merge this into 4.0.

**Comment by cweitkamp** [comment]
@jlaur Done.

**Comment by jlaur** [comment]
> @jlaur Done.

Excellent! Can you remove from `bom/openhab-addons/pom.xml` also?

**Comment by andrewfg** [comment]
Just so you know: the DarkSky binding was actually still running fine on my OH 3.4.x system until this week, but I can confirm that it is now definitely no long working. RIP ..

**Pull request merged**
