### PR TITLE
[miio] Added support for Roborock Q Revo

### PR DESCRIPTION
**Pull request by truidix**
I just added the device name and  the vaccuum is recognized an fill functional

Signed-off-by: David Kumar <github@truidix.de>

### CODE REVIEW

**Comment by marcelrv** [comment]
Thanks for the contribution.
Would be great if you could run the readmemaker as that will update the other needed files as well

**Comment by truidix** [comment]
Right after the merge request I remembered that I forgot the README. I hope that fits so?

**Comment by marcelrv** [comment]
Yes but be aware that the readmemaker also updates the i18n files for the translations

**Comment by truidix** [comment]
@marcelrv , I have added the model there as well. And I also ran spotless:apply, even though I didn't change the pom at all, there are obvious changes to it.

**Comment by truidix** [comment]
@marcelrv , I'm still getting the code format violations. Localy everthing is runing fine. Can you have a hint, how to resolve that problem?

**Comment by jlaur** [comment]
Please retarget PR towards main.

**Comment by wborn** [comment]
Please create a new PR against the main branch as was instructed in the PR template:

> All PRs should be created using the "main" branch as base.
> Important bugfixes are cherry-picked by maintainers to the patch release branch after a PR has been merged.

**Pull request closed without merging**
