### PR TITLE
[mqtt] Check if Thing has been started before changing its status

### LINKED ISSUE #8397: [mqtt.homeassistant] Error when trying to delete a Home Assistant Thing
After https://github.com/openhab/openhab-addons/pull/8317 was merged, I've seen this error message when trying to delete a Home Assistant Thing:

```
22:04:21.311 [ndlerExecutor-1] INFO  smarthome.event.ThingStatusInfoEvent:53 - 'mqtt:homeassistant_zigbee2mqtt_5F0x14b457fffe7eeb7b:15616d5a:zigbee2mqtt_5F0x14b457fffe7eeb7b' updated: REMOVING
22:04:21.312 [ndlerExecutor-1] INFO  s.event.ThingStatusInfoChangedEvent:53 - 'mqtt:homeassistant_zigbee2mqtt_5F0x14b457fffe7eeb7b:15616d5a:zigbee2mqtt_5F0x14b457fffe7eeb7b' changed from ONLINE to REMOVING
22:04:21.371 [-thingManager-1] ERROR o.e.s.c.t.internal.ThingManagerImpl:958 - The ThingHandler caused an exception while handling the removal of its thing
java.lang.IllegalArgumentException: Illegal status transition from REMOVING to ONLINE, only REMOVED would have been allowed.
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.statusUpdated(ThingManagerImpl.java:190)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:357)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:372)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.updateThingStatus(HomeAssistantThingHandler.java:301)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.calculateThingStatus(AbstractMQTTThingHandler.java:366)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.resetMessageReceived(AbstractMQTTThingHandler.java:353)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.stop(AbstractMQTTThingHandler.java:117)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.stop(HomeAssistantThingHandler.java:220)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.handleRemoval(AbstractMQTTThingHandler.java:246)
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$7.run(ThingManagerImpl.java:951)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I will provide a PR soon :wink:

### PR DESCRIPTION
**Pull request by bodiroga**
We need to check if the Thing has been started or stopped in ```updateThingStatus```, otherwise the binding will try to update the status of the Thing while the framework is trying to remove it, as it can be seen here:

```
22:04:21.311 [ndlerExecutor-1] INFO  smarthome.event.ThingStatusInfoEvent:53 - 'mqtt:homeassistant_zigbee2mqtt_5F0x14b457fffe7eeb7b:15616d5a:zigbee2mqtt_5F0x14b457fffe7eeb7b' updated: REMOVING
22:04:21.312 [ndlerExecutor-1] INFO  s.event.ThingStatusInfoChangedEvent:53 - 'mqtt:homeassistant_zigbee2mqtt_5F0x14b457fffe7eeb7b:15616d5a:zigbee2mqtt_5F0x14b457fffe7eeb7b' changed from ONLINE to REMOVING
22:04:21.371 [-thingManager-1] ERROR o.e.s.c.t.internal.ThingManagerImpl:958 - The ThingHandler caused an exception while handling the removal of its thing
java.lang.IllegalArgumentException: Illegal status transition from REMOVING to ONLINE, only REMOVED would have been allowed.
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.statusUpdated(ThingManagerImpl.java:190)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:357)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:372)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.updateThingStatus(HomeAssistantThingHandler.java:301)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.calculateThingStatus(AbstractMQTTThingHandler.java:366)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.resetMessageReceived(AbstractMQTTThingHandler.java:353)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.stop(AbstractMQTTThingHandler.java:117)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.stop(HomeAssistantThingHandler.java:220)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.handleRemoval(AbstractMQTTThingHandler.java:246)
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$7.run(ThingManagerImpl.java:951)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is sequence that creates the error:

- handleRemoval() [AbstractMQTTThingHandler]
- stop() [HomeAssistantHandler]
- stop() [AbstractMQTTThingHandler]
- resetMessageReceived() [AbstractMQTTThingHandler]
- calculateThingStatus() [AbstractMQTTThingHandler]
- updateThingStatus() [HomeAssistantThingHandler]

This error has appeared after https://github.com/openhab/openhab-addons/pull/8317 was merged, sorry.

@jochen314, @Hilbrand or @J-N-K, what do you think?

Fixes #8397

Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

### CODE REVIEW

**Comment by Hilbrand** [comment]
You test with `ThingHandlerHelper.isHandlerInitialized` if the thing is in online, offline, or unknown status. Which are the states when the handler is active.

**Comment by bodiroga** [comment]
> You test with `ThingHandlerHelper.isHandlerInitialized` if the thing is in online, offline, or unknown status. Which are the states when the handler is active.

Thanks @Hilbrand! Looks uglier (or at least longer), but it's more generic! :+1: 

I have also added the same check to the GenericMQTTThingHandler and updated the title of the PR!

**Comment by bodiroga** [comment]
Wait, the implementation is wrong, checking the value returned by ```isHandlerInitialized()``` in GenericMQTTThingHandler will prevent the Thing from going to ONLINE for the first time :worried:

**Comment by bodiroga** [comment]
Ok, I've set the GenericMQTTThing's status to UNKNOWN in its ```initialize()``` method, because, as far as I know, that is a good practice.

But... there is still an error in the ```initialize()``` test function of the GenericThingHandlerTest class. I've been trying to read and learn about JUnit tests, but I don't understand why the ```ThingHandlerHelper.isHandlerInitialized(this)``` returns ```false``` even after setting the thing's status to UNKNOWN. I've added a print statement in the test and ```thingHandler.getThing().getStatus()``` returns ```null```, while ```thingHandler.getThing().getStatusInfo()``` correctly returns ```ONLINE```. It seems that the ```updateStatus(...)``` function is called, but that doesn't modify the thing's status. The mocked Thing doesn't update its attributes? :confused: 

Is there any way to force the thing to update its status with the execution of the ```initialize()``` method? @Hilbrand, can you help me with this?

**Pull request closed without merging**
