### PR TITLE
Adapt to ColorUtil changes in core

### PR DESCRIPTION
**Pull request by holgerfriedrich**
see openhab/openhab-core#3479

may be merged as separate commits without squashing

### CODE REVIEW

**Comment by antroids** [comment]
Hi [@ccutrer](https://github.com/ccutrer), could you take a look

**Comment by andrewfg** [comment]
^
I wonder if rather than using `assertEquals(expected, actual)` (or similar assertions) you should instead use the `assertEquals(expected, actual, delta)` variant? The `delta` variant allows you to set a comparison precision analogous to `assertTrue(Math.abs(actual - expected) < delta)`

**Comment by holgerfriedrich** [comment]
@andrewfg Thanks for mentioning. I agree that double/float comparisons should always use a delta - even if the current check works.
In this case it is not my intent to change existing code in the plugins, except the value changes to adapt to the next rounding behaviour of core functions.
Do you refer to a specific file, TradfriColorTest.java?

**Comment by andrewfg** [comment]
> Do you refer to a specific file, TradfriColorTest.java?

Yes. And also, I think the ones using assertThat..is..

**Comment by J-N-K** [comment]
The correct hamcrest matcher is `closeTo`

**Comment by J-N-K** [comment]
What is the state here? I believe it needs to be merged immediately after the PR in core to not break the build.

**Comment by holgerfriedrich** [comment]
Correct. I renamed one function and the rounding behavior will require tests to be slightly adapted.

I did not check if it is still building after the latest changes, but it should be fine.

**Review by J-N-K — APPROVED** [review]
LGTM

**Comment by holgerfriedrich** [comment]
I can have a look later tonight....

**Comment by J-N-K** [comment]
The issue is a missing new core snapshot. It builds fine locally.

**Comment by jlaur** [comment]
See also https://github.com/openhab/openhab-addons/actions/runs/4644251102

**Comment by holgerfriedrich** [comment]
@jlaur yes, could your pls merge the PR?

**Pull request merged**
