### PR TITLE
[salus] Add support documentation

### PR DESCRIPTION
**Pull request by magx2**
@lsiepel I see that the discussion about `Support` might take a longer time, so I've created a new PR with only this. It will be also easier for you to get back in case someone else will have similar question

### CODE REVIEW

**Comment by magx2** [comment]
Sorry, I've removed this branch by mistake.

**Comment by magx2** [comment]
@kaikreuzer  @lsiepel any update?

**Comment by lsiepel** [comment]
> at the discussion about `Support` might take a longer time, so I've created a new PR with only this. It will be also easier for you to get back in case someone else will have similar question

Nothing i can add to this topic, sorry.

**Comment by magx2** [comment]
> > at the discussion about `Support` might take a longer time, so I've created a new PR with only this. It will be also easier for you to get back in case someone else will have similar question
> 
> Nothing i can add to this topic, sorry.

Are you able to ping @kaikreuzer somehow?

**Comment by nemerdaud** [comment]
Personally, I include "support documentation" for OH and other opensources I support because I believe it is good practice for the free community. Honestly, I don't know if anyone survives on donations through contributions :-), but I believe that in some way it can motivate and encourage greater participation in the community.

**Comment by magx2** [comment]
@kaikreuzer yes or no?

gladiator-thumb-header-1024x576

**Comment by magx2** [comment]
@kaikreuzer 

CatTiktokGIF

**Comment by magx2** [comment]
Is there anyone? @kaikreuzer 

VincentGIF

**Comment by kaikreuzer** [comment]
Hey @magx2, sorry for not responding! I actually didn't get (or see?) any notification from GitHub on this issue, so I wasn't at all aware of your shouts into the void here - I'm very sorry for this. @lsiepel was so kind to ping me on the forum, which now drew my attention here.

Let me say that I very much appreciate and welcome your contributions to openHAB, so it definitely wasn't my intention to ignore or upset you in any way. What I would also like to mention: Since many years, I am no longer the BDFL of openHAB, so it is ultimately not on me to take any decision here, but for this repo it is the team of @openhab/add-ons-maintainers and if they feel it is a topic that should not be decided in that group, the matter can be escalated to the @openhab/architecture-council.

Having said this, please take the following as my personal opinion (and I am happy for others from the @openhab/add-ons-maintainers and @openhab/architecture-council teams to join in):

As said above, I appreciate all your contributions and engagement a lot as it is what makes openHAB to what it is. Likewise, I am very grateful for all contributions by all other contributors. When having to decide on general questions, I try to think about the outcome, if some action proliferates. In our case here: Allowing one binding author to add a "donation link" means that every author should be allowed the same. This automatically brings up many questions: Is it ok to have 400 different kinds of donation requests on our various documentation pages? What about add-ons that have multiple authors (which might be active to different degrees as well)? What about the maintainers that might keep spending many hours in code reviews and testing of the add-ons? What about contributors to core, distro, UI, etc. repositories? I could extend this list of questions endlessly.
The result of it is imho that there is no "fair" solution to it. Anything but simply not doing it would feel unfair to the one or the other group. For that reason, we have always stayed away from paying any developers for work on openHAB (and promoting donations is imho a small step in such a direction) as it would immediately create imbalances in the community. And to be realistic, just as @nemerdaud stated above: Nobody survives on such small donations. In the end, from my own experience a nice comment saying thanks or a personal e-mail to an author is so much more worth than a coffee.

So based on these thoughts, my personal preference would be to close this PR and I hope you understand my reasoning and you do not take it in any way personal. But as I said above, I am not the one to decide (alone), so I am happy to hear other voices and opinions.

**Comment by lsiepel** [comment]
Thank you @kaikreuzer your comment expresses exactly my point of view towards this subject. As no other @openhab/add-ons-maintainers commented on this, I think this is the final conclusion. I'll close this for now.
If there is ever a need to come back to this, we can re-open, link or on any other way continue the discussion.

PS. Don't think i need to explain that i hope you will keep contributing, not only because of the added features, but also because i enjoy the humour and fun you add to your contributions.

**Comment by nemerdaud** [comment]
Agreed as well ! Thanks @kaikreuzer for the good points you left here !

**Pull request closed without merging**
