### PR TITLE
[openwebnet] Fix update of Thermo Central Unit atLeastOneProbeX channels and refactoring

### LINKED ISSUE #12599: [openwebnet] Thermo: wrong startup value for channel weeklyProgram
## Expected Behavior
channel `weeklyProgram` should be 1, 2 or 3 at startup when mode is set to `WEEKLY` or `undef` for others mode.
same for `scenarioProgram` (1...16) when mode is set to `SCENARIO`.

## Current Behavior
channel `weeklyProgram` shows 1970-01-01T00:00:01.000+0000 (at startup when mode is set to `WEEKLY`)

See [community post](https://community.openhab.org/t/openwebnet-thermoregulation-support-in-openhab3-ready-for-testing/123030/73)

### LINKED ISSUE #14449: [openwebnet] Thermo: CU setpointTemp not restored
When changing mode from OH Thermo CU item from MANUAL to OFF and back to MANUAL, the previously set temperature is not restored on the `setpointTemperature` channel, but instead it’s set to a pre-defined value (11,5°), independently from its previous set value.
See forum thread: 

https://community.openhab.org/t/openwebnet-thermoregulation-support-in-openhab3-ready-for-testing/123030/114?u=massi

### LINKED ISSUE #15103: [openwebnet] Thermo: atLeastOneProbeX channels are not updated correctly for CU
Whena a zone is changed for example from Antifreeze to Manual, CU channels `atLeastOneProbeX` are not updated correctly.

### PR DESCRIPTION
**Pull request by mvalla**
This is a cumulative PR to primarly fix handling of Thermo Central Unit state channels `atLeastOneProbeX ` that were not updated correctly.
Thanks to a refactoring it also fixes other smaller issues related to thermo Central Unit channels.
The PR has been tested with one community user and with some simulated integration tests.
Lib openwebnet4j bumped to version 0.10.1.
Fixes #15103
Fixes #14449
Fixes #12599

### CODE REVIEW

**Comment by mvalla** [comment]
@lolodomo also one this should be included in OH4!
This is quite a good catch as it closes 3 issues. I have been working on it since some time and tested it with at least one community user plus some integration tests on my own. 
It works much better than current OH3 code.

**Comment by lolodomo** [comment]
> @lolodomo also one this should be included in OH4 if you can review it quickly !

Too late for me but maybe another @openhab/add-ons-maintainers can do it?

**Review by kaikreuzer — APPROVED** [review]
Sure, let's merge!

**Comment by mvalla** [comment]
great!

**Pull request merged**
