### PR TITLE
[Tankerkoenig]: Lower minimum refresh interval

### PR DESCRIPTION
**Pull request by Flole998**
As per https://creativecommons.tankerkoenig.de (in the "Terms"-section) we should not make more than 1 request per 5 minutes, this changes the limit accordingly and allows doing so.

### CODE REVIEW

**Review by JueBag — APPROVED** [review]

**Comment by JueBag** [comment]
LGTM
Can't remember if the explizit limit of 5 minutes was stated when the binding was created or if I used 10 minutes to be on the safe side.

**Review by Skinah — APPROVED** [review]
LGTM

**Review by Hilbrand — APPROVED** [review]
I would say this was based on the idea 2 api calls are made: `getStationListData` and `getStationDetailData`. the latter one is only made once a day. So it's probably save to make a call every 5 minutes.

**Comment by JueBag** [comment]
> I would say this was based on the idea 2 api calls are made: `getStationListData` and `getStationDetailData`. the latter one is only made once a day. So it's probably save to make a call every 5 minutes.

Thanks for the Merge and No, the DetailRequest isn't counted in that sense (once a day IOT get changes in the opening time schedule).

**Pull request merged**
