### PR TITLE
[sonos] Fix error in channels.xml file

### LINKED ISSUE #11059: [sonos] Multiple channels are not setting properly.
Updated to build 2457 to pull in the new codec channel.  Now, many channels are not pulling in properly.

@lolodomo FYI

```
2021-07-26 13:36:43.010 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'add', because channel type 'sonos:add' could not be found.
2021-07-26 13:36:43.010 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'alarm', because channel type 'sonos:alarm' could not be found.
2021-07-26 13:36:43.013 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'alarmproperties', because channel type 'sonos:alarmproperties' could not be found.
2021-07-26 13:36:43.014 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'alarmrunning', because channel type 'sonos:alarmrunning' could not be found.
2021-07-26 13:36:43.014 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'bass', because channel type 'sonos:bass' could not be found.
2021-07-26 13:36:43.015 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'currentalbum', because channel type 'sonos:currentalbum' could not be found.
2021-07-26 13:36:43.016 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'currentalbumart', because channel type 'sonos:currentalbumart' could not be found.
2021-07-26 13:36:43.017 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'currentalbumarturl', because channel type 'sonos:currentalbumarturl' could not be found.
2021-07-26 13:36:43.018 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'currenttrack', because channel type 'sonos:currenttrack' could not be found.
2021-07-26 13:36:43.019 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'shuffle', because channel type 'sonos:shuffle' could not be found.
2021-07-26 13:36:43.021 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'repeat', because channel type 'sonos:repeat' could not be found.
2021-07-26 13:36:43.022 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'favorite', because channel type 'sonos:favorite' could not be found.
2021-07-26 13:36:43.023 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'led', because channel type 'sonos:led' could not be found.
2021-07-26 13:36:43.024 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'localcoordinator', because channel type 'sonos:localcoordinator' could not be found.
2021-07-26 13:36:43.025 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'loudness', because channel type 'sonos:loudness' could not be found.
2021-07-26 13:36:43.025 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'notificationsound', because channel type 'sonos:notificationsound' could not be found.
2021-07-26 13:36:43.026 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'playlist', because channel type 'sonos:playlist' could not be found.
2021-07-26 13:36:43.027 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'clearqueue', because channel type 'sonos:clearqueue' could not be found.
2021-07-26 13:36:43.028 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'playlinein', because channel type 'sonos:playlinein' could not be found.
2021-07-26 13:36:43.030 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'playqueue', because channel type 'sonos:playqueue' could not be found.
2021-07-26 13:36:43.031 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'playtrack', because channel type 'sonos:playtrack' could not be found.
2021-07-26 13:36:43.032 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'playuri', because channel type 'sonos:playuri' could not be found.
2021-07-26 13:36:43.032 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'publicaddress', because channel type 'sonos:publicaddress' could not be found.
2021-07-26 13:36:43.033 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'radio', because channel type 'sonos:radio' could not be found.
2021-07-26 13:36:43.034 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'remove', because channel type 'sonos:remove' could not be found.
2021-07-26 13:36:43.035 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'restore', because channel type 'sonos:restore' could not be found.
2021-07-26 13:36:43.035 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'restoreall', because channel type 'sonos:restoreall' could not be found.
2021-07-26 13:36:43.036 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'save', because channel type 'sonos:save' could not be found.
2021-07-26 13:36:43.037 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'saveall', because channel type 'sonos:saveall' could not be found.
2021-07-26 13:36:43.038 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'snooze', because channel type 'sonos:snooze' could not be found.
2021-07-26 13:36:43.039 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'standalone', because channel type 'sonos:standalone' could not be found.
2021-07-26 13:36:43.040 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'state', because channel type 'sonos:state' could not be found.
2021-07-26 13:36:43.040 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'stop', because channel type 'sonos:stop' could not be found.
2021-07-26 13:36:43.041 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'treble', because channel type 'sonos:treble' could not be found.
2021-07-26 13:36:43.042 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'tuneinstationid', because channel type 'sonos:tuneinstationid' could not be found.
2021-07-26 13:36:43.042 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'zonegroupid', because channel type 'sonos:zonegroupid' could not be found.
2021-07-26 13:36:43.043 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'zonename', because channel type 'sonos:zonename' could not be found.
2021-07-26 13:36:43.044 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'coordinator', because channel type 'sonos:coordinator' could not be found.
2021-07-26 13:36:43.044 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'sleeptimer', because channel type 'sonos:sleeptimer' could not be found.
2021-07-26 13:36:43.045 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'currenttransporturi', because channel type 'sonos:currenttransporturi' could not be found.
2021-07-26 13:36:43.046 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'currenttrackuri', because channel type 'sonos:currenttrackuri' could not be found.
2021-07-26 13:36:43.046 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'codec', because channel type 'sonos:codec' could not be found.
2021-07-26 13:36:43.047 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'linein', because channel type 'sonos:linein' could not be found.
2021-07-26 13:36:43.047 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'microphone', because channel type 'sonos:microphone' could not be found.
2021-07-26 13:36:43.048 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'nightmode', because channel type 'sonos:nightmode' could not be found.
2021-07-26 13:36:43.064 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'speechenhancement', because channel type 'sonos:speechenhancement' could not be found.
2021-07-26 13:36:43.065 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'subwoofer', because channel type 'sonos:subwoofer' could not be found.
2021-07-26 13:36:43.066 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'subwoofergain', because channel type 'sonos:subwoofergain' could not be found.
2021-07-26 13:36:43.067 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'surround', because channel type 'sonos:surround' could not be found.
2021-07-26 13:36:43.068 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'surroundmusicmode', because channel type 'sonos:surroundmusicmode' could not be found.
2021-07-26 13:36:43.068 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'surroundmusiclevel', because channel type 'sonos:surroundmusiclevel' could not be found.
2021-07-26 13:36:43.069 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'surroundtvlevel', because channel type 'sonos:surroundtvlevel' could not be found.
2021-07-26 13:36:43.070 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'heightlevel', because channel type 'sonos:heightlevel' could not be found.
2021-07-26 13:36:43.076 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'add' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:add' could not be found.
2021-07-26 13:36:43.077 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'alarm' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:alarm' could not be found.
2021-07-26 13:36:43.078 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'alarmproperties' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:alarmproperties' could not be found.
2021-07-26 13:36:43.079 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'alarmrunning' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:alarmrunning' could not be found.
2021-07-26 13:36:43.080 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'bass' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:bass' could not be found.
2021-07-26 13:36:43.081 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'currentalbum' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:currentalbum' could not be found.
2021-07-26 13:36:43.081 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'currentalbumart' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:currentalbumart' could not be found.
2021-07-26 13:36:43.082 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'currentalbumarturl' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:currentalbumarturl' could not be found.
2021-07-26 13:36:43.083 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'currenttrack' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:currenttrack' could not be found.
2021-07-26 13:36:43.084 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'shuffle' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:shuffle' could not be found.
2021-07-26 13:36:43.084 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'repeat' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:repeat' could not be found.
2021-07-26 13:36:43.085 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'favorite' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:favorite' could not be found.
2021-07-26 13:36:43.086 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'led' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:led' could not be found.
2021-07-26 13:36:43.087 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'localcoordinator' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:localcoordinator' could not be found.
2021-07-26 13:36:43.087 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'loudness' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:loudness' could not be found.
2021-07-26 13:36:43.088 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'notificationsound' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:notificationsound' could not be found.
2021-07-26 13:36:43.089 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'playlist' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:playlist' could not be found.
2021-07-26 13:36:43.089 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'clearqueue' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:clearqueue' could not be found.
2021-07-26 13:36:43.090 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'playlinein' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:playlinein' could not be found.
2021-07-26 13:36:43.091 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'playqueue' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:playqueue' could not be found.
2021-07-26 13:36:43.091 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'playtrack' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:playtrack' could not be found.
2021-07-26 13:36:43.092 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'playuri' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:playuri' could not be found.
2021-07-26 13:36:43.093 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'publicaddress' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:publicaddress' could not be found.
2021-07-26 13:36:43.093 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'radio' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:radio' could not be found.
2021-07-26 13:36:43.094 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'remove' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:remove' could not be found.
2021-07-26 13:36:43.094 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'restore' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:restore' could not be found.
2021-07-26 13:36:43.095 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'restoreall' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:restoreall' could not be found.
2021-07-26 13:36:43.095 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'save' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:save' could not be found.
2021-07-26 13:36:43.096 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'saveall' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:saveall' could not be found.
2021-07-26 13:36:43.097 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'snooze' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:snooze' could not be found.
2021-07-26 13:36:43.097 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'standalone' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:standalone' could not be found.
2021-07-26 13:36:43.098 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'state' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:state' could not be found.
2021-07-26 13:36:43.102 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'stop' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:stop' could not be found.
2021-07-26 13:36:43.103 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'treble' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:treble' could not be found.
2021-07-26 13:36:43.103 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'tuneinstationid' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:tuneinstationid' could not be found.
2021-07-26 13:36:43.104 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'zonegroupid' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:zonegroupid' could not be found.
2021-07-26 13:36:43.105 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'zonename' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:zonename' could not be found.
2021-07-26 13:36:43.106 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'coordinator' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:coordinator' could not be found.
2021-07-26 13:36:43.106 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'sleeptimer' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:sleeptimer' could not be found.
2021-07-26 13:36:43.108 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'currenttransporturi' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:currenttransporturi' could not be found.
2021-07-26 13:36:43.109 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'currenttrackuri' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:currenttrackuri' could not be found.
2021-07-26 13:36:43.109 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'codec' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:codec' could not be found.
2021-07-26 13:36:43.109 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'sonos:Arc:RINCON_48A6B8BF040E01400' to inbox.
2021-07-26 13:36:43.110 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'linein' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:linein' could not be found.
2021-07-26 13:36:43.110 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'microphone' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:microphone' could not be found.
2021-07-26 13:36:43.111 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'nightmode' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:nightmode' could not be found.
2021-07-26 13:36:43.111 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'speechenhancement' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:speechenhancement' could not be found.
2021-07-26 13:36:43.112 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'subwoofer' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:subwoofer' could not be found.
2021-07-26 13:36:43.113 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'subwoofergain' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:subwoofergain' could not be found.
2021-07-26 13:36:43.113 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'surround' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:surround' could not be found.
2021-07-26 13:36:43.114 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'surroundmusicmode' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:surroundmusicmode' could not be found.
2021-07-26 13:36:43.115 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'surroundmusiclevel' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:surroundmusiclevel' could not be found.
2021-07-26 13:36:43.116 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'surroundtvlevel' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:surroundtvlevel' could not be found.
2021-07-26 13:36:43.118 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'heightlevel' for thing 'sonos:Arc:RINCON_48A6B8BF040E01400', because channel type 'sonos:heightlevel' could not be found.

```

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #10979
Fix #11059 

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : please merge as soon as possible, the Sonos binding is currently broken in last snapshot.

**Review by kaikreuzer — APPROVED** [review]
Sure thing!

**Comment by morph166955** [comment]
Sorry bout that!

**Comment by lolodomo** [comment]
> Sorry bout that!

Hopefully you discovered and reported the problem very quickly ;)

**Comment by morph166955** [comment]
Confirmed that this is fixed in snapshot 2458.  Just updated my docker and it's all working as expected.

**Pull request merged**
