### PR TITLE
[androidtv] Resolves discovery issues

### LINKED ISSUE #16223: [androidtv] Discovery does not properly track representation-property
representation-property is not properly tracked through the discovery process.  This causes existing devices to not be ignored.

### PR DESCRIPTION
**Pull request by morph166955**
Resolves issue with discovered items not being ignored correctly

Resolves #16223

### CODE REVIEW

**Comment by morph166955** [comment]
@jlaur Pulled the discovery fixes to here.  This won't compile properly until I rebase after you merge the other since we changed PROPERTY_ to PARAMETER_.

**Comment by morph166955** [comment]
Rebased after the merge.  This should just be the discovery fixes now.

**Comment by jlaur** [comment]
This PR was extracted from #16191 while this issue was still open: https://github.com/openhab/openhab-addons/pull/16191#discussion_r1449433422

**Comment by morph166955** [comment]
So what do you think is the issue @jlaur?

**Comment by jlaur** [comment]
> So what do you think is the issue @jlaur?

I don't know. But for me to get the expected results, I only needed to fix this line (relative to **main**):
https://github.com/openhab/openhab-addons/blob/d5bbda6936f8b4575d656089736243553464be0b/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java#L84

into:
```java
    return DiscoveryResultBuilder.create(uid).withProperties(properties)
        .withRepresentationProperty(PARAMETER_IP_ADDRESS).withLabel(label).build();
```

image

**Comment by morph166955** [comment]
That's so interesting to me. That line was pulled from the Roku binding to fix this. The odd part was that Roku had that in place when I was having the issue. Just to confirm, the host property didn't get stuck in the thing database when you tested it without that line correct?

**Comment by jlaur** [comment]
> Just to confirm, the host property didn't get stuck in the thing database when you tested it without that line correct?

No, I tested on my 4.2 development system with a clean slate, i.e. no existing androidtv things. I then created the androidtv.things file and triggered the discovery. Before that I had nothing in my inbox, and after that I had the ignored entry.

**Comment by morph166955** [comment]
Very interesting. I'll run some more tests here.

**Comment by jlaur** [comment]
I can also add that my discovery result looks like this in `userdata/jsondb/org.openhab.core.config.discovery.DiscoveryResult.json`:
```json
  "androidtv:googletv:DCE55BD7C4F7": {
    "class": "org.openhab.core.config.discovery.internal.DiscoveryResultImpl",
    "value": {
      "thingUID": {
        "segments": [
          "androidtv",
          "googletv",
          "DCE55BD7C4F7"
        ],
        "uid": "androidtv:googletv:DCE55BD7C4F7"
      },
      "thingTypeUID": {
        "segments": [
          "androidtv",
          "googletv"
        ],
        "uid": ""
      },
      "properties": {
        "ipAddress": "192.168.0.72"
      },
      "representationProperty": "ipAddress",
      "flag": "IGNORED",
      "label": "Kontor TV (DCE55BD7C4F7)",
      "timestamp": "2024-01-12T22:25:57.098186200Z",
      "timeToLive": -1
    }
  },
```

Perhaps it's worth comparing.

**Comment by morph166955** [comment]
@jlaur I am now baffled.  I also now see that entry ignored without the addition of the property in the handler.  It's unclear to me what's happening here.  Testing before was very conclusive that it needed that line, and now it's working just fine without it.  I'll pull the line out of the handler for now.

**Comment by morph166955** [comment]
Also to note, I tried to return only thing thing uid for shield/google based on the comment here https://github.com/openhab/openhab-addons/pull/16191#discussion_r1450660535 and that didn't resolve that issue.  I'm not sure if it's possible to correlate across different thing types.

**Comment by jlaur** [comment]
> Also to note, I tried to return only thing thing uid for shield/google based on the comment here [#16191 (comment)](https://github.com/openhab/openhab-addons/pull/16191#discussion_r1450660535) and that didn't resolve that issue. I'm not sure if it's possible to correlate across different thing types.

Still, I think it should be fixed, I don't think it makes sense for both discovery services to support both thing types? At least it seems like it **could** cause some issues similar to the one you mentioned.

**Comment by jlaur** [comment]
Perhaps you could also simplify null annotation, now that you are at it. While reading both discovery classes the other day I noticed:
https://github.com/openhab/openhab-addons/blob/afb20ca473b1b329863a506ae1488066e2fba448/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java#L57

should be:
```java
public @Nullable DiscoveryResult createResult(ServiceInfo service) {
```

and:
https://github.com/openhab/openhab-addons/blob/afb20ca473b1b329863a506ae1488066e2fba448/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java#L94

should be:
```java
public @Nullable ThingUID getThingUID(ServiceInfo service) {
```

same for both classes.

**Comment by morph166955** [comment]
Easy enough, standby I'll push that now.

**Comment by morph166955** [comment]
> Perhaps you could also simplify null annotation, now that you are at it. While reading both discovery classes the other day I noticed:
> 
> https://github.com/openhab/openhab-addons/blob/afb20ca473b1b329863a506ae1488066e2fba448/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java#L57
> 
> should be:
> 
> ```java
> public @Nullable DiscoveryResult createResult(ServiceInfo service) {
> ```
> 
> and:
> 
> https://github.com/openhab/openhab-addons/blob/afb20ca473b1b329863a506ae1488066e2fba448/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java#L94
> 
> should be:
> 
> ```java
> public @Nullable ThingUID getThingUID(ServiceInfo service) {
> ```
> 
> same for both classes.

That causes this...

[WARNING] /raid/openhab-dev/androidtv-16223/openhab-addons/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java:[57,14] Redundant null check: comparing '@NonNull ServiceInfo' against null
[WARNING] /raid/openhab-dev/androidtv-16223/openhab-addons/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/GoogleTVDiscoveryParticipant.java:[94,14] Redundant null check: comparing '@NonNull ServiceInfo' against null
[WARNING] /raid/openhab-dev/androidtv-16223/openhab-addons/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/ShieldTVDiscoveryParticipant.java:[57,13] Redundant null check: comparing '@NonNull ServiceInfo' against null
[WARNING] /raid/openhab-dev/androidtv-16223/openhab-addons/bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/discovery/ShieldTVDiscoveryParticipant.java:[96,13] Redundant null check: comparing '@NonNull ServiceInfo' against null

**Comment by jlaur** [comment]
> Would it be cleaner to leave the Nullable in or to remove the null check after?

You can remove those null checks, that's why it's a simplification. 🙂

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
