### PR TITLE
Improved a number of the thread names

### PR DESCRIPTION
**Pull request by Hilbrand**
Related to #8216

### CODE REVIEW

**Review by kaikreuzer — CHANGES_REQUESTED** [review]
Thanks!
I'd like to suggest a slightly stricter naming convention (that is also followed in core bundles):
"The last segment should be camel case starting with small caps."
i.e. a
```
"OH-binding-" + uid + "-Caddx Communicator"
```
would become
```
"OH-binding-" + uid + "-caddxCommunicator"
```
Wdyt?

**Comment by t-8ch** [comment]
For my linuxinput binding I submitted #9582 to make it match more the expected thread names.

Would it make sense for the core to provide a utility function to generate those names or even spawn threads?

**Comment by robnielsen** [comment]
LGTM

**Review by robnielsen — APPROVED** [review]

**Comment by kaikreuzer** [comment]
> Would it make sense for the core to provide a utility function to generate those names or even spawn threads?

@t-8ch We have that already through the `NamedThreadFactory`. This should be used for executors through
```
Executors.newSingleThreadExecutor(new NamedThreadFactory("binding-xyz")
```
which many already do. Creating own Threads within bindings should rather be avoided as an executor with a continuously running job should work in most cases as well.

**Comment by t-8ch** [comment]
> @t-8ch We have that already through the `NamedThreadFactory`. This should be used for executors through
> ```
> Executors.newSingleThreadExecutor(new NamedThreadFactory("binding-xyz")
> ```

Thanks for the pointer with the `Executor` and the `ThreadFactory`.
For my binding for each `Thing` a thread is spawned. I'd like to have the thing UID as part of the thread name.
Would it make sense to extend `NamedThreadFactory` to support this usecase or should I roll my own?

**Comment by kaikreuzer** [comment]
Yes, including the ThingUID is indeed something you should do. Assembling the string can be done by yourself.
Btw, @Hilbrand summarised it nicely in https://github.com/openhab/openhab-addons/issues/8216#issue-667085148.

**Review by cpmeister — APPROVED** [review]
LGTM

**Review by kaikreuzer — APPROVED** [review]
Many thanks @Hilbrand!

**Pull request merged**
