### PR TITLE
[paradoxalarm] Implement zone bypass command and additional zone states

### PR DESCRIPTION
**Pull request by theater**
It's a request from a member of the community to implement a zone bypass functionality from within the OpenHAB. Has been tested by me and the customer. Additionally I enhanced a bit the unit tests.

- Zone bypass command
- 8 new zone special read-only states
- Refactoring of some classes and extraction in interfaces of logic common for partition and zone commands
- Changed RAM pages enumeration so the interfaces of the related methods always use enumeration from 0(as in all Java APIs) and not from 1(as in Paradox system)
- Fixed potential NPEs in several places from the static code scan maven warnings (more to come in separate PR if this one gets merged)
- Minor fixes and code clean up

### CODE REVIEW

**Comment by theater** [comment]
I wonder if someone could have a look at this PR? It looks like a lot of changes but not really... Just one feature added and some refactoring to fit better the new feature...

**Comment by theater** [comment]
@openhab/add-ons-maintainers Could someone have a look at the PR? I'd like to merge it sooner or later and it's pending for a lot of time. Also there is subsequent PR that's waiting a review together with this one and optimally if these two get merged, I would like to invest a little bit to remove all (as much as possible) of the warnings.

Thanks in advance,
Konstantin

**Comment by theater** [comment]
@fwolter Hi Fabian, I wonder if you could continue with the review so we can merge this PR? I already did the requested change a few weeks back...

**Review by fwolter — APPROVED** [review]
LGTM

**Pull request merged**
