### PR TITLE
[scripting] Adjust to core changes

### PR DESCRIPTION
**Pull request by J-N-K**
Related to https://github.com/openhab/openhab-core/pull/3255

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Review by ccutrer — APPROVED** [review]
JRuby changes look fine to me. I'm a bit worried about start level and orderings in the -core commit (this has been touchy this release cycle), but I don't know that I'll have to time test it out anytime soon. so I'm +1 on merging that, and when I have time I'll test, and if something's wrong, I'll fix it and write more tests ;).

**Review by florian-h05 — APPROVED** [review]
JS Scripting changes look good to me!
Together with the core PR this closed two really nasty issues.

I’ll see if I can try this out, but in case I don’t. +1 for merging from my side as well.

**Review by florian-h05 — APPROVED** [review]
LGTM, thanks!

I've tested this together with the core PR https://github.com/openhab/openhab-core/pull/3255, fixes the two core issues :+1:

**Comment by florian-h05** [comment]
Reference https://github.com/openhab/openhab-addons/issues/14019.

**Comment by J-N-K** [comment]
Not sure why the DCO check is not working.

**Comment by jlaur** [comment]
> Not sure why the DCO check is not working.

Strange indeed. Luckily I recognize your sign-off. 🙂

**Pull request merged**
