### PR TITLE
Fix Zigbee name stylization

### PR DESCRIPTION
**Pull request by jlaur**
Name was changed some years ago from ZigBee to [Zigbee](https://en.wikipedia.org/wiki/Zigbee). Maybe it's time to adapt.

See also:
- openhab/org.openhab.binding.zigbee#785

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
LGTM for Plugwiseha, also scanned the rest.

**Comment by mvalla** [comment]
LGTM for openwebnet

**Review by hmerk — APPROVED** [review]
LGTM for Wemo

**Review by wborn — APPROVED** [review]
Do you also plan to update this in the other repos? Such as:
* [openhab-docs](https://github.com/openhab/openhab-docs)
* [org.openhab.binding.zigbee](https://github.com/openhab/org.openhab.binding.zigbee)

**Comment by jlaur** [comment]
> Do you also plan to update this in the other repos?

I did not, but good point!

> * [openhab-docs](https://github.com/openhab/openhab-docs)

I didn't think this would be relevant, but now searched and found three strings to fix. They are all in developer contribution notes/examples, but nevertheless will create a PR for that.

> * [org.openhab.binding.zigbee](https://github.com/openhab/org.openhab.binding.zigbee)

This contained (not) surprisingly a massive amount of such strings! 😄 Created openhab/org.openhab.binding.zigbee#785 for that.

**Comment by wborn** [comment]
> They are all in developer contribution notes/examples, but nevertheless will create a PR for that.

I also noticed the ZigBee stylization is in the logo shown in the docs and UI, see:

https://next.openhab.org/addons/bindings/zigbee/

There are updated logos if you search for "zigbee logo".

**Comment by jlaur** [comment]
@wborn - too controversial to include in 3.4? :-)

**Pull request merged**
