### PR TITLE
[mqtt] Fix itests version number

### PR DESCRIPTION
**Pull request by bodiroga**
As requested in https://github.com/openhab/openhab-addons/pull/7206#issuecomment-682730688, I have created this PR to update the version number of the MQTT itests, so that @jochen314 doesn't need to do it. I can close the PR if he prefers to change them :+1: 

Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

### CODE REVIEW

**Comment by fwolter** [comment]
Could you fix also the tests, that they can be integrated in the normal build again?

**Comment by bodiroga** [comment]
> Could you fix also the tests, that they can be integrated in the normal build again?

Hi @fwolter! You are talking about the itests, right? I will have a look at them, but I started reading about JUnit two days ago :sweat_smile:

**Comment by fwolter** [comment]
Yes, because it makes less sense fixing the version number but letting the tests disabled.

**Comment by bodiroga** [comment]
> Yes, because it makes less sense fixing the version number but letting the tests disabled.

Ummmm... why were the tests disabled? I can see that Homie and HomeAssistant tests depend on the Embedded MQTT broker, which is no longer maintained and, as far as I know, is deprecated. @davidgraeff was the only one contributing to that bundle and he is not involved in the project anymore. I hardly doubt that I will be able to fix this :cry:

**Review by Hilbrand — APPROVED** [review]
LGTM

**Review by fwolter — APPROVED** [review]
Ok, then we adjust only the version numbers for now.

**Comment by Hilbrand** [comment]
If I remember correctly. The tests were disabled when we moved to the new build system. Initially there were some problems with dependencies and to get the itests up and running. I believe the mqtt wer still difficult to fix and never got fixed later on. So I'm guessing it's not something simple to fix, or at least requres so investigation. I would say it's ok to at least keep the version numbers in sync (I did it one time in the past). Hopefully someone will fix the tests some day...

**Pull request merged**
