### PR TITLE
[kodi] Added support for publishing ChannelDescriptionChangedEvents

### PR DESCRIPTION
**Pull request by cweitkamp**
- Added service references to `DynamicCommandDescriptionProvider` and `DynamicStateDescriptionProvider` to support publishing `ChannelDescriptionChangedEvent`s

Depends on https://github.com/openhab/openhab-core/pull/1505

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
one question for you @cweitkamp : when tagging "Activate" on the constructor, are we sure that the `activate` method of the parent class will be called ? This method is initializing the field `bundleContext`.

**Comment by cweitkamp** [comment]
Yes, if the `activate` method is annotated by `@Activate` too. OSGi framework calls every method after the bundle has been marked as being ready.

**Review by lolodomo — APPROVED** [review]

**Comment by lolodomo** [comment]
Thank you for the explanation.

**Comment by lolodomo** [comment]
Depening PR in core repo is now merged. So we are ready to merge this one.

**Review by kaikreuzer — APPROVED** [review]

**Pull request merged**
