### PR TITLE
[openweathermap] Undo PR #7692

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
My PR #7692 was a bad idea because the owm binding implements an unusual bridge / thing status management. We have to revert it, this is the object of this new PR.

**Comment by lolodomo** [comment]
Unfortunately I removed a log added the same day with merged PR #7830

**Comment by cweitkamp** [comment]
> Unfortunately I removed a log added the same day with merged PR #7830

@lolodomo Are you going to readd it?

**Comment by lolodomo** [comment]
As I am preparing a PR for handler factory with constructor injection, I will restore your log in this PR.

**Comment by lolodomo** [comment]
@cweitkamp : your log  is restored in PR #7839

**Pull request merged**
