### PR TITLE
[homekit] allow RelativeHumidity as an optional characteristic on Thermostat

### PR DESCRIPTION
**Pull request by ccutrer**
also support QuantityType as a valid state type for double characteristics (such as RelativeHumidity).

### CODE REVIEW

**Comment by lolodomo** [comment]
@yfre  : maube you can make a first review

**Review by yfre — APPROVED** [review]
LGTM

**Comment by yfre** [comment]
@ccutrer indeed, according to homekit spec, thermostat supports humidity as optional characteristic. not sure why i missed it. thanks for fixing it.

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
