### PR TITLE
New Presence binding

### PR DESCRIPTION
**Pull request by mdabbs**
New 'Presence' Binding geared more towards the detecting the presence of cell phones on a local network.

This new binding is geared more towards the detection of the presence of cell phones and other network devices. While it is similar to the Network binding, the Presence binding is more specific and has better detection methods that work better with cell phones than the Network binding. It is also more specific to just presence detection rather than generic network utilities.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> While it is similar to the Network binding, the Presence binding is more specific and has better detection methods that work better with cell phones 

I would much prefer to add those improved detection methods to the network binding as this is used for such purposes. Also, many technical details, prerequisites and challenges (such as ARPing) seem to be fairly similar here.

Note that we structure the bindings by used technology, not by use case.

Would it be possible to improve the network binding with your logic instead?

**Comment by mdabbs** [comment]
I actually spoke with the author of the network binding. They mentioned that having a separate binding made more sense because network binding was not originally designed for presence, it just happened to get used for that. Having a specific Presence binding means that it alone could be expanded with other technologies that would cause it to diverge away from network-related technologies. Its just that right now, it uses some similar tools.

**Comment by mdabbs** [comment]
I found the link from who I thought was the Network binding author: https://community.openhab.org/t/adventures-implementing-reliable-network-detection-using-arping/62202/27?u=mdabbs1

**Comment by kaikreuzer** [comment]
No, Rich is not the maintainer of the Network binding. 
It is @davidgraeff and @mettke, see https://github.com/openhab/openhab-addons/blob/2.5.x/CODEOWNERS#L116.

> Having a specific Presence binding means that it alone could be expanded with other technologies 

This again shows that it does not fit as a binding. Yes, presence detection is a complex beast, so you could end up using complex network stuff, bluetooth, Wifi-router features, KNX motion detectors, Z-Wave doorlocks, etc... As mentioned above, a binding should stick to a single type of technology and this is in your situation clearly the network stuff, so improving the network binding makes most sense.

And if I read Rich's comment correctly, this is what he says as well - and that existing features must not be broken by adding new features.

**Comment by mdabbs** [comment]
OK, no worries. I'll close this PR then. I don't think I'll wade into the network binding since its architecture is a bit different than mine and I might have to really gut it and I'm not capable of recreating all of its functionality.

**Pull request closed without merging**
