### PR TITLE
[miio] Add Roborock S7/S7MaxV mop mode

### LINKED ISSUE #16607: [miio] Roborock S7/S7MaxV: add support for the MopMode feature
The miio binding currently does not support the MopMode feature available for the Roborock S7/S7MaxV vacuum cleaners.

This feature is also referenced as "Mop Route" and explaination from Roborock can be found [here](https://support.roborock.com/hc/en-us/articles/900005516986-What-s-the-difference-between-Standard-Mop-Route-and-Deep-Mop-Route)

It is also referenced in the python-miio project: https://python-miio.readthedocs.io/en/latest/api/miio.integrations.roborock.vacuum.vacuum_enums.html#miio.integrations.roborock.vacuum.vacuum_enums.MopMode

### PR DESCRIPTION
**Pull request by rsopp**
This PR adds the mop mode feature found in the Roborock S7 vacuum cleaners.
Closes #16607

### CODE REVIEW

**Review by lsiepel — COMMENTED** [review]
Would it be possible to have a full list of possible mop modes? These could be added as option to the channel-type, making translation / UI-support possible.

**Comment by marcelrv** [comment]
Thanks for your contribution!

Indeed suggest to add the options , so in the UI you don't see the numbers like 300 but indeed a proper description. 
example here: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml#L312-L326

Likewise, I think the option is still missing in the translation file:

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties

**Comment by rsopp** [comment]
Thanks for the suggestions! I just added the options for the mop mode.

Maybe, it would be a good idea to also add options for the other modes of the vaccum (fan power, water box mode) in another PR?

**Comment by marcelrv** [comment]
> Thanks for the suggestions! I just added the options for the mop mode.
> 
> Maybe, it would be a good idea to also add options for the other modes of the vaccum (fan power, water box mode) in another PR?

yes, it it, at least for the water box mode..
If I recall right, for the fan power I declined to do it as different models have different meaning for the numeric values.
The best way to solve that would be to create the options dynamic based on the model... but I never considered it that important to add that complexity.

**Review by marcelrv — APPROVED** [review]

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
