### PR TITLE
Use activation-api 1.2.1_3

### LINKED ISSUE #10642: [tellstick] binding fails to start after upgrade to OH3.1.0 M4
[tellstick] binding fails to start after upgrade to OH3 M4, worked fine in M3.

## Expected Behavior
Openhab should start normally and load the Tellstick binding without errors.

## Current Behavior
After upgrade Openhab log says it cannot download file and Openhab server will not start. it gets stuck on this. mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.activation-api-1.2.1/1.2.1_2

I removed all bindings from the addons.config and Openhab starts. I added binding one by one until the error reoccured during tellstick binding installation.

```
2021-05-03 10:05:20.372 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-tellstick': Error:

	Error downloading mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.activation-api-1.2.1/1.2.1_2

```

## Possible Solution
Workaround to remove tellstick binding from addons.config and leave the rest there. Openhab starts, but tellstick does not work.

## Steps to Reproduce (for Bugs)
1. Upgrade to OH3 M4
2. Or install tellstick binding to OH3 M4

## Your Environment
Raspberry PI4 
OH3.1.0 M4

### PR DESCRIPTION
**Pull request by wborn**
Fixes #10642

Related to https://github.com/openhab/openhab-core/pull/2292, https://github.com/openhab/openhab-distro/issues/1256

### CODE REVIEW

**Comment by cweitkamp** [comment]
Maybe I am dumbfounded again - why does it work for mail and pushbullet but not for tellstick? Don't we have to change these feature files too?

https://github.com/openhab/openhab-addons/blob/e24d43aecbcfc5af551c8e9087d9be6992e5c69a/bundles/org.openhab.binding.mail/src/main/feature/feature.xml#L8

https://github.com/openhab/openhab-addons/blob/e24d43aecbcfc5af551c8e9087d9be6992e5c69a/bundles/org.openhab.binding.pushbullet/src/main/feature/feature.xml#L7

**Comment by wborn** [comment]
Yes I can explain this. It seems like @kaikreuzer only uploaded 1.2.1_3 to the online repo, see:

https://openhab.jfrog.io/artifactory/libs-release/org/apache/servicemix/specs/org.apache.servicemix.specs.activation-api-1.1/

https://openhab.jfrog.io/artifactory/libs-release/org/apache/servicemix/specs/org.apache.servicemix.specs.activation-api-1.2.1/

So @kaikreuzer can also fix for the M4 by uploading the old dependency. :slightly_smiling_face:

**Comment by kaikreuzer** [comment]
> So @kaikreuzer can also fix this for the M4 by uploading the old dependency. 🙂

Sorry, what is currently broken and what old dependencies are exactly required...?

**Comment by wborn** [comment]
The Tellstick Binding does not work in 3.1.0.M4 as described in the linked issue (https://github.com/openhab/openhab-addons/issues/10642) because the online repo does not have 1.2.1_2. So this PR fixes it by using 1.2.1_3 instead of 1.2.1_3. But you could also fix it for 3.1.0.M4 by adding 1.2.1_2.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Comment by jorkki22** [comment]
> 
> 
> The Tellstick Binding does not work in 3.1.0.M4 as described in the linked issue (#10642) because the online repo does not have 1.2.1_2. So this PR fixes it by using 1.2.1_3 instead of 1.2.1_2. But you could also fix it for 3.1.0.M4 by adding 1.2.1_2 to the online repo.

Sorry, not so familiar with github. The ticket is now closed, does this mean this will be fixed later possibly in M5, but not in M4? If so is there any workaround for making tellstick binding work before that?

**Comment by wborn** [comment]
> does this mean this will be fixed later possibly in M5, but not in M4

Yes, unless 1.2.1_2 is uploaded to the online repo.

> If so is there any workaround for making tellstick binding work before that?

The missing dependency is part of the offline addons KAR file. I.e. you can use that by downloading [openhab-addons-3.1.0.M4.kar](https://openhab.jfrog.io/artifactory/libs-milestone-local/org/openhab/distro/openhab-addons/3.1.0.M4/openhab-addons-3.1.0.M4.kar) to your `/addons` dir. If you use an APT based deployment you can also install it with: `sudo apt-get install openhab-addons`

The online installation should also work again if you switch to the 3.1.0 snapshots.

**Comment by kaikreuzer** [comment]
> Yes, unless 1.2.1_2 is uploaded to the online repo.

I just uploaded it, so everything should be fine now for M4 as well!

**Pull request merged**
