### PR TITLE
[freeboxos] Fix command handling for DECT thing type

### PR DESCRIPTION
**Pull request by lolodomo**
Related to comment in #17262

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by clinique — APPROVED** [review]
Apart from the fact that you seem to dislike enums, I approve. I like them because it a convenient way to document what's known of a given value.

**Comment by lolodomo** [comment]
> Apart from the fact that you seem to dislike enums, I approve. I like them because it a convenient way to document what's known of a given value.

It is not that I dislike enums, it is just that it can't work at it was. If you have a better solution, I am open.
Maybe one solution would be inside the Gson configuration to lowercase any enum when building the JSON ? If you know how to do that, I let you do and you can even restore the enums where I remove them to make the APIs working.

**Comment by clinique** [comment]
Write a dedicated deserializer is an option but this would have a binding-wide impact, needed many checks to ensure it has no side effects somewhere else. 
The simpler is : 
```
    public enum Type {
        @SerializedName("fxs")
        FXS,
        @SerializedName("dect")
        DECT,
        UNKNOWN
    }
```

**Comment by lolodomo** [comment]
> The simpler is :
> 
> ```
>     public enum Type {
>         @SerializedName("fxs")
>         FXS,
>         @SerializedName("dect")
>         DECT,
>         UNKNOWN
>     }
> ```

With that, when serializing, FXS enum will then be converted into "fxs" ?
In that case, that would be the perfect solution.

**Comment by lolodomo** [comment]
I am going to try on the other places I previously changed something.

**Comment by lolodomo** [comment]
Tested and working for playing media, so I will update that PR and create other PRs for the previous changes I made.

**Comment by lolodomo** [comment]
@clinique : changed

**Review by clinique — APPROVED** [review]

**Review by clinique — APPROVED** [review]

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
