### PR TITLE
[homeconnect] 2 channels added for washer appliance

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Code is based on PR #10990 so we have to wait for the merge of this other PR and then I will rebase this PR.
During this time, the code can already be reviewed.

**Review by bruestel — COMMENTED** [review]
LGTM lets wait for the other two PRs to be merged.

**Comment by kaikreuzer** [comment]
@lolodomo This seems to require a rebase now.

**Comment by lolodomo** [comment]
> @lolodomo This seems to require a rebase now.

I will wait for the merge of PR #11069 before rebasing.

**Comment by lolodomo** [comment]
Rebase is now done. No more conflicts.

**Review by bruestel — APPROVED** [review]

**Review by kaikreuzer — APPROVED** [review]

**Pull request merged**
