### PR TITLE
[dwdunwetter] Improve server problem handling 

### PR DESCRIPTION
**Pull request by lsiepel**
- Fixed https://github.com/openhab/openhab-addons/issues/14691
- Add some unit tests
- Add country tag to addons.xml

Used it for a couple of days and had no problem.

Test jar 4.1.0 here: https://1drv.ms/u/s!AnMcxmvEeupwjrMmX76PHq61-JUHFQ?e=K0E0TR

### CODE REVIEW

**Review by daMihe — COMMENTED** [review]
Generally, it looks like a simple approach to pre check some data. Currently you are testing only for `<?xml` which is quite generic. What do you think about extending this check to some words which appear in every download, e.g. `FeatureCollection`?

**Comment by lsiepel** [comment]
> 

It is not meant to check data correctness. It is a check only to determine of the service works under normal conditions. If the output is xml, it can be assumed to be correct according to the API documentation. If it is not XML, the service is down, degraded, in maintenance or similar.
Validating the XML itself is a different use case. Could be usefull, would also cause a lot of overhead. Anyway i have not seen DTD to use for validation, so i left a more complex check out of this pr.

**Comment by daMihe** [comment]
Sure, that's something i would not expect in smallest detail. But as HTML (showing an Error) can be valid XML including the `<?xml` tag, a little meta check would be nice. That does not mean the code should parse anything in detail but instead looking for some magic strings (like libmagic is doing for content type detection) for the API. I thing that's little effort to get a possibly significant better result.

**Review by daMihe — APPROVED** [review]
Okay. A quick functional test did also work.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
