### PR TITLE
Update Shelly and Tradfri bindings for upgrade to Californium 2.7.3

### PR DESCRIPTION
**Pull request by wborn**
* Fixes deprecated API usages
* Resolves itest runbundles

Depends on openhab/openhab-core#3085

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]

**Comment by markus7017** [comment]
@wborn Could it be that the Shelly snapshot build doesn't work on 3.4 M2, because auf the changed dependencies?
What was the need to bump the version?
Did somebody tried if the Shelly and Trade bindings work at all with this change?

**Comment by wborn** [comment]
> Could it be that the Shelly snapshot build doesn't work on 3.4 M2, because auf the changed dependencies?

Yes the snapshot addons using Californium now have a "[2.7,3)" version range for the org.eclipse.californium bundles.

> What was the need to bump the version?

2.5 years worth of bug fixes and improvements. For details see: https://projects.eclipse.org/projects/iot.californium/governance

> Did somebody tried if the Shelly and Trade bindings work at all with this change?

AFAIK all the Califirnium 2.x releases contain only bug fixes and minor improvements. The more breaking changes are in the 3.x releases. I haven't seen any community topics or GitHub issues about issues in the snapshot versions of these add-ons since this got merged 2 weeks ago. Maybe you can also give it a try?

**Comment by markus7017** [comment]
It seems to run fine in the IDE, but 3.4M2 reports unreasonable external package.

that means that
- I need a build for 3.3+3.4 M1+M2 referencing 2.0.0 and
- a build for 3.4 M3+ referencing 2.7.3
correct?

**Comment by markus7017** [comment]
nope, if I build with -Dohc.version=3.3.0 I get
`
[caused by: Unable to resolve openhab-binding-shelly/3.4.0.SNAPSHOT: missing requirement [openhab-binding-shelly/3.4.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.shelly; type=osgi.bundle; version="[3.4.0.202210060649,3.4.0.202210060649]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.shelly/3.4.0.202210060649: missing requirement [org.openhab.binding.shelly/3.4.0.202210060649] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.eclipse.californium.core)(version>=2.7.0)(!(version>=3.0.0)))"]]
`
I the IDE I could see that there are references to Californium 2.7.3

I also changed the dependencies to
`
	org.eclipse.californium.core;version='[2.0.0,2.0.0)',\
	org.eclipse.californium.element-connector;version='[2.0.0,2.0.0)'
`
same

How could I trigger the dependency resolution on the CLI?

**Comment by wborn** [comment]
IIRC on Windows such build options only work if you enter them before Maven goals. You can also update the `ohc.version` property in the root POM to get the same behavior.

https://github.com/openhab/openhab-addons/blob/31820ad74032ba14da5bd66c27bcc7f82a376dfe/pom.xml#L71

I've also seen it happen that a Maven CLI generated bundle JAR is automatically overwritten by one that is build by an IDE that was still open which got triggered by a file change.

**Comment by markus7017** [comment]
ok, build works

I did `mvn dependency:resolve -Dohc.version=3.3.0`and then `man clean install -Dohc.version=3.3.0`,
but maybe the "stop automatic IDE build" was the more important part  :-)

Now I need to test

**Pull request merged**
