### PR TITLE
[jsscripting] Implement `javax.script.Compilable`

### PR DESCRIPTION
**Pull request by florian-h05**
- Restructure POM and add comments to POM.
- Use OPENHAB_TRANSFORMATION_SCRIPT constant instead of introducing our own.
- Implement `javax.script.Compilable` in preparation for https://github.com/openhab/openhab-core/pull/4289.

### CODE REVIEW

**Comment by digitaldan** [comment]
This looks cool, is this to speed up the first run of scripts ?

**Comment by florian-h05** [comment]
@jlaur Would be cool if you could review this - it currently does not bring a benefit but it is required for https://github.com/openhab/openhab-core/pull/4289 to have an actual performance impact on UI-based JS scripts.

**Comment by florian-h05** [comment]
Okay haha my core PR was just merged, so this does have an impact as soon as it is merged.

**Review by jlaur — APPROVED** [review]
Cool, thanks!

**Pull request merged**
