### PR TITLE
[mqtt] Add documentation about using auto discovery with Tasmota

### PR DESCRIPTION
**Pull request by cmorty**
I got most of this information from https://community.openhab.org/t/oh3-tasmota-via-mqtt-autodiscovery/111630.
IMO at least the gist of it should be in the documentation to help others.
Should I also link the forum? Did I get everything right?

### CODE REVIEW

**Comment by lolodomo** [comment]
You are mentioning a specific device for a very generic binding, I am not sure that it is the right place.
We also have this other README for HomeAssistant binding which already mention some of your points:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.mqtt.homeassistant/README.md
Maybe you should rather update the other file ?

**Comment by cmorty** [comment]
@lolodomo : You are absolutely right. - I'll get to it. :)

**Comment by cmorty** [comment]
@lolodomo : Ok. Fixed it. I also did some minor formatting. It's in an extra commit so I can remove it in case it's too much. :-)

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Can you try to provide a proper "signed-off" ?

**Pull request merged**
