### PR TITLE
[netatmo] Make thing offline if API returns unreachable

### LINKED ISSUE #8162: [netatmo] Thing is displayed as online but the device is offline
I have a Presence camera which is currently not power connected, but the thing is displayed as online.

I would expect that it is displayed as offline, when it isn't available.

Possible solution: The Netatmo /gethomedata endpoint returns the camera with "status" : "disconnected" instead of "on". I would expect that this information is used to determine the thing status.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #8162

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by Hilbrand** [comment]
Is this still wip?

**Comment by lolodomo** [comment]
Yes, not yet finished.

**Comment by lolodomo** [comment]
@Hilbrand : Ok let's go with this PR. I will possibly provide an additional PR in the future.

**Review by Hilbrand — APPROVED** [review]
LGTM

**Pull request merged**
