### PR TITLE
[openwebnet] add support for basic Scenarios (WHO=0)

### PR DESCRIPTION
**Pull request by mvalla**
This PR adds support for basic Scenarios (WHO=0) to the OpenWebNet binding.
With this enhancement it will be possible to detect scenario activation events on the BUS to trigger rules in openHAB: openHAB becomes a very powerful scenario manager activated by physical BTicino scenario modules and buttons.
This will solve https://github.com/openhab/openhab-addons/issues/11378.

(This PR continues from #12847 on a new branch)

### CODE REVIEW

**Review by lolodomo — CHANGES_REQUESTED** [review]
Only few minor comments, mainly for i18n properties.
Remember you  can simply run "mvn i18n:generate-default-translations" to update it

**Comment by lolodomo** [comment]
There might be a bug in the i18n generation tool as I have the feeling the options for a trigger channel type are not considered.
@wborn @cweitkamp for information

**Comment by mvalla** [comment]
> There might be a bug in the i18n generation tool as I have the feeling the options for a trigger channel type are not considered.

@lolodomo what should I do with this trigger options default translation ? Indeed they are not automatically generated by the "generate-default-translations" command. 
Shall I add them manually? If yes, what is the correct syntax?

**Comment by lolodomo** [comment]
I have the strange feeling internalization of trigger channels is not yet implemented in the core framework. 
So maybe, you can ignore my comments.

**Comment by lolodomo** [comment]
I add in my TODO list to add internationalization of trigger options in the core framework. 
So forget my comments about trigger events.

**Comment by wborn** [comment]
Doesn't look like any other binding has translations for event options. I don't know if they are used/translated for UIs. If so, I would expect properties for such translations to be similar to the state options, e.g.:

`channel-type.openwebnet.scenarioEvent.event.option.SCENARIO_01 = Scenario 1`

**Comment by lolodomo** [comment]
@mvalla : you marked my comments as resolved without pushing any new code.

**Comment by mvalla** [comment]
ok I added manullay default translations for event options . 
Do not know how they render on UI considering also that these are trigger events and not states. I guess if you do not correct the auto-gen script these will be overwritten if the script is called again, right?

I also made other requested changes. So for me this can be merged now.

**Comment by lolodomo** [comment]
> ok I added manullay default translations for event options.

Sorry, I was probably not clear enough. This is something not yet implemented in the core framework. Including and forcing to translate them makes no sense now. So please keep them but comment them.

**Comment by mvalla** [comment]
Ok, now I have commented the event options translations.
For me this PR is ready to be merged.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
