### PR TITLE
[kaleidescape] Remove Apache StringEscapeUtils

### PR DESCRIPTION
**Pull request by mlobstein**
Replace StringEscapeUtils.unescapeHtml4() with basic Java methods to address #7722. Also a couple very minor tweaks that I have had pending for some time now.

### CODE REVIEW

**Comment by lsiepel** [comment]
The code looks good. Only thing is, i can't tell if it handles all required cases.  `StringEscapeUtils.unescapeHtml4` handles ~290 different cases. 
It would be really helpfull if a unit test was provided. Throwing in some examples into the stringformatter method.

**Review by lsiepel — COMMENTED** [review]
The code looks good. Only thing is, i can't tell if it handles all required cases. StringEscapeUtils.unescapeHtml4 handles ~290 different cases.
It would be really helpfull if a unit test was provided. Throwing in some examples into the stringformatter method.

**Comment by J-N-K** [comment]
IIRC we use unbescape in other add-ons

**Comment by lsiepel** [comment]
> IIRC we use unbescape in other add-ons

And we try to get rid of them. Would be nice to have such a utility function in core. Please see https://github.com/openhab/openhab-addons/issues/7722#issuecomment-1434669804

**Comment by J-N-K** [comment]
If you scroll up in that issue, you can see that this es exactly the reason why we introduced unbescape. It‘s hard to get it right.

**Comment by lsiepel** [comment]
> hat issue, you can see that this es exactly the

Totally agree, unbescape got somewhat burried in that topic. i re-read and allready got a PR for BSBLAN with that dependency. Would be nice if someone could have commented in that topic about my30+ PR's though.

**Comment by mlobstein** [comment]
I added some tests. This implementation only needs to un-escape the Latin-1 characters as described in the protocol reference manual:
image

**Review by lsiepel — APPROVED** [review]
lgtm

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
