### PR TITLE
[icloud] dynamic certificates

### PR DESCRIPTION
**Pull request by hoeckxer**
As apple is frequently (increasingly) updating the certificate on the server-side, users are more often confronted with a non-functioning iCloud binding.
One of the issues here is that the certificate that is used to verify the server (SSL handshake) is stored statically in the codebase. This means that every time the certificate is changed, a new certificate needs to be included in the codebase (with all the work that comes with it).

This pull request changes the code so that it dynamically retrieves the certificate from the server when needed. The only loophole is that there is no check on the client-side that it's the correct certificate. On the other hand, from what I could tell from the last couple of manual updates, this wasn't being done anyway. If needed, this can be achieved in the future by using a specialised trustmanager to verify the certificate is issues by a trusted party.

With this PR, the binding now works as following with regards to certificates:
* When the binding is started, it checks to see if the file {OPENHAB_DIR}/userdata/tmp/fmipmobile.crt is present. If it exists, it will use this for connecting. This will always allow a user to manually override the certificate should it ever be necessary
* In case it doesn't find this file, it will automatically retrieve the latest certificate and place this in the aforementioned file
* When connecting to the server, it uses the certificate that is last retrieved. In case the request fails with an SSLHandshakeException, it will try to proactively update the certificate again, and retry the request. It will only try to update the certificate once during the course of the request, to prevent the code from getting in an infinite loop
* In case the connection still fails after updating the certificate, the items will go offline. On the next attempt, it will simply try to retrieve a new certificate again, thereby rendering any manual action unnecessary

Please note that I've also added some extra logging, and cleaned up some minor things.

Any suggestions on how the code needs to be improved would be good. I've asked users to try out the snapshot https://drive.google.com/open?id=1qoNP4PlFAcAwtu9w9ydYwtJSdMymkzV7 in thread https://community.openhab.org/t/icloud-ssl-issue-again/79182/157. So far reports seem to be positive.

### CODE REVIEW

**Comment by paulianttila** [comment]
First of all, thanks for PR and I know this issue is huge problem for the users (I'm using it as well). 

I think we should consider automatic certification renewal twice as it's a security flaw. Binding will automatically trust all server certificates, so it doesn't prevent "man in the middle" attacks anymore (user iCloud credentials could be sent to 3rd party).

At least feature should be configurable option and user could enable this feature by knowing consequences.

**Comment by hoeckxer** [comment]
> First of all, thanks for PR and I know this issue is huge problem for the users (I'm using it as well).
> 
> I think we should consider automatic certification renewal twice as it's a security flaw. Binding will automatically trust all server certificates, so it doesn't prevent "man in the middle" attacks anymore (user iCloud credentials could be sent to 3rd party).
> 
> At least feature should be configurable option and user could enable this feature by knowing consequences.

That is my concern as well (as mentioned), but on the other hand nobody is checking the certificates that were installed over the past year as far as I've heard. I could make the dynamic retrieval configurable; in that case people can still actively update the certificate themselves by updating the used .crt file, or they can decide if they want to allow the dynamic retrieval. Is there any way that we can check the source of the certificate; eg is the certificate signed & verifiable by a static key?

**Comment by martinvw** [comment]
Doesn’t it use the same root certificate? I thought the root certificate has a very long validity. And the time I included i of course validated the correctness before creating a PR. 

I would be really happy to have resolved but agree that the current implementation imposes a security issue.

 Did you look into using the root certificate or can you look into it. 

Thanks for your efforts!

**Comment by paulianttila** [comment]
Certificate in binding bundle seems to be the server certificate itself, not Root CA or Apple sub CA what it should be. iCloud binding should trust Apple Root CA or at least Apple Server authentication CA.

**Comment by J-N-K** [comment]
Maybe it has been replaced with a wrong certificate? I think we should not use a trust-all for external connections where important credentials are used.

**Comment by martinvw** [comment]
The first time I worked on it it failed when I tried to use the the root certificate. I did not investigate that much further later on.

**Comment by martinvw** [comment]
The first time it broke down was because they switched from a normal certificate signed by a known CA to the self signed. After that I was not able to get it working using the Root / apple ca certificate so ended up using the server certificate planning to refresh it once per year however it feels that it is now more than once per year.

**Comment by hoeckxer** [comment]
Thanks for the feedback. I'm happy to investigate if we can check the root certificate, I agree that we shouldn't allow all certificates. I need some time to dive into it, I'll report back when I've got an answer.

**Comment by martinvw** [comment]
I just checked and the Apple Root CA is still valid till 2035 so if we could validate against that it would be awesome.

Schermafbeelding 2020-01-31 om 08 01 33

If you want I can also try to take a further look, thanks again for your work to resolve this!

**Comment by hoeckxer** [comment]
@martinvw I can work it out no problem, but thanks :)

**Comment by maihacke** [comment]
Please see here: https://community.openhab.org/t/icloud-ssl-issue-again/79182/187?u=maihacke
I created a jar with apples CA cert, which seems to work: https://drive.google.com/open?id=1fUTq9kqfAqYhLuW7qJypom2HiSRBsOK-

**Comment by hoeckxer** [comment]
I updated the code so that it verifies the presented certificate up the certificate chain up to the root CA certificate, which is included in the bundle.

I'm intrigued by @maihacke 's solution though; can you expand on if you included the server CA certificate, or the root certificate?

@martinvw how do you think we should move forward?

**Comment by maihacke** [comment]
@hoeckxer The certificate chain for the fmipmobile service contains at least three certificates. The first is issued for fmipmobileX.apple.com. This certificate was included in the bundle before my change.
The certificate is issued by „ Apple Server Authentication CA“. This is the CA which certificate is now in the bundle.
The certificate is signed by Apple Root CA. This cert is not part of the bundle.

**Comment by maihacke** [comment]
I would prefer including the required certificates in the bundle and not go for a solution which downloads certificates by itself.
By the Apples Root CA certificate is available here https://www.apple.com/certificateauthority/

**Comment by hoeckxer** [comment]
@maihacke using the CA certificate Apple Server Authentication CA is actually just as unsafe, as this certificate is included in the response sent by the server. This means that this certificate can be mimicked by hackers just as easily. The correct approach I think now is to provide the only certificate in the chain that is not sent by the server (these can be hacked after all), which is Apple's Root CA certificate. I've made this change on a new branch, which seems to work just fine. I've created pull request https://github.com/openhab/openhab-addons/pull/6948 for this new change. As far as I'm concerned this is the right way to go, and we should abandon this pull request (unless we run into serious issues with the other change, but I don't think so).

**Comment by maihacke** [comment]
No that is not correct. An attacker could not create a certificate matching the hosts DNS name. For that he would need the private key of Apples CA cert.

**Comment by J-N-K** [comment]
See #6948

**Comment by hoeckxer** [comment]
@maihacke using the server certificate in the binding would indeed work to check against, I misinterpreted my expectations. This would provide a longer valid certificate and a working binding. While we're at it I think it would be better though to use the root certificate to check against, as this is valid for an even longer period.

**Pull request closed without merging**
