### PR TITLE
[km200] check if negativeSwitch is "on" and positiveSwitch is "off. If so: just

### PR DESCRIPTION
**Pull request by truidix**
# Title
Fix for KM100 with Firmware 04.08.02

# Description
With KM100 and firmware 04.08.02 some negativeSwitch having the value "on". As this is not expected, the binding is throwing an exception. I added a condition on an existing if clause, so there is just a warning and the binding is working again.

### CODE REVIEW

**Review by Markinus — APPROVED** [review]
Ok for me

**Review by jlaur — APPROVED** [review]
LGTM - thanks.

**Comment by jlaur** [comment]
@truidix - please fix DTO, after that we are ready to merge.

**Comment by truidix** [comment]
@jlaur  sry for missing DCO.  I just added it and changed the name.

**Comment by jlaur** [comment]
@truidix - thanks! Actually I meant the PR title, not the title within the PR description. Only the PR title itself will be extracted for the release notes, so you are free to add any details you'd like in the PR description.

**Pull request merged**
