### PR TITLE
[hue] Fix NUPnP discovery

### PR DESCRIPTION
**Pull request by jlaur**
First commit from #14871 cherry-picked.

### CODE REVIEW

**Comment by jlaur** [comment]
@lolodomo - this is a 3.4 backport of #14871 based on same commit, but omitting the second commit from that PR which updated the `connection`. Perhaps you could consider this as well?

**Comment by lolodomo** [comment]
If the integration tests are failing, it looks not reasonable to merge ? It will then break the preparation of next 3.4 release ?

**Comment by jlaur** [comment]
> If the integration tests are failing, it looks not reasonable to merge ?

The question (to which I don't have an answer yet) is why they are failing. I suspect it's unrelated to these changes, since they didn't fail the integration tests in the main branch.

**Comment by jlaur** [comment]
@lolodomo - unrelated, see #14948 and https://ci.openhab.org/job/PR-openHAB-Addons/15513/

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Ok, so I merge, I just hope that @kaikreuzer will not kill us when he will start the build of branch 3.4.x ;)

**Comment by jlaur** [comment]
@lolodomo - in case of any killing, we should have a chance of avoiding it since something else must have broken the integration tests. 😉

**Pull request merged**
