### PR TITLE
[shelly] fix NumberFormatException on Shelly2RelayStatus.timerDuration

### PR DESCRIPTION
**Pull request by spledl**
- If 'Auto OFF' mode is enabled on a Shelly Plus 1 device and set to a value with decimal places a status update throws an NumberFormatException.

  Changed timerDuration/timer_duration from Integer to Double fixes the problem.

```
Unable to create object of type Shelly2DeviceStatus$Shelly2DeviceStatusResult from JSON 
(syntax/format error: java.lang.NumberFormatException: Expected an int but was 1.25 at line 1 column 211 path $.switch:0.timer_duration): 
{
   ...
   "switch:0":{
      "id":0.0,
      "source":"HTTP_in",
      "output":true,
      "timer_started_at":1.72366902863E9,
      "timer_duration":1.25,
      "temperature":{
         "tC":45.8,
         "tF":114.4
      }
   },
   ...
}

```

### CODE REVIEW

**Comment by lolodomo** [comment]
Did you check there is nothing to change where `timer_duration` is used in the code ?

**Comment by jlaur** [comment]
> Did you check there is nothing to change where `timer_duration` is used in the code ?

It is unused, but there are other similar DTO's still defined as `Integer` and being used:

https://github.com/openhab/openhab-addons/blob/d18a6c1cda0539e26e45f0dcf5a2afd0918cdc5c/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java#L583

https://github.com/openhab/openhab-addons/blob/d18a6c1cda0539e26e45f0dcf5a2afd0918cdc5c/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java#L875

So currently the fix is harmless, but I wonder if the other DTO's would suffer the same problem, and what the value actually means. 1.25 seconds? @markus7017 - did you see this PR?

**Comment by lsiepel** [comment]
@spledl does it make sense to also adjust the other DTO's as suggested by jlaur?

**Comment by spledl** [comment]
@lsiepel
I think it would make sense, but i have no such shelly equipment to test this.

**Comment by jlaur** [comment]
@markus7017 - can you please comment?

**Comment by J-N-K** [comment]
I did check what happens: IMO the timer handling should be refactored. 

First `now()` is called which returns `System.currentTimeMillis() / 1000L)`, essentially truncating the system's time to full seconds. Then `timerStartedAt`(which is a `Double`) is converted to a `Long` (again truncating to full seconds), subtracted from `now`. The result is the timespan that is already used from the timer and is subtracted from the `timerDuration` which results in the time still left for the timer to complete. 

It would be more accurate to use `double now = System.currentTimeMillis() / 1000.0;` and then calculate `(int) (timerDuration + timerStartedAt - now)` as final result.

**Review by J-N-K — APPROVED** [review]
Thanks! See #17689 for follow-up PR.

**Pull request merged**
