### PR TITLE
[mikrotik] OH2.5 Mikrotik RouterOS Binding - Initial contribution

### PR DESCRIPTION
**Pull request by duhast**
[Mikrotik](https://mikrotik.com/products) equipment is pretty popular in many countries afaik, and I saw some interest on integrating those devices with OpenHAB around the internet. So when I felt the need for it myself, I've decided to develop this binding.

Overall, it should be ready for the public use after applying some improvements and more testing. Meanwhile I'd like to get some code recommendations and general feedback.

Full readme [is available here](https://github.com/duhast/openhab-addons/blob/mikrotik/bundles/org.openhab.binding.mikrotik/README.md) and pre-built JARs are under [Github releases](https://github.com/duhast/openhab-addons/releases).
Also I've put up a [Github project board](https://github.com/duhast/openhab-addons/projects/1) for myself to track progress and note down TODOs.

And I've started [a community thread](https://community.openhab.org/t/oh2-mikrotik-routeros-binding-initial-contribution/115241) as well.

### CODE REVIEW

**Comment by Hilbrand** [comment]
Thank you for adding this binding. A first feedback is that you need to submit new code/bindings against openHAB 3 branch. No new bindings will be merged on the 2.5.x branch.

**Comment by duhast** [comment]
Yeah, I'm going to port the binding to v3 codebase soon after I'll do some updates and upgrade my home OH instance from v2.11.

**Comment by duhast** [comment]
Hello @Hilbrand !
I've ported this binding to OH3 codebase and opened #10014 

Should close this PR now?
Also, is there any chance a JAR for _this_ (v2.5.12) PR would be build and [auto-published](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/) by Jenkins?

**Comment by Hilbrand** [comment]
Yes this pr can be closed. I must say I'm not very familiar with the process of jars of pr builds. So I don't know the answer. In general I don't use it, because for existing bindings it's unreliable because it just depends on what version was in the last pr that was build. I use GitHub releases, which allow to add binaries and have a static url. So updating the jar won't result in a new url.

**Pull request closed without merging**
