### PR TITLE
[freeboxos] Enhance log warning when handling channel command fails

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by clinique — APPROVED** [review]

**Comment by lolodomo** [comment]
I will try to also log what permission is missing.

**Comment by lolodomo** [comment]
Ready again for review.

**Review by clinique — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@wborn and @openhab/add-ons-maintainers : we have a problem with all builds failing. Something related to the parse of the super POM...

**Comment by lolodomo** [comment]
I will rather the error code to trigger PermissionException.

**Comment by lolodomo** [comment]
@clinique : last change applied

**Review by clinique — APPROVED** [review]

**Comment by lolodomo** [comment]
@jlaur or @lsiepel : can you please have a look?

**Review by jlaur — APPROVED** [review]
Thanks, LGTM.

**Pull request merged**
