### PR TITLE
[netatmo] Enable home being both energy and security

### LINKED ISSUE #15928: [netatmo] Things linked to the bridge "netatmo:home" doesn't work after OH 4.x
## Expected Behavior

I was in version 3.4 of OH. I had configured the Netatmo binding. The relays, thermostat, people linked to the Welcome camera, everything worked. When I upgraded to 4.0, the relay and thermostat went to UNKNOWN status. The camera part works for the moment.

## Current Behavior

When I activate the netatmo account, everything goes well
``` 
2023-11-19 19:04:09.196 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - Initializing Netatmo API bridge handler.
2023-11-19 19:04:09.204 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - Connecting to Netatmo API.
2023-11-19 19:04:09.255 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:home:e9dd9122ce:5971b81c69f74006578b4b92
2023-11-19 19:04:09.269 [DEBUG] [.netatmo.internal.action.RoomActions] - Netatmo RoomActions service created
2023-11-19 19:04:09.319 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:plug:e9dd9122ce:5971b81c69f74006578b4b92:70ee500a54c0
2023-11-19 19:04:09.327 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:53d496838fd842719e71cebee9d648e3
2023-11-19 19:04:09.360 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:1135ceb2a84d4249b6c66594242f7c68
2023-11-19 19:04:09.361 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:c6f72f80adfe4d53943da716a86fd815
2023-11-19 19:04:09.384 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:thermostat:e9dd9122ce:5971b81c69f74006578b4b92:70ee500a54c0:0400000a3946
2023-11-19 19:04:09.430 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:room:e9dd9122ce:5971b81c69f74006578b4b92:42498674
2023-11-19 19:04:09.443 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:welcome:e9dd9122ce:5971b81c69f74006578b4b92:70ee5080de84
2023-11-19 19:04:09.463 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:be22c1ce76a248ef83df5a700f8c2810
2023-11-19 19:04:09.469 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:0d6f7eaf7a1b4d9c878ad8665aaccbbe
2023-11-19 19:04:09.995 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. UnknownTokenException: Unknown token found: value_json['update']['state']
2023-11-19 19:04:11.260 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri GET  https://api.netatmo.com/api/homesdata?home_id=5971b81c69f74006578b4b92
2023-11-19 19:04:11.264 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -with headers : Accept-Encoding: gzip, User-Agent: Jetty/9.4.50.v20221201, Authorization: Bearer 5664244767e48246a48b4925|8f827bb581695709993c3756072456fa
2023-11-19 19:04:11.429 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -returned : code [200 OK] body {"body":{"homes"....
``` 

Same thing when I activate the "netatmo:home" thing, everything is OK
```
2023-11-19 19:06:52.450 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:home:e9dd9122ce:5971b81c69f74006578b4b92
2023-11-19 19:06:52.474 [DEBUG] [.netatmo.internal.action.RoomActions] - Netatmo RoomActions service created
2023-11-19 19:06:52.498 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:plug:e9dd9122ce:5971b81c69f74006578b4b92:70ee500a54c0
2023-11-19 19:06:52.500 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:c6f72f80adfe4d53943da716a86fd815
2023-11-19 19:06:52.503 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:53d496838fd842719e71cebee9d648e3
2023-11-19 19:06:52.524 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:1135ceb2a84d4249b6c66594242f7c68
2023-11-19 19:06:52.564 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:room:e9dd9122ce:5971b81c69f74006578b4b92:42498674
2023-11-19 19:06:52.570 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:0d6f7eaf7a1b4d9c878ad8665aaccbbe
2023-11-19 19:06:52.602 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:thermostat:e9dd9122ce:5971b81c69f74006578b4b92:70ee500a54c0:0400000a3946
2023-11-19 19:06:52.605 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:welcome:e9dd9122ce:5971b81c69f74006578b4b92:70ee5080de84
2023-11-19 19:06:52.608 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:person:e9dd9122ce:5971b81c69f74006578b4b92:be22c1ce76a248ef83df5a700f8c2810
2023-11-19 19:06:54.454 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri GET  https://api.netatmo.com/api/homesdata?home_id=5971b81c69f74006578b4b92
2023-11-19 19:06:54.458 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -with headers : Accept-Encoding: gzip, User-Agent: Jetty/9.4.50.v20221201, Authorization: Bearer 5664244767e48246a48b4925|8f827bb581695709993c3756072456fa
2023-11-19 19:06:54.601 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -returned : code [200 OK] body {"body":{"homes"
```

When I activate the "netatmo:plug" thing, the relay, it tells me that it can connect
```
2023-11-19 19:10:58.522 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:plug:e9dd9122ce:5971b81c69f74006578b4b92:70ee500a54c0
2023-11-19 19:10:58.557 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:thermostat:e9dd9122ce:5971b81c69f74006578b4b92:70ee500a54c0:0400000a3946
2023-11-19 19:11:00.529 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri GET  https://api.netatmo.com/api/getevents?home_id=5971b81c69f74006578b4b92
2023-11-19 19:11:00.533 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -with headers : Accept-Encoding: gzip, User-Agent: Jetty/9.4.50.v20221201, Authorization: Bearer 5664244767e48246a48b4925|8f827bb581695709993c3756072456fa
2023-11-19 19:11:00.685 [TRACE] [mo.internal.handler.ApiBridgeHandler] -  -returned : code [200 OK] body {"body":{"home":...
```

But, it remains at UNKNOWN

## Steps to Reproduce (for Bugs)

To test, if the problem was coming from, I created a new token, and then, in Docker, I created 2 containers:
   - OH 4.1 M3
   - OH 3.4.5

The 2 installations are clean with only the Netatmo binding to install
I first tried setting up the 4.1 container. Same problem as on my OH 4.0, the "netatmo:plug" things linked to the "netatmo:home" bridge go UNKNOW.
Then, I configured the 3.4.5 container with the same token as the 4.1, and everything continued, the "netatmo:plug" things went ONLINE.
In addition, in version 3.4.5, OH sees 17 things after scanning compared to 7 in version 4.1

## Your Environment

My main OH 4.0.4 works on a dedicated machine under `armbian bullseyes`. The installed java is `openjdk 17.0.8 2023-07-18 LTS`
My OHs under Docker run on a Debian VM. The java for OH 3.4 is `openjdk 11.0.20 2023-07-18` and for OH 4.1 `openjdk version "17.0.9" 2023-10-17`

### PR DESCRIPTION
**Pull request by clinique**
Resolves #15928

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@clinique : is it already tested ?

**Comment by clinique** [comment]
> @clinique : is it already tested ?

No, submitted in the issue for testing and feed back. Can not be merged

**Comment by lolodomo** [comment]
Do we delay the merge after OH4.1 is released ?

**Comment by clinique** [comment]
> Do we delay the merge after OH4.1 is released ?
> Or are you enough confident with your change @clinique ?

We should wait, I did not had time to dig a weird thing

**Comment by clinique** [comment]
@lolodomo : this one is ready to go.

**Comment by lolodomo** [comment]
@clinique : is the bug enough serious that we should back port your fix to 4.1.x ?

**Comment by clinique** [comment]
This is a rare case when both energy and security are hosted by the same Netatmo Home. I never succeeded doing this on my own configuration. For peace of mind, I think it would be worth backporting it or else we'll never think to it again.

**Comment by VeronikaWehrle** [comment]
Hi, a downport to 4.1.x would be highly appreciated. We have the same issue ;-) 
Thanks for your great work!

**Comment by mdillmann** [comment]
Hi,
was the fix backported to 4.1.x ? 

I just updated my production OH from 3.4 to 4.1.1 and hoped it would remedy my room issue, but it is still there. 

If it was, I'll do some investigation why it still doesn't work in my setup.

**Pull request merged**
