### PR TITLE
[roku] Add channel to access hidden menus

### PR DESCRIPTION
**Pull request by mlobstein**
Addresses #15822

Still a WIP because only the CHANNEL, HDMI & RESET menus seem to work via the API. @morph166955 can you try this out?

### CODE REVIEW

**Comment by morph166955** [comment]
Tested on a TCL Roku TV:

CHANNEL_INFO  - Works
DEVELOPER_INFO  - Nope
HDMI_INFO  - Works
NETWORK_INFO  - Nope
PLATFORM_INFO  - Nope
RESET_INFO  - Works
ADVERTISING_INFO  - Nope
WIRELESS_INFO - Nope

Very curious that the others don't work through the API.

**Comment by mlobstein** [comment]
> 
> Very curious that the others don't work through the API.

Maybe then it is not worth pursuing this PR if only three of the menus are accessible in this manner.

**Comment by morph166955** [comment]
I am unfortunately forced to agree.  It's confusing to me why they don't work but a few do.  I wonder if there is some extra buttons that have to be pushed or something like that when going through the API.  I'm ok with closing this and the feature request if it's just one of those "can't do it" things.

**Comment by mlobstein** [comment]
Closing for now.

**Pull request closed without merging**
