### PR TITLE
Fix autoUpdatePolicy for write-only channels

### PR DESCRIPTION
**Pull request by mlobstein**
Correct the autoUpdatePolicy for all of the write-only channels in bindings for which I am the code owner.

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM 

As this PR changes the behaviour, this should be listed in the release notes.  Therefore it would be berst to split the PR into seperate PR's per binding. wdyt?

**Comment by mlobstein** [comment]
> Thanks, LGTM
> 
> As this PR changes the behaviour, this should be listed in the release notes. Therefore it would be berst to split the PR into seperate PR's per binding. wdyt?

I can go either way... It is such a minor change to have the autoUpdate policy implicitly for these stateless channels that I thought I would try to do them all in one PR rather than all the noise that 9 individual PRs would cause.

**Comment by lsiepel** [comment]
@openhab/add-ons-maintainers wdyt?

**Comment by kaikreuzer** [comment]
@lsiepel Would we consider it a breaking change? If so, we would have it in the distro's update.lst file, which would automatically warn the users.
But I don't really think that it needs to be considered breaking; in that case, separate PRs might indeed be nice so that users of the respective bindings will find a message in the release notes that informs them about the enhancement.

**Comment by mlobstein** [comment]
OK, I will create individual PRs instead.

**Comment by lsiepel** [comment]
> @lsiepel Would we consider it a breaking change? If so, we would have it in the distro's update.lst file, which would automatically warn the users. But I don't really think that it needs to be considered breaking; in that case, separate PRs might indeed be nice so that users of the respective bindings will find a message in the release notes that informs them about the enhancement.

I would not consider this a breaking change

**Pull request closed without merging**
