### PR TITLE
[canrelay] DIY CanRelay Binding initial contribution

### PR DESCRIPTION
**Pull request by PoJD**
New binding to support DYI CANBUS based set of devices to control lights through smart light switches in a home (house or flat). 
 - supports discovery both bridges and all lights
 - supports USBTin device to talk to the CANBUS network. This is in canbus package and has potential if the maintainers are happy to be moved out of the binding if any other binding would like to leverage this ability (to talk to USBTin or potentially any other CANBUS device in the future).

Link to the product (I am the author): https://github.com/PoJD/can
See README for the full picture.

I have tested this at home and works like a charm.

I have opened up a thread about this at https://community.openhab.org/t/new-binding-for-dyi-canbus-based-light-switch-solution/57583 earlier and was clarifying a few things before there. DSMR was indeed initial inspiration since this is my first binding.

### CODE REVIEW

**Comment by PoJD** [comment]
@Hilbrand tagging you here since you were really helpful in the beginning,thank you!

**Comment by PoJD** [comment]
Btw latest commits were just some additional test cases I figured I did not cover earlier when re-reading all code, do not plan to do any commits anymore :)

**Comment by PoJD** [comment]
latest pushes only to trigger builds again, all builds just fine locally, but perhaps there were some issues with travis builds earlier...?

**Comment by davidgraeff** [comment]
This repo cannot contain bindings for every possible DIY solution although you have an overall good coding style and even tests.

With the new buildsystem it is super easy to have just your binding and 2 buildsystem files in a repo and maintain that. With a travis.yml file you can even generate the jar file with every change or periodically.

But we can help you to reduce the code that need to be outside of this repo if you want to.

The can part is quite interesting and would be merged as a transport to this repo for your binding and other bindings to be used.

**Comment by J-N-K** [comment]
Thanks for your contribution, but I agree with @davidgraeff, DIY solutions should be covered in private repos.

**Pull request closed without merging**
