### PR TITLE
[fsinternetradio] Add Silvercrest SIRD 14 C1 radio modes to documentation

### PR DESCRIPTION
**Pull request by joednemesis**
Added Silvercrest SIRD 14 C1

### CODE REVIEW

**Comment by wborn** [comment]
Thanks! The changes look good to me but I don't use these devices. ;-)
Maybe @TehTux can also review this update?
I see you gave the table a big update in https://github.com/eclipse/smarthome/pull/6285.

**Comment by TehTux** [comment]
@wborn 
Sorry, I only have the C2. So I can't test it.

**Comment by J-N-K** [comment]
@joednemesis can you fix the sign-off?

**Comment by martinvw** [comment]
@joednemesis I would be nice if you could confirm that you agree to the DCO, see some more information at https://community.openhab.org/t/dco-check-signing-off-with-github-web-editor-explanation/83330

For such a case it would be okay if you just confirm it in a message at the pull request.

Thanks!

**Review by Hilbrand — APPROVED** [review]

**Pull request merged**
