### PR TITLE
Resolve itest runbundles for Gson and Commons Lang upgrades and fix JsonParser deprecations

### PR DESCRIPTION
**Pull request by wborn**
Depends on  https://github.com/openhab/openhab-core/pull/2244

### CODE REVIEW

**Review by marcelrv — APPROVED** [review]
LGTM for max & ntp bindings

**Review by pacive — APPROVED** [review]
Looks good for SMHI binding

**Review by mhilbush — APPROVED** [review]
LGTM for squeezebox

**Comment by marcelrv** [comment]
LGTM for max,miio,ntp & windcentrale bindings

**Comment by wborn** [comment]
This will fix the build @openhab/add-ons-maintainers!

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
