### PR TITLE
[pollytts] Update Apache httpcore and httpclient

### LINKED ISSUE #16293: Old version of Apache http client throwing warning at start
I couldn't find specifically where this was being set by a binding or by the core.  If this is the wrong place I apologize.  This is now throwing when I start.  I'm on the most current snapshot (3839).

`
2024-01-15 12:26:52.735 [WARN ] [zonaws.http.apache.utils.ApacheUtils] - NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information
`

Looking at my current bundles I see:
270 │ Active │  80 │ 4.5.5                  │ org.apache.httpcomponents.httpclient
271 │ Active │  80 │ 4.4.9                  │ org.apache.httpcomponents.httpcore

### PR DESCRIPTION
**Pull request by morph166955**
Updates Apache httpcore and httpclient to resolve dependencies.

Resolves #16293

### CODE REVIEW

**Comment by morph166955** [comment]
@J-N-K opening this as draft while we figure out what to do with IPP and IHC

**Comment by J-N-K** [comment]
I think upgrading to client/4.5.14 and core/4.4.13 should be safe, I did look at the release notes and there are no breaking changes as far as I can see.

**Comment by morph166955** [comment]
Sounds good. Would it be smarter to just pull this back to the main addons pom to include since it crossed multiple bindings?  That should help us keep it up to date across.

**Comment by morph166955** [comment]
Is this good to merge at this point?  I'm still getting the same error on 3964

**Review by lsiepel — APPROVED** [review]
LGTM, based on what i have seen this is ok to merge now.

**Pull request merged**
