### PR TITLE
[hdpowerview] Improve Gen 1/2 discovery label

### PR DESCRIPTION
**Pull request by jlaur**
This is a minor improvement to show the specific Hub discovered, e.g. "PowerView **Gen 2** Hub" rather than "PowerView **Gen 1/2** Hub" (introduced with #13355).

For reference:
- [Gen 1 firmware response](https://github.com/openhab/openhab-addons/issues/11856#issuecomment-1001010583)
- [Gen 2 firmware response](https://github.com/openhab/openhab-addons/issues/11856#issuecomment-1001011830)

### CODE REVIEW

**Comment by andrewfg** [comment]
@jlaur thank you for this. But..

An extra HTTP GET request is not required to make the distinction between Gen 1 and 2 hubs. The SDDP and MDNS response telegrams already contain distinguishing markers.. 

- SDDP the type header ends with 'v2'
- MDNS the 'md' property contains '2.0'

**Comment by jlaur** [comment]
> @jlaur thank you for this. But..
> 
> An extra HTTP GET request is not required to make the distinction between Gen 1 and 2 hubs. The SDDP and MDNS response telegrams already contain distinguishing markers..
> 
> * SDDP the type header ends with 'v2'
> * MDNS the 'md' property contains '2.0'

Thanks, I will adapt and test this. Since we don't know what Gen 1 Hub provides, I guess we can consider "v2"/"2.0" as Gen 2 and everything else as Gen 1.

**Comment by jlaur** [comment]
> * SDDP the type header ends with 'v2'
> * MDNS the 'md' property contains '2.0'

I can confirm that `type` in `SddpDevice` is "hunterdouglas:hub:powerviewv2". I can't figure out how to get the `md` property for mDNS, can you advise? I've tried `service.getPropertyNames()` which doesn't give any results, and `service.getPropertyString("md")` returns null. In the Android app **mDNS Discovery** I only see IP Address, Port and Service Type.

**Comment by andrewfg** [comment]
Ah. The v2 hub also responds on '_hap._tcp.local' and this is where it reports an 'md' property. But, (not having a v1 hub), I don't know if that one also answers on '_hap._tcp.local'..

**Comment by jlaur** [comment]
> Ah. The v2 hub also responds on '_hap._tcp.local' and this is where it reports an 'md' property. But, (not having a v1 hub), I don't know if that one also answers on '_hap._tcp.local'..

Thanks, that worked better for finding the `md` property. I guess it's tricky then.

Assuming that Gen 1 doesn't respond on `_hap._tcp.local`, we would need two different `MDNSDiscoveryParticipant` implementations: `_powerview._tcp.local` for Gen 1 and `_hap._tcp.local` for Gen 2. But the Gen 2 Hub would respond to both, so this would cause duplicate discovery with different labels. I don't see a good solution for this, and the only benefit would be one HTTP call avoided when finding a Gen 2 Hub through mDNS.

**Comment by andrewfg** [comment]
^
Yeah. I think that for MDNS an extra GET is indeed the only viable solution.

**Comment by jlaur** [comment]
> Yeah. I think that for MDNS an extra GET is indeed the only viable solution.

So it's ready for review. 🙂

**Review by andrewfg — APPROVED** [review]
LGTM

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
