### PR TITLE
[hue] Use system default channel types for lights

### PR DESCRIPTION
**Pull request by cweitkamp**
- Use system default channel types for lights

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cpmeister** [comment]
Are these changes backwards compatible?

**Review by cweitkamp — COMMENTED** [review]
@cpmeister A comparison:

One thing we will lose is the "Lighting" tag form some channel types which imo is not relevant anymore. Semantics are using the "Light" tag.

The more detailed descriptions for the channels types can be backported to OHC.

**Review by cpmeister — APPROVED** [review]

**Comment by BobMiles** [comment]
Hi,
I recently switched to M1 and I lost all my thing channels for hue lamps except the alarm/loop. 
Could this be related to this change? The items seem still to be linked and interaction is possible (I can control lights via OH), but the channels are "invisible".
Screenshot_20210204_163419

**Comment by cweitkamp** [comment]
Yes, it is. For managed Things the Channel Type is stored in JSON storage and will not be changed accordingly. To solve your issue you have to delete and recreate your Thing.

**Comment by BobMiles** [comment]
Thank you very much for the quick answer!

**Pull request merged**
