### PR TITLE
[caddx] Assign unique id to thing actions (#17707)

### PR DESCRIPTION
**Pull request by Laith-Budairi**
this commit fixes thing actions for methods with the same name

### CODE REVIEW

**Comment by Laith-Budairi** [comment]
> _ No description provided. _

this commit is for thing actions with unique id for methods with same name

**Comment by lolodomo** [comment]
@Laith-Budairi : there is no more need of this id, a change in coming in core framework that solves the issue.
By the way, I be

**Comment by lolodomo** [comment]
So I close your PR.

**Comment by lolodomo** [comment]
So I close your PR.

**Pull request closed without merging**
