### PR TITLE
Remove immediate = true from all Components

### PR DESCRIPTION
**Pull request by Hilbrand**

### CODE REVIEW

**Review by hmerk — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
As I remember we had big difficulties at the very beginning of OH2 and we added "immediate=true" to solve them, are you very sure of your change?

**Review by clinique — APPROVED** [review]

**Comment by cpmeister** [comment]
Looks like we have some conflicts that need to be resolved first.

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by mherwege** [comment]
LGTM

**Review by mherwege — APPROVED** [review]

**Review by bobadair — APPROVED** [review]
LGTM for the Lutron binding.

**Review by BobRak — APPROVED** [review]
LGTM
Approving changes to the 3 smartthings files.

**Review by Cossey — APPROVED** [review]
Approving changes to HP printer binding.

**Review by Skinah — APPROVED** [review]
LGTM

Signed-off-by: Matthew Skinner <matt@pcmus.com>

**Comment by MikeJMajor** [comment]
@Hilbrand this change looks to have broken Hue Emulation.

It no longer starts properly and does not log `Hue Emulation service available under /api`

Adding back `immediate = true` to `HueEmulationService` fixes the issue.

**Pull request merged**
