### PR TITLE
[androidtv] Moves Shim PKI to AndroidTVPKI and adds Trusted CA Certificate functions

### PR DESCRIPTION
**Pull request by morph166955**
This is mostly for debugging protocol issues on remote devices when they can not be reproduced locally.
Automates the PKI process for shim.  
Adds Trusted CA Certificate functions to AndroidTVPKI

### CODE REVIEW

**Comment by morph166955** [comment]
@jlaur for my knowledge, why does this get a regression tag?

**Comment by jlaur** [comment]
> @jlaur for my knowledge, why does this get a regression tag?

This is only to keep it out of the final release notes.

**Comment by morph166955** [comment]
Ah, ok. Thank you!

**Review by wborn — APPROVED** [review]
LGTM!

**Comment by morph166955** [comment]
Thank you!

**Pull request merged**
