### PR TITLE
Bump jsoup from 1.8.3 to 1.14.3

### PR DESCRIPTION
**Pull request by soenkekueper**
I've updated the jsoup library from 1.8.3 to 1.14.3. 

#11615 was created by dependabot, but the 1.14.2 has an OSGI dependency error (see https://jsoup.org/news/release-1.14.3),
so i've used the 1.14.3.

Due some build errors in several plugins i've updated all of them to use the osgi provided bundle instead of compile time dependency.

I've placed all of the plugins within my local test installation, after manual installation of required bundles all of them were installed and started successfully.

### CODE REVIEW

**Review by fwolter — APPROVED** [review]
LGTM

@clinique, @cschneider, @digitaldan, @jochen314, @kgoderis, @lolodomo, @Skinah Can you please test if 1.14.3 behaves as you'd expect it with your code? The update is necessary due to a security issue. See https://jsoup.org/news/release-1.14.2

**Comment by Skinah** [comment]
It works in the ipobserver binding so all good here. However just a suggestion that if there are this many addons all using the same dependency, can it be change like in this PR so changing the version in the future only needs to be done in one line and in one file?

https://github.com/openhab/openhab-addons/pull/11130

From then on it is just the main pom that needs the version to be changed and all the bindings will follow.

**Review by fwolter — APPROVED** [review]

**Comment by fwolter** [comment]
@clinique, @cschneider, @digitaldan, @jochen314, @kgoderis, @lolodomo Your binding will use the new jsoup version from OH 3.2.0.RC1 on. Please test your binding, if this update doesn't break anything. 3.2.0.RC1 will be released on Friday, December 17.

**Comment by digitaldan** [comment]
no problems here.

**Pull request merged**
