### PR TITLE
[mqtt.homeassistant] Update Jinjava to 2.7.3

### LINKED ISSUE #15145: [mqtt.homeassistant][JINJA] Transformation problem with value template key
I did read this is potentially the wrong place (just need some feedback at this point).  I'm not fluent in Java but can read a little bit of code.  The actual log message is from the Addons repository, but when I looked into that class it appears to call on the transformation services in the core.  However, from within the core I could not find the source.  

Background: I'm experimenting with zwave-js-ui for OH. On a test system I can discover all my test zwave devices in OH4M3. Test setup with openhabian (on WSL - Debian 11 with MQTT, Json Path & Jinja transform installed) and all the channels/topics appear.  It is early in testing so far, but most channels/topics can be linked to items and display the state (ON/OFF or Number). 

The one type of channel /topic with a problem so far;
`{"value_template":"{{ {22: \"Window/door is open\",23: \"Window/door is closed\",5632: \"Window/door is open in regular position\",5633: \"Window/door is open in tilt position\"}[value_json.value] | default(value_json.value) }}","icon":"mdi:alarm-light","state_topic":"zwave/nodeID_10/113/0/Access_Control/Door_state","json_attributes_topic":"zwave/nodeID_10/113/0/Access_Control/Door_state","device":{"identifiers":["zwavejs2mqtt_0xe2bd1ff1_node10"],"manufacturer":"Zooz","model":"Tilt Shock XS Sensor (ZSE43)","name":"nodeID_10","sw_version":"1.20.1"},"name":"nodeID_10_notification_access_control_door_state","unique_id":"zwavejs2mqtt_0xe2bd1ff1_10-113-0-Access_Control-Door_state"}`

## Expected Behavior
I would hope this should return the string corresponding with the number.  I don't know if this is a bug or just not allowed by the Jinja /JSON specification.

## Current Behavior
`2023-06-27 14:32:56.534 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. InterpretException: Error resolving expression [{22: "Window/door is open",23: "Window/door is closed",5632: "Window/door is open in regular position",5633: "Window/door is open in tilt position"}[value_json.value] | default(value_json.value)]: TemplateStateException: Dict key must be a string or identifier, was: 22`

and another;
`2023-06-27 14:32:56.174 [WARN ] [t.generic.ChannelStateTransformation] - Executing the JINJA-transformation failed: An error occurred while transformation. InterpretException: Error resolving expression [{0: "off", 1: "heat", 2: "cool"}[value_json.value] | default('off')]: TemplateStateException: Dict key must be a string or identifier, was: 0`

## Possible Solution
Allow a number to be the index to get the string. If it helps, all the numbers will be a member of integers.

## Context
zwave-js-ui includes several features not currently available with the OH Zwave binding including S2 security, OTA firmware updates, 700/800 series controllers and has applied for certification with the Zwave Alliance standards body. I do not know if this is going to work.  There could be more issues (possibly impossible to resolve) as I add different devices.

### PR DESCRIPTION
**Pull request by ccutrer**
Dependent on https://github.com/openhab/openhab-osgiify/pull/51.

Closes #15145

### CODE REVIEW

**Comment by lsiepel** [comment]
[WARNING] Error:
	Error downloading mvn:org.openhab.osgiify/com.hubspot.jinjava.jinjava/2.7.3_0

**Comment by lsiepel** [comment]
Where deos it get that artifact from? Should the osgified file be uploaded somewhere?

**Comment by ccutrer** [comment]
I have no idea. I just kind of assumed a nightly build would handle it. But it's been two nights now. @J-N-K?

**Comment by holgerfriedrich** [comment]
@kaikreuzer could you please upload the latest version? Thanks!

**Comment by J-N-K** [comment]
This should work automatically once the build is triggered.

**Comment by holgerfriedrich** [comment]
Do I get it correctly, https://ci.openhab.org/job/openhab-osgiify/ should upload the artifacts?

@J-N-K it seems that build [36 ](https://ci.openhab.org/job/openhab-osgiify/36/) did not properly store to Artifactory.
I can see builds only up to 35:
https://openhab.jfrog.io/ui/builds/openhab-osgiify/?buildRepo=artifactory-build-info

**Comment by lsiepel** [comment]
@wborn thanks, seems you fixed it. For future changes, do you need to trigger that ci build manually (liike a release/milestone), or should this build and upload ci trigger automatically after merge?

**Comment by J-N-K** [comment]
It's a manual build.

**Comment by wborn** [comment]
I upgraded the Jenkins Artifactory plugin to fix it. I downgraded it earlier to see if it would fix the other issue but it didn't help.

When I find some time I'll try to replace it with the Artifactory Maven plugin which can also be used to upload artifacts in GitHub Actions builds.

**Comment by jimtng** [comment]
https://github.com/openhab/openhab-osgiify/pull/51#issuecomment-2351893731

**Comment by lsiepel** [comment]
Almost there. Some dependency’s are missing

**Comment by ccutrer** [comment]
Omg, there it is! 2.7.3 added the following new dependencies:

* com.fasterxml.jackson.datatype » jackson-datatype-jdk8
* com.hubspot.immutables » immutable-exceptions

Thank you for pointing it out! Now to figure out how to add dependencies...

**Comment by ccutrer** [comment]
https://github.com/openhab/openhab-osgiify/pull/53 needs merged and pushed to the openhab repo first. After that, I ran a full verify build including itests for MQTT and Jinja Transformation locally, and everything passed. 🤞

**Comment by ccutrer** [comment]
Woohoo! Build passed!

**Pull request merged**
