### PR TITLE
[denonmarantz] Remove Apache StringUtils

### PR DESCRIPTION
**Pull request by mlobstein**
Remove usage of org.apache.commons.lang3.StringUtils per #7722

### CODE REVIEW

**Review by wborn — APPROVED** [review]
LGTM!

**Comment by jlaur** [comment]
@wborn - looks good to me also. Can we merge?

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by wborn** [comment]
Yes let's merge it now it has been checked by more eyes. :slightly_smiling_face:

**Pull request merged**
