### PR TITLE
[deconz] Prevent Null Pointer Exception if socket connection is broken

### LINKED ISSUE #12176: [deconz] NullPointerException when stopping the deCONZ service
Stopping the deCONZ service is not handled gracefully.

## Expected Behavior
Binding should set bridge status to OFFLINE (which it does). After this no additional errors should be logged, and no exceptions thrown.

## Current Behavior
```
2022-01-30 22:35:15.700 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:deconz:000000000000' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Disconnected
2022-01-30 22:35:15.704 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:onofflight:000000000000:012345678901234567' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2022-01-30 22:35:25.710 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:deconz:000000000000' changed from OFFLINE (COMMUNICATION_ERROR): Disconnected to OFFLINE (COMMUNICATION_ERROR): Error while connecting: null
2022-01-30 22:35:25.716 [WARN ] [ocket.client.WebSocketUpgradeRequest] - Exception while notifying onError
java.lang.NullPointerException: null
	at org.openhab.binding.deconz.internal.netutils.WebSocketConnection.onError(WebSocketConnection.java:162) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onError(JettyAnnotatedEventDriver.java:192) ~[?:?]
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.handleException(WebSocketUpgradeRequest.java:545) ~[?:?]
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:524) ~[?:?]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218) ~[?:?]
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210) ~[?:?]
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:276) ~[?:?]
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:247) ~[?:?]
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:164) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:819) ~[?:?]
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:502) ~[?:?]
	at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:252) ~[?:?]
	at org.eclipse.jetty.client.AbstractConnectionPool$FutureConnection.failed(AbstractConnectionPool.java:551) ~[?:?]
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136) ~[bundleFile:9.4.43.v20210629]
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:633) ~[?:?]
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138) ~[?:?]
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:188) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:966) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:369) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:65) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:676) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:535) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362) ~[bundleFile:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186) ~[bundleFile:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[bundleFile:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:137) ~[bundleFile:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [bundleFile:9.4.43.v20210629]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [bundleFile:9.4.43.v20210629]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

## Possible Solution
It seems this Session in annotated method `@OnWebSocketError` is in fact `@Nullable` which should be handled. Did quick test:

```
    @SuppressWarnings("unused")
    @OnWebSocketError
    public void onError(@Nullable Session session, Throwable cause) {
        if (session != null && !session.equals(this.session)) {
            handleWrongSession(session, "Connection error: " + cause.getMessage());
            return;
        }
        logger.warn("{} connection errored, closing: {}", socketName, cause.getMessage());
```

But this leads to continuous logging:

```
2022-01-30 23:00:38.534 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:deconz:000000000000' changed from OFFLINE (COMMUNICATION_ERROR): Disconnected to OFFLINE (COMMUNICATION_ERROR): Error while connecting: null
2022-01-30 23:00:48.537 [WARN ] [nternal.netutils.WebSocketConnection] - Websocket$1643579656415-1 connection errored, closing: Connection refused
2022-01-30 23:00:58.541 [WARN ] [nternal.netutils.WebSocketConnection] - Websocket$1643579656415-1 connection errored, closing: Connection refused
2022-01-30 23:01:08.542 [WARN ] [nternal.netutils.WebSocketConnection] - Websocket$1643579656415-1 connection errored, closing: Connection refused
2022-01-30 23:01:19.905 [WARN ] [nternal.netutils.WebSocketConnection] - Websocket$1643579656415-1 connection errored, closing: Connection refused
```

So more is needed. I'm not familiar with the binding code.

## Steps to Reproduce
Stop the deCONZ service while the binding is running, perhaps with at least one thing configured.

Binding version: 3.2 release version and 3.3 snapshot 30.01.2022.

### PR DESCRIPTION
**Pull request by EvilPingu**
This PR fixes #12176.

### CODE REVIEW

**Comment by jlaur** [comment]
@EvilPingu - thanks. Tested and works. Only slight problem is two updates:
```
2022-02-06 13:35:39.470 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:deconz:000000000000' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Disconnected
2022-02-06 13:35:49.475 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:deconz:000000000000' changed from OFFLINE (COMMUNICATION_ERROR): Disconnected to OFFLINE (COMMUNICATION_ERROR): Error while connecting: null
```

I don't know if you'd like to tackle this as well as kind of related?

**Comment by cweitkamp** [comment]
@jlaur The issue you are pointing out is not related to this fix. In the `WebSocketConnection::start()` method we are catching all `Exception`s occurring during start of the websocket connection.

https://github.com/openhab/openhab-addons/blob/da59cdd255a66275dd7ae11dd294fedca4942d30/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java#L77-L84

The catched exception does not always has a message.

If you dig deeper into the lifecycle of the websocketconnection you will find out that under some circumstances a websocket connection will be started twice after it tries to recovers a connection. One of the reasons for that is that the `start()` method never sets the `connectionState` to `ConnectionState.CONNECTING`. Meaning the internal handling of the connection state is incomplete.

**Review by jlaur — APPROVED** [review]
LGTM - thanks for the fix!

**Comment by jlaur** [comment]
For reference, similar fix to same problem: smarthomej/addons#269

**Comment by jlaur** [comment]
> If you dig deeper into the lifecycle of the websocketconnection you will find out that under some circumstances a websocket connection will be started twice after it tries to recovers a connection. One of the reasons for that is that the `start()` method never sets the `connectionState` to `ConnectionState.CONNECTING`. Meaning the internal handling of the connection state is incomplete.

This problem that you mentioned in February, is it the same as fixed in smarthomej/addons#295 in January? If so, can you perhaps advise on best approach to copy that fix into this repository? I would happily do that, but I'm wondering how to attribute/credit @J-N-K who contributed the original fix and stuff like that. I only recently became aware of this alternate version, and I'm relying on deCONZ myself.

I'm aware of discussions in #13706, but this question is really just how to practically bring back additional value from such a fork without getting in trouble - since I would love a more stable deCONZ binding.

**Comment by MHerbst** [comment]
I already thought about porting the changes back, because smarthomej also contains a fix for #13141 (and probably other issues).

I have found PR by @hmerk who already ported a binding back (see https://github.com/openhab/openhab-addons/pull/13108).

**Pull request merged**
