### PR TITLE
[vizio] Prevent thing status from bouncing offline

### PR DESCRIPTION
**Pull request by mlobstein**
Addresses an issue reported by the community with the thing status flapping offline/online several times per day any time a transient communication occurs. Now the thing will only go offline after three consecutive polling errors. I recommend including this in the next available patch release.

### CODE REVIEW

**Comment by lsiepel** [comment]
Did you consider to retry the command when it fails? In general i would not recommend to just ignore the failure. The current solution would prevent the thing from going offline, but it will still be unreliable to the user without any feedback.

**Comment by mlobstein** [comment]
> Did you consider to retry the command when it fails? In general i would not recommend to just ignore the failure. The current solution would prevent the thing from going offline, but it will still be unreliable to the user without any feedback.

This is for the polling job that runs automatically every 10 seconds. The idea is that an intermittent failure will not cause the thing to go offline only to go online again 10 seconds later.

**Comment by lsiepel** [comment]
> > Did you consider to retry the command when it fails? In general i would not recommend to just ignore the failure. The current solution would prevent the thing from going offline, but it will still be unreliable to the user without any feedback.
> 
> This is for the polling job that runs automatically every 10 seconds. The idea is that an intermittent failure will not cause the thing to go offline only to go online again 10 seconds later.

You are right about the polling job, but i meant the commands like volume up/down or set power. The handling of those command have changed, they no longer update the thing status when they fail.

**Comment by mlobstein** [comment]
> You are right about the polling job, but i meant the commands like volume up/down or set power. The handling of those command have changed, they no longer update the thing status when they fail.

Yes I reflected on those and it occurred to me that they were not really helpful because the thing status would go right back to online (and overwrite the failure message) in 10 seconds or less when the polling runs again.

**Comment by jlaur** [comment]
> Yes I reflected on those and it occurred to me that they were not really helpful because the thing status would go right back to online (and overwrite the failure message) in 10 seconds or less when the polling runs again.

Perhaps increasing log level to warn could help?

**Review by lsiepel — APPROVED** [review]
LGTM

**Pull request merged**
