### PR TITLE
Use `OnOffType.from` to reduce code

### PR DESCRIPTION
**Pull request by wborn**
You can create an `OnOffType` using a boolean nowadays which reduces the amount of code.

### CODE REVIEW

**Review by maniac103 — APPROVED** [review]
:+1: for ecovacs

**Review by stefan-hoehn — APPROVED** [review]
Thumbs up for Nanoleaf

**Review by bern77 — APPROVED** [review]
LGTM

**Review by hmerk — APPROVED** [review]
LGTM

**Review by david-pace — APPROVED** [review]
+1 for `boschshc`

**Review by MrRonfo — APPROVED** [review]
LGTM for bticinosmarther binding

**Review by hypetsch — APPROVED** [review]
LGTM for bsblan

**Comment by robnielsen** [comment]
lgtm for insteon

**Review by robnielsen — APPROVED** [review]

**Review by mlobstein — APPROVED** [review]
LGTM for atlona, benq, epson. kaleidescape, nuvo, oppo, tivo

**Comment by morph166955** [comment]
@wborn what is the backwards compatibility on this?  I have a few I'm still holding to 3.x for marketplace.

**Comment by Wolfgang1966** [comment]
LGTM for tacmi. Thanks a lot!

**Review by Wolfgang1966 — APPROVED** [review]

**Comment by wborn** [comment]
> what is the backwards compatibility on this? I have a few I'm still holding to 3.x for marketplace.

It was added 5 years ago so it was already part of OH 2. :wink: 

See: https://github.com/eclipse-archived/smarthome/pull/6152

**Comment by morph166955** [comment]
> > what is the backwards compatibility on this? I have a few I'm still holding to 3.x for marketplace.
> 
> It was added 5 years ago so it was already part of OH 2. 😉
> 
> See: [eclipse-archived/smarthome#6152](https://github.com/eclipse-archived/smarthome/pull/6152)

Perfect!  LGTM then for Neeo!

**Review by morph166955 — APPROVED** [review]

**Review by mherwege — APPROVED** [review]
LGTM for elroconnects, nikohomecontrol and upnpcontrol.

**Review by kaikreuzer — APPROVED** [review]
I guess this is good to merge with so many approvals. 😄

**Pull request merged**
