### PR TITLE
[ferroamp] Binding for Ferroamp

### PR DESCRIPTION
**Pull request by basse04**
This is the binding for local connection to Ferroamp Energy System

# Title
[ferroamp] Binding for Ferroamp

 Description
This binding will be used to get values from different parts of The Ferroamp Energy System. The binding connects locally.

Signed-off-by: Örjan Backsell <orjan.backsell@gmail.com>

### CODE REVIEW

**Comment by basse04** [comment]
Hi, lsiepel.
I have now done a new PR as above.
There is a lot of changes in this one so it's almost a new binding regarded to the former one.
Please have a look and let me know.
Br Basse

**Comment by lsiepel** [comment]
> Hi, lsiepel. I have now done a new PR as above. There is a lot of changes in this one so it's almost a new binding regarded to the former one. Please have a look and let me know. Br Basse

Have some other PR’s to look at first, will come back to this. Maybe you can fix the DCO and merge conflicts meanwhile

**Comment by basse04** [comment]
Just fine with me, I will do my best about the fixes.

**Comment by basse04** [comment]
Hi, this is so strange, I did an sync fork and the PR was closed as described above. Seems to be something wrong  between my branch ferroamp_v3 and my branch main or something else.
I will now start from the beginning with a totaly new branch like ferroamp_v4 and be back with a new PR.
Thank's for your patience.
Br Basse

**Comment by basse04** [comment]
Hi, somehow it has again screwed up. I will now make a totaly new repsitory.
I found some mismatch in Eclipse configuration, so I think I will start with a new installation and so on.
I let you know.
Br Basse

**Pull request closed without merging**
