### PR TITLE
[netatmo] Enhance errored modules handling

### LINKED ISSUE #15858: [Netatmo] Binding fail with exception
Hi,
at home I have a netatmo thermometer (1st relay) and two valves (2nd relay). The first relay directly controls the boiler while the second has no pins to control the boiler so, until last winter I used a shelly 1pm to activate the boiler if one of the valves required it.
Until last winter everything worked, but now the binding is struggling to work. Last winter I was using version 3.3 of openhab, now I upgraded (new installation) to version 4.0.4.
When I create the Things the bridge it works, then after a few hours it no longer updates the values ​​of the items, this error appears in the logs:
```text
2023-11-06 08:07:40.719 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: Cannot invoke "org.openhab.binding.netatmo.internal.deserialization.NAObjectMap.getOpt(String)" because "<parameter1>" is null
	at org.openhab.binding.netatmo.internal.handler.capability.EnergyCapability.lambda$7(EnergyCapability.java:94) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.EnergyCapability.updateHomeStatus(EnergyCapability.java:92) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.Capability.setNewData(Capability.java:70) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.setNewData(CommonInterface.java:161) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.lambda$12(CommonInterface.java:188) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.proceedWithUpdate(CommonInterface.java:188) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.RefreshCapability.proceedWithUpdate(RefreshCapability.java:81) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.RefreshCapability.lambda$2(RefreshCapability.java:122) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

However, if I try to change a setpoint from openhab (without using the netatmo app) the binding restarts working again (for a few more hours)
I activated the debug log for the netatmo binding but I don’t seem to see anything interesting.
I noticed that often when the binding fails other queries on other Things also fail:
```text
2023-11-06 20:05:11.934 [DEBUG] [handler.capability.RefreshCapability] - Module refreshed, next one in 60 s
2023-11-06 20:06:12.299 [DEBUG] [handler.capability.RefreshCapability] - Module refreshed, next one in 60 s
2023-11-06 20:07:03.524 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.207/settings/relay/0' (method='GET', content='null') failed: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
2023-11-06 20:07:03.527 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.207/settings/relay/1' (method='GET', content='null') failed: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
2023-11-06 20:07:03.561 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.215/settings/relay/1' (method='GET', content='null') failed: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
2023-11-06 20:07:03.563 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.215/settings/relay/0' (method='GET', content='null') failed: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
2023-11-06 20:07:03.624 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://192.168.1.205/settings/relay/0' (method='GET', content='null') failed: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
2023-11-06 20:07:22.529 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: Cannot invoke "org.openhab.binding.netatmo.internal.deserialization.NAObjectMap.getOpt(String)" because "<parameter1>" is null
	at org.openhab.binding.netatmo.internal.handler.capability.EnergyCapability.lambda$7(EnergyCapability.java:94) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.EnergyCapability.updateHomeStatus(EnergyCapability.java:92) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.Capability.setNewData(Capability.java:70) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.setNewData(CommonInterface.java:161) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.lambda$12(CommonInterface.java:188) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.proceedWithUpdate(CommonInterface.java:188) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.RefreshCapability.proceedWithUpdate(RefreshCapability.java:81) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.RefreshCapability.lambda$2(RefreshCapability.java:122) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-11-06 21:32:05.707 [DEBUG] [handler.capability.RefreshCapability] - Module refreshed, next one in 60 s
2023-11-06 21:32:10.701 [DEBUG] [handler.capability.RefreshCapability] - Module refreshed, next one in 60 s
2023-11-06 21:32:12.905 [DEBUG] [handler.capability.RefreshCapability] - Module refreshed, next one in 60 s
```

Thanks,
Cristian

**[OpenHab version: 4.0.4]**

### PR DESCRIPTION
**Pull request by clinique**
Resolves #15858

While analyzing this issue, I identified that errored module handled at home level was partial. Fixed.
Strengthened getOpt

### CODE REVIEW

**Comment by clinique** [comment]
Thinking of it twice, I was sure I already faced the same case. It is the issue #15212 . If nothing is defined the  API gives a null where the binding expects (wrongly) an empty list.

**Comment by clinique** [comment]
@lolodomo, @jlaur  : ready for review

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by jlaur** [comment]
@clinique, @lolodomo - should we cherry-pick this for `4.0.x`?

**Comment by clinique** [comment]
> @clinique, @lolodomo - should we cherry-pick this for `4.0.x`?

Yes it should be

**Pull request merged**
