### PR TITLE
[miele] Rename handler to fix case

### PR DESCRIPTION
**Pull request by jlaur**
Rename handler to fix case and make consistent with corresponding channel selector.

### CODE REVIEW

**Comment by lolodomo** [comment]
We have WashingMachineHandler and not WashingmachioneHandler.
While would you like to make an exception for DishWasherHandler ?

**Comment by jlaur** [comment]
> We have WashingMachineHandler and not WashingmachioneHandler.
> While would you like to make an exception for DishWasherHandler ?

It's an old inconsistency that has been bugging me - `DishwasherChannelSelector` is correct, but `DishWasherHandler` not. It's not an exception:
- Washing Machine -> WashingMachine
- Tumble Dryer -> TumbleDryer
- Dishwasher -> Dishwasher

Dishwasher is one word, it's not "Dish Washer".

**Comment by lolodomo** [comment]
> Dishwasher is one word, it's not "Dish Washer".

Didn't know that.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
> > Dishwasher is one word, it's not "Dish Washer".
> 
> Didn't know that.

I cheated - I had to look it up to be sure. :-)

**Comment by mhilbush** [comment]
@jlaur I tried to update my local addons repo today. When running the merge (git merge origin/main), I get the following.

```
Updating 0357049f9f..31fd91129e
error: The following untracked working tree files would be overwritten by merge:
	bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherHandler.java
Please move or remove them before you merge.
Aborting
```

I don't think I should "move or remove" that file because that's the new name of the handler. I'm not sure how to correctly resolve. Any suggestions?

**Comment by J-N-K** [comment]
That‘s a known issue on windows because it is case-insensitive for file names. It‘s probably easiest to hard-reset.

**Comment by jlaur** [comment]
@mhilbush - are you on Windows? In general this is a mess and also the reason why I hesitated this long before fixing this. I'm running Windows on my development machine, so file system is case insensitive. Therefore I did a git `mv DishWasherHandler.java DishwasherHandler.java` to get this correctly picked up by Git. You could try renaming your local file to Dish**w**asherHandler.java before performing the merge in order to avoid the filename conflict.

**Comment by jlaur** [comment]
@mhilbush - you could also check this option: https://www.git-scm.com/docs/git-config/2.14.6#Documentation/git-config.txt-coreignoreCase

**Comment by J-N-K** [comment]
I use SmartGit, that seems to handle that just fine.

**Comment by lolodomo** [comment]
You just have to set ignore case to true in git config. 
And then unset it when your command succeeded.

**Comment by mhilbush** [comment]
SmartGit looks pretty nice - I applied for a non-commercial license.

When I opened my `openhab-addons` repo in SmartGit, it complained about `core.ignoreCase` not being set properly. So I set it to true and that also resolved the issue I was having running git from the command line.

Thanks for the help guys!

**Pull request merged**
