### PR TITLE
[samsungtv] UPnP devices discovery refactored

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@paulianttila : this PR follows our previous discussion. Normally, there is no need for an additional job going through the JUPnP registry. This is done in the thing handler initialization just before registering to the registry to be notified of all added/removed UPnP devices.

**This PR has to be tested before being merged.**

**Comment by lolodomo** [comment]
This will fix #2916
I am not sure if it will solve #7406

**Comment by lolodomo** [comment]
I am not sure what to do with this PR. I removed the "work in progress" as there is nothing more to do.
If noone is interested, I can rather close it.

**Comment by presidentio** [comment]
@lolodomo I really appreciate your work on SamsungTV binding and hope that this fix will solve my problems. What needs to be done to merge this PR?

**Comment by lolodomo** [comment]
What's needed is the review + testing of the changes.

**Comment by fwolter** [comment]
I'd review them, if anybody does a functional testing.

**Pull request closed without merging**
