### PR TITLE
[smhi] Fix exception in aggregation function when daily forecast is empty

### LINKED ISSUE #10850: [smhi] Division by zero error in ForecastAggregator
There's sometimes an ArithmeticException when calculating the total precipitation if there's no entries for that day.
```
2021-06-10 01:08:13.073 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.ArithmeticException: / by zero
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4579) ~[?:?]
	at java.math.BigDecimal.divide(BigDecimal.java:5671) ~[?:?]
	at java.math.BigDecimal.divide(BigDecimal.java:1592) ~[?:?]
	at java.math.BigDecimal.divide(BigDecimal.java:1673) ~[?:?]
	at org.openhab.binding.smhi.internal.ForecastAggregator.total(ForecastAggregator.java:43) ~[?:?]
	at org.openhab.binding.smhi.internal.SmhiHandler.getAggregatedValue(SmhiHandler.java:483) ~[?:?]
	at org.openhab.binding.smhi.internal.SmhiHandler.lambda$3(SmhiHandler.java:177) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
	at org.openhab.binding.smhi.internal.SmhiHandler.updateChannels(SmhiHandler.java:173) ~[?:?]
	at org.openhab.binding.smhi.internal.SmhiHandler.getUpdatedForecast(SmhiHandler.java:340) ~[?:?]
	at org.openhab.binding.smhi.internal.SmhiHandler.waitForForecast(SmhiHandler.java:272) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### PR DESCRIPTION
**Pull request by pacive**
Also catch any Exception to prevent thread from crashing

Fixes #10850

Signed-off-by: Anders Alfredsson <andersb86@gmail.com>

### CODE REVIEW

**Comment by fwolter** [comment]
Catching a division by zero exception, raised in your own code isn't a quite good solution. Better check if the divisor is zero beforehand.

**Comment by pacive** [comment]
> Better check if the divisor is zero beforehand.

That's what I did, the method returns `Optional.empty()` if the expression used as divisor returns zero.

https://github.com/openhab/openhab-addons/blob/b4a61f5093d732c4a17278a503bcf899d354f004/bundles/org.openhab.binding.smhi/src/main/java/org/openhab/binding/smhi/internal/ForecastAggregator.java#L41-L43

The catch-all is just so the binding won't crash if there are other exceptions thrown that I might have missed.

**Comment by fwolter** [comment]
Ok, I missed that. Catching unchecked exceptions in binding's scheduler threads is not necessary as the framework will catch and log them.

**Comment by pacive** [comment]
Yes, but if the exception is caught by the scheduler it stops scheduling new tasks, so the binding stops updating.

**Comment by pacive** [comment]
I know that it's probably bad practice to catch Exception, but is there a better way to prevent overlooked bugs from causing the binding to stop working?

**Comment by fwolter** [comment]
Are you sure the periodic task is cancelled completely? Actually, we came to the conclusion in https://github.com/openhab/openhab-core/issues/2392 that this is covered for bindings.

**Comment by pacive** [comment]
The user who [reported the issue](https://community.openhab.org/t/smhi-weather-binding/65728/36?u=pacive) had the binding stop updating, and I had a different issue earlier (which is already patched) that also caused the same symptom. The discussion you linked only seems to suggest that the exceptions are logged, not that the execution of the scheduled tasks continue? 

Should this be filed as an issue in oh core? I can see cases where you _don't_ want the task to continue be scheduled, e.g. to avoid tasks that consistently throws exception to continue to run, possibly hogging resources (which I admit would also be the case if everyone catches Exception in all tasks)

**Comment by fwolter** [comment]
You're right. The exception is logged and the periodic task is terminated. I think is is okay behavior. It's ok to let the binding crash (loudly) if it encounters a bug that needs to be fixed.

I'd remove the generic try-catch if it was my code as I think bugs should be fixed and not handled. I leave it up to you if you keep it or not. But if you keep it, you should make the log level error.

**Comment by pacive** [comment]
> I'd remove the generic try-catch if it was my code as I think bugs should be fixed and not handled. I leave it up to you if you keep it or not. But if you keep it, you should make the log level error.

I totally agree, but I also want to spare users from problems caused by my mistakes. I narrowed down the try-catch to `RuntimeException` and changed the logging to warn, with a suggestion to report the issue so it can be fixed properly. While working on fixing this one better I also made some changes which I believe should make it a bit more robust.

**Review by fwolter — APPROVED** [review]
LGTM

**Pull request merged**
