### PR TITLE
[growatt] Improved and extended documentation examples

### PR DESCRIPTION
**Pull request by andrewfg**
This PR extends and improves the documentation for example rule actions.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by lsiepel** [comment]
I have some hesitation about merging this. Examples are very usefull, don't get me worng. But we also have the community forums for sharing scripts etc. @openhab/add-ons-maintainers wdyt? Where is the 'line' between the binding docs and the community forums?

**Comment by andrewfg** [comment]
@lsiepel the original version of the ReadMe contains an example which was not optimal. This PR replaces the non optimal version with a better one (based on 6 months actual use of the binding). So I would in any case suggest to update that original example.

I also added a second example for a different use case. I guess we can discuss if it makes sense to add that second example as well.

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Comment by holgerfriedrich** [comment]
@lsiepel did you forget to merge?

**Comment by lsiepel** [comment]
> @lsiepel did you forget to merge?

No, checked some PR's and marked them ready. Just wanted to be sure that i could actually merge them without issues later today. (due to the RC1 etc).

**Pull request merged**
