### PR TITLE
[hue] Fix channel refresh (API v2)

### LINKED ISSUE #15669: [hue] Update other channels when Zigbee channel comes online
On API v2, when a device zigbee channel state changes from offline to online, the device thing handler should execute a poll to fetch the current state of all other channels.

See https://community.openhab.org/t/philips-hue-clip-2-api-v2-discussion-thread/142111/306?u=andrewfg

### LINKED ISSUE #15735: [hue] Refresh is not working correctly (API v2)
When linking a new item to a channel, its value is not updated in a timely manner.

## Expected Behavior
The binding should request initial state upon receiving a `REFRESH` command.

## Current Behavior
Under some circumstances the binding will skip the refresh logic.

## Possible Solution
The conditions here seem wrong:
https://github.com/openhab/openhab-addons/blob/2382a557d33dd2f21369aa7b15e0e446dfc9a191/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java#L304-L307

I believe it will skip the refresh logic when `updateServiceContributorsTask` is assigned and done.

## Steps to Reproduce
- Create a new Thing, for example a battery-powered sensor such as a motion sensor that will only rarely send data (on motion detection and periodically on temperature changes, etc).
- Link an item to a channel.
- Wait for the state to be set.

## Context
While working on #15552 I observed this behavior while testing.

A work-around is to disable and reenable the bridge Thing.

## Your Environment
* Version used: 4.0.3 and 4.1-snapshot

### PR DESCRIPTION
**Pull request by jlaur**
This fixes two issues:
- `REFRESH` command not working. This means, for example, that state will be missing after linking first item to a channel.
- Under specific circumstances (such as a thing migrated from API v1), refresh would be skipped when a device comes online, for example after being unreachable.

Fixes #15735
Fixes #15669

### CODE REVIEW

**Comment by andrewfg** [comment]
BTW your draft code LGTM :)

**Review by andrewfg — APPROVED** [review]
LGTM but we could eventually also include the code from my refresh PR into yours?

**Review by andrewfg — APPROVED** [review]
LGTM

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
