### PR TITLE
GitHub Actions upgrades and improvements

### PR DESCRIPTION
**Pull request by wborn**
* Use Maven 3.9.9
* Use Ubuntu 24.04
* Verify there are no changed files

### CODE REVIEW

**Review by J-N-K — APPROVED** [review]
LGTM

**Comment by J-N-K** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57:21 min (Wall Clock)
[INFO] Finished at: 2024-10-24T18:41:07Z
[INFO] ------------------------------------------------------------------------
[INFO] Static code analysis summary report is available in:
[INFO] file:/home/runner/work/openhab-addons/openhab-addons/target/summary_report.html
Error:  Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.3.1:jar-no-fork (attach-sources) on project org.openhab.voice.marytts: Error creating source archive: Problem creating jar: Execution exception: Java heap space -> [Help 1]
Error:  Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.4.1:jar (default-jar) on project org.openhab.voice.googlestt: Error assembling JAR: Problem creating jar: Execution exception: Java heap space -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :org.openhab.voice.marytts
Error: Process completed with exit code 1.
```

@wborn Do you think this is related to the changed maven or ubuntu-version?

**Comment by wborn** [comment]
>  Do you think this is related to the changed maven or ubuntu-version?

IIRC it sometimes also happens with Java 17 on Ubuntu 22.04. I'll retrigger it.

**Comment by holgerfriedrich** [comment]
@J-N-K If I remember correctly, I have seen the marytts test fail after one of the merges last week as well. It seems not to work reliably.

**Pull request merged**
