### PR TITLE
[nibeheatpump] Added new channels for F1x45 heat pumps

### PR DESCRIPTION
**Pull request by paulianttila**
Added:
- Reset Alarms channel
- 32bit Degree Minutes channel

Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

### CODE REVIEW

**Review by lsiepel — COMMENTED** [review]
Changes look good.

Looks like changes to the documentation is missing (readme channel example and i18n properties file) could you add those ?

**Comment by paulianttila** [comment]
> Looks like changes to the documentation is missing (readme channel example and i18n properties file) could you add those ?

Done

**Review by lsiepel — APPROVED** [review]
Looks good to me

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
