### PR TITLE
[avmfritz] Add missing entries to the default properties file

### PR DESCRIPTION
**Pull request by cweitkamp**
- Add missing entries to the default properties file

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by wborn** [comment]
When I did some grepping on translation keys ending with  `.pattern` but not `.state.pattern` I also found these which may have similar issues:

```
bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties:channel-type.hue.last_updated.options.pattern = %1$td.%1$tm.%1$tY %1$tH\:%1$tM\:%1$tS
bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties:channel-type.hue.last_updated.options.pattern = %1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz_de.properties:channel-type.deconz.last_updated.options.pattern = %1$td.%1$tm.%1$tY %1$tH:%1$tM:%1$tS
bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz_de.properties:channel-type.deconz.last_seen.options.pattern = %1$td.%1$tm.%1$tY %1$tH:%1$tM:%1$tS
```

**Review by wborn — APPROVED** [review]

**Comment by cweitkamp** [comment]
Thanks.

For deCONZ I submitted https://github.com/openhab/openhab-addons/pull/11546.

@lolodomo Are you planning to submit more fixes for the hue binding? If so, can you check the definition of state patterns for date formats? Thanks.

**Comment by lolodomo** [comment]
> @lolodomo Are you planning to submit more fixes for the hue binding? If so, can you check the definition of state patterns for date formats? Thanks.

I will do that this evening in #11535

**Comment by lolodomo** [comment]
This is now fixed in #11535, the key for channel pattern was still in double.

**Pull request merged**
