### PR TITLE
[hue] Factorize thing configurations

### PR DESCRIPTION
**Pull request by lolodomo**
Reduce the number of strings to translate

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@cweitkamp : please have a look. Before completing the French translation, I factorized some configuration settings to avoid a lot of duplicated strings to translate.
Normally, I fixed the German translations keys properly so it is not be impacted.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Comment by lolodomo** [comment]
@cweitkamp : I uploaded the updated German and French files in Crowdin. Can you please check everything is ok with the German translation ? Only one string is missing in German (the new discovery label).

**Comment by cweitkamp** [comment]
Thanks. Done. Full German translation available.

**Pull request merged**
