### PR TITLE
[guntamatic] Initial contribution: Binding for Guntamatic Heating Systems

### PR DESCRIPTION
**Pull request by MikeTheTux**
**Initial contribution: Binding for Guntamatic Heating Systems (Biostar, Powerchip, Powercorn, Biocom, Pro, Therm)**

I have implemented a Binding that can be used to monitor and control Guntamatic Heating Systems (https://www.guntamatic.com/en/).

The Guntamatic Binding was developed and tested using Guntamatic Biostar 15kW Pellets Heating System running Firmware 3.2d.
It should work for all other Guntamatic Heating Systems as well, that support the same web interface:

-    Biostar (tested via 15kW, firmware 3.2d)
-    Powerchip (untested)
-    Powercorn (untested)
-    Biocom (untested)
-    Pro (untested)
-    Therm (untested)

Forum topic:

- [#128451](https://community.openhab.org/t/guntamatic-new-binding-for-guntamatic-heating-systems-biostar-powerchip-powercorn-biocom-pro-therm/128451)

Test Build: 
- [org.openhab.binding.guntamatic-3.2.0-SNAPSHOT_v2.2.1.zip](https://www.dropbox.com/s/o17ruuk2qxs9c88/org.openhab.binding.guntamatic-3.2.0-SNAPSHOT_v2.2.1.zip?dl=0)

### CODE REVIEW

**Comment by MikeTheTux** [comment]
@lolodomo please find here the new PR, started from current OH3.3.0 SNAPSHOT HEAD.

**Comment by lolodomo** [comment]
This is the follow-up of #11598

**Comment by lolodomo** [comment]
I submitted a PR to your repo including the default translation properties.

**Comment by MikeTheTux** [comment]
Bad news: i18n still fails

```
D:\openhab-addons-guntamatic\bundles\org.openhab.binding.guntamatic>mvn i18n:generate-default-translations
[INFO] Scanning for projects...
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.openhab.core.tools:i18n-maven-plugin:jar:3.3.0-SNAPSHOT is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.openhab.core.tools:i18n-maven-plugin:3.3.0-SNAPSHOT: Plugin org.openhab.core.tools:i18n-maven-plugin:3.3.0-SNAPSHOT or one of its dependencies could not be resolved: Failure to find org.openhab.core.tools:i18n-maven-plugin:jar:3.3.0-SNAPSHOT in https://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading from central: https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/codehaus/mojo/maven-metadata.xml
Downloading from openhab-release: https://openhab.jfrog.io/openhab/libs-release/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 41 kB/s)
Downloaded from central: https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 28 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.152 s
[INFO] Finished at: 2022-01-09T19:29:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'i18n' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\mike\.m2\repository), central (https://repo1.maven.org/maven2), openhab-release (https://openhab.jfrog.io/openhab/libs-release)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

> I submitted a PR to your repo including the default translation properties.

reviewed and merged ...

**Comment by MikeTheTux** [comment]
> I submitted a PR to your repo including the default translation properties.

reviewed and merged ...

**Comment by lolodomo** [comment]
@MikeTheTux : I submitted a very last PR to your repo with improvements for your thing handler.
What is required is the additional exception catching in parseAndJsonInit.
Using constants from CoreItemFactory is better.
All the other changes are more suggestions to you.

**Comment by MikeTheTux** [comment]
> 



> @MikeTheTux : I submitted a very last PR to your repo with improvements for your thing handler. What is required is the additional exception catching in parseAndJsonInit. Using constants from CoreItemFactory is better. All the other changes are more suggestions to you.

reviewed, merged and updated

**Review by lolodomo — APPROVED** [review]
Code LGTM

**Comment by lolodomo** [comment]
@MikeTheTux : do you want time for retesting or do you give me the go for merging?

**Comment by MikeTheTux** [comment]
> @MikeTheTux : do you want time for retesting or do you give me the go for merging?

Please let me do some final testing before the merge.

**Comment by MikeTheTux** [comment]
> Code LGTM

go for it 🚀

thanks for all your effors. I owe you one 🍺

**Comment by lolodomo** [comment]
@MikeTheTux : thank your for contributing this new binding.

Now, you could add your binding's logo to the openHAB website. See https://www.openhab.org/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

**Comment by MikeTheTux** [comment]
> @MikeTheTux : thank your for contributing this new binding.
> 
> Now, you could add your binding's logo to the openHAB website. See https://www.openhab.org/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

https://github.com/openhab/openhab-docs/pull/1733

**Pull request merged**
