### PR TITLE
[exec] Support transformation chaining and refactor using ChannelTransformation

### PR DESCRIPTION
**Pull request by jimtng**

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
LGTM, did you consider adding this to the readme?

**Comment by jimtng** [comment]
> did you consider adding this to the readme?

what are you referring to?

**Comment by jimtng** [comment]
oops! I'm glad you noticed. I've added a note in readme

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
