### PR TITLE
fix console command documentation

### PR DESCRIPTION
**Pull request by J-N-K**
Follow-Up to #9342

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by marcelrv** [comment]
For the miio binding this needs also to be applied to the readme-base file, as the take file is automatically generated from the base file.

**Comment by J-N-K** [comment]
@marcelrv I did change that file. Are there more files I didn't see?

**Review by markus7017 — COMMENTED** [review]
LGTM

**Comment by marcelrv** [comment]
@J-N-K sorry missed that while viewing the PR on my small phone screen.
LGTM

**Pull request merged**
