### PR TITLE
[openwebnet] updated links in README

### PR DESCRIPTION
**Pull request by mvalla**
updated obsolete links in README and added pdf file for product datasheet (not in the official catalogue anymore)

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@kaikreuzer @wborn : is it ok to add a PDF of 1 MB as documentation ? It will increase the wieght of our package. Don't know exactly how much once zipped.

**Review by kaikreuzer — CHANGES_REQUESTED** [review]
The bundle size should not be an issue, because the doc folder is not bundled into it at all.
BUT: We do not have the copyright of that file and thus cannot add it to our repo under the EPL license. Instead, the README should only contain a link to its original location.

**Comment by mvalla** [comment]
Yes the copyright for the file is indeed an issue.
I removed the PDF file and put a link to a page still avaialble that describes the product (which is out of production, so its description is disappearing from catalogues.. that is why I proposed to save it here).
I also changed the PR title accordingly.

**Review by kaikreuzer — APPROVED** [review]
Thanks, that looks better to me.

If you are concerned that the file disappears one day, make sure you have a copy. 😄 
What you could do is to create some random GitHub repo without any license file and upload the file there. We could then link to that. But that might have time until the moment that the original is really taken down.

**Pull request merged**
