### PR TITLE
[tesla] Stop the WebSocket client when disposing the thing handler

### LINKED ISSUE #14341: [tesla] WEB socket client should be stopped
Class TeslaEventEndpoint manages a Web socket client. Of course it starts it but it never stops it.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #14341

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@jlaur : can you please merge this one that should avoid a potential memory leak.

**Comment by jlaur** [comment]
> can you please merge this one that should avoid a potential memory leak.

I was hoping @kaikreuzer would pick this since having a Tesla for testing. 😀 Let's merge and have it tested from first milestone.

**Review by jlaur — APPROVED** [review]
LGTM

**Comment by kaikreuzer** [comment]
I didn't see this PR, otherwise I would have tested. Will do so with the latest snapshot then. 😄

**Pull request merged**
