### PR TITLE
{WIP}[loxone] Fix possible resource leak

### PR DESCRIPTION
**Pull request by lolodomo**
Replace #8032
Related to #8027

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@J-N-K @kaikreuzer for review

**Comment by lolodomo** [comment]
I have a doubt why not suing a sessionFuture here like in other bindings.

**Comment by J-N-K** [comment]
The .get blocks until either the connection is established or failed. If you need the connection immediately, you can force it.

**Comment by lolodomo** [comment]
Ok. 
I have the strange feeling that this binding is reconnecting without first disconnecting properly,  I am not sure that it could not lead to other resource leak. 
The reconnection would occur after a command handling failed.

**Comment by lolodomo** [comment]
@ppieczul : are you available for discussing with us. My feeling is that your method disconnect should be called before trying to reconnect,

**Comment by ppieczul** [comment]
Hi. I am available. On the websocket connect, there is no need to wait for the confirmation or error. This is handled asynchronously from the websocket thread. Could you describe in more details the concern about the resource leak? There is chance this is true, but I need to better understand the scenario.

**Comment by lolodomo** [comment]
Please read the related issue for explanations. It concerns releasing a thread in case the connection is closed just after trying to connect. 

What about my remark concerning reconnecting stuff ?

**Comment by lolodomo** [comment]
Not sure if the proposed change is the best.

**Pull request closed without merging**
