### PR TITLE
[yioremote] Stop the web socket client when disposing thing handler

### PR DESCRIPTION
**Pull request by lolodomo**
Avoid a memory leak with web socket client not being stopped.

Also handle properly the case of the thing handler being quickly disposed.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Note that this one is clearly more severe.

**Comment by miloit** [comment]
Do you have a Testversion of it @lolodomo . Would be helpful for me ☺️.I am using oh3.4.1.

**Review by miloit — APPROVED** [review]
I tested today looks good

@kaikreuzer cherry picking for oh3.4.x would be nice

**Comment by miloit** [comment]
Approved

**Comment by lolodomo** [comment]
@miloit :why did you close my PR?

**Comment by miloit** [comment]
@lolodomo as written via pn it was a mistake..... apologize

**Comment by lolodomo** [comment]
@jlaur : please have a look to this one, it has higher priority than my other PRs related to  using destroy.

**Comment by jlaur** [comment]
> please have a look first to this one, it has higher priority than my other PRs related to using destroy.

My question for this one would be the same: https://github.com/openhab/openhab-addons/pull/14336#issuecomment-1435702918. I think that Jetty manages its own lifecycle so that you shouldn't need to explicitly call `destroy()`, but I'm not 100% sure. Perhaps it would be worth testing? Otherwise I would leave it out of this PR until proven.

**Comment by lolodomo** [comment]
> My question for this one would be the same: [#14336 (comment)](https://github.com/openhab/openhab-addons/pull/14336#issuecomment-1435702918). I think that Jetty manages its own lifecycle so that you shouldn't need to explicitly call `destroy()`, but I'm not 100% sure. Perhaps it would be worth testing? Otherwise I would leave it out of this PR until proven.

The problem here is not the missing destroy but the missing stop.
So I am going tol remove the "destroy" so that you can quickly merge the 2 real problems fixed by this PR.

**Comment by jlaur** [comment]
> The problem here is not the missing destroy but the missing stop.

I understand. 🙂 

> So I am going tol remove the "destroy" so that you can quickly merge the 2 real problems fixed by this PR.

Agreed.

**Comment by lolodomo** [comment]
@jlaur: ready for your review (destroy removed)

**Review by jlaur — APPROVED** [review]
Thanks for the fix!

**Comment by lolodomo** [comment]
Thank you.
This is IMHO a candidate for 3.4.x branch.

**Pull request merged**
