### PR TITLE
[linktap] Fix build

### PR DESCRIPTION
**Pull request by jlaur**
Regression of openhab/openhab-core#4389

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks for the quick fix. LGTM 
Not sure why it is critical, as this is not released into any stable or milestone.

**Comment by jlaur** [comment]
> Not sure why it is critical

Okay, maybe exageration, but since build is broken, snapshots are not being created.

**Comment by jlaur** [comment]
To be fair, actually regression of #17235. The core PR was merged first, so when #17235 was merged shortly after, it was already broken, but this was not detected because the latest build succeeded.

**Comment by dag81** [comment]
@jlaur @lsiepel Thank you for looking and sorting -  sorry this weeks been manic at work and just catching up now. I couldn't figure out how that got through the pipelines until I saw the comments above. For my future reference where are the outputs from these pipelines for the regression runs?

**Pull request merged**
