### PR TITLE
[icalendar] Use cache folder to store calendar file

### PR DESCRIPTION
**Pull request by cweitkamp**
- Use cache folder to store calendar file

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Review by daMihe — APPROVED** [review]

**Review by daMihe — CHANGES_REQUESTED** [review]
Ahh, clicked too fast on approve! PullJob is missing.

**Comment by cweitkamp** [comment]
What do you mean by that? Did I miss something?

**Comment by daMihe** [comment]
> What do you mean by that? Did I miss something?

First i did not think you missed something so i approved. Then i thought about PullJob. Now i'm not sure because the github review section shows too less context. I'm sorry for my confusion, i'll review offline in next minutes and do a quick end to end check.

**Review by daMihe — APPROVED** [review]
LGTM. This time really.

**Review by cpmeister — APPROVED** [review]
LGTM

**Pull request merged**
