### PR TITLE
Simplify `DateTimeType` handling

### PR DESCRIPTION
**Pull request by jlaur**
This is a cleanup only and does not change functionality when openhab/openhab-core#3583 has first been merged. The core PR discards time-zone from `DateTimeType`, thus binding code can be simplified:
- Instantiations from `ZonedDateTime` using either time-zone from `TimeZoneProvider` or `ZoneId.systemDefault()` have been simplified to use `Instant`. In some cases this entirely eliminated the need for `TimeZoneProvider`, which has then been removed.
- Usages of deprecated methods `toZone` and `toLocaleZone` have been removed.
- Usages of deprecated method `getZonedDateTime()` have been removed. In cases where time-zone is needed, `getZonedDateTime(ZoneId.systemDefault())` is now explicitly called.

Related to openhab/openhab-core#3583

### CODE REVIEW

**Review by clinique — APPROVED** [review]

**Review by theater — APPROVED** [review]
LGTM. Looks much cleaner. Thank you!

**Review by dougculnane — APPROVED** [review]
LGTM

**Review by maniac103 — APPROVED** [review]

**Comment by andrewfg** [comment]
@jlaur this looks like a massive change; albeit a good simplification; but just so I can be fully sure, can you please confirm that the 'TLDR' of your change is as follows..

1. any "essence of time zone" has been removed from `DateTimeType`
2. so bindings need no longer worry about "essence of time zone" -- and become only responsible for "Instant" data
3. any "essence of time zone" that had been removed above, is added back by OH core (when not otherwise already so done)

=> Is that correct?

**Comment by jlaur** [comment]
> * any "essence of time zone" has been removed from `DateTimeType`

Correct.

> * so bindings need no longer worry about "essence of time zone" -- and become only responsible for "Instant" data

Correct,

> * any "essence of time zone" that had been removed above, is added back by OH core (when not otherwise already so done)

It depends what you mean by "added back", but in context of this PR - i.e. for addons - it means:
- You don't have to provide time-zone when instantiating a `DateTimeType` (it will be discarded anyway).
- You can't get time-zone from a `DateTimeType`. You will have to get it from another source, e.g. `TimeZoneProvider`, `ZoneId.systemDefault()` or configuration.

Many more details can be found in the mentioned core PR, especially the table in the description showing "before" and "now" can give a quick understanding of the change.

**Comment by jlaur** [comment]
Rebased and skipped one commit since #17872 is already merged.

**Review by hmerk — APPROVED** [review]
LGTM

**Review by andrewfg — APPROVED** [review]
Hue => LGTM
Tado => LGTM

**Review by ccutrer — APPROVED** [review]
LGTM for:
 * mqtt.generic
 * persistence.jpa

**Review by florian-h05 — APPROVED** [review]
LGTM for evcc.

**Review by david-pace — APPROVED** [review]
LGTM for `boschshc`

**Comment by lsiepel** [comment]
@jlaur do you recommend to have this merged before 4.3.0?

I’m in doubt, merging it has some risks due to amount of files and lack of test time. Not merging it will make 4.3.x patches harder due to the amount of files and possible conflicts. WDYT?

**Comment by jlaur** [comment]
> do you recommend to have this merged before 4.3.0?

This is only simplifications/optimizations, so it is not needed for 4.3, but...

> I’m in doubt, merging it has some risks due to amount of files and lack of test time.

I agree.

> Not merging it will make 4.3.x patches harder due to the amount of files and possible conflicts. WDYT?

Perhaps one way to mitigate this issue would be to merge it in the very beginning of the 5.0 development cycle and avoid squash-merging. When preserving all commits, it would be a simple matter of cherry-picking the commit for a specific binding before cherry-picking the patch commit. WDYT?

I have carefully crafted one commit per binding. This makes it easier for me to handle potential conflicts, and it also allowed me to quickly cherry-pick a single commit into #17872 for fixing a CI test. It has also helped me keeping a clean history by squashing commits when I had to do multiple iterations for a single binding.

**Review by druciak — APPROVED** [review]
Satel LGTM

**Review by EvilPingu — APPROVED** [review]

**Review by ccutrer — APPROVED** [review]
LGTM for WiZ

**Comment by jlaur** [comment]
> > Not merging it will make 4.3.x patches harder due to the amount of files and possible conflicts. WDYT?
> 
> Perhaps one way to mitigate this issue would be to merge it in the very beginning of the 5.0 development cycle and avoid squash-merging. When preserving all commits, it would be a simple matter of cherry-picking the commit for a specific binding before cherry-picking the patch commit. WDYT?
> 
> I have carefully crafted one commit per binding. This makes it easier for me to handle potential conflicts, and it also allowed me to quickly cherry-pick a single commit into #17872 for fixing a CI test. It has also helped me keeping a clean history by squashing commits when I had to do multiple iterations for a single binding.

Just a small reminder about this suggestion, did you consider it @lsiepel?

**Comment by lsiepel** [comment]
> ps one way to mitigate this issue would be to merge it in the very beginning of the 5.0 development cycle and avoid squash-merging. When preserving all commits, it would be a simple matter of cherry-picking the commit for a specific binding before cherry-pickin

Yes, i think that is the best. As you where still adding changes, i waited. Does it mean this PR is finished now?

**Review by lsiepel — APPROVED** [review]

**Comment by jlaur** [comment]
@lsiepel - thanks for the review, I know it was quite a lot of files.

**Comment by lsiepel** [comment]
back ported commit for Network binding. (i can't set a patch anywhere, so i leave this message here)

**Pull request merged**
