### PR TITLE
[jdbc] Bump mysql-connector-java to version 8.0.22

### PR DESCRIPTION
**Pull request by cweitkamp**
- Bump mysql-connector-java to version 8.0.22

Superseedes #8511

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Review by fwolter — APPROVED** [review]

**Comment by mhilbush** [comment]
@cweitkamp I'm running build 2142, which was built today (well after the build of the addons repo that contains this PR). I still see mysql connector version 8.0.13. Do you know why I'm not seeing 8.0.22?

**Comment by mhilbush** [comment]
Ah ha! Here?
https://github.com/openhab/openhab-addons/blob/main/features/pom.xml#L25

**Comment by cweitkamp** [comment]
What a pity. The bump of MariaDB library in https://github.com/openhab/openhab-addons/pull/8883 is not considered too. I will submit a fix for it.

**Comment by mhilbush** [comment]
Looks good now.

**Comment by cweitkamp** [comment]
Thanks for the feedback. Same for MariaDB.

**Pull request merged**
