### PR TITLE
[apcupsd][WIP] APC UPS Daemon Binding initial contribution

### PR DESCRIPTION
**Pull request by bodiroga**
Hi everyone!

This is my first attempt to write a binding from scratch, but it is not finished yet.

To-Do's:

- [ ] Write the README.md file
- [ ] Test if the binding works with static thing definition files (I have only tested it through Paper UI)
- [ ] JavaDocs everywhere!

I know that I have label it as WIP, but I'm not sure if architectural wise the design is fine, any comment? Anyway, put this is your low priority task list :wink: 

Thanks for all your work and best regards,

Aitor

Signed-off-by: Aitor Iturrioz <riturrioz@gmail.com>

### CODE REVIEW

**Comment by MyRaceData** [comment]
Hi Aitor
My name is Andrew. I am an openhab user and frequent the openhab community forum. My user name is Andrew_Rowe I will be happy to help you with writing the readme file for this binding if you want help. I have a APC battery backup which is capable of using the binding, so I can use the binding myself to help me learn and I am a native english speaker and have 1 or 2 pull request for the documentation under my belt
Thanks
Andy

**Comment by curlyel** [comment]
Hi Aitor,
are you still working on it? Keen to get (direct) apcupsd-support in openhab too. I may help with testing an documentation.

**Comment by MyRaceData** [comment]
Yes, me as well
Is there a JAR file we can try out?

**Comment by curlyel** [comment]
Hi Aitor,
sorry for bothering ;-)

Since Kai has mentioned to focus _now_ on reviewing/merging the PR queue, it's likely a good time to let the maintainers know (again) about your new binding contribution:

_Kai:_ _"... but definitely want to get 2.5 out of the door this year, likely around early December. No dates are set yet, but that’s roughly the timeline to expect. As some might have noticed already, the focus is currently to get the PR queue for new bindings done and merged - so if you are one of the contributors, who is waiting since a long time for a review, now is a good moment to ping us on your PR to get the well-deserved attention :slight_smile: ...."_

copied from: [https://community.openhab.org/t/openhab-milestone-builds/50359/387](url)

**Comment by bodiroga** [comment]
Sorry, but with the release of the Network UPS Tools Binding (https://www.openhab.org/addons/bindings/networkupstools/), I have abandoned the development of this binding.

**Pull request closed without merging**
