### PR TITLE
[myq] Switch to using oAuth for logins

### LINKED ISSUE #11163: [MyQ] Binding Failing on HTTP 400 Error
In the last few days the MyQ Binding is failing:

COMMUNICATION_ERROR
Invalid Response Code 400 : { "SecurityToken": "", "ReturnCode": "0", "ErrorMessage": "please contact customer care, supportID: 2500410849209689490", "CorrelationId": "" }

I'm guessing it is related to this previous issue noted in the Homebridge MyQ plugin and that the User Agent needs to be updated in the binding code?

https://github.com/iRayanKhan/homebridge-chamberlain/issues/105

### PR DESCRIPTION
**Pull request by digitaldan**
Switch to using an oAuth flow for login requests as  the MyQ is no longer accepting legacy login methods, which has rendered  our current implementation non functional for users. 
Fixes #11163

### CODE REVIEW

**Comment by digitaldan** [comment]
Ready for review, thanks!

**Comment by Rathna-K** [comment]
any reason why it is blocked or when it will be merged ?

**Comment by digitaldan** [comment]
> any reason why it is blocked or when it will be merged ?

Its not blocked, our reviewers are very busy and have a lot of other PR's to review, its only been 3 days since i removed the WIP tag.

**Review by fwolter — APPROVED** [review]
LGTM

**Comment by digitaldan** [comment]
Thanks !!!!

**Comment by lolodomo** [comment]
@digitaldan : I think there is a potential problem at this line while your HTTP client is the common HTTP client
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java#L295

**Comment by digitaldan** [comment]
> This can erase cookies set by other bindings.

😱  well poop.  I assumed it was somehow scoped local to the binding, let me create a PR to fix that.  Thanks for pointing this out!

**Comment by digitaldan** [comment]
@lolodomo i have a fix at #11343 if you would be kind enough to review, thanks again for finding this, what a mess up!

**Pull request merged**
