### PR TITLE
[dsmr] Fix IllegalStateException in rfc2217 connector

### PR DESCRIPTION
**Pull request by lsiepel**
Fixes: https://github.com/openhab/openhab-addons/issues/15529

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]

**Comment by lolodomo** [comment]
@lsiepel : are you waiting for a user feedback or can we merge?

**Comment by lsiepel** [comment]
> @lsiepel : are you waiting for a user feedback or can we merge?

Please merge.

**Comment by lolodomo** [comment]
It looks like we have a problem with Jenkins:

image

**Comment by lolodomo** [comment]
@wborn @kaikreuzer for information about Jenkins problem.

**Comment by kaikreuzer** [comment]
@lolodomo I guess this was an automatic patch deployment - at least the warning has gone and the builds seem to work well. Let me know if you still see any issue there.

**Comment by wborn** [comment]
Hello, I did have to restart Jenkins to get the builds working again.
Then after a while the shutdown message showed again, so I restarted it again. :neutral_face:

**Pull request merged**
