### PR TITLE
[homekit] update AuthInfo objects when blockUserDeletion changes

### PR DESCRIPTION
**Pull request by ccutrer**

### CODE REVIEW

**Review by yfre — APPROVED** [review]
LGTM

thank you for the fix. so, it was not properly working on changes

**Comment by ccutrer** [comment]
Yeah, you had to restart the addon (or all of OpenHAB) to get it to respect the changed setting

**Review by lolodomo — APPROVED** [review]
Code LGTM

**Comment by jlaur** [comment]
@ccutrer - I see no linked issue or PR description. If this is to be cherry-picked into the hotfix also, can I ask you to update the description so we have the impact/nature of the bug just briefly described?

**Comment by ccutrer** [comment]
Not a problem. I guess it's not as obvious what's going on when you're not neck deep in this code already ;). This probably added an extra 30-40 minutes of debugging when I was trying to fix the iOS 16.2 pairing issues.

**Pull request merged**
