### PR TITLE
[deconz] fix color temperature channel

### LINKED ISSUE #7884: [deconz]  Color Temperature not functional
For lamps (extendedcolorlight / colortemperaturelight) the Color Temperature item is defined as "Number". Setting this item to any number in the interval 0 to 100 does not change the actual lamps color temperature.
I would also expect the color temperature to be a dimmer item rather than a number item

## Expected Behavior
Setting a number to the colortemperature item should change the lamps color temperature
It should preferably be a dimmer item rather than a number item

## Current Behavior
Opposite to Expected

## Context
I am trying to migrate from Zigbee binding to deconz. But need colortemperature control

## Your Environment
* Version used: (e.g., openHAB 2.5.5 and deconz add-on snapshot build 2020-06-06)
* Environment name and version (e.g.  Java 8.):
* Operating System and version (openhabian on pi4.):

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #7884 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by cpmeister** [comment]
I have no idea if this fixes the issue. Can anyone vouch for this?

**Comment by J-N-K** [comment]
The error message complains about „trying to set read-only color-mode“ (See linked issue). So not sending the color Mode should fix this.

**Comment by MHerbst** [comment]
@cpmeister I have tested the modification. Works correctly now.

**Comment by danli003** [comment]
Works perfectly. Many thanks for your efforts!

**Pull request merged**
