### PR TITLE
[WIP][pushover] Migration of Pushover OH1 action to OH3 binding

### PR DESCRIPTION
**Pull request by cweitkamp**
- Migration of Pushover action to OH3 binding

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by cweitkamp** [comment]
@wborn Hm, I have to dig into it again. But IIRC the basic functions are already working. I now have to finish the README.md, the German translations and migrate the tests to JUnit 5 - will try to use your helper script in [Gist](https://gist.github.com/wborn/a8d4ca26471a92e431211f34027138f6). Maybe more.

Do you want to test it? Shall I provide a *.jar file or can you build it on your own :wink:.

**Comment by wborn** [comment]
If it should already work, I will probably soon give it a try with a local build. :+1: 
But it seems to have some compilation issues now @cweitkamp.

**Comment by cweitkamp** [comment]
@wborn I fixed it. I was working on `ThingActions` bug in parallel and thus some movements of classes were committed wrong.

**Comment by kaikreuzer** [comment]
Could you please re-create this PR against the `main` branch?
See point (4) in https://github.com/openhab/openhab-addons/issues/8512. Thanks!

**Pull request closed without merging**
