### PR TITLE
Migrate to java.nio.file.createTempFile

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Use function from nio package as it uses more restrictive file permissions.

### CODE REVIEW

**Comment by daMihe** [comment]
From code perspective, it‘s a small change. Did you test functionally? For icalendar, there is currently no integration test.

**Comment by holgerfriedrich** [comment]
@daMihe No, I do not have the addons in use - and I don't know if I had triggered the generation of a temp file. Just trying to remove use of this calls from the codeabase.

**Comment by jlaur** [comment]
For reference:
- https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#createTempFile(java.lang.String,java.lang.String)
- https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Files.html#createTempFile(java.lang.String,java.lang.String,java.nio.file.attribute.FileAttribute...)

**Comment by lolodomo** [comment]
The risk seems low (like the benefit ;) ).
@jlaur: WDYT ? Are we merging without someone testing it ?

**Comment by jlaur** [comment]
> WDYT ? Are we merging without someone testing it ?

I agree that risk seems low. We can merge before milestone 1 and hope it will be tested eventually before the release.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
> I agree that risk seems low. We can merge before milestone 1 and hope it will be tested eventually before the release.

Ok, so I merge.

**Comment by lolodomo** [comment]
We don't put any label on such PR because it is too much technical for the release notes, correct ?

**Pull request merged**
