### PR TITLE
[yioremote] Bug fix during websocket error by disposing pollingjob

### PR DESCRIPTION
**Pull request by miloit**
Signed-off-by: Michael Loercher<michaelloercher@web.de>

Bug fix during websocket error by disposing pollingjob

### CODE REVIEW

**Review by J-N-K — COMMENTED** [review]
Agreed, the polling hpuld be disabled. But wouldn't it make sense to re-connect on error?

**Comment by miloit** [comment]
I reconnect to the websocket and after the reconnection is positive the polling job will be started again

**Review by J-N-K — APPROVED** [review]

**Review by J-N-K — APPROVED** [review]

**Comment by J-N-K** [comment]
Can you fix the sign-off?

**Comment by miloit** [comment]
Done

**Comment by J-N-K** [comment]
Jenkins failed in feed tests.

**Pull request merged**
