### PR TITLE
[hccrubbishcollection] HCC Rubbish Collection Binding - Initial Contribution

### PR DESCRIPTION
**Pull request by Cossey**
A binding that displays rubbish collection days for Hamilton City Council (New Zealand).

This binding is simple and polls a web API. It uses to the [Fight the Landfill](https://fightthelandfill.co.nz) website rubbish collection API that I had discovered. This API displays the date when the recycling and the general rubbish will be collected as well as the collection day of week for an address, which gets pulled into channels.

There is also an event that triggers for the day of collection that also supports an offset of up to +- 2 days, in minutes. You can use the event in a rule so that you can do what you need, in my case I send myself a notification reminder to put out the rubbish the night before, using an offset of `-300`.

### CODE REVIEW

**Review by fwolter — COMMENTED** [review]
Thanks for your contribution! I reviewed your code and here is my feedback.

Please add yourself to the `CODEOWNERS` file and add an entry to `bom\openhab-addons\pom.xml`.

**Comment by Cossey** [comment]
Thanks @fwolter for the feedback, I will go ahead and make required corrections.

**Comment by Cossey** [comment]
@fwolter all done. Thanks for reviewing.

**Comment by Cossey** [comment]
I made a fix with gson and commented the code further.

I made additional improvements based on #10549 since I have designed these bindings in the same way.

**Comment by Cossey** [comment]
@fwolter Can you review please and approve if it all looks okay? Thanks heaps!

**Review by fwolter — CHANGES_REQUESTED** [review]
Your code doesn't compile as there are some formatting issues. You can fix them with `mvn spotless:apply`.

**Comment by Cossey** [comment]
Apologies @fwolter, I missed that check after that last set of changes. All fixed now.

**Pull request merged**
