### PR TITLE
[kodi] Changed 'systemcommand' channel to command options

### PR DESCRIPTION
**Pull request by cweitkamp**
- Changed 'systemcommand' channel to command options

Testing for https://github.com/openhab/openhab-core/pull/1422 and https://github.com/openhab/openhab-webui/pull/217

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by Hilbrand** [comment]
@cweitkamp What are your plans for this pull request? The code looks ok. Except for the current conflict does it need any changes?

**Comment by cweitkamp** [comment]
@Hilbrand in general this implementation is final. I will try to solve the conflicts asap to get this PR into mergable status.

**Comment by cweitkamp** [comment]
@Hilbrand Rebase done.

**Review by Hilbrand — APPROVED** [review]
LGTM. I assume the label work-in-progress can be removed?

**Comment by cweitkamp** [comment]
Yes, of course. I removed it.

**Pull request merged**
