### PR TITLE
[mielecloud] Fix mockito concurrency issues in integration tests

### PR DESCRIPTION
**Pull request by BjoernLange**
See #11589.

### CODE REVIEW

**Comment by wborn** [comment]
Thanks for having a look @BjoernLange! :+1: 

It seems that there is still some kind of timing issue because this test in the GitHub Actions CI build failed:

```
TEST org.openhab.binding.mielecloud.internal.handler.HoodDeviceThingHandlerTest#testChannelUpdatesForNullValues() <<< ERROR: expected: <UNDEF> but was: <NULL>
org.opentest4j.AssertionFailedError: expected: <UNDEF> but was: <NULL>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at org.openhab.binding.mielecloud.internal.handler.HoodDeviceThingHandlerTest.lambda$0(HoodDeviceThingHandlerTest.java:68)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:84)
	at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.waitForAssert(AbstractMieleThingHandlerTest.java:135)
	at org.openhab.binding.mielecloud.internal.handler.HoodDeviceThingHandlerTest.testChannelUpdatesForNullValues(HoodDeviceThingHandlerTest.java:67)
```

**Comment by BjoernLange** [comment]
I'll check it...

**Comment by BjoernLange** [comment]
I think I found something that could break the tests, at least the build is green now...

**Review by wborn — APPROVED** [review]
Thanks for having a look!

**Pull request merged**
