### PR TITLE
[bluetooth.bluegiga] Add characteristic notification support

### PR DESCRIPTION
**Pull request by cpmeister**
My test system for OH3 only uses bluegiga so I had to implement the missing notification feature as well as fix an annoying bug that prevented the bluegiga binding from starting correctly.

This PR requires #9064  to be merged first.

### CODE REVIEW

**Comment by cpmeister** [comment]
build failure unrelated

**Comment by kaikreuzer** [comment]
... but it fails on some bluetooth classes. Might https://github.com/openhab/openhab-addons/pull/9064 have introduced these compilation errors?

**Comment by cpmeister** [comment]
off, somehow missed that. I expected the first failure to stop the build. I'll make a fix for the build

**Comment by cpmeister** [comment]
Looks like the compilation errors came from the new bluetooth.generic binding. The null checker got a little overzealous, I've create a fix for it. #9115

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks.

**Pull request merged**
