### PR TITLE
[mycroft] gson checkstyle fixes

### PR DESCRIPTION
**Pull request by lsiepel**
Some minor checkstyle fixes for gson fields

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@lsiepel : these fields were there but not used anywhere ? Because I see no change where they would be used.

**Comment by lsiepel** [comment]
> @lsiepel : these fields were there but not used anywhere ? Because I see no change where they would be used.

Yes, i came to the same conclusion. I guess the dto objects hold all properties, wheter they are used or not.

**Comment by dalgwen** [comment]
Sorry for the late reply.

> @lsiepel : these fields were there but not used anywhere ? Because I see no change where they would be used.

Yes, they are not used. You guessed right, I put all properties inside the DTO, "just in case".

**Pull request merged**
