### PR TITLE
[knx] Fix deprecated tag "required"

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@fwolter : "required" is false by default for a parameter, I believe. Setting the attribute to false is I believe then useless.
I have the feeling we should set it only when its value is "true".
WDYT ?

**Comment by fwolter** [comment]
I would've no problems relying on the default value, but I won't insist on removing it either. I like concise code, so I personally would remove it.

**Comment by lolodomo** [comment]
Few developers chose to set it systematically, I will not change in this case.
In case, it is set to "false" only sometimes, you could remove it.

**Review by fwolter — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Let me still few minutes to check my other PRs.

**Comment by fwolter** [comment]
I'll wait until Jenkins is green.

**Comment by lolodomo** [comment]
Ok, I checked all my PR and changed one. You can review when you like.

**Comment by lolodomo** [comment]
I have now created a PR for each binding having 10 or more items to fix.
For the next step, I will create PRs for multiple bindings.

**Pull request merged**
