### PR TITLE
[openhabcloud] Add the missing configuration parameter for NOT_EXTENDED actions

### PR DESCRIPTION
**Pull request by jimtng**

### CODE REVIEW

**Review by florian-h05 — COMMENTED** [review]
Thanks for this fix, I just checked the UI and yeah, the message param is missing.

As you already are on it, can you please take a look at line 60 and fix the following?
There the config for the broadcast notification is defined/created, and the second argument for the getNotificationConfig call should be false, because for broadcast notification no user ID is required.

**Comment by florian-h05** [comment]
BTW this should be backported once merged.

**Comment by jimtng** [comment]
> As you already are on it, can you please take a look at line 60 and fix the following?
> There the config for the broadcast notification is defined/created, and the second argument for the getNotificationConfig call should be false, because for broadcast notification no user ID is required.

Good catch! Fixed.

**Review by florian-h05 — APPROVED** [review]
LGTM now, thanks!

I’m not sure how Java handles that exactly (you would need to try it), but would it make sense to remove the default case from the switch statement so that a compiler warning is thrown when the enum is modified but the switch statement is not?

**Comment by jimtng** [comment]
Are you referring to line 173? I tried removing default and one case, and java doesn't complain.

**Comment by florian-h05** [comment]
Yes.
Okay, I’m not too surprised — I have never heard about this until the guy who graded my programming exam at university said it would work that way, and then marked my solution as wrong because I had a default case there … probably should have tried it out back then to prove ho wrong. 😂🤦‍♂️

**Comment by jimtng** [comment]
Kotlin forces you to have all cases, or a default.

**Review by lsiepel — APPROVED** [review]

**Comment by jimtng** [comment]
A reminder to backport this

**Comment by lsiepel** [comment]
> A reminder to backport this

Done, thanks for the reminder.

**Pull request merged**
