### PR TITLE
Add issue template config

### PR DESCRIPTION
**Pull request by mueller-ma**
Add issue template config

Instead of using a dummy issue template for support questions, use a
issue template config.

It's live on my fork ("Report a security vulnerability" is probably gone, because it's a fork): https://github.com/mueller-ma/openhab-addons/issues/new/choose

After reviewing the config here it should be added to all other repos as well. Using the `.github` repo didn't work on my fork.

### CODE REVIEW

**Comment by wborn** [comment]
Looks fine to me. Not so sure about `blank_issues_enabled: false` though, sometimes there are RFCs or issues about infrastructure or failing unit tests that may not fit any of the regular flows. 

This may also be a time to update the bug template to add something about including the environment data generated in the OH3 UI, i.e. the webui repo has:

```
<!--
As an admin, in the main UI, choose *Help & About* on the left sidebar, expand *Technical information* and click on *View details*, then click *Copy* and paste the results here. You may omit information that is not pertinent to this issue if you feel it's divulging information you'd like not to share.
-->
```

**Comment by wborn** [comment]
> After reviewing the config here it should be added to all other repos as well. Using the .github repo didn't work on my fork.

I also added something similar now for [openhab-docker](https://github.com/openhab/openhab-docker/issues/new/choose) as it was already on my todo list. :slightly_smiling_face:

**Comment by mueller-ma** [comment]
> Not so sure about blank_issues_enabled: false though, sometimes there are RFCs or issues about infrastructure or failing unit tests that may not fit any of the regular flows.

I changed it to `true`. 

> This may also be a time to update the bug template to add something about including the environment data generated in the OH3 UI

Good idea, I added something similar in the openhab-android repo.
Can you do this for this repo in a new PR? I don't have a lot of experience with the new UI.

**Review by wborn — APPROVED** [review]
Thanks for the improvements!

**Pull request merged**
