### PR TITLE
[Mcp23017] Fix null pointer exception in dispose() for #6111

### PR DESCRIPTION
**Pull request by 9037568**
Fixes the null pointer exception reported in #6111 .

### CODE REVIEW

**Comment by 9037568** [comment]
Whatever for?

**Comment by J-N-K** [comment]
There is no guarantee the pinStateHolder field is not manipulated by other methods between the check and the later call.

**Comment by 9037568** [comment]
Ok, got it. Thanks for the explanation.

**Comment by J-N-K** [comment]
Could you rebase, so we can merge?

**Comment by 9037568** [comment]
>Could you rebase, so we can merge?

@J-N-K I'm working on this but I'm not entirely clear on what I need to do. Is the following correct?

- git checkout mcp6111
- git merge 2.5.x
- git rebase -i

??

Thanks!

**Comment by J-N-K** [comment]
I would do

```
git fetch <upstream repo name>
git checkout <your branch name>
git rebase <upstream repo name>/2.5.x
<resolve conflicts>
git push <your repo name> +<your branch name>
```

Since I always add the openHAB repo as `upstream`, I‘m not sure what the standard setup is. <your repo name> usually is `origin`, the upstream repo might be the same in your case.

**Pull request merged**
