### PR TITLE
[actiontemplatehli] Simplify usage and readme

### PR DESCRIPTION
**Pull request by GiviMAD**
I have have rewritten some parts of this service, to simplify its usage, as I think I overcomplicate things too much on the initial contribution.

I have removed a lot of NLP terminology and non intuitive explanations from the README while updating it to match all the other changes introduced.

I have remove all the NLP terminology from the placeholders configuration names, as it was not user friendly. Also the configuration files for the placeholder values and transformations are all in json format instead of xml, and the transformations files (now called mappedValues of the placeholder) can be reused between read and write actions because the keys define the 'user readable' value and the values the equivalent 'item state'.

Also have improved the template system:
* You can made tokens optional on the template by adding '?' to the end. Also I've removed the configuration option for made optional all tokens matching a certain tag, as I think it's more controlable and intuitive this way.
* Now you can choose to match a specific token by tag or lemma by prefixing it, so you can do thinks like "how \<lemma>be the $itemLabel". So I have removed the action type "lemmas".

Only think new that I have added is a new type for the action called "dice", to use a dice's coefficient comparison instead of the default one (equality).

Sorry for the PR been so big, I think the changes were needed as the initial version miss a lot of usability and the options for the placeholders were hard to configure, also the readme itself. I'll try not to made a change so big again because I understand reviewing this is a lot of work.

Thank you for your time!

Signed-off-by: Miguel Álvarez <miguelwork92@gmail.com>

### CODE REVIEW

**Comment by GiviMAD** [comment]
Fixed build errors and regenerated the translations.

**Comment by GiviMAD** [comment]
I needed to add another commit because I detected some errors on the scoring mechanism.
I've added some unit tests for those situations.

**Comment by lolodomo** [comment]
@GiviMAD : why did you close this PR ? You thing the change is not more a good idea ?

**Comment by GiviMAD** [comment]
Hi @lolodomo, I'd moved this pr version to the marketplace.
I think that a couple of things can be improved, and I think I'll remove the dice comparison as it's difficult to understand, and make a little UI to help the phrase configuration, so this is as easy to use as possible, because based on the little feedback I got I think is too complex for users to be interested on it, but I hope with some changes it gets more attractive.

**Pull request closed without merging**
