### PR TITLE
[hdpowerview] Update shade database

### PR DESCRIPTION
**Pull request by andrewfg**
Add Shade type 65 to database.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
@andrewfg - consider if PR title should be changed to "[hdpowerview] Add full support for Vignette Duolite" or something more specific for the release notes? As I understand it, adding correct capabilities to the database will ensure that position calculations are correct, so without it defaults are used, which can lead to some undesired behavior?

**Comment by andrewfg** [comment]
@jlaur I chose the title 'Update Shade Database' because there will be several such generic updates, and this is just one of many. The PR description (will) say(s) what was actually updated in each PR.

Note: this new shade type has an existing 'capabilities' value, so its functionality has already been coded, and therefore no functional changes are required now..

**Comment by lolodomo** [comment]
I agree that a more precise title would be better.

**Pull request merged**
