### PR TITLE
[haassohnpelletstove] Initial contribution

### PR DESCRIPTION
**Pull request by chingon007**
[haassohnpelletstove]

This binding controls a Pellet stove from Haas & Sohn through the optional WIFI modul. It is able to retreive actual temperature, the actual mode of the stove, the set temperature and turn on and off the stove. The goal was to make this device available in openhab. 

It is the second try to open the pull request, as the one before was automtically closed.

### CODE REVIEW

**Comment by chingon007** [comment]
@fwolter Lets try again.

**Comment by fwolter** [comment]
There were still foreign commits in your branch. I deleted them. Now we're waiting for Jenkins to complete the build.

**Comment by chingon007** [comment]
Did not work as far as I can see. Do I need to do something? 
I saw that there are foreign commits in branch. I did not put them in and did not know how to take them out.

**Comment by fwolter** [comment]
> Did not work as far as I can see. Do I need to do something?
> I saw that there are foreign commits in branch. I did not put them in and did not know how to take them out.

It looked good. What didn't work from your perspective? You pushed the foreign commits again, which causes this PR to fail again.

I'll remove the commits once more. Please don't do anything.

**Comment by chingon007** [comment]
Sorry for that. I am trying to get them out of my local branch. So far no success. I will wait till it is merged and then set up my repo new.

**Review by fwolter — APPROVED** [review]
LGTM

Now, you could add your binding's logo to the openHAB website. See https://deploy-preview-1540--openhab-docs-preview.netlify.app/docs/developer/bindings/#add-your-binding-s-logo-to-the-openhab-website

**Comment by fwolter** [comment]
For the posterity, the actual code review was done in PR #9709.

**Comment by chingon007** [comment]
Finally :-) 
Thanks for the effort.

**Pull request merged**
