### PR TITLE
[mactts] Add LRU cache

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@dalgwen : please have a look

**Comment by dalgwen** [comment]
Sorry for the delay.

I cannot test it, but the use of the TTS cache service is as it was intended to be.
LGTM

**Review by dalgwen — APPROVED** [review]
Sorry for the delay.

I cannot test it, but the use of the TTS cache service is as it was intended to be.
LGTM

**Comment by lolodomo** [comment]
@openhab/add-ons-maintainers : I believe there is no risk with this PR, it can be merged for OH4.

**Review by kaikreuzer — APPROVED** [review]
Alright, let's merge - thanks!

**Pull request merged**
