### PR TITLE
[yioremote] added missing entries in bom and CODEOWNERS

### PR DESCRIPTION
**Pull request by kaikreuzer**
See https://github.com/openhab/openhab-addons/pull/8394#issuecomment-696648523

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Review by Hilbrand — APPROVED** [review]
LGTM

**Comment by kaikreuzer** [comment]
There's really something messed up with the PR build, which I need to look into... 🤔

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by kaikreuzer** [comment]
Hooray, the PR build is finally green :-)

**Pull request merged**
