### PR TITLE
[icalendar] Adding ability to handle events without DTEND

### PR DESCRIPTION
**Pull request by clinique**
According to section 3.6.1 of RFC 5545 :

```For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE value type but no "DTEND" nor "DURATION" property, the event's duration is taken to be one day. For cases where a "VEVENT" calendar component specifies a "DTSTART" property with a DATE-TIME value type but no "DTEND" property, the event ends on the same calendar date and time of day specified by the "DTSTART" property.```

Currently icalendar binding just ignores calendar entries if they have no DTEND defined.

Signed-off-by: clinique <gael@lhopital.org>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@daMihe : is it ok for you?

**Comment by daMihe** [comment]
I have tomorrow time to review.

**Review by daMihe — APPROVED** [review]
Great :)

**Pull request merged**
