### PR TITLE
[bindings s-z] Fix deprecated tag "required"

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by clinique — APPROVED** [review]
LGTM for synopanalyzer and volvooncall

**Review by cweitkamp — APPROVED** [review]
LGTM. Thank you.

Are you planning to remove the deprecated element from [config-description.xsd](https://github.com/openhab/openhab-core/blob/949313744d24b888a90a4e904fca67ae32978b94/bundles/org.openhab.core.config.xml/config-description-1.0.0.xsd#L44) (and code) too?

**Comment by lolodomo** [comment]
> Are you planning to remove the deprecated element from [config-description.xsd](https://github.com/openhab/openhab-core/blob/949313744d24b888a90a4e904fca67ae32978b94/bundles/org.openhab.core.config.xml/config-description-1.0.0.xsd#L44) (and code) too?

Is it time to do it ?
PS: I imagine it could break some unofficial bindings.

**Comment by cweitkamp** [comment]
As long as we do not updated the XSD in out website the changes will not affect any add-on.

To be a little bit more friendly to unofficial add-ons an approach might be to add a warning in the logs when parsing the XML and hitting the deprecated element. wdyt?

**Comment by lolodomo** [comment]
It looks like the code is here:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.config.xml/src/main/java/org/openhab/core/config/xml/ConfigDescriptionParameterConverter.java#L114

As you suggested, we could replace this code and just log something in case a "required" tag is found.

**Comment by lolodomo** [comment]
Thinking about it, if we suppress this code line, the only impact could be that a parameter becomes not required while it was designed as required by the developer. Nothing really critical / blocking.
Maybe it is better to definitively removed it.

**Comment by lolodomo** [comment]
Regarding the XSD, should we increment the version to 1.1 in the file (version XML attribule) and in the XSD file name ?

**Comment by lolodomo** [comment]
Is there a validation of the XML against the XSD when running the binding ?
If not, it would be better to update the XSD on the WEB site to show the change to any developer.

**Comment by cweitkamp** [comment]
Changing the version of the XSD file leads to a necessary migration here and everywhere else. I am not sure if we are capable to handle it.

Imo we should just update the file available on openhab.org. Which btw is not the latest version at all. E.g. the changes of https://github.com/openhab/openhab-core/pull/1410 are not uploaded yet.

**Pull request merged**
