### PR TITLE
[wundergroundupdatereceiver] Bugfix: Check whether the thing is managed before adding newly discovered parameters as channels.

### PR DESCRIPTION
**Pull request by danieldemus**
# Description
Fix for bug #12997

### CODE REVIEW

**Comment by jlaur** [comment]
@fwolter - would it be possible for you to review this in time for 3.3, since you did the review of #10105?

**Comment by fwolter** [comment]
If you just need to check if a Thing exists, `ThingRegistry` seems to be more suitable.

**Comment by danieldemus** [comment]
> If you just need to check if a Thing exists, `ThingRegistry` seems to be more suitable.

I need to know whether it's configured in a file or the UI. This is how the rest api finds out whether the thing is editable. It comes from here: ThingResource.java::725. It might be an idea to add a property such as isEditable to Thing.

**Review by fwolter — APPROVED** [review]
Ok, LGTM

**Pull request merged**
