### PR TITLE
[shelly] Adaption to OH3, Shelly Plug US, minor fixes

### PR DESCRIPTION
**Pull request by markus7017**
Small fixes to adapt the binding to 3.0 and minor fixes
- representationProperty in thing-type.xml
- remove immediate=true in component declaration
- fix some characters in shelly__de.properties
- Fix total consumption for RGBW2+Roller

### CODE REVIEW

**Comment by markus7017** [comment]
Would be good if this PR could be merged before 3.0M1 - the current migrated version does not work (representationPropery was missing in the thing definitions)

**Review by cpmeister — APPROVED** [review]
LGTM

**Comment by cpmeister** [comment]
Looks like you need to run `spotless:apply`

**Comment by markus7017** [comment]
> Looks like you need to run `spotless:apply`

done

**Pull request merged**
