### PR TITLE
Update spotless to 2.0.3

### PR DESCRIPTION
**Pull request by wborn**
Fixes performance issues and memory leaks (see [changelog](https://github.com/diffplug/spotless/blob/master/plugin-maven/CHANGES.md)).

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]

**Comment by kaikreuzer** [comment]
@wborn Is it possible that this change made the Nest binding tests fail? https://ci.openhab.org/job/openHAB-Addons/38/

**Comment by J-N-K** [comment]
I don't think so. The spotless plugin is not used in our build until #8068 or something similar is merged (except it is explicitely called with `mvn spotless:apply` or `-Dspotless.check.skip=false`.

**Comment by kaikreuzer** [comment]
Ok, I'll trigger a third build and see if that is any better than the previous 2...

**Comment by wborn** [comment]
This is about the master and not the 2.5.x branch on which spotless is already enabled.  Those tests now also fail for me on a local build for me regardless of the spotless version. So it might be due to some other change or timing issue. If it keeps failing I can have a closer look later.

**Comment by kaikreuzer** [comment]
@wborn Yeah, it keeps failing with exactly the same problems (now 3 times in a row), so I guess you'll need to have a look...

**Pull request merged**
