### PR TITLE
Use diamond operator and remove redundant type arguments

### PR DESCRIPTION
**Pull request by wborn**
Simplifies the code by using the diamond operator and removing redundant type arguments.

### CODE REVIEW

**Review by david-pace — APPROVED** [review]
LGTM for `boschshc`

**Review by robnielsen — APPROVED** [review]

**Review by ccutrer — APPROVED** [review]
LGTM for bondhome, mqtt, and homekit

**Review by jlaur — APPROVED** [review]
Thank you for simplifying the code. LGTM.

**Review by hmerk — APPROVED** [review]
LGTM

**Review by dougculnane — COMMENTED** [review]
Nice.

**Review by bern77 — COMMENTED** [review]
LGTM for HeliosEasycontrols

**Comment by carlee82** [comment]
No developer, just a user question.
I own the Fronius Smart Meter IP, which is not connected by modbus cable to the inverter. It has an own IP address. Any chance the addon can connect to this new IP Smart Meter. The values it provides are the same as the standard model connected by modbus cable

**Comment by lsiepel** [comment]
> No developer, just a user question. I own the Fronius Smart Meter IP, which is not connected by modbus cable to the inverter. It has an own IP address. Any chance the addon can connect to this new IP Smart Meter. The values it provides are the same as the standard model connected by modbus cable

Please create a separate issue.

**Review by mvalla — COMMENTED** [review]
LGTM for openwebnet

**Pull request merged**
