### PR TITLE
Added a second code owner

### PR DESCRIPTION
**Pull request by andrewfg**
Adding myself as a second code owner for several bindings.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by lolodomo** [comment]
Why not just adding a line for velux binding?

**Comment by jlaur** [comment]
> Why not just adding a line for velux binding?

@andrewfg - or change all four bindings in same PR. @lolodomo commented because it was changed for a different binding in context of a specific binding PR. But just changing code owners doesn't have to be in different PR's.

**Comment by andrewfg** [comment]
> Why not just adding a line for gardena binding?

Sorry for any confusion, but I was trying to avoid and risk of a merge conflict between the various PR's.

> or change all four bindings in same PR

Ok. I will do that.

**Review by lolodomo — APPROVED** [review]
There were already several contributions by @andrewfg for these 3 bindings.

**Pull request merged**
