### PR TITLE
[jrubyscripting] Generate proper i18n file

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lsiepel** [comment]
I'm totally unfamiliair with crowdin, but would there be some kind of workflow tro transfer / rename the file there? so it would not be needed to do all the translations again.

**Comment by lolodomo** [comment]
I am going to rename the existing files'instead of removing them - that is why it is WIP) and then later import them manually in Crowdin.
The work that will be lost is all partial translations that were never come in Git (because partial or not validated in Crowdin).

**Comment by lsiepel** [comment]
Oh very sorry @lolodomo, I checked the WIP label and somehow totally missed it and merged this. I hope i don't mess up your workflow now.

**Comment by jimtng** [comment]
converting it Draft would've prevented accidental merging

**Comment by lolodomo** [comment]
I still have the files locally in my branch. I will update them (file name and keys) and then import them in Crowdin.

**Comment by lolodomo** [comment]
I reinjected the translations in Crowdin for German, Italian and Hungarian.
The binding description in German is still missing to have the translations pushed to Git.
Few translations are missing in Hungarian.
All Italian translations are there and they will be pushed to Git in few minutes.

**Pull request merged**
