### PR TITLE
[network] Fix last-seen channel being set to `UNDEF` at startup

### PR DESCRIPTION
**Pull request by lsiepel**
This fix makes it possible to use `restoreOnStartup` for the last-seen channel. When a device is not on the network and openHAB reboots, the last-seen channel is set to `UNDEF`. This renders the use of `restoreOnStartup` useless. 

If `restoreOnStartup` is not used, the channel remains `NULL` after startup. I think that is a fair trade-off compared to being set to `UNDEF`.

Fixes  https://github.com/openhab/openhab-addons/issues/17404

### CODE REVIEW

**Review by wborn — COMMENTED** [review]
Can you add some comments in the code or a unit test to prevent regressions?

**Review by wborn — APPROVED** [review]
LGTM!

**Comment by wborn** [comment]
Might be a nice fix for 4.3.x too!

**Comment by lsiepel** [comment]
> Might be a nice fix for 4.3.x too!

Yes, will back port this one.

**Pull request merged**
