### PR TITLE
[knx] Remove workaround for DPT 14

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Fixed in Calimero 2.4.

Carryover from smarthomej/addons#104.

Also-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by holgerfriedrich** [comment]
@J-N-K can I start the carryover for the knx binding? Is the commit message / credit ok for you?
(may not be relevant for this PR where we basically remove code, but for the following ones....)

Refs: #14502

**Review by J-N-K — APPROVED** [review]

**Review by lolodomo — APPROVED** [review]
I assume you know what you do :)
LGTM

**Comment by holgerfriedrich** [comment]
@J-N-K seems that the credits in the log message were removed.
When I submitted, it looked like this:

    [knx] Remove workaround for DPT 14

    Fixed in Calimero 2.4.

    Carryover from smarthomej/addons#104.

    Also-by: Jan N. Klug <github@klug.nrw>
    Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

**Comment by J-N-K** [comment]
I guess that is a wrong edit during merging.

**Comment by lolodomo** [comment]
> I guess that is a wrong edit during merging.

I changed nothing when merging, I just take and keep unchanged what GitHub proposed. As there was at least one "Signed-off-by", I did not ask myself more questions.
Look at the other PR, I provided a screenshot.

**Pull request merged**
