### PR TITLE
[webthings][WIP] Initial contribution

### PR DESCRIPTION
**Pull request by svensven94**
This is an initial pull request for the work in progress version of the Mozilla WebThings binding described in [Issue 7009](https://github.com/openhab/openhab-addons/issues/7009). The respective community post can be found [here](https://community.openhab.org/t/mozilla-webthings-binding/92782)

The binding can be used to import and control WebThings from a Mozilla Gateway or any instances of things hosted via the [WebThings framework](https://iot.mozilla.org/framework/).

WebThings can be auto-discovered from a configured gateway and found locally via mDNS (in case of WebThings hosted by a framework library). For manually adding things, the user has to provide a link to the WebThing as well as relevant security information. Afterwards the openHAB thing is updated and generates a channel for each property of the chosen WebThing. Information is exchanged via a websocket which is also able to reconnect in case of a connection loss. Details about the configuration can be found in the [README](https://github.com/svensven94/openhab-addons/blob/webthings_barebones/bundles/org.openhab.binding.webthings/README.md).

### CODE REVIEW

**Comment by svensven94** [comment]
Hello,
I have two questions regarding the pull request:

1. The Check wants me to sign of with my username and my (now) secondary e-mail address. But this is my primary address and I would prefer not to make it openly visible. Therefore, I would like to sign of my commits with another e-mail that is also mine and currently the primary address of this account (svensgit@gmail.com). Is this possible?
2. Apparently, the automatic build fails while compiling parts that do not belong to my binding. Can you give my any advice how to proceed with that? Can I somehow get the current version of these Bindings to my fork?

Thank you for the help!

**Comment by kaikreuzer** [comment]
Hey @svensven94, let me quickly answer your questions:
1. Yes, just just whatever address you like for the sign-off and ignore the automatic DCO check.
2. Simply do a rebase of your branch to the latest head - this should make everything compile again and also resolve the conflicts that this PR is showing.

**Comment by svensven94** [comment]
I ran `git pull --rebase origin 2.5.x`. Afterwards, I compiled everything and committed the changes.

**Comment by kaikreuzer** [comment]
You should be required to do a force push afterwards. You might want to squash your existing 7 commits first, maybe then it is easier to resolve the conflicts (which should not be there, since the filesfrom hue and mqtt are not relevant for your PR)

**Comment by kaikreuzer** [comment]
FTR, this PR has been automatically closed by Github due to our rewrite of the history in that repo - a new PR should be created against the `main` branch, see https://github.com/openhab/openhab-addons/issues/8512 for details.

**Pull request closed without merging**
