### PR TITLE
Removed 'advanced' attribute from channel-group-types

### PR DESCRIPTION
**Pull request by cweitkamp**
- Removed `advanced` attribute from channel-group-types

See https://github.com/openhab/openhab-core/pull/1410

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Should the channels receive the „advanced“ attribute if the group they belong to had it?

**Comment by cweitkamp** [comment]
I tend to say: Yes.

**Comment by kaikreuzer** [comment]
> I tend to say: Yes.

Is this already the case or would you need to update this PR for it?

**Comment by marcelrv** [comment]
LGTM
note. miio already had it on the lower levels as well. From miio point of view no need to update pr

**Comment by cweitkamp** [comment]
> Is this already the case or would you need to update this PR for it?

It already is the case for miio, nest, phc and gardena.

shelly uses one system default channel type which is not marked as advanced. If we change it we have to introduce new channel types for it.

systeminfo partly reuses the same channel types as for other "not advanced" channel groups. If we change it we have to introduce new channel types for it.

**Pull request merged**
