### PR TITLE
[amazonechocontrol] Partial revert of PR 7919

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #8027

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
No, I can't test.
I proposed several PRs related to the issue just to help, even on bindings I am not using at all.

**Comment by kaikreuzer** [comment]
@J-N-K What concerns do you have wrt this change that you flag it as "changes requested"?
It seems to be a logical fix to me and if we'd get an lgtm from @mgeramb, I'd be ok to merge it.

**Comment by J-N-K** [comment]
My concern is: this code was broken before and crashed the whole openHAB instance. It was fixed and confirmed working. Now a change is introduced in that part of the code without proper testing just to make it look better.

**Comment by kaikreuzer** [comment]
> just to make it look better.

Well, I think this is not the intention here.
This PR originates from @sprehn's input from https://github.com/openhab/openhab-addons/issues/8027#issuecomment-653767440, which is imho a valid concern about the current code, which this PR addresses.

**Comment by lolodomo** [comment]
What are we doing here ? @J-N-K : do you want to test this change yourself before its merge ?

**Comment by J-N-K** [comment]
No, I don't want to test it and I'll not merge it, But if someone wants to do it, I'm ok with it.

**Comment by kaikreuzer** [comment]
I am fine to merge it, but I would wait with it until the 2.5.7 release is done. We will then have a few weeks where people can test and complain, if there is any problem, before the PR goes into 2.5.8.

**Pull request merged**
