### PR TITLE
[robonect] Added status 18, Doordelay

### PR DESCRIPTION
**Pull request by 27421**
This modification allows the binding to recognize when the door needs to be opened.

### CODE REVIEW

**Comment by 27421** [comment]
Thanks!
 I still have some (maybe major) problems with github, as I'm experienced in programming things but i have no experience using that.

**Comment by cpmeister** [comment]
Can you please add a sign-off to your commit? I need the DCO check to pass. Thanks!

**Comment by 27421** [comment]
I'm sadly not able to signoff anything here, as im getting my key up here, but are not able to install anything locally like git bash.

**Comment by 27421** [comment]
@cpmeister Isn't this already signed off? I managed to get an linux vm. Appearently the git bash requires me to sign off everything but my commit here sadly. What DCO recommends also doesn't work... Any ideas?

**Comment by cpmeister** [comment]
Just add a signoff line to one of your comments here and I can override the DCO check.

**Comment by cpmeister** [comment]
Just post a comment here with the format 
`Signed-off-by: firstname lastname <XXX@gmail.com>` 
and I will be able to take care of the rest

**Comment by 27421** [comment]
Signed-off-by: Tom Kandler <tomkandler10@gmail.com>
Thanks a lot, that'll make my life a lot easier!

**Comment by 27421** [comment]
In the future, if i start a pull request, how should i do it? 
Should i just post my signoff line here, or do it via git bash? What do you recommend? 
Thanks a lot, Tom!

**Comment by cpmeister** [comment]
> In the future, if i start a pull request, how should i do it?
Should i just post my signoff line here, or do it via git bash? What do you recommend?

Please include your sign-off as part of your commit message. That can be done through git-bash or any of other git tool of your preference.

**Comment by cpmeister** [comment]
Manually check sign-off

**Comment by cpmeister** [comment]
@27421 Thank you for your contribution!

**Comment by 27421** [comment]
Thank you! I also know what I had done wrong now... I tried to sign off this branch like it was mine... That resulted in a 403 error.
Also in the near future i can try again, as this modification is just one part of the whole thing... Sadly in the german forum there is no complete list for api channels so I have to ask or figure it out myself.

**Pull request merged**
