### PR TITLE
[ephemeris] Clean up i18n entries

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@jlaur @lsiepel  : can one of you merge this PR please, I will then be able to validate the French translations in Crowdin.

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by lsiepel** [comment]
> @jlaur @lsiepel : can one of you merge this PR please, I will then be able to validate the French translations in Crowdin.

some duplicates or what is happening?

**Comment by lolodomo** [comment]
> some duplicates or what is happening?

Just a forget to remove entries after different renamings.

**Pull request merged**
