### PR TITLE
typo: successful

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Fix typo, inspired by openhab/openhab-core#3236

Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Does it replace #13997 ?

**Comment by holgerfriedrich** [comment]
> Does it replace #13997 ?
Hm, how did I manage top overlook that one 😉

**Comment by lolodomo** [comment]
At the same time, your PR is signed off, so I would prefer to merge yours ;)

**Comment by holgerfriedrich** [comment]
@lolodomo fine for me, just reopened it....

**Comment by lolodomo** [comment]
Unfortunately, the build failed!

**Comment by jlaur** [comment]
@holgerfriedrich, @lolodomo - the other PR has more fixes, so I think we can accept without DCO for just these typo corrections?

**Comment by lolodomo** [comment]
> @holgerfriedrich, @lolodomo - the other PR has more fixes, so I think we can accept without DCO for just these typo corrections?

OK

**Pull request closed without merging**
