### PR TITLE
[tr064] fix parameter patterns

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Review by syntacrsc — COMMENTED** [review]
I'm not a RegEx expert but:
does the added regEx pattern allow IP-addresses containing 0?
e.g. 10.0.0.10 ??
shouldn't it be something like 
pattern="([0-9]\d{0,2}\.){3}[0-9]\d{0,2}(\s*#.*)*"/>
instead of
pattern="([1-9]\d{0,2}\.){3}[1-9]\d{0,2}(\s*#.*)*"/>

??

**Comment by J-N-K** [comment]
No. The first digit must be non zero [1-9], followed by zero, one or two digits \d, which is a shortcut for [0-9].

**Comment by J-N-K** [comment]
You are right, it's wrong. But something like 010 should not be allowed. So maybe it has to be extended to something like `([1-9]\d{0-2}|0)`.

**Pull request merged**
