### PR TITLE
[homematic] Update README.md

### PR DESCRIPTION
**Pull request by MeisterPiffer**
not sure about the php though, this is from the example which is DSL as well.

### CODE REVIEW

**Comment by jlaur** [comment]
Correction to #13101.

**Comment by jlaur** [comment]
@MeisterPiffer - not sure if it will be rendered differently, but can we have linefeeds before and after each code fence like in previously posted example?

**Comment by MeisterPiffer** [comment]
> @MeisterPiffer - not sure if it will be rendered differently, but can we have linefeeds before and after each code fence like in previously posted example?

I now tried to copy the formatting with all extra spaces like from the example.

**Comment by jlaur** [comment]
> > @MeisterPiffer - not sure if it will be rendered differently, but can we have linefeeds before and after each code fence like in previously posted example?
> 
> I now tried to copy the formatting with all extra spaces like from the example.

Sorry, but only newlines requested, no additional spaces.

**Comment by MeisterPiffer** [comment]
> > > @MeisterPiffer - not sure if it will be rendered differently, but can we have linefeeds before and after each code fence like in previously posted example?
> > 
> > 
> > I now tried to copy the formatting with all extra spaces like from the example.
> 
> Sorry, but only newlines requested, no additional spaces. _Edit:_ It might help to look at the example in GitHub as raw.

ok, thanks for your patience.

**Comment by jlaur** [comment]
@MeisterPiffer - now it looks good:
https://next.openhab.org/addons/bindings/homematic/#troubleshooting

:thumbsup:

**Pull request merged**
