### PR TITLE
[denonmarantz] Run the Telnet socket in a dedicated thread

### LINKED ISSUE #9494: [DenonMarantz] Telnet Thread Issue
Opening as per @kaikreuzer from https://github.com/openhab/openhab-core/issues/1998

It permanently blocks one thread from the thread pool as it uses it to listen to a telnet connection. It should use its own thread instead of the shared thread pool for that.

```
"OH-thingHandler-2" #226 daemon prio=5 os_prio=0 cpu=76.63ms elapsed=3419.19s tid=0x00007fbd1402c000 nid=0x40cdb runnable  [0x00007fbd00825000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.9.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.9.1/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.9.1/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.9.1/SocketInputStream.java:140)
	at sun.nio.cs.StreamDecoder.readBytes(java.base@11.0.9.1/StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(java.base@11.0.9.1/StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(java.base@11.0.9.1/StreamDecoder.java:178)
	- locked <0x00000000c45000f0> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(java.base@11.0.9.1/InputStreamReader.java:185)
	at java.io.BufferedReader.fill(java.base@11.0.9.1/BufferedReader.java:161)
	at java.io.BufferedReader.readLine(java.base@11.0.9.1/BufferedReader.java:326)
	- locked <0x00000000c45000f0> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(java.base@11.0.9.1/BufferedReader.java:392)
	at org.openhab.binding.denonmarantz.internal.connector.telnet.DenonMarantzTelnetClient.run(DenonMarantzTelnetClient.java:71)
```

### PR DESCRIPTION
**Pull request by jwveldhuis**
Fixes #9494

### CODE REVIEW

**Comment by J-N-K** [comment]
I would suggest a differet approach: Instead of implementing `Runnable` in `DenonMarantzTelnetClient` you could extend `Thread`. Then in l. 64 `while (i!sInterrupted())` and call `disconnect` after exiting the `while`-loop.  In the connector you can call `telnetClient.start()` to start it and `telnetClient.interrupt()` to shut it down.

**Review by J-N-K — CHANGES_REQUESTED** [review]
I would suggest a differet approach: Instead of implementing `Runnable` in `DenonMarantzTelnetClient` you could extend `Thread`. Then in l. 64 `while (i!sInterrupted())` and call `disconnect` after exiting the `while`-loop.  In the connector you can call `telnetClient.start()` to start it and `telnetClient.interrupt()` to shut it down.

**Comment by J-N-K** [comment]
Also please set a name to the thread

**Comment by Hilbrand** [comment]
Thank you for fixing this. For thread naming see: #8216

**Comment by jwveldhuis** [comment]
@J-N-K it's ready for a new review.
BTW: the Jenkins setup, why is it compiling every binding and not just the ones touched in the particular PR?

**Review by J-N-K — APPROVED** [review]

**Pull request merged**
