### PR TITLE
Upgrade to Karaf 4.4.3

### PR DESCRIPTION
**Pull request by wborn**
* Rework Servlets to use Http Whiteboard annotations in favor of proprietary `org.openhab.core.io.http.servlet` classes
* Resolve itest runbundles
* Fix dependency issues
* Catch proper exception when starting hueemulation UpnpServer

---

Depends on openhab/openhab-core#3252

To do:

* [x] Rebase and fix merge conflicts
* [x] Upgrade to the latest greatest Karaf 4.4 version
* [x] Check, fix add-on servlets that no longer work

### CODE REVIEW

**Comment by wborn** [comment]
Are going to help me fixing the addons @J-N-K ? 🙂 I was planning to pick this up when Karaf 4.4.3 is released which is "Karaf soon".

**Comment by J-N-K** [comment]
Yes, I have a running OH4 with Karaf 4.4, but there are still some issues. The biggest problem is that I can‘t get some itest I’m core to resolve because it seems that blacklisting tomcat is not working. I‘ll push my changes as separate commit, maybe you can have a look.

**Comment by wborn** [comment]
I can have a look at that! I'll make a backup of my branches before updating them in case something gets lost.

**Comment by J-N-K** [comment]
This one looks pretty good now, apart from the itests that don't resolve. Maybe you can have a look at that, @wborn.

**Comment by jlaur** [comment]
Depends on openhab/openhab-core#3252, I believe.

**Review by hmerk — APPROVED** [review]
LGTM for Wemo

**Comment by wborn** [comment]
@openhab/add-ons-maintainers can you review this PR?
It's required for successful builds now that https://github.com/openhab/openhab-core/pull/3252 got merged.

**Pull request merged**
