### PR TITLE
[dmx] Improve exception handling in refresh job

### PR DESCRIPTION
**Pull request by J-N-K**
If an exception is thrown while sending (or connecting) the refreshJob died. This exception is now handled gracefully.

### CODE REVIEW

**Review by lsiepel — COMMENTED** [review]
Thanks, LGTM

**Comment by J-N-K** [comment]
@lsiepel Please set the milestone when merging :-)

**Comment by jlaur** [comment]
@J-N-K - should we cherry-pick this into 4.1.x?

**Comment by J-N-K** [comment]
Not necessarily. It's a rare corner-case that I encountered on my production system today while rebooting some other devices.

**Comment by jlaur** [comment]
> Not necessarily. It's a rare corner-case that I encountered on my production system today while rebooting some other devices. But it doesn't hurt.

All right, low risk low gain. I have cherry-picked it since I was already cherry-picking another fix as well.

**Pull request merged**
