### PR TITLE
[openuv] Fix time channels not being updated

### PR DESCRIPTION
**Pull request by clinique**
Time channels where always UNDEF.

### CODE REVIEW

**Comment by jlaur** [comment]
@clinique - from the five word description, lack of linked issue and refactoring blended with the actual fix, I'm a bit lost and need you need to help me out of bit: Is the bug related to **channel type id** being checked instead of **channel id**? If I didn't spot this correctly, please add a few words. :-)

**Comment by clinique** [comment]
Sorry. I discovered the issue by myself so took over to investigate directly. The three time related channels where strangely not populated. I think I introduced the error some PR ago when I changed the channel type of these. As the binding used to update the channels based on their type and not their names, it broke.

**Comment by jlaur** [comment]
> Sorry. I discovered the issue by myself so took over to investigate directly. The three time related channels where strangely not populated. I think I introduced the error some PR ago when I changed the channel type of these. As the binding used to update the channels based on their type and not their names, it broke.

So in other words: yes to my question. :-) But just to be sure, had to look up the definitions:

```
		<channels>
			<channel id="UVIndex" typeId="UVIndex"/>
			<channel id="Alert" typeId="Alert"/>
			<channel id="UVColor" typeId="UVColor"/>
			<channel id="UVMax" typeId="UVMax"/>
			<channel id="UVMaxTime" typeId="timestamp">
				<label>UV Max Time</label>
				<description>Max UV Index time (solar noon)</description>
			</channel>
			<channel id="UVMaxEvent" typeId="UVMaxEvent"/>
			<channel id="Ozone" typeId="Ozone"/>
			<channel id="OzoneTime" typeId="timestamp">
				<label>Ozone Observation Time</label>
				<description>Latest OMI ozone update timestamp.</description>
			</channel>
			<channel id="UVTime" typeId="timestamp">
				<label>Report Timestamp</label>
				<description>UV Report timestamp.</description>
			</channel>
			<channel id="SafeExposure" typeId="SafeExposure"/>
			<channel id="elevation" typeId="elevation"/>
		</channels>
```

I can see that **UVMaxTime**, **OzoneTime** and **UVTime** have channel type id's different from their channel id's. So with this knowledge, the fix looks fine.

**Review by jlaur — APPROVED** [review]
LGTM

**Pull request merged**
