### PR TITLE
[atlona] Add support for AT-PRO3HD44M

### PR DESCRIPTION
**Pull request by mlobstein**
follow up to #9385
Add support for the older model AT-PRO3HD44M 4x4 matrix that uses the same protocol as the AT-PRO3HD66M matrix. Also fix binding name to follow standard naming conventions.

### CODE REVIEW

**Comment by lsiepel** [comment]
Would it be needed to re-create the thing because the channel type changed ? to make use of the system provided ones? If so this is a breaking  change.

**Comment by mlobstein** [comment]
> Would it be needed to re-create the thing because the channel type changed ? to make use of the system provided ones? If so this is a breaking change.
That is a good point. I don't think it warrants the trouble so I reverted those changes.

**Comment by lsiepel** [comment]
As 4.0.0 is a release that is gonna break more stuff, this is the right moment to make such changes. Using the system channel type is an improvement.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
