### PR TITLE
[systeminfo] Use AbstractStorageBasedTypeProvider

### PR DESCRIPTION
**Pull request by J-N-K**
This is one of two reference implementations for the use of dynamic type providers.

### CODE REVIEW

**Review by ccutrer — APPROVED** [review]

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@svilenvul @mherwege : can you please have a look to this PR and the related PR in core framework to tell us if the change looks good to you ?

**Comment by mherwege** [comment]
@lolodomo LGTM, tested on a recent snapshot.

**Comment by lolodomo** [comment]
> @lolodomo LGTM, tested on a recent snapshot.

Excellent

**Pull request merged**
