### PR TITLE
[sbus] Initial Contribution

### PR DESCRIPTION
**Pull request by cipianpascu**
This is the first attempt to implement the S-Bus G4 transport protocol.
The code is derived from the Modbus transport protocol and has the following two additions:
1. TCP protocol is replaced with UDP protocol
2. All the protocol queries have a subnetId byte in addition to the deviceId and functionId.
Please look at what I did, and let me know about the additional changes/fixes required for this new transport protocol/binding.

### CODE REVIEW

**Comment by lsiepel** [comment]
Maybe this should be a subbinding of modbus or an addition to the current binding? Don't know it that makes sense, i'm no modbus expert.
Anyway, it needs some work regarding documentaiton, relation with modbus and the builds fail. I would also suggest to add a testable jar file. Would be nice to have a community or marketplace thread with users that tried this binding.

**Comment by lsiepel** [comment]
Gentle ping @cipianpascu

**Comment by cipianpascu** [comment]
hey @lsiepel,
After some more development, this binding can not be merged into the Modbus protocol even if derived from it. The reason is simple: Sbus components have only one type of resource (registers) that can be manipulated with many more functions than Modbus offers.
I have already engaged with the Sbus community on the official channel, and I hope to have something worth merging with the main branch in the following weeks/months, considering your suggestions. Regarding this, I need your guidance for proper integration with the Openhab platform.
Thank you,
Ciprian

**Comment by lsiepel** [comment]
Unfortunately i'm totally not familiair with modbus and sbus so i can't give you much guidance. You could ask for some help in the community forums, there is a special developers section. You could aslo try to discuss it in a github issue, but the community forums is probably a better fit to start with.

This PR is invalid in multiple ways and would need some work:
- it looks like some copy/paste from the modbus binding, the modbus namespace is used on multiple files
- files are named after madbus instead of sbus
- binding id is modbus
- The current PR has some files from other bindings in it, they should be removed.

**Comment by lsiepel** [comment]
Hope you manage to proceed with developing this binding. Unfortunately in it's current state (see previous comment) it needs some work before it can be reviewed and ultimately merged. Obviously you can continue your development efforts on your own branch. Once the binding is developed enough, this PR (or a new one) can be re-openen.

**Pull request closed without merging**
