### PR TITLE
[sonos] Play notification while playing virtual line-in

### LINKED ISSUE #10569: [sonos] notification sound not played (anymore) when spotify playlist is running on sonos box
The sonos speaker is no longer playing notification sounds when a spotify session is running on the speaker. 
It is spotify session related, so it doesn't even meen the spotify list needs to play as long as a spotify session is stil active the speaker doesn't play notification sounds anymore, untill I end the spotify session.

running openhab version 2.5.12
in the past this was working fine. Not sure if this issues started when moving to 2.5.12 (from 2.5.10) or afterwards)

**DEBUG info when having a spotify session on the speaker:**
2021-04-24 09:34:35.451 [DEBUG] [s.internal.handler.ZonePlayerHandler] - playNotificationSoundURI: currentURI x-sonos-vli:RINCON_48A6B882997A01400:2,spotify:16ced13eac14dae2577f0d5f1bbc8192 metadata <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="spotify" parentID="0" restricted="false"><dc:title>Spotify</dc:title><upnp:class>object.item.audioItem.linein</upnp:class><res protocolInfo="x-sonos-vli:*:audio:*">x-sonos-vli:RINCON_48A6B882997A01400:2,spotify:16ced13eac14dae2577f0d5f1bbc8192</res><vli cookie="1" group=""></vli></item></DIDL-Lite>

**DEBUG info when NO spotify session is on the speaker:**
2021-04-24 09:34:59.574 [DEBUG] [s.internal.handler.ZonePlayerHandler] - playNotificationSoundURI: currentURI x-rincon-queue:RINCON_48A6B882997A01400#0 metadata 
2021-04-24 09:34:59.619 [DEBUG] [s.internal.handler.ZonePlayerHandler] - handleSharedQueue: currentQueueURI x-rincon-queue:RINCON_48A6B882997A01400#0 trackPosition 0:00:00 currentTrackNumber 1
2021-04-24 09:34:59.684 [DEBUG] [s.internal.handler.ZonePlayerHandler] - setCurrentURI URI x-rincon-queue:RINCON_48A6B882997A01400#0 URIMetaData

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #10569

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Here is a jar for testing:
[sonos.zip](https://github.com/openhab/openhab-addons/files/6411484/sonos.zip)

**Comment by lolodomo** [comment]
Here is a new jar for testing, compatible with 3.1 M4:
[sonos.zip](https://github.com/openhab/openhab-addons/files/6417255/sonos.zip)

**Comment by lolodomo** [comment]
@cweitkamp @wborn : That's strange, when I look at the build console output, the build succeeded but the last line os "Finished: UNSTABLE". Is it the reason why the build is finially mentioned as KO in the PR and what is generating this "UNSTABLE" ?

**Comment by wborn** [comment]
All add-on builds currently suffer from this. I already tried restarting Jenkins but it is very subborn about this false positive. :slightly_frowning_face:

**Comment by kaikreuzer** [comment]
The main build is unstable because of a failing test: https://ci.openhab.org/job/openHAB-Addons/lastCompletedBuild/org.openhab.addons.bundles$org.openhab.io.hueemulation/testReport/org.openhab.io.hueemulation.internal.upnp/UpnpTests/descriptionWithAddress/

Not sure if this could be in any way related?

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks for the fix.

**Pull request merged**
