### PR TITLE
[jsscripting] Update GraalJS to 21.3 to allow method selection via JavaScript

### PR DESCRIPTION
**Pull request by LukasA83**
To allow method selection via javascript in case of graaljs unable to choose right method by itself, Graaljs needed to be updated to >21, e.g. for events.postUpdate with item and state when state is a DecimalType.

Signed-off-by: Lukas Agethen lukas83@gmx.de

### CODE REVIEW

**Comment by LukasA83** [comment]
Anything else needed for review from my side?

**Comment by digitaldan** [comment]
I just tested this on my system and everything works as expected, so @LukasA83 the upgrade allows Graaljs to pick `foo(String bar)` or `foo(int bar)` correctly when calling from JS ?

**Comment by LukasA83** [comment]
Well it allows you to define in case there is a conflict, see
https://github.com/oracle/graaljs/issues/37

**Comment by digitaldan** [comment]
Maybe @jpg0 can give his review, but this LGTM

**Review by jpg0 — APPROVED** [review]
Looks good to me

**Comment by LukasA83** [comment]
What else is required to get this PR merged?

**Review by wborn — APPROVED** [review]
Thanks! :+1: 
We only need to click a few buttons to get it merged. :wink:

**Pull request merged**
