### PR TITLE
[jsscripting] Add info about npm requiring path

### PR DESCRIPTION
**Pull request by SkyLined**
The command to install an npm package that was suggested in the documentation would not work, as it was missing the required path. I've added information to explain this is required.

### CODE REVIEW

**Comment by lsiepel** [comment]
As step 4 is already asking to do the command ‘ from your library's folder’, adding the path at step 5 is not needed. Or what am I missing?

**Comment by florian-h05** [comment]
I think the point here is, that the tarball is in the library folder and not inside automation/js.
But instead of adding this to the command, I would rather add „copy your tarball to automation/js“ or „make sure to provide the path to your tarball to install it“. Though I would expect that this is self explaining …

**Comment by SkyLined** [comment]
Having a copy of the tarball in `automation/js` makes no sense to me; you can just leave it where it is and provide the path.

Assuming something is self-explanatory is the most common flaw in documentation, please do not leave out information unless it really clutters the page (in which case, link to another page that provide it). In this case, it doesn't clutter but is a useful reminder to provide the path.

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by florian-h05** [comment]
@SkyLined Can you please open a PR to openhab-js to apply the change there as well?

**Pull request merged**
