### PR TITLE
[hue] Reorganize API classes

### LINKED ISSUE #15731: [hue] Reorganize API/DTO classes
We could create a subdirectory, _internal/api_ and move the _dto_ directory here as well as _serialization_.

Additionally, it would be nice to be able to collapse CLIP 1 DTO classes.

So the proposed structure would be something like this:
- internal/api
  - dto
    - clip1
    - clip2
  - serialization

_Originally posted by @jlaur in https://github.com/openhab/openhab-addons/pull/15552#discussion_r1330528369_

### PR DESCRIPTION
**Pull request by jlaur**
Resolves #15731

### CODE REVIEW

**Comment by andrewfg** [comment]
@jlaur as there are 117 files involved, could you please simply explain what you did here? I am hoping that you just moved files from one Java module to another? And I am hoping that you did NOT change any of the functional code (except the module names, and the imports names).

**Comment by jlaur** [comment]
> as there are 117 files involved, could you please simply explain what you did here?

Only what is described in the referenced issue, and nothing else. So yes, it's just files moved around.

**Review by andrewfg — APPROVED** [review]
@jlaur LGTM .. it much improves distinction between the API v1 and API v2 code bases. Thank you.

**Comment by jlaur** [comment]
@lolodomo - to reduce conflicts in further work on this binding, could you have a look at this PR?

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
@lolodomo - thanks!

**Pull request merged**
