### PR TITLE
[emotiva] Remove discovery-methods because of missing listen port support in scanBroadcast

### PR DESCRIPTION
**Pull request by espenaf**
This PR removes discovery-methods declartion in the emotiva binding. The declariton was missing fields, and upon further invesrtigation, the scanBroadcast in IpAddonFinder.java does not support separate destination and listen ports, meaning a discovery via the IpAddonFinder will not work.

### CODE REVIEW

**Comment by jlaur** [comment]
@espenaf - see https://github.com/openhab/openhab-addons/pull/14263#discussion_r1602258111

**Comment by mlobstein** [comment]
You can test by copying the entire `<addon>...</addon>` block into $openhab_dir/runtime/etc/addons.xml

Then use the following debug command to see the IP scans:
`log:set TRACE org.openhab.core.config.discovery.addon.ip.IpAddonFinder`

**Comment by espenaf** [comment]
Thanks for the good suggestions for debugging this. It still was a bit of pain, but after firing up a fresh openhab 4.2.0.M3 I was able to test it.

It actually turns out that the ipBroadcast does not support the method used by Emotiva for discovery. Emotiva devices needs to be discovered via ip broadcast, not multicast, but it also requires different dest (7000) and listen port (7001). The current scanBroadcast in IpAddonFinder.java does not support a listenPort, on the multicast version does. The EmotivaDiscoveryService does handle this, but the suggested discovery seem to be lacking this for now

This PR has now been updated to remove the discovery-methods declaration completly. Hopefully the support for this will come, and it can be readded.

**Review by jlaur — APPROVED** [review]
Thanks! Let's merge this to get rid of the useless discovery method. I might have a look at the finder to see if listen port can be easily added, but won't promise/commit to that for the time being. I'll let you know if/when it happens. 🙂

**Pull request merged**
