### PR TITLE
Avoid star imports and add missing braces

### PR DESCRIPTION
**Pull request by wborn**
Fixes the following SAT findings:

* AvoidStarImportCheck (125)
* NeedBracesCheck (39)

### CODE REVIEW

**Review by pacive — APPROVED** [review]
Good for Smhi

**Review by andrewfg — APPROVED** [review]
[hdpowerview] LGTM
[siemensrds] LGTM

**Review by bjoernbrings — APPROVED** [review]
[valloxmv] LGTM

**Comment by BobRak** [comment]
Smartthings changes look good

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks for cleaning up.

**Pull request merged**
