### PR TITLE
Exclude 3rdparty directories from license header generation

### PR DESCRIPTION
**Pull request by jlaur**
Related to #14154, see https://github.com/openhab/openhab-addons/pull/14154#issuecomment-1371319055

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Lgtm, although I think there should be no 3rd party code using our namespace (this should not be allowed), so this is maybe something to look at separately (I see that's the case for lametrictime).

**Comment by jlaur** [comment]
@kaikreuzer - I can have a look at this also. I'm wondering though which namespace to use, since at some point this must have been changed to `org.openhab`. But even when fixed for the concrete case, there would still be a risk of messing with 3rd party license headers in case something new would be introduced by mistake again. So probably we should still consider exclusion a permanent solution for additional safety.

**Comment by kaikreuzer** [comment]
I faintly remember that I was involved in adding this code to the lametric binding, so I can dig for the reasons why it is like it is.

> we should still consider exclusion a permanent solution for additional safety.

Definitely yes! This PR is not considered a temporary solution.

**Comment by jlaur** [comment]
@kaikreuzer - now looking into the last missing pieces of the puzzle, we also have this issue of two files with openHAB header living inside the 3rdparty directory. They were included in the search & replace, but won't be handled automatically by `mvn license:format` next time, so we need to decide what to do. One of them is lametrictime again. I didn't check yet, but if there are no other license headers, I guess we could move the files into the org.openhab namespace and have them handled normally.

```
diff --git a/bundles/org.openhab.binding.lametrictime/src/3rdparty/java/org/openhab/binding/lametrictime/api/common/impl/typeadapters/imported/CustomizedTypeAdapterFactory.java b/bundles/org.openhab.binding.lametrictime/src/3rdparty/java/org/openhab/binding/lametrictime/api/common/impl/typeadapters/imported/CustomizedTypeAdapterFactory.java
index 03091e1ab8..3508d2ad52 100644
--- a/bundles/org.openhab.binding.lametrictime/src/3rdparty/java/org/openhab/binding/lametrictime/api/common/impl/typeadapters/imported/CustomizedTypeAdapterFactory.java
+++ b/bundles/org.openhab.binding.lametrictime/src/3rdparty/java/org/openhab/binding/lametrictime/api/common/impl/typeadapters/imported/CustomizedTypeAdapterFactory.java
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2010-2022 Contributors to the openHAB project
+ * Copyright (c) 2010-2023 Contributors to the openHAB project

diff --git a/bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/UnrecoverableSmslibException.java b/bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/UnrecoverableSmslibException.java
index 5ae22b8a62..e44b41162c 100644
--- a/bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/UnrecoverableSmslibException.java
+++ b/bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/UnrecoverableSmslibException.java
@@ -1,5 +1,5 @@
 /**
- * Copyright (c) 2010-2022 Contributors to the openHAB project
+ * Copyright (c) 2010-2023 Contributors to the openHAB project
```

Oh, and last thing: Now that we are already discussing license headers, can you have a look at https://github.com/openhab/openhab-addons/pull/14134#issuecomment-1368595983 and possible comment? 🙂

**Comment by jlaur** [comment]
> I faintly remember that I was involved in adding this code to the lametric binding, so I can dig for the reasons why it is like it is.

Did you find/remember the reason? 🙂

**Comment by kaikreuzer** [comment]
Haha, I said I "can" check, I didn't say I would do. 😉 
But thanks for the ping. I just had a look and found in the NOTICE file the reference to the original lib at https://github.com/syphr42/liblametrictime-java.
Afair, @syphr42 planned to maintain this library independently from openHAB, so that it can be used by other projects as well.
Since the maintenance of liblametrictime-java seems to have stopped, I actually wonder if @syphr42 would be willing to contribute this code under EPLv2, so that we could move it from the 3rdparty folder to the official source code of the binding. @syphr42 Wdyt, would that be ok for you?

**Comment by mhilbush** [comment]
I also tried to contact @syphr42 a while back regarding the sleepiq binding, which also happens to have a 3rd party library that I modified pretty extensively in my PR [here](https://github.com/openhab/openhab-addons/pull/14180). But I got no response.

If it would be ok with @syphr42, I would be happy to move the sleepiq 3rdparty lib into the official openHAB source code for the sleepiq binding and make whatever mods are required to make it compliant. But in the absence of a response from @syphr42, what do we do?

**Comment by syphr42** [comment]
@kaikreuzer @mhilbush I would be happy to contribute the code under EPLv2. I had a lot of ambitions for those bindings early on, but then I stepped away from openHAB for a bit and when I tried to come back wasn't able to get the development environment working for the latest incarnation of openHAB. Eventually it fell off my radar again. Happy to help get this in shape to make it easier to maintain and sorry for not responding sooner! 

Let me know what you need from me.

**Comment by mhilbush** [comment]
@syphr42 Thanks!!

@kaikreuzer @jlaur I would be happy to rework the sleepiq binding to roll the sleepiq api 3rd party library into the official source code of the binding, and make the changes necessary to make the code compliant (I don't think there's much to do). If that's ok with you, I will mark my sleepiq PR as WIP until I complete that. Ok?

**Comment by kaikreuzer** [comment]
@syphr42 Awesome, thank you so much!
In case you ever want to get back into openHAB development, feel free to reach out - I'll be happy to support you in getting a dev env up and running!

@jlaur I'll prepare a PR to adapt the lametrictime binding, so that we no longer need the 3rdparty source folder in there.

**Comment by mhilbush** [comment]
FYI I've updated my PR for sleepiq to migrate all the 3rd party code into the official binding code.

**Comment by kaikreuzer** [comment]
Done for LametricTime: https://github.com/openhab/openhab-addons/pull/14425

**Pull request merged**
