### PR TITLE
Update POM and documentation for renamed repository (master)

### PR DESCRIPTION
**Pull request by wborn**
Signed-off-by: Wouter Born <github@maindrain.net>

### CODE REVIEW

**Comment by wborn** [comment]
The Jenkins PR-openHAB2-Addons job currently will fail for every PR to the master branch because it is configured to always merge PRs to the 2.5.x branch and then build the code @kaikreuzer. Besides merging to different branches it will soon also need to build using Java 8 or 11 depending on the branch https://github.com/openhab/openhab-core/issues/1287#issuecomment-570780115.

**Comment by kaikreuzer** [comment]
>  job currently will fail for every PR to the master branch because it is configured to always merge PRs to the 2.5.x branch

I know, before it failed for all PRs to 2.5.x (which were 98%), so I changed that :-)

Any good suggestion how to solve it? Probably best to have to different build plans with different configurations? Would need to find out if it is possible for Jenkins to detect against which branch the PR is created...

**Comment by wborn** [comment]
I see that the webhook passes a `GITHUB_PR_TARGET_BRANCH` parameter:

https://ci.openhab.org/job/PR-openHAB2-Addons/16653/parameters/

Perhaps it can be used as `$GITHUB_PR_TARGET_BRANCH` instead of the hardcoded `2.5.x` ?

If it's also available in shell scripts, then it can be used to setup the environment to use Java 8 or Java 11 depending on the branch.

**Comment by kaikreuzer** [comment]
> Perhaps it can be used as $GITHUB_PR_TARGET_BRANCH instead of the hardcoded 2.5.x ?

Sounds good, I have changed it accordingly.

Wrt JDKs, I will have to have a closer look at how they are provisioned once I have a few more minutes...

**Pull request merged**
