### PR TITLE
[Netatmo] Fix remaining warnings at Room startup

### PR DESCRIPTION
**Pull request by clinique**
Delayed initialization of the HomeEnergyCapability

### CODE REVIEW

**Comment by jlaur** [comment]
Regression of #14595?

**Comment by clinique** [comment]
No, RoomCapability was not involved in this PR - and these warning may be masked depending upon thing initialization speed/order I guess. I never faced them in my dev environment - they appeared when I switched production on OH4.

**Comment by jlaur** [comment]
@clinique - so probably still a regression in 4.0, or do you think the problem also existed in 3.4?

**Comment by clinique** [comment]
I think it exists since a while but has gone unnoticed. Maybe the new thing initialization mechanism of OH4 made him visible.

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
