### PR TITLE
[bluetooth.bluegiga] Fix scan interval descriptions

### PR DESCRIPTION
**Pull request by pfink**
Signed-off-by: Patrick Fink <mail@pfink.de>

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by paulianttila** [comment]
Intervals are unit of 625us, so 6400 x 625us = 4000ms

**Comment by pfink** [comment]
@paulianttila: I'm very sorry! Did setup #9026 for fixing, could you please review? Thanks!

**Comment by paulianttila** [comment]
No problem, description wasn't so unambiguous

**Pull request merged**
