### PR TITLE
[Nibeuplink] enhanced custom channel feature

### PR DESCRIPTION
**Pull request by alexf2015**
2 changes of custom channel feature:

- changed binding to implement "extensible" and thus support an arbitrary number of custom channels
- added possibility to scale custom channels as the API only provides integer values which need to be scaled.

Those enhancement were requested by users who have setups which are not covered by the default channels. Thus the usability for those guys who have special needs is much improved.

In addition I have refactored the binding a little bit and removed the JAVA modelling of channels completely as there is no need to duplicate channel configuration in JAVA code.

### CODE REVIEW

**Comment by J-N-K** [comment]
I have two questions: 

1. Why are there customChannels at all? Why can't we just make the thing `extensible` and let the user decide how many custom channels should be added? This would also simplify code.

2. The scaling should be handled by a transformation. Why can't that be done here?

**Comment by alexf2015** [comment]
Is there any documentation which explains how to make a thing extensible?

Regarding transformation: What do you mean by transformation? I only know transformation which can be configured to transform value which are displayed in the UI. But this does not make sense here as it does not apply to the persistence.

**Comment by alexf2015** [comment]
@htreu / @Hilbrand As you already did the review of my initial contribution, you could perhaps also have a look on this. Thanks!

**Comment by alexf2015** [comment]
Any chance to get this into 2.5.0 release?

**Comment by cweitkamp** [comment]
@alexf2015 I am afraid not. We are already in code freeze phase for the release - apart from critical fixes.

**Comment by Hilbrand** [comment]
Same code changes as #6696 but some older base against master. The new pr is against 2.5.x and those changes will then eventually end up in 3.0. There is no need for a separate pr, so I'm closing this one.

**Pull request closed without merging**
