### PR TITLE
[jsscripting] Upgrade openhab-js & Remove SharedCache

### PR DESCRIPTION
**Pull request by florian-h05**
This PR upgrades the included openhab-js version to 3.1.0, which uses the new caches from core instead of the addon provided one and brings many doc improvements.

The `SharedCache` is therefore removed as it is superseded by the caches added to core in https://github.com/openhab/openhab-core/pull/2887.

@jlaur Ping.
@wborn FYI: We can now remove the `SharedCache`.

### CODE REVIEW

**Review by wborn — CHANGES_REQUESTED** [review]
It seems to break the build:

```
Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npx (npx webpack) on project org.openhab.automation.jsscripting: Failed to run task: 'npx webpack -c ./node_modules/openhab/webpack.config.js --entry ./node_modules/openhab/ -o ./dist' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
```

**Comment by florian-h05** [comment]
I see the problem, I'll fix it later.

**Comment by florian-h05** [comment]
@wborn The build is now working.
The problem was, that due to a change in the library we were requiring an import from openHAB that our bundler webpack was not aware of. I‘ve added the missing webpack configuration and now it works fine.

I‘ve also had a look at the classed in the `org.openhab.automation.jsscripting.internal.scope` package and I will probably open a PR with some cleanups and refactorings, since parts of the functionality of that package is actually also provided by core.

**Review by wborn — APPROVED** [review]
Thanks! :+1:  It's nice to also have this available in M6 as well.

**Pull request merged**
