### PR TITLE
3.4.x Create new binding for SyrSafeTech

### PR DESCRIPTION
**Pull request by RushAlmosa**
I am adding a new binding for a leakage protection device from Syr SafeTech.

### CODE REVIEW

**Comment by lolodomo** [comment]
Note that only new bindings on 4.0 branch will be reviewed and merged.

**Comment by RushAlmosa** [comment]
> Note that only new bindings on 4.0 branch will be reviewed and merged.

@lolodomo Thanks that's an impotent info.

It´s my first time contributing on an open-source project. I´m a little confused how to start. Do you have any tips?
Do i have to make a fork and work on that?
I thought i can open a PR and can work on it, but im not sure what´s the right way.
Goal is to make a new binding, i already did some coding but it's still on WIP.

i would appreciate any advice.

**Comment by Skinah** [comment]
Ask on the forum so more people can Learn instead of hidden away here.

**Comment by RushAlmosa** [comment]
> Ask on the forum so more people can Learn instead of hidden away here.

Thats a clever idea, https://community.openhab.org/t/seeking-guidance-on-contributing-and-creating-a-binding/146495

**Pull request closed without merging**
