### PR TITLE
[mqtt-homeassistant] Add JOSNPath and JINJA as requirements for MQTT HA

### PR DESCRIPTION
**Pull request by fundef1**
cfr. forum post: https://community.openhab.org/t/mqtt-homeassistant-thing-detected-no-channel/111775/

### CODE REVIEW

**Comment by J-N-K** [comment]
If it‘s a requirement, it should be installed automatically by adding a dependency to the feature.

**Comment by kaikreuzer** [comment]
@J-N-K No, we do not support dependencies between add-ons.
We might think about moving transformations to core, though and allow them to be required by add-ons, similar to the io-transport features - but that'll be a bigger change.

**Comment by J-N-K** [comment]
@kaikreuzer Why is that? I‘m pretty sure it would work.

**Comment by kaikreuzer** [comment]
Many reasons, in general known as [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).

**Comment by mhilbush** [comment]
Ruh roh! [This](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.globalcache/src/main/feature/feature.xml#L7) was done a long time ago when the transformations were part of ESH...

**Comment by J-N-K** [comment]
@mhilbush Thanks. I knew I saw that somewhere.

**Comment by Skinah** [comment]
I got caught out by the missing JINJA requirement, and in the last month I have seen at least 2 people in the forum asking why it does not work correctly with Tasmota devices. I am happy to change the feature.xml and do the testing but only if this is the recommended way forward?

https://community.openhab.org/t/mqtt-config-with-auto-discovery/109955

**Review by fwolter — APPROVED** [review]
If I understand correctly, the right way is to document it and not to add it to the features.xml.

**Comment by fwolter** [comment]
@fundef1 Can you sign-off your commit or post the sign-off message here if that is easier for you? See https://www.openhab.org/docs/developer/contributing.html#sign-your-work

**Comment by fundef1** [comment]
Signed-off-by: Jo Degraef <jo.degraef@addestino.be>

**Pull request merged**
