### PR TITLE
[liquidcheck] Initial Contribution

### PR DESCRIPTION
**Pull request by marcelGoerentz**

### CODE REVIEW

**Comment by fwolter** [comment]
Your PR contains changes outside your new binding.

**Comment by marcelGoerentz** [comment]
Yes, sorry my bad.
I'm new to contributing to an open source project.
Can I fix this with another commit?
Thanks in advance for your guidance.

**Comment by digitaldan** [comment]
@marcelGoerentz there are probably some git wizards here that can help untangle your branch, but you might want to think about creating a new branch from an up to date main branch, and copy your binding folder to it, then manually insert your binding into the pom.xml file in the addons directory, and add your binding to the CODEOWNERS file in the base folder  ( when you generated the skeleton, this is part of what that script did).   Make sure this compiles , then start a new PR.  B/c you pushed 500 changed files due to a git mishap, this PR has notified 50+ other code owners for review, so it might be good to start a new PR.  FYI when you open a PR, github lets you see the changed files before you actually open it, so you can test next time before going through with it.   

Yes, its a crude way to solve the problem, but i think doing it the Git way will take some sophistication (and this is what i would do)

**Comment by marcelGoerentz** [comment]
@digitaldan 
Thank you.
I will do as you say. Sorry for the inconvenience.

**Comment by marcelGoerentz** [comment]
I will close the PR right now

**Pull request closed without merging**
