### PR TITLE
[ipcamera] Add channel Privacy Mode to Amcrest and Dahua handlers

### PR DESCRIPTION
**Pull request by sidamos**
[ipcamera] Add channel Privacy Mode to Amcrest and Dahua handlers

Add a new channel "Privacy Mode" for camera types Amcrest and Dahua.

### CODE REVIEW

**Comment by Skinah** [comment]
I believe you need to get changes merged against V3 first before it is backported to 2.5 Also I don’t know if another 2.5 build will be made.

**Comment by sidamos** [comment]
> I believe you need to get changes merged against V3 first before it is backported to 2.5 Also I don’t know if another 2.5 build will be made.

I am sure, there won't be another 2.5.x build and that is ok.
I cannot code against 3.0 because I do not run 3.0 yet.
Can you integrate it for the 3.0 release? It is only a few small changes.

**Comment by Skinah** [comment]
No I wont implement it as my camera returns 'not supported' as the only response to those urls, it will need to wait until someone is using V3 that is willing to add it. Also it may be possible to implement this as an ONVIF feature by deliberately defocussing the lens or changing shutter and other values to destroy the picture, but I am not keen on doing the work on this myself as I have far many more important things for my own house that need doing.

**Comment by sidamos** [comment]
That's OK, I will do it for V3 once I have V3 installed.
The feature does 2 things: Move the lens WAY down (more than normally possible, so visitors can see that it does not film them anymore) AND it stops the stream. My cheap Tapo camera has the same feature, but it has no API.
ONVIF does not support privacy mode. It has privacy masks, which is a different thing.

**Comment by sidamos** [comment]
I have ported the changes to OH3. However, my OH3 snapshot binding does not show up in OH3. First, I had exceptions because of missing netty jars. Then I copied those that you provided for the OH2 snapshot binding to addons. This made the missing netty exceptions go away, but I still get an exception:
```
2020-11-21 13:52:00.207 [ERROR] [rg.apache.cxf.jaxrs.utils.JAXRSUtils] - Problem with writing the data, class org.openhab.core.io.rest.Stream2JSONInputStream, ContentType: application/json
2020-11-21 13:52:00.248 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {http://resources.internal.rest.io.core.openhab.org/}SystemInfoResource has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Closed
        at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleWriteException(JAXRSOutInterceptor.java:396) ~[bundleFile:1.0.9]
```
And the binding does not show up under installed bindings. This is with OH3 M2. 
Any idea? Otherwise, I would ask in the OH forums.

**Comment by sidamos** [comment]
I have ported it to V3 and created a pull request there.

**Pull request closed without merging**
