### PR TITLE
[stiebelheatpump][WIP] Stiebel Eltron Heat Pump Binding initial contribution

### PR DESCRIPTION
**Pull request by kreutpet**
WIP stiebel heatpump migration to openhab2

### CODE REVIEW

**Comment by wborn** [comment]
Thanks for the PR @kreutpet! It seems to contain two new bindings: iec6205621meter, stiebelheatpump. Can you create a separate PR for each binding?

**Comment by kreutpet** [comment]
upps, will have to clean it up before.
will review and make a new PR.

**Comment by triller-telekom** [comment]
@kreutpet A few more general comments before I'll do a review:

* `config-descriptions` in xml files can be reused, using `config-description-ref` see https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-binding-definitions which should make your thingtype xml file a lot smaller already.

* Please have a look at https://www.eclipse.org/smarthome/documentation/development/guidelines.html especially at the [Java naming conventions](http://java.about.com/od/javasyntax/a/nameconventions.htm) part. Sometimes you have upper case variable names and some of your class names start with a lower case.

* Regarding the `TypeResolver`: I didn't look deep enough into your code but you might not need it anymore. I am not sure whether its a good design to attach properties to channels which carry the information on how to decode the information from the serial connection. However to get the code compile for you to play around with you can do the following:

In your `HandlerFactory`:

```
@Reference
    public void setChannelTypeRegistry(ChannelTypeRegistry channelTypeRegistry) {
        this.channelTypeRegistry = channelTypeRegistry;
    }

    public void unsetChannelTypeRegistry(ChannelTypeRegistry channelTypeRegistry) {
        this.channelTypeRegistry = null;
    }

return new StiebelheatpumpHandler(thing, thingType, channelTypeRegistry);
```

And in the handler you can make use of this channelTypeRegistry as follows:

```
ChannelGroupType channelGroupType = channelTypeRegistry.getChannelGroupType(ChannelGroupTypeUID);

ChannelType channelType = channelTypeRegistry.getChannelType(channelTypeUID);
```

Regarding the `@Reference` in the factory:

We are using [DS annotations](http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/scr-annotations.html) now. Can you please remove this file and put a ".gitignore" fle in the OSGI-INF directory?

Inside your `HandlerFactory` you can use the `@Component` annotation which will create  this xml description for you. You can find an example in the [astro binding](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.astro/src/main/java/org/eclipse/smarthome/binding/astro/internal/AstroHandlerFactory.java#L33)

**Comment by martinvw** [comment]
> upps, will have to clean it up before.
> will review and make a new PR.

hello @kreutpet what is the status of this PR? Thanks for updating us!

**Comment by martinvw** [comment]
> hello @kreutpet what is the status of this PR? Thanks for updating us!

@kreutpet any updates for us? Is it still WIP do you expect to finish the work on it?

**Comment by triller-telekom** [comment]
@martinvw If @kreutpet is not responding/has other things to do/does not like to continue working on this binding, I guess I can continue here.

I need this binding anyway because I get a tecalor thz 304 flex in a couple of month too!

@kreutpet Would be great if you like to continue on this binding and maybe we can work together to get it done (though I will have the hardware only in a couple of month)?

**Comment by t2000** [comment]
FYI: I made the binding compatible with the current bnd workspace. It compiles fine and talks to my Tecalor THZ 5.5 flex heat pump. I just needed to comment out the check for the firmware version.

The work in progress code is in my branch: https://github.com/t2000/openhab2-addons/tree/stiebelheatpump

I will probably also clean up the code so at some point we might be able to finally merge it into the codebase.

**Comment by Hilbrand** [comment]
As this pr accidentally also contains the binding for `iec6205621meter` I was wondering in what way is the `iec6205621meter` different from the `smartmeter` binding that already is part of openHAB 2?

**Comment by t2000** [comment]
> As this pr accidentally also contains the binding for iec6205621meter I was wondering in what way is the iec6205621meter different from the smartmeter binding that already is part of openHAB 2?

I this this was included by accident and totally unrelated. I don't know if @kreutpet is still working on this binding though.

I am planning to continue working on my fork (bnd compatible already but not rebased to current master) https://github.com/t2000/openhab2-addons/tree/stiebelheatpump

However, I don't know when I will find the time to continue :(

**Comment by Hilbrand** [comment]
Closing this pr for now due to long time no activity. If development is to be continued a new pr can be created, which would be preferred if someone else is going to continue development.

**Pull request closed without merging**
