### PR TITLE
[miio] Add support for Roborock Q7 Max (roborock.vacuum.a38)

### PR DESCRIPTION
**Pull request by cribskip**
This enhancement adds the roborock Q7 Max to the supported devices of the miio binding.

I'll use the generated jar for testing, so please don't merge yet, thanks.

### CODE REVIEW

**Comment by marcelrv** [comment]
thanks for the contribution, good to hear it works for this model as well. 
Before you make your final push, can you run the readme maker as well, that way the documentation is updated as well.

**Comment by cribskip** [comment]
Ok, sadly, this needs more investigation as adding the json-file.

I'll take some time to debug in the next few days

**Comment by lolodomo** [comment]
What is the status of that PR? 
Is it still work in progress or abandoned?

**Comment by lolodomo** [comment]
@marcelrv : is that PR still relevant now that your PR #13111 was merged ?

**Comment by marcelrv** [comment]
I suggest to close this one. 
If @cribskip feels the merged PR does not work well enough and more channels to be defined he can do his testing confirm the working/details for the channels and submit a PR with improvements

**Comment by lolodomo** [comment]
Thank you for the feedback. 
@cribskip : feel free to reopen it or create another PR if you think something is missing

**Pull request closed without merging**
