### PR TITLE
[openwebnet] Backport of some fixes from OH 3.1.0 to 2.5.x branch

### LINKED ISSUE #9317: [openwebnet] Lowering dimmers from 20 to 10% does not change device level
Lowering dimmers from 20 to 10% does not change device level

## Expected Behavior
Lowering from 20 to 10% changes device level to minimum

## Current Behavior
Device level is not changed. A loop of requests to the gw are logged

## Steps to Reproduce (for Bugs)
Lower a BUS dimmer from 20 to 10% using PaperUI

## Your Environment
OH 3.0.0.M4 & M5

### LINKED ISSUE #9651: [openwebnet] Command UP/DOWN inverted on old firmwares when using Legrand Bticino USB dongle (OH3 binding version 3.0.0)
Due to a buggy old firmware on the Legrand/Bticino USB dongle, up/down command shall be inverted in the Openwebnet binding for OH3.

## Expected Behavior
When you click up, rollershutters should open.
When you click down, rollershutters should close.

## Current Behavior
When you click up, rollershutters are closing
When you click down, rollershutters are opening.
This is due to a buggy firmware of the Legrand/Bticino USB dongle.

Scenario Up / STOP / down led to the following logs:
```
    2021-01-02 14:15:46.257 [DEBUG] [ebnet.handler.OpenWebNetThingHandler] - handleCommand() (command=UP - channel=openwebnet:zb_automation:donglelegrand:voletsbureau:shutter)
    2021-01-02 14:15:46.257 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## older firmware: converting Automation UP / DOWN on message: <*2*1*767876801#9##>
    2021-01-02 14:15:46.257 [INFO ] [nwebnet4j.communication.FrameChannel] - -FC-USB -------> *2*1*767876801#9##
    2021-01-02 14:15:46.257 [INFO ] [j.communication.USBConnector.message] - USB-CMD ====>>>> *2*1*767876801#9##
    2021-01-02 14:15:46.275 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## START Processing DATA_AVAILABLE event...
    2021-01-02 14:15:46.275 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB <------- [*#*1##]
    2021-01-02 14:15:46.275 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## processing frame: *#*1##
    2021-01-02 14:15:46.275 [DEBUG] [j.communication.USBConnector.message] - USB-CMD   <<==   *#*1##
    2021-01-02 14:15:46.275 [DEBUG] [.openwebnet4j.communication.Response] - <*2*2*767876801#9##>   <<add   <*#*1##>
    2021-01-02 14:15:46.275 [DEBUG] [.openwebnet4j.communication.Response] - now: <*2*2*767876801#9##>   <<==    [<*#*1##>]
    2021-01-02 14:15:46.276 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## USB final response: {REQ=<*2*2*767876801#9##>|RESP=[<*#*1##>]}
    2021-01-02 14:15:46.276 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## [safeCall-213] response COMPLETE!
    2021-01-02 14:15:46.276 [INFO ] [j.communication.USBConnector.message] - USB-CMD <<<<==== [<*#*1##>]
    2021-01-02 14:15:46.378 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB |<--     NO DATA (size=0)
    2021-01-02 14:15:46.499 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## START Processing DATA_AVAILABLE event...
    2021-01-02 14:15:46.501 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB <------- [*2*1*767876801#9##]
    2021-01-02 14:15:46.501 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## processing frame: *2*1*767876801#9##
    2021-01-02 14:15:46.501 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## older firmware: converting Automation UP / DOWN on message: <*2*1*767876801#9##>
    2021-01-02 14:15:46.502 [INFO ] [unication.USBConnector.message.event] - USB-MON <<<<<<<< *2*2*767876801#9##
    2021-01-02 14:15:46.503 [DEBUG] [bnet.handler.OpenWebNetBridgeHandler] - ownIdFromMessage(<*2*2*767876801#9##>) --> 2.767876800h9
    2021-01-02 14:15:46.504 [DEBUG] [.handler.OpenWebNetAutomationHandler] - updateAutomationState() - msg=<*2*2*767876801#9##> what=DOWN
    2021-01-02 14:15:46.504 [DEBUG] [.handler.OpenWebNetAutomationHandler] - # w:767876801#9 # MOVING 2 - startedMovingAt=1609593346504 - 46.504
    2021-01-02 14:15:46.504 [DEBUG] [.handler.OpenWebNetAutomationHandler] - # w:767876801#9 # movingState=2 positionEstimation=-1 - calibrating=-1 shutterRun=-1
    2021-01-02 14:15:46.705 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB |<--     NO DATA (size=0)
    2021-01-02 14:15:50.511 [DEBUG] [ebnet.handler.OpenWebNetThingHandler] - handleCommand() (command=STOP - channel=openwebnet:zb_automation:donglelegrand:voletsbureau:shutter)
    2021-01-02 14:15:50.511 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## older firmware: converting Automation UP / DOWN on message: <*2*0*767876801#9##>
    2021-01-02 14:15:50.511 [INFO ] [nwebnet4j.communication.FrameChannel] - -FC-USB -------> *2*0*767876801#9##
    2021-01-02 14:15:50.511 [INFO ] [j.communication.USBConnector.message] - USB-CMD ====>>>> *2*0*767876801#9##
    2021-01-02 14:15:50.530 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## START Processing DATA_AVAILABLE event...
    2021-01-02 14:15:50.530 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB <------- [*#*1##]
    2021-01-02 14:15:50.530 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## processing frame: *#*1##
    2021-01-02 14:15:50.530 [DEBUG] [j.communication.USBConnector.message] - USB-CMD   <<==   *#*1##
    2021-01-02 14:15:50.530 [DEBUG] [.openwebnet4j.communication.Response] - <*2*0*767876801#9##>   <<add   <*#*1##>
    2021-01-02 14:15:50.530 [DEBUG] [.openwebnet4j.communication.Response] - now: <*2*0*767876801#9##>   <<==    [<*#*1##>]
    2021-01-02 14:15:50.530 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## USB final response: {REQ=<*2*0*767876801#9##>|RESP=[<*#*1##>]}
    2021-01-02 14:15:50.530 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## [safeCall-214] response COMPLETE!
    2021-01-02 14:15:50.530 [INFO ] [j.communication.USBConnector.message] - USB-CMD <<<<==== [<*#*1##>]
    2021-01-02 14:15:50.733 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB |<--     NO DATA (size=0)
    2021-01-02 14:15:51.499 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## START Processing DATA_AVAILABLE event...
    2021-01-02 14:15:51.500 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB <------- [*2*0*767876801#9##]
    2021-01-02 14:15:51.501 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## processing frame: *2*0*767876801#9##
    2021-01-02 14:15:51.501 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## older firmware: converting Automation UP / DOWN on message: <*2*0*767876801#9##>
    2021-01-02 14:15:51.501 [INFO ] [unication.USBConnector.message.event] - USB-MON <<<<<<<< *2*0*767876801#9##
    2021-01-02 14:15:51.502 [DEBUG] [bnet.handler.OpenWebNetBridgeHandler] - ownIdFromMessage(<*2*0*767876801#9##>) --> 2.767876800h9
    2021-01-02 14:15:51.503 [DEBUG] [.handler.OpenWebNetAutomationHandler] - updateAutomationState() - msg=<*2*0*767876801#9##> what=STOP
    2021-01-02 14:15:51.503 [DEBUG] [.handler.OpenWebNetAutomationHandler] - # w:767876801#9 # movingState=0 positionEstimation=-1 - calibrating=-1 shutterRun=-1
    2021-01-02 14:15:51.705 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB |<--     NO DATA (size=0)
    2021-01-02 14:15:52.181 [DEBUG] [ebnet.handler.OpenWebNetThingHandler] - handleCommand() (command=DOWN - channel=openwebnet:zb_automation:donglelegrand:voletsbureau:shutter)
    2021-01-02 14:15:52.181 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## older firmware: converting Automation UP / DOWN on message: <*2*2*767876801#9##>
    2021-01-02 14:15:52.181 [INFO ] [nwebnet4j.communication.FrameChannel] - -FC-USB -------> *2*2*767876801#9##
    2021-01-02 14:15:52.182 [INFO ] [j.communication.USBConnector.message] - USB-CMD ====>>>> *2*2*767876801#9##
    2021-01-02 14:15:52.200 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## START Processing DATA_AVAILABLE event...
    2021-01-02 14:15:52.200 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB <------- [*#*1##]
    2021-01-02 14:15:52.200 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## processing frame: *#*1##
    2021-01-02 14:15:52.200 [DEBUG] [j.communication.USBConnector.message] - USB-CMD   <<==   *#*1##
    2021-01-02 14:15:52.200 [DEBUG] [.openwebnet4j.communication.Response] - <*2*1*767876801#9##>   <<add   <*#*1##>
    2021-01-02 14:15:52.200 [DEBUG] [.openwebnet4j.communication.Response] - now: <*2*1*767876801#9##>   <<==    [<*#*1##>]
    2021-01-02 14:15:52.200 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## USB final response: {REQ=<*2*1*767876801#9##>|RESP=[<*#*1##>]}
    2021-01-02 14:15:52.200 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## [safeCall-214] response COMPLETE!
    2021-01-02 14:15:52.200 [INFO ] [j.communication.USBConnector.message] - USB-CMD <<<<==== [<*#*1##>]
    2021-01-02 14:15:52.403 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB |<--     NO DATA (size=0)
    2021-01-02 14:15:54.329 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## START Processing DATA_AVAILABLE event...
    2021-01-02 14:15:54.330 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB <------- [*2*2*767876801#9##]
    2021-01-02 14:15:54.330 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## processing frame: *2*2*767876801#9##
    2021-01-02 14:15:54.331 [DEBUG] [nwebnet4j.communication.USBConnector] - ##USB-conn## older firmware: converting Automation UP / DOWN on message: <*2*2*767876801#9##>
    2021-01-02 14:15:54.331 [INFO ] [unication.USBConnector.message.event] - USB-MON <<<<<<<< *2*1*767876801#9##
    2021-01-02 14:15:54.332 [DEBUG] [bnet.handler.OpenWebNetBridgeHandler] - ownIdFromMessage(<*2*1*767876801#9##>) --> 2.767876800h9
    2021-01-02 14:15:54.332 [DEBUG] [.handler.OpenWebNetAutomationHandler] - updateAutomationState() - msg=<*2*1*767876801#9##> what=UP
    2021-01-02 14:15:54.333 [DEBUG] [.handler.OpenWebNetAutomationHandler] - # w:767876801#9 # MOVING 1 - startedMovingAt=1609593354333 - 54.333
    2021-01-02 14:15:54.333 [DEBUG] [.handler.OpenWebNetAutomationHandler] - # w:767876801#9 # movingState=1 positionEstimation=-1 - calibrating=-1 shutterRun=-1
    2021-01-02 14:15:54.534 [DEBUG] [nwebnet4j.communication.FrameChannel] - -FC-USB |<--     NO DATA (size=0)
```

## Possible Solution
Already known by developper

## Steps to Reproduce (for Bugs)
Just push up & see roller shutter closing (or vice & versa)

## Context
Closing / Opening of my rollershutters is improperly working (need to click down to open shuttrers, and up to close them)

## Your Environment
Openhab 3 running on Windows 10 PC
Openwebnet binding version 3.0.0

### PR DESCRIPTION
**Pull request by mvalla**
Backport of some fixes from OH 3.1.0 to 2.5.x branch (see PR #9662)
* fixed reconnect of gateway from USB port
* fixed up/down inverted automation messages for old firmwares (fixes #9651)
* removed warn logs when reconnecting BUS command connection
* fixed dimmers creating loop when lowered from 20 to 10% (fixes #9317)
* now using openwebnet4j 0.3.4

### CODE REVIEW

**Review by fwolter — APPROVED** [review]

**Comment by kaikreuzer** [comment]
@mvalla Please change the issue title to something that makes sense to have in the release notes and what describes the changes.

**Comment by kaikreuzer** [comment]
@fwolter Please also note that we should only merge critical fixes for 2.5.x and no improvements anymore.
I'd thus recommend to not accept "summary PRs" anymore, which don't clearly address a single issues. Whereever possible, fixes should be backported by cherry-picking a commit from a PR against main.

**Comment by fwolter** [comment]
OK!

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by mvalla** [comment]
> @mvalla Please change the issue title to something that makes sense to have in the release notes and what describes the changes.

done, thanks.

**Pull request merged**
