### PR TITLE
Remove SmartHome leftovers

### PR DESCRIPTION
**Pull request by wborn**
Depends on https://github.com/openhab/openhab-core/pull/1901

The "SmartHome" references in these classes may also need an update:

* HueBridgeHandler
* MiCloudConnector
* SonosBindingConstants

I haven't changed these as it was not clear how much it would break existing configurations.

### CODE REVIEW

**Comment by marcelrv** [comment]
@wborn the reference in the MiCloudConnector is not related to the Eclipse smarthome but rather a reference to the Xiaomi smarthome

**Review by marcelrv — APPROVED** [review]
LGTM wrt to the max binding

**Review by fruggy83 — APPROVED** [review]
LGTM wrt to the enocean binding

**Comment by kaikreuzer** [comment]
Hm, for some reason this keeps running into a `java.lang.StackOverflowError`...

**Comment by kaikreuzer** [comment]
```
[INFO] openHAB Add-ons :: Bundles :: IO :: Modbus Transport FAILURE [01:15 min]
```
Maybe we should first look at merging https://github.com/openhab/openhab-addons/pull/9268... I waited with the rebase for this PR here, but if you wish we can swap the order (and you'll have to rebase as well...)

**Comment by wborn** [comment]
It's probably easier to first merge https://github.com/openhab/openhab-addons/pull/9268.

**Comment by wborn** [comment]
Looking at the content in this PR there might probably still be failing integration tests in PR builds for #9268 until this PR is merged. We can also temporarily disable feature verification to prevent the `StackOverflowError` by adding `-Dfeatures.verify.skip=true`

**Review by kaikreuzer — APPROVED** [review]
We can also merge this without Jenkins and deal with any issues after the modbus PR is merged as well. Will do the rebase now...

**Comment by wborn** [comment]
Good! In the end the build will succeed anyways. :wink:

**Pull request merged**
