### PR TITLE
[knx] DPT 1 to support Switch and Contact

### PR DESCRIPTION
**Pull request by holgerfriedrich**
* Allow assigning Switch or Contact to most of the DPT 1 subtypes (exceptions 1.008 UpDownType, 1.010 StopMoveType, 1.022 DecimalType).
* Tests for all published subtypes for DPT 1.
* Fix sending of DPT 1.022.

This PR has been initiated because of a discussion in the (German speaking) [KNX User Forum](https://knx-user-forum.de/forum/supportforen/openhab/1921835-ko-mit-datentyp-1-011-als-switch-geht-als-contact-nicht).
DPT1 implementation had a rather strict mapping to types before. A Contact could not be used if the specific DPT was added to the group address definition ```ga="1.011:<17/1/38"```, unless it was 1.009 or 1.019. As only subtypes 009 and 019 were mapped to OpenClosedType and the fallback for other DPTs was OnOffType,

### CODE REVIEW

**Comment by lsiepel** [comment]
I guess this does not fix https://github.com/openhab/openhab-addons/issues/9747, but does it in someway improve that?

**Comment by holgerfriedrich** [comment]
It does not, and this is intended.

It allows to map DPTs that could previously be mapped to switch items also to be mapped to contact items.
It was possible to do so as well before, but with the workaround to force the DPT to 1.009 or 1.019. 
I think it is more convenient if users can configure the same DPTs as in ETS.

**Review by lsiepel — APPROVED** [review]
LGTM, double check before i merge: Would it be usefull to have a note/comment in the readme about this DPT 1 'fallback' functionality'

**Comment by holgerfriedrich** [comment]
@lsiepel Thanks for asking. We do not state possible conversions in the README, just the default DPTs for the different types. So you could just go on....

**Pull request merged**
