### PR TITLE
[homekit] fix restarted on network interface change

### PR DESCRIPTION
**Pull request by ccutrer**
a regression caused during the final changes of #13877

### CODE REVIEW

**Comment by ccutrer** [comment]
cc @kaikreuzer. when we simplified to only receiving notification of STATES start level, we stopped updating the currentStartLevel instance member, which was being checked to know if it should stop/start the Homekit server when a network interface changed. This PR simplifies currentStartLevel to a simple boolean, and actually updates it.

Note that this is a regression in 3.4.0 vs 3.3, and if we plan on having a 3.4.2 release, we should cherry-pick this over.

I'm leaving as a draft while I test the fix in my local environment for 24 hours (I seemed to hit this every night).

**Review by lolodomo — APPROVED** [review]
Code LGTM

**Comment by lolodomo** [comment]
@kaikreuzer :would you like to have a look ?

**Comment by yfre** [comment]
@ccutrer do know whether this is included in 3.4.2?

**Comment by ccutrer** [comment]
It did not: https://github.com/openhab/openhab-addons/commits/3.4.2

**Comment by kaikreuzer** [comment]
Shall we pick it for a future 3.4.3?

**Comment by ccutrer** [comment]
Yes please.

**Comment by kaikreuzer** [comment]
Done!

**Pull request merged**
