### PR TITLE
[freeboxos] Remove macAddress as thing configuration parameter

### LINKED ISSUE #17076: [freeboxos] macAddress parameter really required for server thing?
The macAddress parameter for server/revolution thing is not documented in README while it is a required parameter in the thing description.

### PR DESCRIPTION
**Pull request by lolodomo**
For server, revolution, player, active-player, repeater and vm thing types.
Replace it by a thing property.

Fix #17076

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM. Waiting for @clinique approval.

**Comment by lolodomo** [comment]
I also removed the configuration parameter from player and active-player thing types.

**Comment by lolodomo** [comment]
I have to apply the same for vm and repeater.

**Comment by lolodomo** [comment]
It is now ready for review.

**Review by lsiepel — APPROVED** [review]
@clinique for approval

**Review by clinique — APPROVED** [review]

**Pull request merged**
