### PR TITLE
[shelly] Various small fixes for BLU HT, Range Extender, Plus 10V, TRV set temp

### PR DESCRIPTION
**Pull request by markus7017**
This PR includes various small fixes (1 liners)

Closing
#16736
#16734
#16542
#16709
#16655
#16724

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
LGTM, let's wait for some test confirmations.

**Comment by lolodomo** [comment]
@markus7017 : What is the status here ? Still work in progress ? Or still waiting for additional tests ? Or just ready for a merge ?

**Comment by markus7017** [comment]
@lolodomo waited for tester feedback, looks good = ready to merge

**Comment by lolodomo** [comment]
@lsiepel : I let you click on merge button as you reviewed this PR.

You will probably have then to close each referenced issue manually as I believe this was not declared as expected for an automatic closing.

**Comment by markus7017** [comment]
@lolodomo I marked the issues in the initial description (Closing:) or is the syntax incorrect?

**Comment by lsiepel** [comment]
> @lolodomo I marked the issues in the initial description (Closing:) or is the syntax incorrect?

Yes,  you can also see it on the right side:
image

**Pull request merged**
