### PR TITLE
Updated the openhab-cloud readme for OH3

### PR DESCRIPTION
**Pull request by Stefan300381**

### CODE REVIEW

**Review by fwolter — APPROVED** [review]

**Comment by fwolter** [comment]
You need to sign-off your commits. See https://www.openhab.org/docs/developer/contributing.html#sign-your-work The necessary commands are listed when you click on "Details" at the DCO check below.

**Comment by kaikreuzer** [comment]
@Stefan300381 You can also post your sign-off as a comment on this PR, if that's easier for you. Thanks!

**Comment by Stefan300381** [comment]
Signed-off-by: Stefan Haupt <stefan@haupt.xyz>

**Review by fwolter — APPROVED** [review]
Thanks!

**Pull request merged**
