### PR TITLE
[tesla] Set the token creation time as it is no longer provided in the response

### LINKED ISSUE #12533: [tesla] Exception occurred - communication_error
After the [fix of a recent API token problem](https://github.com/openhab/openhab-addons/pull/12530), another problem with the tesla binding has come up.
@tkranz gets this error

```2022-03-27 17:52:41.378 [ERROR] [internal.handler.TeslaAccountHandler] - An exception occurred while connecting to the Tesla back-end: 'null'
at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.authenticate(TeslaAccountHandler.java:259) ~[?:?]
at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$0(TeslaAccountHandler.java:377) ~[?:?]
2022-03-27 17:52:41.443 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:models:12345:54321' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2022-03-27 17:52:41.526 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:models:12345:54321' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2022-03-27 17:52:56.379 [ERROR] [internal.handler.TeslaAccountHandler] - An exception occurred while connecting to the Tesla back-end: 'null'
at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.authenticate(TeslaAccountHandler.java:259) ~[?:?]
at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$0(TeslaAccountHandler.java:377) ~[?:?]
```

and I'm getting this error
```
2022-03-27 17:01:36.557 [WARN ] [internal.handler.TeslaVehicleHandler] - Exception occurred in slowStateRunnable
java.util.ConcurrentModificationException: null
	at java.util.ArrayList.sort(ArrayList.java:1752) ~[?:?]
	at org.apache.cxf.jaxrs.provider.ProviderFactory.sortReaders(ProviderFactory.java:734) ~[?:?]
	at org.apache.cxf.jaxrs.provider.ProviderFactory.setCommonProviders(ProviderFactory.java:662) ~[?:?]
	at org.apache.cxf.jaxrs.client.ClientProviderFactory.setProviders(ClientProviderFactory.java:73) ~[?:?]
	at org.apache.cxf.jaxrs.provider.ProviderFactory.setUserProviders(ProviderFactory.java:862) ~[?:?]
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:282) ~[?:?]
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:377) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicle(TeslaVehicleHandler.java:738) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicleAndUpdate(TeslaVehicleHandler.java:772) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.lambda$0(TeslaVehicleHandler.java:977) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Since the night, I get a COMMUNICATION_ERROR for the car thing (the account thing is online). I get this warn an error once a minute now:
```
2022-03-28 00:29:41.745 [WARN ] [internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
2022-03-28 00:29:41.746 [ERROR] [internal.handler.TeslaVehicleHandler] - An error occurred while querying the vehicle
```

Manually disabling the account and car thing and then enabling them again, brings both back online.

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes #12533

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by phuongpham** [comment]
Great work. I will test it soon. But it will takes time before the error appear?

**Comment by kaikreuzer** [comment]
Yes, it only occurs when the access token expires. Afaik, they have a validity of 8 hours, before they are refreshed.

**Comment by phuongpham** [comment]
@kaikreuzer could you upload the jar file instead of zip? It would be easier to just update existing binding with the path to the jar file

**Comment by kaikreuzer** [comment]
Ok, I have uploaded the jar directly, but changed its extension to zip, since Github does not allow jars.

**Comment by phuongpham** [comment]
> Ok, I have uploaded the jar directly, but changed its extension to zip, since Github does not allow jars.

Ok strange.
I just tested by my self now: https://github.com/phuongpham/temp/blob/main/org.openhab.binding.tesla-3.3.0-SNAPSHOT.jar
It seems to work.
Anyway I have managed to update the binding now.
Will let you know when the token will refresh.

Again thanks for your great work :)

**Comment by kaikreuzer** [comment]
For the ones with multiple vehicles: Here's an updated version, which should also fix the ConcurrentModificationException:
[org.openhab.binding.tesla-3.3.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/8382782/org.openhab.binding.tesla-3.3.0-SNAPSHOT.zip)

**Comment by kaikreuzer** [comment]
Hm, ok, this only partially fixed the issue - the account now stays ONLINE, but querying the vehicle still fails once the access token is expired:
```
07:46:51.564 [DEBUG] [.internal.handler.TeslaVehicleHandler] - Querying the vehicle, response : 401, Unauthorized
07:46:51.566 [WARN ] [.internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
07:46:51.566 [ERROR] [.internal.handler.TeslaVehicleHandler] - An error occurred while querying the vehicle
```
Will continue to look into it...

**Comment by phuongpham** [comment]
> Hm, ok, this only partially fixed the issue - the account now stays ONLINE, but querying the vehicle still fails once the access token is expired:
> 
> ```
> 07:46:51.564 [DEBUG] [.internal.handler.TeslaVehicleHandler] - Querying the vehicle, response : 401, Unauthorized
> 07:46:51.566 [WARN ] [.internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
> 07:46:51.566 [ERROR] [.internal.handler.TeslaVehicleHandler] - An error occurred while querying the vehicle
> ```
> 
> Will continue to look into it...

Yes I got the error this morning.
Do you need additional logs from me or do you have enough information from your logs?

**Comment by kaikreuzer** [comment]
I already have a local fix that I am just testing. Will provide an update tonight.

**Comment by kaikreuzer** [comment]
Ok, my latest changes from yesterday evening seem to do the trick - my car is still online this morning. 🎉 
I've pushed the code and rebased it to the latest main branch, so I'd say it is ready to be merged, @openhab/add-ons-maintainers.

**Review by jlaur — APPROVED** [review]
Thanks for the fix!

**Comment by phuongpham** [comment]
@kaikreuzer what build number is the correct one? https://openhab.jfrog.io/ui/builds/PR-openHAB-Addons?buildRepo=artifactory-build-info

**Comment by phuongpham** [comment]
OK I managed to get the latest snapshot now here: https://openhab.jfrog.io/artifactory/libs-snapshot-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0-SNAPSHOT/org.openhab.binding.tesla-3.3.0-20220402.032507-90.jar

But the problem I have now is I have problem with the car things. The status is stuck in "INITIALIZING".
The account things works fine and the status is "ONLINE".
I have tried to delete the car things but still same issue.
In the logs I can see this warning/error:

`19:05:54.117 [WARN ] [.core.thing.internal.ThingManagerImpl] - Disposing handler for thing 'tesla:account:4c1a063380' takes more than 5000ms.`

**Comment by phuongpham** [comment]
Ok It was some problem with the OH installation. I got the same error with Zwave as well.
I rebooted the rpi and everything works fine now :)

**Comment by phuongpham** [comment]
> @phuongpham Hi, link doesn't seem to work. Could you provide the jar-file again? Thank you!

I'm struggeling to get the lastest snapshot working. 
Not sure if it's the binding that cause the problem.
@kaikreuzer  can you please share the snapshot you are using?

**Comment by phuongpham** [comment]
@kaikreuzer  the error I receiving is 
`19:05:17.841 [WARN ] [core.internal.thing.ThingTypeResource] - Cannot find channel type: tesla:allowwakeup
`

**Comment by kaikreuzer** [comment]
Try deleting and recreating the Thing. And consider upgrading to 3.3.0.M3.

**Comment by hlemmens** [comment]
I run 3.3.0.M3. I generated a new refresh token with a third party app. But my Tesla account is stuck "Initialising". Any idea what I can do to?

**Comment by phuongpham** [comment]
> I run 3.3.0.M3. I generated a new refresh token with a third party app. But my Tesla account is stuck "Initialising". Any idea what I can do to?

Have you tried to delete both things (car and account)?

**Comment by hlemmens** [comment]
@phuongpham 
Thanks for the suggestion. Cleaning the cash is indeed unlocking the bridge and the car thing. However, the car thing stops updating after a short time. No traces to find in openhanded.log file.
Is there a more recent snapshot then th 3.3.0M3?

**Comment by phuongpham** [comment]
> @phuongpham Thanks for the suggestion. Cleaning the cash is indeed unlocking the bridge and the car thing. However, the car thing stops updating after a short time. No traces to find in openhanded.log file. Is there a more recent snapshot then th 3.3.0M3?

Unsure what version binding you running.

What results do you get in karaf console


You could always try to update the lastest snapshot in karaf console:

`bundle:update org.openhab.binding.tesla https://openhab.jfrog.io/artifactory/libs-snapshot-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0-SNAPSHOT/org.openhab.binding.tesla-3.3.0-20220412.032507-98.jar`

**Comment by hlemmens** [comment]
When I run de bundle:list command in Karaf i get:
256 │ Active │  80 │ 3.3.0.M3               │ openHAB Add-ons :: Bundles :: Tesla Binding

Then, I run the command: bundle:update org.openhab.binding.tesla https://openhab.jfrog.io/artifactory/libs-snapshot-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0-SNAPSHOT/org.openhab.binding.tesla-3.3.0-20220412.032507-98.jar

After running the command, I get  
256 │ Active │  80 │ 3.3.0.202204120405     │ openHAB Add-ons :: Bundles :: Tesla Binding
It looks like the snapshot is installed. However, looking into the add-on directory (/var/lib/openhab/tmp/kar/openhab-addons-3.3.0.M3/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0.M3 ), I find org.openhab.binding.tesla-3.3.0.M3.jar. No snapshot version is found. I'm afraid I will fallback to the M3 version after restart.
The car thing is for the time being properly updating the items I created and linked to the channels. Cross fingers that it stays OK.

**Comment by phuongpham** [comment]
I see.
But based ot the bundle:list you have upgraded to the latest snapshot (the link I provided to you)
I don't think It will "fall back" even with restart. Only when you upgrade openHab.

**Comment by hlemmens** [comment]
I'm sorry to say, but the car thing is not properly updating anymore. Tried to get an update of all channels by disabling and enabling the car thing, but it's again stuck on 'Initiliazing". I'm afraid the latest version is not stable yet and I'm sorry not to be able to contribute to an improvement.

**Comment by phuongpham** [comment]
> I'm sorry to say, but the car thing is not properly updating anymore. Tried to get an update of all channels by disabling and enabling the car thing, but it's again stuck on 'Initiliazing". I'm afraid the latest version is not stable yet and I'm sorry not to be able to contribute to an improvement.

Try to delete the thing now and try again.

**Comment by hlemmens** [comment]
I don't think It will "fall back" even with restart. Only when you upgrade openHab.
It didn't fall back after a stop and start of openhab.

**Comment by hlemmens** [comment]
I deleted the car thing and the account thing. Now I'm stuck on "Initializing" the account thing.
Isn't Tesla playing a game with us?

**Comment by kaikreuzer** [comment]
@hlemmens You might want to try the latest snapshot as I did another fix wrt deadlocks on it: https://github.com/openhab/openhab-addons/pull/12603

If this doesn't help either, I'd suggest you create a new issue and provide debug logs with it.

**Comment by hlemmens** [comment]
@kaikreuzer I installed the snapshot yesterday morning and up to now, it works fine. Thanks.

**Pull request merged**
