### PR TITLE
[amazonechocontrol] fix routines (backport)

### PR DESCRIPTION
**Pull request by J-N-K**
See #9982 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Review by Hilbrand — APPROVED** [review]
LGTM

**Review by mgeramb — APPROVED** [review]
Thank you!

**Comment by jaywiseman1971** [comment]
Agreed, Thank you!

**Comment by jaywiseman1971** [comment]
@Hilbrand ,

A few of us are wondering when the build will be fixed above in order to finish?  

Thank  you!

Best, Jay

**Comment by J-N-K** [comment]
I guess #10000 will do.

**Comment by jaywiseman1971** [comment]
It got through the Amazon binding but failed for the spotless build across all the bindings.

https://ci.openhab.org/job/PR-openHAB-Addons/2493/

Is there anywhere we can download the new Amazon Echo Build w/o having all the bindings succeed?

Best, Jay

**Pull request merged**
