### PR TITLE
[tr064] Update Tr064PhonebookImpl.java

### PR DESCRIPTION
**Pull request by JensHoRi**
Increased Timeout for Phonebook Download to 5 seconds. Maybe somebody else can make it configurable within bridge. :-)

### CODE REVIEW

**Comment by JensHoRi** [comment]
Just a quick change because of Issue:
https://github.com/openhab/openhab-addons/issues/10436

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

I am wondering if we can use the following method to request the phonebook:

https://github.com/openhab/openhab-addons/blob/3525c9123e5741d44cc3124045c0bf5194f9f74e/bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java#L342

It already has a timeout of 5 seconds. And additionally supports caching. @J-N-K wdyt?

**Comment by cweitkamp** [comment]
I submitted https://github.com/openhab/openhab-addons/pull/10447 to show a different solution.

**Comment by J-N-K** [comment]
IIRC the `Util.getAndUnmarshalXML` originally was non-static and in a different package. So using it should be fine.

**Comment by cweitkamp** [comment]
Superseded by #10447

**Pull request closed without merging**
