### PR TITLE
Resolve runbundles and fix tests

### PR DESCRIPTION
**Pull request by wborn**
Related to:

* openhab/openhab-core#3433
* openhab/openhab-core#3446
* openhab/openhab-core#3450

Some tests were updated because private lifecycle methods (annotated with `@BeforeAll`, `@AfterAll`, `@BeforeEach`, or `@AfterEach`) now lead to an exception.

See: https://junit.org/junit5/docs/current/release-notes/index.html#deprecations-and-breaking-changes-3

### CODE REVIEW

**Review by jlaur — APPROVED** [review]
Thanks for the upgrades and fixes!

**Review by hmerk — COMMENTED** [review]
LGTM for Wemo

**Comment by andrewfg** [comment]
@wborn (putting aside the fact that this broke my PR #13570 yet again) .. .. as @kaikreuzer says _"another effect of Java17 is that it (OH 4.0) does not include the Nashorn Javascript engine anymore"_ so perhaps you need to remove `org.openhab.automation.jssscriptiingnashorn.tests`?

**Comment by wborn** [comment]
No because @kaikreuzer also says _"Install the JavaScript Nashorn add-on ..."_.
So that's the add-on that is tested by that project. :slightly_smiling_face:

**Pull request merged**
