### PR TITLE
[openwebnet] OpenWebNet Binding initial contribution

### PR DESCRIPTION
**Pull request by smf666**
Goal of this binding to add support of OpenWebNet / ZigBee devices (later also classical OpenWebNet SCS devices)

OpenWebNet binding

This is the first working (at least on my setup) of an OpenWebNet / ZigBee devices including:
- serial bridge, 
- lighting devices (switch and dimmer)
- automation

The binding is developed under this repository:
https://github.com/smf666/openhab2-addons/tree/openwebnet/addons/binding/org.openhab.binding.openwebnet

A build of the actual binding for testing can be found here:
https://github.com/smf666/openhab2-addons/releases/

### CODE REVIEW

**Comment by smf666** [comment]
How can I add the missing Signed-off-by ?

**Comment by wborn** [comment]
Thanks for your PR @smf666! 

Can you rebase/squash your commits so [Files changed](https://github.com/openhab/openhab2-addons/pull/3220/files) only shows the changes for your binding?
That makes the PR easier to review. 

When you squash the commits into a single commit make sure your commit message ends with:

`Signed-off-by: Antoine Laydier <smf@free.fr>`

That way it is properly signed off (see [Sign your work](https://docs.openhab.org/developers/contributing/contributing#sign-your-work)).

**Comment by J-N-K** [comment]
@smf66, do you intend to continue here?

**Comment by martinvw** [comment]
@smf666, do you intend to continue here?

**Comment by Hilbrand** [comment]
Closing pr due to long time inactivity.

**Pull request closed without merging**
