### PR TITLE
[nzwateralerts] New Zealand Water Alerts Binding initial contribution

### PR DESCRIPTION
**Pull request by Cossey**
New Zealand Water Alerts Binding

This is a new binding which gives the Water Alert Level in some regions in New Zealand.

There is only a single channel which returns the water alert level, a range of `0-4` or `1-4` depending on region. This is intended to be used with automated sprinkler systems in openHAB as restriction levels usually dictate the days where you are allowed to use sprinklers.

_Unfortunately since my country is always 20 years behind there's no web service for this information so specific web pages have to be scraped and data returned using regular expressions._

This Binding is on the _Eclipse Marketplace_ or can be downloaded from here https://www.dropbox.com/s/1uc5ky5rg35bfcm/org.openhab.binding.nzwateralerts-2.5.0-SNAPSHOT.jar?dl=1

### CODE REVIEW

**Comment by Cossey** [comment]
Just checking in to see if this PR will be approved or if changes may need to be made?

I did have a thought at possibly expanding this a bit more to support other places in the world to be the "Water alerts binding" vs the "NZ Water Alerts Binding" but I'd need input for people from other regions, if they have websites or actual APIs that can pull their local/county water restriction information.

**Comment by fwolter** [comment]
Are you still interested in a review/merge? If you fix the conflicts, I'd take a look into it.

**Comment by Cossey** [comment]
Thanks, I had just assumed that this binding wasn't suitable for the addons repository considering this PR has been open for a long time. I will resolve the conflicts in the next few days and make some additional tweaks to the code. 

Cheers @fwolter

**Comment by Cossey** [comment]
Rebase failed as its pulling in other commits since last year. Will close and re-open as new pull request.

**Pull request closed without merging**
