### PR TITLE
[transform] Use Java 17 features

### PR DESCRIPTION
**Pull request by holgerfriedrich**
instanceof matching and multiline strings

Similar to what we did in core a few month ago. Note that this breaks compatibilty to Java 11.

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks!
The build issues will probably be resolved after #15473 is merged.

**Review by clinique — APPROVED** [review]
LGTM

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by holgerfriedrich** [comment]
Jenkins did not complete, tried a rebase to current main. Sorry for doing a force push.

**Pull request merged**
