### PR TITLE
[netatmo] Room-Thing offline after restart

### LINKED ISSUE #13403: [Netatmo] Room-Thing offline after restart
## Expected Behavior
Room thing still online after restart of OH

## Current Behavior
If a room-action is defined, the room-thing is initially online. But after a restart of OH it stays offline.

## Possible Solution
Race condition initializing actionhandler before room-thing is initialized.

## Steps to Reproduce (for Bugs)
1. define a room-action (in my case in a .rules file)
2. restart OH

Log-Entries:
```
2022-09-14 14:58:10.726 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - Initializing Netatmo API bridge handler.
2022-09-14 14:58:10.766 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:home:f1a78f54ab:59cf54c5ae4763a9f18b4fdf
2022-09-14 14:58:10.770 [DEBUG] [.netatmo.internal.action.RoomActions] - Netatmo RoomActions service created
2022-09-14 14:58:10.771 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ModuleHandler of thing netatmo:room:aa:bb:cc tried accessing its bridge although the handler was already disposed.
2022-09-14 14:58:10.790 [DEBUG] [tatmo.internal.handler.DeviceHandler] - Initializing handler for bridge netatmo:plug:aa:bb:dd
2022-09-14 14:58:10.799 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:room:aa:bb:cc
2022-09-14 14:58:10.824 [DEBUG] [tatmo.internal.handler.ModuleHandler] - Initializing handler for thing netatmo:valve:a:b:dd:ee
```

If the roomaction is removed, cache-cleaned and OH restarted the problem is gone

## Your Environment
Observed in 
OH 3.3 release
OH 3.4 M2

### PR DESCRIPTION
**Pull request by clinique**
Correcting issue by late loading of the capability.
Resolves #13403 
Signed-off-by: clinique <gael@lhopital.org>

### CODE REVIEW

**Comment by clinique** [comment]
This solves also these warning raised at OH startup:
`
2022-09-30 08:50:33.091 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ModuleHandler of thing netatmo:room:home:59959297b4809d1aff8b4726:dining tried accessing its bridge although the handler was already disposed.
2022-09-30 08:50:33.130 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ModuleHandler of thing netatmo:room:home:59959297b4809d1aff8b4726:office tried accessing its bridge although the handler was already disposed.
2022-09-30 08:50:33.213 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ModuleHandler of thing netatmo:room:home:59959297b4809d1aff8b4726:parents tried accessing its bridge although the handler was already disposed.
2022-09-30 08:50:33.275 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ModuleHandler of thing netatmo:room:home:59959297b4809d1aff8b4726:kitchen tried accessing its bridge although the handler was already disposed.
`

**Comment by jlaur** [comment]
@clinique - if you change "solves issue" to "Resolves" in the PR description, the issue will be automatically linked and closed upon PR completion. :)

**Comment by clinique** [comment]
The work is in my pull request.

**Comment by clinique** [comment]
Main work is in my pull request.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@clinique ! you arre now avoiding to retry the API request in case the API limit is reached but you agree that this is not a fix for #13358  ?

**Comment by clinique** [comment]
> @clinique ! you arre now avoiding to retry the API request in case the API limit is reached but you agree that this is not a fix for #13358 ?

It should fix it. The thing being I did not find how many time we've got to wait when Api limit is reached.

**Comment by clinique** [comment]
I've got another issue to fix. From time to time API does not answer to camera pings (TimeoutException) and then the binding goes on error. I'll study this once this PR is available to see how it behaves.

**Comment by lolodomo** [comment]
> > @clinique ! you arre now avoiding to retry the API request in case the API limit is reached but you agree that this is not a fix for #13358 ?
> 
> It should fix it. The thing being I did not find how many time we've got to wait when Api limit is reached.

I see nothing new in that PR that could avoid reaching the API limit.
Please develop.

**Comment by clinique** [comment]
Sorry. Misunderstood. It not meant to avoid reaching API limit but rather handle it more gracefully

**Comment by lolodomo** [comment]
> Sorry. Misunderstood. It not meant to avoid reaching API limit but rather handle it more gracefully

So we agree.
The issue #13358 is more how to fix the binding to avoid reaching that limit.

**Pull request merged**
