### PR TITLE
[wemo] Separate handlers for Insight, Motion and Socket/Light Switch

### LINKED ISSUE #12105: [wemo] Refactoring WeMo Insight Switch parser
This issue described some possible next step after #12100.

Suggestions/plan:
- Create new subclasses from `WemoHandler` targeting each thing type: **Insight**, **Motion** and **Switch**/**Socket**.
- Make `WemoHandler` abstract.
- Extract relevant `onValueReceived` parts into each handler.
- For `WemoInsightHandler` method `onValueReceived()`: Extract parser to separate class and provide unit test for this. The unit test must cover variables **EnergyPerUnitCost** (currently not supported), **BinaryState** and **InsightParams**.

### Service variables
Example data to support in parser:
```
Received pair 'EnergyPerUnitCost':'4|2000|4' (service 'basicevent1') for thing 'wemo:insight:insight1'
Received pair 'BinaryState':'0|1642884254|0|0|0|1209600|13|0|0|0' (service 'basicevent1') for thing 'wemo:insight:insight1'
Received pair 'InsightParams':'1|1632573998|10371148|52746|1174820|1209600|39|26440|28068134|548930560|8000' (service 'insight1') for thing 'wemo:insight:insight2'
```

### PR DESCRIPTION
**Pull request by jlaur**
Fixes #12105

Signed-off-by: Jacob Laursen <jacob-github@vindvejr.dk>

Review notes:
- First commit contains **no logic/code changes**, just extraction/separation. Method `onValueReceived()` was copied into each handler and the parts not concerning that handler were removed.
- This is a work-in-progress, but code is ready to be merged at any time to reduce potential conflicts with other ongoing work and to keep review process manageable.
- Next steps will be some actual refactoring of `onValueReceived()`, see linked issue for details.

### CODE REVIEW

**Comment by hmerk** [comment]
@jlaur Could you please explain, why you started this while my #12114 is waiting for your review ? Why not first finish this, which is mainly a cut/copy/paste ?????

**Review by hmerk — APPROVED** [review]
LGTM

Should not be merged before #12114

**Comment by jlaur** [comment]
> Do I see it right, that this PR is based on the changes in #12114 ????

No, it's not. It's a continuation as what I intended to do with #12100 - extracted to #12105. I'll provide more context later, it seems that you did not receive my mail or PR comments, so some communication will need to be catched up.

**Comment by jlaur** [comment]
> Should not be merged before #12114

They do not conflict (currently) and are not related, so I do not agree.

**Comment by hmerk** [comment]
> They do not conflict (currently) and are not related, so I do not agree.

I am not convinced. My PR still includes WemoHandler which you removed and does not Include changes in WemoInsightHandler, WemoMotionHandler and WemoSocketHandler...

**Comment by jlaur** [comment]
> > They do not conflict (currently) and are not related, so I do not agree.
> 
> I am not convinced. My PR still includes WemoHandler which you removed and does not Include changes in WemoInsightHandler, WemoMotionHandler and WemoSocketHandler...

I did not remove `WemoHandler`. I made it `abstract` and removed the implementation of `onValueReceived` which is now implemented in subclasses. If you didn't touch the other handlers, then there's no Git conflict. The only Git conflict will be some surrounding lines, but this is easily resolvable and the merge order doesn't matter, it will need to be resolved either way.

**Comment by hmerk** [comment]
> I did not remove `WemoHandler`. I made it `abstract` and removed the implementation of `onValueReceived` which is now

Sorry, did not see the few green lines between all the red.
I have touched ALL handlers in my PR, including WemoBaseThingHandler...

**Comment by jlaur** [comment]
> I have touched ALL handlers in my PR, including WemoBaseThingHandler...

It doesn't matter as long as we didn't change the same lines. Git can merge automatically, only some lines "touching" each other will have to be manually resolved, but this is trivial.

**Comment by hmerk** [comment]
> It doesn't matter as long as we didn't change the same lines. Git can merge automatically, only some lines "touching" each other will have to be manually resolved, but this is trivial.

We will see....

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
