### PR TITLE
[wemo] Fix stability issues

### LINKED ISSUE #14162: [wemo] Stability issues affecting openHAB as a whole
For some time I've been suffering from system stability issues kicking in at most a week after starting openHAB. Usually after 3-4 days the system will become slower and will start to have timeouts now and then. Rule changes will load noticeable slower.

Recently the WeMo binding became my prime suspect for the reasons described below.

## Expected Behavior
The binding should work reliably continuously and not affect general openHAB performance.

## Current Behavior
As I've been trying to hunt down the problem, I started looking into threads:

```shell
threads --monitors --locks
```

One thing I noticed multiple times was this:

```
"upnp-main-493" Id=20857 in BLOCKED on lock=org.openhab.binding.wemo.internal.handler.WemoInsightHandler@1db766f
     owned by OH-thingHandler-2 Id=496
    at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:266)
    at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:287)
    at org.openhab.binding.wemo.internal.handler.WemoInsightHandler.onValueReceived(WemoInsightHandler.java:106)
    at org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback.eventReceived(UpnpIOServiceImpl.java:161)
    at org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222)
      - locked org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback@1bf6ff2
    at org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114)
      - locked org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
    at org.jupnp.protocol.sync.ReceivingEvent$2.run(ReceivingEvent.java:130)
    at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@fd708b

    Locked monitors: count = 2
      - org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback@1bf6ff2 locked at
          4 org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222)
      - org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c locked at
          5 org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114)
```

I then filtered by blocked threads:

```shell
threads --monitors --locks | grep BLOCKED
```

and saw something like this:

```
"OH-thingHandler-2" Id=496 in BLOCKED on lock=org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback@1bf6ff2
"OH-thingHandler-3" Id=497 in BLOCKED on lock=org.openhab.binding.wemo.internal.handler.WemoInsightHandler@1db766f
"OH-thingHandler-4" Id=503 in BLOCKED on lock=org.openhab.binding.hdpowerview.internal.HDPowerViewWebTargets@f7c432
"OH-thingHandler-5" Id=512 in BLOCKED on lock=org.openhab.binding.hdpowerview.internal.HDPowerViewWebTargets@f7c432
"upnp-main-493" Id=20857 in BLOCKED on lock=org.openhab.binding.wemo.internal.handler.WemoInsightHandler@1db766f
"upnp-main-495" Id=20889 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-496" Id=21120 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-497" Id=21121 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-498" Id=21122 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-499" Id=21123 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-500" Id=21124 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-501" Id=21125 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-502" Id=21128 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-503" Id=21134 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-504" Id=21135 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"upnp-main-505" Id=21136 in BLOCKED on lock=org.jupnp.controlpoint.SubscriptionCallback$2@1b9be4c
"OH-safeCall-917" Id=266519 in BLOCKED on lock=org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback@1bf6ff2
"OH-safeCall-918" Id=266522 in BLOCKED on lock=org.openhab.binding.wemo.internal.handler.WemoInsightHandler@1db766f
"OH-safeCall-919" Id=266536 in BLOCKED on lock=org.openhab.binding.wemo.internal.handler.WemoInsightHandler@1db766f
"OH-safeCall-920" Id=266539 in BLOCKED on lock=org.openhab.binding.wemo.internal.handler.WemoInsightHandler@1db766f
"OH-safeCall-921" Id=267012 in BLOCKED on lock=org.openhab.core.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback@1bf6ff2
"pipe-grep BLOCKED" Id=267121 in TIMED_WAITING on lock=java.io.PipedInputStream@91a93c
```

This clearly seems to indicate a problem within the WeMo binding.

## Possible Solution

I probably did this to myself (and others - sorry) in one of these pull requests:
- #12148
- #12648

The first one is my prime candidate, but the second one has also been on my mind for some time, because I was unable at the time to implement a more fine-grained solution.

I have found by testing (and comparing with this SONOS binding) that it's not needed to manually renew UPnP subscription like it's done in the current implementation as well as in the implementation it replaced.

I'm currently testing a version having removed both subscription renewal and UPnP rediscovery. The missing rediscovery will bring back an old problem, so if the test turns out positive, I'll try to put that back in. Additionally I've added some locks which are not included in the version I'm currently testing. So I'm monitoring and will need to finetune the final bugfix.

Even though I'm trying to simplify the code, I'm still not aware of the actual root cause.

## Steps to Reproduce
Have one WeMo Insight device turned on all the time and wait a week.

### PR DESCRIPTION
**Pull request by jlaur**
Fixes #14162.

Tested on my system for a few weeks now and didn't see any blocked threads since. Also my system in general is now stable and responsive after running for more than a week without restarts.

JARs for testing:
- [org.openhab.binding.wemo-3.4.2-SNAPSHOT.jar](https://drive.google.com/file/d/1q_RcE8JnqDQeJI6c5RkGcDZuP8Uyo_Qc/view?usp=sharing)
- [org.openhab.binding.wemo-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/1ASIeKW1wopgw0Ac9DQiRwyY1yi-cUgEG/view?usp=sharing)

### CODE REVIEW

**Comment by jlaur** [comment]
@hmerk - I don't remember if I've asked you before, sorry: Do you know how to run the integrations tests locally? With:

```shell
mvn -pl :org.openhab.binding.wemo.tests clean install -DwithResolver=true
```

I currently end up with:
```
[INFO] Resolving openhab-addons\itests\org.openhab.binding.wemo.tests\itest.bndrun:
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ? osgi.identity: (osgi.identity=org.openhab.core.binding.xml)
    [org.openhab.binding.wemo.tests version=4.0.0.202301132049 type=osgi.fragment]
      ? osgi.wiring.package: (osgi.wiring.package=org.openhab.core.common.registry)
```

**Comment by hmerk** [comment]
@jlaur Sorry, don‘t know about the tests.
@J-N-K can you help?

**Comment by jlaur** [comment]
@openhab/add-ons-maintainers - this should be considered for being cherry-picked into 3.4.x.

**Review by hmerk — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
@lolodomo - can you have a look at this?

**Review by lolodomo — APPROVED** [review]
LGTM, thank you.
PS: I checked the Sonos binding and a lock object is also used ;)

**Comment by jlaur** [comment]
@lolodomo - thanks for the review. Can I cherry-pick into 3.4.x?

**Comment by jlaur** [comment]
> PS: I checked the Sonos binding and a lock object is also used ;)

I also compared with the Sonos implementation. I basically did three things:
- Removed the unneeded renewal complexity.
- Added locking.
- Fixed a small problem in core.

At least it's working really well on my system now, and it's still stable and responsive after weeks. Very new situation for me. 🙂

**Comment by jaywiseman1971** [comment]
Is the top post the latest version of the JAR if not, can I get a link to the JAR? 

I have 37 WeMo's in my setup that I liked to test. I'm stilling using Han's version from 1/2022.

Best, Jay

**Comment by jlaur** [comment]
@jaywiseman1971 - yes, you can use one of the provided JAR's mentioned in the description. They were built before the last two commits, but this should not matter much. Tomorrow there will be a fully up-to-date 4.0 snapshot version.

**Comment by jaywiseman1971** [comment]
> @jaywiseman1971 - yes, you can use one of the provided JAR's mentioned in the description. They were built before the last two commits, but this should not matter much. Tomorrow there will be a fully up-to-date 4.0 snapshot version.

Thank you!  So far so good!  Will report back.  FYI, I'm running OH 3.2.

Best, Jay

**Comment by lolodomo** [comment]
> @lolodomo - thanks for the review. Can I cherry-pick into 3.4.x?

Would make sense. 
I have not in mind other concurrent PR merged for this binding.

**Pull request merged**
