### PR TITLE
[touchwand] Add port configuration to websocket

### PR DESCRIPTION
**Pull request by roieg**
# Added port parameter to websocket URI .
The optional port parameter applied to websocket connection as well allow the binding to connect also to a non default port

### CODE REVIEW

**Comment by jlaur** [comment]
@roieg - is it intentionally marked as draft?

**Comment by roieg** [comment]
> @roieg - is it intentionally marked as draft?

yes , wanted to make sure all the checks are passed before submitting it to review.
Since this is the case I move it from draft

**Comment by jlaur** [comment]
@roieg - only one question: The `port` parameter is documented as "Management port (default 80)". Is it always the same port for web socket connection?

**Comment by roieg** [comment]
> 

yes it is , in the current touchwand hub implementation the API port and the WebSocket port are the same  
the WebSocket URI under **/async** in the API root URI

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
