### PR TITLE
[icloud] Fix NPE in AccountBridgeHandler

### PR DESCRIPTION
**Pull request by radokristof**
Hope this makes sense.
I got this NPE few days ago:

```
2020-02-29 22:10:53.325 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.icloud.internal.handler.ICloudAccountBridgeHandler.refreshData(ICloudAccountBridgeHandler.java:170) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

So I think only `iCloudData` can be `null` here.
This and every non-catch Exceptions interrupts the refreshData thread, meaning that the binding won't refresh the data automatically. 
Or should we somehow restart the threads again when something causes it to interrupt?

### CODE REVIEW

**Comment by J-N-K** [comment]
Makes sense. But it also means that the methos signature https://github.com/openhab/openhab-addons/blob/4ad6329abacfd8d77733dd59ff5a50e62c0639f5/bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationParser.java#L32 needs to be changed to  

```
public @Nullable ICloudAccountDataResponse parse(String json) throws JsonSyntaxException
```

This might result in some more errors where the (wrong) non-null assumption is used. Please have an eye on this.

**Comment by radokristof** [comment]
@J-N-K yes you are right. Previously when I worked on the binding, I assumed that JsonSyntaxException is thrown every time when the JSON is incorrect or null.
But now looking at the docs:

> an object of type T from the json. Returns null if json is null.

However the json is checked against `null` before, so it can't be `null` there.
I'm a little bit confused now...

**Comment by J-N-K** [comment]
Seems to be this issue: https://github.com/google/gson/issues/540. See also https://stackoverflow.com/questions/42396634/prevent-gson-from-returning-null-when-deserializing-empty-strings.

IMO the documentation for `fromJson` is wrong.

**Comment by J-N-K** [comment]
So the null-check could be omitted and the method

```
public @Nullable ICloudAccountDataResponse parse(@Nullable String json) throws JsonSyntaxException
```

**Comment by radokristof** [comment]
@J-N-K Thanks! Already pushed a commit that contains that fix.

Thanks for your help!

**Pull request merged**
