### PR TITLE
[Wemo] add @jlaur as code-owner

### PR DESCRIPTION
**Pull request by hmerk**
Signed-off-by: Hans-Jörg Merk <github@hmerk.de>

### CODE REVIEW

**Review by jlaur — APPROVED** [review]
Thanks.

**Comment by hmerk** [comment]
@jlaur Don‘ think such a change needs to be added to a milestone

**Comment by jlaur** [comment]
@hmerk - you are probably right. When not having any labels it won't be mentioned in the change log anyway, but probably safer/more correct not to add milestone.

**Comment by kaikreuzer** [comment]
@jlaur No, as we had discussed, any PR should be tagged with a milestone.

**Comment by jlaur** [comment]
> @jlaur No, as we had discussed, any PR should be tagged with a milestone.

Thanks for clarifying.

**Pull request merged**
