### PR TITLE
Switched persistence services from Date to ZonedDateTime

### PR DESCRIPTION
**Pull request by kaikreuzer**
Related to https://github.com/openhab/openhab-core/pull/1588

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This will fix https://ci.openhab.org/job/openHAB-Addons/35/

**Comment by wborn** [comment]
That's awesome! It's a good to try to minimize the use of Date/Calendar as much as possible nowadays. Would it also be possible to fix all the `FilterCriteria` deprecations by switching from the Date to ZonedDateTime based methods?

deprecations

**Comment by kaikreuzer** [comment]
If you merge this PR in the next 10 minutes, I promise to do a follow-up PR for the deprecations :-)

**Comment by kaikreuzer** [comment]
That was quick ;-)

**Pull request merged**
