### PR TITLE
[boschshc] Support for Compact Smart Plugs (#13528)

### LINKED ISSUE #13528: [boschshc] Support for Compact Smart Plugs
Compact smart plugs are not supported yet by the Bosch Smart Home binding.

Product links (German and UK version):
- https://www.bosch-smarthome.com/de/de/produkte/geraete/zwischenstecker-kompakt/
- https://www.bosch-smarthome.com/uk/en/products/devices/plug-compact/

I'm happy to contribute the code and created this issue so you guys know someone is working on this 👍

### PR DESCRIPTION
**Pull request by david-pace**
* add thing definition with ID "smart-plug-compact"
* add constant for thing type UID
* extract abstract implementation for devices with power switch and energy monitoring
* let in-wall switch handler and smart plug handler extend the abstract implementation
* register new handler
* add method with boolean parameter to fetch initial state actively
* make BoschSHCDeviceHandler abstract
* add documentation
* add unit tests

closes #13528

Signed-off-by: David Pace <dev@davidpace.de>

### CODE REVIEW

**Comment by GerdZanker** [comment]
Hello @david-pace , thank you for your pull request! I want to review and test your changes until end of the week.

**Comment by david-pace** [comment]
Thanks @GerdZanker, there is no hurry 👍

**Review by GerdZanker — APPROVED** [review]

**Comment by GerdZanker** [comment]
Thanks a lot @david-pace for your contribution, especially your new tests for devices.
Binding Code tests in my environment and new item works as expected.

**Review by jlaur — APPROVED** [review]
Many thanks!

**Pull request merged**
