### PR TITLE
[voicerss] Fix service-id in addon.xml

### PR DESCRIPTION
**Pull request by J-N-K**
@lolodomo FYI

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
Thank you.

**Comment by lolodomo** [comment]
They are wrong in all voice services.

**Comment by J-N-K** [comment]
I checked and rustpotterks defines `SERVICE_PID = "org.openhab." + SERVICE_CATEGORY + "." + SERVICE_ID`, so `org.openhab.voice.rustpotterks` and that is also in the addon.xml.

**Comment by lolodomo** [comment]
It might be wrong in all these cases:
```
org.openhab.io.neeo/src/main/resources/OH-INF/addon/addon.xml:  <service-id>org.openhab.io.neeo.NeeoService</service-id>

org.openhab.voice.actiontemplatehli/src/main/resources/OH-INF/addon/addon.xml:  <service-id>org.openhab.voice.actiontemplatehli</service-id>
org.openhab.voice.googlestt/src/main/resources/OH-INF/addon/addon.xml:  <service-id>org.openhab.voice.googlestt</service-id>
org.openhab.voice.googletts/src/main/resources/OH-INF/addon/addon.xml:  <service-id>org.openhab.voice.googletts</service-id>
org.openhab.voice.mimictts/src/main/resources/OH-INF/addon/addon.xml:   <service-id>org.openhab.voice.mimictts</service-id>
org.openhab.voice.pollytts/src/main/resources/OH-INF/addon/addon.xml:   <service-id>org.openhab.voice.pollytts</service-id>
org.openhab.voice.porcupineks/src/main/resources/OH-INF/addon/addon.xml:        <service-id>org.openhab.voice.procupineks</service-id>
org.openhab.voice.rustpotterks/src/main/resources/OH-INF/addon/addon.xml:       <service-id>org.openhab.voice.rustpotterks</service-id>
org.openhab.voice.voicerss/src/main/resources/OH-INF/addon/addon.xml:   <service-id>org.openhab.voice.voicerss</service-id>
org.openhab.voice.voskstt/src/main/resources/OH-INF/addon/addon.xml:    <service-id>org.openhab.voice.voskstt</service-id>
org.openhab.voice.watsonstt/src/main/resources/OH-INF/addon/addon.xml:  <service-id>org.openhab.voice.watsonstt</service-id>
```

And this one is surprising:
```
org.openhab.binding.upb/src/main/resources/OH-INF/addon/addon.xml:      <service-id>org.openhab.upb</service-id>
```

**Comment by lolodomo** [comment]
> rustpotterks defines `SERVICE_PID `

Ok, maybe we should change that to make all services consistent. But not urgent at all.

**Comment by J-N-K** [comment]
Changing it will erase all existing configurations for that.

**Comment by J-N-K** [comment]
UPB looks like a mistake, it does not use that PID in code.

**Comment by J-N-K** [comment]
Neeo, Google STT and Google TTS are also fine. I didn't check the others.

**Pull request merged**
