### PR TITLE
[wemo] Refactor duplicated code

### LINKED ISSUE #12100: [wemo] Refactoring code duplication
When reviewing #12001 it turned out that some technical debt needs to be paid for this binding in order to progress without too much pain. The biggest issue is the code duplication between handlers which required the contributor to spend more time on duplicate work and me to spend more time on the review. While handling some regressions and looking deeper into the code some other improvement opportunities was revealed.

Phase 1:
- Remove code duplication between handlers by introducing a new `WemoBaseThingHandler` providing common logic. For example, `getHost()` is duplicated in all handlers.
- Delete class `AbstractWemoHandler` which provides no value. Move `WemoHttpCall` instance to `WemoBaseThingHandler`.
- Move service helper methods to `WemoBaseThingHandler` (for example `isUpnpDeviceRegistered()`).

Phase 2:
- Refactor UPnP subscription handling and centralize it in `WemoBaseThingHandler`.
- Remove or fix `subscriptionState` as it is unused/incorrectly implemented: Status (success/failure) is not read anywhere, so calling `addSubscription()` after `onServiceSubscribed()` has received failure will not try to subscribe again. Also, even without any confirmation from `onServiceSubscribed()`, subscription will be cached as successful.
- Fix bug in `handleCommand` in all handlers: After catching exception marking thing **OFFLINE**, it will immediately be marked as **ONLINE** in next line.

Phase 3:
- Reuse UDN configuration parameter in XML files.
- Fix already configured devices showing up in inbox (file-based configuration).

Phase 4:
- Consolidate host initialization/caching in `WemoBaseThingHandler`.
- Simplify usage of `getWemoURL` and remove redundant error handling.

See also related: #12105.

### PR DESCRIPTION
**Pull request by jlaur**
Signed-off-by: Jacob Laursen <jacob-github@vindvejr.dk>

Fixes #12100 

Changes:
- `getHost()`, `getUDN()` and `isUpnpDeviceRegistered()` have been extracted to a common base class for all handlers.
- `AbstractWemoHandler` has been deleted as it served no purpose other than containing a `WemoHttpCall` instance, but actually each handler held their own instances. This instance has been moved to `WemoBaseThingHandler` and handlers have been refactored to use it.

### CODE REVIEW

**Comment by lolodomo** [comment]
Why not just adding grtUDN and getHost in AbstractWemoHandler?

**Comment by jlaur** [comment]
> Why not just adding grtUDN and getHost in AbstractWemoHandler?

This is an early draft. When preparing first commit I didn't realize that `AbstractWemoHandler` made absolutely no sense. It added a `WemoHttpCall` instance, but it was unused - each handler held their own private instances. So as first step I refactored handlers to use this instance, but left the class as it's abstract and my idea was to provide a concrete base class with shared logic. In next commit I plan to simply delete `AbstractWemoHandler` and move the `WemoHttpCall` instance to `WemoBaseThingHandler`.

**Comment by hmerk** [comment]
> When preparing first commit I didn't realize that `AbstractWemoHandler` made absolutely no sense.

To be honest, I never understood, why this was added years ago.

**Comment by jlaur** [comment]
> In next commit I plan to simply delete `AbstractWemoHandler` and move the `WemoHttpCall` instance to `WemoBaseThingHandler`.

Done.

**Comment by hmerk** [comment]
@jlaur Please see my email with attachement.
Already did a lot of this….

**Comment by jlaur** [comment]
> Already did a lot of this….

Okay, I've published this PR for possibility of quick review and avoiding conflicts when doing further work. Ready for review. New issue created for next step I would like to do: #12105

**Review by hmerk — APPROVED** [review]
LGTM

**Comment by hmerk** [comment]
> Ready for review. New issue created for next step I would like to do: #12105

In my proposal sent to you, I already refactored addSubscription and removeSubscription to be moved to WemoBaseThingHandler…

**Comment by hmerk** [comment]
@jlaur What about first finish moving shared methods to WemoBaseThingHandler ?
I think initialise() dispose() poll() addSubscription and removeSubscription can be moved without much effort…

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by hmerk** [comment]
> They are a bit more tricky. Phase one, this PR, was the easy part with very low risk. Some common methods being called by all/most handlers have simply been moved to the super class. Still, they are explicitly called by each handler.

Apart from the WemoBridgeHandler andWemoLighthandler, initialize() and dispose() are identical in other handler classes. One or two classes don‘t use subscription, so overriden empty add/remove methods can be shared.

**Pull request merged**
