### PR TITLE
[netatmo] Only log stack traces to openhab.log if debug is enabled

### PR DESCRIPTION
**Pull request by robnielsen**
This fixes https://github.com/openhab/openhab-addons/issues/9405 and https://github.com/openhab/openhab-addons/issues/9406

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM for netatmo

**Review by kaikreuzer — APPROVED** [review]

**Comment by kaikreuzer** [comment]
This is low risk to merge and helps to keep the logs clean, so merging it for 3.0.

**Comment by robnielsen** [comment]
@kaikreuzer, this also fixes the logging for openhabcloud

**Comment by kaikreuzer** [comment]
@robnielsen I know, but I can only mention one add-on in the title.
Better create separate PRs for different add-ons in future.-

**Pull request merged**
