### PR TITLE
[sonnen] Initial contribution of new binding for solar battery 

### PR DESCRIPTION
**Pull request by chingon007**
Initial contribution for a new binding which communicates with a solar battery from sonnen. It is a simple read only binding which just reads the values of the solar battery. 

I mentioned my initiative in the forum here: https://community.openhab.org/t/new-binding-sonnen-battery/129178

Regards
Chingon

### CODE REVIEW

**Comment by lolodomo** [comment]
Please fix the conflict in bundles/pom.xml
I will then review your binding.

**Comment by chingon007** [comment]
Fixed the Merge conflict. Ready for Review

**Comment by lolodomo** [comment]
Look at the diffs for the pom file, you have added many and many blank lines.
You should find only one line added.

**Comment by lolodomo** [comment]
The good point is that as soon as you fixed that problem with the pom file, your PR size will really reduce a lot.

**Comment by lolodomo** [comment]
Just take the pom file from the main branch, copy it in your branch, add only one line and that's all.

**Comment by chingon007** [comment]
Shit, seemed, that I screwed something up with git. @lolodomo: Are you able to fix it?

**Comment by lolodomo** [comment]
Can you backup your binding directory and start again a new clean branch and finally commit your work with a proper sign-off?

**Comment by lolodomo** [comment]
DCO is red and build failed.

Try from scratch. The problem could be that you used your main branch...

First backup your files: CODEOWNERS, bom/openhab-addons/pom.xml and your directory bundles/org.openhab.binding.sonnen outside git.

Then I am not sure what is the proper way for you to make your main branch in sync with the remote main branch. If you have nothing else pending, just remove your git repository and create it agin.

Then make sure your main branch is uptodate: git pull origin main

Then create a branch for developing your binding: git checkout -b sonnen

Then resore your backuped file

Then commit everything, providing a proper "Signed-off-by" in your commit.

Then push your work in Github: git push origin sonnen

Finally in GitHub, create a new PR from this new branch and close the current one.

**Comment by lolodomo** [comment]
After a quick search on the web, the commands to restore a proper main branch are:
git fetch origin
git reset --hard origin/master

**Comment by daMihe** [comment]
As @lolodomo wrote: Please fix your history. Here is a guide with images: https://community.openhab.org/t/rebase-your-code-or-how-to-fix-your-git-history-before-requesting-a-pull/129358

**Comment by chingon007** [comment]
I will do so and open another clean pull request.

**Pull request closed without merging**
