### PR TITLE
[amazonechocontrol] remove deprecated discovery interfaces

### PR DESCRIPTION
**Pull request by J-N-K**
See https://github.com/openhab/openhab-addons/pull/7969#issuecomment-655912453

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
@cweitkamp this should fix the OH3 build again.

**Comment by cweitkamp** [comment]
There is a second class impending and using them: `AmazonEchoDiscovery`.

**Comment by cpmeister** [comment]
> There is a second class impending and using them: `AmazonEchoDiscovery`.

@J-N-K Can you make this change as well in this PR?

**Comment by J-N-K** [comment]
Ah. Didn't look at that file. It seems that the changes (which were done before) have been reverted accidentally in #7969.

**Pull request merged**
