### PR TITLE
[hdpowerview] Restructure DTO classes

### PR DESCRIPTION
**Pull request by jlaur**
This PR picks up on small cleanup suggested in #13352:
- Nested DTO classes have been extracted into separate classes.
- Directory `api` has been renamed to `dto`.
- Test classes are moved into `internal` to conform with related classes being tested.

Related to: #12678

### CODE REVIEW

**Comment by jlaur** [comment]
@andrewfg - in order to avoid conflicts when rebasing #13355 towards this after a merge, in your branch beforehand:
- Rename `api` to `dto`.
- Move all tests classes into subdirectory `internal`.

**Comment by jlaur** [comment]
> This change causes the HDPowerViewJUnitTests now to fail. The reason is that the test JSON files are located in a relative path from the module path.

I'll have a look at this in the evening, but didn't notice it locally or on build server. Where do you see this?

https://ci.openhab.org/job/PR-openHAB-Addons/12015/console

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.hdpowerview.OnlineCommunicationTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.059 s - in org.openhab.binding.hdpowerview.OnlineCommunicationTest
[INFO] Running org.openhab.binding.hdpowerview.SceneChannelBuilderTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.766 s - in org.openhab.binding.hdpowerview.SceneChannelBuilderTest
[INFO] Running org.openhab.binding.hdpowerview.HDPowerViewJUnitTests
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.394 s - in org.openhab.binding.hdpowerview.HDPowerViewJUnitTests
[INFO] Running org.openhab.binding.hdpowerview.SceneGroupChannelBuilderTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 s - in org.openhab.binding.hdpowerview.SceneGroupChannelBuilderTest
[INFO] Running org.openhab.binding.hdpowerview.AutomationChannelBuilderTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.069 s - in org.openhab.binding.hdpowerview.AutomationChannelBuilderTest
[INFO] Running org.openhab.binding.hdpowerview.ShadePositionTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 s - in org.openhab.binding.hdpowerview.ShadePositionTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 45, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by jlaur** [comment]
> I'll have a look at this in the evening, but didn't notice it locally or on build server. Where do you see this?

I don't know how it was able to build and run tests, but I found inconsistencies caused by unsaved changes locally (from refactoring in VS Code). Should be fixed now.

**Review by andrewfg — APPROVED** [review]
LGTM

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@jlaur : I assume you don't want to see that in the release notes ?

**Comment by jlaur** [comment]
> @jlaur : I assume you don't want to see that in the release notes ?

Correct, this is just some renamed files and namespaces without any user impact.

**Comment by andrewfg** [comment]
@jlaur there are still some merge conflicts with the naming adopted in my Gen 3 PR, but I will adapt that PR again to match this one.

**Pull request merged**
