### PR TITLE
[folderwatcher] Improve Exception handling

### PR DESCRIPTION
**Pull request by lsiepel**
This mainly fixes AvoidThrowingRawExceptionTypes SAT warnings. 
No functional change other then that it should catch more exception variants gracefully to thingstatus.

### CODE REVIEW

**Comment by lsiepel** [comment]
To the reviewer; I was not sure about the `ThingStatusDetail.HANDLER_INITIALIZING_ERROR`, maybe another state is better. Please advice if that should change.

**Review by goopilot — APPROVED** [review]
Thanks for doing this, looks good to me.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@lsiepel : there is a file conflict to resolve first.

**Comment by lsiepel** [comment]
> @lsiepel : there is a file conflict to resolve first.

Fixed.

**Pull request merged**
