### PR TITLE
[tradfri] TradfriDeviceData.java, remove DEVICE from payload

### LINKED ISSUE #11185: [tradfri] Plug does not change state
## Expected Behavior

To power Tradfri Plug following payload should be sent to gateway
```json
{"3312":[{"5850":1}]}
```

## Current Behavior

The OpenHab sends additional field `"3":null` and as result the command is ignored
```
2021-09-01 12:29:53.564 [DEBUG] [internal.handler.TradfriThingHandler] - Sending payload: {"3312":[{"5850":1}],"3":null}
2021-09-01 12:29:53.587 [DEBUG] [g.tradfri.internal.TradfriCoapClient] - CoAP PUT request
uri: coaps://192.168.0.37:5684/15001/65556
payload: {"3312":[{"5850":1}],"3":null}
2021-09-01 12:29:53.602 [DEBUG] [.tradfri.internal.TradfriCoapHandler] - CoAP response
options: null
payload:
2021-09-01 12:29:55.072 [DEBUG] [internal.handler.TradfriThingHandler] - Sending payload: {"3312":[{"5850":0}],"3":null}
2021-09-01 12:29:55.074 [DEBUG] [g.tradfri.internal.TradfriCoapClient] - CoAP PUT request
uri: coaps://192.168.0.37:5684/15001/65556
payload: {"3312":[{"5850":0}],"3":null}
2021-09-01 12:29:55.089 [DEBUG] [.tradfri.internal.TradfriCoapHandler] - CoAP response
options: null
payload:
```

## Possible Solution

remove `"3":null` from payload
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: `openhab-3.1.0-1.noarch`
* Operating System and version: CentOS Linux release 8.1.1911 (Core)

### PR DESCRIPTION
**Pull request by qermit**
Fixes #11185

### CODE REVIEW

**Comment by lolodomo** [comment]
Fix #11185

**Comment by kaikreuzer** [comment]
As this class seems to be used throughout all devices: Can we be sure that this line isn't required for any of the other devices?
Please also update the PR title to something speaking as it will appear in the release notes. Thanks!

**Comment by isrjo** [comment]
I have verified the patch against devices (bulbs) with ID 0220, 0100 as well as the plug with ID 0010. They all work fine with this patch, whereas without they are no longer controllable from OH. I'm under the impression starting with IKEA-GW firmware 1.16.26 (relased October 27th) the extra null field sent, will invalidate the whole payload and therefor dropped by the gw. 

I believe the current state of ikea trådfri support via this binding and is to be considered broken.

**Comment by fwolter** [comment]
@soenkekueper reported that OH is still working with the gateway version 1.16.26. Are you sure the device attribute is the originator of this problem?

**Comment by soenkekueper** [comment]
Hey,

i can't confirm this, the current version of the binding is working fine here.
Here are my version details:

```
openhabVersion:
runtimeInfo:
  version: 3.1.0
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.10.63-v7l+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 109821456
  totalMemory: 194772992
bindings:
  - ahawastecollection
  - astro
  - avmfritz
  - denonmarantz
  - deutschebahn
  - exec
  - heos
  - mqtt
  - netatmo
  - network
  - ntp
  - tankerkoenig
  - tradfri
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: light
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: 8
    hardwareConcurrency: 8
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 2560
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/96.0.4664.93 Safari/537.36
timestamp: 2021-12-11T14:09:20.490Z
```

Thing properties:
Gateway:
gateway

Plug
steckdose

lightbulb:
lampe

**Comment by jlaur** [comment]
@qermit - is this still a problem in openHAB 3.2/3.3 when running latest version of the TRÅDFRI firmware? From what I have been able to read from the forum thread, this PR and the linked issue it seems the problem was introduced in FW 1.16.26, but also there are some indications that it was later fixed? In this case we could close this PR as well as the linked issue, openhab/openhab-addons#11185.

**Comment by lolodomo** [comment]
Let's close that PR as there is no more activity since almost one year, the last messages seem to indicate the problem is solved and that PR is no more required.

**Pull request closed without merging**
