### PR TITLE
Fix findbugs instanceof pattern matching

### PR DESCRIPTION
**Pull request by J-N-K**
Findbugs can't properly handle `if (foo instanceof Bar bar)`. The same suppression is done in core.

Signed-off-by: Jan N. Klug <github@klug.nrw>

### CODE REVIEW

**Comment by jlaur** [comment]
@J-N-K - thanks! So it fixes this problem, right?

https://github.com/jlaur/openhab-addons/blob/7b8c75b640207302d771d33ac1bdb5289178f63a/bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/retry/RetryPolicyFactory.java#L43-L46

**Comment by J-N-K** [comment]
Exactly.

**Comment by J-N-K** [comment]
Looks like there are more issues. I'll have a look.

**Comment by J-N-K** [comment]
I really don't understand why these additional suppressions (from core) are needed, but it compiles fine with them and fails with a ton of false-positives if they are missing.

**Review by jlaur — APPROVED** [review]
Thanks for taking care of this.

**Pull request merged**
