### PR TITLE
[bluetooth.ruuvitag] minor checkstyle

### PR DESCRIPTION
**Pull request by lsiepel**
Signed-off-by: Leo Siepel <leosiepel@gmail.com>

Very minor checkstyle.
Part of multiple PR's for bluetooth bundles.

### CODE REVIEW

**Comment by lsiepel** [comment]
Two low warning empty if statements are left. Would like ot get those fixed too, but they contain notes. Preference? Or leave it as is.

**Review by ssalonen — APPROVED** [review]

**Comment by ssalonen** [comment]
> Two low warning empty if statements are left. Would like ot get those fixed too, but they contain notes. Preference? Or leave it as is.

Can you link the code here please?

**Comment by lsiepel** [comment]
> > Two low warning empty if statements are left. Would like ot get those fixed too, but they contain notes. Preference? Or leave it as is.
> 
> Can you link the code here please?

org.openhab.binding.bluetooth.ruuvitag.internal.RuuviTagHandler.java lines 158 and 168

```
if (atLeastOneRuuviFieldPresent) {
HERE 158 ==>                      // In practice, updated to ONLINE by super.onScanRecordReceived already, based on RSSI value
                    } else {
                        updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
                                "Received Ruuvi Tag data but no fields could be parsed");
                    }
                } else {
                    updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
                            "Received bluetooth data which could not be parsed to any known Ruuvi Tag data formats");
                }
            } else {
HERE 168  ==>                // Received Bluetooth scan with no manufacturer data
                // This happens -- we ignore this silently.
            }
```

**Comment by ssalonen** [comment]
Thanks! Is there a way to ignore the warning?

**Comment by lsiepel** [comment]
> Thanks! Is there a way to ignore the warning?

As far as i know only by removing the empty block. We can leave it as is.

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
