### PR TITLE
[wemo] Improve GENA subscription reliability and error handling

### PR DESCRIPTION
**Pull request by jlaur**
Signed-off-by: Jacob Laursen <jacob-github@vindvejr.dk>

Continuation of #12101:
- Service subscription consolidated in base class (removing a lot of duplicate code).
- Fix status wrongly set to **ONLINE** when exception is thrown.
- Fix exception thrown from `handleCommand()` - set status **OFFLINE** instead.
- Rework error handling for `WemoHttpCall`: Duplicated logging moved inside and throws exception rather than returning null.
- Decrease log level from **error** to **warning** for communication errors and avoid warning every minute while a device is offline.
- Improve reliability of GENA events by renewing subscriptions automatically.

Review notes:
- Reading commit by commit might be helpful to understand the process/distinct steps.

### CODE REVIEW

**Comment by hmerk** [comment]
Thanks @jlaur, this looks really good at first quick sight.
Only one thing I don‘t agree, commit 7d073f6 - removing subscription cache.
Subscroption duration is 600s per default, refresh cycle is 60s. With your proposed change, we try to subscribe to events ever 60s, even there are registered subscriptions.
I don‘t know how the Wemo devices will handle this on the long run, but I would not want to try…

**Comment by jlaur** [comment]
> Subscroption duration is 600s per default, refresh cycle is 60s. With your proposed change, we try to subscribe to events ever 60s, even there are registered subscriptions.

Thanks for this comment, I missed this logic. I'll rework it! I don't quite follow the original implementation, though. It seems to me that there is no resubscription performed? `addSubscription()` will be called every minute, but if subscription is already cached, it will not subscribe again.

**Comment by hmerk** [comment]
> It seems to me that there is no resubscription performed?

Indeed, unfortunately, resubsciption is not implemented in org.openhab.core.io.transport.upnp.

**Comment by jlaur** [comment]
> Indeed, unfortunately, resubsciption is not implemented in org.openhab.core.io.transport.upnp.

So summing up:
- Original implementation: Cache prevents any kind of resubscription and caches before getting confirmation about subscription. Do you know if this in practice means that we stop receiving events 10 minutes after binding starts? I'll test this to verify.
- Current PR implementation: Resubscription is too frequent (every minute).

After some tests I'll implement a proper subscription renewal mechanism.

**Comment by hmerk** [comment]
No, cache prevents adding a new subscription as long as there is a valid subscription. So we would loose events just for about a minute. It is the same implementation as in Sonos binding.

**Comment by jlaur** [comment]
> No, cache prevents adding a new subscription as long as there is a valid subscription. So we would loose events just for about a minute. It is the same implementation as in Sonos binding.

But cache doesn't know if subscription is still valid, it just caches the service name once and keeps it? At least if participant is still registered.

**Comment by hmerk** [comment]
You are right, so there must be some logic within JUPnP to resubscribe, as I did not see loosing subscriptions after 10 minutes.
What about adding a cache which gets invalid after DEFAULT-SUBSCRIPTION-DURATION and then add a new subscription ?

**Comment by jlaur** [comment]
> What about adding a cache which gets invalid after DEFAULT-SUBSCRIPTION-DURATION and then add a new subscription ?

That's similar to what I had in mind with:

> After some tests I'll implement a proper subscription renewal mechanism.

I have pushed a draft implementation of this and is currently testing it. I was not able to reproduce any loss of events (with original code) after subscription supposedly expires:

```
    /**
     * Subscribe to a GENA subscription
     * 
     * @param participant the participant to the subscription is for
     * @param serviceID the UPNP service we want to subscribe to
     * @param duration the duration of the subscription
     */
    public void addSubscription(UpnpIOParticipant participant, String serviceID, int duration);
```

I also double-checked that duration is in seconds since not documented here. So my implementation might be a theoretic one as duration might have some other meaning, or if there is renewal implemented elsewhere. I never missed events from my WeMo Insight, but it might have gone unnoticed since there is also polling of values each minute.

**Review by hmerk — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
JAR here: https://drive.google.com/file/d/12hX52zTN53LEUra6rCiwwI-NNy4Gw6ki/view?usp=sharing

@jaywiseman1971 - if you would still have some nerve for this, this one would be nice to have tested with a broader equipment selection.

**Comment by jlaur** [comment]
@hmerk - I pushed two new commits after testing handling of Insight device being turned off and on again as well as being turned off initially when binding is started, then turned on. I found some issues which are now also addressed.

**Comment by jaywiseman1971** [comment]
> JAR here: https://drive.google.com/file/d/12hX52zTN53LEUra6rCiwwI-NNy4Gw6ki/view?usp=sharing
> 
> @jaywiseman1971 - if you would still have some nerve for this, this one would be nice to have tested with a broader equipment selection.

Once it becomes more unchanged for a while, I will test and provide feedback.  I get all the emails on this thread daily so I'm aware of all the massive changes.  I just can't be the first one to test all these changes in my PRO system.

**Comment by jlaur** [comment]
> Once it becomes more unchanged for a while, I will test and provide feedback. I get all the emails on this thread daily so I'm aware of all the massive changes. I just can't be the first one to test all these changes in my PRO system.

That's fine, I'll not bug you anymore by tagging you, I think I understand your standpoint by now. :-) Everything is already tested with Insight, for other devices I hope that no regressions are introduced by mistake, since I can't test.

**Review by hmerk — APPROVED** [review]

**Comment by hmerk** [comment]
@jlaur Could you please change Line 495 in WemoDimmerHandler from
logger.trace("New attribute brewed '{}' received", dateTimeState);
to
logger.trace("New dateTime attribute '{}' received", dateTimeState);

**Comment by hmerk** [comment]
@jlaur There seems to be an issue with the new WemoInsightHandler, as my logs are being flooded with warnings „Handler already disposed“ while trying to do state updates….

**Comment by jlaur** [comment]
> There seems to be an issue with the new WemoInsightHandler, as my logs are being flooded with warnings „Handler already disposed“ while trying to do state updates….

Are you running a build from this PR, or #12120 (now main)? Can you reproduce? Can you post logs from when it started, i.e. what happened just before? I have it running in production now with two WeMo Insights (one online 24/7, one being turned on/off every now and then) for a week without any issues.

**Comment by hmerk** [comment]
@jlaur running from this PR. I will check the logs tomorrow to see when it started and what happened before.
Will try to reproduce with stopping and restarting the binding.
For completeness, i am on 3.3 M1..

**Comment by hmerk** [comment]
@jlaur Seems to have been a coincedence with reboot after upgrade, as I have seen the same error on another binding, just not as frequently.
I will do a clean restart over the weekend and keep an eye on this.

**Comment by jlaur** [comment]
@openhab/add-ons-maintainers, anyone willing to have a look at this one before next round? :-)

**Review by kaikreuzer — APPROVED** [review]
Thanks @jlaur, your code lgtm and as @hmerk has tested it, it should all be good to merge!

**Pull request merged**
