### PR TITLE
[bloomsky] BloomSky Binding initial contribution

### PR DESCRIPTION
**Pull request by dschoepel**
[bloomsky] Initial contribution

Implementing an OpenHab binding for the BloomSky personal weather station.  This is a "read-only" binding that uses the [BloomSky API](http://weatherlution.com/bloomsky-api/?doing_wp_cron=1615241711.4678061008453369140625) to retrieve the sensor data from the **SKY1, SKY2** and **STORM** personal weather stations.  If you are not familiar with these weather stations, you can find out more at the [BloomSky Home Page](https://www.bloomsky.com/).

This pull request includes the initial working binding that has been developed against the 3.2.0-SNAPSHOT.  The coding guidelines have been followed, all issues from the static code analysis have been addressed.  WIP refers to completing the documentation and README.MD.  

Link to JAR file: https://nextcloud.theschoepels.com/s/RHq2fGeE49dQ3Zg

This binding has been tested against the developers BloomSky account that has two Sky's and one Storm weather station associated with it.  It is currently running in a OH 3.2.0 system in both Windows and RPI.

### CODE REVIEW

**Comment by Jamstah** [comment]
You've caught a lot of code owners and I think it's because you need to revise... Maybe.

**Comment by dschoepel** [comment]
Rookie on submitting this.  Can you give a bit more background on what I 
need to revise to remove the the code owners from this request?  Or do I 
simply remove it and submit a new one?

Any advice is greatly appreciated.

------ Original Message ------
From: "James Hewitt" ***@***.***>
To: "openhab/openhab-addons" ***@***.***>
Cc: "dschoepel" ***@***.***>; "Author" 
***@***.***>
Sent: 7/19/2021 3:26:22 PM
Subject: Re: [openhab/openhab-addons] [bloomsky] BloomSky Binding 
initial contribution (#11030)

**Comment by Jamstah** [comment]
I'm a bit confused as to how this PR even has commits from other PRs. If they are already in main, they shouldn't show up, and if they aren't then I'm not sure where you would have got them from. Which branch did you start from?

You can either try a rebase (`git fetch` then `git rebase origin/main`), or if you aren't really familiar with git, you could just take a copy of your binding, reset your branch to match main, and then commit your binding again.

I'm not an official reviewer btw, but I would say please don't forget to focus on your README and documentation - its one of the most important parts of any binding for users to be able to use it!

**Comment by dschoepel** [comment]
> I'm a bit confused as to how this PR even has commits from other PRs. If they are already in main, they shouldn't show up, and if they aren't then I'm not sure where you would have got them from. Which branch did you start from?
> 
> You can either try a rebase (`git fetch` then `git rebase origin/main`), or if you aren't really familiar with git, you could just take a copy of your binding, reset your branch to match main, and then commit your binding again.
> 
> I'm not an official reviewer btw, but I would say please don't forget to focus on your README and documentation - its one of the most important parts of any binding for users to be able to use it!

Thanks for the quick reply.  I have put quite a bit of work into the README and documentation, wanted to be sure it is up to standards.

**Pull request closed without merging**
