### PR TITLE
[luxtronikheatpump] Add Support for HeatpumpType 81 - "LW 8 "

### PR DESCRIPTION
**Pull request by jamietownsend**
See #10558 Add Support for HeatpumpType 81 - "LW 8 "

### CODE REVIEW

**Comment by wborn** [comment]
Does this look good to you @sgiehl?

**Review by sgiehl — APPROVED** [review]
Code change looks good to be.
@jamietownsend I assume you have a heatpump of that type? Or where do you know that mapping from?

**Comment by jamietownsend** [comment]
Yes indeed, I have one of those. Just got around to hooking it up to openhab.

**Review by wborn — APPROVED** [review]
Thank you both!

**Pull request merged**
