### PR TITLE
[jdbc] Console: Fix NoSuchElementException when there are no tables

### PR DESCRIPTION
**Pull request by jlaur**
Fix regression from #13662.

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
LGTM

**Comment by jlaur** [comment]
@lsiepel - bug label removed in order not to be mentioned in release notes, since the bug hasn't yet been introduced in any milestone releases.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lsiepel** [comment]
> @lsiepel - bug label removed in order not to be mentioned in release notes, since the bug hasn't yet been introduced in any milestone releases.

Yes, sorry was a bit too quick there

**Pull request merged**
