### PR TITLE
[androidtv] Adds additional checks for parser

### LINKED ISSUE #15163: [androidtv] ShiledTV Parser Issue With New Update
Separated from #15153 as they are two issues

```
2023-06-30 16:56:06.072 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Received ShieldTV message from: SHIELD - Message: 080b123808b51012330a06534849454c44189b462210363035333834333264643430363731312a0b61726d656162692d7637612a0761726d65616269180b
2023-06-30 16:56:06.073 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Longer Hostname Reply
2023-06-30 16:56:06.089 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Message Parser Caught Exception
java.lang.ArrayIndexOutOfBoundsException: Index 124 out of bounds for length 124
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVMessageParser.handleMessage(ShieldTVMessageParser.java:132) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.finishReaderMessage(ShieldTVConnectionManager.java:738) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.readerThreadJob(ShieldTVConnectionManager.java:777) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The structure that I've always observied is:
080b 12 5b08b510 12 TOTALLEN? 0a LEN Hostname 12 LEN IPADDR Padding? 22 LEN DeviceID 2a LEN arm64-v8a 2a LEN armeabi-v7a 2a LEN armeabi 180b

The offending line in comparison:
080b 12 3808b510 12 33 0a 06 534849454c44 18 9b46 22 10 36303533383433326464343036373131 2a 0b 61726d656162692d763761 2a 07 61726d65616269 180b

The difference here being that we normally see "12 LEN IPADDR Padding?" but we're getting "18 9b46" which is unexpected.

### PR DESCRIPTION
**Pull request by morph166955**
Adds additional checks to the parser to prevent exception when information is missing.

Resolves #15163

### CODE REVIEW

**Comment by morph166955** [comment]
This is now happening on my device, which is not an IPv6 device.  This looks like it's tied to a recent update of the software and will happen to all devices when they update.

**Comment by morph166955** [comment]
@openhab/add-ons-maintainers Respectfully requesting this get reviewed and merged prior to 4.0.0.  This bug seems to be impacting a growing number of users and is tied to a yet undetermined software upgrade on the device.  The changes are not complex and mostly just moves some code around and adds some conditional checks.  Thanks!

**Review by kaikreuzer — APPROVED** [review]
Thank you!

**Comment by morph166955** [comment]
@kaikreuzer Thank you!

**Pull request merged**
