### PR TITLE
[comfoair] fix updateState

### PR DESCRIPTION
**Pull request by boehan**
Partly reverting #8563 since `updateState` is apparently not needed on `handleCommand` and therefore causing issues with state changes.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
If you receive the new state from the device after sending a command to it, it is perfectly fine to update the state accordingly - I assumed that is the situation in #8356 

Can you elaborate on what issues you are now seeing with that?

**Comment by boehan** [comment]
The write commands implemented in the binding only receive an ACK from the device. As this cannot be transformed to a valid state, `sendCommand` returns UNDEF state. The real state is then received with the next polling. So, with #8563 the channel state is switching from the sent state to UNDEF until the next update.
Sure, the behaviour could be changed to pull the real state from the device directly after sending the command, but I don't consider this necessary (and the command is acknowledged by the device anyway).

**Comment by boehan** [comment]
@kaikreuzer how to proceed here? The current situation, as described above, is definitely worse than before #8563

**Comment by kaikreuzer** [comment]
Right, if you receive only an ACK and don't know whether the command has been executed and the state has changed, not doing a state update is the right thing to do here.
In #8563 you also did a state update [in this line](https://github.com/openhab/openhab-addons/pull/8563/files#diff-5ea2270a1fc35f2c479ea7dac0b38fe6R434) - shouldn't this be reverted as well?

**Comment by boehan** [comment]
> In #8563 you also did a state update in this line - shouldn't this be reverted as well?

No, in that part the values, which are affected by the initial write command are re-read from the device. Therefore, `updateState` is necessary here to reflect the changes on the other channels. Before #8563 the values were only read from the device but channel states kept unchanged until next regular pull.

**Comment by kaikreuzer** [comment]
I cannot really follow you here, sorry.
As the code looks exactly the same, I would at least say it isn't self explaining, why this time the returned state is something valid and in the other case it isn't.
I just trust that you know why it needs to be that way and am ok to merge.

**Review by kaikreuzer — APPROVED** [review]

**Comment by kaikreuzer** [comment]
cherry-picked to 2.5.x

**Pull request merged**
