### PR TITLE
Fix io metrics documentation references

### PR DESCRIPTION
**Pull request by pravussum**
Minor updates/fixes to the documenation of the Metrics addon.

### CODE REVIEW

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by pravussum** [comment]
@kaikreuzer this didn't fully work. The screenshots are visible now, but the dashboard (json) isn't.
There seems to be a mechanism that copies image resources by convention from subfolders called "doc" to the assets in the website. But I wasn't able to find out where this is done and what I have to do to make the json work as well.

**Comment by kaikreuzer** [comment]
I see that all files are correctly copied to https://github.com/openhab/openhab-docs/tree/final/_addons_ios/metrics/doc.

I don't know what the website exactly does with the content either. I see that the images are referenced at https://www.openhab.org/assets/img/grafana-3.a8d2abe7.png on the final site - this definitely wouldn't make sense for other file types.

Maybe @ghys or @Confectrician can enlighten us here?

**Comment by Confectrician** [comment]
I have to check the ruby scripts we are running in the website build first for a proper validation, but probably we do not include json files over there as a quick idea.

**Comment by Confectrician** [comment]
https://github.com/openhab/website/blob/main/prepare-docs.rb#L544-L586

As already guessed the build logic does not know how to deal with the json file.
We have some extra script for the zwave binding and its dozens of thing pages, but nothing for files different from `*.md` and `images`.

I would guess that the usecase is providing the file for downloading it.
Should we do so for other formats too and improve the build scripts with some general logic?

**Comment by kaikreuzer** [comment]
> I would guess that the usecase is providing the file for downloading it.

In this case here yes. But I now that other add-ons also use the `doc` folder to provide additional information e.g. for developers - those should be ideally rendered as well, but I guess this would bring us into trouble with navigation etc.

The urls (https://www.openhab.org/addons/bindings/<bindingid>/) seem to suggest that it should be possible to have resources underneath as well. Is that in general a possibility to provide all content of the doc folder there?

**Pull request merged**
