### PR TITLE
[rrd4j] Correctly identify Number items with dimensions and persist them in the defined unit

### LINKED ISSUE #8809: [rrd4j] QuantityType unit is lost when restoring values on startup
When restarting see events like this in events.log:

```
2020-10-14 17:01:21.804 [INFO ] [marthome.event.ItemStateChangedEvent] - Item 'iMeter1Kwh' changed from 26.1861 to 26.1861 kWh
2020-10-14 17:01:21.810 [INFO ] [marthome.event.ItemStateChangedEvent] - Item 'iMeter1Watts' changed from 0.0 to 0 W
2020-10-14 17:02:15.159 [INFO ] [marthome.event.ItemStateChangedEvent] - Item 'iMeter2Kwh' changed from 0.0 to 0.0000 kWh
2020-10-14 17:02:15.188 [INFO ] [marthome.event.ItemStateChangedEvent] - Item 'iMeter2Watts' changed from 0.0 to 0 W
```

Later on, it's logged correctly:

```
2020-10-15 03:22:15.208 [INFO ] [marthome.event.ItemStateChangedEvent] - Item 'iMeter2Watts' changed from 1 W to 0 W
2020-10-15 03:27:15.141 [INFO ] [marthome.event.ItemStateChangedEvent] - Item 'iMeter2Watts' changed from 0 W to 1 W
```

### LINKED ISSUE #8856: RRD4J and charts no more working in OH3 for items of  type Number with a dimension
I find no rrd files created for items of type Number with a dimension.
A file is present for Items of type Number.

I have no chart working but I imagine this is a consequence of this problem.

I did not set any file rrd4j.cfg.

Here is the content of my rrd4j.persist file:
```
// persistence strategies have a name and a definition and are referred to in the "Items" section
Strategies {
	// for rrd charts, we need a cron strategy
	everyMinute : "0 * * * * ?"
}

Items {
	GTemperature*, GHumidite*, GSuiviConsoElec* : strategy = everyChange, everyMinute, restoreOnStartup
	GVirtualData*, GParametres* : strategy = everyChange, restoreOnStartup
}
```

### PR DESCRIPTION
**Pull request by kaikreuzer**
The persistence service will now use the defined unit of Number items with dimensions (which is derived from the unit given in its state description or - if not set - from the defaults of the used measurement system) for both writing and reading values from the database.

Fixes #8809
Fixes #8856

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Review by wborn — APPROVED** [review]
Thanks a lot! :+1:

**Comment by ghys** [comment]
FYI, either this or a related rrd4j PR had a **_significant_** impact on performance with retrieving data from `/rest/persistence`.
On my RPi3-equivalent, requests that used to be instant now take seconds.

image

Also some things in the UI, like the analyzer, don't work anymore because the unit comes with the number.

**Comment by kaikreuzer** [comment]
> FYI, either this or a related rrd4j PR had a significant impact on performance with retrieving data from /rest/persistence.

No idea what could cause this - I don't see any performance degradation on my system so far.

> Also some things in the UI, like the analyzer, don't work anymore because the unit comes with the number.

I just noticed the same after upgrading and @lolodomo reported https://github.com/openhab/openhab-core/issues/1781.

**Comment by ghys** [comment]
(Copied from https://github.com/openhab/openhab-core/issues/1781#issuecomment-719949241)

I have now downgraded to the M1 version of the rrd4j bundle and I'm back to acceptable perf levels again:
(see ~60ms vs 3.5s)

image

I would suspect there's something way heavier than before being done for each data point.

**Pull request merged**
