### PR TITLE
correctly adding configfiles to features

### PR DESCRIPTION
**Pull request by kaikreuzer**
It seems those were lost somewhere on the way to 2.5...

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
FTR: The distro build currently fails due to this: https://ci.openhab.org/view/Integration%20Builds%20(2.5.x)/job/openHAB-Distribution/68/

**Comment by J-N-K** [comment]
Interesting. Does that mean no new Installation is using these bindings? Do we need to add an empty `exec.whitelist`?

**Comment by cpmeister** [comment]
I looked at the failing build in jenkins but couldn't find any errors...what failed?

**Comment by kaikreuzer** [comment]
> Does that mean no new Installation is using these bindings?

No, it means that the default cfg file simply has not been created for voicerss, which doesn't matter much. For leapmotion, this binding indeed won't have worked, but I doubt that anybody is using it productively (it mainly makes sense for demos).

> what failed?

It couldn't find the cfg files for the assembly as the GAV was incorrect.

**Comment by kaikreuzer** [comment]
> Do we need to add an empty exec.whitelist?

That's what I did with https://github.com/openhab/openhab-addons/issues/7108 (which you merged) and I just came across those issues here when trying it out on the final distro build... Needs to be fixed before 2.5.3.

**Comment by kaikreuzer** [comment]
Travis failure looks unrelated to this PR.

**Comment by cpmeister** [comment]
I also see these warnings in the build:
```
[WARNING] The POM for com.leapmotion.leap:leap-java:jar:2.0.0 is missing, no dependency information available
[WARNING] The POM for com.github.cbornet.netatmo-swagger-api:netatmo-java-retrofit:jar:1.1.3 is missing, no dependency information available
[WARNING] The POM for com.github.tavalin.orvibo-sdk:s20-sdk:jar:0.0.6-nmu1 is missing, no dependency information available
[WARNING] The POM for org.openhab.binding.tado:api-client:jar:1.3.0 is missing, no dependency information available
[WARNING] The POM for org.tellstick:javatellstick:jar:1.1 is missing, no dependency information available
[WARNING] The POM for name.eskildsen:zoneminder4j:jar:0.9.7 is missing, no dependency information available
[WARNING] The POM for com.github.pathec:zway-lib:jar:0.2.9.OH is missing, no dependency information available
```

**Comment by kaikreuzer** [comment]
@cpmeister Those warnings are not new and not related to this PR, see https://github.com/openhab/openhab-addons/issues/6960.

**Comment by cpmeister** [comment]
@J-N-K If this looks alright can you go ahead and merge. I don't want to merge changes that I don't understand. I'm still learning the osgi stuff.

**Pull request merged**
