### PR TITLE
[gruenbeksoftener][WIP] Grünbeck Softener Binding initial contribution

### PR DESCRIPTION
**Pull request by msteigenberger**
This binding provides support for reading out values from an Gruenbeck softener device (SC18, SC23, MC32) via the WIFI HTTP interface.

### CODE REVIEW

**Comment by J-N-K** [comment]
@msteigenberger, is this still work-in-progress?

**Comment by mschallar** [comment]
@msteigenberger Are you will working on this binding?

**Comment by msteigenberger** [comment]
At the moment I got no time due to personal reasons. This might change in the future, but I can promise nothing at the moment.

**Comment by Hilbrand** [comment]
@msteigenberger I'm closing this pr due to long time no activity. If you still intend to finish this binding feel free to reopen this pr. Or if you need any advice let us know.

**Comment by oduzus** [comment]
@msteigenberger That's great work! I was looking a while to connect my SC18. But this made it really comfortable to get it running.
I am wondering if additional datapoints could be added, espacially it would be more interesting to see the days left until next service interval instead of the preset 365 days for the Service Interval.

**Comment by Anpro88** [comment]
> @msteigenberger That's great work! I was looking a while to connect my SC18. But this made it really comfortable to get it running.
> I am wondering if additional datapoints could be added, espacially it would be more interesting to see the days left until next service interval instead of the preset 365 days for the Service Interval.

Where did you get the jar file from?

**Comment by oduzus** [comment]
> > @msteigenberger That's great work! I was looking a while to connect my SC18. But this made it really comfortable to get it running.
> > I am wondering if additional datapoints could be added, espacially it would be more interesting to see the days left until next service interval instead of the preset 365 days for the Service Interval.
> 
> Where did you get the jar file from?

I have installed it in openHAB from the Eclipse Marketplace.

**Comment by Anpro88** [comment]
> > > @msteigenberger That's great work! I was looking a while to connect my SC18. But this made it really comfortable to get it running.
> > > I am wondering if additional datapoints could be added, espacially it would be more interesting to see the days left until next service interval instead of the preset 365 days for the Service Interval.
> > 
> > 
> > Where did you get the jar file from?
> 
> I have installed it in openHAB from the Eclipse Marketplace.

Thanks, missed the download symbol...

**Pull request closed without merging**
