### PR TITLE
[mybmw] fix not working binding due to API update

### PR DESCRIPTION
**Pull request by martingrassl**
This is mainly a bugfix PR to resolve the failing backend requests.

To make it work the code has been refactored and due to API changes some improvements could be made. These include:

- (improvement) fingerprint generation: You can take a look at the README how to create a fingerprint more conveniently. - (change) changed channel: charge-info has been renamed to charge-remaining
- (improvement) added channels: estimated-fuel-l-100km and estimated-fuel-mpg which calculates the estimated fuel consumption based on the range and remaining fuel liters - unfortunately such a calculation is not available for EVs as there is no information about the capacity of the battery.
- (improvement) added channel last-fetched: the last-updated timestamp is showing by when the last update of the vehicle happened. As right now you can not see from the channels if a thing is offline due to connection issues, you can check now if last-fetched is more than 5 minutes ago to identify an issue
- (fixed) remote command typos fixed

The jar file can be found in https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.mybmw/3.4.2-SNAPSHOT/org.openhab.binding.mybmw-3.4.2-SNAPSHOT.jar

Co-authored-by: Mark Herwege <mark.herwege@telenet.be>

Fixes https://github.com/openhab/openhab-addons/issues/14065

Also-by: Mark Herwege <mark.herwege@telenet.be>
Signed-off-by: Martin Grassl <martin.grassl@digital-filestore.de>

### CODE REVIEW

**Comment by wborn** [comment]
Please create PRs that target the main branch only.

**Comment by martingrassl** [comment]
Hi @wborn , could you give me any idea how to fix a bug in the 3.4.x branch if I'm not allowed to create a PR for it? Imho the main branch should be the released version as long as the next version hasn't been released. If I create a PR for 4.0, then it will be released far in the future, but users are waiting for the fix of #14065

**Comment by wborn** [comment]
Maintainers cherry pick important bugfixes from main to 3.4.x. So to make their life simple create a small PR that only fixes the particular bug and does not add new functionality.

**Comment by martingrassl** [comment]
> Maintainers cherry pick important bugfixes from main to 3.4.x. So to make their life simple create a small PR that only fixes the particular bug and does not add new functionality.

OK I understand. Unfortunately the change in the api caused this heavy refactoring to keep the functionality. I'll create a PR to main branch.

**Pull request closed without merging**
