### PR TITLE
[enera][WIP] Enera binding initial contribution 

### PR DESCRIPTION
**Pull request by oliverrahner**
Hi,

as this is my first binding, I am sure I missed some things, even though I tried to respect all available documentation and guidelines.

What I know is still missing:
- lots of Warnings regarding @Nullable handling
- Unit Tests
- i18n

I am very open for any kind of feedback!

### CODE REVIEW

**Comment by oliverrahner** [comment]
Sorry, this got closed as I needed to fix some git mistakes I made...

**Comment by fwolter** [comment]
Is this still work in progress? Do you like to have it reviewed?

**Comment by oliverrahner** [comment]
I still think it would be valuable contribution. The reason why I never submitted this for review is that I have much trouble removing all warnings regarding Null-Value-Warnings. After spending days trying to do this I basically surrendered...

**Comment by fwolter** [comment]
If you have any question don't hesitate to ask.

**Comment by oliverrahner** [comment]
I need to fix some things because Enera changed their API last week, so maybe during this I'll come back to you ;)

**Comment by kaikreuzer** [comment]
Closing this PR as it is not in a mergeable state. Please follow [the instructions to port this PR to the main branch](https://github.com/openhab/openhab-addons/issues/8512) for openHAB 3.

**Pull request closed without merging**
