### PR TITLE
[plclogo] Modernize to Java 11

### PR DESCRIPTION
**Pull request by falkena**
Migrate from Java 8 with Java 11. Replace discovery with background one.

Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com>

### CODE REVIEW

**Comment by lolodomo** [comment]
@falkena : is your PR still in a draft state or ready for a review ?

**Comment by lsiepel** [comment]
Some fixes might allready be added as we jumped to java 17 and bulk PR's have been merged.

**Comment by lsiepel** [comment]
@falkena recently you created some other PR's so i was wondering if you still aim to get this PR towards the finish line?

**Comment by lsiepel** [comment]
As the last commit was 2,5 years ago, i guess we can't push this forward anymore. I close this PR for now. If there is a need again to update the code, please feel free to re-open.

**Pull request closed without merging**
