### PR TITLE
[miio] Add support for Xiaomi Robot Vacuum X20+

### PR DESCRIPTION
**Pull request by marcelrv**
Adding support for the following models:
* Xiaomi Robot Vacuum X20+ (modelId: xiaomi.vacuum.c102gl)

closing #17796

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
Thanks LGTM

**Comment by sergiocastis82** [comment]
Hi. Could you post a step-by-step tutorial on how to add the vacuum cleaner to Xiaomi Miio?

**Comment by lsiepel** [comment]
> Hi. Could you post a step-by-step tutorial on how to add the vacuum cleaner to Xiaomi Miio?

You probably get a better response in the community forums for tuturial liek questions.

**Comment by marcelrv** [comment]
Yes, please indicate what you are missing from the readme. 
There is a section about adding experimental support for unsupported devices

**Pull request merged**
