### PR TITLE
[voicerss] Add LRU cache

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@dalgwen : here is a first implementation.
It is working well when the cache is enabled. But when I disable the cache, I see that my method `synthesizeForCache` is called but then I have no rendering (no sound). I am using the command `say`. I suppose there is a bug in the code of the cache when the cache is disabled.

**Comment by lolodomo** [comment]
For the review, `VoiceRSSFileAudioStream` is not a new class but the previous class named `VoiceRSSAudioStream` and I added/defined a different class `VoiceRSSAudioStream`.

**Comment by J-N-K** [comment]
What is the state here?

**Comment by lolodomo** [comment]
This PR is now finished and properly tested. But it is preferable to first wait for an update of all audio sinks. If not, the case where the TTS cache is disabled will probably not work with most of audio sinks.

**Comment by lolodomo** [comment]
To be updated when openhab/openhab-core#3675 is merged.

**Comment by lolodomo** [comment]
This PR is now ready for a review. It has been fully tested with Sonos as audio sink, either with cache enabled or disabled.

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!

**Comment by lolodomo** [comment]
Excellent, thank you.

**Pull request merged**
