### PR TITLE
[comfoair] extend UoM support, add semantic tags & update state descriptions

### PR DESCRIPTION
**Pull request by boehan**
This PR provides following improvements to the comfoair binding:

- add UoM support for fan speed in RPM (`ventilation#fanInRPM` and `ventilation#fanOutRPM`)
- add UoM support for non-hour time-related channels (mainly delay settings, and filter duration)
- allow DecimalType for QuantityType channels --> this should also avoid breaking changes for channels now supporting UoM
- add semantic tags for some channels
- update state descriptions and options for some channels
- (theoretically) enable support for rfc2217 (not tested and not sure if this is really possible for the RS232 connection)
- some code improvements

### CODE REVIEW

**Comment by boehan** [comment]
Some things are a bit unclear for me and maybe have to be adapted:

1. I was not sure if update instructions are required / make sense if only tags or state options are updated. So far I only added them for channels were `item-type` changed (UoM) or `read-only` setting was corrected.
1. AFAICT [#3132](https://github.com/openhab/openhab-core/pull/3132) should enable bounds in state descriptions for UoM channels, but I was unsure if I should add corresponding units to the `min` and `max` values.
1. I was thinking about also adding UoM support for channels with percentage values, but I see no real benefit being worth the effort as unit conversion doesn't make any sense here. However, if anyone has an argument why UoM should also be made available for percentage channels wherever possible, I will try to add it.

Any recommendations on these are welcome.

**Review by jlaur — APPROVED** [review]
Thanks! LGTM.

**Comment by boehan** [comment]
Thanks @jlaur for the fast review and merge. 
One thing I forgot to mention: `enthalpy#enthalpyTime` now represents the set time (in minutes) instead of the internal number value that is sent to the device (`minutes / 12`). For items newly created as `Number:Time` this is clear, but for *old* plain `Number` items the state is now different. 
I'm not sure if this requires / is worth a breaking change note (though I expect this channel to be hardly used)?

Additionally, I forgot to update the changes on `read-only` channels in the README. I will fix that in a follow-up PR.

**Comment by jlaur** [comment]
> For items newly created as `Number:Time` this is clear, but for _old_ plain `Number` items the state is now different.
> I'm not sure if this requires / is worth a breaking change note (though I expect this channel to be hardly used)?

If you can create a small note about this in this section, it would probably be safest - just in case some users would be affected:
https://github.com/openhab/openhab-distro/blob/ca7e75ab4db186ee73dc982af30d3aea2e24fca3/distributions/openhab/src/main/resources/bin/update.lst#L95-L116

**Pull request merged**
