### PR TITLE
[MongoDB Persistence] Fix error 500 and various improvements

### LINKED ISSUE #10574: [MongoDB Persistence] Query exception: Can't serialize class java.time.ZonedDateTime
## Expected Behavior
Query should be successful and no exception should be thrown.

## Current Behavior
When trying to access persisted data from MongoDB, the exception in the stacktrace (see attachments) is thrown. This reflects itself as a HTTP 500 Server error when trying to analyze items.
Persisting works fine, though.

## Steps to Reproduce (for Bugs)
1. Setup MongoDB as a persistence driver
2. Use Mongo as default persistence provider
3. Try to analyze an item

## Context
I'm using one collection for all items (e. g. the "collection"-parameter is set to the string "data" as per the docs)

## Your Environment
* Version used: 3.0.2 (both core and mongodb-persistence)
* Operating System and version: Official Docker image ("latest" amd64 as of 2021-04-24 19:53 CEST)
* Mongo Server: MongoDB 4.4.2 Community, Docker image

## Attachments
[stacktrace.txt](https://github.com/openhab/openhab-addons/files/6370258/stacktrace.txt)

### PR DESCRIPTION
**Pull request by boomer41**
[MongoDB Persistence] Bugfixes and various improvements

I noticed the MongoDB persistence driver had several issues, with the biggest one being the completely broken query support.
Additionally, connection recovery to the database server was not working, either. 
Also, the indices were reordered to improve performance.
Last but not least some code style changed were introduced.
Please see the commits for detailed changes. I split the changes in small commits for easier review.

The changes were tested in my local openHAB snapshot instance, running in docker.

Prebuilt module:
[mongodb-persistence.zip](https://github.com/openhab/openhab-addons/files/6408092/mongodb-persistence.zip)

Fixes #10574

### CODE REVIEW

**Comment by boomer41** [comment]
PR failure seems unrelated to my changes? Looks like Maven can't find a dependency for the plclogo binding.
The run before my last commit went through successfully, though.

**Comment by boomer41** [comment]
PR should be ready for review. By now I should have spotted most issues as I use the driver in production here.

**Review by fwolter — APPROVED** [review]
LGTM, Thanks!

@boomer41 Can you check if this fixes also #10230?

**Comment by boomer41** [comment]
> @boomer41 Can you check if this fixes also #10230?

Yes, this is the same issue as I opened. That'ss exactly the reason i looked into it ;)

@cweitkamp already linked this issue to this PR.

**Comment by fwolter** [comment]
Thanks!

**Pull request merged**
