### PR TITLE
[jellyfin] Add URL path support

### PR DESCRIPTION
**Pull request by SR-Lut3t1um**
### [Jellyfin] Added URL path support.
**Changes:**
**Fix:** Now using KTOR instead of building the url by simple string concad. This fixes the https and port 443 bug that existed prier to this change. (https://example.com would look like: https://example.com:443)
**Added:** Support for jellyfins Base URL option. This allows the addon to be used on installations were jellyfin is configured to use a base path.

### CODE REVIEW

**Comment by GiviMAD** [comment]
Hi, thank you for the changes!
Can you add the new parameter also to the readme on the "Server Thing Configuration" table?
Also the DCO check is not passing, I think is required in order to get this merged.

**Comment by GiviMAD** [comment]
Sorry, I closed this by error.

**Comment by SR-Lut3t1um** [comment]
Alright should work now :)

**Review by GiviMAD — APPROVED** [review]
LGTM! Thanks for the changes.

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
@GiviMAD : why did you use ktor for this binding ? Wasn't it possible to use the recommended HTTP client for openHAB (Jetty) ?
Typically, I am almost sure that the new code for the method `getServerUrl` could also be done easily with Jetty stuff.

**Comment by GiviMAD** [comment]
@lolodomo it's required by the jellyfin sdk.

**Pull request merged**
