### PR TITLE
Add GitHub Action Annotations for compiler warnings

### PR DESCRIPTION
**Pull request by fwolter**
Signed-off-by: Fabian Wolter <github@fabian-wolter.de>

### CODE REVIEW

**Comment by wborn** [comment]
It will probably annotate all files with warnings instead of only changed lines. That's why only annotation were added for errors.

**Comment by fwolter** [comment]
It reports the warnings for all addons that are built. As most of the time only one addon is built in a particular PR, there will only be warnings for one addon. See https://github.com/fwolter/openhab-addons/actions/runs/1567745895

**Comment by fwolter** [comment]
Ah, you mean unchanged files in the addon, which has changes. Yes, that's right. But I think that's not too bad, if the codeowner sees all warnings of his/her binding in the PR. Maybe the 10 warnings limit is prioritized to start with the changed files? I take a look.

**Comment by fwolter** [comment]
There can be 10 warnings per step and 50 warnings per job. See https://github.community/t/annotation-limitation/17998 Compiler, Checkstyle, PMD and Spotbugs are separate steps, so there will be room for some more warnings. I think that's OK for a single binding. For sure it won't be enough when all addons are built.

I think it's better to have warnings for all files of a binding, which might be truncated therefore, than no warnings at all.

**Comment by wborn** [comment]
> I think that's OK for a single binding. For sure it won't be enough when all addons are built.

I think it will be annoying and everybody will just start ignoring all these unrelated warnings which will then also clutter up reviews.

**Comment by fwolter** [comment]
I find it makes code reviews easier and more efficient. Especially to see the SAT warnings which are newly introduced in contrast to the existing. You'll see it at a glance with the annotations:
grafik
Maybe another maintainer can join the discussion @openhab/add-ons-maintainers  If I'm alone with my opinion it's okay to close this.

**Comment by fwolter** [comment]
Seems like I'm alone with my opinion. That's ok.

**Comment by kaikreuzer** [comment]
Hey @fwolter, sorry for not commenting earlier. I definitely also see value in annotating warnings, but knowing the code base and the amount of warnings we still have in there, I'm also a bit worried that it might be too distracting/annoying and thus think that we should go without at least for now.

**Pull request closed without merging**
