### PR TITLE
[danfossairunit] Fix already configured units in inbox

### LINKED ISSUE #12216: [danfossairunit] Duplicate inbox entry (file-based configuration)
Discovered Danfoss Air Units already configured in files are showing up in the inbox.

## Expected Behavior
Already configured things should be ignored.

## Current Behavior
Already configured things are displayed.

## Possible Solution
Define host as representation property in things definition.

## Steps to Reproduce
1. Create a .things file with a Danfoss Air Unit.
2. Go to inbox.
3. Observe that same unit is discovered and displayed.

### PR DESCRIPTION
**Pull request by jlaur**
Fixes #12216

Signed-off-by: Jacob Laursen <jacob-github@vindvejr.dk>

Fix entries in inbox for already configured units.

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
This was already set correctly by the discovery class, so need to other change than what you proposed.

**Comment by jlaur** [comment]
> This was already set correctly by the discovery class, so need to other change than what you proposed.

Not sure what you mean? You are right about discovery class, so should be in sync now:
```
                DiscoveryResult result = DiscoveryResultBuilder.create(uid).withRepresentationProperty("host")
                        .withProperties(properties).withLabel("Danfoss HRV").build();
```

**Comment by lolodomo** [comment]
Yes, I was just mentioning your change in the XML file was sufficient.

**Pull request merged**
