### PR TITLE
[tesla] Use correct command for opening trunk/frunk

### LINKED ISSUE #7158: The Tesla binding addon is using the wrong command for opening the trunk/frunk:
The correct command from the [API Reference](https://tesla-api.timdorr.com/vehicle/commands/trunk) is "actuate_trunk".

[The binding is using "trunk_open"](https://github.com/openhab/openhab-addons/blob/127f05d7cbb865ae2f7a939c761707f0479d5143/bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java)
`public static final String COMMAND_TRUNK_OPEN = "trunk_open";`

This causes a "400:Bad Request" 
```
2020-03-13 12:56:08.121 [WARN ] [internal.handler.TeslaAccountHandler] - Reached the maximum number of errors (2) for the current interval (15 seconds)
2020-03-13 12:56:08.129 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request trunk_open: 400:Bad Request

```
and the bridge connection to disconnect:
```
2020-03-13 12:56:08.130 [hingStatusInfoChangedEvent] - 'tesla:account:myaccount' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)
2020-03-13 12:56:08.135 [hingStatusInfoChangedEvent] - 'tesla:model3:myaccount:mycar' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2020-03-13 12:56:10.493 [hingStatusInfoChangedEvent] - 'tesla:model3:myaccount:mycar' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
```

### PR DESCRIPTION
**Pull request by wborn**
I don't own a Tesla, but I can help their owners to open their trunk/frunk. :wink: 

Fixes #7158

### CODE REVIEW

**Comment by wborn** [comment]
Yes I already thought you'd do the PR yourself otherwise. Though this fix was too easy to risk it slipping past the 2.5.3 release. :slightly_smiling_face:

**Comment by kaikreuzer** [comment]
It will only make it into the release if we get the build working again, see https://github.com/openhab/openhab-addons/pull/7140#issuecomment-599195972. Maybe you have an idea about it?

**Comment by tonyyng** [comment]
Thanks guys.  Hopefully the build gets fixed.

**Comment by wborn** [comment]
>  Maybe you have an idea about it?

Not really since it builds fine locally and the [Jenkins PR build for 7140 also succeeded before it was merged](https://ci.openhab.org/job/PR-openHAB2-Addons/17717/). Though it looks like there haven't been any other PRs that changed the bnd version (pretty risky for stable builds IMHO) or how itests run so reverting those changes may be a good option if @mehoekstra doesn't know a solution either.

**Pull request merged**
