### PR TITLE
[velux] Fixed a couple of bugs if the Bridge contains one or more Scenes

### PR DESCRIPTION
**Pull request by andrewfg**
Fixed the following bugs..
1. If the Bridge contains one or more Scenes, the Bridge Check Property displayed an error 
2. If the Bridge contains one or more Scenes, the mapThing2Velux() method displayed an error
3. Removed a compiler null warning

### CODE REVIEW

**Review by fwolter — APPROVED** [review]
LGTM

There are many static loggers. They should be only final. Could you file a follow-up PR?

**Comment by andrewfg** [comment]
@fwolter thank you for the merge.

> There are many static loggers. They should be only final. 

And thank you for the feedback. But the reason for having static loggers is normally that the respective classes have static methods which require logging. I don't know any other way to resolve that. (Do you have suggestions?)

**Comment by fwolter** [comment]
Shame on me, I didn't looked into the code at these places. It's ok to have these static.

But I just saw that the JAR got accidentally into this PR. Can you file a follow-up PR to remove it?

**Comment by andrewfg** [comment]
> the JAR got accidentally into this PR. Can you file a follow-up PR to remove it?

Yes.

**Pull request merged**
