### PR TITLE
[semp] New openHAB SEMP Service

### PR DESCRIPTION
**Pull request by Markinus**
This service implements the SEMP protocol for openHAB. This protocol is a [SMA ](https://www.sma.de/produkte/sma-developer.html )protocol used for controling of devices depending on the sun's state. 

**Features**:

UPNP automatic discovery
Full SEMP Support

**Installation**:

After the activation of this plugin and the configuration of the consumer(s) the upnp service will start immediately. After some minutes you can start a device search in the SMA Sunny Portal. It will detect the device(s) and you will be able to add it to your device list.

**Documentation**:
See the READMÉ file.

**Testing**:
Tested with different users

### CODE REVIEW

**Comment by Hilbrand** [comment]
The file `ImperiHomeApiServlet.java` is moved in this pr, that doesn't look right?

**Comment by Markinus** [comment]
Ohh, yes. Strange. I will remove it.

**Comment by Markinus** [comment]
Hi @Hilbrand, I removed this wrong file moving.

**Comment by Markinus** [comment]
Hi @pdegeus, 
it would be great if you could review this.
Greetings

**Comment by Markinus** [comment]
Hi @Hilbrand,
could you review this request? I would like to finish this project.
Greetings

**Comment by Markinus** [comment]
In the löast commit I removed a conflict in the bundles/pom.xml (modulelist). This list there is not longer existing. If I need to add this somewhere else then it would be great to get a hint..

**Comment by Markinus** [comment]
Maybe I should move this PR to the 2.5.x branch...

**Comment by Markinus** [comment]
New PR #6715 based on 2.5.x branch. I will close this one.

**Pull request closed without merging**
