### PR TITLE
[neohub] Avoid too frequent requests to hub

### LINKED ISSUE #15498: [neohub] systemTimeout config param not working
Entering a `systemTimeout` config param via a `.things` file does not change the actual value used.

### PR DESCRIPTION
**Pull request by andrewfg**
### Background

The NeoHub bridge thing sometimes goes offline due to systemTimeout. Discussions on the Heatmiser developer forum indicate that this error may be due to the binding making requests too fast.

https://dev.heatmiser.com/t/need-help-with-neohub-spuriously-changing-thermostat-settings/818/1

### Solution

The solution is to pipeline the requests and throttle them.

Fixes #15498 

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

### CODE REVIEW

**Comment by lolodomo** [comment]
@andrewfg : still really work in progress ?

**Comment by andrewfg** [comment]
> still really work in progress ?

@lolodomo yes, unfortunately; I have been running it 7/24 and the PR seems not to solve the issue.

**Comment by andrewfg** [comment]
@lolodomo this one is good to go now :)

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
