### PR TITLE
[hdpowerview] Add console extension for showing IDs

### LINKED ISSUE #13614: [hdpowerview] Console command for identifying shade/repeater IDs
In order to support file-based configuration without the need for prior UI configuration using discovery, a console command could be added. See #13555 for a similar solution for Netatmo.

### PR DESCRIPTION
**Pull request by jlaur**
Example session:
```
openhab> openhab:hdpowerview showIds
API bridge: PowerView Hub
 - Shades:
    - ID: 23137 (Gardin 7)
    - ID: 24076 (Gardin 10)
    - ID: 32544 (Gardin 6)
    - ID: 58120 (Gardin 2)
    - ID: 34896 (Gardin 5)
    - ID: 5868 (Gardin 8)
    - ID: 38196 (Gardin 1)
    - ID: 46532 (Gardin 3)
    - ID: 42949 (Gardin 4)
    - ID: 36137 (Gardin 11)
    - ID: 24927 (Gardin 9)
 - Repeaters:
    - ID: 17805 (Repeater soveværelse)
```

Fixes #13614
Depends on openhab/openhab-core#3111

### CODE REVIEW

**Comment by andrewfg** [comment]
@jlaur brilliant! We will of course also need it for Gen 3..

**Review by andrewfg — APPROVED** [review]
LGTM :)

**Comment by andrewfg** [comment]
Albeit (nota bene to self) your code will have to be extended to include support for `gateway` bridges resp. `shade3` things.

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Pull request merged**
