### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by martinlindjarv**
Fix for simple typo in priter status channel name.

### CODE REVIEW

**Comment by Cossey** [comment]
Looks good, but please signoff this commit so that I can approve and get the maintainers to merge. 

*You can click the Details link on the DCO line to get more information on how to fix this.*

**Comment by martinlindjarv** [comment]
@Cossey Due to fact that it's my first commit and i can't figure out how it need's to be done. Can you point me to right direction?

**Review by wborn — APPROVED** [review]
Thanks! A sign off is not required in this case because of the [small patch exception](https://www.openhab.org/docs/developer/contributing.html#small-patch-exception).

**Comment by wborn** [comment]
I'll cherry-pick this to the main branch.

**Pull request merged**
