### PR TITLE
[onkyo] Add support for TX-NR609

### PR DESCRIPTION
**Pull request by Albinoman887**
Commit message pretty much says it all. Just added tx-nr609 to the list of supported models. also added a missing listening mode I use to the list of possible choices

### CODE REVIEW

**Comment by jlaur** [comment]
@Albinoman887 - please update this file also:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/i18n/onkyo.properties

**Review by lolodomo — CHANGES_REQUESTED** [review]
Please update the file only.properties for the new type and the new option. 

Can be done manually or simply by running `mvn i18b:generate-default-translations`

**Comment by Albinoman887** [comment]
I don't see "only.properties" just onkyo.properties. updating that now

**Review by lolodomo — APPROVED** [review]
LGTM

**Review by jlaur — APPROVED** [review]
Thanks for the contribution, looks good.

**Comment by brusan** [comment]
Thank you so much!

**Pull request merged**
