### PR TITLE
[darksky] Update default translations

### PR DESCRIPTION
**Pull request by lolodomo**
Related to #12837

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Once merged, I hope the binding will finally appear in Crowdin.
The German translations should then be uploaded in Crowdin.

**Review by wborn — APPROVED** [review]
Thanks!

**Comment by lolodomo** [comment]
Binding is now available in Crowdin. 
I will upload the German translations later today.

**Comment by lolodomo** [comment]
German translations are now uploaded in Crowdin and only one translation entry is now missing.
I also tried to upload Hungarian translations (only few translations are present in GitHub) but I am not sure it worked !

**Pull request merged**
