### PR TITLE
[bluetooth] Introduced manufacturer data to BluetoothDevice

### PR DESCRIPTION
**Pull request by paulianttila**
Discovery participants can access manufacturer data from scan result if necessary.

Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com>

### CODE REVIEW

**Comment by cpmeister** [comment]
Ugh, I'm not sure what to think of this. I've seen bluetooth devices that do multiple manufacturerData advertisements with different data. I guess this field can be treated the same way we treat RSSI, as a sort of last-seen value but ultimately manufacturerData is much more valuable as a notification.

**Comment by paulianttila** [comment]
E.g. Airthing devices expose model type information in manufacturer data. Model type information is necessary in discovery phase to create correct thing. Airthings provides simple python script as an example how to read data from the device (no any other documentation is available) and script doesn't give any hint if model type could be read from the device.

**Comment by cpmeister** [comment]
If Airthing devices expose model type information through their GATT data then if might be worthwhile to wait for #7056 to go through. I have another PR that I'm in the process of making that will make some significant API improvements to BluetoothDevice, using CompletableFuture for most of the async operations will make life a lot simpler for any complex bluetooth binding development.

**Comment by paulianttila** [comment]
@cpmeister, model type can be read from standard Model Number String GATT Characteristic

https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.model_number_string.xml

It take me awhile to understand why I couldn't read that from Airthing device. BlueGiga binding seems to construct 128 bit UUID wrongly from 16 and 32 bit UUID. Airthing device publish handles for those standard UUID's as a 16bit UUID and in BlueGiga those are constructed to 128 bit by just filling via 0.

https://github.com/openhab/openhab-addons/blob/95c5e8b179b8e1f8c17a465d75c2c48fbffbe59d/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaResponse.java#L88-L121

BlueZ seems to handle 16 and 32 bit UUID's correctly

https://github.com/intel-iot-devkit/tinyb/blob/ac6d3082d06183c860eea97f451d5a92022348e0/src/BluetoothUUID.cpp#L12-L47

If I'm right all UUID's in bluetooth binding is used as a 128 bit UUID (16 or 32 bit UUID are not supported), so I think this cause incompatible at the moment between BlueZ and BlueGiga and needed to be fixed.

Not sure why "find primary services" seems to work with illegal UUID? Maybe Airthing device just check first 16/32 bit from UUID.

https://github.com/openhab/openhab-addons/blob/95c5e8b179b8e1f8c17a465d75c2c48fbffbe59d/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java#L503-L513

**Comment by cpmeister** [comment]
> Not sure why "find primary services" seems to work with illegal UUID? Maybe Airthing device just check first 16/32 bit from UUID. UPDATE: reason obviously is that the handle is still correct even UUID is wrong

I wonder if this is one of those "if it ain't broke, don't fix it" situations.

**Comment by cpmeister** [comment]
@paulianttila Since connection based discovery has been implemented, do you want to try adding that gatt model number logic to your discovery participant? If that works then I feel we can close this PR.

**Comment by paulianttila** [comment]
@cpmeister, should connection based discovery try to read all parameters from Device information service (https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Services/org.bluetooth.service.device_information.xml)? Then discovery participant should hopefully have enough information to create correct device.

**Comment by paulianttila** [comment]
@cpmeister, implemented **proto type** for device information fetch. See https://github.com/openhab/openhab-addons/commit/ff0ebdfce481106c4040783a0072df0c0ccee714

`
18:57:55.246 [OH-discovery-2] DEBUG o.o.b.b.d.i.BluetoothDiscoveryProcess:204 - Device information read from device BluetoothDevice [address=A4:DA:32:B9:59:34, manufacturer=820, name=Airthings Wave+, model=2930, serialNumber=014215, hwRevision=1.0, fwRevision=G-BLE-1.2.4, swRevision=null, rssi=-55 (Corentium/Airthings AS)]
`

**Comment by cpmeister** [comment]
@paulianttila Ugh, I really like that idea, but at the same time I don't think that characteristic data should exist as fields on the BluetoothDevice object. Your prototype example is at odds to my idea of getting rid of the 'value' field in BluetoothCharacteristic since that would be the perfect place to cache that data instead.

Then again, all those fields are essential Thing properties that would be useful to include during discovery....
AAAAAAAAAGGHHHHH, why did you have to show such a good idea!?
Make PR for this so I can get it merged!

**Comment by paulianttila** [comment]
#7147

**Pull request closed without merging**
