### PR TITLE
[luxtronik] Add channel for fixed heating return temperature

### PR DESCRIPTION
**Pull request by Taxifahrer**
I run my Apha Innotec LWC heat pump in fixed temperature mode, so I can directly control the target heating return temperature via openHAB (higher temperature if solar is generating enough power, etc.). Currently upgrading from OH2, where I had made private changes to the addon, so maybe we can add this to the standard code.

Clean version of https://github.com/openhab/openhab-addons/pull/16178

### CODE REVIEW

**Review by lsiepel — APPROVED** [review]
LGTM

**Review by sgiehl — APPROVED** [review]

**Comment by Taxifahrer** [comment]
It still says merging is blocked, because the base branch restricts merging to authorized users. All checks are showing as OK. I just don't know the process, so do I need to do anything else, or simply wait until someone does the merge?

**Comment by lsiepel** [comment]
> It still says merging is blocked, because the base branch restricts merging to authorized users. All checks are showing as OK. I just don't know the process, so do I need to do anything else, or simply wait until someone does the merge?

Yeah, just simply wait until it is picked up by a maintainer.

**Comment by lsiepel** [comment]
Thanks, LGTM

**Pull request merged**
