### PR TITLE
[xmltv] Handle possible XXE injection

### PR DESCRIPTION
**Pull request by holgerfriedrich**
XMLInputFactory: Disable property IS_SUPPORTING_EXTERNAL_ENTITIES which allows injecting external entities.

I cannot test this change. @clinique was it intentional to disable DTD and keep external entities on?
In case, please close my PR.

### CODE REVIEW

**Comment by lolodomo** [comment]
@clinique : any feedback ?

**Review by clinique — APPROVED** [review]
LGTM

**Comment by clinique** [comment]
@holgerfriedrich : sorry for late review of your proposal. Thanks for this.

**Review by lolodomo — APPROVED** [review]
LGTM

**Pull request merged**
