### PR TITLE
apply spotless

### PR DESCRIPTION
**Pull request by J-N-K**
Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Review by bern77 — APPROVED** [review]

**Review by druciak — APPROVED** [review]

**Review by Hilbrand — CHANGES_REQUESTED** [review]
The `itest.bndrun` files also need to be updated.

**Review by Confectrician — APPROVED** [review]
Pixometer

**Comment by Confectrician** [comment]
Also congrats for issue/pull #10000 in this repository and thanks for your ongoing work here. 🙂🎉

**Comment by JueBag** [comment]
Tankerkoenig

LGTM

**Review by JueBag — APPROVED** [review]

**Review by wborn — APPROVED** [review]
Thanks! And congrats on making the 10000th PR! :partying_face:

**Review by andrewfg — APPROVED** [review]

**Comment by J-N-K** [comment]
No idea why the itests still fail. `NoClassDefFoundException` on `JAXBUtils` seems to be unrelated to the new development cycle.

**Review by bobadair — APPROVED** [review]
LGTM for the alarmdecoder and lutron bindings.
Congrats on PR 10000 in this repo, and here's to the next 10000!

**Review by yfre — APPROVED** [review]
LGTM for homekit

**Review by Hilbrand — APPROVED** [review]
LGTM. Lets merge this. If other test problems need to be fixed this can be done in a follow up pr.

**Review by fruggy83 — COMMENTED** [review]
LGTM for enocean

**Pull request merged**
