### PR TITLE
[danfossairunit] Remove broken link from documentation

### PR DESCRIPTION
**Pull request by jlaur**

### CODE REVIEW

**Review by pravussum — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
I just tested the new link but it leads to a page saying "We're sorry but we can't find the page you're looking for"

**Comment by jlaur** [comment]
> I just tested the new link but it leads to a page saying "We're sorry but we can't find the page you're looking for"

OMG, you're right. They literally just took down that page since @pravussum approved. It existed until a few days ago. Thanks for checking, I'll see if I can find another page. I heard rumors that they are abandoning Danfoss Air.

**Comment by jlaur** [comment]
I have sent an inquiry to Danfoss. Currently you get the impression that these products never existed. I will send an update here when they get back to me.

**Comment by jlaur** [comment]
I have received an e-mail from Danfoss stating that they stopped selling all ventilation systems for homes per June 30th 2023. Therefore there are no replacement links.

**Review by lolodomo — APPROVED** [review]

**Pull request merged**
