### PR TITLE
[systeminfo] Bump OSHI to 6.4.8

### PR DESCRIPTION
**Pull request by J-N-K**
This is the latest OSHI version that is compatible with the Karaf provided JNA 5.13.0

### CODE REVIEW

**Review by wborn — APPROVED** [review]
LGTM!

**Comment by J-N-K** [comment]
Even if it was not the OP's issue: merging this cleans up out dependencies.

**Review by mherwege — COMMENTED** [review]
LGTM

**Review by mherwege — APPROVED** [review]

**Comment by mhilbush** [comment]
@J-N-K Does someone (@kaikreuzer) need to upload this new version to Artifactory. In snapshot build 3845 the installer is complaining that `mvn:com.github.oshi/oshi-core/6.4.8` can't be downloaded.

**Comment by J-N-K** [comment]
it's available on maven central, I thought it was automatically transferred to the artifactory during a build

**Comment by mhilbush** [comment]
I just looked on https://openhab.jfrog.io/ and 6.2.2 is the latest version there. Am I looking in the right place?

**Comment by J-N-K** [comment]
@kaikreuzer Do you have an idea what is missing here? We have upgraded the dependency the same way we did in the past and never faced an issue with artifacts from maven central.

**Comment by mherwege** [comment]
Could it be (wild guess) it kept the wrong version because the integration test still has version 6.2.2 in its pom.xml? That's fixed with https://github.com/openhab/openhab-addons/pull/16012.

**Comment by kaikreuzer** [comment]
>  I thought it was automatically transferred to the artifactory during a build

@J-N-K No, unfortunately, this is still done manually. I just did so for version 6.4.8 of that library.

**Comment by J-N-K** [comment]
Interesting. So you manually upload when we upgrade any dependency? Or just some special ones?

**Comment by kaikreuzer** [comment]
Any dependency of an add-on that is not embedded into the jar. All core dependencies are packaged into the runtime, so for those there is no need to upload them.

**Comment by J-N-K** [comment]
Thanks! I'll keep that in mind.

**Pull request merged**
