### PR TITLE
[pulseaudio] Fix #8843. Stop spamming logs when pulseaudio device is offline

### LINKED ISSUE #8843: [pulseaudio] Offline Pulseaudio Bridge triggers throwing of exceptions
```
2020-10-23 18:35:41.455 [ERROR] [pulseaudio.internal.PulseaudioClient] - No route to host (Host unreachable)
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_265]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_265]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_265]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_265]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_265]
	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_265]
	at java.net.Socket.connect(Socket.java:556) ~[?:1.8.0_265]
	at java.net.Socket.<init>(Socket.java:452) ~[?:1.8.0_265]
	at java.net.Socket.<init>(Socket.java:229) ~[?:1.8.0_265]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.connect(PulseaudioClient.java:611) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.checkConnection(PulseaudioClient.java:599) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.sendRawRequest(PulseaudioClient.java:555) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.listModules(PulseaudioClient.java:166) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.update(PulseaudioClient.java:143) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.<init>(PulseaudioClient.java:131) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.handler.PulseaudioBridgeHandler.lambda$1(PulseaudioBridgeHandler.java:135) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
2020-10-23 18:35:41.476 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.sendRawRequest(PulseaudioClient.java:558) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.listModules(PulseaudioClient.java:166) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.update(PulseaudioClient.java:143) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.PulseaudioClient.<init>(PulseaudioClient.java:131) ~[?:?]
	at org.openhab.binding.pulseaudio.internal.handler.PulseaudioBridgeHandler.lambda$1(PulseaudioBridgeHandler.java:135) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

## Expected Behavior
Log a single message about the device being offline (at most) and set the device state to offline, since an offline state seems something that could be expected of a pulseaudio bridge

## Current Behavior
The connection request to an offline pulseaudio client causes a NoRouteToHostException to be thrown. 

## Possible Solution
Catch the exception and add a logger statement

## Steps to Reproduce (for Bugs)
- set up a pulseaudio server on some linux box.
- enable its cli-protocol and set up the bridge and perhaps a sink item in openhab
- confirm the creation and states of the items and bridge in the log
- take the pulseaudio server offline

## Context 
In my setup i have 3 thin clients in different rooms running linux and pulseaudio. Sometimes these devices are shut off or in sleep mode to conserve energy.
Whenever this is the case and the pulseaudio binding does *something* periodically, i get a long stack trace message in my logs resulting of the route to the host not being found. 
I think this exception should be handled more gracefully, so as not to spam the logs.

## Environment
* Version used: (openHAB 2.5.9-1 on openhabian)
* Environment name and version: pulseaudio servers in version 12.x and 13.x

### PR DESCRIPTION
**Pull request by vKnmnn**
Signed-off-by: Robert von Könemann <lordtaifleh@gmail.com>

This PR addresses an issue where an offline pulseaudio device is being contacted periodically by the binding when configured by text files.

## [Pulseaudio] Stop spamming logs when configured pulseaudio device is offline

The issue arises when the binding tries to read data from the socket representing the offline pulseaudio device. This PR addresses the issue by making sure that the socket is not equal to null before returning its value or before writing to it.

It also catches a NoRouteToHostException that occurs when the binding tries to connect to an offline device, which removes the strack-traces from the logs and instead displays an error line.

### CODE REVIEW

**Comment by vKnmnn** [comment]
@peuter

**Comment by cpmeister** [comment]
If you want to cover all your bases you should do the client null checks in the `sendRawCommand` method as well.

**Comment by peuter** [comment]
@cpmeister suggestion makes sense. Despite that the PR looks good to me, altough I don't use this binding myself anymore and therefore cannot test the code.

**Comment by vKnmnn** [comment]
That's a good point, thanks @cpmeister. Added the check to that method.

To be honest, i think this binding could be a lot better in the handling of offline devices, but i'm not experienced enough to tackle it.

**Comment by vKnmnn** [comment]
There's a failing test in jenkins, but it has to do with mqtt which i find rather weird
retrigger?

**Review by cpmeister — APPROVED** [review]
Don't worry about the test failures since they aren't related to your changes.

**Pull request merged**
