### PR TITLE
[remoteopenhab] Consider ItemStateChangedEvent events when relevant

### LINKED ISSUE #9190: Remote OpenHab Issue with Federated Docker OH3-OH2 Not Properly Updating
## Binding Name
OpenHAB Remote Binding

## Expected Behavior
Bi-directional link between OH2 and OH3 Items.

## Current Behavior
I have noticed an issue that continues to plague its use in my setup. I am trying to link my OH2 2.5.9 setup with OH3 M3. Both are running in Dockers on the same UnRaid server on the same subnet (br0) with unique IPs and ports set to 8080. OH2 has been working flawlessly for almost 2 yrs now. I have an extensive ISY/Insteon installation that OH2 automates and for which there is no OH3 binding as of today. I am able to link OH3 to OH2 and control OH2 Things/Items from OH3. However any changes made to Items using OH2 are not reflected in my linked Items in OH3. Going the other direction OH3 to OH2 works fine and changes are properly reflected in both OH2 and OH3. My understanding is that the binding is bi-directional, but in my setup it appears to only be OH3 -> OH2, not OH2-> OH3. If I restart OH3 then changes made in OH2 prior to the restart seem to be reflected, but no real time updates seem to happen. This issue seems to affect dimmer type switches mostly. Simple ON/Off switches seem to get updated correctly most of the time.

My Items are created using text based files. For this exercise/example to demonstrate the issue I am using a dimmer for fireplace lighting. The Item declaration is the same for both OH2 and OH3.

## Item Definitions and Logs
OH 2 Item:

Dimmer v2A35C71FireplaceLoadLevel "Fireplace Lighting"  <screen>  (Group_HabPanel_Dashboard, PubItems_CMD, gLighting, gFamilyRoom) ["WallSwitch"]

OH3 Item:

Dimmer v2A35C71FireplaceLoadLevel "Fireplace Lighting"  <screen>  (Group_HabPanel_Dashboard, PubItems_CMD, gLighting, gFamilyRoom) ["WallSwitch"]

When Issuing a command from OH2 to adjust the Fireplace Light I see these events in the OH2.events log Turning it OFF from 73% state then turning on to 73% state.

2020-11-29 12:33:10.909 [vent.ItemStateChangedEvent] - v2A35C71FireplaceLoadLevel changed from 73 to 0
2020-11-29 12:33:20.923 [vent.ItemStateChangedEvent] - v2A35C71FireplaceLoadLevel changed from 0 to 73
The corresponding OH2.log entry is

2020-11-29 12:33:10.901 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="260" sid="uuid:1462"><control>DOF</control><action>0</action><node>2A 35 C7 1</node><eventInfo></eventInfo></Event>]
2020-11-29 12:33:10.902 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node '2A 35 C7 1' got control message 'DOF' action '0'
2020-11-29 12:33:10.903 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - onModelChanged called, control: DOF, action: 0, var event: null
2020-11-29 12:33:10.903 [TRACE] [binding.isy.handler.IsyBridgeHandler] - find thing handler for address: 2A 35 C7 1
2020-11-29 12:33:10.904 [TRACE] [binding.isy.handler.IsyBridgeHandler] - Find thing for address: 2A 35 C7
2020-11-29 12:33:10.904 [TRACE] [binding.isy.handler.IsyBridgeHandler] - address: 2A 35 C7
2020-11-29 12:33:10.904 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - handleUpdate called, control: DOF , action: 0 , node:2A 35 C7 1
2020-11-29 12:33:10.905 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="261" sid="uuid:1462"><control>ST</control><action>0</action><node>2A 35 C7 1</node><eventInfo></eventInfo></Event>]
2020-11-29 12:33:10.906 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node '2A 35 C7 1' got control message 'ST' action '0'
2020-11-29 12:33:10.906 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - onModelChanged called, control: ST, action: 0, var event: null
2020-11-29 12:33:10.907 [TRACE] [binding.isy.handler.IsyBridgeHandler] - find thing handler for address: 2A 35 C7 1
2020-11-29 12:33:10.907 [TRACE] [binding.isy.handler.IsyBridgeHandler] - Find thing for address: 2A 35 C7
2020-11-29 12:33:10.908 [TRACE] [binding.isy.handler.IsyBridgeHandler] - address: 2A 35 C7
2020-11-29 12:33:10.908 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - handleUpdate called, control: ST , action: 0 , node:2A 35 C7 1
2020-11-29 12:33:10.909 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="262" sid="uuid:1462"><control>_1</control><action>3</action><node></node><eventInfo>[  2A 35 C7 1]      DOF   0</eventInfo></Event>]
2020-11-29 12:33:10.909 [DEBUG] [pdb.internal.MapDBPersistenceService] - store called for v2A35C71FireplaceLoadLevel
2020-11-29 12:33:10.909 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node 'n/a' got control message '_1' action '3'
2020-11-29 12:33:10.910 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="263" sid="uuid:1462"><control>_1</control><action>3</action><node></node><eventInfo>[  2A 35 C7 1]       ST   0</eventInfo></Event>]
2020-11-29 12:33:10.911 [DEBUG] [pdb.internal.MapDBPersistenceService] - Stored 'v2A35C71FireplaceLoadLevel' with state '0' in mapdb database
2020-11-29 12:33:10.911 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node 'n/a' got control message '_1' action '3'

2020-11-29 12:33:20.915 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="264" sid="uuid:1462"><control>DON</control><action>0</action><node>2A 35 C7 1</node><eventInfo></eventInfo></Event>]
2020-11-29 12:33:20.917 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node '2A 35 C7 1' got control message 'DON' action '0'
2020-11-29 12:33:20.917 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - onModelChanged called, control: DON, action: 0, var event: null
2020-11-29 12:33:20.918 [TRACE] [binding.isy.handler.IsyBridgeHandler] - find thing handler for address: 2A 35 C7 1
2020-11-29 12:33:20.918 [TRACE] [binding.isy.handler.IsyBridgeHandler] - Find thing for address: 2A 35 C7
2020-11-29 12:33:20.918 [TRACE] [binding.isy.handler.IsyBridgeHandler] - address: 2A 35 C7
2020-11-29 12:33:20.919 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - handleUpdate called, control: DON , action: 0 , node:2A 35 C7 1
2020-11-29 12:33:20.919 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="265" sid="uuid:1462"><control>ST</control><action>188</action><node>2A 35 C7 1</node><eventInfo></eventInfo></Event>]
2020-11-29 12:33:20.920 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node '2A 35 C7 1' got control message 'ST' action '188'
2020-11-29 12:33:20.920 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - onModelChanged called, control: ST, action: 188, var event: null
2020-11-29 12:33:20.921 [TRACE] [binding.isy.handler.IsyBridgeHandler] - find thing handler for address: 2A 35 C7 1
2020-11-29 12:33:20.921 [TRACE] [binding.isy.handler.IsyBridgeHandler] - Find thing for address: 2A 35 C7
2020-11-29 12:33:20.921 [TRACE] [binding.isy.handler.IsyBridgeHandler] - address: 2A 35 C7
2020-11-29 12:33:20.921 [DEBUG] [binding.isy.handler.IsyDeviceHandler] - handleUpdate called, control: ST , action: 188 , node:2A 35 C7 1
2020-11-29 12:33:20.922 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="266" sid="uuid:1462"><control>_1</control><action>3</action><node></node><eventInfo>[  2A 35 C7 1]      DON   0</eventInfo></Event>]
2020-11-29 12:33:20.922 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node 'n/a' got control message '_1' action '3'
2020-11-29 12:33:20.923 [DEBUG] [pdb.internal.MapDBPersistenceService] - store called for v2A35C71FireplaceLoadLevel
2020-11-29 12:33:20.923 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="267" sid="uuid:1462"><control>_1</control><action>3</action><node></node><eventInfo>[  2A 35 C7 1]       ST 188</eventInfo></Event>]
2020-11-29 12:33:20.924 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node 'n/a' got control message '_1' action '3'
2020-11-29 12:33:20.924 [DEBUG] [pdb.internal.MapDBPersistenceService] - Stored 'v2A35C71FireplaceLoadLevel' with state '73' in mapdb database
The OH3.events.log I’m not seeing an entry it is set to INFO just like the OH2
OH3.Log is

020-11-29 12:33:10.909 [TRACE] [nternal.rest.RemoteopenhabRestClient] - Received event name message date {"topic":"smarthome/items/v2A35C71FireplaceLoadLevel/state","payload":"{\"type\":\"OnOff\",\"value\":\"OFF\"}","type":"ItemStateEvent"}
2020-11-29 12:33:10.910 [DEBUG] [l.handler.RemoteopenhabBridgeHandler] - Unexpected value type OnOff for item v2A35C71FireplaceLoadLevel
2020-11-29 12:33:10.910 [TRACE] [nternal.rest.RemoteopenhabRestClient] - Received event name message date {"topic":"smarthome/items/v2A35C71FireplaceLoadLevel/statechanged","payload":"{\"type\":\"Percent\",\"value\":\"0\",\"oldType\":\"Percent\",\"oldValue\":\"73\"}","type":"ItemStateChangedEvent"}
2020-11-29 12:33:10.910 [TRACE] [nternal.rest.RemoteopenhabRestClient] - Ignored event type ItemStateChangedEvent for topic smarthome/items/v2A35C71FireplaceLoadLevel/statechanged

2020-11-29 12:33:20.923 [TRACE] [nternal.rest.RemoteopenhabRestClient] - Received event name message date {"topic":"smarthome/items/v2A35C71FireplaceLoadLevel/state","payload":"{\"type\":\"Percent\",\"value\":\"73\"}","type":"ItemStateEvent"}
2020-11-29 12:33:20.924 [DEBUG] [l.handler.RemoteopenhabBridgeHandler] - updateState remoteopenhab:server:openhab25x:v2A35C71FireplaceLoadLevel with 73
2020-11-29 12:33:20.924 [TRACE] [internal.events.ThreadedEventHandler] - inspect event: org.osgi.service.event.Event [topic=openhab] {topic=openhab/items/v2A35C71FireplaceLoadLevel/state, source=remoteopenhab:server:openhab25x:v2A35C71FireplaceLoadLevel, type=ItemStateEvent, payload={"type":"Percent","value":"73"}, timestamp=1606671200924}
2020-11-29 12:33:20.924 [TRACE] [nternal.rest.RemoteopenhabRestClient] - Received event name message date {"topic":"smarthome/items/v2A35C71FireplaceLoadLevel/statechanged","payload":"{\"type\":\"Percent\",\"value\":\"73\",\"oldType\":\"Percent\",\"oldValue\":\"0\"}","type":"ItemStateChangedEvent"}
2020-11-29 12:33:20.924 [TRACE] [nternal.rest.RemoteopenhabRestClient] - Ignored event type ItemStateChangedEvent for topic smarthome/items/v2A35C71FireplaceLoadLevel/statechanged
2020-11-29 12:33:20.925 [TRACE] [ab.core.internal.items.ExpireManager] - Received '73' for item v2A35C71FireplaceLoadLevel

Just to put a final point on this, if I change the state of the Fireplace Light from OH3 I do get an event in the OH3events.log as shown below, and the light dims as expected.

2020-11-29 12:58:47.127 [ome.event.ItemCommandEvent] - Item 'v2A35C71FireplaceLoadLevel' received command 20
2020-11-29 12:58:47.156 [vent.ItemStateChangedEvent] - Item 'v2A35C71FireplaceLoadLevel' changed from 73 to 20

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #9190

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : is it possible to include that PR in OH3 milestone 5 ?

**Comment by lolodomo** [comment]
Is it possible to merge this PR please.
Tis is only 28 lines of new code and a very basic change.
I would really like to have this in OH3 RC1.

**Review by fwolter — APPROVED** [review]
LGTM

**Comment by lolodomo** [comment]
Thank you ;)

**Pull request merged**
