### PR TITLE
[dynamodb] Changes required after API changes in core framework

### PR DESCRIPTION
**Pull request by lolodomo**
Changes in openhab/openhab-core#3481 broke this service due to a breaking API change in NumberItem class (constructor).

Related to openhab/openhab-core#3600

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
> Why don't you inject the `UnitProvider` in the constructor (similar to the `ItemRegistry`)?

Good idea.

**Comment by lolodomo** [comment]
Ok, it is now fully fixed.

**Comment by lolodomo** [comment]
@openhab/add-ons-maintainers : please review and merge ASAP so that we can get new snapshots again.

**Review by jlaur — APPROVED** [review]
Thanks!

**Comment by lolodomo** [comment]
Thank you @jlaur 
@kaikreuzer @J-N-K : please start the build of a new snapshot.

**Comment by jlaur** [comment]
@lolodomo - FYI, build failed because of another test:

https://github.com/openhab/openhab-addons/actions/runs/4939114188/jobs/8829556438
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project org.openhab.binding.modbus.tests: Compilation failure
Error:  /home/runner/work/openhab-addons/openhab-addons/itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java:[159,27] The constructor org.openhab.core.library.CoreItemFactory() is undefined
```

**Comment by lolodomo** [comment]
> @lolodomo - FYI, build failed because of another test

I certainly forgot to grep in integration tests. 
I will continue to share in openhab/openhab-core#3600
This would have been better if J-N-K had checked the build of addons before the merge of the core change.

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-core/issues/3600#issuecomment-1542648159
I see at least 3 bundles to fix for integration tests.

**Pull request merged**
