### PR TITLE
[hue] Use auto update policy 'veto' for light channels (API v2)

### LINKED ISSUE #15983: [hue] States are changed multiple times because of rounding
The default [auto update policy](https://www.openhab.org/docs/developer/bindings/thing-xml.html#auto-update-policies) causes state to be updated immediately when commands are received rather than awaiting the actual state provided by the bridge.

Example:
```
2023-11-25 23:56:36.113 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Brightness' received command 30
2023-11-25 23:56:36.114 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Brightness' predicted to become 30
2023-11-25 23:56:36.115 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 0 to 30
2023-11-25 23:56:36.207 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 30 to 30.04
2023-11-25 23:56:36.207 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Switch' changed from OFF to ON
```

Or even worse:
```
2023-11-25 23:59:12.488 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Brightness' received command ON
2023-11-25 23:59:12.488 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Brightness' predicted to become ON
2023-11-25 23:59:12.489 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 0 to 100
2023-11-25 23:59:12.730 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 100 to 30.04
2023-11-25 23:59:12.730 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Switch' changed from OFF to ON
```

## Your Environment
* Version used: 4.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by jlaur**
This pull request addresses an issue with [auto update policy](https://www.openhab.org/docs/developer/bindings/thing-xml.html#auto-update-policies) being **default**, which causes commands to trigger state update immediately rather than awaiting the final state from the bridge.

This can cause:
- Flickering in UI's.
- Misbehavior from rules (see chapter **Context** in #15700).
- A bit of a mess in persisted values.

Example:
```
2023-11-25 23:56:36.113 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Brightness' received command 30
2023-11-25 23:56:36.114 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Brightness' predicted to become 30
2023-11-25 23:56:36.115 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 0 to 30
2023-11-25 23:56:36.207 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 30 to 30.04
2023-11-25 23:56:36.207 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Switch' changed from OFF to ON
```

Or even worse:
```
2023-11-25 23:59:12.488 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Brightness' received command ON
2023-11-25 23:59:12.488 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Brightness' predicted to become ON
2023-11-25 23:59:12.489 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 0 to 100
2023-11-25 23:59:12.730 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 100 to 30.04
2023-11-25 23:59:12.730 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Switch' changed from OFF to ON
```

With auto update policy **veto**:
```
2023-11-25 23:42:53.686 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Brightness' received command 30
2023-11-25 23:42:53.781 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 0 to 30.04
2023-11-25 23:42:53.782 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Switch' changed from OFF to ON
```

and:
```
2023-11-26 00:03:51.614 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Brightness' received command ON
2023-11-26 00:03:51.694 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Brightness' changed from 0 to 30.04
2023-11-26 00:03:51.695 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Switch' changed from OFF to ON
```

Using auto update policy **veto** will allow us to await the final state from the bridge. This will happen quite quickly since we receive events through SSE with API v2.

Fixes #15983
Related to #15700, #15995
Depends on openhab/openhab-core#3888

### CODE REVIEW

**Comment by andrewfg** [comment]
@jlaur as you added a description text to some of the channels, perhaps you need to run update properties script to update the .properties file? Or?

**Comment by jlaur** [comment]
> as you added a description text to some of the channels, perhaps you need to run update properties script to update the .properties file? Or?

Yes, thanks for the reminder, it was done. Ready for final review.

**Review by andrewfg — APPROVED** [review]
LGTM

**Review by kaikreuzer — APPROVED** [review]
@jlaur certainly any time!
Thanks for this improvement!

**Pull request merged**
