### PR TITLE
[miio] Add support for Roborock Q Revo

### PR DESCRIPTION
**Pull request by truidix**
I've just added the Q Revo to the supported models and have tested almost all of the base channels with success

Signed-off-by:  David Kumar <github@truidix.de>

### CODE REVIEW

**Comment by truidix** [comment]
@marcelrv,  @wborn , @jlaur , might one of you have a quick look at my changes, so that it can be merged? The changes are really minimal..;)

Thx

**Comment by wborn** [comment]
I think the conclusion was that more changes are needed in https://github.com/openhab/openhab-addons/pull/15340.

**Comment by truidix** [comment]
@wborn , but the files are changed, too.
And I merged it into the main. That is the reason why the previous one was closed.

Did I miss any changes?

**Comment by wborn** [comment]
Yes translation files: https://github.com/openhab/openhab-addons/pull/15340#issuecomment-1657245401

**Comment by truidix** [comment]
Hallo @marcelrv,

sry. it took me a while. But i added the needed translation I uses the "ReadmeHelper.java" for that. Hopefully now eveythings fine?  :-)

**Comment by lolodomo** [comment]
Let's wait for @marcelrv approval, this binding is so particular.

**Review by marcelrv — APPROVED** [review]
thanks

**Review by wborn — APPROVED** [review]
Thanks all!

**Pull request merged**
