### PR TITLE
[rfxcom] Add junit to test dependencies

### PR DESCRIPTION
**Pull request by Jamstah**
Tests will not compile by default without this, because the tests use junit.

Signed-off-by: James Hewitt <james.hewitt@uk.ibm.com>

### CODE REVIEW

**Comment by martinvw** [comment]
@wborn why did the build even work without this? Is there other magic involved?

**Comment by wborn** [comment]
I think this PR unnecessary? It should already be a transitive dependency. Also we use JUnit 5 not 4.

**Comment by wborn** [comment]
I think this dependency takes care of it

https://github.com/openhab/openhab-addons/blob/047ae89aaf2c95cb97ef04ed4cdd2f9d5af31311/bundles/pom.xml#L409

**Comment by Jamstah** [comment]
Hmm.

I followed the guide here: https://www.openhab.org/docs/developer/ide/eclipse.html

And the only project I imported was the rfxcom binding. This left me with a project where the test classes had errors because they were missing junit.

Perhaps what is needed is an update to the doc to say "always open the top level project" too?

Or, maybe my eclipse was just being weird. I'm OK if we just close this, because I've got things working.

**Comment by wborn** [comment]
Probably something else fixed your issue but not adding this old JUnit 4 dependency. The rfxcom tests also use the JUnit 5 Jupiter API which is not provided by the dependency you added.

**Pull request closed without merging**
