### PR TITLE
[icloud] Add german translation

### PR DESCRIPTION
**Pull request by Pantastisch**
Signed-off-by: Panagiotis Doulgeris <panagiotis.doulgeris@outlook.com>

### CODE REVIEW

**Review by fwolter — APPROVED** [review]
Thanks!

**Comment by fwolter** [comment]
The sign-off message must contain your realname and a valid mail address. See https://www.openhab.org/docs/developer/contributing.html#sign-your-work

**Comment by Pantastisch** [comment]
> The sign-off message must contain your realname and a valid mail address. See https://www.openhab.org/docs/developer/contributing.html#sign-your-work

Done!

**Comment by fwolter** [comment]
Did you push your change?

**Comment by Pantastisch** [comment]
> Did you push your change?

Hope it looks better now. 

In my commit message are now two sign-off messages by myself. 
One with my git account, one with my personal data. 

How do I get rid of the git accounts one? 
Does it interfere with the contribution guideline?

**Comment by fwolter** [comment]
That's fine, thanks!

**Pull request merged**
