### PR TITLE
[fineoffsetweatherstation] Replace apache.commons

### PR DESCRIPTION
**Pull request by lsiepel**
Depends on https://github.com/openhab/openhab-core/pull/4279

### CODE REVIEW

**Comment by jlaur** [comment]
@lsiepel - we need to wait for a core build, then we can reschedule and it should comple without errors. 🙂

**Comment by lsiepel** [comment]
> @lsiepel - we need to wait for a core build, then we can reschedule and it should comple without errors. 🙂

Thanks, thought it was more realtime. I’ll be patient now 🤣

**Comment by jlaur** [comment]
@lsiepel - method name is `padRight` rather than `rightPad`.

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
