### PR TITLE
[mybmw] Fix images not loading anymore

### LINKED ISSUE #16642: [mybmw] images not loading anymore
The images in the myBMW binding are not loading anymore

## Expected Behavior

image can be loaded

## Current Behavior

404 error happens when trying to load an image

## Possible Solution

see https://github.com/bimmerconnected/bimmer_connected/pull/604/files

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

### PR DESCRIPTION
**Pull request by martingrassl**
Fixes #16642

### CODE REVIEW

**Review by lsiepel — CHANGES_REQUESTED** [review]
I think upgrade instructiosn are not needed, but can you verify that the obsolete options are removed from the channel without re-creating the thing ? 
As these channel options are removed, they should also be removed from the default translation file.

**Comment by martingrassl** [comment]
> I think upgrade instructiosn are not needed, but can you verify that the obsolete options are removed from the channel without re-creating the thing ? As these channel options are removed, they should also be removed from the default translation file.

Hi @lsiepel, you are very quick in checking PRs :100: I changed the update file, so it should be fine, and the translation is also fixed.

I have only one thing which I'm facing all the time when I'm testing in my local sandbox environment and keep exchanging the addon continuously:

`2024-04-11 22:35:01.822 [ERROR] [core.thing.internal.ThingManagerImpl] - Checking/initializing thing 'mybmw:conv:8fcadebba9:xxxx' failed unexpectedly.
java.lang.IllegalArgumentException: Duplicate channels mybmw:conv:8fcadebba9:xxxx:status#last-fetched
`
it is always concerning the same channel - if I look into the jsondb-file, there is no duplicate, it looks like this:
`        {
          "uid": "mybmw:conv:8fcadebba9:xxxx:status#last-fetched",
          "id": "status#last-fetched",
          "channelTypeUID": "mybmw:last-fetched-channel",
          "itemType": "DateTime",
          "kind": "STATE",
          "label": "Last Openhab Update Timestamp",
          "defaultTags": [],
          "properties": {},
          "configuration": {}
        },
`

do you know where this could come from? When I delete the thing and re-add it, it works perfectly fine. The channel was added in targetVersion 1

**Review by lsiepel — APPROVED** [review]
LGTM. I'll leave this here for some days so the codeowners are able to comment.

**Review by mherwege — APPROVED** [review]
LGTM

**Pull request merged**
