### PR TITLE
[boschshc] Parental Controls for Thermostats; Wall Thermostats; Internal refactoring

### PR DESCRIPTION
**Pull request by coeing**
Hi there,

We managed to finish a new version of our binding.

Here is a list of issues that were fixed since 1.1:

- Unify names of handlers by removing Bosch prefix [#46](https://github.com/stefan-kaestle/openhab2-addons/issues/46)
- Use new service architecture in all device handlers [#40](https://github.com/stefan-kaestle/openhab2-addons/issues/40)
- Detect incorrect device ID instead of showing the thing as "Online" [#34](https://github.com/stefan-kaestle/openhab2-addons/issues/34)
- Add information to each channel in `README.md` if it is writeable [#83](https://github.com/stefan-kaestle/openhab2-addons/issues/83)
- Add a short description for each device/thing to `README.md` [#84](https://github.com/stefan-kaestle/openhab2-addons/issues/84)
- Add handler for "Wall thermostat" (temperature + humidity) [#25](https://github.com/stefan-kaestle/openhab2-addons/issues/25)
- Enhance robustness of TwinGuard measurment handling on weak wireless connections [#66](https://github.com/stefan-kaestle/openhab2-addons/issues/66)
- Parental controls on ash thermostats [#41](https://github.com/stefan-kaestle/openhab2-addons/issues/41)
- Received invalid - State within openhab not updated properly [#101](https://github.com/stefan-kaestle/openhab2-addons/issues/101)
- Prevent creation of Thing without assigning a parent bridge [#63](https://github.com/stefan-kaestle/openhab2-addons/issues/63)

Hope we can get our update merged quickly, we'll try to help where we can :)

### CODE REVIEW

**Comment by coeing** [comment]
@hmerk As you are the only one that did something on this issue: Do we have to do anything else before the pull request is checked? :)

**Comment by hmerk** [comment]
@coeing Unfortunately, you have to be patient. We are not having enough maintainers actually to review all PRs.

**Comment by coeing** [comment]
> @coeing Unfortunately, you have to be patient. We are not having enough maintainers actually to review all PRs.

@hmerk No problem, I just wanted to make sure that we provided all the information required.

**Review by fwolter — APPROVED** [review]
LGTM

**Comment by GerdZanker** [comment]
Thank you @coeing for finishing the changes and finalization the PR.

**Comment by coeing** [comment]
Thanks @fwolter for taking the time to approve the PR :) Have a nice weekend!

**Pull request merged**
