### PR TITLE
[deconz] Provide battery level as QuantityType with unit [%]

### PR DESCRIPTION
**Pull request by LukasA83**
Provide battery level as QuantityType Dimensionless with unit [%].

Signed-off-by: Lukas Agethen <lukas83@gmx.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
I had the same idea while looking into #9424. I wonder if the benefit of providing this as quantitytype is bigger than the hassle with a breaking change. The benefit of quantitytype is (in my opinion) that it‘s easy to provide different units (like Celsius and Fahrenheit) or different scales (like g and kg). Nothing of that applies to the battery level, I can‘t imagine that someone wants another unit than percent.

**Comment by LukasA83** [comment]
The reason I picked it up is because without state formatting some items reported the battery levels like "95 one". This will fix it. By breaking change you mean all users have to change their linked item from Number to Number:dimensionless? I was guessing it will continue to work with Number, but haven't tried.

**Comment by LukasA83** [comment]
I updated the docs, too. Did you make up your mind around this change @J-N-K ?

**Comment by cweitkamp** [comment]
I have to second @J-N-Ks opinion. It looks like a minor change in this binding but it will have a greater impact when looking from the view of the whole framework. If we change it here we imo have to change it everywhere - in all the add-ons, the default system channel type in OHC and so on. A mixture of quantitized battery levels and "normal" values might be a mess and upset people.

I appreciate your effort and like to support the migration of as much as possible to use UoM. But not in this case ...

... Unless you are volunteering to pick up the whole migration and start working on it.

**Comment by cweitkamp** [comment]
Or we try to find a feasible way to support both.

**Comment by LukasA83** [comment]
I check some other bindings and it seems there is already a mix, e.g. automower binding. So, to my understanding, changing the system channel type and update respective bindings using this channel type is the way to go?

**Comment by cweitkamp** [comment]
If we really want to do it: Yes.

@openhab/add-ons-maintainers What is your opinion on this?

**Comment by fwolter** [comment]
If I remember correctly, all new bindings I saw are already using UoM for the battery state, without using the system Channel. I'd second to change the system Channel, as I understood the backward compatibility is maintained, but "only" code changes are necessary. I counted 24 bindings using the system Channel, which would need to be adapted.

**Comment by kaikreuzer** [comment]
Err, in any case bindings must use the system channel type instead of defining their own... So the best PR here would be to refactor the binding to use the system channel type.
And yes, as a follow-up, we can discuss in openhab-core how to evolve the system channel type as I agree that it is a pity that we missed to switch them to UoM.

**Comment by J-N-K** [comment]
I agree with @kaikreuzer. However, I would first change the core and then change all bindings at once when UoM are available in the system-channel.

**Comment by kaikreuzer** [comment]
If the switch to the (current) system channel type is a breaking change, I'd agree - if not, I think this can and should be done right away.

**Comment by LukasA83** [comment]
@kaikreuzer : I believe for the deconz binding there has been a PR committed, submitted after this one, to use the system type for battery level. #9513

**Comment by cweitkamp** [comment]
I think we can close this for now until we have a solution for in OHC and a volunteer who likes to rework the affected bindings.

**Pull request closed without merging**
