### PR TITLE
[tplinksmarthome] KL400 support

### PR DESCRIPTION
**Pull request by dustinsoftware**
This builds on the work of @Hilbrand, and fixes a bug with HSL commands ignoring the brightness.

### CODE REVIEW

**Comment by dustinsoftware** [comment]
@Hilbrand I see #12000 is marked as a draft, once that is merged I can rebase this on top of it.

**Comment by lolodomo** [comment]
Is there an order to respect for both of your PRs?

**Comment by dustinsoftware** [comment]
No, I just wanted to get my KL400 lights working so I put both commits in this PR. :) 

I can split it into separate PRs if you prefer.

**Comment by lolodomo** [comment]
Please coordinate with @Hilbrand . His PR is only draft!

**Comment by Hilbrand** [comment]
@dustinsoftware You can also create a PR against my branch. That way I can merge the changes in my pr and make the pr ready for review, and update the community marketplace. I had it draft to comply with the community marketplace guidelines and because my implementation was not tested (and I have no devices to test, so I was relying on the community to provide feedback, but didn't get any so far).

**Comment by Hilbrand** [comment]
Closing this pr. @dustinsoftware created a pr against my pr and that has been merged. @dustinsoftware Thanks for your fixes.

**Pull request closed without merging**
