### PR TITLE
[ism8] Extend example sitemap

### PR DESCRIPTION
**Pull request by holgerfriedrich**
* Add things, items, and sitemap for heat pump and solar module.
* Use UOM for all items.

This PR adds example code needed for heat pumps. Implementation of new channels was done in #17688.
Closes: #17682

### CODE REVIEW

**Comment by lsiepel** [comment]
The examples have German labels. I know they where already there, but if you are looking at it, would it be possible to adjust hem to English?

**Comment by holgerfriedrich** [comment]
@lsiepel Fair point. Though, the documentation of ism8 is available only in German as well, and most of the item names and descriptions seem to be derived from the docs. When I start translating this, it will certainly sound wrong.... Not sure how to proceed on this.
Not sure how popular those devices are outside of Germany.

**Comment by lsiepel** [comment]
Wolf devices are being sold here in NL. As the rest is already in german it is consistent, so let's take this improvement as is.

**Review by lsiepel — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
