### PR TITLE
[jrubyscripting] Upgrade to jruby-9.4.3.0

### PR DESCRIPTION
**Pull request by jimtng**

### CODE REVIEW

**Review by ccutrer — APPROVED** [review]

**Comment by lolodomo** [comment]
@kaikreuzer : do you want to take this very late change ?

**Comment by kaikreuzer** [comment]
I cannot assess the implications, I would therefore say "no".

If @jimtng and @ccutrer say it is critical to have it in 4.0, this would be the only argument. But if it is only a nice to have, I would leave it for 4.1.

**Comment by ccutrer** [comment]
No, it can wait.

**Review by wborn — APPROVED** [review]
LGTM and :+1:

**Pull request merged**
