### PR TITLE
[ecobee] only log stack traces to openhab.log if debug is enabled

### PR DESCRIPTION
**Pull request by robnielsen**

### CODE REVIEW

**Review by mhilbush — CHANGES_REQUESTED** [review]
I'm good with this. But wouldn't it make sense to include the exception type in the non-debug log message?

**Comment by robnielsen** [comment]
I followed the same pattern as elsewhere, why is it needed?

**Comment by mhilbush** [comment]
Well, if I were the developer of the binding, my first question would be "there are multiple exceptions. which one did you get"

**Comment by robnielsen** [comment]
OK, exception name, along with message will get logged in non-debug mode.

**Review by mhilbush — APPROVED** [review]
Thanks! LGTM

**Review by cpmeister — APPROVED** [review]

**Pull request merged**
