### PR TITLE
[kostalinverter] Prevent randomly hanging HTTP-connections

### PR DESCRIPTION
**Pull request by basse04**
Changes are done to prevent randomly hanging HTTP-connections. The
changes are mostly done regarded to Exceptions but there are also some
other fixes.

Signed-off-by: basse04 <orjan.backsell@gmail.com>
Also-by: Christian Schneider <>
Also-by: René Stakemeier <>
Also-by: Christoph Weitkamp <>

### CODE REVIEW

**Comment by lolodomo** [comment]
The problem could be the also-by without email.

**Comment by basse04** [comment]
Thank's

Signed-off-by: basse04 orjan.backsell@gmail.com

**Comment by basse04** [comment]
I also did as described in Details for DCO.
I have tried earlier to found the e-mails for the Also-by people but have not found them, though I think that they should be there.
Do you have any ide'as how to handle this in some other way, I will make a new try to find them but just if not.

**Comment by lolodomo** [comment]
Looks like DCO is now ok but your PR contains almost nothing in comparison to the original PR. 
This is very simple, I will detail the actions in the evening.

**Comment by basse04** [comment]
There are only changes done in these 3 files

It's strange, I thought that these changes already were there from earlier, but there must have been some mismatch done. I found out when I did as you said and made a new local repository and forked the latest addons there.
So again, Thank's a lot for your help and patience.
BR Basse

**Comment by lolodomo** [comment]
You are updating directly your main branch ! That is not good.

1. Switch to your original branch with your changes: git checkout 2.5.x
2. Backup your changed file (5 or 6 files, I don' remember exactly) somewhere outside Git
3. Switch to the main branch: git checkout main
4. Update the main branch: git pull origin main
5. Create a new branch for your changes: git checkout -b kostalinverter_something
6. Restore your previously backuped files
7. Check that everything compiles: cd bundles/org.openhab.binding.kostalinverter ; mvn clean install
8. For each updated file: git add xxx
9. Commit your changes with a correct `Signed-off-by` in the text (and no also-by without a mailà: git commit
10. Push your branch: git push origin kostalinverter_something
11. In GitHub, create a new PR from the new branch kostalinverter_something that was created

**Comment by basse04** [comment]
Thank's for all help, I will make a new one.

**Pull request closed without merging**
