### PR TITLE
Build addon xml

### PR DESCRIPTION
**Pull request by J-N-K**
Related to https://github.com/openhab/openhab-core/pull/3865
Supersedes #15780

### CODE REVIEW

**Comment by andrewfg** [comment]
A minor issue concerning the generated xml .. to ensure 'proper' xml .. I think the `addon-header.xml` should include a reference to the over-wrap xml schema file `addon-info-list-1.0.0.xsd` (which I have created in my PR in org.openhab.core.addon`) before the copyright declaration..

```
<?xml version="1.0" encoding="UTF-8"?>
==> insert schema and namespace reference here
<!--

	Copyright (c) 2010-2023 Contributors to the openHAB project

	See the NOTICE file(s) distributed with this work for additional
	information.

	This program and the accompanying materials are made available under the
	terms of the Eclipse Public License 2.0 which is available at
	http://www.eclipse.org/legal/epl-2.0

	SPDX-License-Identifier: EPL-2.0

-->
<addon-info-list>
	<addons>
<addon:addon id="groovyscripting" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:addon="https://openhab.org/schemas/addon/v1.0.0"
	xsi:schemaLocation="https://openhab.org/schemas/addon/v1.0.0 https://openhab.org/schemas/addon-1.0.0.xsd">

	<type>automation</type>
	<name>Groovy Scripting</name>
	<description>This adds a Groovy script engine.</description>
	<connection>none</connection>

</addon:addon>
...

</addons>
</addon-info-list>
```

**Comment by J-N-K** [comment]
IMO there should not be a header in an auto-generated XML file. We don'T have the headers in the add-ons either.

**Comment by andrewfg** [comment]
> there should not be a header in an auto-generated XML file

Ok. (But it opens the question why therefore is a copyright message needed? .. )

**Review by andrewfg — APPROVED** [review]
LGTM

**Comment by mherwege** [comment]
LGTM.

**Comment by lolodomo** [comment]
@wborn : maybe you could review this one ?

**Review by wborn — APPROVED** [review]
Looks good to me too! :+1:

**Review by kaikreuzer — APPROVED** [review]
Thanks! I guess this can already be merged without having to wait for the other PRs.

**Pull request merged**
