### PR TITLE
[modbus] Update README.md

### PR DESCRIPTION
**Pull request by Rossko57**
Hoping I have added a Table of Contents to this large document.  I am not at all familiar with this editor, and do not know if I have done this correctly!

Signed-off-by Ross Kennedy <rossko@culzean.clara.co.uk>

### CODE REVIEW

**Comment by ssalonen** [comment]
Sounds like a good idea!

I am actually not familiar with the syntax. Would @Confectrician  help here please?

**Comment by Hilbrand** [comment]
I tested the toc notation and it should work. It's also the same syntax used on other documentation pages.

Does this change required other changes?

**Comment by Rossko57** [comment]
> I tested the toc notation and it should work. 

Thankyou for that.  It was just doubts on our part, not having used the ToC style before, as there seems to be no preview for the effect.

**Comment by Hilbrand** [comment]
@ssalonen Can you have another look?

**Comment by ssalonen** [comment]
Lgtm

**Review by Hilbrand — APPROVED** [review]

**Pull request merged**
