### PR TITLE
[Netatmo] Floodlight issue on Presence Camera

### PR DESCRIPTION
**Pull request by clinique**
Solves issue #14458 

 Removes the usage of "app.netatmo.net" since api now holds these entry points.
I think it was the origin of malfunction of floodlight (to be controlled by somebody who has one).

### CODE REVIEW

**Review by lolodomo — APPROVED** [review]
LGTM, thank you

**Comment by lolodomo** [comment]
@clinique : you want to wait for a user feedback before merging ?

**Comment by clinique** [comment]
Yes, I'm unable to ensure that what I did works really, so I would prefer have somebody (@multimartin) validate this.

**Comment by lolodomo** [comment]
Confirmed to work in the issue.

**Pull request merged**
