### PR TITLE
Upgrade SAT to 0.12.0

### PR DESCRIPTION
**Pull request by wborn**
See the [0.12.0 milestone](https://github.com/openhab/static-code-analysis/milestone/18?closed=1) for all changes in this release.

Depends on https://github.com/openhab/openhab-addons/pull/11476

### CODE REVIEW

**Review by cweitkamp — CHANGES_REQUESTED** [review]
There is an SAT error in pwm Binding. Can you fix it?

```
[ERROR] Code Analysis Tool has found: 
 1 error(s)! 
 0 warning(s) 
 0 info(s)
[ERROR] org.openhab.automation.pwm.internal.handler.state.State.java:[54]
Use equals() to compare object references.
[INFO] Detailed report can be found at: file:/home/jenkins/jenkins-agent1/workspace/PR-openHAB-Addons@3/bundles/org.openhab.automation.pwm/target/code-analysis/report.html
```

**Comment by wborn** [comment]
> Can you fix it?

That's done in #11476 and why this PR has a "awaiting other PR" label. :wink:

**Comment by cweitkamp** [comment]
Alright then. I did not see that. Thanks for the hint. I merged the other PR and restarted builds for this one.

**Review by cweitkamp — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
