### PR TITLE
[knx] Refactor manufacturer map

### PR DESCRIPTION
**Pull request by J-N-K**
This makes adding new manufacturers easy and is the last improvement that was missing for the re-integration of the KNX binding.

### CODE REVIEW

**Review by holgerfriedrich — CHANGES_REQUESTED** [review]
Thanks, @J-N-K, for completing this.
I am missing 2 manufacturers which are not contained in the new file:

> 34 = eVoKNX
> 373 = ZF Friedrichshafen AG

**Comment by holgerfriedrich** [comment]
Did you consider smarthomej/addons#371?
The helper function ```readProperties``` from commons seems a bit different, e.g. regarding error handling.

**Comment by J-N-K** [comment]
The other code is more generic and there are more things that can go wrong. I omitted the error handling for cases that cannot occur in this version.

**Review by holgerfriedrich — APPROVED** [review]
Thanks for clarification, LGTM

**Review by jlaur — APPROVED** [review]
Thanks!

**Pull request merged**
