### PR TITLE
[miio] Fix handling commands with curly brackets

### PR DESCRIPTION
**Pull request by marcelrv**
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by marcelrv** [comment]
Fixing issue from forum for Vacuum 1C STYTJ01ZHM (dreame.vacuum.mc1808)
https://community.openhab.org/t/problem-with-miio-binding-for-vacuum-1c-stytj01zhm-dreame-vacuum-mc1808/102631/27

**Review by cpmeister — APPROVED** [review]

**Comment by cpmeister** [comment]
Well somehow the TADO binding broke, but it was due to some dependency issue unrelated to this PR.

**Comment by J-N-K** [comment]
@kaikreuzer or @wborn can you restart Jenkins/clear cache? It seems to have problems picking up the dependencies I uploaded some days ago. It builds fine locally and also succeeded once on Jenkins.

**Comment by kaikreuzer** [comment]
You mean
```
Failure to find org.openhab.binding.tado:api-client:jar:1.4.1 in https://openhab.jfrog.io/openhab/libs-release
```
?
This looks rather like an issue with Artifactory, not Jenkins: https://openhab.jfrog.io/openhab/libs-release/org/openhab/binding/tado/ gave me a 404.
I just logged in to Artifactory as an admin and now suddenly I see the content at that url - so I'd assume that it is solved now.

**Comment by J-N-K** [comment]
That‘s very strange, because in the tado-PR one Build succeeed and failed for another reason. Thanks for having a Look.

**Pull request merged**
