### PR TITLE
[homekit] fix group handling

### PR DESCRIPTION
**Pull request by yfre**
PR #7967 creates sometimes one accessory twice:
there are following cases that should be supported:
1) one accessory defined using group, light switch tagged as "OnState" characteristic  
```
Group  gLight 	"Light Group" {homekit="Lighting"}
Switch light   "Light" (gLight) {homekit="OnState"}
```

2) one accessory defined using group, light switch tagged as "Lighting.OnState" characteristic  
```
Group  gLight 	"Light Group" {homekit="Lighting"}
Switch light   "Light" (gLight) {homekit="Lighting.OnState"}
```

3) two accessories: first = group itself, second = switch (switch can be tagged as "Lighting" or "Lighting.OnState")
```
Group:Switch:OR(ON,OFF)  gLight "Light Group" {homekit="Lighting"}
Switch light   "Light" (gLight)  {homekit="Lighting..OnState"}
```

1) and 3) were working correctly, but in case of 2) it has created 2 accessories, one = group+switch, second = switch

this PR fixes the 2) case. all 3 cases are tested and working correctly.  added comment describing the cases

Signed-off-by: Eugen Freiter <freiter@gmx.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Is this behavior properly documented in the README?

**Comment by yfre** [comment]
> Is this behavior properly documented in the README?

it seems to be expected behaviour and it was working that way before. This PR fixes basically a bug. 
but i have added an example to a README so that different ways of using groups are more clear.

**Comment by yfre** [comment]
@J-N-K  i have updated the documentation. is anything else open here? i would love to merge this before 2.6.7 as it is pretty ugly bug

**Comment by J-N-K** [comment]
Travis fails in Java11 build while using SAT.

**Pull request merged**
