### PR TITLE
[mqtt.generic] fix state description provider

### LINKED ISSUE #8845: [MQTT] OH3 Error: DynamicStateDescriptionProvider implementations must never return the original state description. class org.openhab.binding.mqtt.generic.MqttChannelStateDescriptionProvider has to be fixed.
Hi,

I'm sneak peeking into OH3 build #1980. Most my issues went away over the last builds, greatjob.

In my log I see ~ every minute this error:
`[ERROR] [ernal.ChannelStateDescriptionProvider] - Dynamic state description matches original state description. DynamicStateDescriptionProvider implementations must never return the original state description. class org.openhab.binding.mqtt.generic.MqttChannelStateDescriptionProvider has to be fixed.`

Is there anything wrong with my configuration or something wrong with the addon?

### PR DESCRIPTION
**Pull request by J-N-K**
Fixes #8845 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by cpmeister** [comment]
I'm not sure about this, from the bug conversation it looks like the core is checking if the new state description is equal to the original description using `.equals`. IMO it shouldn't be an error for a binding to coincidentally return a description that happens to be similar to the original one. If the intent of the check is to make sure that the binding isn't returning the original description then perhaps the equality check in the core should be changed to a reference comparison between the old and new descriptions.

**Comment by jochen314** [comment]
Even the documentation says:
```
If the given channel will not be managed by the provider null should be returned. You never must return the 
original state description in such case.
```
But the implemenation will always return ```null``` if the cannel is not managed by the provider.
This is not a problem of the provider, but of the logging in the core.

**Comment by J-N-K** [comment]
@openhab/core-maintainers Can you comment here? It's true that the original state description is returned but the channel is managed by the provider, to the restriction is not fulfilled here.

**Comment by cweitkamp** [comment]
I agree on that this implementation of the `DynamicStateDeaceiptionProvider` is a valid use case. And the companies OHC does not considered such a situation. Point is that we have to make sure in some way that no original state description will be returned by any binding if the channel is not manged by the provider because if it does it will accidently overwrite state description of other bindings.

> the equality check in the core should be changed to a reference comparison between the original and returned descriptions

This is probably not possible because most of the bindings extend the `BaseDynamicStateDescriptionProvider` which always builds a new state description instance to provide transportation features for dynamic state options and patterns.

**Comment by cpmeister** [comment]
>>the equality check in the core should be changed to a reference comparison between the original and returned descriptions
>
> This is probably not possible because most of the bindings extend the BaseDynamicStateDescriptionProvider which always builds a new state description instance to provide transportation features for dynamic state options and patterns.

Why would them always building a new dynamic state cause problems, that is exactly what you want them to do, no?
The code change in the core should be simple:
```
            StateDescription stateDescription = provider.getStateDescription(channel, originalStateDescription, locale);
            if (stateDescription != null) {
                if (stateDescription == originalStateDescription) {
                    logger.error(
                            "Dynamic state description matches original state description. DynamicStateDescriptionProvider implementations must never return the original state description. {} has to be fixed.",
                            provider.getClass());
                } else {
                    return stateDescription;
                }
            }
```

This would guarantee that the dynamic providers are not returning the originalStateDescription that is passed in as a parameter. Any returned non-null description after the reference comparison would be guaranteed to have been intentionally  supplied by the provider.

**Comment by cweitkamp** [comment]
Yes, I was talking nonsense yesterday. I will do some test later this day.

**Comment by cweitkamp** [comment]
I submitted https://github.com/openhab/openhab-core/pull/1817 to fix #8845. This PR will not be needed anymore.

**Pull request closed without merging**
