### PR TITLE
[freeboxos] Remove unneeded thing config parameter

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lsiepel** [comment]
I did not check and don’t see a context,  but this is not used in code anywhere?

**Comment by lolodomo** [comment]
> this is not used in code anywhere?

No, no use found.

**Review by lsiepel — APPROVED** [review]
LGTM, thanks

**Comment by clinique** [comment]
@lolodomo : searched also and did not find any usage. Weird. Can't remember what I had in mind on this 3 years ago.

**Pull request merged**
