### PR TITLE
[hue] Changing the default color mode from HS to XY

### LINKED ISSUE #10159: [hue] [zigbee] openhab does not change color on a bulb or zone, if the bulb or zone is in white mode
OpenHAB 2.5.12

When changing the color on a zone, room or bulb in OpenHAB using the PaperUI or similar, and if the color bulb is in warm white/white mode, the change of color is ignored or in some cases a random white color is selected. 

This behaviour was not the case in early versions of 2.5. It's been a while since I used/tested it.

I'm not sure, if #9741 refers to the same issue or a similar cause, but I feel, that when one sets a color or a warm white tone in OpenHAB, OpenHAB should be able to switch the bulb to the correct mode first, if needed.

If I use the Hue App (or equivalent) and set the bulb, room or zone to a color first, then OpenHAB will correctly set colors.

/M

### PR DESCRIPTION
**Pull request by gkunz**
Some hue compatible bulbs, such as the TuYa TS0505A and its re-labeled
versions (e.g. Lidl, Aldi) do not work with control input in HS (hue
staturation) color mode. This color mode however is the implicit
default used by the hue binding. As a result, when trying to change
the color of such a bulb from color temperature (CT) mode to a color
mode, the bulb ignores the input and the light does not change.

This change switches the default color mode from HS to XY.

Fixes #10159

Signed-off-by: Georg Kunz <der.schorsch@gmail.com>

### CODE REVIEW

**Comment by gkunz** [comment]
Hi @cweitkamp,
it would be very appreciated if you could take a look at this PR and let me know if this approach is worth pursuing.
Thanks a lot.
Georg

**Comment by cweitkamp** [comment]
@gkunz Thanks for your contribution and the reminder. I will look into this soon. Did not find the time for it yet.

**Comment by gkunz** [comment]
> @gkunz Thanks for your contribution and the reminder. I will look into this soon. Did not find the time for it yet.

No worries. Thank you!

**Comment by Trickx** [comment]
I have a similar issue with one of my non-Philips HUE LED strips.
In the PR, I saw th followig override:
`private static final Map<String, ColorMode> overwritePreferredColorModePerModel = Map.of("TS0505B", ColorMode.XY);`
I want to give it a try.
How may I identify the required identifier like "TS0505B" for my light strip?
A query to my light via the HUE API results in:

```
{
	"state": {
		"on": true,
		"bri": 254,
		"hue": 33314,
		"sat": 254,
		"effect": "none",
		"xy": [
			0.2061,
			0.2621
		],
		"ct": 450,
		"alert": "select",
		"colormode": "xy",
		"mode": "homeautomation",
		"reachable": true
	},
	"swupdate": {
		"state": "notupdatable",
		"lastinstall": "2020-03-28T16:52:14"
	},
	"type": "Extended color light",
	"name": "Bibliothek",
	"modelid": "RGB-CCT",
	"manufacturername": "Sunricher",
	"productname": "Extended color light",
	"capabilities": {
		"certified": false,
		"control": {
			"colorgamuttype": "other",
			"ct": {
				"min": 155,
				"max": 450
			}
		},
		"streaming": {
			"renderer": false,
			"proxy": false
		}
	},
	"config": {
		"archetype": "huelightstrip",
		"function": "mixed",
		"direction": "omnidirectional"
	},
	"uniqueid": "ec:1b:bd:ff:fe:98:6f:ab-01",
	"swversion": "2.5.3_r47"
}
```

**Comment by cweitkamp** [comment]
Adding this vendor map increases potential effort for maintaining this binding, e.g. when new lights / models / vendors have to be added. In https://github.com/openhab/openhab-addons/pull/10137 I removed such a map from this binding to be not that strict.

In https://github.com/openhab/openhab-addons/issues/10159#issuecomment-814787490 you suggested a second approach to handle this issue by switching from currently preferred HS color mode to XY. I did a brief test with my Hue bulbs and all of them accepted color settings in XY regardless if they are in HS or CT color mode. From my personal feeling we should go for that.

https://github.com/openhab/openhab-addons/blob/858ef65aef0f0ed18fb969ea90050f9adc1be34e/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java#L71-L72

has to be changed accordingly. This change might solve #9741 in advance.

**Comment by Trickx** [comment]
I can confirm. My original Philips light strip accepts all color modes.
The Sunricher only "CT" and "XY".
I will adapt the code snippet, rebuild, test and report.
Thank you.

**Comment by gkunz** [comment]
@cweitkamp thank you for the feedback. I didn't dare to create a PR which changes the global default, since I cannot judge the implications for all bulbs out there, but I am fine with this approach. I can modify the PR accordingly.

@Trickx I believe the is no means in the hue API to read the supported color modes. There is some functionality like this when using the Zigbee binding, but there seems to be an issue with some bulbs reporting support for HS mode despite not working well with this mode (see [another discussion](https://community.openhab.org/t/oh2-cant-set-color-on-bulbs-from-certain-manufacturers/117856)).

To answer your initial question (for completeness), it is the modelId - "RGB-CCT" in your case - which I used for the vendor map. Doesn't matter though if we change the global default.

**Comment by Trickx** [comment]
@gkunz and @cweitkamp thank you for your comments and instructions.
I rebuild the hue binding with modified defaults set to XY color mode according to:
 
```
- StateUpdate stateUpdate = ColorMode.XY.equals(lightState.getColorMode()) ? toXYColorLightState(hsbType)
-                : toHSBColorLightState(hsbType);

+  StateUpdate stateUpdate = ColorMode.XY.equals(lightState.getColorMode()) ? toXYColorLightState(hsbType)
+                : toXYColorLightState(hsbType);

```
I can confirm this fixes the issue I had with my Sunricher Zigbee LED Controller
https://www.sunricher.com/dim-cct-rgbw-rgb-cct-4-in-1-constant-voltage-zigbee-led-controller-sr-zg1029-5c.html
It supports RGB and CCT. After setting a color temperatur openHAB failed to set a color, because HSB was used.
The Sunricher only accepts XY command for the color.

I wonder whether the UI always calls:
`StateUpdate toColorLightState(HSBType hsbType, State lightState)`

If there is a chance the UI calls the following method directly, the Sunricher LED controller will fail:
`StateUpdate toHSBColorLightState(HSBType hsbType)`

**Comment by cweitkamp** [comment]
@Trickx Sounds good. Thanks for testing.

> I wonder whether the UI always calls:
StateUpdate toColorLightState(HSBType hsbType, State lightState)

No, it does not. The UI only sends commands to bindings which are handled by the related `ThingHandler` in the `handleCommand(ChannelUID, Command)` method.

**Comment by gkunz** [comment]
Please keep this closed and do not merge.

**Comment by cweitkamp** [comment]
We have been informed and agree to the deletion of the pull request.

//CC @openhab/add-ons-maintainers

**Pull request closed without merging**
