### PR TITLE
[http] Add spaces-in-url info

### PR DESCRIPTION
**Pull request by digitlength**
Unsigned - minor mod exemption

### CODE REVIEW

**Comment by J-N-K** [comment]
Can you explain why this should be added? I do not fully understand it.

**Comment by digitlength** [comment]
> Can you explain why this should be added? I do not fully understand it.

From this thread:

https://community.openhab.org/t/solved-oh3-http-binding-creating-request-failed/112122

This first clue from namracer

https://community.openhab.org/t/solved-oh3-http-binding-creating-request-failed/112122/8

Unsuccessful attempts:

https://community.openhab.org/t/solved-oh3-http-binding-creating-request-failed/112122/9

Successful attempt:
https://community.openhab.org/t/solved-oh3-http-binding-creating-request-failed/112122/10

**Comment by Hilbrand** [comment]
I would think this solution is specific for the problem you encountered and the server you send the query to expects `+` instead of the url escaped spaces `%20`. So I don't think this should be a generic recommendation in documentation.

**Comment by digitlength** [comment]
> I would think this solution is specific for the problem you encountered and the server you send the query to expects `+` instead of the url escaped spaces `%20`. So I don't think this should be a generic recommendation in documentation.

I am not the OP of the thread.

Here they state that they used the original URL with `%20` to successfully extract the data using a browser, so presumably this isn't about the server?

https://community.openhab.org/t/solved-oh3-http-binding-creating-request-failed/112122/3

Let's put this another way: is the binding capable of handling url's with `%20` in them?

**Comment by J-N-K** [comment]
No. And it's a bug.

**Pull request closed without merging**
