### PR TITLE
[mielecloud] Remove e-mail parameter validation

### LINKED ISSUE #11050: [mielecloud] E-Mail check is not RFC compliant
The mail address syntax check is not RFC compliant at all. It rejects valid mail addresses for no reason.
Miele simply uses `<input type="email">` and there is no reason to be more restrictive here...

### PR DESCRIPTION
**Pull request by BjoernLange**
Fixes #11050.

Signed-off-by: Björn Lange <bjoern.lange@tu-dortmund.de>

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thank you!

**Comment by kaikreuzer** [comment]
@BjoernLange The [PR build failed](https://ci.openhab.org/job/PR-openHAB-Addons/5127/) due to an error in the integration tests. Do they succeed locally for you?

**Comment by BjoernLange** [comment]
@kaikreuzer Yes, they do succeed locally. All failing tests concern the configuration UI and assume that it is available under `http://127.0.0.1:8080/mielecloud`.

**Comment by kaikreuzer** [comment]
I'll restart the PR build and see if it was just a temporary hiccup.

**Comment by kaikreuzer** [comment]
Hooray, it's green 🎉

**Pull request merged**
