### PR TITLE
Added support for publishing ChannelDescriptionChangedEvents

### PR DESCRIPTION
**Pull request by lolodomo**
Pack 2

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Review by clinique — APPROVED** [review]
LGTM for VolvoOnCall binding

**Review by hmerk — APPROVED** [review]
LGTM for Intesis

**Review by kaikreuzer — APPROVED** [review]
Build now succeeded as well. Many thanks!

**Comment by lolodomo** [comment]
I will produce a last PR this evening for bindings not yet fixed (around 10).

**Pull request merged**
