### PR TITLE
[vitotronic] Add channel "currentmode" to "circuit" thing

### PR DESCRIPTION
**Pull request by Fejitatete**

### CODE REVIEW

**Comment by Fejitatete** [comment]
Signed-off-by: Fejitatete <fejitatete@msn.com>

**Comment by Fejitatete** [comment]
F...k, don't know how add the signature msg. Help plz :s

**Comment by jlaur** [comment]
@Fejitatete - what is the intention behind this PR? I see a channel added in the channel declarations, but as far as I can see it references a non-existing channel type and doesn't have any code to update it? How did you test this?

**Comment by Fejitatete** [comment]
@jlaur , you're right, I forgot to add this part.

**Pull request closed without merging**
